### ISSUE TITLE
[MNG-473] m2 fails if user.home contains $ character

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2607]
**[Max Muermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=max2)** opened **[MNG-473](https://issues.apache.org/jira/browse/MNG-473?redirect=false)** and commented

If the user.home path contains the $ character at the end, the string replacement in org.apache.maven.settings.DefaultMavenSettingsBuilder.getSettingsFile() fails with a StringIndexOutOfBoundsException:

java.lang.StringIndexOutOfBoundsException: String index out of range: 22
at java.lang.String.charAt(String.java:558)
at java.util.regex.Matcher.appendReplacement(Matcher.java:704)
at java.util.regex.Matcher.replaceAll(Matcher.java:806)
at java.lang.String.replaceAll(String.java:2000)
at org.apache.maven.settings.DefaultMavenSettingsBuilder.getSettingsFile(DefaultMavenSettingsBuilder.java:124)
...

If the $ character occurs not at the end of the path, an IllegalArgumentException: Illegal Group Reference is thrown.

proposed fix:

add

userHome = userHome.replaceAll("\\$", "\\\\\\$");

to the getSettingsFile() before

path = path.replaceAll("\\$\{user.home\}", userHome);

This results in $ characters being properly escaped.

---

**Affects:** 2.0-alpha-1

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

added the proposed fix, for now.

This is sort of a hint that we need a better solution for this in general...not just a patch adding an additional layer of regexp. If this solves the immediate problem, we can revisit this as more of a design issue later, and come up with a replacement.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

closing, with the current fix. we can re-address this later in another issue, if necessary.
