### ISSUE TITLE
[MNG-419] Setting snapshotPolicy to never throws a NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2617]
**[Malcolm Wong Ho](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aardvark)** opened **[MNG-419](https://issues.apache.org/jira/browse/MNG-419?redirect=false)** and commented

Setting snapshotPolicy to 'never' for the central pluginRepository in pom.xml, then executing an m2 comman eg. m2 clean:clean

Sample pom.xml :
\<pluginRepositories>
\<pluginRepository>
\<id>central\</id>
\<name>central\</name>
\<url>http://repo1.maven.org/maven2\</url>
\<snapshotPolicy>never\</snapshotPolicy>
\<layout>default\</layout>
\</pluginRepository>
\</pluginRepositories>

Exception :

java.lang.NullPointerException
at org.apache.maven.artifact.transform.AbstractVersionTransformation.resolveVersion(AbstractVersionTransformation.java:140)
at org.apache.maven.artifact.transform.ReleaseArtifactTransformation.transformForResolve(ReleaseArtifactTransformation.java:52)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:99)
at org.codehaus.plexus.DefaultArtifactEnabledContainer.addComponent(DefaultArtifactEnabledContainer.java:104)
at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginManager.java:285)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:241)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:389)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.configureMojo(DefaultLifecycleExecutor.java:337)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.processGoals(DefaultLifecycleExecutor.java:135)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:90)
at org.apache.maven.DefaultMaven.processProject(DefaultMaven.java:253)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:246)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

---

**Affects:** 2.0-alpha-2

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I can't reproduce this. Brett, can you?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

changing the subject of the error, since the plugin update policy is different than the snapshotPolicy on the plugin repository...

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

nope, didn't get to try yet. did you try with alpha-2 itself? If it fails, there and works in alpha-3-SNAP, mark as fixed, otherwise, cannot reproduce. Thanks!
