### ISSUE TITLE
[MNG-267] m2 -version leads to ugly exception

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2693]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** opened **[MNG-267](https://issues.apache.org/jira/browse/MNG-267?redirect=false)** and commented

C:\tmp>m2 -version

---

constituent[0]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/commons-cli-1.0-beta-2.jar
constituent[1]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/marmalade-core-1.0-alpha-2.jar
constituent[2]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/maven-artifact-2.0-20050407.164450-2.jar
constituent[3]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/maven-core-2.0-SNAPSHOT.jar
constituent[4]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/maven-model-2.0-20050407.164450-2.jar
constituent[5]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/maven-monitor-2.0-20050407.164450-2.jar
constituent[6]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/maven-plugin-2.0-20050407.164450-2.jar
constituent[7]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/maven-script-marmalade-2.0-20050407.164450-2.jar
constituent[8]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/maven-settings-2.0-20050407.164450-2.jar
constituent[9]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/plexus-container-artifact-1.0-alpha-2.jar
constituent[10]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/plexus-i18n-1.0-beta-3.jar
constituent[11]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/plexus-marmalade-factory-1.0-alpha-2.jar
constituent[12]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/wagon-http-lightweight-1.0-alpha-2.jar
constituent[13]: file:/C:/PROGRA~1/APACHE~1/MAVEN-~1.0-S/bin/../lib/wagon-provider-api-1.0-alpha-2.jar

---

org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -e
at org.apache.commons.cli.Parser.processOption(Parser.java:129)
at org.apache.commons.cli.Parser.parse(Parser.java:53)
at org.apache.commons.cli.Parser.parse(Parser.java:22)
at org.apache.maven.cli.MavenCli$CLIManager.parse(MavenCli.java:344)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)
C:\tmp>

---

**Issue Links:**
- [MNG-122](https://issues.apache.org/jira/browse/MNG-122) clean up of exception handling, error reporting and logging

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

Of course I know that it's --version! :-) Sorry emmanuel but my point is not about whether to type "m2 --version" or "m2 -version"!!

Try reading the stack trace, you'll see that it's wrong in several instances:
- first there are lots of ugly stuff printed on the screen that should definitely not be there
- second the exception has nothing to do with what I wrote. It says something about the "-e" flag which I have not passed
