### ISSUE TITLE
[MNG-666] need to be able to operate on a Maven 1 repository

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2719]
**[Davy Toch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dtoch)** opened **[MNG-666](https://issues.apache.org/jira/browse/MNG-666?redirect=false)** and commented

I have an ANT script using maven antlib (alpha-3) as follows:

...

\<target name="getdeps">
\<artifact:remoteRepository
id="remote.repository" url="http://172.16.40.249/ourrepo" layout="legacy"/>

    <artifact:dependencies verbose="true">
      <remoteRepository refid="remote.repository"/>
      <dependency groupId="sis2" artifactId="sis2-common" version="0.1"/>
    </artifact:dependencies>

\</target>

...

The central repository contains only artifacts with model-3.0.0 POMs (generated by Maven 1.1)

However when executing the ANT target I get the following exception:

--- Nested Exception ---
org.apache.maven.artifact.resolver.TransitiveArtifactResolutionException: Unable to read the metadata file
sis2:sis2-common:0.1:jar

from the specified remote repositories:
http://172.16.40.249/ourrepo
Path to dependency:
1) unspecified:unspecified:jar:0.0

   at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:164)
   at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:66)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:173)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:199)
   at org.apache.maven.artifact.ant.DependenciesTask.execute(DependenciesTask.java:115)
   at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)
   at org.apache.tools.ant.Task.perform(Task.java:364)
   at org.apache.tools.ant.Target.execute(Target.java:341)
   at org.apache.tools.ant.Target.performTasks(Target.java:369)
   at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1216)
   at org.apache.tools.ant.Project.executeTarget(Project.java:1185)
   at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:40)
   at org.apache.tools.ant.Project.executeTargets(Project.java:1068)
   at org.apache.tools.ant.Main.runBuild(Main.java:668)
   at org.apache.tools.ant.Main.startAnt(Main.java:187)
   at org.apache.tools.ant.launch.Launcher.run(Launcher.java:246)
   at org.apache.tools.ant.launch.Launcher.main(Launcher.java:67)

Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:88)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:151)
... 16 more
Caused by: org.apache.maven.project.ProjectBuildingException: Failed to validate POM for 'Artifact [sis2:sis2-common:pom:0.1]'.

Reason(s):
[0]  'modelVersion' is missing.

    at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:439)
    at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:317)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:220)
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:81)
    ... 17 more

The problem is that in the class DefaultModelValidator (apparently always called when retrieving a dependency) a check is done to verify whether the element \<modelVersion> is present in the POM. However for model-3.0.0 POMs this element isn't defined in the XSD!

Regards,
Davy Toch

---

**Affects:** 2.0-alpha-3

**Issue Links:**
- [MANTTASKS-126](https://issues.apache.org/jira/browse/MANTTASKS-126) Exception "parser must be on START_TAG or TEXT to read text" in MavenXpp3Reader for model-3.0.0 POMs.
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

will handle as one

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

need to (a) allow maven-artifact to read v3.0.x poms, and (b) avoid recursion when using v3.0.x poms.

**Comment by jira-importer** [comment]
**[Davy Toch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dtoch)** commented

Can't you just ignore v3.0.x POM's when layout="legacy", meaning that you don't need a POM for the dependency in order to retrieve it?

This was already the case in Maven 1.x. Remember that there is still a large portion of jars, wars, ... that aren't created by Maven and that have no POM (BEA WebLogic jars, IBM WebSphere jars, ...). Manually creating a POM for these dependencies just in order to be retrievable by the Maven artifact handler just seems stupid.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

sorry, was moving through these a little too fast, I guess...

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

see it0059
