### ISSUE TITLE
[MNG-277] When a download is failing the error message is confusing.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2720]
**[Trygve Laugstøl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trygvis@inamo.no)** opened **[MNG-277](https://issues.apache.org/jira/browse/MNG-277?redirect=false)** and commented

When I was trying execute "m2 install" in a directory and I was missing a jar file locally and the same file was missing from the remote repository Maven tried to download it as expected, but when it couldn't find the remote file I got the following exception. Note the path in the stack trace versus the one in the log output.

[INFO] maven-core: using locally installed snapshot
[INFO] plexus-mail-sender-api: resolved to version 1.0-alpha-1-20050409.172553-2 from local repository
[INFO] maven-scm-api: resolved to version 1.0-alpha-1-20050407.203912-2 from local repository
[INFO] maven-scm: resolved to version 1.0-alpha-1-20050407.203912-3 from local repository
[INFO] maven-settings: resolved to version 2.0-20050407.164450-2 from local repository
[INFO] maven-plugin: resolved to version 2.0-20050407.164450-2 from local repository
[INFO] maven-monitor: resolved to version 2.0-20050407.164450-2 from local repository
Downloading: plexus/plexus-mail-sender-api/1.0-alpha-1-SNAPSHOT/plexus-mail-sender-api-1.0-alpha-1-20050409.172553-2.jar
[WARNING] Unable to get resource from repository http://test.maven.codehaus.org/maven2/
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[ERROR] Cause:
org.apache.maven.plugin.PluginExecutionException: Unable to resolve required dependencies for goal
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:375)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeMojo(DefaultLifecycleExecutor.java:393)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executePhase(DefaultLifecycleExecutor.java:362)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:138)
at org.apache.maven.DefaultMaven.processProject(DefaultMaven.java:207)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:131)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:233)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: The artifact is not present locally as:

plexus/plexus-mail-sender-api/1.0-alpha-1-SNAPSHOT/plexus-mail-sender-api-1.0-alpha-1-SNAPSHOT.jar

or in any of the specified remote repositories:

http://test.maven.codehaus.org/maven2/
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:131)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:197)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:723)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:355)
... 14 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:196)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:119)
... 17 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Sun Apr 10 01:21:48 CEST 2005
[INFO] Final Memory: 1M/3M
[INFO] ------------------------------------------------------------------------

---

**Issue Links:**
- [MNG-122](https://issues.apache.org/jira/browse/MNG-122) clean up of exception handling, error reporting and logging

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this also gets swallowed for transfer failed, checksum failed, etc
