### ISSUE TITLE
[MNG-590] NPE in org.apache.maven.artifact.DefaultArtifact.hashCode

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2799]
**[Steve Loughran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=steve_l)** opened **[MNG-590](https://issues.apache.org/jira/browse/MNG-590?redirect=false)** and commented

Getting an NPE when attempting to write a POM/. Now, an NPE in a hashCode usually means a gulf between the classes expectatoins and what fields are configured. I dont see anything obvious missing from my pom, though of course I am just learning maven. Either the hashcode operator needs fixing to handle missing data, or something upstream should fail with a meaningful error.

java.lang.NullPointerException
at org.apache.maven.artifact.DefaultArtifact.hashCode(DefaultArtifact.java:193)
at java.util.HashMap.hash(HashMap.java:264)
at java.util.HashMap.put(HashMap.java:382)
at java.util.HashSet.add(HashSet.java:194)
at org.apache.maven.artifact.factory.DefaultArtifactFactory.createArtifacts(DefaultArtifactFactory.java:44)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:266)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:198)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:129)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:117)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:266)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:170)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:102)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:233)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)constituent
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

---

**Affects:** 2.0-alpha-3

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12711570/pom.xml) (_1.44 kB_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

avoiding NPE.

The problem is that the POM ignores all attributes, so it is effectively \<dependency />, which has no group, artifact or version.
