### ISSUE TITLE
[MNG-533] m2 -v throws NPE

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2849]
**[Bartosz Rempuszewski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brempusz)** opened **[MNG-533](https://issues.apache.org/jira/browse/MNG-533?redirect=false)** and commented

...>svn update
...>m2-bootstrap-all.bat
...>m2 -v

---

constituent[0]: file:/c:/java/maven2/lib/maven-profile-2.0-alpha-3.jar
constituent[1]: file:/c:/java/maven2/lib/commons-validator-1.1.4.jar
constituent[2]: file:/c:/java/maven2/lib/maven-plugin-api-2.0-alpha-3.jar
constituent[3]: file:/c:/java/maven2/lib/maven-artifact-manager-2.0-alpha-3.jar
constituent[4]: file:/c:/java/maven2/lib/wagon-ssh-1.0-alpha-4.jar
constituent[5]: file:/c:/java/maven2/lib/maven-settings-2.0-alpha-3.jar
constituent[6]: file:/c:/java/maven2/lib/wagon-file-1.0-alpha-4.jar
constituent[7]: file:/c:/java/maven2/lib/wagon-http-lightweight-1.0-alpha-4.jar
constituent[8]: file:/c:/java/maven2/lib/maven-reporting-api-2.0-alpha-3.jar
constituent[9]: file:/c:/java/maven2/lib/jline-0.9.1.jar
constituent[10]: file:/c:/java/maven2/lib/maven-model-2.0-alpha-3.jar
constituent[11]: file:/c:/java/maven2/lib/maven-artifact-2.0-alpha-3.jar
constituent[12]: file:/c:/java/maven2/lib/wagon-provider-api-1.0-alpha-4.jar
constituent[13]: file:/c:/java/maven2/lib/doxia-core-1.0-alpha-3.jar
constituent[14]: file:/c:/java/maven2/lib/maven-project-2.0-beta-1-SNAPSHOT.jar
constituent[15]: file:/c:/java/maven2/lib/maven-plugin-registry-2.0-alpha-3.jar
constituent[16]: file:/c:/java/maven2/lib/commons-cli-1.0-beta-2.jar
constituent[17]: file:/c:/java/maven2/lib/oro-2.0.7.jar
constituent[18]: file:/c:/java/maven2/lib/maven-plugin-descriptor-2.0-alpha-3.jar
constituent[19]: file:/c:/java/maven2/lib/plexus-input-handler-1.0-alpha-2.jar
constituent[20]: file:/c:/java/maven2/lib/maven-monitor-2.0-alpha-3.jar
constituent[21]: file:/c:/java/maven2/lib/jsch-0.1.17.jar
constituent[22]: file:/c:/java/maven2/lib/maven-core-2.0-beta-1-SNAPSHOT.jar

---

java.lang.NullPointerException
at java.io.Reader.\<init>(Reader.java:61)
at java.io.InputStreamReader.\<init>(InputStreamReader.java:80)
at java.util.Properties.load(Properties.java:266)
at org.apache.maven.cli.MavenCli.showVersion(MavenCli.java:422)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:143)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

---

**Affects:** 2.0-alpha-3

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Fixed.
