### ISSUE TITLE
[MNG-437] Improve version = null message in DefaultArtifact

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2933]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** opened **[MNG-437](https://issues.apache.org/jira/browse/MNG-437?redirect=false)** and commented

Would be nice to get something like artifact version cannot be null for g:a instead of this;

constituent[0]: file:/home/jvanzyl/m2/lib/commons-validator-1.1.4.jar
constituent[1]: file:/home/jvanzyl/m2/lib/maven-plugin-api-2.0-SNAPSHOT.jar
constituent[2]: file:/home/jvanzyl/m2/lib/bsh-1.3.0.jar
constituent[3]: file:/home/jvanzyl/m2/lib/plexus-bsh-factory-1.0-alpha-6-20050517.080828-1.jar
constituent[4]: file:/home/jvanzyl/m2/lib/plexus-container-artifact-1.0-alpha-4-20050527.013505-1.jar
constituent[5]: file:/home/jvanzyl/m2/lib/maven-settings-2.0-SNAPSHOT.jar
constituent[6]: file:/home/jvanzyl/m2/lib/wagon-http-lightweight-1.0-alpha-3.jar
constituent[7]: file:/home/jvanzyl/m2/lib/maven-reporting-api-2.0-SNAPSHOT.jar
constituent[8]: file:/home/jvanzyl/m2/lib/maven-model-2.0-SNAPSHOT.jar
constituent[9]: file:/home/jvanzyl/m2/lib/maven-script-beanshell-2.0-SNAPSHOT.jar
constituent[10]: file:/home/jvanzyl/m2/lib/maven-artifact-2.0-SNAPSHOT.jar
constituent[11]: file:/home/jvanzyl/m2/lib/wagon-provider-api-1.0-alpha-3.jar
constituent[12]: file:/home/jvanzyl/m2/lib/doxia-core-1.0-alpha-3-SNAPSHOT.jar
constituent[13]: file:/home/jvanzyl/m2/lib/maven-project-2.0-SNAPSHOT.jar
constituent[14]: file:/home/jvanzyl/m2/lib/commons-cli-1.0-beta-2.jar
constituent[15]: file:/home/jvanzyl/m2/lib/maven-script-marmalade-2.0-SNAPSHOT.jar
constituent[16]: file:/home/jvanzyl/m2/lib/marmalade-core-1.0-alpha-3.jar
constituent[17]: file:/home/jvanzyl/m2/lib/oro-2.0.7.jar
constituent[18]: file:/home/jvanzyl/m2/lib/maven-plugin-descriptor-2.0-SNAPSHOT.jar
constituent[19]: file:/home/jvanzyl/m2/lib/plexus-i18n-1.0-beta-4.jar
constituent[20]: file:/home/jvanzyl/m2/lib/maven-monitor-2.0-SNAPSHOT.jar
constituent[21]: file:/home/jvanzyl/m2/lib/plexus-marmalade-factory-1.0-alpha-3.jar
constituent[22]: file:/home/jvanzyl/m2/lib/maven-core-2.0-SNAPSHOT.jar

---

java.lang.NullPointerException: Artifact version cannot be null.
at org.apache.maven.artifact.DefaultArtifact.\<init>(DefaultArtifact.java:92)
at org.apache.maven.artifact.factory.DefaultArtifactFactory.createArtifact(DefaultArtifactFactory.java:69)
at org.apache.maven.artifact.factory.DefaultArtifactFactory.createArtifact(DefaultArtifactFactory.java:39)
at org.apache.maven.project.DefaultMavenProjectBuilder.createArtifacts(DefaultMavenProjectBuilder.java:487)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:296)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:239)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:155)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:144)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:309)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:203)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:111)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:246)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)
Press any key to continue...

---
No further details from [MNG-437](https://issues.apache.org/jira/browse/MNG-437?redirect=false)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

I did a minor fix to allow you to see what the g:a is when the groupId and artifactId are set. But maybe a MalformedArtifactException would be prudent and could be dealt with by the ErrorDiagnoser.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Now displays g:a when the version is null.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I've backed out these changes and put an error diagnoser and RT exception in place instead. This should make diagnosis on the part of the user better, esp. once we can provide the pedigree of the artifact, including the [multiple] places where it was included in the artifact list.

commit to follow.
