### ISSUE TITLE
[MNG-431] Error check for old style pom dependency declarations

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2937]
**[Hiram R. Chirino](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chirino)** opened **[MNG-431](https://issues.apache.org/jira/browse/MNG-431?redirect=false)** and commented

had a dependency like:
\<dependency>
\<id>springframework\</id>
\<artifactId>spring\</artifactId>
\<version>1.1\</version>
\</dependency>
Maven barfed like:
java.lang.NullPointerException
at org.apache.maven.artifact.DefaultArtifact.hashCode(DefaultArtifact.java:197)
at java.util.HashMap.hash(HashMap.java:264)
at java.util.HashMap.put(HashMap.java:382)
at java.util.HashSet.add(HashSet.java:194)
at org.apache.maven.project.DefaultMavenProjectBuilder.createArtifacts(DefaultMavenProjectBuilder.java:475)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:283)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:237)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:153)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:142)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:314)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:203)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:111)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:246)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

---

**Affects:** 2.0-alpha-2

**Issue Links:**
- [MNG-284](https://issues.apache.org/jira/browse/MNG-284) POMs should be validated at the XML level
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

validating at the XML level should correct this
