### ISSUE TITLE
[MNG-389] site:site Exception

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2977]
**[Thomas Van de Velde](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thomas.vdvelde)** opened **[MNG-389](https://issues.apache.org/jira/browse/MNG-389?redirect=false)** and commented

I've build a skeleton project with

m2 archetype:create -DgroupId=org.maven.m2 -DartifactId=Maven2

Then ran site:site for the generated project.

Result:
$ m2 site:site
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Building Maven Quick Start
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] maven-jar-plugin: resolved to version 2.0-alpha-2 from local repository
[INFO] maven-site-plugin: resolved to version 2.0-alpha-1 from local repository
[INFO] [site:site]
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] BUILD ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] Cause:
org.apache.maven.plugin.MojoExecutionException: Error during site generation
at org.apache.maven.doxia.DoxiaMojo.execute(DoxiaMojo.java:181)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.processGoals(Defa
ultLifecycleExecutor.java:169)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:90)
at org.apache.maven.DefaultMaven.processProject(DefaultMaven.java:253)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:246)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

Caused by: java.lang.NullPointerException
at org.codehaus.plexus.util.StringUtils.interpolate(StringUtils.java:206
5)
at org.apache.maven.doxia.DoxiaMojo.getSiteDescriptor(DoxiaMojo.java:283
)
at org.apache.maven.doxia.DoxiaMojo.execute(DoxiaMojo.java:176)
... 14 more

---

**Affects:** 2.0-alpha-2

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

JAson has fixed this

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

I tried this and I still get the same error... is this really fixed?
