### ISSUE TITLE
[MNG-375] 3-level pom plugin config inheritance causes ConcurrentModificationException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2983]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** opened **[MNG-375](https://issues.apache.org/jira/browse/MNG-375?redirect=false)** and commented

The attached project structure causes the following exception:

[mark@mark testproject]$ m2 clean:clean

---

constituent[0]: file:/c:/Program Files/maven-2.0/lib/commons-cli-1.0-beta-2.jar
constituent[1]: file:/c:/Program Files/maven-2.0/lib/doxia-core-1.0-alpha-2-20050507.132213-9.jar
constituent[2]: file:/c:/Program Files/maven-2.0/lib/marmalade-core-1.0-alpha-3-20050504.035023-1.jar
constituent[3]: file:/c:/Program Files/maven-2.0/lib/maven-artifact-2.0-SNAPSHOT.jar
constituent[4]: file:/c:/Program Files/maven-2.0/lib/maven-core-2.0-SNAPSHOT.jar
constituent[5]: file:/c:/Program Files/maven-2.0/lib/maven-model-2.0-SNAPSHOT.jar
constituent[6]: file:/c:/Program Files/maven-2.0/lib/maven-monitor-2.0-SNAPSHOT.jar
constituent[7]: file:/c:/Program Files/maven-2.0/lib/maven-plugin-api-2.0-SNAPSHOT.jar
constituent[8]: file:/c:/Program Files/maven-2.0/lib/maven-plugin-descriptor-2.0-SNAPSHOT.jar
constituent[9]: file:/c:/Program Files/maven-2.0/lib/maven-project-2.0-SNAPSHOT.jar
constituent[10]: file:/c:/Program Files/maven-2.0/lib/maven-reporting-api-2.0-20050507.125719-3.jar
constituent[11]: file:/c:/Program Files/maven-2.0/lib/maven-script-marmalade-2.0-SNAPSHOT.jar
constituent[12]: file:/c:/Program Files/maven-2.0/lib/maven-settings-2.0-SNAPSHOT.jar
constituent[13]: file:/c:/Program Files/maven-2.0/lib/oro-2.0.7.jar
constituent[14]: file:/c:/Program Files/maven-2.0/lib/plexus-container-artifact-1.0-alpha-3-20050422.054920-3.jar
constituent[15]: file:/c:/Program Files/maven-2.0/lib/plexus-i18n-1.0-beta-3.jar
constituent[16]: file:/c:/Program Files/maven-2.0/lib/plexus-marmalade-factory-1.0-alpha-3-20050504.035023-1.jar
constituent[17]: file:/c:/Program Files/maven-2.0/lib/wagon-http-lightweight-1.0-alpha-3-SNAPSHOT.jar
constituent[18]: file:/c:/Program Files/maven-2.0/lib/wagon-provider-api-1.0-alpha-3-SNAPSHOT.jar

---

java.util.ConcurrentModificationException
at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:449)
at java.util.AbstractList$Itr.next(AbstractList.java:420)
at org.apache.maven.project.inheritance.DefaultModelInheritanceAssembler.assemblePluginManagementInheritance(Def
aultModelInheritanceAssembler.java:213)
at org.apache.maven.project.inheritance.DefaultModelInheritanceAssembler.assembleBuildInheritance(DefaultModelIn
heritanceAssembler.java:356)
at org.apache.maven.project.inheritance.DefaultModelInheritanceAssembler.assembleModelInheritance(DefaultModelIn
heritanceAssembler.java:126)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:221)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:153)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:142)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:288)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:177)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:199)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:199)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:230)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

---

**Affects:** 2.0-alpha-2

**Attachments:**
- [testproject.zip](https://issues.apache.org/jira/secure/attachment/12711398/testproject.zip) (_4.26 kB_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

changing "affects for" - works on alpha-1. Is a regression.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

test project works for me. You may have been operating with older code, I recall fixing code in that area last week.

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

I've just:

* checked out the latest code
* cleaned all m2 target directories
* cleaned all ~/.m2/repository/org/**
* rebuilt m2

And I still get the same exception when trying a 'm2 install' on the testproject - any ideas?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I'll try another machine. We are on the same setup though, so I don't know... are you up to stepping into the code?

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

Sure, I'm happy to if you point me in the right direction.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

it would involve setting a breakpoint in the default model assembler and stepping through up to the point of breakage, seeing what was modified just beforehand. I don't see the original being changed, but I may be missing something.

Can you confirm it is broken if you redownload the patch you uploaded? maybe there is a local difference?

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

How strange..  just svn up'ed, cleaned, rebuilt and it all works fine now!  Feel free to close this one down.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

phew! :)
