### ISSUE TITLE
[MNG-393] autogenerate/install doesn't work

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#2992]
**[Malachi de AElfweald](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=malachid)** opened **[MNG-393](https://issues.apache.org/jira/browse/MNG-393?redirect=false)** and commented

Migrating from M1 to M2.

Tried to start with instructions from here:
http://maven.apache.org/maven2/getting-started.html

did: m2 archetype:create -DgroupId=com.mycompany.app -DartifactId=my-app
verified that pom.xml and source files were there

tried: m2 install
crashed with null pointer because jar had nothing to jar because compile said there was no source

added the following to the autogenerated pom.xml:
\<build>
\<sourceDirectory>src/main/java\</sourceDirectory>
\<testSourceDirectory>src/test/java\</testSourceDirectory>
\<directory>target/classes\</directory>
\<outputDirectory>target/dist\</outputDirectory>
\<testOutputDirectory>target/test-classes\</testOutputDirectory>
\</build>

still, 'm2 package', 'm2 compile' and 'm2 install' give same error:

[INFO] ----------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO] ----------------------------------------------------------------------------
[INFO] maven-jar-plugin: resolved to version 2.0-alpha-2 from local repository
[INFO] maven-resources-plugin: resolved to version 2.0-alpha-2 from local repository
[INFO] maven-compiler-plugin: resolved to version 2.0-alpha-2 from local repository
[INFO] maven-surefire-plugin: resolved to version 2.0-alpha-2 from local repository
[INFO] maven-install-plugin: resolved to version 2.0-alpha-2 from local repository
[INFO] [resources:resources]
[INFO] [compiler:compile]
[INFO] No sources to compile
[INFO] [resources:testResources]
[INFO] [compiler:testCompile]
[INFO] No sources to compile
[INFO] [surefire:test]
[INFO] Setting reports dir: target/surefire-reports

---

T E S T S

---

There are no test to run.

Results :
[surefire] Tests run: 0, Failures: 0, Errors: 0

[INFO] [jar:jar]
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[ERROR] Cause:
org.apache.maven.plugin.MojoExecutionException: Error assembling JAR
at org.apache.maven.plugin.jar.JarMojo.execute(JarMojo.java:105)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.processGoals(DefaultLifecycleExecutor.java:169)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:90)
at org.apache.maven.DefaultMaven.processProject(DefaultMaven.java:253)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:246)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)
Caused by: java.lang.NullPointerException
at org.codehaus.plexus.archiver.AbstractArchiver.addFile(AbstractArchiver.java:141)
at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:204)
at org.apache.maven.plugin.jar.JarMojo.execute(JarMojo.java:100)
... 14 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Sun May 15 09:42:21 PDT 2005
[INFO] Final Memory: 1M/3M
[INFO] ------------------------------------------------------------------------

---

**Affects:** 2.0-alpha-2

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Works for me on JDK 5.0_03. Incidentally, I don't know why you chose those output directories. I think you have them back to front :)

I'm speculating that the alpha doesn't work with Java 1.6.0. We have no intention of supporting that until it is closer to release, and if it isn't backwards compat, that's probably a bug on their end :)

**Comment by jira-importer** [comment]
**[Choong Yong Koh](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=choongyong.koh)** commented

Could be that Malachi forgot to change folder into the generated project before running "m2 install".  Happened to me when I tried to follow the same set of instructions at http://maven.apache.org/maven2/getting-started.html
