### ISSUE TITLE
[MNG-350] unable to bootstrap: update in dependcy lost  ArtifactRepository  <-> Repository 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3010]
**[Michael Hinterseher](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mhinterseher)** opened **[MNG-350](https://issues.apache.org/jira/browse/MNG-350?redirect=false)** and commented

I failed to bootstrap during compile:
Resolved version: 1.0-alpha-3-20050422.075233-11
Downloading http://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-alpha-3-SNAPSHOT/wagon-provider-
api-1.0-alpha-3-20050422.075233-11.jar
Compiling sources ...
Compiling 49 source files to C:\org\apache\m2test\m2\maven-artifact\target\classes
C:\org\apache\m2test\m2\maven-artifact\src\main\java\org\apache\maven\artifact\repository\ArtifactRepository.java:71: ca
nnot find symbolRepository
symbol  : constructor (java.lang.String,java.lang.String,org.apache.maven.wagon.authentication.AuthenticationI
nfo)
location: class org.apache.maven.wagon.repository.Repository
super( id, url, authInfo );
^
C:\org\apache\m2test\m2\maven-artifact\src\main\java\org\apache\maven\artifact\deployer\DefaultArtifactDeployer.java:70:
cannot find symbol
symbol  : method getAuthenticationInfo()
location: class org.apache.maven.artifact.repository.ArtifactRepository
if ( deploymentRepository.getAuthenticationInfo() == null )
^
2 errors
Failure executing javac, but could not parse the error:

Exception in thread "main" java.lang.Exception: Compilation error.
at MBoot.compile(MBoot.java:905)
at MBoot.buildProject(MBoot.java:563)
at MBoot.run(MBoot.java:314)
at MBoot.main(MBoot.java:116)
Rebuilding maven2 plugins

Caused by: Changes introduced to Repository constructor were lost/not in the wagon-provider-
api-1.0-alpha-3-20050422.075233-11.jar

---

**Affects:** 2.0-alpha-2

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

sorry, the site its out of date. We moved to Subversion last week, so the code you were using is out of date and won't work with newer snapshots.

svn co http://svn.apache.org/repos/asf/maven/components
