### ISSUE TITLE
[MNG-70] ClassLoader issue when executing the eclipse:eclipse goal

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3083]
**[Cameron Braid](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cameronbraid)** opened **[MNG-70](https://issues.apache.org/jira/browse/MNG-70?redirect=false)** and commented

D:\maven2\src\maven-core>m2 eclipse:eclipse
[INFO] [eclipse:eclipse]

---

constituent[0]: file:/d:/maven2/lib/commons-cli-1.0-beta-2.jar
constituent[1]: file:/d:/maven2/lib/marmalade-core-0.1.jar
constituent[2]: file:/d:/maven2/lib/marmalade-el-ognl-0.1.jar
constituent[3]: file:/d:/maven2/lib/maven-core-2.0-SNAPSHOT.jar
constituent[4]: file:/d:/maven2/lib/maven-model-2.0-SNAPSHOT.jar
constituent[5]: file:/d:/maven2/lib/maven-plugin-2.0-SNAPSHOT.jar
constituent[6]: file:/d:/maven2/lib/ognl-2.5.1.jar
constituent[7]: file:/d:/maven2/lib/plexus-i18n-1.0-beta-3.jar

---

Exception in thread "main" java.lang.VerifyError: (class: org/apache/maven/plugin/eclipse/EclipsePlugin, method: execute signature:
(Lorg/apache/maven/plugin/PluginExecutionRequest;Lorg/apache/maven/plugin/PluginExecutionResponse;)V) Incompatible object argument f
or function call
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:1610)
at java.lang.Class.getConstructor0(Class.java:1922)
at java.lang.Class.newInstance0(Class.java:278)
at java.lang.Class.newInstance(Class.java:261)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:71)
at org.codehaus.plexus.DefaultPlexusContainer.createComponentInstance(DefaultPlexusContainer.java:1182)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:92)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:65)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:166)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:265)
at org.apache.maven.lifecycle.session.MavenSession.lookup(MavenSession.java:112)
at org.apache.maven.lifecycle.goal.MavenGoalExecutionContext.lookup(MavenGoalExecutionContext.java:74)
at org.apache.maven.lifecycle.goal.phase.GoalAttainmentPhase.execute(GoalAttainmentPhase.java:67)
at org.apache.maven.lifecycle.goal.DefaultMavenGoalPhaseManager.execute(DefaultMavenGoalPhaseManager.java:48)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:116)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:86)
at org.apache.maven.MavenCli.main(MavenCli.java:150)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:350)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:290)
at org.codehaus.classworlds.Launcher.main(Launcher.java:433)
D:\maven2\src\maven-core>

---

**Attachments:**
- [maven-eclipse-plugin-fixTests.patch](https://issues.apache.org/jira/secure/attachment/12711367/maven-eclipse-plugin-fixTests.patch) (_1.59 kB_)
- [patch.patch](https://issues.apache.org/jira/secure/attachment/12711369/patch.patch) (_6.50 kB_)

**Comment by jira-importer** [comment]
**[Trygve Laugstøl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trygvis@inamo.no)** commented

Is this still a issue for you? It's probably beause of a non-successful build of maven 2 causing some of the jars to be newer that others.
