### ISSUE TITLE
[MNG-26] The jar mojo dies is the /target directory doesn't exist.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3159]
**[Trygve Laugstøl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trygvis@inamo.no)** opened **[MNG-26](https://issues.apache.org/jira/browse/MNG-26?redirect=false)** and commented

[ERROR] Cause:
java.lang.IllegalStateException: basedir /tmp/continuum/ff808081fdc9a28000fdc9a2e1950001/maven-wagon/target/classes does not exist
at org.codehaus.plexus.util.DirectoryScanner.scan(DirectoryScanner.java:539)
at org.apache.maven.plugin.jar.AbstractJarMojo.addDirectory(AbstractJarMojo.java:134)
at org.apache.maven.plugin.jar.JarMojo.execute(JarMojo.java:84)
at org.apache.maven.lifecycle.phase.GoalAttainmentPhase.execute(GoalAttainmentPhase.java:67)
at org.apache.maven.lifecycle.DefaultMavenLifecycleManager.execute(DefaultMavenLifecycleManager.java:49)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:110)
at org.codehaus.continuum.builder.maven2.Maven2ContinuumBuilder.build(Maven2ContinuumBuilder.java:265)
at org.codehaus.continuum.BuilderThread.run(BuilderThread.java:60)
at java.lang.Thread.run(Thread.java:534)

---
No further details from [MNG-26](https://issues.apache.org/jira/browse/MNG-26?redirect=false)

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Fixed.
