### ISSUE TITLE
[MNG-1848] Cannot execute "mvn clean" on plugins

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3191]
**[Grzegorz Slowikowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gslowikowski)** opened **[MNG-1848](https://issues.apache.org/jira/browse/MNG-1848?redirect=false)** and commented

"mvn clean" on plugins trunk throws error. Eclipse plugin uses Surefire in its pom, and in the reactor Surefire is prior to Eclipse, but "clean" does not create Surefire artifact. Workaround is to "install" Surefire first, and then "clean" all plugins ;-)

Eclipse plugin pom:
...
\<build>
\<plugins>
\<plugin>
\<artifactId>maven-surefire-plugin\</artifactId>
\<configuration>
\<excludes>
\<exclude>**/Abstract*TestCase.java\</exclude>
\<exclude>**/EclipsePluginMasterProjectTest.java\</exclude>
\</excludes>
\</configuration>
\</plugin>
\</plugins>
\</build>
...

Execution log:
...
[INFO] ----------------------------------------------------------------------------
[INFO] Building Maven Eclipse Plugin
[INFO]    task-segment: [clean]
[INFO] ----------------------------------------------------------------------------
[DEBUG] Skipping disabled repository central
[DEBUG] maven-surefire-plugin: using locally installed snapshot
[DEBUG] Trying repository snapshots
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.1.2-SNAPSHOT/maven-surefire-plugin-2.1.2-SNAPSHOT.jar
[WARNING] Unable to get resource from repository snapshots (http://snapshots.maven.codehaus.org/maven2)
[DEBUG] Skipping disabled repository central
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ----------------------------------------------------------------------------
[INFO] A required plugin was not found: Plugin could not be found - check that the goal name is correct: Unable to download the artifact from any repository

org.apache.maven.plugins:maven-surefire-plugin:maven-plugin:2.1.2-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2)

org.apache.maven.plugins:maven-surefire-plugin:maven-plugin:2.1.2-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2)

[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: A required plugin was not found: Plugin could not be found - check that the goal name is correct: Unable to download the artifact from any repository

org.apache.maven.plugins:maven-surefire-plugin:maven-plugin:2.1.2-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2)

org.apache.maven.plugins:maven-surefire-plugin:maven-plugin:2.1.2-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:460)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.PluginNotFoundException: Plugin could not be found - check that the goal name is correct: Unable to download the artifact from any repository

org.apache.maven.plugins:maven-surefire-plugin:maven-plugin:2.1.2-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2)

org.apache.maven.plugins:maven-surefire-plugin:maven-plugin:2.1.2-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2)

    at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:246)
    at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:182)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1174)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifecycle(DefaultLifecycleExecutor.java:1139)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:948)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:450)
    ... 14 more

Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:260)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:124)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:209)
... 19 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 29 seconds
[INFO] Finished at: Thu Dec 15 16:24:22 CET 2005
[INFO] Final Memory: 3M/6M
[INFO] ------------------------------------------------------------------------

---

**Affects:** 2.0.1

**Issue Links:**
- [MNG-2036](https://issues.apache.org/jira/browse/MNG-2036) The clean plugin requires dependent plugins defined in a project's pom.xml to be in the repository before it can perform a clean
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

other issue describes problem
