### ISSUE TITLE
[MNG-1718] deploy to scp repository hangs forever

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3200]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** opened **[MNG-1718](https://issues.apache.org/jira/browse/MNG-1718?redirect=false)** and commented

After upgrading from alpha-3 to beta-1, deploy to my scp repository hangs forever (alpha-3 works fine with identical settings).

A thread on maven-users concering this issue starts at
http://marc.theaimsgroup.com/?l=turbine-maven-user&m=112721905414020&w=2

Here's a  thread dump taken while deploy hangs:

---

[INFO] [deploy:deploy]
[INFO] Retrieving previous build number from internal
Full thread dump Java HotSpot(TM) Client VM (1.4.2-54 mixed mode):

"Connect thread maven.example.com session" prio=5 tid=0x005651b0 nid=0x1e20000 runnable [f0c89000..f0c89ac0]
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:129)
at com.jcraft.jsch.IO.getByte(Unknown Source)
at com.jcraft.jsch.Session.read(Unknown Source)
at com.jcraft.jsch.Session.run(Unknown Source)
at java.lang.Thread.run(Thread.java:552)

"Signal Dispatcher" daemon prio=10 tid=0x00508210 nid=0x1823a00 waiting on condition [0..0]

"Finalizer" daemon prio=8 tid=0x00506ca0 nid=0x1810800 in Object.wait() [f0a04000..f0a04ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x657178d0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:111)
- locked <0x657178d0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:127)
  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=0x00506970 nid=0x1803e00 in Object.wait() [f0983000..f0983ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x65717938> (a java.lang.ref.Reference$Lock)
  at java.lang.Object.wait(Object.java:429)
  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:115)
- locked <0x65717938> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x00500e30 nid=0x1804600 in Object.wait() [f07fe000..f08002c8]
at java.lang.Object.wait(Native Method)
- waiting on <0x650a5f08> (a com.jcraft.jsch.Channel$MyPipedInputStream)
  at java.io.PipedInputStream.read(PipedInputStream.java:229)
- locked <0x650a5f08> (a com.jcraft.jsch.Channel$MyPipedInputStream)
  at org.apache.maven.wagon.providers.ssh.ScpWagon.checkAck(ScpWagon.java:614)
  at org.apache.maven.wagon.providers.ssh.ScpWagon.get(ScpWagon.java:407)
  at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:325)
  at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadata(DefaultWagonManager.java:256)
  at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:198)
  at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:183)
  at org.apache.maven.artifact.transform.SnapshotTransformation.resolveLatestSnapshotBuildNumber(SnapshotTransformation.java:130)
  at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:75)
  at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForDeployment(DefaultArtifactTransformationManager.java:58)
  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:62)
  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:53)
  at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:142)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:357)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:479)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:452)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:438)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:131)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:186)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

"VM Thread" prio=5 tid=0x005061f0 nid=0x1804e00 runnable

"VM Periodic Task Thread" prio=10 tid=0x00508150 nid=0x1823600 waiting on condition
"Exception Catcher Thread" prio=10 tid=0x00500f90 nid=0x1804a00 runnable

---

**Affects:** 2.0-beta-1

**Issue Links:**
- [WAGON-191](https://issues.apache.org/jira/browse/WAGON-191) deploy to scp repository hangs forever
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

Using OSX 10.4.3, java 1.4.2_09 on client,
OpenSSH_3.8.1p1, OpenSSL 0.9.7g 11 Apr 2005

server is OSX 10.3.9
OpenSSH_3.6.1p1+CAN-2004-0175, SSH protocols 1.5/2.0, OpenSSL 0x0090702f

I get the same hanging problem.

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

When deploying there is a parent java process, and a forked java process. I assume the second one hangs. Here is the thread dump at hang time of the second process.

[INFO] [deploy:deploy]
Uploading: scp://commons.ucalgary.ca/Library/WebServer/Documents/pub/m2//ca/ucalgary/commons/pmgt/1.0/pmgt-1.0.pom

Full thread dump Java HotSpot(TM) Client VM (1.4.2-54 mixed mode):

"Connect thread commons.ucalgary.ca session" prio=5 tid=0x00545a10 nid=0x1b0a800 runnable [f0c08000..f0c08ac0]
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:129)
at com.jcraft.jsch.IO.getByte(Unknown Source)
at com.jcraft.jsch.Session.read(Unknown Source)
at com.jcraft.jsch.Session.run(Unknown Source)
at java.lang.Thread.run(Thread.java:552)

"Signal Dispatcher" daemon prio=10 tid=0x00508280 nid=0x1818000 waiting on condition [0..0]

"Finalizer" daemon prio=8 tid=0x00506cf0 nid=0x1810800 in Object.wait() [f0a04000..f0a04ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x65718cc0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:111)
- locked <0x65718cc0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:127)
  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=0x005069c0 nid=0x1803e00 in Object.wait() [f0983000..f0983ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x65718d28> (a java.lang.ref.Reference$Lock)
  at java.lang.Object.wait(Object.java:429)
  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:115)
- locked <0x65718d28> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x00500e30 nid=0x1804600 in Object.wait() [f07fe000..f08002c8]
at java.lang.Object.wait(Native Method)
- waiting on <0x6503f300> (a com.jcraft.jsch.Channel$MyPipedInputStream)
  at java.io.PipedInputStream.read(PipedInputStream.java:229)
- locked <0x6503f300> (a com.jcraft.jsch.Channel$MyPipedInputStream)
  at org.apache.maven.wagon.providers.ssh.ScpWagon.checkAck(ScpWagon.java:196)
  at org.apache.maven.wagon.providers.ssh.ScpWagon.put(ScpWagon.java:140)
  at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:180)
  at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:109)
  at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:77)
  at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:137)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

"VM Thread" prio=5 tid=0x00506240 nid=0x1804e00 runnable

"VM Periodic Task Thread" prio=10 tid=0x005081c0 nid=0x1817c00 waiting on condition
"Exception Catcher Thread" prio=10 tid=0x00500f90 nid=0x1804a00 runnable

**Comment by jira-importer** [comment]
**[Julian Wood](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=woodj)** commented

Here is a thread dump from the parent java process.

Full thread dump Java HotSpot(TM) Client VM (1.4.2-54 mixed mode):

"Thread-3" prio=5 tid=0x00536890 nid=0x19b0400 runnable [f0e0c000..f0e0cac0]
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(FileInputStream.java:194)
at sun.nio.cs.StreamDecoder$CharsetSD.readBytes(StreamDecoder.java:408)
at sun.nio.cs.StreamDecoder$CharsetSD.implRead(StreamDecoder.java:450)
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:182)
- locked <0x65016d00> (a java.io.InputStreamReader)
  at java.io.InputStreamReader.read(InputStreamReader.java:167)
  at java.io.BufferedReader.fill(BufferedReader.java:136)
  at java.io.BufferedReader.readLine(BufferedReader.java:299)
- locked <0x65016d00> (a java.io.InputStreamReader)
  at java.io.BufferedReader.readLine(BufferedReader.java:362)
  at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:152)

"Thread-2" prio=5 tid=0x00536730 nid=0x1a32200 runnable [f0d8b000..f0d8bac0]
at java.io.FileInputStream.readBytes(Native Method)
at java.io.FileInputStream.read(FileInputStream.java:194)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:220)
at java.io.BufferedInputStream.read(BufferedInputStream.java:277)
- locked <0x65015df8> (a java.io.BufferedInputStream)
  at sun.nio.cs.StreamDecoder$CharsetSD.readBytes(StreamDecoder.java:408)
  at sun.nio.cs.StreamDecoder$CharsetSD.implRead(StreamDecoder.java:450)
  at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:182)
- locked <0x65016b48> (a java.io.InputStreamReader)
  at java.io.InputStreamReader.read(InputStreamReader.java:167)
  at java.io.BufferedReader.fill(BufferedReader.java:136)
  at java.io.BufferedReader.readLine(BufferedReader.java:299)
- locked <0x65016b48> (a java.io.InputStreamReader)
  at java.io.BufferedReader.readLine(BufferedReader.java:362)
  at org.codehaus.plexus.util.cli.StreamPumper.run(StreamPumper.java:152)

"process reaper" daemon prio=5 tid=0x00536390 nid=0x186a200 runnable [f0c89000..f0c89ac0]
at java.lang.UNIXProcess.waitForProcessExit(Native Method)
at java.lang.UNIXProcess.access$800(UNIXProcess.java:20)
at java.lang.UNIXProcess$3.run(UNIXProcess.java:82)

"Signal Dispatcher" daemon prio=10 tid=0x00508250 nid=0x1818000 waiting on condition [0..0]

"Finalizer" daemon prio=8 tid=0x00506cd0 nid=0x1810800 in Object.wait() [f0a04000..f0a04ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x657162b0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:111)
- locked <0x657162b0> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:127)
  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:159)

"Reference Handler" daemon prio=10 tid=0x005069a0 nid=0x1803e00 in Object.wait() [f0983000..f0983ac0]
at java.lang.Object.wait(Native Method)
- waiting on <0x65716318> (a java.lang.ref.Reference$Lock)
  at java.lang.Object.wait(Object.java:429)
  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:115)
- locked <0x65716318> (a java.lang.ref.Reference$Lock)

"main" prio=5 tid=0x00500dd0 nid=0x1804600 in Object.wait() [f07fe000..f08002c8]
at java.lang.Object.wait(Native Method)
- waiting on <0x65016058> (a java.lang.UNIXProcess)
  at java.lang.Object.wait(Object.java:429)
  at java.lang.UNIXProcess.waitFor(UNIXProcess.java:111)
- locked <0x65016058> (a java.lang.UNIXProcess)
  at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:93)
  at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:56)
  at org.apache.maven.plugins.release.PerformReleaseMojo.runGoals(PerformReleaseMojo.java:223)
  at org.apache.maven.plugins.release.PerformReleaseMojo.execute(PerformReleaseMojo.java:95)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:482)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:452)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:214)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

"VM Thread" prio=5 tid=0x00506220 nid=0x1804e00 runnable

"VM Periodic Task Thread" prio=10 tid=0x00508190 nid=0x1817c00 waiting on condition
"Exception Catcher Thread" prio=10 tid=0x00500f60 nid=0x1804a00 runnable
