### ISSUE TITLE
[MNG-1653] Spaces in M2_HOME breaks new bootstrap

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3204]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** opened **[MNG-1653](https://issues.apache.org/jira/browse/MNG-1653?redirect=false)** and commented

There are various bugs that appear when M2_HOME contains spaces.  The attached patch fixes a few, although the integration tests still all fail as follows:

it0000... FAILED
----- Standard Out -----
Command: "C:\Program Files\maven-2.0.1-SNAPSHOT\bin\m2" -e --no-plugin-registry --batch-mode "-Dmaven.repo.local=C:\Documents and Settings\mark/.m2/repository" clean:clean package

----- Standard Error -----
Exit code: 1

> Error Stacktrace:
> org.apache.maven.it.VerificationException
> at org.apache.maven.it.Verifier.executeGoals(Verifier.java:676)
> at org.apache.maven.it.Verifier.main(Verifier.java:856)
> <<<<<< Error Stacktrace
> Log file contents:
> 'C:\Program' is not recognized as an internal or external command, operable program or batch file.
> 0/85 passed
> Failed tests: [it0085, it0084, it0083, it0082, it0081, it0080, it0079, it0078, it0077, it0076, it0075, it0074, it0073, it0072, it0071, it0070, it0069, it0068, it0067, it0066, it0065, it0064, it0063, it0062, it0061, it0060, it0059, it0058, it0057, it0056, it0055, it0054, it0053, it0052, it0051, it0050, it0049, it0048, it0047, it0046, it0045, it0044, it0043, it0042, it0041, it0040, it0039, it0038, it0037, it0036, it0035, it0034, it0033, it0032, it0031, it0030, it0029, it0028, it0027, it0026, it0025, it0024, it0023, it0022, it0021, it0020, it0019, it0018, it0017, it0016, it0014, it0013, it0012, it0011, it0010, it0009, it0008, it0007, it0006, it0005, it0004, it0003, it0002, it0001, it0000]

---

**Affects:** 2.0.1

**Attachments:**
- [patch.txt](https://issues.apache.org/jira/secure/attachment/12711538/patch.txt) (_966 bytes_)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Move to ant in the new bootstrap in trunk changes this and the ITs are separated now.
