### ISSUE TITLE
[MNG-1232] Incorrect field case triggers NPE when configurator unable to configure object

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3251]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** opened **[MNG-1232](https://issues.apache.org/jira/browse/MNG-1232?redirect=false)** and commented

Triggered working on a new plugin. The configuration error is mine, but the error message is very cryptic. I spent 15 min trying to finx the reason for the issue...
NPE should at least be avoided. Better should the configuration error reported.

pom.xml extract:

        <configuration>
            
    
           
           
           
           <dependencies>
             <dependency>commons-logging:commons:logging</dependency>
             <dependency>commons-cli:commons:cli</dependency>
           </dependencies>
    
           <jnlp>
              ...
             <sign>
                ....
               <dnameC>US</dnameC>

and my Mojo:

public class JnlpMojo
extends AbstractMojo
{
/**
* `@parameter`
  */
  private SignConfig sign;
  ...
  }

public class SignConfig {
private String dnamec;   // note the case issue
...
}

Gives the following failure:

[DEBUG] adding entry META-INF/maven/org.apache.maven.plugins/jar-mng-1130-0/pom.properties
[DEBUG] org.codehaus.mojo:webstart-maven-plugin:maven-plugin:0.1-SNAPSHOT (selected for runtime)
[DEBUG]   commons-lang:commons-lang:jar:2.1 (selected for runtime)
[DEBUG] Configuring mojo 'org.codehaus.mojo:webstart-maven-plugin:0.1-SNAPSHOT:jnlp' -->
[DEBUG]   (f) gzip = false
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------

---

constituent[0]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-core-2.0.jar
constituent[1]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-model-2.0.jar
constituent[2]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-plugin-parameter-documenter-2.0.jar
constituent[3]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-profile-2.0.jar
constituent[4]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-error-diagnostics-2.0.jar
constituent[5]: file:/home/jerome/local/lib/maven-2.0-RC/lib/plexus-interactivity-api-1.0-alpha-4.jar
constituent[6]: file:/home/jerome/local/lib/maven-2.0-RC/lib/wagon-http-lightweight-1.0-alpha-5.jar
constituent[7]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-plugin-descriptor-2.0.jar
constituent[8]: file:/home/jerome/local/lib/maven-2.0-RC/lib/commons-cli-1.0.jar
constituent[9]: file:/home/jerome/local/lib/maven-2.0-RC/lib/wagon-ssh-1.0-alpha-5.jar
constituent[10]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-monitor-2.0.jar
constituent[11]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-repository-metadata-2.0.jar
constituent[12]: file:/home/jerome/local/lib/maven-2.0-RC/lib/jsch-0.1.23.jar
constituent[13]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-settings-2.0.jar
constituent[14]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-artifact-manager-2.0.jar
constituent[15]: file:/home/jerome/local/lib/maven-2.0-RC/lib/wagon-file-1.0-alpha-5.jar
constituent[16]: file:/home/jerome/local/lib/maven-2.0-RC/lib/wagon-provider-api-1.0-alpha-5.jar
constituent[17]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-project-2.0.jar
constituent[18]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-reporting-api-2.0.jar
constituent[19]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-plugin-api-2.0.jar
constituent[20]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-artifact-2.0.jar
constituent[21]: file:/home/jerome/local/lib/maven-2.0-RC/lib/maven-plugin-registry-2.0.jar
constituent[22]: file:/home/jerome/local/lib/maven-2.0-RC/lib/doxia-sink-api-1.0-alpha-4.jar

---

java.lang.NullPointerException
at java.util.regex.Matcher.getTextLength(Matcher.java:1127)
at java.util.regex.Matcher.reset(Matcher.java:284)
at java.util.regex.Matcher.\<init>(Matcher.java:205)
at java.util.regex.Pattern.matcher(Pattern.java:879)
at org.apache.maven.plugin.PluginConfigurationException.addParameterUsageInfo(PluginConfigurationException.java:85)
at org.apache.maven.plugin.PluginConfigurationException.buildConfigurationDiagnosticMessage(PluginConfigurationException.java:272)
at org.apache.maven.usability.PluginConfigurationDiagnoser.diagnose(PluginConfigurationDiagnoser.java:49)
at org.apache.maven.usability.diagnostics.ErrorDiagnostics.diagnose(ErrorDiagnostics.java:81)
at org.apache.maven.DefaultMaven.logDiagnostics(DefaultMaven.java:693)
at org.apache.maven.DefaultMaven.logError(DefaultMaven.java:640)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:119)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Renaming the field from dnamec to dnameC fixes the issue.

---

**Attachments:**
- [MNG-1232.diff](https://issues.apache.org/jira/secure/attachment/12711590/MNG-1232.diff) (_1.08 kB_)
- [project-1232.tar.bz2](https://issues.apache.org/jira/secure/attachment/12711593/project-1232.tar.bz2) (_1.29 kB_)

**Issue Links:**
- [MNG-1414](https://issues.apache.org/jira/browse/MNG-1414) Maven dies when trying to report a plugin error
 (_**"is duplicated by"**_)
- [MNG-1351](https://issues.apache.org/jira/browse/MNG-1351) Improve error handling and message
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

Forgot to mention: affects 2.0-RC.

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

Simpler/more generic test case:

Have a Mojo with an object field (the error is not reported otherwise)
Add an non-existing property for the bean to the configuration.

E.g.

class MyMojo {
private MyBean bean;
}

class MyBean {
}

Configure like:

\<configuration>
\<bean>
\<notthere>\</notthere>
\</bean>
\</configuration>
And you reproduce the issue.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I did this with the final (\<archive>\<notthere>\</notthere>\</archive> in the assembly plugin) and got no error. Please reopen if you can still reproduce (preferably attaching test case)

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

Investigated more. With

class MyMojo {
private MyBean bean;
}

class MyBean {
private String fieldx;

// getter and setter
}

Configure like:

\<configuration>
\<bean>
\<fieldx>\</fieldx>
\</bean>
\</configuration> 

The problem is reproduced only if the getter has a wrong case.
I.e.

String getFieldX() { return fieldx; }            will fail

while

String getFieldx() { return fieldx; }

Trying to create a test case.

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

a plugin + a project exercing that plugin that is somewhat minimal.
modify the src/test/projects/project1/pom.xml (comment out the fieldX property, comment the other one) to reproduce the issue.

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

Simple thing that can fix the NPE.
Not sure why the cause is null thought. I also thought of recursing the children and add their causes (if not null) but
that didn't bring help to the user.
