### ISSUE TITLE
[MNG-1898] Plugin classpath broken from 2.0 to 2.0.1

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3320]
**[Brian E Fox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf)** opened **[MNG-1898](https://issues.apache.org/jira/browse/MNG-1898?redirect=false)** and commented

I'm working on a kodo plugin in the codehaus mojo sandbox. Using 2.0, it works fine. In 2.1, it can't find xercesImpl, which is a transitive dependency of the plugin. Did something change to cause new behavior (aka a bug) related to this? Just eyeballing the info below, in 2.0, the instance of classloader was  org.codehaus.classworlds.RealmClassLoader but in 2.0.1 it is org.codehaus.plexus.util.RealmDelegatingClassLoader

I tried specifying xercesImpl as a direct dependency and that didn't work either so I'm not sure it's related to the transitivity.

Output from 2.0.1: (2.0 follows further below)

[DEBUG] org.codehaus.mojo:kodo-maven-plugin:maven-plugin:1.0-alpha-1-SNAPSHOT (selected for runtime)
[DEBUG]   org.apache.maven:maven-model:jar:2.0 (selected for runtime)
[DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
[DEBUG] Skipping disabled repository snapshots
[DEBUG]   com.solarmetric:kodo-jdo:jar:3.3.3 (setting version to: 3.3.3 from range: [3.0,])
[DEBUG]   com.solarmetric:kodo-jdo:jar:3.3.3 (selected for runtime)
[DEBUG]     com.solarmetric:kodo-wl81manage:jar:1.0 (selected for runtime)
[DEBUG]     com.solarmetric:kodo-workbench:jar:1.0 (selected for runtime)
[DEBUG]     org.hsqldb:jdbc-hsql:jar:1.7.0 (selected for runtime)
[DEBUG]     sqlline:sqlline:jar:1.0 (selected for runtime)
[DEBUG]     jcommon:jcommon:jar:0.9.1 (selected for runtime)
[DEBUG]     javax.jdo:jdo:jar:1.0.2 (selected for runtime)
[DEBUG]     xalan:xalan:jar:2.5.1 (selected for runtime)
[DEBUG]     jfreechart:jfreechart:jar:0.9.16 (selected for runtime)
[DEBUG]     com.solarmetric:kodo-jdo-runtime:jar:3.3.3 (selected for runtime)
[DEBUG]     javax.sql:jdbc-stdext:jar:2.0 (selected for runtime)
[DEBUG]     jline:jline:jar:0.9.1 (selected for runtime)
[DEBUG]     mx4j:mx4j-jmx:jar:1.1.1 (selected for runtime)
[DEBUG]     jta-spec:jta-spec:jar:1.0.1 (selected for runtime)
[WARNING] While downloading xml-apis:xml-apis:2.0.0
This artifact has been relocated to xml-apis:xml-apis:1.0.b2.

[DEBUG]     xml-apis:xml-apis:jar:1.0.b2 (selected for runtime)
[DEBUG]     xerces:xercesImpl:jar:2.5.0 (selected for runtime)
[DEBUG]     jca:jca:jar:1.0.0 (selected for runtime)
[DEBUG]     mx4j:mx4j-tools:jar:1.1.1 (selected for runtime)
[DEBUG]     jndi:jndi:jar:1.2.1 (selected for runtime)
[DEBUG] Skipping disabled repository snapshots
[DEBUG]   log4j:log4j:jar:1.2.12 (setting version to: 1.2.12 from range: [1.2.9,])
[DEBUG]   log4j:log4j:jar:1.2.12 (selected for runtime)
[DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0 (selected for runtime)
[DEBUG] Configuring mojo 'org.codehaus.mojo:kodo-maven-plugin:1.0-alpha-1-SNAPSHOT:enhance' -->
[DEBUG]   (f) classDir = E:\STC\svn\modules\services\supplementaldata-jdo\trunk\target\classes
[DEBUG]   (f) resources = [org.apache.maven.model.Resource@acb158]
[DEBUG]   (f) searchDir = E:\STC\svn\modules\services\supplementaldata-jdo\trunk\target\classes
[DEBUG]   - end configuration --
[INFO] [kodo:enhance {execution: kodo-enhance}]
[info] Found file:E:\STC\svn\modules\services\supplementaldata-jdo\trunk\target\classes\com\stchome\application\supplementalforms\persist\persist.jdo
[info] org.codehaus.plexus.util.RealmDelegatingClassLoader@16dfa45
[debug] Added to Classpath:
[debug] /E:/STC/svn/modules/services/supplementaldata-jdo/trunk/src/main/resources/
[debug] /E:/STC/svn/modules/services/supplementaldata-jdo/trunk/target/classes/
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:93)
at serp.xml.XMLFactory.checkSAXCache(XMLFactory.java:217)
at serp.xml.XMLFactory.getSAXParser(XMLFactory.java:66)
at com.solarmetric.meta.XMLMetaDataParser.parseNew(XMLMetaDataParser.java:354)
at com.solarmetric.meta.XMLMetaDataParser.parse(XMLMetaDataParser.java:320)
at com.solarmetric.meta.ClassArgParser.getFromMetaData(ClassArgParser.java:182)
at com.solarmetric.meta.ClassArgParser.parseClassNames(ClassArgParser.java:98)
at com.solarmetric.meta.ClassArgParser.parseClasses(ClassArgParser.java:74)
at kodo.enhance.JDOEnhancer.run(JDOEnhancer.java:2657)

2.0 Output:
[DEBUG] org.codehaus.mojo:kodo-maven-plugin:maven-plugin:1.0-alpha-1-SNAPSHOT (selected for runtime)
[DEBUG]   org.apache.maven:maven-model:jar:2.0 (selected for runtime)
[DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
[DEBUG] Skipping disabled repository snapshots
[DEBUG]   com.solarmetric:kodo-jdo:jar:3.3.3 (setting version to: 3.3.3 from range: [3.0,])
[DEBUG]   com.solarmetric:kodo-jdo:jar:3.3.3 (selected for runtime)
[DEBUG]     com.solarmetric:kodo-wl81manage:jar:1.0 (selected for runtime)
[DEBUG]     com.solarmetric:kodo-workbench:jar:1.0 (selected for runtime)
[DEBUG]     org.hsqldb:jdbc-hsql:jar:1.7.0 (selected for runtime)
[DEBUG]     sqlline:sqlline:jar:1.0 (selected for runtime)
[DEBUG]     jcommon:jcommon:jar:0.9.1 (selected for runtime)
[DEBUG]     javax.jdo:jdo:jar:1.0.2 (selected for runtime)
[DEBUG]     xalan:xalan:jar:2.5.1 (selected for runtime)
[DEBUG]     jfreechart:jfreechart:jar:0.9.16 (selected for runtime)
[DEBUG]     com.solarmetric:kodo-jdo-runtime:jar:3.3.3 (selected for runtime)
[DEBUG]     javax.sql:jdbc-stdext:jar:2.0 (selected for runtime)
[DEBUG]     jline:jline:jar:0.9.1 (selected for runtime)
[DEBUG]     mx4j:mx4j-jmx:jar:1.1.1 (selected for runtime)
[DEBUG]     jta-spec:jta-spec:jar:1.0.1 (selected for runtime)
[WARNING]
This artifact has been relocated to xml-apis:xml-apis:1.0.b2.

[DEBUG]     xml-apis:xml-apis:jar:1.0.b2 (selected for runtime)
[DEBUG]     xerces:xercesImpl:jar:2.5.0 (selected for runtime)
[DEBUG]     jca:jca:jar:1.0.0 (selected for runtime)
[DEBUG]     mx4j:mx4j-tools:jar:1.1.1 (selected for runtime)
[DEBUG]     jndi:jndi:jar:1.2.1 (selected for runtime)
[DEBUG] Skipping disabled repository snapshots
[DEBUG]   log4j:log4j:jar:1.2.12 (setting version to: 1.2.12 from range: [1.2.9,])
[DEBUG]   log4j:log4j:jar:1.2.12 (selected for runtime)
[DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0 (selected for runtime)
[DEBUG] Configuring mojo 'org.codehaus.mojo:kodo-maven-plugin:1.0-alpha-1-SNAPSHOT:enhance' -->
[DEBUG]   (f) classDir = E:\STC\svn\modules\services\supplementaldata-jdo\trunk\target\classes
[DEBUG]   (f) resources = [org.apache.maven.model.Resource@39e5b5]
[DEBUG]   (f) searchDir = E:\STC\svn\modules\services\supplementaldata-jdo\trunk\target\classes
[DEBUG]   - end configuration --
[INFO] [kodo:enhance {execution: kodo-enhance}]
[info] Found file:E:\STC\svn\modules\services\supplementaldata-jdo\trunk\target\classes\com\stchome\application\supplementalforms\persist\persist.jdo
[info] org.codehaus.classworlds.RealmClassLoader@589e56
[debug] Added to Classpath:
[debug] /E:/STC/svn/modules/services/supplementaldata-jdo/trunk/src/main/resources/
[debug] /E:/STC/svn/modules/services/supplementaldata-jdo/trunk/target/classes/
0     INFO  [main] kodo.Tool - JDO enhancer running on type "class com.stchome.application.supplementalforms.persist.FormOwnerAssociation".

---

**Attachments:**
- [automatedTestCase.zip](https://issues.apache.org/jira/secure/attachment/12711896/automatedTestCase.zip) (_238.65 kB_)
- [it0100.tar.gz](https://issues.apache.org/jira/secure/attachment/12711743/it0100.tar.gz) (_3.46 kB_)
- [MNG-1898-coreit.tar.bz2](https://issues.apache.org/jira/secure/attachment/12711608/MNG-1898-coreit.tar.bz2) (_6.39 kB_)
- [mng-1898-for-2.1-take2.patch](https://issues.apache.org/jira/secure/attachment/12712220/mng-1898-for-2.1-take2.patch) (_2.69 kB_)
- [test-1.0.zip](https://issues.apache.org/jira/secure/attachment/12711606/test-1.0.zip) (_232.47 kB_)
- [test-case.zip](https://issues.apache.org/jira/secure/attachment/12711736/test-case.zip) (_5.04 kB_)

**Issue Links:**
- [MCHECKSTYLE-10](https://issues.apache.org/jira/browse/MCHECKSTYLE-10) Exception when creating Checkstyle report as part of a 'site' build

- [MSITE-60](https://issues.apache.org/jira/browse/MSITE-60) Report Classloaders out of sync when executed from within the site:site goal.

- [MNG-1804](https://issues.apache.org/jira/browse/MNG-1804) Can't load a class from a plugin, when this class is in a user's pom/build/plugins/plugin/dependencies

2 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Fixed test case

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

BTW the one I tried is MNG-1898-coreit.tar.bz2

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

the IT case came from someone else. I just retried this and was able to reproduce with 2.0.2.

Extract test-1.0.zip to localrepo/test/test/1.0

extract test-case.zip and run: mvn install
then mvn test:enhance

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Attaching new fully automated test case: automatedTestCase.zip

Unzip and run test.bat (sorry only on windows but you can look at the commands and run on unix, only 3 of them)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

IT test that breaks under 2.0.3-SNAPSHOT and succeeds under 2.0

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

it0100.tar.gz is the one for maven components\maven-core-it

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Added as it094
http://svn.apache.org/viewcvs.cgi/maven/components/trunk/maven-core-it/it0094/

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

1804 was what introduced the issue.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

the problem appeared to be that the RealmDelegatingClassLoader included the system classpath, which would have conflicted with Xerces, as best I can guess.

Flipping to realm.getClassLoader() achieves the original aim, while still matching the 2.0 classloader that the plugin was relying on. Fixed in r379425 on trunk.

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Thank you!

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

attaching patch to fix it0094 for maven 2.1

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Brian, you need to reopen the issue to bring the attention, if  you just comment it can be missed.

> attaching patch to fix it0094 for maven 2.1

It'd be good if you explain why is this patch needed now after 10 months

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Jason paged me on the dev list to fix the IT test because classworlds changed. I didn't have karma to directly commit so I figured this would be the logical place to attach. Since the actual bug itself was still fixed, it didn't occur to me to reopen.

-----Original Message-----
From: Jason van Zyl [mailto:jason@maven.org]
Sent: Tuesday, December 12, 2006 2:02 AM
To: Maven Developers List
Subject: Re: it0094 calling Brian Fox

Awesome, thanks. That means the new container works with everything now.

Jason.

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

just for further clarification: all that needs to be done on this issue is to have the mng-1898-for-2.1take2.patch applied against the trunk integration tests. Only the IT was broken, not the real code.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

re-closing for the original version. Shouldn't reopen stuff fixed in earlier versions - beter to create a new one. I will apply the patch.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

actually, looks like it was already applied

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> the problem appeared to be that the RealmDelegatingClassLoader included the system classpath, which would have conflicted with Xerces, as best I can guess.
> Actually, the `RealmDelegatingClassLoader` wasn't really delegating. The call hierarchy looked like

```
client calls ClassLoader.loadClass(String)
  ClassLoader.loadClass(String) calls this.loadClass(String, boolean)
  ClassLoader.loadClass(String, boolean) calls parent.loadClass(String, boolean)
    RealmDelegatingClassLoader.loadClass(String, boolean) calls parent.loadClass(String, boolean)  UPS
```

`RealmDelegatingClassLoader` didn't override the overload `loadClass(String, boolean)` and as such never called into `ClassRealm.loadClass()` which would have provided the requested Xerces implementation from the plugin dependencies.
