### ISSUE TITLE
[MNG-1876] exception coming from the embedder prohibits modifying the pom file. 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3352]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** opened **[MNG-1876](https://issues.apache.org/jira/browse/MNG-1876?redirect=false)** and commented

the embedder is seriously broken when it has to reload the project definition. When I open a project and the embedder reads it's structures for teh first time, it's fine, but when the user changes the pom.xml, I need to reload the data. reusing the same embedder instance,
I get this strange exception and the whole project/IDE is mainly unusable because of reoccuring exceptions. That's a showstpper for any serious IDE integration.

org.apache.maven.project.ProjectBuildingException: Duplicate project ID found in /home/mkleint/src/mevenide/mevenide2/netbeans/libs/embedder/pom.xml
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:298)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:274)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildWithDependencies(DefaultMavenProjectBuilder.java:169)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildWithDependencies(DefaultMavenProjectBuilder.java:159)
at org.apache.maven.embedder.MavenEmbedder.readProjectWithDependencies(MavenEmbedder.java:307)
at org.codehaus.mevenide.netbeans.NbMavenProject.getOriginalMavenProject(NbMavenProject.java:131)
\<snip>

---

**Affects:** 2.0.1

**Attachments:**
- [duplicates.patch](https://issues.apache.org/jira/secure/attachment/12711805/duplicates.patch) (_1.48 kB_)
- [newversion.patch](https://issues.apache.org/jira/secure/attachment/12711887/newversion.patch) (_4.87 kB_)

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

a fix that seems to work. No more embedder restarts are required, all maven integration tests passed for me.

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

a better patch, introducing a resetCache() method to MavenProjectBuilder. everytime the embedder loads any project, the resetCache() method gets called.

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

was fixed in embedder refactor branch and is now in trunk.
