### ISSUE TITLE
[MNG-1819] StringIndexOutOfBoundsException when running maven

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3362]
**[Daniel Diephouse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dandiep)** opened **[MNG-1819](https://issues.apache.org/jira/browse/MNG-1819?redirect=false)** and commented

Just trying out 2.0.1 and I am getting this message below. any ideas?

$ mvn.bat
[WARNING] Failed to initialize environment variable resolver. Skipping environment substitution in settings.
[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] String index out of range: -1
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1768)
at org.codehaus.plexus.util.cli.CommandLineUtils.getSystemEnvVars(CommandLineUtils.java:188)
at org.codehaus.plexus.util.interpolation.EnvarBasedValueSource.\<init>(EnvarBasedValueSource.java:16)
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolate(RegexBasedModelInterpolator.java:86)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:725)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:632)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:304)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:274)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:515)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:447)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:351)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:278)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Mon Dec 12 16:50:03 PST 2005
[INFO] Final Memory: 1M/2M
[INFO] ------------------------------------------------------------------------

---

**Affects:** 2.0.1

3 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

Do you have a line without '=' when you run set and/or env command?

**Comment by jira-importer** [comment]
**[Aviran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aviran)** commented

I'm getting a similar exception running continuum on Solaris. I can run maven without problems, but continuum willl fail to execute maven.

org.apache.maven.continuum.execution.ContinuumBuildExecutorException:
Error while executing shell command. The most common error is that 'mvn' is not in your path.
at
org.apache.maven.continuum.execution.AbstractBuildExecutor.executeShellCommand(AbstractBuildExecutor.java:199)
at
org.apache.maven.continuum.execution.maven.m2.MavenTwoBuildExecutor.build(MavenTwoBuildExecutor.java:86)
at
org.apache.maven.continuum.core.action.ExecuteBuilderContinuumAction.execute(ExecuteBuilderContinuumAction.java:127)
at
org.apache.maven.continuum.buildcontroller.DefaultBuildController.build(DefaultBuildController.java:171)
at
org.apache.maven.continuum.buildcontroller.BuildProjectTaskExecutor.executeTask(BuildProjectTaskExecutor.java:53)
at
org.codehaus.plexus.taskqueue.execution.ThreadedTaskQueueExecutor$ExecutorRunnable.run(ThreadedTaskQueueExecutor.java:103)
at java.lang.Thread.run(Thread.java:595)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1768)
at
org.codehaus.plexus.util.cli.CommandLineUtils.getSystemEnvVars(CommandLineUtils.java:188)
at
org.codehaus.plexus.util.cli.Commandline.addSystemEnvironment(Commandline.java:355)
at
org.apache.maven.continuum.utils.shell.DefaultShellCommandHelper.executeShellCommand(DefaultShellCommandHelper.java:71)
at
org.apache.maven.continuum.utils.shell.DefaultShellCommandHelper.executeShellCommand(DefaultShellCommandHelper.java:53)
at
org.apache.maven.continuum.execution.AbstractBuildExecutor.executeShellCommand(AbstractBuildExecutor.java:190)
... 6 more

**Comment by jira-importer** [comment]
**[Aviran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aviran)** commented

I don't know if this is related but I found that if I have an entry in the system's path with a folder name containing a space, continuum will fail to start

**Comment by jira-importer** [comment]
**[Jay Stramel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jay_stramel)** commented

I am getting this same issue also.  After trying various different things, I found that I would get this error under cygwin but not under the cmd.exe shell.

**Comment by jira-importer** [comment]
**[Aviran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aviran)** commented

OK, I got it to work.
The workaround is:
Remove any carriage return from environment elements
Remove . (dot) from the system's path
Remove any path entry with spaces in the folder name (Windows only)

Hope this help

Aviran

**Comment by jira-importer** [comment]
**[Christopher Cobb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cseg)** commented

I am also running cygwin.

If I open a windows cmd shell, I get:

C:\downloads\maven-2.0.1\bin>mvn
[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ----------------------------------------------------------------------------
[INFO] You must specify at least one goal. Try 'install'
[INFO] ----------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Wed Dec 14 11:34:47 EST 2005
[INFO] Final Memory: 1M/2M
[INFO] ----------------------------------------------------------------------------

If I open a cygwin rxvt bash shell, I get (whose path has been purified of directories with spaces with PATH=`echo $PATH|tr : '\n'|grep -v " " | tr '\n' :`), I get:

/downloads/maven-2.0.1/bin $ ./mvn
[WARNING] Failed to initialize environment variable resolver. Skipping environment substitution in settings.
[WARNING] Failed to initialize environment variable resolver. Skipping environment substitution in settings.
[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] String index out of range: -1
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1768)
at org.codehaus.plexus.util.cli.CommandLineUtils.getSystemEnvVars(CommandLineUtils.java:188)
at org.codehaus.plexus.util.interpolation.EnvarBasedValueSource.\<init>(EnvarBasedValueSource.java:16)
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolate(RegexBasedModelInterpolator.java:86)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:725)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildStandaloneSuperProject(DefaultMavenProjectBuilder.java:1334)
at org.apache.maven.DefaultMaven.getSuperProject(DefaultMaven.java:333)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:281)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Wed Dec 14 11:36:03 EST 2005
[INFO] Final Memory: 1M/2M
[INFO] ----------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

this is fixed, but may need some more revision to handle multiline envars.

**Comment by jira-importer** [comment]
**[ruel loehr](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ruelloehr)** commented

Is there a workaround in the immediate timeframe?  Or how can i get the fix?

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

the workaround is to modify all environment variables with carriage return.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

* If an environment variable line contains '=', then it will be parsed normally.
* If it doesn't contain '=', and it is not the first envar to be parsed, this entire line will be joined to the value from the last envar, using a '\n' as the join character
* Otherwise, it will ignore the line.

**Comment by jira-importer** [comment]
**[Joakim Erdfelt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joakime)** commented

I have a fresh cygwin install (new laptop)

I got it working with a minimum of change.

In a fresh cygwin install, all I had to do was add "unset PS1" into my $M2_HOME/bin/mvn script file (near the top).

I could never see the need for a project to depend on the prompt, so I felt safe in doing that.

**Comment by jira-importer** [comment]
**[Julien Dubois](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julien.dubois)** commented

This is also a bug on Mac OS X.

I tried to clean up my environement variables as said in this thread (no dots, no carriage returns, no spaces), without any success.

**Comment by jira-importer** [comment]
**[Andy Brook](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=javahollic)** commented

I know its closed, but just to rule out the cygwin-only thing, I just had this happen on SLES8, a default maven 2.0.1 install breaking... (works fine on another distro)...

**Comment by jira-importer** [comment]
**[Daniel Diephouse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dandiep)** commented

Its fixed in 2.0.2. So download the new version and you should be all set!
