### ISSUE TITLE
[MNG-1740] Error getting dependencies for a pom packaging project

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3382]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** opened **[MNG-1740](https://issues.apache.org/jira/browse/MNG-1740?redirect=false)** and commented

It seems there might be a bug with Project.getArtifacts() on projects with a pom packaging. I get an empty artifact set even though my project has some dependencies. It's working for a war packaging project though...

Here's what I get:

org.apache.maven.lifecycle.LifecycleExecutionException: Artifact [org.codehaus.cargo:simple-war:war] is not a dependency of the project.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:544)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:482)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:452)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Artifact [org.codehaus.cargo:simple-war:war] is not a dependency of the project.
at org.codehaus.cargo.maven2.AbstractDeployable.resolveArtifact(AbstractDeployable.java:105)
at org.codehaus.cargo.maven2.WarDeployable.createDeployable(WarDeployable.java:62)
at org.codehaus.cargo.maven2.DeployMojo.deploy(DeployMojo.java:91)
at org.codehaus.cargo.maven2.DeployMojo.execute(DeployMojo.java:71)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
... 16 more

And here's my POM:

\<?xml version="1.0" encoding="UTF-8"?>
\<project>
\<modelVersion>4.0.0\</modelVersion>
\<parent>
\<groupId>org.codehaus.cargo\</groupId>
\<artifactId>cargo-samples-testAll\</artifactId>
\<version>0.1-SNAPSHOT\</version>
\</parent>
\<artifactId>cargo-samples-maven2-testStartAndRemoteDeploy\</artifactId>
\<packaging>pom\</packaging>
\<name>cargo-samples-maven2-testStartAndRemoteDeploy\</name>
\<description>testStartAndRemoteDeploy\</description>
\<scm>
\<connection>scm:svn:svn://svn.cargo.codehaus.org/cargo/scm/cargo/trunk/samples/extensions/maven2/testStartAndRemoteDeploy\</connection>
\<url>http://svn.cargo.codehaus.org/\</url>
\</scm>
\<dependencies>
\<dependency>
\<groupId>org.codehaus.cargo\</groupId>
\<artifactId>simple-war\</artifactId>
\<version>0.7-SNAPSHOT\</version>
\<type>war\</type>
\</dependency>
\</dependencies>
[...]
Thanks

---

**Affects:** 2.0

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

I was missing   `@requiresDependencyResolution` in my plugin. What's strange is that it was working so far when used with war packaging projects. Anyway sorry for the false alarm...
