### ISSUE TITLE
[MNG-1445] NPE thrown when parsing bad plugin jar

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3519]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** opened **[MNG-1445](https://issues.apache.org/jira/browse/MNG-1445?redirect=false)** and commented

Due to a configuration error, I had referenced a jar that was not a plugin in the list of plugins.  This caused the following NPE:
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] null
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginManager.java:292)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:198)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:163)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1095)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifecycle(DefaultLifecycleExecutor.java:1060)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:869)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 2.0

**Attachments:**
- [MNG-1445-testcase.zip](https://issues.apache.org/jira/secure/attachment/12711521/MNG-1445-testcase.zip) (_1.29 kB_)

**Issue Links:**
- [MNG-2239](https://issues.apache.org/jira/browse/MNG-2239) Null pointer exception when typo is in plugin name
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** commented

The attached test case contains two projects:
-  testplugin creates a simple plugin
-  test references the plugin

To replicate the problem:
-  Run "mvn install" on testplugin
-  Unpack the installed jar, remove META-INF/maven/plugin.xml, and repack the jar
-  Run "mvn compile" on test

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

this is a dupe, but I don't have the issue number handy to close/link it.

**Comment by jira-importer** [comment]
**[Aaron Digulla](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=digulla)** commented

Probably this one
