### ISSUE TITLE
[MNG-1415] quoted arguments are not being protected

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3525]
**[Matthew Pocock](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dozer)** opened **[MNG-1415](https://issues.apache.org/jira/browse/MNG-1415?redirect=false)** and commented

Arguments with whitespace protected by quotes are broken up into individual arguments by maven. It's not happening inside the mvn script - I've echoed the generated command-line to check that. This same exception is raised regardless of using...

-x="y z"
-x=\"y z\"
-x='y z'
"-x=y z"

and several other combinations I can't remember.

Here's an example failure:

nmrp3@farnham:~/devel/fluxion/trunk/stack/sql-schema$ ~/m2_home/bin/mvn org.codehaus.mojo:maven-execute-plugin:0.1-SNAPSHOT:resources -Dexecute.class=org.comparagrid.fluxion.sql.schema.OWLFromSchema -Dexecute.args="-baseURI=fish -Xdebug"
+ Error stacktraces are turned on.
  [DEBUG] Building Maven user-level plugin registry from: '/home/nmrp3/.m2/plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: '/home/nmrp3/m2_home/conf/plugin-registry.xml'
  [INFO] Scanning for projects...
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: org.comparagrid.fluxion:sql-schema:jar:0.1-SNAPSHOT
  [DEBUG] Skipping disabled repository central
  [DEBUG] Skipping disabled repository central
  [DEBUG] maven-execute-plugin: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-execute-plugin:maven-plugin:0.1-SNAPSHOT
  [DEBUG] maven-execute-plugin: using locally installed snapshot
  [INFO] ----------------------------------------------------------------------------
  [ERROR] BUILD FAILURE
  [INFO] ----------------------------------------------------------------------------
  [INFO] Invalid task 'debug': you must specify a valid lifecycle phase, or a goal in the format plugin:goal or pluginGroupId:pluginArtifactId:pluginVersion:goal
  [INFO] ----------------------------------------------------------------------------
  [DEBUG] Trace
  org.apache.maven.BuildFailureException: Invalid task 'debug': you must specify a valid lifecycle phase, or a goal in the format plugin:goal or pluginGroupId:pluginArtifactId:pluginVersion:goal
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1351)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.segmentTaskListByAggregationNeeds(DefaultLifecycleExecutor.java:376)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:132)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:585)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
  [INFO] ----------------------------------------------------------------------------
  [INFO] Total time: < 1 second
  [INFO] Finished at: Thu Nov 03 23:35:37 GMT 2005
  [INFO] Final Memory: 1M/3M
  [INFO] ------------------------------------------------------------------------

---

**Issue Links:**
- [MNG-2190](https://issues.apache.org/jira/browse/MNG-2190) -Dkey=value parameters cannot include spaces in the value
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Alexandre Poitras](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pouet)** commented

Seems related to http://jira.codehaus.org/browse/MNG-1389

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this is different to MNG-1389.

Matthew, did you determine whether this was an issue with the shell script or not?

**Comment by jira-importer** [comment]
**[Matthew Pocock](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dozer)** commented

This seems to definitely be an issue with bash, not anything in maven. However, I've not been able to work arround it in bash, so the *nix mvn script is by deffinition affected.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

The actual fix was a bit more involved, on two fronts.

First, commons-cli apparently doesn't know what to do with:

"-Dfoo=some bar"

when it sees it, so it balks. I compensated for this by adding my own quoted-argument reconstruction method to the parse() method of the CLIManager in MavenCLI. This will groom out any quotes and re-join quoted arguments that span multiple arg-array elements.

Second, usage of the 'm2' script will still break when using the fix included in the comments of this issue. To handle this, I have had to introduce some fairly shady scripting in the m2 shell script, which **may** need some more tweaking to get right. However, since it's deprecated, IMO we shouldn't go to outrageous lengths to fix it for this issue.

**Comment by jira-importer** [comment]
**[Gordon Henriksen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gordonhenriksen)** commented

Sorry for the dup.

The above changes just seem to shift the problem from spaces to quotes. Try this bash voodoo:

- ${CLASSWORLDS_LAUNCHER} $@

+ ${CLASSWORLDS_LAUNCHER} "$@"
