### ISSUE TITLE
[MNG-1394] Use of the RelativePath Multi-Module produces failure

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3549]
**[Peter Pilgrim](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=peterpilgrim)** opened **[MNG-1394](https://issues.apache.org/jira/browse/MNG-1394?redirect=false)** and commented

Run maven with the pom.xml that explicitly set the \<relativePath> element inside the
parent \<parent> element causes a stacktrace failure

C:\Projects\bridgetown\core>mvn compile
[INFO] Scanning for projects...
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] FATAL ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Error building POM (may not be this project's POM).

Project ID: com.xenonsoft.bridgetown:bridgetown-core

Reason: Could not find the model file 'C:\Projects\bridgetown'.

[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Could not find the model file
'C:\Projects\bridgetown'.
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:359)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:276)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.project.ProjectBuildingException: Could not find the
model file 'C:\Projects\bridgetown'.
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(Default
MavenProjectBuilder.java:1061)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(D
efaultMavenProjectBuilder.java:899)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMave
nProjectBuilder.java:586)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFi
le(DefaultMavenProjectBuilder.java:298)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMave
nProjectBuilder.java:276)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:509)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:441)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:345)
... 11 more
Caused by: java.io.FileNotFoundException: C:\Projects\bridgetown (Access is deni
ed)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.\<init>(FileInputStream.java:106)
at java.io.FileReader.\<init>(FileReader.java:55)
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(Default
MavenProjectBuilder.java:1056)
... 18 more
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Total time: < 1 second
[INFO] Finished at: Wed Nov 02 10:22:16 GMT 2005
[INFO] Final Memory: 1M/2M
[INFO] -------------------------------------------------------------------------
&mdash;

C:\Projects\bridgetown\core>

\<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
\<parent>
\<artifactId>bridgetown\</artifactId>
\<groupId>com.xenonsoft.bridgetown\</groupId>
\<version>0.9.8-SNAPSHOT\</version>
\<relativePath>..\</relativePath>
\</parent>
\<modelVersion>4.0.0\</modelVersion>
\<groupId>com.xenonsoft.bridgetown\</groupId>
\<artifactId>bridgetown-core\</artifactId>

    ...

\</parent>

If I remove the relativePath element or comment it out. Mvn2 works successfully.

---

**Affects:** 2.0

**Attachments:**
- [MNG-1394-maven-project.patch](https://issues.apache.org/jira/secure/attachment/12711878/MNG-1394-maven-project.patch) (_998 bytes_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

it requires ../pom.xml

I guess we should improve the error message, and if relativePath gives a directory add pom.xml

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

Please see attached patch.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Applied, with added debug statement in case of a directory relativePath, to let the user know we're looking for 'pom.xml' in that dir.

Thanks, Edwin.
