### ISSUE TITLE
[MNG-1351] Improve error handling and message

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3566]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** opened **[MNG-1351](https://issues.apache.org/jira/browse/MNG-1351?redirect=false)** and commented

I don't know yet what the problem is but the stack trace doesn't help me in solving it. It would be nice to display a more indicative error message:

C:\dev\cargo\trunk\samples\extensions\maven2>mvn org.codehaus.cargo.maven2:cargo-maven2-plugin:start -X
+ Error stacktraces are turned on.
  [DEBUG] Building Maven user-level plugin registry from: 'C:\Documents and Settings\Vincent Massol\.m2\plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: 'c:\apps\maven2\conf\plugin-registry.xml'
  [INFO] Scanning for projects...
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: org.codehaus.cargo.samples.maven2:cargo-samples-
  maven2:war:null
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: org.codehaus.cargo.samples:cargo-samples-extensi
  ons:pom:null
  [DEBUG] Using parent-POM from the project hierarchy at: '../pom.xml' for project: org.codehaus.cargo.samples:cargo-samples:pom:nul
  l
  [DEBUG] cargo-maven2-plugin: resolved to version 0.7-SNAPSHOT from local repository
  [DEBUG] Skipping disabled repository central
  [DEBUG] cargo-maven2-plugin: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: org.codehaus.cargo.maven2:cargo-maven2-plugin:maven-plugin:0.7-SNAP
  SHOT
  [DEBUG] Skipping disabled repository central
  [DEBUG] cargo: using locally installed snapshot
  [DEBUG] cargo-maven2-plugin: using locally installed snapshot
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building Cargo Sample for the Maven2 plugin
  [INFO]    task-segment: [org.codehaus.cargo.maven2:cargo-maven2-plugin:start]
  [INFO] ----------------------------------------------------------------------------
  [DEBUG] cargo-maven2-plugin: using locally installed snapshot
  [DEBUG] org.codehaus.cargo.maven2:cargo-maven2-plugin:maven-plugin:0.7-SNAPSHOT (selected for runtime)
  [DEBUG] Skipping disabled repository central
  [DEBUG] cargo-core-generic: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: null:cargo-core-generic:jar:0.7-SNAPSHOT
  [DEBUG] Skipping disabled repository central
  [DEBUG] cargo-core: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: org.codehaus.cargo.core:cargo-core:jar:0.7-SNAPSHOT
  [DEBUG] cargo: using locally installed snapshot
  [DEBUG]   org.codehaus.cargo.core:cargo-core-generic:jar:0.7-SNAPSHOT (selected for runtime)
  [DEBUG]     ant:ant:jar:1.5.4 (selected for runtime)
  [DEBUG] Skipping disabled repository central
  [DEBUG] cargo-core-container: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: null:cargo-core-container:jar:0.7-SNAPSHOT
  [DEBUG] cargo-core: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: org.codehaus.cargo.core:cargo-core:jar:0.7-SNAPSHOT
  [DEBUG] cargo: using locally installed snapshot
  [DEBUG]     org.codehaus.cargo.core:cargo-core-container:jar:0.7-SNAPSHOT (selected for runtime)
  [DEBUG]       ant:ant:jar:1.5.4 (selected for runtime)
  [DEBUG] Skipping disabled repository central
  [DEBUG] cargo-core-module: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: null:cargo-core-module:jar:0.7-SNAPSHOT
  [DEBUG] cargo-core: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: org.codehaus.cargo.core:cargo-core:jar:0.7-SNAPSHOT
  [DEBUG] cargo: using locally installed snapshot
  [DEBUG]       org.codehaus.cargo.core:cargo-core-module:jar:0.7-SNAPSHOT (selected for runtime)
  [DEBUG]         ant:ant:jar:1.5.4 (selected for runtime)
  [DEBUG] Skipping disabled repository central
  [DEBUG] cargo-core-util: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: null:cargo-core-util:jar:0.7-SNAPSHOT
  [DEBUG] cargo-core: using locally installed snapshot
  [DEBUG] Retrieving parent-POM from the repository for project: org.codehaus.cargo.core:cargo-core:jar:0.7-SNAPSHOT
  [DEBUG] cargo: using locally installed snapshot
  [DEBUG]         org.codehaus.cargo.core:cargo-core-util:jar:0.7-SNAPSHOT (selected for runtime)
  [DEBUG]           ant:ant:jar:1.5.4 (selected for runtime)
  [DEBUG]         xml-apis:xml-apis:jar:2.0.2 (selected for runtime)
  [DEBUG]         xerces:xercesImpl:jar:2.6.2 (selected for runtime)
  [DEBUG]       geronimo-spec:geronimo-spec-j2ee-deployment:jar:1.1-rc4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-project:jar:2.0
  [DEBUG]   org.apache.maven:maven-project:jar:2.0 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]     org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8 (selected for runtime)
  [DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]       classworlds:classworlds:jar:1.1-alpha-2 (selected for runtime)
  [DEBUG]       junit:junit:jar:3.8.1 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-artifact:jar:2.0
  [DEBUG]     org.apache.maven:maven-artifact:jar:2.0 (selected for runtime)
  [DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-model:jar:2.0
  [DEBUG]     org.apache.maven:maven-model:jar:2.0 (selected for runtime)
  [DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-artifact-manager:jar:2.0
  [DEBUG]     org.apache.maven:maven-artifact-manager:jar:2.0 (selected for runtime)
  [DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8 (selected for runtime)
  [DEBUG]       org.apache.maven:maven-artifact:jar:2.0 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-repository-metadata:jar:2.0
  [DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0 (selected for runtime)
  [DEBUG]         org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]       org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-5 (selected for runtime)
  [DEBUG]         org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: null:maven-profile:jar:2.0
  [DEBUG]     org.apache.maven:maven-profile:jar:2.0 (selected for runtime)
  [DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.0.4 (selected for runtime)
  [DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-8 (selected for runtime)
  [DEBUG]       org.apache.maven:maven-model:jar:2.0 (selected for runtime)
  [DEBUG]   org.codehaus.cargo.core:cargo-core-container:jar:0.7-SNAPSHOT (selected for runtime)
  [DEBUG]     ant:ant:jar:1.5.4 (selected for runtime)
  [DEBUG]     org.codehaus.cargo.core:cargo-core-module:jar:0.7-SNAPSHOT (selected for runtime)
  [DEBUG]       ant:ant:jar:1.5.4 (selected for runtime)
  [DEBUG]       org.codehaus.cargo.core:cargo-core-util:jar:0.7-SNAPSHOT (selected for runtime)
  [DEBUG]         ant:ant:jar:1.5.4 (selected for runtime)
  [DEBUG]       xml-apis:xml-apis:jar:2.0.2 (selected for runtime)
  [DEBUG]       xerces:xercesImpl:jar:2.6.2 (selected for runtime)
  [DEBUG]     geronimo-spec:geronimo-spec-j2ee-deployment:jar:1.1-rc4 (selected for runtime)
  [DEBUG] Retrieving parent-POM from the repository for project: org.apache.maven:maven-plugin-api:jar:2.0
  [DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0 (selected for runtime)
  [DEBUG] cargo-core-container: using locally installed snapshot
  [DEBUG] cargo-core-generic: using locally installed snapshot
  [DEBUG] cargo-core-util: using locally installed snapshot
  [DEBUG] cargo-core-module: using locally installed snapshot
  [DEBUG] Configuring mojo 'org.codehaus.cargo.maven2:cargo-maven2-plugin:0.7-SNAPSHOT:start' -->
  [INFO] ----------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ----------------------------------------------------------------------------

---

constituent[0]: file:/c:/apps/maven2/lib/commons-cli-1.0.jar
constituent[1]: file:/c:/apps/maven2/lib/doxia-sink-api-1.0-alpha-6-20051021.114601-1.jar
constituent[2]: file:/c:/apps/maven2/lib/jsch-0.1.23.jar
constituent[3]: file:/c:/apps/maven2/lib/junit-3.8.1.jar
constituent[4]: file:/c:/apps/maven2/lib/maven-artifact-2.0.1-SNAPSHOT.jar
constituent[5]: file:/c:/apps/maven2/lib/maven-artifact-manager-2.0.1-SNAPSHOT.jar
constituent[6]: file:/c:/apps/maven2/lib/maven-core-2.0.1-SNAPSHOT.jar
constituent[7]: file:/c:/apps/maven2/lib/maven-error-diagnostics-2.0.1-SNAPSHOT.jar
constituent[8]: file:/c:/apps/maven2/lib/maven-model-2.0.1-SNAPSHOT.jar
constituent[9]: file:/c:/apps/maven2/lib/maven-monitor-2.0.1-SNAPSHOT.jar
constituent[10]: file:/c:/apps/maven2/lib/maven-plugin-api-2.0.1-SNAPSHOT.jar
constituent[11]: file:/c:/apps/maven2/lib/maven-plugin-descriptor-2.0.1-SNAPSHOT.jar
constituent[12]: file:/c:/apps/maven2/lib/maven-plugin-parameter-documenter-2.0.1-SNAPSHOT.jar
constituent[13]: file:/c:/apps/maven2/lib/maven-plugin-registry-2.0.1-SNAPSHOT.jar
constituent[14]: file:/c:/apps/maven2/lib/maven-profile-2.0.1-SNAPSHOT.jar
constituent[15]: file:/c:/apps/maven2/lib/maven-project-2.0.1-SNAPSHOT.jar
constituent[16]: file:/c:/apps/maven2/lib/maven-reporting-api-2.0.1-SNAPSHOT.jar
constituent[17]: file:/c:/apps/maven2/lib/maven-repository-metadata-2.0.1-SNAPSHOT.jar
constituent[18]: file:/c:/apps/maven2/lib/maven-settings-2.0.1-SNAPSHOT.jar
constituent[19]: file:/c:/apps/maven2/lib/plexus-interactivity-api-1.0-alpha-4.jar
constituent[20]: file:/c:/apps/maven2/lib/wagon-file-1.0-alpha-5.jar
constituent[21]: file:/c:/apps/maven2/lib/wagon-http-lightweight-1.0-alpha-5.jar
constituent[22]: file:/c:/apps/maven2/lib/wagon-provider-api-1.0-alpha-5.jar
constituent[23]: file:/c:/apps/maven2/lib/wagon-ssh-1.0-alpha-5.jar

---

java.lang.NullPointerException
at java.util.regex.Matcher.getTextLength(Matcher.java:758)
at java.util.regex.Matcher.find(Matcher.java:414)
at org.apache.maven.plugin.PluginConfigurationException.addParameterUsageInfo(PluginConfigurationException.java:92)
at org.apache.maven.plugin.PluginConfigurationException.buildConfigurationDiagnosticMessage(PluginConfigurationException.j
ava:272)
at org.apache.maven.usability.PluginConfigurationDiagnoser.diagnose(PluginConfigurationDiagnoser.java:49)
at org.apache.maven.usability.diagnostics.ErrorDiagnostics.diagnose(ErrorDiagnostics.java:81)
at org.apache.maven.DefaultMaven.logDiagnostics(DefaultMaven.java:699)
at org.apache.maven.DefaultMaven.logError(DefaultMaven.java:646)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

C:\dev\cargo\trunk\samples\extensions\maven2>

---

**Affects:** 2.0

**Issue Links:**
- [MNG-1232](https://issues.apache.org/jira/browse/MNG-1232) Incorrect field case triggers NPE when configurator unable to configure object
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

I've found the problem. I had a class variable in my plugin Mojo named after a config element in my test pom.xml...
