### ISSUE TITLE
[MNG-1323] Plugin extensions (dependencies) not resolved in reactor build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3573]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** opened **[MNG-1323](https://issues.apache.org/jira/browse/MNG-1323?redirect=false)** and commented

I've added a dependency on an Ant Task in project/build/plugins/plugin[artifactId='maven-antrun-plugin']/dependencies/ and run that anttask using the antrun plugin.

When run from the project dir itself it runs fine.
When running from the root of the project tree (reactor build, project one level below root),
antrun bails out because the taskdef can't be found (not on classpath).

It looks like the dependency isn't resolved, or not added to the plugins' classrealm.

---

**Affects:** 2.0

**Attachments:**
- [MNG-1323-components-2.0.x.diff](https://issues.apache.org/jira/secure/attachment/12712566/MNG-1323-components-2.0.x.diff) (_54.73 kB_)
- [MNG-1323-core-integration-testing.diff](https://issues.apache.org/jira/secure/attachment/12712463/MNG-1323-core-integration-testing.diff) (_12.81 kB_)
- [MNG-1323-core-integration-testing-2.diff](https://issues.apache.org/jira/secure/attachment/12712498/MNG-1323-core-integration-testing-2.diff) (_13.59 kB_)
- [MNG-1323-core-integration-tests.diff](https://issues.apache.org/jira/secure/attachment/12712052/MNG-1323-core-integration-tests.diff) (_12.56 kB_)
- [MNG-1323-core-integration-tests-3.diff](https://issues.apache.org/jira/secure/attachment/12712505/MNG-1323-core-integration-tests-3.diff) (_34.05 kB_)
- [MNG1323-maven-core-2.1.diff](https://issues.apache.org/jira/secure/attachment/12712502/MNG1323-maven-core-2.1.diff) (_29.42 kB_)
- [two-antruns.zip](https://issues.apache.org/jira/secure/attachment/12711762/two-antruns.zip) (_6.20 kB_)

**Issue Links:**
- [MANTRUN-52](https://issues.apache.org/jira/browse/MANTRUN-52) plugin dependencies seem to get lost when using the plugin multiple times
 (_**"is duplicated by"**_)
- [MANTRUN-51](https://issues.apache.org/jira/browse/MANTRUN-51) Problems with multiple antrun declarations in multiproject
 (_**"is duplicated by"**_)
- [MANTRUN-61](https://issues.apache.org/jira/browse/MANTRUN-61) Classloader issue with ant optional tasks in a hierarchical structure
 (_**"is duplicated by"**_)
- [MANTRUN-63](https://issues.apache.org/jira/browse/MANTRUN-63) ant classpath resolves incorrectly if project is invoked as part of multi-project builds
 (_**"is duplicated by"**_)
- [MNG-1949](https://issues.apache.org/jira/browse/MNG-1949) project-level plugin dependencies not handled correctly in multimodule builds
 (_**"is duplicated by"**_)
- [MNG-2946](https://issues.apache.org/jira/browse/MNG-2946) Module-by-Profile seems to break plugin dependencies
 (_**"is duplicated by"**_)
- [MNG-3950](https://issues.apache.org/jira/browse/MNG-3950) With multiple modules using the same plugin later invocations of the plugin are not initialized
 (_**"is duplicated by"**_)
- [MNG-4178](https://issues.apache.org/jira/browse/MNG-4178) Plugin dependency not always included to classpath
 (_**"is duplicated by"**_)
- [MNG-5290](https://issues.apache.org/jira/browse/MNG-5290) Plugin extensions (dependencies) not resolved in reactor build
 (_**"is duplicated by"**_)
- [MASSEMBLY-233](https://issues.apache.org/jira/browse/MASSEMBLY-233) Custom ContainerDescriptorHandler integration tests don't work in Maven 2.0.7

- [MNG-1911](https://issues.apache.org/jira/browse/MNG-1911) Building plugins with extensions in a reactor fails

- [MNG-3284](https://issues.apache.org/jira/browse/MNG-3284) Cached plugins are used, even when the specifically declared

- [MANTRUN-106](https://issues.apache.org/jira/browse/MANTRUN-106) Maven dependency bug can lead to very confusing failures

- [MASSEMBLY-468](https://issues.apache.org/jira/browse/MASSEMBLY-468) Sharing assembly descriptor across sub modules does not work if parent defines assembly and submodule want to add own assembly

- [MNG-1949](https://issues.apache.org/jira/browse/MNG-1949) project-level plugin dependencies not handled correctly in multimodule builds

- [MPLUGIN-37](https://issues.apache.org/jira/browse/MPLUGIN-37) parent with multi-type mojo children does not build ant mojo
 (_**"is depended upon by"**_)

60 votes, 36 watchers

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

note above that this is scheduled for 2.0.3 (Feb release).

**Comment by jira-importer** [comment]
**[ruel loehr](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ruelloehr)** commented

Are there any suggested work arounds for this issue?    Hence, if I wish to use a custom ant task in a child module (which would require a dependency upon the antrun plugin), how would I accomplish it, or is it impossible at this time?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

workaround is to include the dependency in the first antrun plugin instance encountered. one way to guarantee would be to include this in the root project.

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

Hm.. this problem is really annoying and there is no workaround. Now I even get a weirder error:

java.lang.NoSuchMethodError: java_cup.runtime.lr_parser.parse()V
at org.jacorb.idl.JacIDL.execute(JacIDL.java:356)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)

The org.jacorb.idl stuff AND the java_cup.runtime are both in the same jar file! This might be a bug
in Jacorb, but when run from the projects themselves, everything goes OK.
It doesn't matter if I specify the dependencies in a dependencyManagement in the root pom,
or in the project's declaring the plugin themselves.

I even tried the idlj-maven-plugin in mojo's sandbox. It's used twice in the entire reactor tree.
The plugin itself does not define the jacorb dependency, so I had to define it. I tried \<build>\<extensions>,
root pom's pluginManagement, and both pom's. Since this is the exact same plugin with the exact same
deps and configuration, it should work. Unfortunately it doesn't.

Now, about a solution.

M2 currently disposes the PlexusRealm for the plugin after each execution. However,
the classloader is set to the mojoDescriptor.getPluginDescriptor().getClassRealm().getClassLoader().
This classloader/classRealm is NOT disposed of. I'm not sure why the PlexusRealm isn't equal to the
pluginDescriptor's classRealm. There should be one access point to manage a plugin's execution environment.

If this were fixed, John Casey's comment above about the ArtifactHandlerManager comes into play.

A suggestion: We could leave the plugin's declared dependencies in the same classloader as the plugin's artifact.
We could add a NEW classloader containing the project's \<dependencies> for that plugin, and hook that into
the plugin's classloader as a child. After execution, we unhook it (perhaps a child PlexusRealm?)

I would really like to get this fixed in 2.0.5. My previous workaround (specifying the filename of the dependency
in an ant script's TaskDef tag) doesn't work anymore since 2.0.4.

**Comment by jira-importer** [comment]
**[Piotr Tabor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptabor)** commented

Attached integration test to the issue - ready to commit.

The test fails if run from parent directory and works
if run from children directories.

**Comment by jira-importer** [comment]
**[Brian Topping](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=topping)** commented

John's comment in http://jira.codehaus.org/browse/MNG-1323#action_50268 is correct, that "this is undoubtedly caused by Maven not disposing of plugin containers between project builds".  DefaultPluginManager.ensurePluginContainerIsComplete() specifically skips plugin instantiation on the first line if it's already been initialized.

This is a huge problem in a build that I am working on.  Using a setup like:

root/pom.xml, modules: a, b
a/pom.xml: define antrun, with antrun target that generates an ant Task
b/pom.xml: define antrun, with \<dependencies> section that includes the task built with a

There's no way to use the Task built in a if the container that built a is not disposed and reloaded with the new dependencies of b (which includes a).

This whole thing of using antrun is suboptimal, but it needs to be supported.  The project that I'm currently porting uses XDoclet 1 very heavily, along with a forked version of Castor and some Texen tasks for a forked version of Torque.  The only way to reliably bring this across is to clean it up after things are stabilized, with 60+ projects at last count, there's just too much risk to try to create plugins before the build is operational.

JOHN:  have you tried to solve this before and run into problems?  This issue is coming up on two years old and has over 20 watchers.  I'd like to help, but from previous experience, I'd like to get as much information as I can about what the solution is up against.  It's an obvious performance violation to blindly dispose the container with every execution (there should probably be some kind of dependency signature comparison before disposing the container), but since this happens per-build rather than within a build, the impact should be minimal.

Discuss!

**Comment by jira-importer** [comment]
**[Piotr Tabor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptabor)** commented

I am trying to work on the issue too.

The simplest solution is in DefaultPluginManager change the code to:

private PluginDescriptor verifyVersionedPlugin( Plugin plugin,
MavenProject project,
ArtifactRepository localRepository )

    File pluginFile = pluginArtifact.getFile();

* 

       if  /*( !pluginCollector.isPluginInstalled( plugin ) ||*/  ( pluginContainer == null ) *
      {
          addPlugin( plugin, pluginArtifact, project, localRepository );
      }

* 

             else  /*if ( pluginFile.lastModified() > pluginContainer.getCreationDate().getTime() )/ * *
            {
                getLogger().info(
                    "Reloading plugin container for: " + plugin.getKey() + ". The plugin artifact has changed." );
      
                pluginContainer.dispose();
      
                pluginCollector.flushPluginDescriptor( plugin );
      
                addPlugin( plugin, pluginArtifact, project, localRepository );
            }

But it slows Maven to much... I will trying to prepare know a little bit better solution that checks if getted descriptor matches and if
not - to replace it.

The best solution is to build plugin's identifiers that contains hashcode of dependencies.

Any comments from Commiters ?

**Comment by jira-importer** [comment]
**[Piotr Tabor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptabor)** commented

Sent to dev@maven.apache.org:

Business (user's) problem:

The problem is that maven only once resolve dependencies for every plugin's KEY (plugin's groupId:artifactId) - not for
every mavan USAGE. But the pom's \<plugin>\<dependencies>\</dependencies>\</plugin> tag allows for specifying plugin's dependencies per
every USAGE. In current maven's version (2.0.8-SNAPSHOT, 2.1-SNAPSHOT) the all plugin's USAGES are using the same dependencies as the first USAGE.
It is especially annoying with maven-antrun-plugin (that is often used with diffrent "tags" dependencies).

Implementation situation:

Facts:
* PluginDescriptors class constain's resolved plugin's dependencies
* MavenPluginCollector constains cache - map  (pluginKey (groupId:artifactId) into PluginDescriptors)
* DefaultPluginManager.verifyVersionedPlugin (is responsible for transferring Plugin object into PluginDescriptor)
  uses MavenPluginCollector to check if the right entry exists.

There are possible such a fixes:

    1) The worst: Remove caching (every plugin's environment (including) child plexusContainer has to be recalculated for each maven usage)  - simplest to implement (and working patch is in JIRA comments))
    
    2) Better: Check after getting PluginDescriptor from MavenPluginCollector:
          if(comutativeEquals(!pluginCollector.getPluginDescriptor(plugin).getIntroducedDependencyArtifacts(), plugin.getDependencies()))
          {
             recalculateTheEntry();
          }         
    
       adventages: simple to implement (change in single place)
    
       disadventages: If there are two (or more) usage of the same plugin      (interlaced) the one will be cashed and the other will be recalculated

with each use.
3 ) to change the plugin identificator for this cashing from: groupId:artifactId  to groupId:artifactId:comutativeHashCode(getDependencies())

adventages: the best for performance
disadventages:
a) many changes in many places
b) I am a little bit afraid about resolving plugin's transitive dependencies (they seems to be  resolved "lazily", so the dependencies list so the cache key too)...
(but I'm sure it is to be worked out)

Am I right? Please comment... At least to motivate me to work on this issue further.

**Comment by jira-importer** [comment]
**[mtkopone](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mikko.koponen@ri.fi)** commented

Sounds to me like plugin dependencies should be execution-specific?

**Comment by jira-importer** [comment]
**[mtkopone](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mikko.koponen@ri.fi)** commented

Ugliest workaround yet:
Since we are mostly running into this when using the maven-antrun-plugin, I redeployed the version we are using into our company-wide maven repo with a different groupId/artifactId, and am now issueing such groupIds/artifactIds to developers that require differing dependencies in their antruns. When this bug gets fixed, I'll relocate all those plugins back to the real version.

**Comment by jira-importer** [comment]
**[Piotr Tabor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptabor)** commented

Patch for this issue for 2.0.x.
All it's passed.

**Comment by jira-importer** [comment]
**[Piotr Tabor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptabor)** commented

It test for this issue. Actualized to current tests numeration (127)

**Comment by jira-importer** [comment]
**[Piotr Tabor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptabor)** commented

Corrected one thing in Integration Test.

**Comment by jira-importer** [comment]
**[Piotr Tabor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ptabor)** commented

Patch for trunk(2.1) was commited by Jason van Zyl.

Patch for 2.0.x is waiting to be commited (http://jira.codehaus.org/secure/attachment/29268/MNG-1323-components-2.0.x.diff).

I hope the issue is likely to be marked as : Fix version: 2.1-alpha-1, 2.0.8
