### ISSUE TITLE
[MNG-1297] Continuum build throws LifecycleExecutionException while building Maven PLUGIN Plugin 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3596]
**[Grzegorz Slowikowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gslowikowski)** opened **[MNG-1297](https://issues.apache.org/jira/browse/MNG-1297?redirect=false)** and commented

In your continuum logs there is an exception. Build finishes with success. What does this exception mean?
Why is it not critical?

---

[INFO] Error for project: Maven PLUGIN Plugin (during install)
[INFO] ----------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-plugin-plugin:2.0.1-SNAPSHOT:updateRegistry': Unable to find the mojo 'org.apache.maven.plugins:maven-plugin-plugin:2.0.1-SNAPSHOT:updateRegistry' in the plugin 'org.apache.maven.plugins:maven-plugin-plugin'
org.apache.maven.plugin.plugin.UpdatePluginRegistryMojo
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-plugin-plugin:2.0.1-SNAPSHOT:updateRegistry': Unable to find the mojo 'org.apache.maven.plugins:maven-plugin-plugin:2.0.1-SNAPSHOT:updateRegistry' in the plugin 'org.apache.maven.plugins:maven-plugin-plugin'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:523)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-plugin-plugin:2.0.1-SNAPSHOT:updateRegistry' in the plugin 'org.apache.maven.plugins:maven-plugin-plugin'
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:520)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:377)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
... 16 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-plugin-plugin:2.0.1-SNAPSHOT:updateRegistry', it could not be created
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:436)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:511)
... 18 more
Caused by: org.codehaus.plexus.component.factory.ComponentInstantiationException: Could not instanciate component: role: 'null', implementation: 'org.apache.maven.plugin.plugin.UpdatePluginRegistryMojo'
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.makeException(JavaComponentFactory.java:77)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:54)
at org.codehaus.plexus.DefaultPlexusContainer.createComponentInstance(DefaultPlexusContainer.java:1454)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:93)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:327)
... 20 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.plugin.plugin.UpdatePluginRegistryMojo
at java.net.URLClassLoader$1.run(URLClassLoader.java:199)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:187)
at java.lang.ClassLoader.loadClass(ClassLoader.java:289)
at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassLoader.java:195)
at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:255)
at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:274)
at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:274)
at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:30)
... 24 more
[INFO] ----------------------------------------------------------------------------
[INFO] BUILD ERRORS
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 29 seconds
[INFO] Finished at: Mon Oct 24 02:17:09 GMT+00:00 2005
[INFO] Final Memory: 6M/11M
[INFO] ------------------------------------------------------------------------

---

**Affects:** 2.0.1

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

It's a known issue - there may already be a JIRA to fix it but leaving this open until now.

It is ignored because the plugin is rebuilt a second time which succeeds. IT is a bug that only affects building of the plugin-plugin (because it is using itself).

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

wrong project.
