### ISSUE TITLE
[MNG-695] Exceptions thrown building project information report "Source Repository"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3620]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** opened **[MNG-695](https://issues.apache.org/jira/browse/MNG-695?redirect=false)** and commented

(This was working yesterday.  This morning I updated my SVN tree to 227227 and this started happening.)

I am not currently using SCM features of Maven, so I do not have a developer connection defined.  In v1.0.2, I have always had an empty tag in the project.xml.

If the v2 POM has "\<developerConnection/>", I get the following exception:
[INFO] ----------------------------------------------------------------------------
[INFO] Diagnosis: Error during site generation
[INFO] ----------------------------------------------------------------------------
[ERROR] Cause:
org.apache.maven.plugin.MojoExecutionException: Error during site generation
at org.apache.maven.doxia.DoxiaMojo.execute(DoxiaMojo.java:491)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:361)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:378)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:359)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:341)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:229)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:123)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:209)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -4
at java.lang.String.substring(String.java:1768)
at java.lang.String.substring(String.java:1735)
at org.apache.maven.scm.manager.plexus.DefaultScmManager.findDelimiter(DefaultScmManager.java:218)
at org.apache.maven.scm.manager.plexus.DefaultScmManager.makeScmRepository(DefaultScmManager.java:118)
at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.getScmRepository(ScmReport.java:632)
at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderBody(ScmReport.java:200)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.ScmReport.executeReport(ScmReport.java:135)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:117)
at org.apache.maven.doxia.DoxiaMojo.execute(DoxiaMojo.java:290)
... 16 more

If a comment out the stanza, I get the following exception:
[INFO] ----------------------------------------------------------------------------
[INFO] Diagnosis: Error during site generation
[INFO] ----------------------------------------------------------------------------
[ERROR] Cause:
org.apache.maven.plugin.MojoExecutionException: Error during site generation
at org.apache.maven.doxia.DoxiaMojo.execute(DoxiaMojo.java:491)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:361)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:378)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:359)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:341)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:229)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:123)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:209)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: java.lang.NullPointerException
at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderDeveloperAccessSection(ScmReport.java:368)
at org.apache.maven.report.projectinfo.ScmReport$ScmRenderer.renderBody(ScmReport.java:212)
at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
at org.apache.maven.report.projectinfo.ScmReport.executeReport(ScmReport.java:135)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:117)
at org.apache.maven.doxia.DoxiaMojo.execute(DoxiaMojo.java:290)
... 16 more

---

**Affects:** 2.0-beta-1

**Comment by jira-importer** [comment]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** commented

I made the following changes to ScmReport.java to eliminate the problem:

In method renderDeveloperAccessSection, added the following at the top of the method:
if ( devRepository == null )
{
return;
}

In method getScmRepository, added the following after the check for scmUrl == null:
if ( scmUrl.equals("") )
{
return null;
}

I don't know if these changes are the best, but they do seem to work for me.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

was this already applied?

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Partially applied. Thanks!

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

changing resolution

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

application fixes the problem
