### ISSUE TITLE
[MNG-874] Cannot download plugin POM when auto-discovering plugins

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3676]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** opened **[MNG-874](https://issues.apache.org/jira/browse/MNG-874?redirect=false)** and commented

This issue is following the thread: [m2] using deployed plugin snapshots with new metadata

See attached test-plugin project.  Steps to reproduce:

1) Deploy the plugin: m2 -DupdateReleaseInfo=true clean:clean deploy

[mark@mark test-plugin]$ m2 -DupdateReleaseInfo=true clean:clean deploy
[INFO] Searching repository for plugin with prefix: 'clean'.
[INFO] ----------------------------------------------------------------------------
[INFO] Building hello:hello:maven-plugin:1.0
[INFO]    task-segment: [clean:clean, deploy]
[INFO] ----------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory c:\Documents and Settings\mark\Desktop\test-plugin\target
[INFO] [plugin:descriptor]
[INFO] [resources:resources]
[INFO] [compiler:compile]
Compiling 1 source file to c:\Documents and Settings\mark\Desktop\test-plugin\target\classes
[INFO] [resources:testResources]
[INFO] [compiler:testCompile]
[INFO] No sources to compile
[INFO] [surefire:test]
[INFO] Setting reports dir: c:\Documents and Settings\mark\Desktop\test-plugin\target/surefire-reports

---

T E S T S

---

There are no test to run.

Results :
[surefire] Tests run: 0, Failures: 0, Errors: 0

[INFO] [jar:jar]
[INFO] Building jar: c:\Documents and Settings\mark\Desktop\test-plugin\target\hello-1.0.jar
[INFO] [plugin:addPluginArtifactMetadata]
[INFO] [install:install]
[INFO] Installing c:\Documents and Settings\mark\Desktop\test-plugin\target\hello-1.0.jar to C:\Documents and Settings\m
ark\.m2\repository\hello\hello\1.0\hello-1.0.jar
[INFO] [deploy:deploy]
Uploading: file:target/test-repo/hello/hello/1.0/hello-1.0.jar
2K uploaded
[INFO] Retrieving previous metadata from test
[INFO] Uploading repository metadata for: 'hello'
[INFO] Retrieving previous metadata from test
[INFO] Uploading project information for hello 1.0
[INFO] Retrieving previous metadata from test
[INFO] Uploading repository metadata for: 'artifact hello:hello'
[INFO] ----------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Tue Sep 13 20:25:05 BST 2005
[INFO] Final Memory: 4M/12M
[INFO] ----------------------------------------------------------------------------

2) Clean all knowledge of plugin from local-repo:

rm -rf ~/.m2/repository/hello
rm ~/.m2/plugin-registry.xml

3) Attempt to auto-discover plugin: m2 -s settings.xml hello:hello

[mark@mark test-plugin]$ m2 -s settings.xml hello:hello
[INFO] Searching repository for plugin with prefix: 'hello'.
[INFO] hello: checking for updates from test
[INFO] hello: checking for updates from central-plugins
[INFO] artifact hello:hello: checking for updates from test
[INFO] artifact hello:hello: checking for updates from central-plugins
Downloading: http://repo1.maven.org/maven2/plugins/hello/hello/1.0/hello-1.0.pom
[WARNING]
***** Using defaults for missing POM hello:hello:pom:1.0 *****

Downloading: file:target/test-repo/hello/hello/1.0/hello-1.0.jar
2K downloaded
[INFO] ----------------------------------------------------------------------------
[INFO] Building hello:hello:maven-plugin:1.0
[INFO]    task-segment: [hello:hello]
[INFO] ----------------------------------------------------------------------------
[INFO] [hello:hello]
[INFO] *** Hello ***
[INFO] ----------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Sep 13 20:26:04 BST 2005
[INFO] Final Memory: 1M/3M
[INFO] ----------------------------------------------------------------------------

The plugin jar is successfully found, but not the POM..?

---

**Affects:** 2.0-beta-1

**Attachments:**
- [test-plugin.zip](https://issues.apache.org/jira/secure/attachment/12711721/test-plugin.zip) (_1.14 kB_)
- [test-plugin2.zip](https://issues.apache.org/jira/secure/attachment/12711584/test-plugin2.zip) (_1.29 kB_)

**Issue Links:**
- [MNG-1928](https://issues.apache.org/jira/browse/MNG-1928) ignores pluginRepository in settings.xml, honors in POM

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I verify the results, but the missing pom seems to just be a warning - it does find the one in the test repo. Leaving for b2.

**Comment by jira-importer** [comment]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** commented

It doesn't seem to be even finding the POM for me?  For example, see the attached test-plugin2.zip - I've added a commons-collections dependency and it's not being added to the classpath:

[mark@mark test-plugin]$ m2 -s settings.xml hello:hello
[INFO] Searching repository for plugin with prefix: 'hello'.
[INFO] hello: checking for updates from test
[INFO] hello: checking for updates from central-plugins
[INFO] artifact hello:hello: checking for updates from test
[INFO] artifact hello:hello: checking for updates from central-plugins
Downloading: http://repo1.maven.org/maven2/plugins/hello/hello/1.0/hello-1.0.pom
[WARNING]
***** Using defaults for missing POM hello:hello:pom:1.0 *****

Downloading: file:target/test-repo/hello/hello/1.0/hello-1.0.jar
2K downloaded
[INFO] ----------------------------------------------------------------------------
[INFO] Building hello:hello:maven-plugin:1.0
[INFO]    task-segment: [hello:hello]
[INFO] ----------------------------------------------------------------------------
[INFO] [hello:hello]

---

constituent[0]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/commons-cli-1.0.jar
constituent[1]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/commons-lang-1.0.jar
constituent[2]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/commons-logging-1.0.jar
constituent[3]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/doxia-sink-api-1.0-alpha-4.jar
constituent[4]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/jline-0.9.1.jar
constituent[5]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/jsch-0.1.21.jar
constituent[6]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-artifact-2.0-beta-1-SNAPSHOT.jar
constituent[7]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-artifact-manager-2.0-beta-1-SNAPSHOT.jar
constituent[8]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-core-2.0-beta-1-SNAPSHOT.jar
constituent[9]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-model-2.0-beta-1-SNAPSHOT.jar
constituent[10]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-monitor-2.0-beta-1-SNAPSHOT.jar
constituent[11]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-plugin-api-2.0-beta-1-SNAPSHOT.jar
constituent[12]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-plugin-descriptor-2.0-beta-1-SNAPSHOT.jar
constituent[13]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-plugin-registry-2.0-beta-1-SNAPSHOT.jar
constituent[14]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-profile-2.0-beta-1-SNAPSHOT.jar
constituent[15]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-project-2.0-beta-1-SNAPSHOT.jar
constituent[16]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-reporting-api-2.0-beta-1-SNAPSHOT.jar
constituent[17]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-repository-metadata-2.0-beta-1-SNAPSHOT.jar
constituent[18]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/maven-settings-2.0-beta-1-SNAPSHOT.jar
constituent[19]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/plexus-input-handler-1.0-alpha-2.jar
constituent[20]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/wagon-file-1.0-alpha-4.jar
constituent[21]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/wagon-http-lightweight-1.0-alpha-4.jar
constituent[22]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/wagon-provider-api-1.0-alpha-4.jar
constituent[23]: file:/c:/Progra~1/maven-2.0-SNAPSHOT/lib/wagon-ssh-1.0-alpha-4.jar

---

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/collections/FastArrayList
at HelloMojo.execute(HelloMojo.java:11)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:357)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:479)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:460)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:442)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:131)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:186)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:316)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Since this stops auto-discovery of plugins with dependencies shouldn't it be fixed for beta1?
