### ISSUE TITLE
[MNG-838] NumberFormatException while readung setting.xml

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3700]
**[Emmanuel Lécharny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elecharny)** opened **[MNG-838](https://issues.apache.org/jira/browse/MNG-838?redirect=false)** and commented

When I create a setting.xml, using the empty one provided on the site, I get a nasty NumberFormatException :
java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
at java.lang.Integer.parseInt(Integer.java:468)
at java.lang.Integer.valueOf(Integer.java:553)
at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.getIntegerValue(SettingsXpp3Reader.java:148)
at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.parseProxy(SettingsXpp3Reader.java:451)
at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.parseSettings(SettingsXpp3Reader.java:601)
at org.apache.maven.settings.io.xpp3.SettingsXpp3Reader.read(SettingsXpp3Reader.java:979)
at org.apache.maven.settings.DefaultMavenSettingsBuilder.readSettings(DefaultMavenSettingsBuilder.java:89)
at org.apache.maven.settings.DefaultMavenSettingsBuilder.buildSettings(DefaultMavenSettingsBuilder.java:110)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

The setting.xml is pretty simple :
\<settings>
\<localRepository>$HOME/.m2/repository\</localRepository>
\<offline/>
\<proxies/>
\<proxy>
\<active/>
\<protocol/>
\<username/>
\<password/>
\<port/>
\<host/>
\<nonProxyHosts/>
\</proxy>
\</proxies>
\<servers>
\<server>
\<id/>
\<username/>
\<password/>
\<privateKey/>
\<passphrase/>
\</server>
\</servers>
\<mirrors>
\<mirror>
\<id/>
\<mirrorOf/>
\<name/>
\<url/>
\</mirror>
\</mirrors>
\<profiles>
\<profile>
\<id/>
\<activation>
\<jdk/>
\<activationProperty>
\<name/>
\<value/>
\</activationProperty>
\</activation>
\<properties/>
\<repositories>
\<repository>
\<id/>
\<name/>
\<url/>
\<snapshotPolicy/>
\<layout/>
\</repository>
\</repositories>
\<pluginRepositories>
\<repository>
\<id/>
\<name/>
\<url/>
\<snapshotPolicy/>
\<layout/>
\</repository>
\</pluginRepositories>
\</profile>
\</profiles>
\<activeProfiles/>
\</settings>

---

**Affects:** 2.0-alpha-3

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

parsing of port
