### ISSUE TITLE
[MNG-716] Bootstrap fails with Exception in thread "main" java.lang.OutOfMemoryError: unable to create new native thread.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3775]
**[Joakim Erdfelt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joakime)** opened **[MNG-716](https://issues.apache.org/jira/browse/MNG-716?redirect=false)** and commented

When kicking off "sh ./m2-bootstrap-all.sh" the following error occurs.
Deleting the following directories does not help
/home/joakim/java/maven-*
/home/joakim/.m2/repository

This occurs consistently, and in the same spot, with the same stack trace.
Setting the MAVEN_OPTS to "-Xmx512m -Xss100m" makes no difference in the process.

When inspecting the contents of classworlds-1.1-alpha-1.pom it always downloads it successfully, and is identical (via diff and md5sum check) to what's on the www.ibiblio.org/maven2/ repo.

---

Building mboot ...

---

---

Building maven2 components ...

---

Maven installation directory: /home/joakim/java/maven-2.0-SNAPSHOT
Using the following for your local repository: /home/joakim/.m2/repository
Using the following for your remote repository: http://repo1.maven.org/maven2, http://snapshots.maven.codehaus.org/maven2/
Installing POM: /home/joakim/.m2/repository/org/apache/maven/maven/2.0-beta-1-SNAPSHOT/maven-2.0-beta-1-SNAPSHOT.pom
Installing POM: /home/joakim/.m2/repository/org/apache/maven/plugins/maven-plugin-parent/2.0-beta-1-SNAPSHOT/maven-plugin-parent-2.0-beta-1-SNAPSHOT.pom
Installing POM: /home/joakim/.m2/repository/org/apache/maven/maven-plugin-tools/2.0-beta-1-SNAPSHOT/maven-plugin-tools-2.0-beta-1-SNAPSHOT.pom
Installing POM: /home/joakim/.m2/repository/org/apache/maven/maven-script/2.0-beta-1-SNAPSHOT/maven-script-2.0-beta-1-SNAPSHOT.pom
Installing POM: /home/joakim/.m2/repository/org/apache/maven/reporting/maven-reporting/2.0-beta-1-SNAPSHOT/maven-reporting-2.0-beta-1-SNAPSHOT.pom
Downloading http://repo1.maven.org/maven2/classworlds/classworlds/1.1-alpha-1/classworlds-1.1-alpha-1.pom
Exception in thread "main" java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start(Native Method)
at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:89)
at java.security.AccessController.doPrivileged(Native Method)
at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:75)
at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:382)
at sun.net.www.http.HttpClient.finished(HttpClient.java:370)
at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:72)
at sun.net.www.MeteredStream.justRead(MeteredStream.java:66)
at sun.net.www.MeteredStream.read(MeteredStream.java:107)
at java.io.FilterInputStream.read(FilterInputStream.java:111)
at java.io.FilterInputStream.read(FilterInputStream.java:90)
at download.HttpUtils.getFile(HttpUtils.java:279)
at download.HttpUtils.getFile(HttpUtils.java:155)
at download.HttpUtils.getFile(HttpUtils.java:104)
at download.ArtifactDownloader.getRemoteArtifact(ArtifactDownloader.java:189)
at download.ArtifactDownloader.downloadDependencies(ArtifactDownloader.java:91)
at model.ModelReader.retrievePom(ModelReader.java:477)
at model.ModelReader.resolveDependencies(ModelReader.java:412)
at model.ModelReader.endElement(ModelReader.java:384)
at org.apache.crimson.parser.Parser2.maybeElement(Parser2.java:1720)
at org.apache.crimson.parser.Parser2.parseInternal(Parser2.java:667)
at org.apache.crimson.parser.Parser2.parse(Parser2.java:337)
at org.apache.crimson.parser.XMLReaderImpl.parse(XMLReaderImpl.java:448)
at javax.xml.parsers.SAXParser.parse(SAXParser.java:345)
at util.AbstractReader.parse(AbstractReader.java:63)
at MBoot.run(MBoot.java:309)
at MBoot.main(MBoot.java:120)

---

**Affects:** 2.0-beta-1

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I am almost certain this is a system configuration error. It's not a memory problem (Java report OOME for lack of file descriptors and threads as well).

You might need to google this one a bit. FWIW, it builds on FC4 for me.
