### ISSUE TITLE
[MNG-714] When artifact not found on mirror the real site isn't checked

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3777]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** opened **[MNG-714](https://issues.apache.org/jira/browse/MNG-714?redirect=false)** and commented

I'm using the settings.xml mirror feature as a local cache. Periodically I upload my local repo
to the webserver specified as mirror.

When an artifact cannot be found on the mirror, the original site isn't checked (and possibly the rest of the sites).

I'm not sure what the exact function of the mirror is (except caching?), but repo1 is checked often regardless
of mirror presence, so I figure it's not meant to totally disable checking the central repo's.

Simple reproduction: define a few mirrors in your settings.xml for central, central-plugins and snapshots, pointing to
say file://tmp/empty/dir/.

Stacktrace:

[DEBUG] Error resolving artifact version from metadata.
org.apache.maven.wagon.ResourceDoesNotExistException: Unable to locate resource in repository
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:81)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:70)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:343)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadata(DefaultWagonManager.java:263)
at org.apache.maven.artifact.metadata.AbstractVersionArtifactMetadata.retrieveFromRemoteRepository(AbstractVersionArtifactMetadata.java:93)
at org.apache.maven.artifact.transform.AbstractVersionTransformation.retrieveFromRemoteRepository(AbstractVersionTransformation.java:171)
at org.apache.maven.artifact.transform.AbstractVersionTransformation.resolveVersion(AbstractVersionTransformation.java:96)
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForResolve(SnapshotTransformation.java:43)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:95)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:290)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:274)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:81)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:186)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:70)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:197)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:185)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:156)
at org.apache.maven.plugin.DefaultPluginManager.ensurePluginContainerIsComplete(DefaultPluginManager.java:544)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:479)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:334)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:378)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:351)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:337)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:229)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:123)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:209)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: java.io.FileNotFoundException: http://MY_MIRROR_SITE/maven2/repository/plexus/plexus-compiler-manager/1.5-SNAPSHOT/plexus-compiler-manager-1.5-SNAPSHOT.version.txt
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:798)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:71)
... 35 more
[DEBUG] Skipping disabled repository central
Downloading: http://MY_MIRROR_SITE/maven2/repository/plexus/plexus-compiler-manager/1.5-SNAPSHOT/plexus-compiler-manager-1.5-SNAPSHOT.pom
[WARNING] Unable to get resource from repository http://snapshots.maven.codehaus.org/maven2
[WARNING]
***** Using defaults for missing POM plexus:plexus-compiler-manager:pom:1.5-SNAPSHOT *****

[DEBUG]   plexus:plexus-compiler-manager:jar:1.5-SNAPSHOT (selected for runtime)
[DEBUG] Skipping disabled repository central
Downloading: http://MY_MIRROR_SITE/maven2/repository/plexus/plexus-compiler-manager/1.5-SNAPSHOT/plexus-compiler-manager-1.5-SNAPSHOT.jar
[WARNING] Unable to get resource from repository http://snapshots.maven.codehaus.org/maven2
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Diagnosis: Error configuring plugin for execution of 'compiler:compile'.
[INFO] ----------------------------------------------------------------------------
[ERROR] Cause:
org.apache.maven.plugin.MojoExecutionException: Error configuring plugin for execution of 'compiler:compile'.
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:339)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:378)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:351)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:337)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:229)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:123)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:209)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Cannot resolve plugin dependencies
at org.apache.maven.plugin.DefaultPluginManager.ensurePluginContainerIsComplete(DefaultPluginManager.java:579)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:479)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:334)
... 15 more
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to download the artifact from any repository
plexus:plexus-compiler-manager:1.5-SNAPSHOT:jar

from the specified remote repositories:
http://repo1.maven.org/maven2, http://snapshots.maven.codehaus.org/maven2
Path to dependency:
1) org.apache.maven.plugins:maven-compiler-plugin:maven-plugin:2.0-beta-1-SNAPSHOT

2) plexus:plexus-compiler-manager:jar:1.5-SNAPSHOT

   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:132)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:204)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:185)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:156)
   at org.apache.maven.plugin.DefaultPluginManager.ensurePluginContainerIsComplete(DefaultPluginManager.java:544)
   ... 17 more

Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:233)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:115)
... 22 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Aug 09 10:39:58 CEST 2005
[INFO] Final Memory: 2M/4M
[INFO] ------------------------------------------------------------------------

---

**Affects:** 2.0-beta-1

**Attachments:**
- [MNG-714-maven-artifact-manager.patch](https://issues.apache.org/jira/secure/attachment/12712067/MNG-714-maven-artifact-manager.patch) (_6.06 kB_)

**Issue Links:**
- [MNG-3533](https://issues.apache.org/jira/browse/MNG-3533) Unreachable mirror should cause Maven to fall back to the original repository
 (_**"is duplicated by"**_)
- [MNG-3772](https://issues.apache.org/jira/browse/MNG-3772) mirrors should allow specifying multiple alternate locations
 (_**"is duplicated by"**_)
- [MNG-2999](https://issues.apache.org/jira/browse/MNG-2999) Receiving a 403 response from a mirror server should attempt other mirrors
 (_**"is duplicated by"**_)

12 votes, 9 watchers

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

that the original is not checked is by design, but it is a good idea that it check the original as a backup.

**Comment by jira-importer** [comment]
**[Trygve Laugstøl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trygvis@inamo.no)** commented

I'm not sure I agree Brett, people use mirror to avoid going to Ibiblio in case it's firewalled or just down. If people want to check two repositories list both mirror and the mirrored repository as primiary (non-mirrored) repositories.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

listing both will check both every time, looking for the newest. The mirror is meant to be a closer mirror to use primarily but that should be identical to the other one, sO think this makes sense.

If we don't do this, we might as well get rid of mirrors and just use repository overrides, which is what you are referring to.

**Comment by jira-importer** [comment]
**[Trygve Laugstøl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trygvis@inamo.no)** commented

As long as I get the ability to not go to ibiblio, I'm fine with this beeing a feature, I do see the value.

**Comment by jira-importer** [comment]
**[Edwin Punzalan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elpunzalan)** commented

I'm attaching a patch to fix this.

The patch iterates through all the configured mirrors, in case there are more than one mirror for a certain repository id, and when all the mirrors fails, the original repository is then checked.

**Comment by jira-importer** [comment]
**[Szczepan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=szczepiq@gmail.com)** commented

There are number reasons this is a valuable feature:

-ability to implement simple fail-over system with two mirrors mirroring the same repo(s)
-currently, if there are mirrors with the same value of "mirrorOf", last mirror wins and previous mirrors are silently ignored. Not very nice...
-some folks from my company have to change the settings file every time they go home because at home they don't have proxy. Quite annoying...

Is it going to be released into maven? Is "improving maven" in the agenda of maven roadmap?

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

The real mirror is not checked on purpose. The way repository managers work these days would break severely if we started doing this.

**Comment by jira-importer** [comment]
**[John Bäckstrand](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sandos)** commented

Is there any more long-winded explanation this is not fixed? How exactly would this break repository managers?

"-some folks from my company have to change the settings file every time they go home because at home they don't have proxy. Quite annoying..." is my exact situation, too.

**Comment by jira-importer** [comment]
**[Igor Dvorzhak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=medb)** commented

Why this issue is closed? Was something done to address failover to mirrored repository if mirror not accessible or artifact is not present in mirror.

Looks like this is a must have feature taking into account that "mirroring the entire central repository is not allowed":
https://maven.apache.org/guides/mini/guide-mirror-settings.html
