### ISSUE TITLE
[MNG-687] Crash: in source-plugin, using assembly:assembly goal, on non-SNAPSHOT project.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3793]
**[Joakim Erdfelt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joakime)** opened **[MNG-687](https://issues.apache.org/jira/browse/MNG-687?redirect=false)** and commented

When using the assembly:assembly plugin, the following Exception occurs.

java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableCollection.add(Collections.java:1004)
at org.apache.maven.project.MavenProject.addAttachedArtifact(MavenProject.java:1016)
at org.apache.maven.plugin.source.JarSourceMojo.execute(JarSourceMojo.java:106)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:361)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:378)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:351)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:437)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:373)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:359)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:341)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:229)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:123)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:209)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:267)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:303)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:243)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:416)
at org.codehaus.classworlds.Launcher.main(Launcher.java:363)

Attached is an example project that shows this behaviour.

I used the commands
$ m2 clean:clean package
$ m2 assembly:assembly

---

**Affects:** 2.0-beta-1

**Attachments:**
- [assembly-unmodifiable-exception.tar.gz](https://issues.apache.org/jira/secure/attachment/12711925/assembly-unmodifiable-exception.tar.gz) (_1.12 kB_)

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

modified the clone of a MavenProject to have a modifyable attachment list
