### ISSUE TITLE
[MNG-897] allows use of Ant build files

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3800]
**[Chris Berry](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cberry)** opened **[MNG-897](https://issues.apache.org/jira/browse/MNG-897?redirect=false)** and commented

Per John Casey, This is logged to that it stays on the radar.
Please consider incorporating my antfile plugin.

I have included the following in the ZIP
maven-antrun-plugin --> the basic antrun w/ a few small mods
maven-antfile-plugin
maven-axisant-plugin --> an example plugin using the antfile plugin
axis-master --> a "grouping" plugin for axis example
my-app --> an example app using the axisant plugin.

Cheers,
- Chris

---

**Affects:** 2.0-alpha-3

**Attachments:**
- [antfile.zip](https://issues.apache.org/jira/secure/attachment/12711792/antfile.zip) (_52.12 kB_)

**Comment by jira-importer** [comment]
**[Davy Toch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dtoch)** commented

Question : shouldn't the POM files in antfile.zip have \<project> as root instead of \<model>? If the latter works, then there is something fishy going on in M2 :-).

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I'm actually thinking we may want to separate the metadata bindings into a separate file to accompany the script. This would achieve the following:

1. Don't have to fire up an Ant instance just to retrieve the [relatively speaking] miniscule metadata.
2. Don't want to support ant imports and other complex features for metadata...this should be **very** easy to read.
3. The syntax I laid out above was hackish at best.
4. I don't want to process an embedded metadata definition using DOM or somesuch and have Ant people asking why ant-import isn't working...it's too unintuitive.

I think it may be better to simply separate the metadata physically to keep from introducing any implications/expectations about how that metadata is processed by the plugin tool. We can use a naming convention of:

foo-build.xml................................plugin script
foo-build.bindings.xml...............plugin metadata (bindings to m2)

This is something we've been discussing a little bit on the IRC channel, and it seems like the least of all evils to me.

WDYT?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

The plugin will have at least one build.xml and at least one build.metadata.xml file (they may be named differently, but '.xml' and '.metadata.xml' suffixes must be preserved). The build.xml will contain at least one target that you want to execute as a mojo...this target may be the default target, if you wish. The build.metadata.xml will contain a set of mojo definitions, including parameters, various build system requirements (like online status, a valid project, etc.), and a mapping element from each mojo definition to a target in the corresponding build.xml script. If this mapping element is left off, the default target is assumed.

The POM plugin definition for using an Ant-based mojo will look exactly like it would for any type of mojo. The mojo implementation language is abstracted away from the user.

I'll post more specifics about the metadata file, etc. once I have this tested.

**Comment by jira-importer** [comment]
**[Yann Le Du](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=le.du.yann@gmail.com)** commented

Apart from avoiding writing a Maven plugin when you don't know how, I see two reasons why you would want to call Ant scripts from Maven :

* You have an Ant script which configures your project for the developement environment. The production team uses the same Ant script to configure the project for the production environment, and they * won't * use Maven. Obviously, you don't want to duplicate your scripting into an Ant script AND a Maven plugin, because you would have to synchronize every modification. So you will go on with the Ant script.

* You want to quickly "mavenize" a highly-Ant-dependent project - and prove this is worth and painless :) In a first phase, you only want to write POMs, and keep all your existing do-some-obscure-tasks Ant scripts (but keeping in mind that you'll replace them by Maven plugins later)

In both cases, it would be great to leave the existing Ant script alone, and only write some calling code. It seems to me that John's foo-build.xml and foo-build.bindings.xml fully fills this need. foo-build.xml could as well be an existing Ant script... Am I wrong ?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Yann, your examples are best covered by using the antrun plugin:

\<configuration>
\<tasks>
\<ant file="build.xml" target="foo" />
\</tasks>
\</configuration>
Can we please use a wiki for this in future. JIRA is not suited to reading design discussions.

**Comment by jira-importer** [comment]
**[Chris Berry](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cberry)** commented

I realize that I inadvertently inluded the module; maven-antfile-plugin, when building the ZIP. Please note that this module should be ignored::
So it is::
maven-antrun-plugin --> the basic antrun w/ a few small mods (INCLUDES ALL PIECES)
maven-antfile-plugin <=== IGNORE THIS -- WON'T COMPILE -- IS SUPERFLUOUS
maven-axisant-plugin --> an example plugin using the antfile plugin
axis-master --> a "grouping" plugin for axis example
my-app --> an example app using the axisant plugin.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

do we expect this to be completed for 2.0?

Given that it can be added to the plugin-plugin without waiting for 2.1 I'm wondering if its worth pushing out for now to make sure we get it right...

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Depending on how much time I get to work on this in the near future (I'm not anticipating much), I'd agree. I would definitely rather take a little extra time and vet this addition thoroughly, since it's likely that many people will be screaming if it doesn't work well...

We can release separately with the plugin-plugin 2.0.1 or something, without needing to release maven itself.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

It's ready, but we need to work out the versioning for its release, and it will depend on a new release of the plugin-plugin, to use the new version of maven-plugin-tools-api, upon which maven-plugin-tools-ant depends.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Should this be closed John?

**Comment by jira-importer** [comment]
**[Robert Watts](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wattsie)** commented

IMO I don't think this should be closed.  This is still happening on 2.0.1.

This is completely reproducable using the latest download with a clean install using the following doc
http://maven.apache.org/guides/plugin/guide-ant-plugin-development.html

upon mvn install for the hello world example...

[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] org.apache.maven.tools.plugin.extractor.AbstractScriptedMojoDescriptorExtractor.extractMojoDescriptors(Ljava/util/Map;Lorg/apache/maven/plugin/descriptor/PluginDescriptor;)Ljava/util/List;
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.AbstractMethodError: org.apache.maven.tools.plugin.extractor.AbstractScriptedMojoDescriptorExtractor.extractMojoDescriptors(Ljava/util/Map;Lorg/apache/maven/plugin/descriptor/PluginDescriptor;)Ljava/util/List;
at org.apache.maven.tools.plugin.extractor.AbstractScriptedMojoDescriptorExtractor.execute(AbstractScriptedMojoDescriptorExtractor.java:32)
at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:69)
at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:99)

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

forgot to close this. See documentation at http://maven.apache.org/guides/index.html, under developer documentation or plugin documentation...once Maven 2.0.2 is released.

**Comment by jira-importer** [comment]
**[Gregory Block](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gblock)** commented

Maven 2.0.2 is released - but this is still bust.  Worse yet, I can't even figure out, if I were going to file a new bug on it, where that bug should go.

Can someone update this with a plan of action to get this fixed?  Do we wait for the next version?  Do we have to use a snapshot?  This has been mentioned in the mailing list over the last few days, and continues to be a problem - but it doesn't seem to be a part of the standard test cases that are used.

We're frustrated here, because we're not even sure if people are admitting that there's a problem at the moment - are we waiting for a release of the plugin, or is it this component's responsibility?  We can't even see if anything's going on, and despite the fact that there was a comment on this bug saying that it was still broken on 2.0.1, it didn't get tested on snapshot or bits of the system just haven't been pushed live...  I suppose it's partially my fault for not testing a 2.0.2 snapshot and filing, but it's not clear from available documentation how exactly one goes about testing a release where some dependencies may not be updated on the live servers as a part of a 2.0.2 deploy - which is what I'm guessing is the case here?  I just don't know, and there isn't enough information in documentation to let me provide any useful information on the state of a pre-release build.

I'm worried mostly because we're supposed to be moving our project to this framework - but versioning in maven feels pretty fragile.  Shouldn't this have been caught?  What do we have to do to get a fix?  Where's the right place to file a bug for this component?  Who's responsible?  Where is it in the release plan?

I hope someone can help - at least to look at the problem and tell me what's going on, and help us figure out what we can do to help.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I'm told mvn -U install on the first run will ensure that it works.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

oops, awaiting release of newest maven-plugin-plugin (will be 2.1)
