### ISSUE TITLE
[MNG-734] java.lang.InstantiationException while deploying snapshot

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3807]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** opened **[MNG-734](https://issues.apache.org/jira/browse/MNG-734?redirect=false)** and commented

Setting up a project to deploy a snapshot.  From comments of others, I have a bad POM in one of my dependencies (haven't tracked that down yet).

When I set the project's version to "3.0", the jar is deployed properly.

When I set the project's version to "3.0-SNAPSHOT", I get the following stack dump:
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Diagnosis: Error configuring plugin for execution of 'deploy:deploy'.
[INFO] ----------------------------------------------------------------------------
[ERROR] Cause:
org.apache.maven.plugin.MojoExecutionException: Error configuring plugin for execution of 'deploy:deploy'.
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:342)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:445)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:431)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:127)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:186)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:292)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse the created DOM for plugin configuration
at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1022)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:522)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:337)
... 15 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Class 'org.apache.maven.artifact.repository.ArtifactRepository' cannot be instantiated
at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject(AbstractConfigurationConverter.java:120)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:83)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:118)
at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:55)
at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1017)
... 17 more
Caused by: java.lang.InstantiationException: org.apache.maven.artifact.repository.ArtifactRepository
at java.lang.Class.newInstance0(Class.java:335)
at java.lang.Class.newInstance(Class.java:303)
at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject(AbstractConfigurationConverter.java:110)
... 21 more

---

**Affects:** 2.0-beta-1

**Issue Links:**
- [MNG-761](https://issues.apache.org/jira/browse/MNG-761) fallback to deployment repository for snapshots when there is no snapshot repository
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** commented

Exception is thrown because org.apache.maven.artifact.repository.ArtifactRepository is an interface.

To try to see what is happening, I added a System.out.println at the beginning of AbstractConfigurationConverter.instantiateObject (the method throwing the exception) to see every time an object is being created this way.  When deploying a release, no objects are created using this method while configuring the deploy plugin.  When deploying a snapshot, an attempt is made to instantiate this interface.

**Comment by jira-importer** [comment]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** commented

I have simplified my POM to the following:
\<project>
\<modelVersion>4.0.0\</modelVersion>
\<groupId>qaccess\</groupId>
\<artifactId>log4j\</artifactId>
\<packaging>jar\</packaging>
\<version>3.0-SNAPSHOT\</version>
\<name>Q.Access log4j Interface\</name>
\<dependencies>
\<dependency>
\<groupId>log4j\</groupId>
\<artifactId>log4j\</artifactId>
\<version>1.2.8\</version>
\<type>jar\</type>
\<scope>provided\</scope>
\</dependency>
\</dependencies>
\</project>

I am still getting the exception while deploying the snapshot.

**Comment by jira-importer** [comment]
**[Trygve Laugstøl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trygvis@inamo.no)** commented

Thanks, a real test case like this makes it easier to debug the problem.

**Comment by jira-importer** [comment]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** commented

I renamed "deploymentRepository" to "ploymentRepository" so that it comes after "localRepository" during processing.  This allows me to look at the method calls for both configuration elements.  The method calls look identical, yet "localRepository" gets configured correctly and "ploymentRepository" causes an exception.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Just reading up on this, and I have a couple questions:

1. Do you specify a repository entry in your \<distributionManagement/> section of your POM?

2. Do you specify a snapshotRepository element in that same section?

If #1 but not #2, then the problem has a simple solution. Recently, we've separated snapshot repositories from release repositories, to aid in maintaining cleaner copies of each (snapshots are easier to cull if all you're dealing with is snapshots, for example). SO, this means where you would've used the repository entry in \<distributionManagement/> when your version didn't include -SNAPSHOT, you'll have to have a corresponding entry called \<snapshotRepository/> in there as well if you want to handle SNAPSHOT deployment.

FYI, the reason the configuration was failing with that somewhat cryptic message is because it tried to evaluate ${localRepository} using MavenSession.getLocalRepository() (this returns either repository or snapshotRepository, depending on project version)...when ${localRepository} evaluated to null, it tried to create a new instance of the type specified by the deployment plugin's localRepository parameter.

Clearly, we need to improve error diagnosis and feedback for this type of problem. However, simply adding \<snapshotRepository/> (the full section inside \<distributionManagement/>...this looks just like the \<repository/> section) SHOULD solve your particular problem.

**Comment by jira-importer** [comment]
**[Bob Allison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=allisonb)** commented

Well, that description does explain why when I simplified my POM for testing I started geting the exception for both snapshots and releases.  Adding the snapshot repository reference fixed the problem.

For the record, the working minimal test POM is:
\<project>
\<modelVersion>4.0.0\</modelVersion>
\<groupId>qaccess\</groupId>
\<artifactId>log4j\</artifactId>
\<packaging>jar\</packaging>
\<version>3.0-SNAPSHOT\</version>
\<name>Q.Access log4j Interface\</name>
\<dependencies>
\<dependency>
\<groupId>log4j\</groupId>
\<artifactId>log4j\</artifactId>
\<version>1.2.8\</version>
\<type>jar\</type>
\<scope>provided\</scope>
\</dependency>
\</dependencies>
\<distributionManagement>
\<repository>
\<id>qadev\</id>
\<name>Q.Access Release Repository\</name>
\<url>scp://cvs.host.machine/path/to/m2/release\</url>
\</repository>
\<snapshotRepository>
\<id>qadev\</id>
\<name>Q.Access Development Repository\</name>
\<url>scp://cvs.host.machine/path/to/m2/snapshot\</url>
\</snapshotRepository>
\</distributionManagement>
\</project>
