### ISSUE TITLE
[MNG-2352] Upgrade to plexus-container-default-alpha-10

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3874]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** opened **[MNG-2352](https://issues.apache.org/jira/browse/MNG-2352?redirect=false)** and commented

This is required for MNG-2201 in particular.

---

**Attachments:**
- [MNG-2352.diff](https://issues.apache.org/jira/secure/attachment/12711996/MNG-2352.diff) (_8.34 kB_)

**Issue Links:**
- [MNG-2201](https://issues.apache.org/jira/browse/MNG-2201) Interpolation problem when using surefire
 (_**"is depended upon by"**_)

2 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

PLX-223 was a blocker

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

This fixes it for me.

Note that bumping to plexus alpha 10 snapshot breaks it0043 if I don't specify a mirror !

Using a mirror and the test passes again:

FATAL ERROR: Unable to configure the Maven application
Error stacktrace:
org.apache.maven.reactor.MavenExecutionException: The plugin 'org.apache.maven.plugins:maven-resources-plugin' does not exist or no valid version could be found
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:165)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:699)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:372)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.lifecycle.LifecycleExecutionException: The plugin 'org.apache.maven.plugins:maven-resources-plugin' does not exist or no valid version could be found
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1281)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindLifecycleForPackaging(DefaultLifecycleExecutor.java:1011)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:975)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:453)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:364)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
... 10 more
Caused by: org.apache.maven.plugin.version.PluginVersionNotFoundException: The plugin 'org.apache.maven.plugins:maven-resources-plugin' does not exist or no valid version could be found
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersionManager.java:225)
at org.apache.maven.plugin.version.DefaultPluginVersionManager.resolvePluginVersion(DefaultPluginVersionManager.java:87)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:158)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1252)
... 19 more
0/1 passed

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I get a component lookup problem (which applying PLX-223 doesn't seem to fix)

Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository: org.apache.maven.Mave
n.
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:69)

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

Brett,

Nothing else interesting in the stack trace? What does trigger this lookup ?

I created the patch on the trunk.  So the problem could either be an incompatibility, or something that changed in the past 2 weeks. Will try to look at it again.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

nothing else interesting in the trace. This is basically the first lookup of the app in the CLI.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

We'll be sticking with the alpha-9-stable in the branch. The trunk uses the latest.
