### ISSUE TITLE
[MNG-2295] Stack trace is printed during download when a SocketException happens

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3918]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[MNG-2295](https://issues.apache.org/jira/browse/MNG-2295?redirect=false)** and commented

It should just print the error and not the stack trace

[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
Downloading: http://repo.mergere.com/maven2/commons-pool/commons-pool/1.2/commons-pool-1.2.pom
4K downloaded
Downloading: http://repo.mergere.com/maven2/xerces/xerces/2.0.2/xerces-2.0.2.pom
311b downloaded
Downloading: http://repo.mergere.com/maven2/xerces/xercesImpl/2.0.2/xercesImpl-2.0.2.pom
150b downloaded
Downloading: http://repo.mergere.com/maven2/com/jamonapi/jamon/1.0/jamon-1.0.pom
149b downloaded
Downloading: http://repo.mergere.com/maven2/xdoclet/xjavadoc/1.1/xjavadoc-1.1.pom
1K downloaded
Downloading: http://repo.mergere.com/maven2/ant/ant/1.5.2/ant-1.5.2.pom
140b downloaded
Downloading: http://repo.mergere.com/maven2/com/jamonapi/jamon/1.0/jamon-1.0.jar
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:168)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:256)
at java.io.BufferedInputStream.read(BufferedInputStream.java:313)
at sun.net.www.MeteredStream.read(MeteredStream.java:116)
at java.io.FilterInputStream.read(FilterInputStream.java:111)
at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:2139)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:290)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:199)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:182)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:80)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:369)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:282)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:244)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:124)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:233)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:211)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:182)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1117)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:366)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

GET request of: com/jamonapi/jamon/1.0/jamon-1.0.jar from central failed
com.jamonapi:jamon:jar:1.0

from the specified remote repositories:
central (http://repo.mergere.com/maven2)
Path to dependency:
1) org.springframework:spring-aop:jar:2.0-SNAPSHOT
2) com.jamonapi:jamon:jar:1.0

Caused by I/O exception: Connection reset

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20 seconds
[INFO] Finished at: Sun May 14 23:45:43 PDT 2006
[INFO] Final Memory: 8M/27M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.4

**Issue Links:**
- [MNG-2282](https://issues.apache.org/jira/browse/MNG-2282) If a repo is down, maven stops the buid instead of trying other repos
 (_**"is superceded by"**_)

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

All global fatal errors are printed as stacktraces. After fixing MNG-2285, which is marked as related,
this error goes away.

You still get a stacktrace though, if a parent pom can't be resolved, or if a pom is missing a groupId.

Should we create a new issue with a more global description, like 'never print stacktraces
if -e or -X not specified', or re-open this one and rename it? Closing for now since the problem this issue
describes is fixed.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Fixed as part of MNG-2282
