### ISSUE TITLE
[MNG-2285] local repository path cannot have special characters

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3926]
**[Ravi Varanasi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ravi116)** opened **[MNG-2285](https://issues.apache.org/jira/browse/MNG-2285?redirect=false)** and commented

When there are special characters in the \<localrepository> path and  running the command **mvn clean**.causes  the exception
&mdash;
java.lang.NullPointerException
at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginM
anager.java:295)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(De
faultPluginManager.java:200)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPlug
inManager.java:165)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(Defa
ultLifecycleExecutor.java:1218)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor
(DefaultLifecycleExecutor.java:1430)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.segmentTaskListBy
AggregationNeeds(DefaultLifecycleExecutor.java:378)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:134)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375) 

&mdash;
Attached is the settiings.xml.

---

**Affects:** 2.0.2

**Attachments:**
- [settings.xml](https://issues.apache.org/jira/secure/attachment/12711700/settings.xml) (_8.66 kB_)

**Issue Links:**
- [MNG-3607](https://issues.apache.org/jira/browse/MNG-3607) Class loaders employed by Maven return invalid URLs to resources
 (_**"depends upon"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

This is a side effect of MNG-3607. Class loaders fail to load stuff from broken URLs like `file:/C:/Documents and Settings/#rvarana/.m2/repository/org/apache/maven/plugins/maven-clean-plugin/2.3/maven-clean-plugin-2.3.jar`. So while the artifacts themselves end up in the proper location, Maven isn't able to read any classes/resources from them.
