### ISSUE TITLE
[MNG-2731] Regression: new container handling cannot locate resources properly

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3940]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-2731](https://issues.apache.org/jira/browse/MNG-2731?redirect=false)** and commented

Run: mvn project-info-reports:scm on any Maven project.

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Can't find bundle for base name project-info-report, locale en_AU
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: Can't find bundle for base name project-info-report, locale en_AU
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:315)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:141)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:550)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:346)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: java.util.MissingResourceException: Can't find bundle for base name project-info-report, locale en_AU
at org.codehaus.plexus.i18n.DefaultI18N.cacheBundle(DefaultI18N.java:394)
at org.codehaus.plexus.i18n.DefaultI18N.getBundle(DefaultI18N.java:157)
at org.codehaus.plexus.i18n.DefaultI18N.getString(DefaultI18N.java:206)
at org.apache.maven.report.projectinfo.ScmReport.getName(ScmReport.java:68)
at org.apache.maven.report.projectinfo.AbstractProjectInfoReport.execute(AbstractProjectInfoReport.java:158)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:435)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:311)
... 11 more

This works in Maven 2.0.4/2.0.5-SNAPSHOT, but not on trunk.

---

**Affects:** 3.0-alpha-1

**Attachments:**
- [doxia-site-renderer-MNG-2731.diff](https://issues.apache.org/jira/secure/attachment/12712357/doxia-site-renderer-MNG-2731.diff) (_1.06 kB_)
- [maven-project-info-reports-plugin-MNG-2731.diff](https://issues.apache.org/jira/secure/attachment/12712020/maven-project-info-reports-plugin-MNG-2731.diff) (_980 bytes_)

**Issue Links:**
- [MPIR-60](https://issues.apache.org/jira/browse/MPIR-60) Current head throws NPE when generating reports

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I tried `mvn site` with 2.0.x and 2.1-SNAPSHOT and I got the NPE.
The pb seems to come in plexus (maybe plexus-container-default) when we upgraded plexus-i18n from 1.0.6 to 1.0-beta-7-SNAPSHOT in doxia-site-renderer

It is the same, if we used in doxia-site-renderer:
plexus-i18n:1.0.6
plexus-velocity:1.1.4

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

This issue seems to be related to plexus, via doxia. These patches excludes some plexus artifacts in doxia.
Works **only** for maven 2.0.x. With maven 2.1-snap, I got another exception:

```
 
org.apache.maven.BuildFailureException: Can't find bundle for base name project-info-report, locale en
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:276)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:109)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:520)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:341)
...
```
