### ISSUE TITLE
[MNG-2266] NPE in MAven Settings writer

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3945]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** opened **[MNG-2266](https://issues.apache.org/jira/browse/MNG-2266?redirect=false)** and commented

With a settings.xml like this :

```
 
<settings>
  <localRepository>/home/m2/repositories/local</localRepository>
  <proxies>
    <proxy>
      <active>true</active>
      <protocol>http</protocol>
      <host>192.168.128.254</host>
      <port>3128</port>
      <nonProxyHosts>cvs.abcd.fr</nonProxyHosts>
    </proxy>
  </proxies>
  <mirrors>
    <mirror>
      <id>abcd.eu</id>
      <name>Repository de dev abcd</name>
      <url>http://cvs.abcd.fr:8080/repository</url>
      <mirrorOf>central</mirrorOf>
    </mirror>
  </mirrors>
  <profiles>
    <profile>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>central</id>
          <url>http://cvs.abcd.fr/repository</url>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>interval:120</updatePolicy>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>daily</updatePolicy>
          </snapshots>
          <releases>
            <enabled>true</enabled>
          </releases>
          <id>abcd.plugins</id>
          <name>Repository de dev de plugins de abcd</name>
          <url>http://cvs.abcd.fr/maven2</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
</settings>
```

Maven Settings writer generate a NPE :

org.apache.maven.continuum.execution.ContinuumBuildExecutorException: Error while mapping metadata.
at org.apache.maven.continuum.execution.maven.m2.MavenTwoBuildExecutor.updateProjectFromCheckOut(MavenTwoBuildExecutor.java:117)
at org.apache.maven.continuum.core.action.UpdateProjectFromWorkingDirectoryContinuumAction.execute(UpdateProjectFromWorkingDirectoryContinuumAction.java:64)
at org.apache.maven.continuum.buildcontroller.DefaultBuildController.build(DefaultBuildController.java:273)
at org.apache.maven.continuum.buildcontroller.BuildProjectTaskExecutor.executeTask(BuildProjectTaskExecutor.java:47)
at org.codehaus.plexus.taskqueue.execution.ThreadedTaskQueueExecutor$ExecutorRunnable.run(ThreadedTaskQueueExecutor.java:103)
at java.lang.Thread.run(Thread.java:595)
Caused by: org.apache.maven.continuum.execution.maven.m2.MavenBuilderHelperException: Cannot build maven project from /home/m2/continuum-folders/working-directory/44/pom.xml (null).

    at org.apache.maven.continuum.execution.maven.m2.DefaultMavenBuilderHelper.getMavenProject(DefaultMavenBuilderHelper.java:339)
    at org.apache.maven.continuum.execution.maven.m2.DefaultMavenBuilderHelper.mapMetadataToProject(DefaultMavenBuilderHelper.java:112)
    at org.apache.maven.continuum.execution.maven.m2.MavenTwoBuildExecutor.updateProjectFromCheckOut(MavenTwoBuildExecutor.java:113)
    ... 5 more

Caused by: java.lang.NullPointerException
at org.codehaus.plexus.util.xml.pull.MXSerializer.writeElementContent(MXSerializer.java:912)
at org.codehaus.plexus.util.xml.pull.MXSerializer.text(MXSerializer.java:776)
at org.apache.maven.settings.io.xpp3.SettingsXpp3Writer.writeSettings(SettingsXpp3Writer.java:581)
at org.apache.maven.settings.io.xpp3.SettingsXpp3Writer.write(SettingsXpp3Writer.java:71)
at org.apache.maven.continuum.execution.maven.m2.DefaultMavenBuilderHelper.writeSettings(DefaultMavenBuilderHelper.java:489)
at org.apache.maven.continuum.execution.maven.m2.DefaultMavenBuilderHelper.getMavenProject(DefaultMavenBuilderHelper.java:301)

---

**Affects:** 2.0.4

2 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Reopen if desired.
