### ISSUE TITLE
[MNG-2242] mvn command gives a Null Pointer Exception when a plugin is invalid

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3960]
**[Kin Leung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=timleung22)** opened **[MNG-2242](https://issues.apache.org/jira/browse/MNG-2242?redirect=false)** and commented

I tried to use xdoclet with Maven 2.0.2 by adding those lines in pom.xml:

\<build>
\<finalName>bookstore-web\</finalName>
\<plugins>
\<plugin>
\<groupId>xdoclet\</groupId>
\<artifactId>maven-xdoclet-plugin\</artifactId>
\<version>1.2\</version>
\<executions>
	      \<execution>
	        \<id>generate-deployment-decriptor\</id>
	        \<phase>generate-sources\</phase>
	        \<configuration>
	          \<fileset dir="src/main/java">
	            \<include name="**/*.java"/>
	          \</fileset> 
	          \<webdoclet>
	             \<destinationFile>web.xml\</destinationFile>
	             \<destDir>src/main/webapp/WEB-INF\</destDir>
	          \</webdoclet>
	         \</configuration>
	        \<goals>
	          \<goal>webdoclet\</goal>
	        \</goals>
	      \</execution>
	    \</executions>
\</plugin>
\</plugins>
After I saved the file and run mvn (mvn install and mvn clean), it gives me Null Pointer Exception:
Downloading: http://repo1.maven.org/maven2/xdoclet/maven-xdoclet-plugin/1.2/mave
n-xdoclet-plugin-1.2.pom
159b downloaded
Downloading: http://repo1.maven.org/maven2/xdoclet/maven-xdoclet-plugin/1.2/mave
n-xdoclet-plugin-1.2.jar
34K downloaded
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] FATAL ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] null
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginM
anager.java:295)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(De
faultPluginManager.java:200)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPlug
inManager.java:165)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(Defa
ultLifecycleExecutor.java:1218)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifec
ycle(DefaultLifecycleExecutor.java:1182)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycl
eMappings(DefaultLifecycleExecutor.java:950)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:450)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] -------------------------------------------------------------------------
&mdash;

Looks like something is screwed up when maven attempts to run the plugin for generating the web.xml of my servlet.  I didn't do anything on the settings.xml, does that matter?

Also the documentation is por and in worse case the poor documentation offsets the benefits of the tool.

---

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12711750/pom.xml) (_1.92 kB_)

**Issue Links:**
- [MNG-2239](https://issues.apache.org/jira/browse/MNG-2239) Null pointer exception when typo is in plugin name

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

You are trying to use a maven 1 plugin, which is absolutely wrong

However the error should be improved

**Comment by jira-importer** [comment]
**[Todd Nine](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=todd@spidertracks.co.nz)** commented

I am also receiving this error on a Maven1 plugin.  However it has been wrapped with a Maven 2 POM, and it will run at the command line.  For instance, if I execute the following command, the plugin runs successfully.

mvn clean antlr:generate -Dgrammars=com/ata/util/validator/validwhen/ValidWhenParser.g

However if I set up the following plugin

    <plugin>
         <groupId>maven</groupId>
         <artifactId>maven-antlr-plugin</artifactId>
         <version>1.2.1</version>
         <executions>
              <execution>
                       <goals>
                                <goal>generate</goal>
                       </goals>
                       <phase>generate-sources</phase>
              </execution>
         </executions>
              <configuration>
              <grammars>com/ata/util/validator/validwhen/ValidWhenParser.g</grammars>
         </configuration>
    </plugin>

I receive a NullPointerException.  If I can run the task from the command line, why can't I execute it as a plugin?  I would really prefer to have this generated automatically before my compile task runs.

Thanks,
Todd

Todd

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

The command line and pom configuration that you have presented are not equal. You can read more on why here:
http://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

now gives a better error (plugin descriptor can not be found)
