### ISSUE TITLE
[MNG-2239] Null pointer exception when typo is in plugin name

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3961]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[MNG-2239](https://issues.apache.org/jira/browse/MNG-2239?redirect=false)** and commented

Running mvn eclipsE:eclipse

$ mvn eclipsE:eclipse
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'eclipsE'.
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginManager.java:292)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:198)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:163)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1252)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.segmentTaskListByAggregationNeeds(DefaultLifecycleExecutor.java:381)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:135)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Apr 25 16:32:32 PDT 2006
[INFO] Final Memory: 1M/3M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.4

**Issue Links:**
- [MNG-1445](https://issues.apache.org/jira/browse/MNG-1445) NPE thrown when parsing bad plugin jar
 (_**"is duplicated by"**_)
- [MNG-2091](https://issues.apache.org/jira/browse/MNG-2091) NPE when including middlegen-hibernate-plugin
 (_**"is duplicated by"**_)
- [MNG-2242](https://issues.apache.org/jira/browse/MNG-2242) mvn command gives a Null Pointer Exception when a plugin is invalid

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Fixed.
