### ISSUE TITLE
[MNG-2732] Regression: new container unable to run release:prepare

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#3967]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-2732](https://issues.apache.org/jira/browse/MNG-2732?redirect=false)** and commented

I get this exception running mvn release:prepare -DdryRun=true on any project (both with 2.0-beta-4 and 2.0-beta-5-SNAPSHOT of the release plugin):

[INFO] ------------------------------------------------------------------------
[INFO] Error for project: Maven Artifact (during release:prepare)
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-release-plugin:2.0-beta-5-SNAPSHOT:prepare': Unable to find the mojo 'org.apache.maven.plugins:maven-release-plugin:2.0-beta-5-SNAPSHOT:prepare' in the plugin 'org.apache.maven.plugins:maven-release-plugin'
org.apache.maven.plugins.release.scm.ScmRepositoryConfigurator
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-release-plugin:2.0-beta-5-SNAPSHOT:prepare': Unable to find the mojo 'org.apache.maven.plugins:maven-release-plugin:2.0-beta-5-SNAPSHOT:prepare' in the plugin 'org.apache.maven.plugins:maven-release-plugin'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:538)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:219)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:311)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:141)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:550)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:346)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-release-plugin:2.0-beta-5-SNAPSHOT:prepare' in the plugin 'org.apache.maven.plugins:maven-release-plugin'
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:534)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:413)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 17 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-release-plugin:2.0-beta-5-SNAPSHOT:prepare', it could not be started
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:107)
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:212)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:524)
... 19 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:136)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:122)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:39)
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:98)
... 22 more
Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:49)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:118)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:132)
... 25 more
Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed of field releaseManager in object of type org.apache.maven.plugins.release.PrepareReleaseMojo because the requirement ComponentRequirement{role='org.apache.maven.plugins.release.ReleaseManager', roleHint='null', fieldName='releaseManager'} was missing
at org.codehaus.plexus.component.composition.CompositionUtils.findRequirement(CompositionUtils.java:116)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:62)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirement(FieldComponentComposer.java:53)
at org.codehaus.plexus.component.composition.AbstractComponentComposer.assembleComponent(AbstractComponentComposer.java:119)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:62)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:45)
... 27 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugins.release.ReleaseManager', it could not be started
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:107)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:304)
at org.codehaus.plexus.component.composition.CompositionUtils.findRequirement(CompositionUtils.java:103)
... 32 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:136)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:122)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:83)
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:98)
... 34 more
Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:49)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:118)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:132)
... 37 more
Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed of field releasePhases in object of type org.apache.maven.plugins.release.DefaultReleaseManager because the requirement ComponentRequirement{role='org.apache.maven.plugins.release.phase.ReleasePhase', roleHint='null', fieldName='releasePhases'} was missing
at org.codehaus.plexus.component.composition.CompositionUtils.findRequirement(CompositionUtils.java:116)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:62)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirement(FieldComponentComposer.java:53)
at org.codehaus.plexus.component.composition.AbstractComponentComposer.assembleComponent(AbstractComponentComposer.java:119)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:62)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:45)
... 39 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugins.release.phase.ReleasePhaserewrite-poms-for-development', it could not be started
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:107)
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:212)
at org.codehaus.plexus.DefaultComponentLookupManager.lookupMap(DefaultComponentLookupManager.java:162)
at org.codehaus.plexus.DefaultPlexusContainer.lookupMap(DefaultPlexusContainer.java:310)
at org.codehaus.plexus.component.composition.CompositionUtils.findRequirement(CompositionUtils.java:83)
... 44 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:136)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:122)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:83)
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:98)
... 48 more
Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:49)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:118)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:132)
... 51 more
Caused by: org.codehaus.plexus.component.composition.CompositionException: Component Composition failed for component: role: 'org.apache.maven.plugins.release.phase.ReleasePhase', implementation: 'org.apache.maven.plugins.release.phase.RewritePomsForDevelopmentPhase', role hint: 'rewrite-poms-for-development': Requirement class: 'org.apache.maven.plugins.release.scm.ScmRepositoryConfigurator' not found.
at org.codehaus.plexus.component.composition.FieldComponentComposer.findMatchingField(FieldComponentComposer.java:124)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirement(FieldComponentComposer.java:45)
at org.codehaus.plexus.component.composition.AbstractComponentComposer.assembleComponent(AbstractComponentComposer.java:119)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:62)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:45)
... 53 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.plugins.release.scm.ScmRepositoryConfigurator
at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadRealmClass(ClassRealm.java:170)
at org.codehaus.plexus.classworlds.strategy.ForeignStrategy.loadClass(ForeignStrategy.java:39)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:197)
at org.codehaus.plexus.component.composition.FieldComponentComposer.findMatchingField(FieldComponentComposer.java:104)
... 57 more

Works with 2.0.4, but not trunk

---

**Affects:** 3.0-alpha-1

**Comment by jira-importer** [comment]
**[Andrew Williams](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=handyande)** commented

This issue is now fixed with the latest plexus and maven
