### ISSUE TITLE
[MNG-2185] Could not access both "maven-core" and "maven-archetype-core" through ViewCVS

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4035]
**[Jian Wu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hellojianwu)** opened **[MNG-2185](https://issues.apache.org/jira/browse/MNG-2185?redirect=false)** and commented

When accessing maven2 source code through ViewCVS ( http://svn.apache.org/viewcvs.cgi/maven/components/trunk/ ),  accessing maven-core got the following ViewCVS Exception:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
An Exception Has Occurred

Access to "maven/components/trunk/maven-core" is forbidden.
HTTP Response Status

403 Forbidden

---

Python Traceback

Traceback (most recent call last):
  File "/usr/local/viewcvs-1.0-dev/lib/viewcvs.py", line 3351, in main
    request.run_viewcvs()
  File "/usr/local/viewcvs-1.0-dev/lib/viewcvs.py", line 228, in run_viewcvs
    % self.where, '403 Forbidden')
ViewCVSException: 403 Forbidden: Access to "maven/components/trunk/maven-core" is forbidden.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The similar exception also occurred when accessing maven-archetype-core:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
An Exception Has Occurred

Access to "maven/archetype/trunk/maven-archetype-core" is forbidden.
HTTP Response Status

403 Forbidden

---

Python Traceback

Traceback (most recent call last):
  File "/usr/local/viewcvs-1.0-dev/lib/viewcvs.py", line 3351, in main
    request.run_viewcvs()
  File "/usr/local/viewcvs-1.0-dev/lib/viewcvs.py", line 228, in run_viewcvs
    % self.where, '403 Forbidden')
ViewCVSException: 403 Forbidden: Access to "maven/archetype/trunk/maven-archetype-core" is forbidden.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

---

**Issue Links:**
- [MNG-2160](https://issues.apache.org/jira/browse/MNG-2160) Access Problem with viewcvs
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

fixed in apache's svn, waiting for it to go live
