### ISSUE TITLE
[MNG-2590] NPE when listed POM repository is missing the <id> element

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4077]
**[Brian Topping](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=topping)** opened **[MNG-2590](https://issues.apache.org/jira/browse/MNG-2590?redirect=false)** and commented

I created a remote repository as such:

\<repositories>
\<repository>
\<name>Brian's Repo\</name>
\<url>http://brian/repository/\</url>
\</repository>
\</repositories>

This results in an NPE:

java.lang.NullPointerException
at org.apache.maven.wagon.repository.Repository.hashCode(Repository.java:239)
at java.util.HashMap.hash(HashMap.java:264)
at java.util.HashMap.containsKey(HashMap.java:342)
at java.util.HashSet.contains(HashSet.java:182)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:964)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1176)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:674)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:416)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:192)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:515)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:447)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:351)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:278)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)

This is because the \<id> element is missing.  The schema should be updated such that the \<id> element is mandatory.

---

**Affects:** 2.0.4

**Comment by jira-importer** [comment]
**[Brian Topping](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=topping)** commented

Note that this bug is mislabelled, but I can't edit it now that it's been submitted.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

in 2.1.0-M1, a proper error message is given
