### ISSUE TITLE
[MNG-2571] ArrayStoreException when handling a pojo array in a plugin configuration

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4105]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** opened **[MNG-2571](https://issues.apache.org/jira/browse/MNG-2571?redirect=false)** and commented

I am currently writing test cases with the embedder for the EAR plugin. It runs fine with basic plugin's configuration but as soon as I use the _modules_ element, I got an ArrayStoreException

Full stacktrace

```
java.lang.ArrayStoreException
	at java.lang.System.arraycopy(Native Method)
	at java.util.ArrayList.toArray(ArrayList.java:305)
	at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromConfiguration(ArrayConverter.java:141)
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1030)
	at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:576)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:390)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:488)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
	at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:441)
	at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:382)
	at org.apache.maven.plugin.ear.AbstractEarPluginTestCase.executeMojo(AbstractEarPluginTestCase.java:86)
	at org.apache.maven.plugin.ear.EarMojoTest.doTestProject(EarMojoTest.java:35)
	at org.apache.maven.plugin.ear.EarMojoTest.testProject02(EarMojoTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at com.intellij.rt.execution.junit2.JUnitStarter.main(JUnitStarter.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:90)
```

Steps to reproduce, get the latest version of the EAR plugin and uncomment the method `testProject02` in `EarMojoTest`

---

**Affects:** 2.0.4

**Issue Links:**
- [MNG-3888](https://issues.apache.org/jira/browse/MNG-3888) Configuration of array-typed mojo parameters with type-incompatible elements causes ArrayStoreException

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

The issue lies here:

```
return values.toArray( (Object []) Array.newInstance( type.getComponentType(), 0 ) );
```

* values contains one `EjbModule` element
* type.getComponentType returns the `EarModule` interface

Of course EjbModule implements EarModule

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

See also
http://www.nabble.com/MNG-2571---weird-exception-using-the-embedder-tf2364333.html

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

The interface and the implementation are in different classloaders which is the root cause of this exception.

**Comment by jira-importer** [comment]
**[Stephane Nicoll](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=snicoll)** commented

Classloader issue which has been fixed with the new IT testing technique.
