### ISSUE TITLE
[MNG-2529] it0063... FAILED

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4121]
**[Hilco Wijbenga](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hilco)** opened **[MNG-2529](https://issues.apache.org/jira/browse/MNG-2529?redirect=false)** and commented

1 of the 101 integration tests fails.

it0063... FAILED
----- Standard Out -----
Command: /home/maven/bin/maven/current/bin/mvn -e --no-plugin-registry --batch-mode -Dmaven.repo.local=/home/maven/.m2/repository clean:clean package

----- Standard Error -----
Exit code: 1

> Error Stacktrace:
> org.apache.maven.it.VerificationException
> at org.apache.maven.it.Verifier.executeGoals(Verifier.java:732)
> at org.apache.maven.it.Verifier.main(Verifier.java:964)
> <<<<<< Error Stacktrace
> Log file contents:

+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'clean'.
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building Unnamed - org.apache.maven.it:maven-core-it0063:jar:1.0
  [INFO]    task-segment: [clean:clean, package]
  [INFO] ----------------------------------------------------------------------------
  [INFO] [clean:clean]
  [INFO] Deleting directory /home/maven/maven/components/maven-core-it/it0063/target
  [INFO] Deleting directory /home/maven/maven/components/maven-core-it/it0063/target/classes
  [INFO] Deleting directory /home/maven/maven/components/maven-core-it/it0063/target/test-classes
  [INFO] [resources:resources]
  [INFO] Using default encoding to copy filtered resources.
  [INFO] [compiler:compile]
  Compiling 1 source file to /home/maven/maven/components/maven-core-it/it0063/target/classes
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD FAILURE
  [INFO] ------------------------------------------------------------------------
  [INFO] Compilation failure

/home/maven/maven/components/maven-core-it/it0063/src/main/java/org/apache/maven/it0001/Person.java:[3,27] package com.sun.tools.javac does not exist

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: Compilation failure
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:555)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:393)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:182)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:747)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:380)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:505)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:111)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Fri Aug 25 02:00:21 GMT 2006
FATAL ERROR: Unable to configure the Maven application
Error stacktrace:
org.apache.maven.reactor.MavenExecutionException: Compilation failure
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:206)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:747)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:380)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.BuildFailureException: Compilation failure
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:555)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:393)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:182)
... 10 more
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:505)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:111)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:417)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 17 more
[INFO] Final Memory: 3M/7M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0-alpha-1

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this is because the profile only adds tools.jar on a sun distribution. This is correct for sun distributions and for apple distributions (where the tools are always in the classpath). We need to cover blackdown and maybe others too.

While it should be easy to fix this test, we should consider the impact this has on other parts of the system that use tools.jar

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Works fine.
