### ISSUE TITLE
[MNG-2079] scm plugin cannot checkout nested modules

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4150]
**[Dan Allen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.j.allen)** opened **[MNG-2079](https://issues.apache.org/jira/browse/MNG-2079?redirect=false)** and commented

Maven2 doesn't seem to be smart enough to recognize that it is being told to checkout a project that has sub-modules and that it needs to get the pom.xml files for those modules from the scm url located in the top level pom.

Commands speak louder than words, so I will cite an example.  Say you need to checkout the continuum code, but you would like to do it via maven scm (which, by the way, is required to get continuum set up using your project, which is the purpose of this issue)

wget http://svn.apache.org/repos/asf/maven/continuum/trunk/pom.xml
mvn scm:checkout

The result:

Reason: Could not find the model file '/home/dallen/tmp/checkout/continuum/continuum-api/pom.xml'.

[INFO] ----------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Could not find the model file '/home/dallen/tmp/checkout/continuum/continuum-api/pom.xml'.
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:359)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:276)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Could not find the model file '/home/dallen/tmp/checkout/continuum/continuum-api/pom.xml'.
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1061)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:291)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:276)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:509)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:441)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:485)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:345)
... 11 more
Caused by: java.io.FileNotFoundException: /home/dallen/tmp/checkout/continuum/continuum-api/pom.xml (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.\<init>(FileInputStream.java:106)
at java.io.FileReader.\<init>(FileReader.java:55)
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1056)

And I promptly say, "of course you can't, because you haven't checked it out yet!"

---

**Affects:** 2.0.2

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

The preferred solution is :
mvn scm:checkout -DconnectionUrl=scm:svn:.....

If you want to wget the pom, you must run scm:checkout with -N

**Comment by jira-importer** [comment]
**[Dan Allen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.j.allen)** commented

Hey, thanks for the quick response!  I would like to see this make it into the documentation somewhere, to avoid future bugs reports.  However, I think just the presence of this report is going to help a whole lot.  Time well spent.
