### ISSUE TITLE
[MNG-2005] ArtifactCollector fails without looking into other repositories

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4193]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** opened **[MNG-2005](https://issues.apache.org/jira/browse/MNG-2005?redirect=false)** and commented

My pom references 2 pluginRepositories (the snapshots codehaus one and the corporate one).

The keytool-maven-plugin is deployed as 0.3-SNAPSHOT on the snapshots
repository and I've built  a newer version (0.4-SNAPSHOT)
deployed in my internal repository, but it's not picked up.

It looks like it found the plugin on snapshots, but not with the
requested version and failed instead of looking further.

Sounds like an issue in the DefaultArtifactCollector. Will try to investigate further...

[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Couldn't find a version in [0.3-SNAPSHOT] to match range [0.3,)
org.codehaus.mojo:keytool-maven-plugin:jar:null

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2/),
embedded (file://${basedir}/tmp/m2repos),
myrepo (http://myrepository/)

[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Couldn't find a version in [0.3-SNAPSHOT] to match range [0.3,)
org.codehaus.mojo:keytool-maven-plugin:jar:null

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2/),
embedded (file://${basedir}/tmp/m2repos),
myrepo (http://myrepository/)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:548)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:472)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.artifact.versioning.OverConstrainedVersionException: Couldn't find a version in [0.3-SNAPSHOT] to match range [0.3,)
org.codehaus.mojo:keytool-maven-plugin:jar:null

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
snapshots (http://snapshots.maven.codehaus.org/maven2/),
embedded (file://${basedir}/tmp/m2repos),
myrepo (http://myrepository/)

    at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:266)
    at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:67)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:223)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:211)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:182)
    at org.apache.maven.plugin.DefaultPluginManager.ensurePluginContainerIsComplete(DefaultPluginManager.java:611)
    at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:522)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:393)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
    ... 16 more

[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 15 seconds
[INFO] Finished at: Tue Jan 24 14:39:00 CET 2006
[INFO] Final Memory: 7M/13M

---

**Affects:** 2.0.2

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

Problem is within the MXParser indeed.

I've modified the parser to print the following information:

    public int next()
        throws XmlPullParserException, IOException
    {
        tokenize = false;
        int next = nextImpl();
        if (debug) {
            System.out.println("lineNumber: " + lineNumber
                    + " columnNumber:" + columnNumber
                    + " String: " + (depth > 0 ? new String(elRawName[depth]) : "depth = 0" ) );
        }
         return next;
    }

Here's the log when the parser parses the metadata files. First parsing is related to the metadata file from the snapshot repository. Second parsing is from the file from my corporate repository (pasted in a previous comment).

lineNumber: 1 columnNumber:48 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:12 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:31 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:39 String: groupId^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:15 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:37 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:48 String: artifactId^@^@^@^@
lineNumber: 4 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 4 columnNumber:12 String: versiontId^@^@^@^@
lineNumber: 4 columnNumber:26 String: versiontId^@^@^@^@
lineNumber: 4 columnNumber:34 String: versiontId^@^@^@^@
lineNumber: 5 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 5 columnNumber:15 String: versioning^@^@^@^@
lineNumber: 6 columnNumber:7 String: versioning^@^@^@^@
lineNumber: 6 columnNumber:13 String: latest^@^@^@^@^@^@
lineNumber: 6 columnNumber:27 String: latest^@^@^@^@^@^@
lineNumber: 6 columnNumber:34 String: latest^@^@^@^@^@^@
lineNumber: 7 columnNumber:7 String: versioning^@^@^@^@
lineNumber: 7 columnNumber:15 String: versions^@^@^@^@
lineNumber: 8 columnNumber:9 String: versions^@^@^@^@
lineNumber: 8 columnNumber:16 String: version^@^@^@^@^@^@^@
lineNumber: 8 columnNumber:30 String: version^@^@^@^@^@^@^@
lineNumber: 8 columnNumber:38 String: version^@^@^@^@^@^@^@
lineNumber: 9 columnNumber:7 String: versions^@^@^@^@
lineNumber: 9 columnNumber:16 String: versions^@^@^@^@
lineNumber: 10 columnNumber:7 String: versioning^@^@^@^@
lineNumber: 10 columnNumber:18 String: lastUpdated^@
lineNumber: 10 columnNumber:34 String: lastUpdated^@
lineNumber: 10 columnNumber:46 String: lastUpdated^@
lineNumber: 11 columnNumber:5 String: versioning^@^@^@^@
lineNumber: 11 columnNumber:16 String: versioning^@^@^@^@
lineNumber: 12 columnNumber:3 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 12 columnNumber:12 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 12 columnNumber:12 String: depth = 0

lineNumber: 1 columnNumber:48 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:12 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:31 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:39 String: groupId^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:15 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:37 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:48 String: artifactId^@^@^@^@
lineNumber: 4 columnNumber:3 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 4 columnNumber:12 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 4 columnNumber:12 String: depth = 0
lineNumber: 1 columnNumber:48 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:12 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:31 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:39 String: groupId^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:15 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:37 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:48 String: artifactId^@^@^@^@
lineNumber: 4 columnNumber:3 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 4 columnNumber:12 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 4 columnNumber:12 String: depth = 0
lineNumber: 1 columnNumber:48 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:12 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:31 String: groupId^@^@^@^@^@^@^@
lineNumber: 2 columnNumber:39 String: groupId^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:5 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 3 columnNumber:15 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:37 String: artifactId^@^@^@^@
lineNumber: 3 columnNumber:48 String: artifactId^@^@^@^@
lineNumber: 4 columnNumber:3 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 4 columnNumber:12 String: metadata^@^@^@^@^@^@^@^@
lineNumber: 4 columnNumber:12 String: depth = 0

Notice how the second parsing ends up being kind of reset and neither versioning nor version tags are processed. Will try to investigate further.
