### ISSUE TITLE
[MNG-2227] Can't use repositories in protocols other than http

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4249]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[MNG-2227](https://issues.apache.org/jira/browse/MNG-2227?redirect=false)** and commented

When adding the wagon-scm to the build extensions to **add** another scm based repo (not to replace the http one) Maven fails because tries to validate the scm repo before downloading the wagon-scm jar from the http repo.

\<build>
\<extensions>
\<extension>
\<groupId>org.apache.maven.wagon\</groupId>
\<artifactId>wagon-scm\</artifactId>
\<version>1.0-alpha-7-SNAPSHOT\</version>
\</extension>
\</extensions>
\</build>
[WARNING] repository metadata for: 'snapshot org.apache.maven.wagon:wagon-scm:1.0-alpha-7-SNAPSHOT' could not be retrieved from repository: acme due to an error: Unsupported Protocol: 'scm': Cannot find wagon which supports the requested protocol: scm
[INFO] Repository 'acme' will be blacklisted
[DEBUG] Exception
org.apache.maven.wagon.TransferFailedException: Unsupported Protocol: 'scm': Cannot find wagon which supports the requested protocol: scm
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:325)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadata(DefaultWagonManager.java:295)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:356)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolve(DefaultRepositoryMetadataManager.java:91)
at org.apache.maven.artifact.transform.AbstractVersionTransformation.resolveVersion(AbstractVersionTransformation.java:62)
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForResolve(SnapshotTransformation.java:60)
at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForResolve(DefaultArtifactTransformationManager.java:40)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:104)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:467)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:225)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:102)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:275)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:67)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:223)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:211)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:182)
at org.apache.maven.extension.DefaultExtensionManager.addExtension(DefaultExtensionManager.java:68)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.findExtensions(DefaultLifecycleExecutor.java:155)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:138)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.wagon.UnsupportedProtocolException: Cannot find wagon which supports the requested protocol: scm
at org.apache.maven.artifact.manager.DefaultWagonManager.getWagon(DefaultWagonManager.java:99)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:319)
... 30 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository: org.apache.maven.wagon.Wagonscm.
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.artifact.manager.DefaultWagonManager.getWagon(DefaultWagonManager.java:94)
... 31 more

---

**Affects:** 2.0.4

**Attachments:**
- [log.txt](https://issues.apache.org/jira/secure/attachment/12711486/log.txt) (_38.12 kB_)

**Issue Links:**
- [WAGON-137](https://issues.apache.org/jira/browse/WAGON-137) Unsupported Protocol: 'ftp': Cannot find wagon which supports the requested protocol: ftp
 (_**"is duplicated by"**_)
- [MNG-2195](https://issues.apache.org/jira/browse/MNG-2195) FTP download is not supported directly by Maven
 (_**"is duplicated by"**_)
- [MNG-2225](https://issues.apache.org/jira/browse/MNG-2225) Classloader problem when adding jars to M2_HOME

- [MNG-657](https://issues.apache.org/jira/browse/MNG-657) possible chicken and egg problem with extensions

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Actually it doesn't fail due to the previous exception, it fails later when trying to download a jar wich is not in the repositories checked before the scm one.

[DEBUG] Trying repository apache.snapshots
Downloading: http://cvs.apache.org/maven-snapshot-repository/org/apache/maven/wagon/wagon-provider-api/1.0-alpha-5/wagon-provider-api-1.0-alpha-5.pom
[WARNING] Unable to get resource from repository apache.snapshots (http://cvs.apache.org/maven-snapshot-repository)
[DEBUG] Trying repository codehaus.snapshots
Downloading: http://snapshots.maven.codehaus.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0-alpha-5/wagon-provider-api-1.0-alpha-5.pom
[WARNING] Unable to get resource from repository codehaus.snapshots (http://snapshots.maven.codehaus.org/maven2)
[DEBUG] Trying repository acme-plugins
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: org.apache.maven.wagon:wagon-provider-api

Reason: Error getting POM for 'org.apache.maven.wagon:wagon-provider-api' from the repository: Unsupported Protocol: 'scm': Cannot find wagon which supports the requested protocol: scm
org.apache.maven.wagon:wagon-provider-api:pom:1.0-alpha-5

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

The workaround is adding the central repo to the list of repos, maven checks it before the scm repo (by chance) and download the necessary files.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I believe this is a dupe - someone has filed the need-extension-to-use-repository-to-find-extension issue before, IIRC.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

The solution of adding the central repo and using the SCM repo **before** the one that contains the wagon+wagon dependencies works because Maven looks in the repos in inverse order than they are defined.

So I have
1 scm repo
2 central repo
3 snapshot repo

and maven looks for dependencies in inverse order: 3,2,1

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Brett: that's more related with MNG-2225, this one is about gettiong wagons from http repo and use them to access other repos

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Brett: gotcha, I closed MNG-2195 as duplicate

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
