### ISSUE TITLE
[MNG-2214] ITs fail when bootstrapping M2 SVN trunk with java.lang.StringIndexOutOfBoundsException: String index out of range: 1

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4253]
**[Rahul Akolkar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rahul)** opened **[MNG-2214](https://issues.apache.org/jira/browse/MNG-2214?redirect=false)** and commented

Here is an exception stacktrace for one of the failed tests...

it0002... FAILED

> Error Stacktrace:
> org.apache.maven.it.VerificationException: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
> at org.apache.maven.it.Verifier.executeHook(Verifier.java:366)
> at org.apache.maven.it.Verifier.main(Verifier.java:862)
> Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
> at java.lang.String.charAt(String.java:566)
> at java.util.regex.Matcher.appendReplacement(Matcher.java:696)
> at java.util.regex.Matcher.replaceAll(Matcher.java:806)
> at java.lang.String.replaceAll(String.java:2028)
> at org.apache.maven.it.Verifier.resolveCommandLineArg(Verifier.java:698)
> at org.apache.maven.it.Verifier.executeHook(Verifier.java:355)
> ... 1 more
> <<<<<< Error Stacktrace

---

**Attachments:**
- [StringReplacementTest.java](https://issues.apache.org/jira/secure/attachment/12711483/StringReplacementTest.java) (_446 bytes_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I don't experience this issue

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I'm not seeing it either.
