### ISSUE TITLE
[MNG-2091] NPE when including middlegen-hibernate-plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4343]
**[badamowicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=badamowicz)** opened **[MNG-2091](https://issues.apache.org/jira/browse/MNG-2091?redirect=false)** and commented

As soon as the plugin middlegen-hibernat-plugin is integrated into the POM, a NPE is thrown when the plugin is added. This is the stacktrace:

bernd@linuxba:~/THEMEN/ECLIPSE_WORKBENCH/Buttenlauf> mvn compile
[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[INFO] Building Buttenlauf Auswertung - GVC Criesbach
[INFO]    task-segment: [compile]
[INFO] ----------------------------------------------------------------------------
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] null
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginManager.java:295)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:200)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:165)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1218)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifecycle(DefaultLifecycleExecutor.java:1182)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:950)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:450)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Mon Feb 20 21:04:30 CET 2006
[INFO] Final Memory: 1M/4M
[INFO] ----------------------------------------------------------------------------

This is how the Middlegen-part of the POM looks like:

....
\<build>
\<plugins>
\<plugin>
\<groupId>middlegen\</groupId>
\<artifactId>middlegen-hibernate-plugin\</artifactId>
\<version>2.1\</version>
\</plugin>
\<plugin>
....

I know this issue has been around with Maven 1.x. The cause there was a corrupted plugin pom from middlegen. But I wasn't able to reproduce this. I couldn't find anything wrong with the pom.

This problem can be reproduced with Maven 2.0 and on Windows systems, too. So I think the problem really is the plugin.  I will open an issue on the Middlegen page, too and will (hopefully) post a solution here. But maybe someone has a workaround to fix this in the meantime.

Thanks in advance for any help.

Bernd

---

**Issue Links:**
- [MNG-2239](https://issues.apache.org/jira/browse/MNG-2239) Null pointer exception when typo is in plugin name
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Plugin related problem. If still a problem submit a working build that can be tested.
