### ISSUE TITLE
[MNG-2051] Failure to inject ScmManager component

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4365]
**[Michael Böckling](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=buddycasino)** opened **[MNG-2051](https://issues.apache.org/jira/browse/MNG-2051?redirect=false)** and commented

When using the embedder, the component "org.apache.maven.scm.manager.ScmManager" can not be injected (for what reason ever). It works when using the commandline.

My field declaration:

/**
* Plexus injected component.
* 
* `@component`
  */
  private ScmManager scmManager;

Stacktrace:

Exception in thread "main" org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'com.giniality:maven-scm-transfer-plugin:0.9-SNAPSHOT:transfer': Unable to find the mojo 'com.giniality:maven-scm-transfer-plugin:0.9-SNAPSHOT:transfer' in the plugin 'com.giniality:maven-scm-transfer-plugin'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:485)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:455)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:472)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:413)
at com.giniality.EmbeddedRunner.testProject(EmbeddedRunner.java:81)
at com.giniality.EmbeddedRunner.main(EmbeddedRunner.java:99)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'com.giniality:maven-scm-transfer-plugin:0.9-SNAPSHOT:transfer' in the plugin 'com.giniality:maven-scm-transfer-plugin'
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:536)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:393)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
... 9 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojocom.giniality:maven-scm-transfer-plugin:0.9-SNAPSHOT:transfer', it could not be started
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:339)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:527)
... 11 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:109)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
... 13 more
Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:33)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
... 16 more
Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed for the field scmManager in object of type com.giniality.TransferMojo
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:144)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.java:73)
at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:68)
at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
... 18 more
Caused by: java.lang.IllegalArgumentException
at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
at java.lang.reflect.Field.set(Unknown Source)
at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:137)
... 22 more

---
No further details from [MNG-2051](https://issues.apache.org/jira/browse/MNG-2051?redirect=false)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Can you give me a sample project that I can use to reproduce the problem?

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

The SCM plugin appears to work just fine:

http://svn.apache.org/repos/asf/maven/components/trunk/maven-embedder/src/test/java/org/apache/maven/embedder/EmbedderUsingScmPluginTest.java
