### ISSUE TITLE
[MNG-2049] Timeouts in POM downloads cause the build to fail

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4366]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** opened **[MNG-2049](https://issues.apache.org/jira/browse/MNG-2049?redirect=false)** and commented

We have a number of jars in our repository that don't have POMs, e.g. third-party libraries, etc. Maven happily downloads the jar anyway, and issues a warning that there's no POM - except, sometimes, it just fails instead. See the build log below. If I were to rerun Maven again, it might fail on a different jar, or it might succeed. I can't seem to find any rhyme or reason to it...

I agree that a missing POM merits a warning, but if the jar is there, it shouldn't be failing the build!

Downloading: http://prdwebdev11/repository/j2ee/j2ee/1.3.1/j2ee-1.3.1.pom
[WARNING] Unable to get resource from repository prdwebdev11 (http://prdwebdev11/repository)
Downloading: http://repo1.maven.org/maven2/j2ee/j2ee/1.3.1/j2ee-1.3.1.pom
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: j2ee:j2ee

Reason: Error getting POM for 'j2ee:j2ee' from the repository: Error transferring file
j2ee:j2ee:pom:1.3.1

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
prdwebdev11 (http://prdwebdev11/repository)

---

**Affects:** 2.0.2

**Issue Links:**
- [MNG-2282](https://issues.apache.org/jira/browse/MNG-2282) If a repo is down, maven stops the buid instead of trying other repos
 (_**"duplicates"**_)

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

is this because j2ee.jar also does not exist?

**Comment by jira-importer** [comment]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** commented

Nope, it exists - in fact, it was already in my local repository as well.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

It does NOT exist at ibiblio

**Comment by jira-importer** [comment]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** commented

I realize, but it exists in /my/ private repository. Is the issue here that an artifact-not-found at any repository on the list is failing the build? Unfortunately, there's no obvious way to disable the "central" repository, at least that I've seen.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

It's noth e central repo that's the issue. Run with -X and see what the error behind the WARNING is. Or check your server logs.

**Comment by jira-importer** [comment]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** commented

Sorry for the slowness; I finally managed to capture this one in the act. The artifactIds are snipped out, as the project is proprietary. It seems to happen when the central repository is down or overloaded...

org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency information: Unable to read the metadata file
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:548)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:304)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:67)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:223)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:211)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:182)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1120)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:369)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:531)
... 16 more
Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:131)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:282)
... 23 more
Caused by: org.apache.maven.project.ProjectBuildingException: Error getting POM
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:417)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:351)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:102)
... 24 more
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Error transferring file
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:140)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:386)
... 26 more
Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:99)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:68)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:369)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:282)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:244)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:124)
... 28 more
Caused by: java.net.ConnectException: Connection timed out: connect
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
at java.net.Socket.connect(Socket.java:507)
at java.net.Socket.connect(Socket.java:457)
at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:365)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:477)
at sun.net.www.http.HttpClient.\<init>(HttpClient.java:214)
at sun.net.www.http.HttpClient.New(HttpClient.java:287)
at sun.net.www.http.HttpClient.New(HttpClient.java:299)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:792)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:744)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:669)
at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:1698)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1085)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:85)
... 33 more

**Comment by jira-importer** [comment]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** commented

Right... but I think there's still a bug here: a failure (for any reason) to find a given artifact on one repository should not fail the build, so long as the artifact is found on /some/ repository. Further, a failure to load the POM should never fail the build, so long as the actual artifact was retrieved successfully.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

a failure to get poms doesn't fail the build, unless it's a parent pom

**Comment by jira-importer** [comment]
**[Christoffer Hammarström](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kreiger)** commented

I can verify this.

Right now repo1.maven.org is down for some reason, and does not answer any requests.
Maven goes looking for every missing pom there, and fails the build when repo1.maven.org does not answer.

The output is:

Downloading: http://repo.imcode.com/maven2/com/imcode/imcms/imcms/3.1.2/imcms-3.1.2.pom
[WARNING] Unable to get resource from repository imcode (http://repo.imcode.com/maven2)
Downloading: http://repo1.maven.org/maven2/com/imcode/imcms/imcms/3.1.2/imcms-3.1.2.pom
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).
Project ID: com.imcode.imcms:imcms
Reason: Error getting POM for 'com.imcode.imcms:imcms' from the repository: Error transferring file
com.imcode.imcms:imcms:pom:3.1.2
from the specified remote repositories:
central (http://repo1.maven.org/maven2),
imcode (http://repo.imcode.com/maven2)
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Mon May 15 16:10:25 CEST 2006
[INFO] Final Memory: 4M/7M
[INFO] -------------------
