### ISSUE TITLE
[MNG-1956] profile build without pluginManagement fails if pom build has pluginManagement

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4425]
**[Shinobu Kawai](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shinobu)** opened **[MNG-1956](https://issues.apache.org/jira/browse/MNG-1956?redirect=false)** and commented

If the build sections has a pluginManagement, profiles without pluginManagement fails with the following:

[INFO] Scanning for projects...
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] null
[INFO] ----------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.project.injection.DefaultProfileInjector.injectPlugins(DefaultProfileInjector.java:147)
at org.apache.maven.project.injection.DefaultProfileInjector.injectBuild(DefaultProfileInjector.java:134)
at org.apache.maven.project.injection.DefaultProfileInjector.inject(DefaultProfileInjector.java:80)
at org.apache.maven.project.DefaultMavenProjectBuilder.injectActiveProfiles(DefaultMavenProjectBuilder.java:1037)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:838)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:594)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFile(DefaultMavenProjectBuilder.java:304)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:274)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:515)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:447)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:351)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:278)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Wed Jan 11 16:29:00 PST 2006
[INFO] Final Memory: 1M/2M
[INFO] ----------------------------------------------------------------------------

Attached is a sample pom.xml to reproduce.

Workaround is to put an empty \<pluginManagement/> in the profile build.

---

**Affects:** 2.0.1

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12711941/pom.xml) (_766 bytes_)

**Issue Links:**
- [MNG-1955](https://issues.apache.org/jira/browse/MNG-1955) null pointer exception in profile if pluginManagement section exists in pom
 (_**"duplicates"**_)

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Shinobu Kawai](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shinobu)** commented

You can see the exception with "mvn -Denv=dev"

**Comment by jira-importer** [comment]
**[Yann Le Du](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=le.du.yann@gmail.com)** commented

This issue one provides more info, though.
