### ISSUE TITLE
[MNG-2056] Exception when starting new page with AbstractMavenMultiPageReport

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4466]
**[Adam Winer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adamwiner)** opened **[MNG-2056](https://issues.apache.org/jira/browse/MNG-2056?redirect=false)** and commented

Attempts to call AbstractMavenMultiPageReport.startPage() from a custom report result in the following exception:

Caused by: java.io.EOFException: input contained no data
at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:2979)
at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3022)
at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1407)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1392)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1090)
at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:172)
at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:83)
at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:48)
at org.codehaus.doxia.module.xhtml.decoration.model.DecorationModelReader.createNavigation(DecorationModelReader.java:30)
at org.codehaus.doxia.site.renderer.DefaultSiteRenderer.createSink(DefaultSiteRenderer.java:244)
at org.apache.maven.reporting.sink.SinkFactory.getSink(SinkFactory.java:76)
at org.apache.maven.reporting.AbstractMavenMultiPageReport.getSink(AbstractMavenMultiPageReport.java:79)
at org.apache.maven.reporting.AbstractMavenMultiPageReport.startPage(AbstractMavenMultiPageReport.java:85)

FYI, I'm creating the SinkFactory for the multipage report using:

    SinkFactory factory = new SinkFactory();
    factory.setSiteRenderer(getSiteRenderer());
    factory.setSiteDirectory(getOutputDirectory());
    setSinkFactory(factory);

Without this code, you just get a NullPointerException in AbstractMavenMultiPageReport.getSink().

---

**Affects:** 2.0.2

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[d.vicente](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=d.vicente)** commented

I have the same problem.

When do you schedule a release for this bug ?

Thanks

**Comment by jira-importer** [comment]
**[Kenney Westerhof](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kenney)** commented

The AbstractMavenMultiPage report has never worked and no longer exists.

Instead, use the latest maven-site-plugin (maybe even a snapshot),
and add a dependency on maven-reporting-api 2.1-SNAPSHOT (or the maven-site-plugin, a dirty hack).

Then let your report implement the MavenMultiPageReport interface.
In the new generate method there's a SinkFactory parameter you can use to create
additional sinks.
