### ISSUE TITLE
[MNG-1943] MavenProject::getParent() returns a MavenProject that is NOT interpolated

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4472]
**[skaze](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=skaze)** opened **[MNG-1943](https://issues.apache.org/jira/browse/MNG-1943?redirect=false)** and commented

Plugin developers repeatedly use ${project}.getParent().someMethod() yet getParent() returns a project that has not been interpolated. This obviously needs to be fixed but may I also suggest that all plugin acceptance testing is revisted to ensure that the tests use POMs that are littered with property expressions and not literals.

---

**Attachments:**
- [mng-1943-test.zip](https://issues.apache.org/jira/secure/attachment/12712486/mng-1943-test.zip) (_14.71 kB_)

**Issue Links:**
- [MSITE-585](https://issues.apache.org/jira/browse/MSITE-585) site-deploy: empty deploy protocol when properties are used
 (_**"is depended upon by"**_)

2 votes, 4 watchers

**Comment by jira-importer** [comment]
**[skaze](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=skaze)** commented

Brett,

re 'a rare case', obviously my familiarity with these internal APIs and there usage is greatly limited so I will defer to your expertese but in general I would have thought that if someone is using an accessor to retreive a value they will want the cooked version of that 'property' and not an internal/meta representation of it, after all what use is ${foo.bar} to the developer who has called getUrl()?

I'll keep a keen eye out for your MSITE-71 code as I have a number of plugins that i've had to make reactor dependent in order to gain access to properly interpolated parent model data.

re 'integration tests' - yep, thats exactly what i meant :)

**Comment by jira-importer** [comment]
**[Nate Good](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nsgood82)** commented

I have just experienced this issue in a more critical use case.  Here are the details.  Please let me know if you need more information.

${buildVersion} is a property defined in a profile in settings.xml and is used in all poms.

\<parent>
&nbsp;&nbsp;\<artifactId>bar\</artifactId>
&nbsp;&nbsp;\<groupId>foo.bar\</groupId>
&nbsp;&nbsp;\<version>${buildVersion}\</version>
\</parent>

It seems that the problem presents itself when a project depends on an artifact that has a parent with a non-literal value; and the parent pom is not located on the filesystem.

Example:

pom.xml - This is the master pom that all others inherit from
Project A
&nbsp;&nbsp;pom.xml - Inherits from master pom
&nbsp;&nbsp;A.x
&nbsp;&nbsp;&nbsp;&nbsp;pom.xml - inherits from ProjectA/pom.xml

Project B
&nbsp;&nbsp;pom.xml - depends on A.x

if you run maven on ProjectB and A.x is located in a remote repository it will fail because ${buildVersion} in A.x/pom.xml will not be interpolated before it is used to lookup the pom.

Here is the resulting stack trace (from version 2.0.9):

Caused by: org.apache.maven.project.ProjectBuildingException:
Cannot find parent: foo.bar:xyz-pom for project: foo.bar:prompting-client:jar:${buildVersion} for project foo.bar:zyx-client:jar:${buildVersion}
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1370)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:821)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:253)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:106)

Is this scheduled to be fixed in the next maven release?

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

3.0 does interpolation of the parent. I wasn't able to get the attached IT to run, as it is relying on old, non-existent snapshots.
