### ISSUE TITLE
[MNG-3242] It's not possible to get a property with unescaped & sign for urls

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4489]
**[Nils Eckert](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nils_eckert)** opened **[MNG-3242](https://issues.apache.org/jira/browse/MNG-3242?redirect=false)** and commented

I found no way to create a property with a not escaped ampersand (&-sign). This is needed for a MySQL jdbc-connection String with some connection variabled and should be filtered in a properties file during compile phase.

It tried to escape it with &amp; This leeds to following error: Project build error Cannot read project model from interpolating filter of serialized version.

It is no option to use a double escaping with &amp;amp;. Here I get a &amp; in my connection url.

I also tried to use a <[CDATA[ ... ]]> with the same problems. It's not possible to use & sign. And if I use &amp; this escaped tag appears in my properties file after filtering.

---

**Affects:** 2.0.6

**Attachments:**
- [mvntest-20080327.zip](https://issues.apache.org/jira/secure/attachment/12712642/mvntest-20080327.zip) (_2.81 kB_)

**Issue Links:**
- [MNG-3243](https://issues.apache.org/jira/browse/MNG-3243) It's not possible to get a property with unescaped & sign for urlsIt's not possible to get a property with unescaped & sign for urls
 (_**"is duplicated by"**_)
- [MNG-6027](https://issues.apache.org/jira/browse/MNG-6027) Can't get a unescaped & sign

8 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Nils Eckert](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nils_eckert)** commented

It seems to be a little bit tricky to get these `&`-signs into this JIRA. Third try :-)

But in my case I reference the property for some plugins and want to filter my resources with that value.

And here is the problem. As mentioned above, using the double-escaped `&amp;amp;` notation the filtered properties file containts {html}&amp;{html} instead of the expected `&`-sign.

Comment: Using `{{` might help.

**Comment by jira-importer** [comment]
**[fabien markart](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fmarkart)** commented

this bug is still on.

I have the same issue with the same use case.
- ubuntu lucid
- jboss 5.1GA
- hudson 1.376
- maven 2
- jdk java-6-sun update 21

my project, as the test one, has a jdbc url property field with an ampersand, the URL is propected with a CDATA and I still have this Exception :
Started by user anonymous
Parsing POMs
ERROR: Failed to parse POMs
hudson.maven.MavenEmbedder$1: Cannot read project model from interpolating filter of serialized version. for project de.neckert:mvntest at /tmp/mvntest/pom.xml
at hudson.maven.MavenEmbedder.readProject(MavenEmbedder.java:334)
at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:878)
at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:796)
at hudson.FilePath.act(FilePath.java:753)
at hudson.FilePath.act(FilePath.java:735)
at hudson.maven.MavenModuleSetBuild$RunnerImpl.parsePoms(MavenModuleSetBuild.java:519)
at hudson.maven.MavenModuleSetBuild$RunnerImpl.doRun(MavenModuleSetBuild.java:405)
at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:416)
at hudson.model.Run.run(Run.java:1273)
at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:291)
at hudson.model.ResourceController.execute(ResourceController.java:88)
at hudson.model.Executor.run(Executor.java:129)
Caused by: org.apache.maven.project.InvalidProjectModelException: Cannot read project model from interpolating filter of serialized version. for project de.neckert:mvntest at /tmp/mvntest/pom.xml
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:882)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:506)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:215)
at hudson.maven.MavenEmbedder.readProject(MavenEmbedder.java:332)
... 11 more
Caused by: org.apache.maven.project.interpolation.ModelInterpolationException: Cannot read project model from interpolating filter of serialized version.
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolate(RegexBasedModelInterpolator.java:114)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:1016)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:878)
... 14 more
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: entity reference name can not contain character =' (position: START_TAG seen ...c:mysql://localhost/nefo?createDatabaseIfNotExist=true&useUnicode=... `@128`:85)
at org.codehaus.plexus.util.xml.pull.MXParser.parseEntityRef(MXParser.java:2222)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1275)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1093)
at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:187)
at org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:94)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePlugin(MavenXpp3Reader.java:2955)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseBuild(MavenXpp3Reader.java:753)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2224)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4422)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4433)
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolate(RegexBasedModelInterpolator.java:105)
... 16 more
Finished: FAILURE

Just tested the test one attached by Nils and it has the same issue.
