### ISSUE TITLE
[MNG-3121] goal specified in execution but not found in plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4498]
**[x](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gvsg)** opened **[MNG-3121](https://issues.apache.org/jira/browse/MNG-3121?redirect=false)** and commented

Hi all;

I want to run the XML-MAVEN-Plugin when 'mvn site:run' goal has been executed.
Whien doing this I receive the following exception:

org.apache.maven.lifecycle.LifecycleExecutionException: 'run' was specified in an execution, but not found in the plugin
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindExecutionToLifecycle(DefaultLifecycleExecutor.java:1342)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLifecycle(DefaultLifecycleExecutor.java:1243)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:987)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Here is a partial example of my pom.xml  file

    <build>        
        <plugins>
    	<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>xml-maven-plugin</artifactId>
                <version>1.0-beta-2-patched</version>
    			<dependencies>
    				<dependency>
    		           <groupId>org.codehaus.mojo</groupId>
    		            <artifactId>xml-maven-plugin</artifactId>
    		            <version>1.0-beta-2-patched</version>
    		            <scope>provided</scope>
    				</dependency>
    			</dependencies>
    			<executions>
    			  <execution>
    				<id>execution1</id>
    				<phase>site</phase>
    				<goals>
    					<goal>run</goal>
    				</goals>
    	            <configuration>
    	                <forceCreation>true</forceCreation>
    	                <transformationSets>
    	                    <transformationSet>
    	                        <dir>target</dir>
    	                        <stylesheet>./target/site/pmd-report-per-class.xslt</stylesheet>
    	                        <fileMappers>
    	                            <fileMapper implementation="org.codehaus.plexus.components.io.filemappers.FileExtensionMapper">
    	                                <targetExtension>.html</targetExtension>
    	                            </fileMapper>
    	                        </fileMappers>
    	                        <includes>
    	                            <include>pmd.xml</include>
    	                        </includes>
    	                        <outputDir>target/site</outputDir>
    	                    </transformationSet>
    	                </transformationSets>
    	            </configuration>
    						  
    			</execution>
    			</executions>
            </plugin>

Note:: If I try to set this for other plugins this will also fail.

Kind regards,

Guy

---

**Affects:** 2.0.7

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

The problem is you are specifying the phase you defined in your execution. The correct way to do this is put the configuration outside the executions block and then execute "mvn xml:run"
