### ISSUE TITLE
[MNG-2936] IllegalArgumentException forking during javadoc

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4558]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[MNG-2936](https://issues.apache.org/jira/browse/MNG-2936?redirect=false)** and commented

it0051 fails
I think it's picking an older plexus-utils

Caused by: java.lang.IllegalArgumentException
at java.lang.ProcessImpl.\<init>(ProcessImpl.java:69)
at java.lang.ProcessImpl.start(ProcessImpl.java:30)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:451)
at java.lang.Runtime.exec(Runtime.java:591)
at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:653)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:102)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:89)
at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1196)
at org.apache.maven.plugin.javadoc.JavadocJar.execute(JavadocJar.java:108)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:618)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:359)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:260)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:146)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:304)
... 11 more

---

**Affects:** 3.0-alpha-1

**Attachments:**
- [log.txt](https://issues.apache.org/jira/secure/attachment/12712363/log.txt) (_5.15 kB_)
- [logX.txt](https://issues.apache.org/jira/secure/attachment/12712025/logX.txt) (_55.82 kB_)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Not also that you get build error and then build successful

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------

...

[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4 seconds
[INFO] Finished at: Thu Apr 05 16:29:26 PDT 2007
[INFO] Final Memory: 8M/15M
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4 seconds
[INFO] Finished at: Thu Apr 05 16:29:26 PDT 2007
[INFO] Final Memory: 8M/15M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Upgraded plexus-utils
