### ISSUE TITLE
[MNG-2928] Null pointer exeception when introducing version range [major.minor.build-SNAPSHOT,)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4566]
**[Dennis Schafroth](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=schafdog)** opened **[MNG-2928](https://issues.apache.org/jira/browse/MNG-2928?redirect=false)** and commented

Due to selection of "wrong" version of a library (SystemResultDomain 1.0.2), an "hard-limit" was introduced on one project forcing the build to use at least 1.0.4-SNAPSHOT). All others are soft versions, so I dont see an inconsistency.

The dependency check fails with:

[DEBUG]     com.mobilepeople.resultdomain:SystemResultDomain:jar:1.0.2:compile (selected for compile)
...
[DEBUG] SystemResultDomain: resolved to version 1.0.4-20070402.154234-1 from repository mobilepeople
[DEBUG]     com.mobilepeople.resultdomain:SystemResultDomain:jar:1.0.4-SNAPSHOT:compile (setting version to: 1.0.4-SNAPSHOT from range: [1.0.4-SNAPSHOT,)
)
[DEBUG]     com.mobilepeople.resultdomain:SystemResultDomain:jar:1.0.4-SNAPSHOT:compile (removed - nearer found: null)
...

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] version was null for com.mobilepeople.resultdomain:SystemResultDomain
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.NullPointerException: version was null for com.mobilepeople.resultdomain:SystemResultDomain
at org.apache.maven.artifact.DefaultArtifact.getBaseVersion(DefaultArtifact.java:364)
at org.apache.maven.artifact.DefaultArtifact.getId(DefaultArtifact.java:225)
at org.apache.maven.artifact.resolver.ResolutionNode.getDependencyTrail(ResolutionNode.java:118)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:96)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:284)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:272)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1238)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:397)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.6

**Attachments:**
- [build.txt](https://issues.apache.org/jira/secure/attachment/12712027/build.txt) (_32.11 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712425/pom.xml) (_4.24 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712166/pom.xml) (_2.95 kB_)

**Issue Links:**
- [MNG-3372](https://issues.apache.org/jira/browse/MNG-3372) dependency:tree throws exception
 (_**"is duplicated by"**_)
- [MNG-2635](https://issues.apache.org/jira/browse/MNG-2635) DefaultArtifactCollector.recurse can lose versionRange

- [MNG-2923](https://issues.apache.org/jira/browse/MNG-2923) Having any active profiles causes the build to fail

3 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Looks a duplicate of MNG-2123

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

this is not a dup of MNG-2123

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Can't reproduce. If this is still occuring in 2.0.8/2.0.9 please reopen with a test project.
