### ISSUE TITLE
[MNG-2909] zero length files can be created for metadata

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4578]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-2909](https://issues.apache.org/jira/browse/MNG-2909?redirect=false)** and commented

I was getting build fails because of this:
Caused by: java.io.EOFException: input contained no data
at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:2979)
at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3022)
at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1407)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1392)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1090)
at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:863)
at org.apache.maven.artifact.repository.metadata.AbstractRepositoryMetadata.updateRepositoryMetadata(AbstractRepositoryMetadata.java:98)
at org.apache.maven.artifact.repository.metadata.AbstractRepositoryMetadata.storeInLocalRepository(AbstractRepositoryMetadata.java:68)
... 21 more
It happened after cancelling a previous build, presumably mid-update of the metadata.
Probably 2 things to do here:
a) This error should be handled when reading back the metadata to merge, and treated as a non-existent file instead of an error.
b) use an atomic rename instead of overwriting an existing file to prevent dataloss in the even of a cancelled build

---

**Affects:** 3.0

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

We need to make a little utility for writing out files atomically and use it everywhere. Or build this capability into the writers generated by modello.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

The whole notion of transactionality has to be dealth with. Added to the architectural goals for 2.1. It is not just here that can be a problem. It's everywhere we read/write models, metadata, checksums ...
