### ISSUE TITLE
[MNG-2904] Misleading error message if profiles that are active by default do not have an ID

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4580]
**[Andrew Williams](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=handyande)** opened **[MNG-2904](https://issues.apache.org/jira/browse/MNG-2904?redirect=false)** and commented

to reproduce edit your ~/.m2/settings.xml and add a new profile.
Mark it as active by default and make sure it has no ID.
The resulting stack is thus:

java.lang.ClassCastException: Settings.addActiveProfiles(string) parameter must be instanceof java.lang.String
at org.apache.maven.settings.Settings.addActiveProfile(Settings.java:91)
at org.apache.maven.settings.DefaultMavenSettingsBuilder.activateDefaultProfiles(DefaultMavenSettingsBuilder.java:197)
at org.apache.maven.settings.DefaultMavenSettingsBuilder.buildSettings(DefaultMavenSettingsBuilder.java:177)
at org.apache.maven.settings.DefaultMavenSettingsBuilder.buildSettings(DefaultMavenSettingsBuilder.java:153)
at org.apache.maven.settings.DefaultMavenSettingsBuilder.buildSettings(DefaultMavenSettingsBuilder.java:141)
at org.apache.maven.cli.MavenCli.buildSettings(MavenCli.java:315)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:176)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 2.0.5

**Comment by jira-importer** [comment]
**[Andrew Williams](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=handyande)** commented

It seems that this is somehow due to the \<id> field which should be required not being verified when the ~/.m2/settings.xml is merged into the effective-pom.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Fixed in trunk and the branch.
