### ISSUE TITLE
[MNG-2898] Look at allowing all org.codehaus.plexus.util.xml to show through

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4590]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** opened **[MNG-2898](https://issues.apache.org/jira/browse/MNG-2898?redirect=false)** and commented

We have things like merging code in the DOM and it access StringUtils and the Serializer. Why and how this happened I have no idea as the DOM is a piece of data. But it leaks all over the place causing problems with doxia because Xpp3Dom is open while the rest of p-u is hidden in the core causing NoSuchMethod exceptions.

---
No further details from [MNG-2898](https://issues.apache.org/jira/browse/MNG-2898?redirect=false)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Doing a clean install in surefire yields:

java.lang.NoSuchMethodError: org.codehaus.plexus.util.xml.Xpp3Dom.writeToSerializer(Ljava/lang/String;Lorg/codehaus/plexus/util/xml/pull/XmlSerializer;)V
at org.apache.maven.doxia.site.decoration.io.xpp3.DecorationXpp3Writer.writeBody(DecorationXpp3Writer.java:119)
at org.apache.maven.doxia.site.decoration.io.xpp3.DecorationXpp3Writer.writeDecorationModel(DecorationXpp3Writer.java:202)
at org.apache.maven.doxia.site.decoration.io.xpp3.DecorationXpp3Writer.write(DecorationXpp3Writer.java:67)
at org.apache.maven.plugins.site.SiteDescriptorArtifactMetadata.storeInLocalRepository(SiteDescriptorArtifactMetadata.java:81)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.install(DefaultRepositoryMetadataManager.java:450)
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:79)
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:94)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:442)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

This truly sucks as the Xpp3Dom uses StringUtils which is probably half the cases where people need new versions. I'm looking at I might be able to work around this now.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Fix with importFrom with a class realm.
