### ISSUE TITLE
[MNG-2878] [regression] NPE when running Checkstyle

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4607]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** opened **[MNG-2878](https://issues.apache.org/jira/browse/MNG-2878?redirect=false)** and commented

I get:

```
[INFO] An error has occurred in Checkstyle report generation.

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: An error has occurred in Checkstyle report generation.
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:524)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:862)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:699)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:470)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:440)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:419)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:271)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:238)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:146)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:303)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:123)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:907)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:369)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: org.apache.maven.plugin.MojoExecutionException: An error has occurred in Checkstyle report generation.
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:79)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:598)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:499)
        ... 20 more
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:61)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:55)
        at org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:248)
        at org.codehaus.plexus.util.IOUtil.toString(IOUtil.java:307)
        at org.codehaus.plexus.util.IOUtil.toString(IOUtil.java:295)
        at org.apache.maven.reporting.AbstractMavenReport.getSiteDescriptor(AbstractMavenReport.java:134)
        at org.apache.maven.reporting.AbstractMavenReport.execute(AbstractMavenReport.java:70)
        ... 22 more
```

The POM I used:

```
<build>
  <plugins>
    <plugin>
      <!-- Apply the Checkstyle configurations defined in the top level pom.xml file -->
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-checkstyle-plugin</artifactId>
      <dependencies>
        <dependency>
          <groupId>com.xpn.xwiki</groupId>
          <artifactId>xwiki-build-verifications</artifactId>
          <version>1.0-SNAPSHOT</version>
        </dependency>
      </dependencies>
      <configuration>
        <includes>
            **/Api.java,
            **/xmlrpc/Attachment.java,
            **/xmlrpc/SpaceSummary.java,
            **/ViewAction.java,
            **/ZipExplorer*.java,
            **/content/**/*.java,
            **/XWikiMessageTool.java
        </includes>
      </configuration>
    </plugin>
  </plugins>
</build>
```

Thanks
-Vincent

---

**Affects:** 3.0-alpha-1

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

- I've moved this from the checkstyle plugin as it works in Maven 2.0.5 but fails with 2.1-SNAPSHOT.
- I wasn't sure what "affects" version I should put
- Jason asked me to put a fix for of 2.1-alpha-1

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Vincent, what version of checkstyle? I'll just assume the latest release.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Added an import from the plugin realm back into the core realm for the resource:

/default-report.xml

which is referenced from line 134 of AbstractMavenReport.java in maven-reporting-impl version 2.0 (the version in use by checkstyle).

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

Thanks John, that's cool.
