### ISSUE TITLE
[MNG-3289] unable to resolve profile properties from a parent pom

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4648]
**[Rot Ulet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rotulet)** opened **[MNG-3289](https://issues.apache.org/jira/browse/MNG-3289?redirect=false)** and commented

I defined some properties in the default profile in the settings.xml :

\<settings>
\<profiles>
\<profile>
\<id>profile01\</id>
\<activation> 
\<activeByDefault>true\</activeByDefault>
\</activation> 
\<properties>
\<scm.connection>scm:svn:svn://linux-dev/source\</scm.connection>
	\<issue.url>http://linux-dev/bugzilla\</issue.url>
\</properties>
\</profile>
\</profiles>
\</settings>

I have defined a parent pom file named BaseProject (for default configuration, report, etc.) used in all project I use. I can compile and install this pom to my local repository. I reference this pom as the parent for my other projects.

* For a project with parent defined to my BaseProject-pom and without dependencies to other project, there is no problem : I can compile and install without any warning.

* But for a project with parent defined to my BaseProject-pom and with some dependencies to other project (previously compiled and installed), I have this warning :

[WARNING] POM for 'net.dummy:FW-Interfaces:pom:1.0-SNAPSHOT:compile' is invalid. It will be ignored for artifact resolution. Reason: The POM expression: ${pom.scm.connection} could not be evaluated. Reason: Expression value '${pom.scm.connection}/FW/FW-Interfaces' references itself in 'net.dummy:FW-Interfaces:jar:1.0-SNAPSHOT'. for project net.dummy:FW-Interfaces at Artifact [net.dummy:FW-Interfaces:pom:1.0-SNAPSHOT:compile]

But ${pom.scm.connection} (or ${scm.connection}) is defined  in the default profile of the settings.xml.

But It is just a warning and can go through all the compilation steps.

* And for an helper project (called 'all_project.pom') without parent and dependencies but with all the project in need to compile in the 'modules' section. I got this :
  [WARNING] POM for 'net.dummy:BaseProject-Conf:pom:1.0-SNAPSHOT:runtime' is invalid. It will be ignored for artifact resolution. Reason: The POM expression: ${pom.scm.connection} could not be evaluated. Reason: Expression value '${pom.scm.connection}/BaseProject-Conf' references itself in 'net.dummy:BaseProject-Conf:jar:1.0-SNAPSHOT'. for project net.dummy:BaseProject-Conf at Artifact [net.dummy:BaseProject-Conf:pom:1.0-SNAPSHOT:runtime]
  [INFO] ------------------------------------------------------------------------
  [ERROR] FATAL ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] null
  [INFO] ------------------------------------------------------------------------
  [INFO] Trace
  java.lang.UnsupportedOperationException
  at java.util.AbstractCollection.add(AbstractCollection.java:221)
  at org.apache.maven.plugin.DefaultPluginManager.checkPlexusUtils(DefaultPluginManager.java:743)
  at org.apache.maven.extension.DefaultExtensionManager.addExtension(DefaultExtensionManager.java:112)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.findExtensions(DefaultLifecycleExecutor.java:158)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:141)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
  at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
  at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
  at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

(BaseProject-Conf is the first 'module' of BaseProject)

Also see Wish n° MNG-2896.

Regards.

---

**Affects:** 2.0.7

**Issue Links:**
- [MNG-3249](https://issues.apache.org/jira/browse/MNG-3249) Profile resident POM element overrides do not effect inherited projects if the children have their own explicitly defined elements.
 (_**"is duplicated by"**_)
- [MNG-2896](https://issues.apache.org/jira/browse/MNG-2896) ${basedir} used in a repository url does not work for parent pom lookup

3 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Rot Ulet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rotulet)** commented

Hello,
I had got the same problem if I define some profiles and properties inside profiles in my BaseProject pom. Problems occur when I use a project with dependencies onto another project sub-module. Maven does not propagate properties !

--+ BaseProject without dependencies
--+ Project A with dependency to BaseProject
\-- Sub-Project A with parent : Project A
--+ Project B with dependency to BaseProject AND to Sub-Project A

Project B does not compile because Sub-Project A can not retreive the properties and thus, cannot retrieve its parent pom (which name is build onto a property).

HELP!!!!!

**Comment by jira-importer** [comment]
**[Kenneth William](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nhhockeyplayer)** commented

Yeah I'm getting WHACKED by the same thing too...

[DEBUG] Trying repository central
[DEBUG] Unable to get resource 'oracle.jdbc.driver:oracle-jdbc:pom:9.0.2.0' from repository central (http://repo1.maven.org/maven2) Unable to locate resource in repository
[DEBUG] Trying repository central
[DEBUG] Unable to get resource 'oracle.jdbc.driver:oracle-jdbc:pom:9.0.2.0' from repository central (http://repo1.maven.org/maven2) Unable to locate resource in repository
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ----------------------------------------------------------------------------
[INFO] java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException
at java.util.AbstractCollection.add(Unknown Source)
at org.apache.maven.compat.plugin.Maven20xCompatAspect.checkPlexusUtils(Maven20xCompatAspect.aj:309)
at org.apache.maven.compat.plugin.Maven20xCompatAspect.ajc$privMethod$org_apache_maven_compat_plugin_Maven20xCompatAspect$org_apache_maven_compat_plugin_Maven20xCompatAspect$checkPlexusUtils(Maven20xCompatAspect.aj:1)
at org.apache.maven.extension.DefaultExtensionManager.getArtifacts_aroundBody1$advice(DefaultExtensionManager.java:237)
at org.apache.maven.extension.DefaultExtensionManager.addExtension(DefaultExtensionManager.java:323)
at org.apache.maven.extension.DefaultExtensionManager.addExtension(DefaultExtensionManager.java:147)
at org.apache.maven.extension.DefaultBuildExtensionScanner.checkModelBuildForExtensions(DefaultBuildExtensionScanner.java:309)
at org.apache.maven.extension.DefaultBuildExtensionScanner.scanInternal(DefaultBuildExtensionScanner.java:153)
at org.apache.maven.extension.DefaultBuildExtensionScanner.scanForBuildExtensions(DefaultBuildExtensionScanner.java:81)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:282)
at org.apache.maven.DefaultMaven.createReactorManager(DefaultMaven.java:109)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:166)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:813)
at org.maven.ide.eclipse.embedder.Maven2Executor.main(Maven2Executor.java:85)
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 5 second
[INFO] Finished at: Mon Jan 07 14:31:04 EST 2008
[INFO] Memory 1M/6M
[INFO] ----------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I think your main issue would be fixed in 2.0.9. Can you confirm?

Scheduling to investigate the problem in the checkPlexusUtils method - that shouldn't happen.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please reopen with a test project.
