### ISSUE TITLE
[MNG-3284] Cached plugins are used, even when the specifically declared 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4652]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** opened **[MNG-3284](https://issues.apache.org/jira/browse/MNG-3284?redirect=false)** and commented

In the attached project, you can build module A, then build module B, but the top level aggregator project will fail at B.

The reason this happens is that maven seems to cache plugins. When B is built in isolation, all things are fine - but when built in aggregation, one of the plugins that it uses has already been instantiated, and so it uses that one. This is incorrect, since the declared version is different in B, and is relying on functionality not present in the version declared in A.

I have seen similar behaviour when a plugin relies on other plugins to get work done - all of a sudden a build mysteriously stops working, because of a completely unrelated plugin.

This is pretty painful because
- it's possible to get into a 'no solution', where one project relies on one behaviour so can't upgrade, and one project relies on new behaviour, so can't downgrade.
- you get builds that work OK in isolation, but not in their project. This is bad. Also builds tied together in bigger aggregator projects can fail in mysterious ways (mysterious because the user /has/ specified the plugin version, and maven has ignored them, or it's a plugin dependency that got there first)
- subtle build ordering changes can cause new failures (the example has B depend on A - but the bug might only manifest itself in certain build orders that change even when B and A don't).

---

**Affects:** 2.0.7

**Attachments:**
- [0001-Initial-fix-to-see-if-we-can-have-1-version-of-a-pl.patch](https://issues.apache.org/jira/secure/attachment/12711963/0001-Initial-fix-to-see-if-we-can-have-1-version-of-a-pl.patch) (_14.21 kB_)
- [0001-Initial-fix-to-see-if-we-can-have-1-version-of-a-pl.patch.svn](https://issues.apache.org/jira/secure/attachment/12711973/0001-Initial-fix-to-see-if-we-can-have-1-version-of-a-pl.patch.svn) (_14.18 kB_)
- [maven-bug-2.tar](https://issues.apache.org/jira/secure/attachment/12712510/maven-bug-2.tar) (_40.00 kB_)
- [MNG-3284.patch](https://issues.apache.org/jira/secure/attachment/12712577/MNG-3284.patch) (_13.82 kB_)
- [mng3284-usingCachedPlugins.tar](https://issues.apache.org/jira/secure/attachment/12712376/mng3284-usingCachedPlugins.tar) (_50.00 kB_)
- [plugin.diff](https://issues.apache.org/jira/secure/attachment/12712707/plugin.diff) (_14.08 kB_)
- [pluginbug.tar](https://issues.apache.org/jira/secure/attachment/12712563/pluginbug.tar) (_10.00 kB_)

**Issue Links:**
- [MNG-4580](https://issues.apache.org/jira/browse/MNG-4580) Plugin dependencies for module ignored when building from aggregator project using direct plugin invocation

- [MNG-3013](https://issues.apache.org/jira/browse/MNG-3013) The plugin manager incorrectly caches plugin versions between embedder calls

- [MNG-1024](https://issues.apache.org/jira/browse/MNG-1024) Reactor does not allow multiple plugin versions across projects

- [MNG-1323](https://issues.apache.org/jira/browse/MNG-1323) Plugin extensions (dependencies) not resolved in reactor build

- [MNG-3217](https://issues.apache.org/jira/browse/MNG-3217) a plugin's dependencies can influence other plugins in a build

- [MNG-3801](https://issues.apache.org/jira/browse/MNG-3801) Plugin dependencies for module ignored when building from aggregated project

**Backported to:** [2.1.0](https://github.com/apache/maven/milestone/53?closed=1)

8 votes, 7 watchers

**Comment by jira-importer** [comment]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** commented

This is an easy-to-reproduce test :

Build the module mojo
Build the module mojo2

then from top level do
mvn install

it should use 2 different versions, you can observe that it only uses one.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this looks good to me - if you have a chance could you turn the reproduction into the integration test format?

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Identified as blocker to upgrading. Lets try to include this (even has an IT)

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

any chance you can make that patch against svn?

**Comment by jira-importer** [comment]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** commented

I think this should apply with SVN (if that's what you meant?) - it's the same patch but with --no-prefix; I'm told tortoiseSVN is a bit picky about patch formats..

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

perfect timing...i just finished merging in the IT.

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

patch doesn't work, it still has git junk in there. I'll try to do it manually

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Attaching an svn patch (MNG-3284.patch) by hand applying these changes to 2.0.9. The IT is already committed to the core-its but with this patch there is a crash:

INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The PluginDescriptor for the plugin Plugin [org.apache.maven.plugins:maven-plugin-plugin] was not found.
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.IllegalStateException: The PluginDescriptor for the plugin Plugin [org.apache.maven.plugins:maven-plugin-plugin] was not found.
at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginManager.java:329)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:215)

If you can fix the patch and reattach, then we can include for 2.0.9

**Comment by jira-importer** [comment]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** commented

Ok - I've re-rolled the patch, and tried to execute it as an SVN diff.

I've run it against the current set of 2.0.9 ITs and it seems to work.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I've applied the latest patch, and everything (including the IT that Brian committed) seems happy.

I'd like to provide one caveat to all of this, though:

plugin-level dependencies still cannot vary for a single plugin version in the same build. This is a particular problem when using the ant-run plugin. I'll see if I can dig up the issue (I'm sure it's been logged), and link it here. I've also got a simple test project that I can attach to the issue, which is what I've used to verify that this is indeed fixed in the Maven 2.1 code.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

These two issues deal with subtly different aspects of plugin variance within a multimodule project, with MNG-3284 specifying variance of plugin versions, and MNG-1323 specifying variance of plugin-level dependencies.

I have a test case that I'll attach to MNG-1323 that displays the issue.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Applied the latest patch, and everything seems good.

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

This is still causing problems. See the IT output here: https://ci.sonatype.org/job/Maven-2.0.x-freestyle/18/console

**Comment by jira-importer** [comment]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** commented

Hmm - that's confusing me.

On my machine, both trunk and trunk-1 (without and with the patch respectively) both only have 1 IT failure, in testitMNG2861 - I've updated the core-it tests and rebuilt, so I don't see why I get different results.

So I must be doing something wrong;  I'm currently re-running on my machine with the same commandline that I can see from the hudson build to see what happens.

**Comment by jira-importer** [comment]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** commented

I've just executed the following:
svn co -r 636941 https://svn.apache.org/repos/asf/maven/components/branches/maven-2.0.x /tmp/maven-2.0.x
cd /tmp/maven-2.0.x
mvn clean install -B -U -e -Dmaven.repo.local=/tmp/maven-2.0.x.repo -Pstrict,run-its -Dsurefire.useFile=false

And still things seem to be happy bar 2861..

?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I verified this also. I get the same result, except for me 2123 and 2861 are failing, but Brian tells me these are failing on his copy (with 3284 rolled back).

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

we will retry the patch once everything is stabilized. I know that as soon as I rolled it back, everything was ok, both on my machine and the hudson one and the error was the same as I saw when I applied it originally.

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Tried again. My test results locally are nearly identical to hudson:

Mine:
Tests in error:
testitMNG2277(org.apache.maven.integrationtests.MavenITmng2277AggregatorAndResolutionPluginsTest)
testit0104(org.apache.maven.integrationtests.MavenIT0104Test)
testit0075(org.apache.maven.integrationtests.MavenIT0075Test)
testit0074(org.apache.maven.integrationtests.MavenIT0074Test)
testit0073(org.apache.maven.integrationtests.MavenIT0073Test)
testit0071(org.apache.maven.integrationtests.MavenIT0071Test)
testit0068(org.apache.maven.integrationtests.MavenIT0068Test)
testit0064(org.apache.maven.integrationtests.MavenIT0064Test)
testit0049(org.apache.maven.integrationtests.MavenIT0049Test)
testit0046(org.apache.maven.integrationtests.MavenIT0046Test)
testit0045(org.apache.maven.integrationtests.MavenIT0045Test)
testit0041(org.apache.maven.integrationtests.MavenIT0041Test)
testit0040(org.apache.maven.integrationtests.MavenIT0040Test)
testit0027(org.apache.maven.integrationtests.MavenIT0027Test)
testit0022(org.apache.maven.integrationtests.MavenIT0022Test)
testit0018(org.apache.maven.integrationtests.MavenIT0018Test)
testit0012(org.apache.maven.integrationtests.MavenIT0012Test)

Hudson:
https://ci.sonatype.org/job/Maven-2.0.x-ITs/30/console

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

When I built this locally, then installed it and tried to build again with the version I just built, I got the following:

[INFO] Internal error in the plugin manager getting plugin 'org.apache.maven.plugins:maven-shade-plugin': Failed to create plugin container for plugin 'Plugin [org.apache.maven.plugins:maven-shade-plugin]': Cannot create child container, because child named 'maven-shade-plugin:org.apache.maven.plugins:1.0-beta-2-SNAPSHOT' already exists in parent 'app0'.

I haven't reproduced Brian's problem above, but this in itself signals that the patch is not careful enough to avoid duplication of plugin containers. We need to take some more time and build up a better test suite for this issue, to guard against all the different problems that can occur when you start changing the plugin classloading scheme.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

We simply cannot be certain of this patch without more tests to check that the plugin classloaders are being constructed correctly. We're seeing too many different problems that are hard to reproduce consistently. It also will probably be useful to look at the documentation for the plugin and extension classloading refactor that I did for 2.1, once I get those docs done (next on my TODO list once 2.0.9 is staged).

**Comment by jira-importer** [comment]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** commented

That's ok - I'll keep plugging away at getting the tests to pass..

Unfortunately - my tests seem to work. I must be doing something wrong.

I'm doing
mvn clean install
from maven-2.0.x

then mvn clean test (or mvn clean test -e -U -B -Prun-its)
from maven-2.0.x/maven-core-it-runner

I see the same tests running as in hudson, I see
mng2744checksumVerification
failing
but the testit* working.

Is there some external dependency I need to recompile? How come testitMNG2277 fails for Brian Fox but not for hudson ? Could there be some change /difference in the IT framework that I'm not picking up?

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I'm not sure why this is failing in so many different ways, but I can say that the ITs were all passing in the three environments we tested: mine, hudson, and Brian's. When we applied the patch again (today, merged from Brian's rollback on Friday/Saturday/whenever it was), we got three different failure profiles on three different machines. Yours makes four where something is failing.

On my side, it seemed like all the ITs ran when I did the following:

1. svn up core-integration-testing
2. cd core-integration-testing && mvn clean install
3. cd maven-2.0.x && mvn -P run-its,strict clean install

Then, when I installed the newly-built copy of maven into my apps directory (just a local directory structure I have where things like Maven live), and tried to build the maven-2.0.x project once again (#3 above) using that newly-installed version, it failed with the error I gave above (two of my entries back, about the child container already existing when calling the shade plugin). To me, this is an indication that we don't have sufficient test coverage, if that error could slip by, regardless of whether all the ITs succeed or not.

**Comment by jira-importer** [comment]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** commented

Out of interest, what platform are you / hudson running ?

I've tried my build on linux and OS X (though both with maven 2.0.8 and 1.5.0_13) and get the same result - it seems there's something odd. I'll try some JVM variants and windows tomorrow and try and find why I get different test resutls

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Pushing to 2.0.11 so we can have a smaller set of high-value issues to target for the next release (2.0.10).

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r591391](http://svn.eu.apache.org/viewvc?view=rev&revision=591391) and [r744497](http://svn.eu.apache.org/viewvc?view=rev&revision=744497), respectively.
