### ISSUE TITLE
[MNG-3282] maven only tries the first repo that contains an artifact

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4656]
**[Brian E Fox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf)** opened **[MNG-3282](https://issues.apache.org/jira/browse/MNG-3282?redirect=false)** and commented

If there are multiple repos that contain an artifact, the metadata in the local repo for all of them will contain this fact. Maven only tries the first one to get the artifact and doesn't try the others. It should try any other repos known to contain the artifact if the previous ones fail (if they are down for example).

---

**Affects:** 2.0.7

**Remote Links:**
- [GitHub Pull Request #1979
](https://github.com/apache/maven/pull/1979)

2 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

is this a regression? I'm sure it never used to be the case - can you reproduce with older versions?

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

I tried with 2.0.5 and 2.0.6. Same exact issue:

+ Error stacktraces are turned on.
  Maven version: 2.0.7
  Java version: 1.6.0
  OS name: "windows xp" version: "5.1" arch: "x86"
  [DEBUG] Building Maven user-level plugin registry from: 'C:\Documents and Settings\fxb\.m2\plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: 'C:\RC_development\build_platform_v0.2\maven-2.0.7\conf\plugin-registry.xml'
  [INFO] Scanning for projects...
  [DEBUG] Skipping disabled repository release
  [DEBUG] Skipping disabled repository component_scope_tpp
  [DEBUG] Skipping disabled repository central
  [DEBUG] maven-enforcer-plugin: resolved to version 1.0-alpha-4-20070928.022802-3 from repository group
  [DEBUG] Trying repository group
  Downloading: http://vbubldzs03:8443/nexus/groups/torrent/org/apache/maven/plugins/maven-enforcer-plugin/1.0-alpha-4-SNAPSHOT/maven-enforcer-plugin-1.0-alpha-4-20070928.022802-3.pom
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Error building POM (may not be this project's POM).

Project ID: org.apache.maven.plugins:maven-enforcer-plugin

Reason: Error getting POM for 'org.apache.maven.plugins:maven-enforcer-plugin' from the repository: Error transferring file
org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0-alpha-4-20070928.022802-3

from the specified remote repositories:
public-snapshot (http://snapshots),
group (xxxxxxxxxxxxx),
component_scope_tpp (xxxxxxxxx),
release (xxxxxx),
central (xxxxx)
for project org.apache.maven.plugins:maven-enforcer-plugin

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to build project for plugin 'org.apache.maven.plugins:maven-enforcer-plugin': Error getting POM for 'org.apache.maven.plugins:maven-enforcer-plugin' from the repository: Error transferring file
org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0-alpha-4-20070928.022802-3

from the specified remote repositories:
public-snapshot (http://snapshots),
group (xxxx,
component_scope_tpp (xxxxx),
release (xxxxx),
central (xxxxx)
for project org.apache.maven.plugins:maven-enforcer-plugin
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1274)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1522)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.segmentTaskListByAggregationNeeds(DefaultLifecycleExecutor.java:386)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:138)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.InvalidPluginException: Unable to build project for plugin 'org.apache.maven.plugins:maven-enforcer-plugin': Error getting POM for 'org.apache.maven.plugins:maven-enforcer-plugin' from the repository: Error transferring file
org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0-alpha-4-20070928.022802-3

from the specified remote repositories:
public-snapshot (http://snapshots),
group (xxxxxxxxxxxxxxx),
component_scope_tpp (xxx),
release (xxxxxx),
central (xxxxxxxxxxx/)
for project org.apache.maven.plugins:maven-enforcer-plugin
at org.apache.maven.plugin.DefaultPluginManager.checkRequiredMavenVersion(DefaultPluginManager.java:276)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:192)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:171)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(DefaultLifecycleExecutor.java:1257)
... 14 more
Caused by: org.apache.maven.project.ProjectBuildingException: Error getting POM for 'org.apache.maven.plugins:maven-enforcer-plugin' from the repository: Error transferring file
org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0-alpha-4-20070928.022802-3

from the specified remote repositories:
\<snip>

for project org.apache.maven.plugins:maven-enforcer-plugin
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:560)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:234)
at org.apache.maven.plugin.DefaultPluginManager.checkRequiredMavenVersion(DefaultPluginManager.java:260)
... 17 more
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Error transferring file
org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0-alpha-4-20070928.022802-3

from the specified remote repositories:
\<snip>

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:201)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:73)
    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:526)
    ... 19 more

Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:104)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:68)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:462)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:347)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:181)
... 21 more
Caused by: java.net.ConnectException: Connection refused: connect
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
at java.net.Socket.connect(Socket.java:519)
at java.net.Socket.connect(Socket.java:469)
at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:388)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:500)
at sun.net.www.http.HttpClient.\<init>(HttpClient.java:233)
at sun.net.www.http.HttpClient.New(HttpClient.java:306)
at sun.net.www.http.HttpClient.New(HttpClient.java:318)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:792)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:733)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:658)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:981)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:83)
... 25 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Mon Nov 12 17:13:23 CET 2007
[INFO] Final Memory: 1M/4M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Kenneth William](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nhhockeyplayer)** commented

This is a pain in the neck.

I receive the same thin with maven 2.0.6

org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'com.gargoyle.test:gbase:jar': Error getting POM for 'com.gargoyle.test:gbase' from the repository: Error transferring file
com.gargoyle.test:gbase:pom:2.0.1

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
apache.snapshots (http://people.apache.org/repo/m2-snapshot-repository),
trails.codehaus.org (http://trails.codehaus.org/repository),
howardlewisship.com (http://howardlewisship.com/repository),
localhost.repository (file:///C:\Tomcat-5.5.17/webapps/m2.repository)

com.gargoyle.test:gbase:jar:2.0.1

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
apache.snapshots (http://people.apache.org/repo/m2-snapshot-repository),
trails.codehaus.org (http://trails.codehaus.org/repository),
howardlewisship.com (http://howardlewisship.com/repository),
localhost.repository (file:///C:\Tomcat-5.5.17/webapps/m2.repository)
Path to dependency:
1) org.trailsframework.examples:realty:war:1.2-SNAPSHOT

   at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:297)
   at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:67)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:223)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:211)
   at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:192)
   at org.apache.maven.project.DefaultMavenProjectBuilder.buildWithDependencies(DefaultMavenProjectBuilder.java:342)
   at org.apache.maven.project.DefaultMavenProjectBuilder.buildWithDependencies(DefaultMavenProjectBuilder.java:289)
   at org.apache.maven.embedder.MavenEmbedder.readProjectWithDependencies(MavenEmbedder.java:277)
   at org.maven.ide.eclipse.Maven2Executor.main(Maven2Executor.java:53)

Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file for artifact 'com.gargoyle.test:gbase:jar': Error getting POM for 'com.gargoyle.test:gbase' from the repository: Error transferring file
com.gargoyle.test:gbase:pom:2.0.1

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
apache.snapshots (http://people.apache.org/repo/m2-snapshot-repository),
trails.codehaus.org (http://trails.codehaus.org/repository),
howardlewisship.com (http://howardlewisship.com/repository),
localhost.repository (file:///C:\Tomcat-5.5.17/webapps/m2.repository)

    at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:131)
    at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:275)
    ... 8 more

Caused by: org.apache.maven.project.ProjectBuildingException: Error getting POM for 'com.gargoyle.test:gbase' from the repository: Error transferring file
com.gargoyle.test:gbase:pom:2.0.1

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
apache.snapshots (http://people.apache.org/repo/m2-snapshot-repository),
trails.codehaus.org (http://trails.codehaus.org/repository),
howardlewisship.com (http://howardlewisship.com/repository),
localhost.repository (file:///C:\Tomcat-5.5.17/webapps/m2.repository)

    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:501)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:225)
    at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:102)
    ... 9 more

Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Error transferring file
com.gargoyle.test:gbase:pom:2.0.1

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
apache.snapshots (http://people.apache.org/repo/m2-snapshot-repository),
trails.codehaus.org (http://trails.codehaus.org/repository),
howardlewisship.com (http://howardlewisship.com/repository),
localhost.repository (file:///C:\Tomcat-5.5.17/webapps/m2.repository)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:140)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:63)
    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:467)
    ... 11 more

Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:99)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:68)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:369)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:282)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:244)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:124)
... 13 more
Caused by: java.net.UnknownHostException: trails.codehaus.org
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:177)
at java.net.Socket.connect(Socket.java:507)
at java.net.Socket.connect(Socket.java:457)
at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:365)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:477)
at sun.net.www.http.HttpClient.\<init>(HttpClient.java:214)
at sun.net.www.http.HttpClient.New(HttpClient.java:287)
at sun.net.www.http.HttpClient.New(HttpClient.java:299)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:792)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:744)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:669)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:913)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:85)
... 18 more

---

Here is my build...

C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty>set M2_OPTS=-Xms128m -X
mx512m -Xss32768k -Dmaven.test.skip=true
[INFO]
NOTE: Maven is executing in offline mode. Any artifacts not already in your local
repository will be inaccessible.

[INFO] Scanning for projects...
WAGON_VERSION: 1.0-beta-2
[INFO] ----------------------------------------------------------------------------
[INFO] Building Trails Demo
[INFO]    task-segment: [clean, install]
[INFO] ----------------------------------------------------------------------------
[INFO] artifact org.codehaus.mojo:aspectj-maven-plugin: checking for updates from codehaus

[INFO] artifact org.apache.myfaces.tobago:maven-apt-plugin: checking for updates from code
haus
[INFO] [clean:clean]
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target\classes
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target\test-classes
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target\site
[INFO] snapshot org.trailsframework:trails-hibernate:1.2-SNAPSHOT: checking for updates fr
om trails.codehaus.org
[INFO] snapshot org.trailsframework:trails-hibernate:1.2-SNAPSHOT: checking for updates fr
om apache.snapshots
[INFO] snapshot org.trailsframework:trails-hibernate:1.2-SNAPSHOT: checking for updates fr
om howardlewisship.com
[INFO] snapshot org.trailsframework:trails-hibernate:1.2-SNAPSHOT: checking for updates fr
om localhost.repository
[INFO] snapshot org.trailsframework:modules:1.2-SNAPSHOT: checking for updates from trails
.codehaus.org
[INFO] snapshot org.trailsframework:modules:1.2-SNAPSHOT: checking for updates from apache
.snapshots
[INFO] snapshot org.trailsframework:modules:1.2-SNAPSHOT: checking for updates from howard
lewisship.com
[INFO] snapshot org.trailsframework:modules:1.2-SNAPSHOT: checking for updates from localh
ost.repository
[INFO] snapshot org.trailsframework:trails:1.2-SNAPSHOT: checking for updates from trails.
codehaus.org
[INFO] snapshot org.trailsframework:trails:1.2-SNAPSHOT: checking for updates from apache.
snapshots
[INFO] snapshot org.trailsframework:trails:1.2-SNAPSHOT: checking for updates from howardl
ewisship.com
[INFO] snapshot org.trailsframework:trails:1.2-SNAPSHOT: checking for updates from localho
st.repository
[INFO] snapshot org.trailsframework:trails-core:1.2-SNAPSHOT: checking for updates from tr
ails.codehaus.org
[INFO] snapshot org.trailsframework:trails-core:1.2-SNAPSHOT: checking for updates from ap
ache.snapshots
[INFO] snapshot org.trailsframework:trails-core:1.2-SNAPSHOT: checking for updates from ho
wardlewisship.com
[INFO] snapshot org.trailsframework:trails-core:1.2-SNAPSHOT: checking for updates from lo
calhost.repository
[INFO] snapshot ognl:ognl:2.7.2-SNAPSHOT: checking for updates from trails.codehaus.org
[INFO] snapshot ognl:ognl:2.7.2-SNAPSHOT: checking for updates from apache.snapshots
[INFO] snapshot ognl:ognl:2.7.2-SNAPSHOT: checking for updates from howardlewisship.com
[INFO] snapshot ognl:ognl:2.7.2-SNAPSHOT: checking for updates from localhost.repository
[INFO] snapshot com.javaforge.tapestry:tapestry-javaforge:1.0.0-SNAPSHOT: checking for upd
ates from trails.codehaus.org
[INFO] snapshot com.javaforge.tapestry:tapestry-javaforge:1.0.0-SNAPSHOT: checking for upd
ates from apache.snapshots
[INFO] snapshot com.javaforge.tapestry:tapestry-javaforge:1.0.0-SNAPSHOT: checking for upd
ates from howardlewisship.com
[INFO] snapshot com.javaforge.tapestry:tapestry-javaforge:1.0.0-SNAPSHOT: checking for upd
ates from localhost.repository
[INFO] snapshot org.trailsframework:trails-security:1.2-SNAPSHOT: checking for updates fro
m trails.codehaus.org
[INFO] snapshot org.trailsframework:trails-security:1.2-SNAPSHOT: checking for updates fro
m apache.snapshots
[INFO] snapshot org.trailsframework:trails-security:1.2-SNAPSHOT: checking for updates fro
m howardlewisship.com
[INFO] snapshot org.trailsframework:trails-security:1.2-SNAPSHOT: checking for updates fro
m localhost.repository
[INFO] snapshot org.trailsframework:trails-test:1.2-SNAPSHOT: checking for updates from tr
ails.codehaus.org
[INFO] snapshot org.trailsframework:trails-test:1.2-SNAPSHOT: checking for updates from ap
ache.snapshots
[INFO] snapshot org.trailsframework:trails-test:1.2-SNAPSHOT: checking for updates from ho
wardlewisship.com
[INFO] snapshot org.trailsframework:trails-test:1.2-SNAPSHOT: checking for updates from lo
calhost.repository
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Missing:

---

1) ognl:ognl:jar:2.7.2-SNAPSHOT

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=ognl -DartifactId=ognl \
-Dversion=2.7.2-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

Path to dependency:
1) org.trailsframework.examples:realty:war:1.2-SNAPSHOT
2) ognl:ognl:jar:2.7.2-SNAPSHOT

---

1 required artifact is missing.

for artifact:
org.trailsframework.examples:realty:war:1.2-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
apache.snapshots (http://people.apache.org/repo/m2-snapshot-repository),
trails.codehaus.org (http://trails.codehaus.org/repository),
howardlewisship.com (http://howardlewisship.com/repository),
localhost.repository (file:///C:\Tomcat-5.5.17/webapps/m2.repository)

NOTE: Maven is executing in offline mode. Any artifacts not already in your local
repository will be inaccessible.

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 54 seconds
[INFO] Finished at: Thu Jan 03 08:49:44 EST 2008
[INFO] Final Memory: 12M/127M
[INFO] ------------------------------------------------------------------------

C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty>mvn clean install

C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty>set MAVEN_OPTS=-Xms128m
-Xmx512m -Xss32768k -Dmaven.test.skip=true

C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty>set M2_OPTS=-Xms128m -X
mx512m -Xss32768k -Dmaven.test.skip=true
[INFO] Scanning for projects...
Downloading: http://trails.codehaus.org/repository/oracle/jdbc/driver/oracle-jdbc/9.0.2.0/
oracle-jdbc-9.0.2.0.pom
Downloading: http://people.apache.org/repo/m2-snapshot-repository/oracle/jdbc/driver/oracl
e-jdbc/9.0.2.0/oracle-jdbc-9.0.2.0.pom
Downloading: http://howardlewisship.com/repository/oracle/jdbc/driver/oracle-jdbc/9.0.2.0/
oracle-jdbc-9.0.2.0.pom
Downloading: file:///C:\Tomcat-5.5.17/webapps/m2.repository/oracle/jdbc/driver/oracle-jdbc
/9.0.2.0/oracle-jdbc-9.0.2.0.pom
Downloading: http://repo1.maven.org/maven2/oracle/jdbc/driver/oracle-jdbc/9.0.2.0/oracle-j
dbc-9.0.2.0.pom
Downloading: http://trails.codehaus.org/repository/com/mysql/jdbc/mysql-jdbc/5.0.7/mysql-j
dbc-5.0.7.pom
Downloading: http://people.apache.org/repo/m2-snapshot-repository/com/mysql/jdbc/mysql-jdb
c/5.0.7/mysql-jdbc-5.0.7.pom
Downloading: http://howardlewisship.com/repository/com/mysql/jdbc/mysql-jdbc/5.0.7/mysql-j
dbc-5.0.7.pom
Downloading: file:///C:\Tomcat-5.5.17/webapps/m2.repository/com/mysql/jdbc/mysql-jdbc/5.0.
7/mysql-jdbc-5.0.7.pom
Downloading: http://repo1.maven.org/maven2/com/mysql/jdbc/mysql-jdbc/5.0.7/mysql-jdbc-5.0.
7.pom
Downloading: http://trails.codehaus.org/repository/com/sun/tools/1.5.0/tools-1.5.0.pom
Downloading: http://people.apache.org/repo/m2-snapshot-repository/com/sun/tools/1.5.0/tool
s-1.5.0.pom
Downloading: http://howardlewisship.com/repository/com/sun/tools/1.5.0/tools-1.5.0.pom
Downloading: file:///C:\Tomcat-5.5.17/webapps/m2.repository/com/sun/tools/1.5.0/tools-1.5.
0.pom
Downloading: http://repo1.maven.org/maven2/com/sun/tools/1.5.0/tools-1.5.0.pom
WAGON_VERSION: 1.0-beta-2
[INFO] ----------------------------------------------------------------------------
[INFO] Building Trails Demo
[INFO]    task-segment: [clean, install]
[INFO] ----------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target\classes
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target\test-classes
[INFO] Deleting directory C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\real
ty\target\site
Downloading: http://trails.codehaus.org/repository/com/gargoyle/test/gbase/2.0.1/gbase-2.0
.1.pom
Downloading: http://people.apache.org/repo/m2-snapshot-repository/com/gargoyle/test/gbase/
2.0.1/gbase-2.0.1.pom
Downloading: http://howardlewisship.com/repository/com/gargoyle/test/gbase/2.0.1/gbase-2.0
.1.pom
Downloading: file:///C:\Tomcat-5.5.17/webapps/m2.repository/com/gargoyle/test/gbase/2.0.1/
gbase-2.0.1.pom
Downloading: http://repo1.maven.org/maven2/com/gargoyle/test/gbase/2.0.1/gbase-2.0.1.pom
[INFO] [aspectj:compile {execution: default}]
[WARNING] advice defined in org.trails.validation.HibernateValidationAspect has not been a
pplied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.trails.i18n.DescriptorInternationalization has not been ap
plied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.trails.i18n.DescriptorInternationalization has not been ap
plied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.trails.i18n.DescriptorInternationalization has not been ap
plied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.trails.i18n.DescriptorInternationalization has not been ap
plied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.trails.validation.ValidateUniqueAspect has not been applie
d [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.trails.validation.CheckForOrphansAspect has not been appli
ed [Xlint:adviceDidNotMatch]
[INFO] [apt:execute {execution: default}]
2008-01-03 09:10:31,022 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty/src/main/resource
s/hibernate.cfg.xml
2008-01-03 09:10:31,492 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - javax.persistence.Entity
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Lender
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Buyer
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Mgr
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Facility
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Sale
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.UploadableMedia
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Role
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.SalesAgent
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.User
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Person
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.AdminLayout
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Director
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.ListingAgent
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Listing
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Officer
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - org.trails.demo.Corporation
2008-01-03 09:10:31,883 [main] INFO  org.trails.hibernate.HibernateAnnotationProcessorFact
ory - Creating destFile: C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realt
y/target/generated-sources/resources/hibernate.cfg.xml
[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:compile]
[INFO] Nothing to compile - all classes are up to date
[INFO] [aspectj:test-compile {execution: default}]
[INFO] [resources:testResources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:testCompile]
[INFO] Not compiling test sources
[INFO] [surefire:test]
[INFO] Tests are skipped.
[INFO] [war:war]
[INFO] Exploding webapp...
[INFO] Assembling webapp realty in C:\Prototype\Mavenized\Product\trails\trunk\trails\exam
ples\realty\target\realty-1.2-SNAPSHOT
[INFO] Copy webapp webResources to C:\Prototype\Mavenized\Product\trails\trunk\trails\exam
ples\realty\target\realty-1.2-SNAPSHOT
[INFO] Generating war C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty\t
arget\realty-1.2-SNAPSHOT.war
[INFO] Building war: C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty\ta
rget\realty-1.2-SNAPSHOT.war
[INFO] [install:install]
[INFO] Installing C:\Prototype\Mavenized\Product\trails\trunk\trails\examples\realty\targe
t\realty-1.2-SNAPSHOT.war to C:\Tomcat-5.5.17\webapps\m2.repository\org\trailsframework\ex
amples\realty\1.2-SNAPSHOT\realty-1.2-SNAPSHOT.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 16 seconds
[INFO] Finished at: Thu Jan 03 09:11:02 EST 2008
[INFO] Final Memory: 22M/127M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Kenneth William](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nhhockeyplayer)** commented

Happening again out of the blue... was building fine yesterday. No changes to this machine or source tree or repo.

[INFO] snapshot com.javaforge.tapestry:tapestry-javaforge:1.0.0-SNAPSHOT: checking for updates
from apache.snapshots
[INFO] snapshot com.javaforge.tapestry:tapestry-javaforge:1.0.0-SNAPSHOT: checking for updates
from howardlewisship.com
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).

Project ID: com.javaforge.tapestry:tapestry-spring:jar:1.0.0

Reason: Cannot find parent: com.javaforge.tapestry:tapestry-javaforge for project: com.javafor
ge.tapestry:tapestry-spring:jar:1.0.0 for project com.javaforge.tapestry:tapestry-spring:jar:1
.0.0

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 minutes 9 seconds
[INFO] Finished at: Fri Feb 29 09:35:15 EST 2008
[INFO] Final Memory: 16M/49M
[INFO] ------------------------------------------------------------------------

C:\Prototype\Mavenized\Product\trails\trunk\trails>mvn clean install
