### ISSUE TITLE
[MNG-3206] Changes to MavenSettingsBuilder breaks backward compatibility

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4723]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** opened **[MNG-3206](https://issues.apache.org/jira/browse/MNG-3206?redirect=false)** and commented

When I tried to run a the component-it-plugin from maven sandbox during an integration-test run on the assembly plugin with a Maven build from Sept. 10, 2007, I got the following:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.settings.MavenSettingsBuilder.buildSettings()Lorg/apache/maven/settings/Settings;
at org.apache.maven.shared.test.plugin.RepositoryTool.findLocalRepositoryDirectory(RepositoryTool.java:100)
at org.apache.maven.shared.test.plugin.ProjectTool.manglePomForTesting(ProjectTool.java:301)
at org.apache.maven.shared.test.plugin.ProjectTool.packageProjectArtifact(ProjectTool.java:168)
at org.apache.maven.shared.test.plugin.ComponentTestTool.prepareForTesting(ComponentTestTool.java:180)
at org.apache.maven.shared.test.plugin.ComponentTestTool.prepareComponentForUnitTestingWithMavenBuilds(ComponentTestTool.java:121)
at org.apache.maven.plugin.componentit.StagingBuildMojo.execute(StagingBuildMojo.java:90)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:650)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:419)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:293)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:150)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:219)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:819)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:418)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:85)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)

This is a backward compatibility issue, and should be addressed in order to ensure smooth migrations from 2.0.x to 2.1-alpha-1

---

**Affects:** 3.0-alpha-1

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

handled by the backward compat aspect now.
