### ISSUE TITLE
[MNG-3231] [regression] pom errors are not reported anymore

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4728]
**[Brian E Fox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf)** opened **[MNG-3231](https://issues.apache.org/jira/browse/MNG-3231?redirect=false)** and commented

See the following -e output, there's no indication what is wrong with the pom

```
$ mvn clean deploy -e
+ Error stacktraces are turned on.

Failed to validate POM for project foo at ...\pom.xml

Error stacktrace:
org.apache.maven.reactor.MavenExecutionException: Failed to validate POM for project foo at ...\pom.xml
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:298)
        at org.apache.maven.DefaultMaven.createReactorManager(DefaultMaven.java:111)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:165)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:820)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:418)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:85)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: org.apache.maven.project.InvalidProjectModelException: Failed to validate POM for project foo at ...\pom.xml
        at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:914)
        at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:675)
        at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:426)
        at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:193)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:330)
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:289)
        ... 13 more

```

---

**Affects:** 3.0-alpha-1

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

should output diagnostics for validation problems regardless of the state of the -e switch now.
