### ISSUE TITLE
[MNG-3181] JDOM artifact filtering is causing problems

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4763]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** opened **[MNG-3181](https://issues.apache.org/jira/browse/MNG-3181?redirect=false)** and commented

For example in the release plug that requires JDOM which uses Jaxen. We are cutting off resolution of Jaxen so the release plugin fails. Anything that requires Jaxen via JDOM will fail.

---

**Affects:** 3.0

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

There are two problems.

1) The JDOM in the root loader causes the release plugin grief
2) The JDOM pulled in by the webdav extension causes the release plugin grief

The problem is that JDOM uses Class.forName (bad) and it's in the root loader and trying to grab something from Jaxen which is in the release plugin loader which causes things to blow. I have no idea how this is working. Things might all be getting jammed in the same classloader, but JDOM and Jaxen are definitely in different classloaders in 2.1 and we get the following.

Exception in thread "main" java.lang.NoClassDefFoundError: org/jaxen/JaxenException
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:164)
at org.jdom.xpath.XPath.newInstance(XPath.java:126)

I have removed JDOM from the core and put the JDOM stuff required for the embedder in a maven-embedder-extras package and this makes more sense as it is an extra and prevents the core from being polluted. But the webdav extension is a problem, currently being loaded in the root loader makes it not work. My theory is that the extension manager was not blocking the loading of artifacts by adding extension artifacts to the filter manager and the classloader was loading child first. We tried to be more standard with later versions of classworlds but i think we need to load child first and let duplicate artifacts find their way into plugin classloaders.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

If the problem is pollution from extensions, can't we find a way to define standard extension points, then load extensions into separate realms and only put imports from those realms into the main realm for implementations of the standard extensions points?

This seems a lot less severe than altering the entire classloading method, which could have severe ramifications for things trying to share project information, for instance...

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

extensions are now loaded into separate ClassRealms, and components defined in the plexus descriptor for the local extension artifact (not its dependencies) are then re-imported back into the main container realm. This gives access to the extension using existing interfaces in the core while still isolating the classes the extension needs to function to the separate realm.
