### ISSUE TITLE
[MNG-3137] IT 0108 (snapshot updates) fail intermittently 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4814]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-3137](https://issues.apache.org/jira/browse/MNG-3137?redirect=false)** and commented

testSnapshotUpdatedWithMetadata(org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest)  Time elapsed: 4.443 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<updated...> but was:<original...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at org.apache.maven.it.Verifier.assertArtifactContents(Verifier.java:1493)
at org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest.assertArtifactContents(MavenIT0108SnapshotUpdateTest.java:255)
at org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest.testSnapshotUpdatedWithMetadata(MavenIT0108SnapshotUpdateTest.java:113)
at org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest.testSnapshotUpdatedWithMetadata(MavenIT0108SnapshotUpdateTest.java:113)

testSnapshotUpdatedWithMetadataUsingFileTimestamp(org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest)  Time elapsed: 5.265 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<updated...> but was:<original...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at org.apache.maven.it.Verifier.assertArtifactContents(Verifier.java:1493)
at org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest.assertArtifactContents(MavenIT0108SnapshotUpdateTest.java:255)
at org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest.testSnapshotUpdatedWithMetadataUsingFileTimestamp(MavenIT0108SnapshotUpdateTest.java:195)
at org.apache.maven.integrationtests.MavenIT0108SnapshotUpdateTest.testSnapshotUpdatedWithMetadataUsingFileTimestamp(MavenIT0108SnapshotUpdateTest.java:195)

---

**Issue Links:**
- [MNG-3158](https://issues.apache.org/jira/browse/MNG-3158) IT 108 success remains sporadic
 (_**"is duplicated by"**_)
- [MNG-1908](https://issues.apache.org/jira/browse/MNG-1908) snapshots not deployed using m2, or deployed with uniqueVersion = false are not updated if present locally

- [MNG-2780](https://issues.apache.org/jira/browse/MNG-2780) snapshots are not updated based on metadata deployed with uniqueVersion = false

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

it appears MavenIT0109ReleaseUpdateTest is the same.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
