### ISSUE TITLE
[MNG-3085] mvn script isn't setting maven.home correctly with cygwin on xp

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4818]
**[Brian E Fox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf)** opened **[MNG-3085](https://issues.apache.org/jira/browse/MNG-3085?redirect=false)** and commented

The script is generating the following execution:

```
 
/cygdrive/c/program files/java/jdk1.5.0_11/bin/java -classpath c:\program files\
maven2/boot/classworlds-1.1.jar -Dclassworlds.conf=c:\program files\maven2/bin/m
2.conf -Dmaven.home=c:\program files\maven2 org.codehaus.classworlds.Launcher
```

In the invoker, it attempts to read the env to find the maven executable. Augmented with debug;

```
if ( mavenHome == null )
     {
         String mavenHomeProperty = System.getProperty( "maven.home" );
         System.out.println("maven.home="+mavenHomeProperty);
         if ( mavenHomeProperty != null )
         {
             mavenHome = new File( mavenHomeProperty );
             System.out.println("mavenHome="+mavenHome.getAbsolutePath());
             System.out.println("mavenHome.isDirectory="+mavenHome.isDirectory());
             if ( !mavenHome.isDirectory() )
             {
                 File binDir = mavenHome.getParentFile();
                 System.out.println("binDir="+binDir);
                 if ( "bin".equals( binDir.getName() ) )
                 {
                     // ah, they specified the mvn executable instead...
                     mavenHome = binDir.getParentFile();
                 }
                 else
                 {
                     throw new IllegalStateException( "${maven.home} is not specified as a directory: \'"
                         + mavenHomeProperty + "\'." );
                 }
             }
         }
```

Results in:

```
 
maven.home=${env.M2_HOME}
mavenHome=e:\svn\maven\maven-plugins\maven-eclipse-plugin\${env.M2_HOME}
mavenHome.isDirectory=false
binDir=null
```

And crashes on  if ( "bin".equals( binDir.getName() ) )

I tried modifying the cygpath commands to remove the space and reverse the backslashes in the -Dmaven.home= but none of them seemed to work.

---

**Affects:** 2.0.7

**Issue Links:**
- [MINVOKER-87](https://issues.apache.org/jira/browse/MINVOKER-87) Invoker install goal fails when used in eclipse

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I think I'd prefer to make the invoker better at handling this if possible?

**Comment by jira-importer** [comment]
**[Tuomas Kiviaho](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tuomas_kiviaho)** commented

I was trying use bulldozer instead of a shovel (filtering using invoker:run instead of resources plugin at process-test-resources) and got following error with invoker:run using maven embedder provided by m2eclipse. I'm reporting this in case if somebody is trying something similar with following results.

[ERROR] ${maven.home} is not specified as a directory: 'C:\cygwin\home\kivtuo\scm\eniram\commons\trunk\EMBEDDED'.
java.lang.IllegalStateException: ${maven.home} is not specified as a directory: 'C:\cygwin\home\kivtuo\scm\eniram\commons\trunk\EMBEDDED'.
at org.apache.maven.shared.invoker.MavenCommandLineBuilder.findMavenExecutable(MavenCommandLineBuilder.java:470)
...
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:460)
