### ISSUE TITLE
[MNG-3077] NullPointerException, if MojoExecutionException has no message

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4823]
**[Johannes Konstantinidis](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lachdanan)** opened **[MNG-3077](https://issues.apache.org/jira/browse/MNG-3077?redirect=false)** and commented

It seems, that you get a NPE, when a throwable passed to MojoExecutionExceptionDiagnoser.diagose(Throwable error) has no message, which means the message is null.

java.lang.NullPointerException
at org.apache.maven.usability.MojoExecutionExceptionDiagnoser.diagnose(MojoExecutionExceptionDiagnoser.java:64)
at org.apache.maven.usability.diagnostics.ErrorDiagnostics.diagnose(ErrorDiagnostics.java:84)
at org.apache.maven.DefaultMaven.logDiagnostics(DefaultMaven.java:727)
at org.apache.maven.DefaultMaven.logError(DefaultMaven.java:672)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:131)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Line 64 --> if ( directCauseMessage != null && mee.getMessage().indexOf( directCauseMessage ) < 0 )
(Source: Revision 495147)

---

**Affects:** 2.0.7

6 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Graham Miller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gmiller)** commented

Could someone please post a workaround or fix for this soon.  It's a showstopper, I can't tell why my build is broken, I only get the NPE.  Thanks!

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

This was already fixed:

Revision: 576588
Author: carlos
Date: 5:18:01 PM, Monday, September 17, 2007
Message:
consider the case when exception message is null

---

Modified : /maven/components/branches/maven-2.0.x/maven-core/src/main/java/org/apache/maven/usability/MojoExecutionExceptionDiagnoser.java

I added unit tests to ensure it stays fixed, but MojoExecution and MojoFailure exceptions
