### ISSUE TITLE
[MNG-3070] ${x} properties no longer expanded in </version> tag after 2.0.3

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4826]
**[Gabriele Garuglieri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=garu)** opened **[MNG-3070](https://issues.apache.org/jira/browse/MNG-3070?redirect=false)** and commented

I was experimenting  with maven using killer-app sample (http://www.sonatype.com/book/examples/book-killerapp.zip) from Sonatipe book (http://www.sonatype.com/book/index.html) and immediately hit a show stopper.
Maven 2.0.3 is able to build the sample out of the box, but any later version up to 2.0.7 chokes telling that it's not able to find the parent project:

C:\home\prjHome\mavenTest\killerapp>mvn help:effective-pom
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

GroupId: com.training.killerapp
ArtifactId: killerapp
Version: 1.0-SNAPSHOT

Reason: Unable to download the artifact from any repository

com.training.killerapp:killerapp:pom:1.0-SNAPSHOT

from the specified remote repositories:
central (http://repo1.maven.org/maven2)

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Cannot find parent: com.training.killerapp:killerapp for project: null:killerapp-model:jar:null for project null:killerapp-model:jar:null
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:378)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:290)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

All the problems looks to be caused by the fact that the root POM has the following construct (that should be perfectly legal) in it:
\<version>${killerappVersion}\</version>

\<properties>
\<killerappVersion>1.0-SNAPSHOT\</killerappVersion>
\</properties>

If i substitute the version tag in the root POM with the following everything works with all versions.
\<version>1.0-SNAPSHOT\</version>

I was not able to find anywhere in the doc that ${x} substitution is no longer legal in \</version> tag, so i think this is a regression from 2.0.3.

Btw, all the test were done with clean local repository.

---

**Affects:** 2.0.7

**Issue Links:**
- [MNG-3536](https://issues.apache.org/jira/browse/MNG-3536) REGRESSION: pom.build.sourceDirectory in Maven 2.0.9: it doesn't work anymore

- [MNG-3535](https://issues.apache.org/jira/browse/MNG-3535) Valid properties which look self referential fail to resolve

- [MNG-2562](https://issues.apache.org/jira/browse/MNG-2562) expose current time as a property for POM interpolation

- [MNG-624](https://issues.apache.org/jira/browse/MNG-624) automatic parent versioning

15 votes, 10 watchers

**Comment by jira-importer** [comment]
**[Wojtek K](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wojtek)** commented

If MNG-624 was resolved, this one could be closed.

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

will need to verify, even maven uses properties in versions.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

The zip you reference in this description no longer exists, and there isn't enough information in this bug report to reproduce the problem. If you have a failing test case that you can attach, please don't hesitate to reopen this issue.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Adding fix-for for both 2.0.10 and 2.1.0-M1, since 2.1.0-M1 will actually be released first and may not incorporate all of the eventual issue fixes released in 2.0.10.
