### ISSUE TITLE
[MNG-3040] Failure to construct build plan fatal error on trunk r545155

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4842]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-3040](https://issues.apache.org/jira/browse/MNG-3040?redirect=false)** and commented

see attached pom which causes this:

mcbrett:~/scm/maven/sandbox/continuum/continuum-data-upgrade brett$ mvn clean install -e
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building Unnamed - org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT
  [INFO] task-segment: [clean, install]
  [INFO] ----------------------------------------------------------------------------
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Failed to construct build plan for: org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT ( task-segment: [clean, install] ). Reason: No phase specified for goal: exec in plugin: org.codehaus.mojo:exec-maven-plugin from POM: org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT
  [INFO] ------------------------------------------------------------------------
  [INFO] Trace
  org.apache.maven.BuildFailureException: Failed to construct build plan for: org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT ( task-segment: [clean, install] ). Reason: No phase specified for goal: exec in plugin: org.codehaus.mojo:exec-maven-plugin from POM: org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:296)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:112)
  at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:906)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:367)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:585)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
  Caused by: org.apache.maven.lifecycle.LifecycleExecutionException: Failed to construct build plan for: org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT ( task-segment: [clean, install] ). Reason: No phase specified for goal: exec in plugin: org.codehaus.mojo:exec-maven-plugin from POM: org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getLifecycleBindings(DefaultLifecycleExecutor.java:305)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:246)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:141)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
  ... 11 more
  Caused by: org.apache.maven.lifecycle.LifecycleSpecificationException: No phase specified for goal: exec in plugin: org.codehaus.mojo:exec-maven-plugin from POM: org.apache.maven.continuum:continuum-data-upgrade:jar:1.1-SNAPSHOT
  at org.apache.maven.lifecycle.binding.DefaultLifecycleBindingManager.getProjectCustomBindings(DefaultLifecycleBindingManager.java:295)
  at org.apache.maven.lifecycle.plan.DefaultBuildPlanner.constructBuildPlan(DefaultBuildPlanner.java:54)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getLifecycleBindings(DefaultLifecycleExecutor.java:294)
  ... 14 more
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: < 1 second
  [INFO] Finished at: Thu Jun 07 22:40:57 EST 2007
  [INFO] Final Memory: 2M/5M
  [INFO] ------------------------------------------------------------------------
  [INFO] ------------------------------------------------------------------------
  [INFO] BUILD SUCCESSFUL
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: < 1 second
  [INFO] Finished at: Thu Jun 07 22:40:57 EST 2007
  [INFO] Final Memory: 2M/5M
  [INFO] --------------------------------------------------------------------

---

**Affects:** 3.0-alpha-1

**Attachments:**
- [exec-phase-binding-test.zip](https://issues.apache.org/jira/secure/attachment/12712185/exec-phase-binding-test.zip) (_4.60 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712189/pom.xml) (_3.61 kB_)

**Issue Links:**
- [MNG-3054](https://issues.apache.org/jira/browse/MNG-3054) [regression] maven reports build success even on error.

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Here's the relevant code chunk:

```
                               String phase = execution.getPhase();
                                if ( phase == null )
                                {
                                    if ( pluginDescriptor == null )
                                    {
                                        try
                                        {
                                            pluginDescriptor = pluginLoader.loadPlugin( plugin, project );
                                        }
                                        catch ( PluginLoaderException e )
                                        {
                                            throw new LifecycleLoaderException( "Failed to load plugin: " + plugin
                                                            + ". Reason: " + e.getMessage(), e );
                                        }
                                    }

                                    if ( pluginDescriptor.getMojos() == null )
                                    {
                                        logger.error( "Somehow, the PluginDescriptor for plugin: " + plugin.getKey()
                                                        + " contains no mojos. This is highly irregular. Ignoring..." );
                                        continue;
                                    }

                                    MojoDescriptor mojoDescriptor = pluginDescriptor.getMojo( goal );
                                    phase = mojoDescriptor.getPhase();

                                    if ( phase == null )
                                    {
                                        throw new LifecycleSpecificationException( "No phase specified for goal: "
                                                        + goal + " in plugin: " + plugin.getKey() + " from POM: "
                                                        + projectId );
                                    }
```

Are you sure that one of {your POM, exec plugin} specifies a phase binding??

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

The mojo itself does not seem to have an `@phase` annotation, so are you binding it to a phase in your \<execution/>?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

No, that's the point. I don't want to use it in the lifecycle (the pom is there if you'd like to look at the execution)

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

You have:

```xml
<executions>
   <execution>
     <goals>
       <goal>exec</goal>
     </goals>
   </execution>
```

in there. How do you figure this will not bind it to the lifecycle? That's the point of an execution.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

sorry John, you're right.

So in 2.0.6, 'binding' something without a phase causes it to be ignored.

I'd suggest you change this to fail fast with a clearer error message ("Can't bind an execution without a phase if the mojo doesn't have a default phase").

Thanks.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

This test shows that this sort of phase binding works in 2.0.5, 2.0.6, 2.0.7, and 2.1-snapshot...you can run this test in any version of maven to check for this problem.

I have not been able to replicate the issue anywhere.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

I'm closing this issue, as at best we can call this a reporting issue (in terms of providing a better error message, I guess...)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

the compile goal has a default phase, so does not reproduce the error. Change it to 'aspectj-report' in the example you provided and it is still present.

Also note the incorrect error result of build successful - is that a known bug?

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Did you guys sort this out?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

John fixed it (the error is a bit confusing, but it's better than the exception :)
