### ISSUE TITLE
[MNG-3055] [regression] loader constraint problems with XmlSerializer if attaching site descriptor

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4852]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-3055](https://issues.apache.org/jira/browse/MNG-3055?redirect=false)** and commented

Was not a problem on 2.0.6.

eg. try mvn install from the root of the plugins reactor, or surefire (either trunk or branch).

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] loader constraints violated when linking org/codehaus/plexus/util/xml/pull/XmlSerializer class
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.LinkageError: loader constraints violated when linking org/codehaus/plexus/util/xml/pull/XmlSerializer class
at org.apache.maven.doxia.site.decoration.io.xpp3.DecorationXpp3Writer.writeBody(DecorationXpp3Writer.java:119)
at org.apache.maven.doxia.site.decoration.io.xpp3.DecorationXpp3Writer.writeDecorationModel(DecorationXpp3Writer.java:202)
at org.apache.maven.doxia.site.decoration.io.xpp3.DecorationXpp3Writer.write(DecorationXpp3Writer.java:67)
at org.apache.maven.plugins.site.SiteDescriptorArtifactMetadata.storeInLocalRepository(SiteDescriptorArtifactMetadata.java:81)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.install(DefaultRepositoryMetadataManager.java:450)
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:79)
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:94)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4 seconds
[INFO] Finished at: Thu Jun 14 16:17:50 EST 2007
[INFO] Final Memory: 6M/12M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.7

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Fixed by using a realm::import From for the xml parser classes.
