### ISSUE TITLE
[MNG-3030] PluginParameterExpressionEvaluatorTest failure in the components maven-core module 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4857]
**[Young Lee](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=youngl)** opened **[MNG-3030](https://issues.apache.org/jira/browse/MNG-3030?redirect=false)** and commented

ant bootstrap build on the maven 2.1 components trunk test failure.  The components maven-core test PluginParameterExpressionEvaluatorTest  fails with the message:

---

Test set: org.apache.maven.plugin.PluginParameterExpressionEvaluatorTest

---

Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.922 sec <<< F
AILURE!
testTwoExpressions(org.apache.maven.plugin.PluginParameterExpressionEvaluatorTest)  Time elapsed: 0.094 sec  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<C:\svnroot\maven\components\maven-core\expected-directory\expected-finalName> but was:<C:\svnroot\maven\components\maven-core\expected-directory/expected-finalName>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:71)
at org.apache.maven.plugin.PluginParameterExpressionEvaluatorTest.testTwoExpressions(PluginParameterExpressionEvaluatorTest.java:259)

---

**Affects:** 3.0

**Attachments:**
- [MNG-3030-maven-core.patch](https://issues.apache.org/jira/secure/attachment/12712186/MNG-3030-maven-core.patch) (_920 bytes_)

**Comment by jira-importer** [comment]
**[Young Lee](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=youngl)** commented

fix for the test is attached

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Thanks, Carlos fixed this for windows.
