### ISSUE TITLE
[MNG-3028] plugin configuration issue (DefaultPluginManager.mergeMojoConfiguration)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4865]
**[Cliff Resnick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cresnick)** opened **[MNG-3028](https://issues.apache.org/jira/browse/MNG-3028?redirect=false)** and commented

The embedder is throwing an error while configuring the xdoclet-maven-plugin.
The error message I get is:
"on the command line, specify: '-DdummyExpression=VALUE'                  Cause: Class 'org.codehaus.classworlds.ClassRealm' cannot be instantiated"
In debugging, I noticed that the "dummyExpression" is being introduced in DefaultPluginManager.mergeMojoConfiguration, which takes two parameters (pomConfiguration, mojoDescriptor)
pomConfiguration (DOM)=
\<configuration>
\<tasks>
\<ejbdoclet excludedtags="@version,@author" destdir="${project.build.directory}/generated-sources/xdoclet" ejbspec="2.0">
\<fileset dir="src/main/java">
\<include name="**/*Bean.java"/>
\</fileset>
\<utilobject destdir="${project.build.directory}/generated-sources/xdoclet">\</utilobject>
\<mdb destdir="${project.build.directory}/generated-sources/xdoclet">\</mdb>
\<localinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<localhomeinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<remoteinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<homeinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<deploymentdescriptor destdir="${project.build.directory}/classes/META-INF">\</deploymentdescriptor>
\<jboss destdir="${project.build.directory}/classes/META-INF" version="4.0">\</jboss>
\</ejbdoclet>
\</tasks>
\<classRealm/>
\<generatedSourcesDirectory/>
\<project/>
\<sourceDirectory/>
\</configuration>

mojoDescriptor =
org.apache.maven.plugin.descriptor.MojoDescriptor [role: 'org.apache.maven.plugin.Mojo', hint: 'org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet' realm: 'org.codehaus.mojo:xdoclet-maven-plugin']

what is returned is:

\<?xml version="1.0" encoding="UTF-8"?>
\<configuration>
\

\<classRealm implementation="org.codehaus.classworlds.ClassRealm">${dummyExpression}\</classRealm>

\<generatedSourcesDirectory implementation="java.lang.String">${project.build.directory}/generated-sources/xdoclet\</generatedSourcesDirectory>
\<project implementation="org.apache.maven.project.MavenProject">${project}\</project>
\<sourceDirectory implementation="java.lang.String">${basedir}/src/main/java\</sourceDirectory>
\<tasks implementation="org.apache.tools.ant.Target">
\<ejbdoclet excludedtags="@version,@author" destdir="${project.build.directory}/generated-sources/xdoclet" ejbspec="2.0">
\<fileset dir="src/main/java">
\<include name="**/*Bean.java"/>
\</fileset>
\<utilobject destdir="${project.build.directory}/generated-sources/xdoclet">\</utilobject>
\<mdb destdir="${project.build.directory}/generated-sources/xdoclet">\</mdb>
\<localinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<localhomeinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<remoteinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<homeinterface destdir="${project.build.directory}/generated-sources/xdoclet"/>
\<deploymentdescriptor destdir="${project.build.directory}/classes/META-INF">\</deploymentdescriptor>
\<jboss destdir="${project.build.directory}/classes/META-INF" version="4.0">\</jboss>
\</ejbdoclet>${tasks}\</tasks>
\</configuration>

The top-level stack trace is kind of misleading:

org.apache.maven.lifecycle.LifecycleExecutionException: Error configuring: org.codehaus.mojo:xdoclet-maven-plugin. Reason: Unable to parse the created DOM for plugin configuration

If it helps, here is the original plugin config from my pom:

    <plugin>
         <groupId>org.codehaus.mojo</groupId>
         <artifactId>xdoclet-maven-plugin</artifactId>
         <executions>
              <execution>
                       <phase>generate-sources</phase>
                       <goals>
                                <goal>xdoclet</goal>
                       </goals>
                       <configuration>
                                <tasks>
                                         <ejbdoclet excludedtags="@version,@author" destdir="${project.build.directory}/generated-sources/xdoclet" ejbspec="2.0">
                                                  <fileset dir="src/main/java">
                                                               <include name="**/*Bean.java" />
                                                  </fileset>
                                                  <utilobject destdir="${project.build.directory}/generated-sources/xdoclet">
                                                  </utilobject>
                                                  <mdb destdir="${project.build.directory}/generated-sources/xdoclet">
                                                  </mdb>
                                                  <localinterface destdir="${project.build.directory}/generated-sources/xdoclet" />
                                                  <localhomeinterface destdir="${project.build.directory}/generated-sources/xdoclet" />
                                                  <remoteinterface destdir="${project.build.directory}/generated-sources/xdoclet" />
                                                  <homeinterface destdir="${project.build.directory}/generated-sources/xdoclet" />
                                                  <deploymentdescriptor destdir="${project.build.directory}/classes/META-INF">
                                                  </deploymentdescriptor>
                                                  <jboss destdir="${project.build.directory}/classes/META-INF" version="4.0">
                                                  </jboss>
                                         </ejbdoclet>
                                </tasks>
                       </configuration>
              </execution>
         </executions>
    </plugin>

---

**Affects:** 3.0

**Attachments:**
- [sample-ejb-config.zip](https://issues.apache.org/jira/secure/attachment/12712026/sample-ejb-config.zip) (_1.29 kB_)

2 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Give me a sample project and I'll start fixing it.

**Comment by jira-importer** [comment]
**[Cliff Resnick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cresnick)** commented

I attached a sample project (actually just a pom.xml since the error occurs during configuration)

I also noticed that  ${dummyExpression} is introduced by xdoclet mojo, passes empty string test and so is included for population even though the parameter does not resolve to anything.

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

I'm getting the same problem but I'm not calling the embedder. It looks more like a core maven issue or rather a xdoclet one:

```
[INFO] Error for project: Maven Clover Plugin XDoclet Sample (during org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2:xdoclet)
[INFO] ------------------------------------------------------------------------
[INFO] Failed to configure plugin parameters for: org.codehaus.mojo:xdoclet-maven-plugin:1.0-alpha-2

on the command line, specify: '-DdummyExpression=VALUE'

Cause: Class 'org.codehaus.classworlds.ClassRealm' cannot be instantiated
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error configuring: org.codehaus.mojo:xdoclet-maven-plugin. Reason: Unable to parse the created DOM for plugin configuration
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:388)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:260)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:146)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:304)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:124)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:906)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:369)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Error configuring: org.codehaus.mojo:xdoclet-maven-plugin. Reason: Unable to parse the created DOM for plugin configuration
        at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1180)
        at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:822)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:590)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:359)
        ... 14 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Class 'org.codehaus.classworlds.ClassRealm' cannot be instantiated
        at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject(AbstractConfigurationConverter.java:133)
        at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:86)
        at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
        at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:135)
        at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
        at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1174)
        ... 17 more
Caused by: java.lang.InstantiationException: org.codehaus.classworlds.ClassRealm
        at java.lang.Class.newInstance0(Class.java:335)
        at java.lang.Class.newInstance(Class.java:303)
        at org.codehaus.plexus.component.configurator.converters.AbstractConfigurationConverter.instantiateObject(AbstractConfigurationConverter.java:123)
        ... 22 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD ERRORS
[INFO] ------------------------------------------------------------------------
```

**Comment by jira-importer** [comment]
**[Cliff Resnick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cresnick)** commented

It appears this problem was in Plexus and has been fixed. Anny chance there can be a new drop of Maven Embedder that contains the Plexus fix?

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

This is not an MNGECLIPSE problem but a general Maven problem and is a result of the xdoclet plugin extending the antrun plugin which I will have to look into. I will move this issue to MNG.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Reopen if this is still an issue.
