### ISSUE TITLE
[MNG-3021] it0114 is failing in trunk

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4868]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** opened **[MNG-3021](https://issues.apache.org/jira/browse/MNG-3021?redirect=false)** and commented

it's not finding the plugin resource in the plugin classloader/realm.

---
No further details from [MNG-3021](https://issues.apache.org/jira/browse/MNG-3021?redirect=false)

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

output in surefire-reports is:

org.apache.maven.it.VerificationException: Exit code was non-zero: 1; log =
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Searching repository for plugin with prefix: 'clean'.
  [INFO] ----------------------------------------------------------------------------
  [INFO] Building it0114 - plugin runner
  [INFO]    task-segment: [clean:clean, verify]
  [INFO] ----------------------------------------------------------------------------
  [INFO] [clean:clean]
  [INFO] Deleting directory /Users/jdcasey/workspace/maven/core-integration-testing/core-integration-tests/target/test-classes/it0114-extensionThatProvidesResources/test-project/target
  [INFO] Deleting directory /Users/jdcasey/workspace/maven/core-integration-testing/core-integration-tests/target/test-classes/it0114-extensionThatProvidesResources/test-project/target/classes
  [INFO] Deleting directory /Users/jdcasey/workspace/maven/core-integration-testing/core-integration-tests/target/test-classes/it0114-extensionThatProvidesResources/test-project/target/test-classes
  [INFO] Deleting directory /Users/jdcasey/workspace/maven/core-integration-testing/core-integration-tests/target/test-classes/it0114-extensionThatProvidesResources/test-project/target/site
  [INFO] [site:attach-descriptor]
  [INFO] [it0114:test]
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Can't find it0114_rule_set.xml on classpath!!
  [INFO] ------------------------------------------------------------------------
  [INFO] Trace
  org.apache.maven.BuildFailureException: Can't find it0114_rule_set.xml on classpath!!
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:308)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:124)
  at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:906)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:367)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
  Caused by: org.apache.maven.lifecycle.LifecycleExecutionException: Can't find it0114_rule_set.xml on classpath!!
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:379)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:255)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:141)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:304)
  ... 11 more
  Caused by: org.apache.maven.plugin.MojoExecutionException: Can't find it0114_rule_set.xml on classpath!!
  at org.apache.maven.plugin.It0014Mojo.execute(It0014Mojo.java:26)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:638)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:354)
  ... 14 more
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: < 1 second
  [INFO] Finished at: Wed May 30 12:00:46 EDT 2007
  [INFO] Final Memory: 4M/8M
  [INFO] ------------------------------------------------------------------------
  [INFO] Error for project: it0114 - plugin runner (during org.apache.maven.its.it0114:it0114-plugin:1.0:test)
  [INFO] ------------------------------------------------------------------------
  [INFO] Can't find it0114_rule_set.xml on classpath!!
  [INFO] ------------------------------------------------------------------------
  [INFO] Trace
  org.apache.maven.lifecycle.LifecycleExecutionException: Can't find it0114_rule_set.xml on classpath!!
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:379)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:255)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:141)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:304)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:124)
  at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:906)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:367)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
  Caused by: org.apache.maven.plugin.MojoExecutionException: Can't find it0114_rule_set.xml on classpath!!
  at org.apache.maven.plugin.It0014Mojo.execute(It0014Mojo.java:26)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:638)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:354)
  ... 14 more
  [INFO] ------------------------------------------------------------------------
  [INFO] BUILD ERRORS
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: < 1 second
  [INFO] Finished at: Wed May 30 12:00:46 EDT 2007
  [INFO] Final Memory: 4M/8M
  [INFO] ------------------------------------------------------------------------
  FATAL ERROR: Unable to configure the Maven application
  Error stacktrace:
  org.apache.maven.reactor.MavenExecutionException: Some builds failed
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:165)
  at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:906)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:367)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
  at org.apache.maven.it.Verifier.executeGoals(Verifier.java:941)
  at org.apache.maven.it.Verifier.executeGoal(Verifier.java:807)
  at org.apache.maven.it.Verifier.executeGoal(Verifier.java:802)
  at org.apache.maven.integrationtests.MavenIT0114ExtensionThatProvidesResources.testit0114(MavenIT0114ExtensionThatProvidesResources.java:38)
  at org.apache.maven.integrationtests.MavenIT0114ExtensionThatProvidesResources.testit0114(MavenIT0114ExtensionThatProvidesResources.java:38)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at junit.framework.TestCase.runTest(TestCase.java:154)
  at org.apache.maven.integrationtests.AbstractMavenIntegrationTestCase.runTest(AbstractMavenIntegrationTestCase.java:75)
  at junit.framework.TestCase.runBare(TestCase.java:127)
  at junit.framework.TestResult$1.protect(TestResult.java:106)
  at junit.framework.TestResult.runProtected(TestResult.java:124)
  at junit.framework.TestResult.run(TestResult.java:109)
  at junit.framework.TestCase.run(TestCase.java:118)
  at junit.framework.TestSuite.runTest(TestSuite.java:208)
  at junit.framework.TestSuite.run(TestSuite.java:203)
  at junit.framework.TestSuite.runTest(TestSuite.java:208)
  at junit.framework.TestSuite.run(TestSuite.java:203)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:213)
  at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:138)
  at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:125)
  at org.apache.maven.surefire.Surefire.run(Surefire.java:132)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:290)
  at org.apache.maven.surefire.booter.SurefireBooter.run(SurefireBooter.java:198)
  at org.apache.maven.plugin.surefire.SurefirePlugin.execute(SurefirePlugin.java:398)
  at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:638)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:354)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:255)
  at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:141)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:304)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:124)
  at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:906)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:367)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:324)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

The issue may have been specific to my environment, as it seems to be passing now. Will reopen if things start failing again...
