### ISSUE TITLE
[MNG-2860] Empty <module></module> entry causes OutOfMemoryError

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4873]
**[Thorsten Scherler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thorsten)** opened **[MNG-2860](https://issues.apache.org/jira/browse/MNG-2860?redirect=false)** and commented

Accidentially I forgot to remove an empty \<module>\</module> entry in my pom.xml. When I tried to fully clean my project and all its subprojects Maven crashes with an OutOfMemoryError after a couple of minutes:

H2841@YBPB055257 /cygdrive/d/workspaces/sukv-maven
$ mvn -e -X clean
+ Error stacktraces are turned on.
  Maven version: 2.0.5
  [DEBUG] Building Maven user-level plugin registry from: 'D:\Dokumente und Einstellungen\H2841\.m2\plugin-registry.xml'
  [DEBUG] Building Maven global-level plugin registry from: 'c:\maven-2.0.5\conf\plugin-registry.xml'
  [INFO] Scanning for projects...
  [INFO] ------------------------------------------------------------------------
  [ERROR] FATAL ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Java heap space
  [INFO] ------------------------------------------------------------------------
  [DEBUG] Trace
  java.lang.OutOfMemoryError: Java heap space
  at org.codehaus.plexus.util.xml.pull.MXParser.ensurePC(MXParser.java:3047)
  at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1374)
  at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1090)
  at org.codehaus.plexus.util.xml.pull.MXParser.nextText(MXParser.java:1055)
  at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseScm(MavenXpp3Reader.java:4045)
  at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2206)
  at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4422)
  at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1345)
  at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1309)
  at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:429)
  at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:195)
  at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:523)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:455)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:499)
  [INFO] ------------------------------------------------------------------------
  [INFO] Total time: 5 minutes 26 seconds
  [INFO] Finished at: Wed Mar 07 12:40:03 CET 2007
  [INFO] Final Memory: 31M/234M
  [INFO] ------------------------------------------------------------------------

H2841@YBPB055257 /cygdrive/d/workspaces/sukv-maven
$

pom.xml to test:

\<modules>
	\<module>module1\</module>
	...
	\<module>moduleN\</module>
	\<module>\</module>
\</modules>
Maven doesn't complain about the empty \<module>\</module> entry, and obviously runs in a recursion in this case.

---

**Affects:** 2.0.5

**Backported to:** [2.0.7](https://github.com/apache/maven/milestone/47?closed=1)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Added a simple check for the empty string.

**Comment by jira-importer** [comment]
**[Krashan Brahmanjara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krokodylowy3)** commented

Not fixed. Still exist even more after update to m2eclipse 0.10.0.20100209-800 on Eclipse 3.5 build  20100218-1602

INFO] Trace
java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOf(Arrays.java:2882)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:515)
at java.lang.StringBuffer.append(StringBuffer.java:306)
at java.io.StringWriter.write(StringWriter.java:77)
at hidden.org.codehaus.plexus.util.IOUtil.copy(IOUtil.java:214)
at hidden.org.codehaus.plexus.util.IOUtil.toString(IOUtil.java:416)
at hidden.org.codehaus.plexus.util.IOUtil.toString(IOUtil.java:405)
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1595)
at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1624)
at org.apache.maven.project.DefaultMavenProjectBuilder.getSuperModel(DefaultMavenProjectBuilder.java:1790)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:744)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

This is not a problem in Maven, I can't reproduce. If this is only happening inside M2Eclipse then file your issue there:

https://issues.sonatype.org/browse/MNGECLIPSE
