### ISSUE TITLE
[MNG-2835] The localRepository settings from the global settings file are ignored

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4892]
**[Aaron Digulla](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=digulla)** opened **[MNG-2835](https://issues.apache.org/jira/browse/MNG-2835?redirect=false)** and commented

With the latest embedder (20070219), the localRepository is only taken into account when it's specified in the user settings. When it is only in the global settings file, it's ignored.

I think the problem is that not all settings are copied when

request = defaultsPopulator.populateDefaults( request );

is called.

---

**Affects:** 2.0-alpha-1

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Fixed and tested:

http://svn.apache.org/repos/asf/maven/components/trunk/maven-embedder/src/test/java/org/apache/maven/embedder/MavenEmbedderBehaviorTest.java

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

MavenEmbedderBehaviorTest fails under windows

---

Test set: org.apache.maven.embedder.MavenEmbedderBehaviorTest

---

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.25 sec <<< FAILURE!
testThatTheLocalRepositoryIsTakenFromGlobalSettingsWhenUserSettingsAreNull(org.apache.maven.embedder.MavenEmbedderBehaviorTest)  Time elapsed: 0.25 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:</global/maven/...> but was:<D:\global\maven\...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at org.apache.maven.embedder.MavenEmbedderBehaviorTest.testThatTheLocalRepositoryIsTakenFromGlobalSettingsWhenUserSettingsAreNull(MavenEmbedderBehaviorTest.java:47)
at org.apache.maven.embedder.MavenEmbedderBehaviorTest.testThatTheLocalRepositoryIsTakenFromGlobalSettingsWhenUserSettingsAreNull(MavenEmbedderBehaviorTest.java:47)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

This is now working.
