### ISSUE TITLE
[MNG-2825] LightWeightHttpWagon cannot handle https when port is explicitly specified.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4898]
**[Bruno Ranschaert](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=branscha)** opened **[MNG-2825](https://issues.apache.org/jira/browse/MNG-2825?redirect=false)** and commented

When a repository is specified with https and a port number like this:

\<repository>
\<id>Central-2\</id>
\<url>https://\<my server name>:1234/maven2\</url>            
\</repository>

The build process raises an error

Caused by: java.io.IOException: HTTPS hostname wrong:  should be \<my server name>
at sun.net.www.protocol.https.HttpsClient.checkURLSpoofing(HttpsClient.java:490)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:415)
......

The port number (1234) is not accepted.

---

**Affects:** 2.0.4

**Comment by jira-importer** [comment]
**[Bruno Ranschaert](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=branscha)** commented

The reason for the error is that the SSL certificate does not contain the correct hostname, so the verification of the certificate fails. So this error  has nothing to do with the port number (and put me on the wrong track). I came to this conclusion after doing a test with a socket forwarder which forwarded the 443 port to the 1234 port. The result was the same so it had nothing to do with the url.

Solution: correct the server certificate.

Note: Maybe it would be better for the http wagon to issue a warning iso a plain error message.
