### ISSUE TITLE
[MNG-2791] Error parsing Maven 1 POM file with an extend tag

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#4931]
**[Rodrigo Ruiz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nodens2k)** opened **[MNG-2791](https://issues.apache.org/jira/browse/MNG-2791?redirect=false)** and commented

Trying to rebuild a project that depends on an artifact obtained from a Maven1 repository, I get the following stacktrace:

org.eclipse.core.runtime.CoreException: Parsing error [whatever].pom; org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'extend' (position: START_TAG seen ...\</modelVersion>\n  \<extend>... `@4`:11)
at org.maven.ide.eclipse.embedder.MavenModelManager.readMavenModel(MavenModelManager.java:137)
at org.maven.ide.eclipse.embedder.ClassPathResolver.getJavaDocUrl(ClassPathResolver.java:241)
at org.maven.ide.eclipse.embedder.ClassPathResolver.resolveClasspathEntries(ClassPathResolver.java:154)
at org.maven.ide.eclipse.builder.Maven2Builder.updateClasspath(Maven2Builder.java:95)
at org.maven.ide.eclipse.builder.Maven2Builder.build(Maven2Builder.java:86)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:603)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:167)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:201)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:230)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:233)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:252)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:285)
at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:208)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
org.eclipse.core.runtime.CoreException[4]: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised tag: 'extend' (position: START_TAG seen ...\</modelVersion>\n  \<extend>... `@4`:11)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2405)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4438)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4449)
at org.apache.maven.embedder.MavenEmbedder.readModel(MavenEmbedder.java:208)
at org.maven.ide.eclipse.embedder.MavenModelManager.readMavenModel(MavenModelManager.java:133)
at org.maven.ide.eclipse.embedder.ClassPathResolver.getJavaDocUrl(ClassPathResolver.java:241)
at org.maven.ide.eclipse.embedder.ClassPathResolver.resolveClasspathEntries(ClassPathResolver.java:154)
at org.maven.ide.eclipse.builder.Maven2Builder.updateClasspath(Maven2Builder.java:95)
at org.maven.ide.eclipse.builder.Maven2Builder.build(Maven2Builder.java:86)
at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:603)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:167)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:201)
at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:230)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:233)
at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:252)
at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:285)
at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:208)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

---

**Affects:** 3.0

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

How are you getting an m1 POM in the mix for an m2 project. You need to give me more information and the repo where this POM came from.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

We don't parse m1 POMs.
