### ISSUE TITLE
[MNG-3623] [regression] it0081 and it0065 fail since the xbean migration

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5036]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-3623](https://issues.apache.org/jira/browse/MNG-3623?redirect=false)** and commented

both contain errors similar to:

Caused by: org.apache.xbean.recipe.ConstructionException: Type class could not be found: org.apache.maven.plugin.coreit.TestBasedirMojo
at org.apache.xbean.recipe.ObjectRecipe.getType(ObjectRecipe.java:351)
at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:262)
at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:122)
... 28 more

---

**Affects:** 3.0-alpha-2

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

According to this:

http://ci.sonatype.org/view/Maven%202.1x/job/Maven-2.1.x-ITs/155/console

It's this:

Results :

Tests in error:
testitMNG3473(org.apache.maven.integrationtests.MavenITmng3473PluginReportCrash)
testit0112(org.apache.maven.integrationtests.MavenIT0112ExtensionsThatDragDependencies)

Was this on a Windows machine?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

actually, they pass for me on windows. I've found these two tests to be intermittent - they both fail on my mac, but then in debug mode they succeed. On continuum (linux), they fairly regularly fail, but there is an occasional success.

My current theory is that it's related to version of the test mojos that are installed.

They are probably bad tests, so this can be pushed to 2.1-alpha-2.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

it0065 only refers to mojos it creates
it0081 doesn't use any test mojos and only uses fixed versions

What test mojos are you referring to?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Sorry, since the names of the mojos are the same as the shared ones I thought that was what they were using. it0081 uses one it builds too, giving this error:

Root cause: Type class could not be found: org.apache.maven.plugin.coreit.CoreItMojo
org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component role: 'null', implementation: 'org.apache.maven.plugin.coreit.CoreItMojo', role hint: 'default'
at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:138)
at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:92)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:135)
at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:45)
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:147)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:492)

So they have in common that they use plugins they build. I know the plugin manager used to have some reloading logic to accommodate that - though if that weren't working you'd expect more consistent failures on these. Beyond that, I'm not sure of the cause yet.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

No errors in Hudson, or on my machine. So not sure what's up with your machine. I consider these working.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Reference for the last Hudson build:

https://ci.sonatype.org/view/Maven%202.1x/job/Maven-2.1.x-ITs/159/console
