### ISSUE TITLE
[MNG-3586] [regression] jaxws mojo wsgen failure with maven 3.0 due to system-scope dependencies being excluded

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5067]
**[Gomez Henri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hgomez)** opened **[MNG-3586](https://issues.apache.org/jira/browse/MNG-3586?redirect=false)** and commented

I can build jar projects using the jaxws wsgen mojo (1.9) under maven
2.0.x but it failed under m2eclipse (0.9.3) when using maven 2.1
embedded (it works if I switch m2eclipse to use the maven 2.0.9 on my
system).

I tried with various JVM (Sun and IBM 5 and 6) but still got the
problem with maven 2.1 embedded (maven 2.1-620417 and 2.1-655675):

error is :

From file: C:\workspace\xxx-er-go\pom.xml
Reason: Failed to execute wsgen

java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadRealmClass(ClassRealm.java:174)
at org.codehaus.plexus.classworlds.strategy.DefaultStrategy.loadClass(DefaultStrategy.java:67)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:201)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
at com.sun.tools.ws.WsGen.doMain(WsGen.java:69)
at org.codehaus.mojo.jaxws.AbstractWsGenMojo.execute(AbstractWsGenMojo.java:91)
at org.codehaus.mojo.jaxws.MainWsGenMojo.execute(MainWsGenMojo.java:14)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:577)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:265)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:191)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:304)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody2(MavenEmbedder.java:903)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody3$advice(MavenEmbedder.java:304)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:52)

Any idea or fixes ?

my pom.xml wsgen is standard :

      <build>
    
              <plugins>
    
                      <plugin>
                              <artifactId>maven-compiler-plugin</artifactId>
                              <configuration>
                                      <source>1.5</source>
                                      <target>1.5</target>
                              </configuration>
    
                              <executions>
                                      <execution>
                                              <id>compile</id>
                                              <goals>
                                                      <goal>compile</goal>
                                              </goals>
                                              <phase>initialize</phase>
                                      </execution>
                              </executions>
                      </plugin>
    
                      
                      
\<plugin>
\<groupId>org.codehaus.mojo\</groupId>
\<artifactId>jaxws-maven-plugin\</artifactId>
\<executions>
\<execution>
\<id>go-wsgen\</id>
\<goals>
\<goal>wsgen\</goal>
\</goals>
\<phase>generate-sources\</phase>
\<configuration>

\<resourceDestDir>${project.build.directory}/classes/com/mycorp/service/resources/wsdl\</resourceDestDir>

\<sei>com.mycorp.service.MyService\</sei>
\<genWsdl>true\</genWsdl>
\<keep>false\</keep>
\</configuration>
\</execution>
\</executions>
\</plugin>

              </plugins>
    
      </build>

I attached a simple project so you could try it.

From others reports, it seems the tools.jar is missing in embedded mode.

---

**Affects:** 3.0-alpha-1

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712533/pom.xml) (_1.83 kB_)
- [sample-wsgen.zip](https://issues.apache.org/jira/secure/attachment/12712717/sample-wsgen.zip) (_1.88 kB_)
- [sample-wsgen-20081229.zip](https://issues.apache.org/jira/secure/attachment/12712329/sample-wsgen-20081229.zip) (_2.70 kB_)
- [sample-wsgen-fixed.zip](https://issues.apache.org/jira/secure/attachment/12712534/sample-wsgen-fixed.zip) (_1.96 kB_)

**Issue Links:**
- [MNG-3712](https://issues.apache.org/jira/browse/MNG-3712) [regression] java.lang.NoClassDefFoundError in maven-jaxb-schemagen-plugin
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I can't reproduce this because the sources compiled in the initialize phase don't compile

**Comment by jira-importer** [comment]
**[Gomez Henri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hgomez)** commented

Something change in this mojo recently, I'll track it down and fix the pom

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

i've had to change the pom.xml config according to the help from https://jax-ws-commons.dev.java.net/jaxws-maven-plugin/usage.html

then it built correctly for me using the latest embedded maven (3/7/2008) and latest mevenide/netbeans sourcebase. Not sure if it works in released mevenide as well.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

same here from the command line (as long as I'm using Java 6.0, both versions work. I suspect the sample hasn't even been tested on Java 5 since it doesn't include the JARs that provide javax.jws...)

**Comment by jira-importer** [comment]
**[Gomez Henri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hgomez)** commented

Right I missing deps (dam'nt Java 6)

    	<dependency>
    		<groupId>com.sun.xml.ws</groupId>
    		<artifactId>jaxws-rt</artifactId>
    		<version>2.1.4</version>
    	</dependency>
    
    	<dependency>
    		<groupId>javax.annotation</groupId>
    		<artifactId>jsr250-api</artifactId>
    		<version>1.0</version>
    	</dependency>
    
    	<dependency>
    		<groupId>javax.jws</groupId>
    		<artifactId>jsr181-api</artifactId>
    		<version>1.0-MR1</version>
    	</dependency>

Attached the corrected sample

**Comment by jira-importer** [comment]
**[Gomez Henri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hgomez)** commented

This one is with corrected POM

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this now gives:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/jws/WebService
at com.sun.tools.ws.wscompile.WsgenOptions.validateEndpointClass(WsgenOptions.java:198)

Under both 2.1-SNAPSHOT and 2.0.9.

But it works under Java 1.5.

**Comment by jira-importer** [comment]
**[Gomez Henri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hgomez)** commented

With IBM JDK 1.5 and maven 2.0.9 :

[DEBUG] jaxws:wsgen args: [-d, C:\Documents and Settings\gomezhe\Bureau\sample-wsgen\target\classes, -cp, C:\Documents and Settings\gomezhe\Bureau\sample-wsgen\target\classes;c:\maven-repository\com\sun\xml\ws\jaxws-rt\2.1.4\jaxws-rt-2.1.4.jar;c:\maven-repository\javax\xml\ws\jaxws-api\2.1\jaxws-api-2.1.jar;c:\maven-repository\javax\xml\bind\jaxb-api\2.1\jaxb-api-2.1.jar;c:\maven-repository\javax\xml\stream\stax-api\1.0\stax-api-1.0.jar;c:\maven-repository\javax\activation\activation\1.1\activation-1.1.jar;c:\maven-repository\javax\xml\soap\saaj-api\1.3\saaj-api-1.3.jar;c:\maven-repository\javax\annotation\jsr250-api\1.0\jsr250-api-1.0.jar;c:\maven-repository\javax\jws\jsr181-api\1.0-MR1\jsr181-api-1.0-MR1.jar;c:\maven-repository\com\sun\xml\bind\jaxb-impl\2.1.7\jaxb-impl-2.1.7.jar;c:\maven-repository\com\sun\xml\messaging\saaj\saaj-impl\1.3.1\saaj-impl-1.3.1.jar;c:\maven-repository\com\sun\xml\stream\buffer\streambuffer\0.7\streambuffer-0.7.jar;c:\maven-repository\org\jvnet\staxex\stax-ex\1.2\stax-ex-1.2.jar;c:\maven-repository\junit\junit\3.8\junit-3.8.jar;c:\maven-repository\com\sun\xml\stream\sjsxp\1.0.1\sjsxp-1.0.1.jar;c:\maven-repository\com\sun\org\apache\xml\internal\resolver\20050927\resolver-20050927.jar;c:\maven-repository\org\jvnet\mimepull\1.2\mimepull-1.2.jar;c:\maven-repository\com\sun\xml\ws\jaxws-tools\2.1.3\jaxws-tools-2.1.3.jar;c:\maven-repository\com\sun\xml\ws\jaxws-rt\2.1.3\jaxws-rt-2.1.3.jar;c:\maven-repository\javax\xml\ws\jaxws-api\2.1\jaxws-api-2.1.jar;c:\maven-repository\javax\xml\bind\jaxb-api\2.1\jaxb-api-2.1.jar;c:\maven-repository\javax\xml\stream\stax-api\1.0\stax-api-1.0.jar;c:\maven-repository\javax\activation\activation\1.1\activation-1.1.jar;c:\maven-repository\javax\xml\soap\saaj-api\1.3\saaj-api-1.3.jar;c:\maven-repository\javax\annotation\jsr250-api\1.0\jsr250-api-1.0.jar;c:\maven-repository\javax\jws\jsr181-api\1.0-MR1\jsr181-api-1.0-MR1.jar;c:\maven-repository\com\sun\xml\bind\jaxb-impl\2.1.6\jaxb-impl-2.1.6.jar;c:\maven-repository\com\sun\xml\messaging\saaj\saaj-impl\1.3\saaj-impl-1.3.jar;c:\maven-repository\com\sun\xml\stream\buffer\streambuffer\0.7\streambuffer-0.7.jar;c:\maven-repository\org\jvnet\staxex\stax-ex\1.2\stax-ex-1.2.jar;c:\maven-repository\com\sun\xml\stream\sjsxp\1.0\sjsxp-1.0.jar;c:\maven-repository\com\sun\org\apache\xml\internal\resolver\20050927\resolver-20050927.jar;c:\maven-repository\org\jvnet\mimepull\1.1\mimepull-1.1.jar;c:\maven-repository\com\sun\xml\bind\jaxb-xjc\2.1.6\jaxb-xjc-2.1.6.jar;c:\maven-repository\org\codehaus\plexus\plexus-utils\1.1\plexus-utils-1.1.jar;C:\maven\lib\maven-2.0.9-uber.jar;C:\maven\lib\maven-2.0.9-uber.jar, -wsdl, -r, C:\Documents and Settings\gomezhe\Bureau\sample-wsgen\target\classes\com\mycorp\resources\wsdl, samplewsgen.SampleService]
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to execute wsgen

Embedded error: com.sun.tools.apt.Main
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute wsgen
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:583)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:615)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute wsgen
at org.codehaus.mojo.jaxws.AbstractWsGenMojo.execute(AbstractWsGenMojo.java:102)
at org.codehaus.mojo.jaxws.MainWsGenMojo.execute(MainWsGenMojo.java:14)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
... 16 more
Caused by: java.lang.NoClassDefFoundError: com.sun.tools.apt.Main
at com.sun.tools.ws.wscompile.WsgenTool.buildModel(WsgenTool.java:194)
at com.sun.tools.ws.wscompile.WsgenTool.run(WsgenTool.java:119)
at com.sun.tools.ws.WsGen.doMain(WsGen.java:69)
at org.codehaus.mojo.jaxws.AbstractWsGenMojo.execute(AbstractWsGenMojo.java:97)
... 19 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5 seconds
[INFO] Finished at: Fri Jul 04 11:32:07 CEST 2008
[INFO] Final Memory: 7M/22M
[INFO] ------------------------------------------------------------------------

It works for me with maven 2.0.9 (Sun 1.5 and 1.6).

Could you provided the log ?

**Comment by jira-importer** [comment]
**[Gomez Henri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hgomez)** commented

Hi to all,

I take a look at the jaxws-maven-plugin and found this in its pom :

\<profiles>
\<profile>
\
\<id>default-tools.jar\</id>
\<activation>
\<property>
\<name>java.vendor\</name>
\<value>Sun Microsystems Inc.\</value>
\</property>
\</activation>
\<dependencies>
\<dependency>
\<groupId>com.sun\</groupId>
\<artifactId>tools\</artifactId>
\<version>1.5.0\</version>
\<scope>system\</scope>
\<systemPath>${java.home}/../lib/tools.jar\</systemPath>
\</dependency>
\</dependencies>
\</profile>
\</profiles>

System scope and path are deprecated in maven 2.1 ?

Regards

**Comment by jira-importer** [comment]
**[Pat Podenski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stug23)** commented

Although this bug is closed, there is another factor in the failure of the jaxws plugins. If you resolve javax.xml.ws:jaxws-api:2.1 via Maven Central Repository, the pom.xml there only contains one dependency, whereas the same pom.xml at maven-repository.dev.java.net has four dependencies. Both have the same coordinates, so if you resolve your dependencies from Maven Central first, you will never pickup the four dependencies.

This difference causes the jaxws plugins to fail -- I just changed my Artifactory proxy configuration such that the dev.java.net repo is checked first which avoids the older entry from Maven Central.

See here for the older javax.xml.ws:jaxws-api:2.1 entry in Maven Central Repository:

<http://repo1.maven.org/maven2/javax/xml/ws/jaxws-api/2.1/jaxws-api-2.1.pom>

Arguably Sun should have changed the version number when they revised the pom, however since they didn't do so, anyone attempting to correctly resolve these dependencies, even with the latest jaxws-rt version 2.1.4 release will run into problems if the artifact is resolved from Maven Central Repository.

**Comment by jira-importer** [comment]
**[Gomez Henri](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hgomez)** commented

This project failed with :

While building project:
Group-Id: mycorp.com
Artifact-Id: samplewsgen
Version: 1.0.0-SNAPSHOT
From file: C:\Documents and Settings\gomezhe\Bureau\sample-wsgen\pom.xml
Reason: Failed to execute wsgen

java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadRealmClass(ClassRealm.java:174)
at org.codehaus.plexus.classworlds.strategy.DefaultStrategy.loadClass(DefaultStrategy.java:67)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:201)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
at com.sun.tools.ws.WsGen.doMain(WsGen.java:69)
at org.codehaus.mojo.jaxws.AbstractWsGenMojo.execute(AbstractWsGenMojo.java:97)
at org.codehaus.mojo.jaxws.MainWsGenMojo.execute(MainWsGenMojo.java:14)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:579)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:265)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:191)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:304)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody2(MavenEmbedder.java:904)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody3$advice(MavenEmbedder.java:304)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:52)

Error stacktrace:
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.codehaus.mojo:jaxws-maven-plugin:1.10:wsgen': Mojo execution failed.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:505)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:265)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:191)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:304)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody2(MavenEmbedder.java:904)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody3$advice(MavenEmbedder.java:304)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:52)
Caused by: org.apache.maven.plugin.PluginExecutionException: Mojo execution failed.
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:601)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:498)
... 12 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to execute wsgen
at org.codehaus.mojo.jaxws.AbstractWsGenMojo.execute(AbstractWsGenMojo.java:102)
at org.codehaus.mojo.jaxws.MainWsGenMojo.execute(MainWsGenMojo.java:14)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:579)
... 13 more
Caused by: java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadRealmClass(ClassRealm.java:174)
at org.codehaus.plexus.classworlds.strategy.DefaultStrategy.loadClass(DefaultStrategy.java:67)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:201)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
at com.sun.tools.ws.WsGen.doMain(WsGen.java:69)
at org.codehaus.mojo.jaxws.AbstractWsGenMojo.execute(AbstractWsGenMojo.java:97)
... 15 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILED
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Mon Dec 29 10:43:20 CET 2008
[INFO] Final Memory: 2M/9M
[INFO] ------------------------------------------------------------------------
