### ISSUE TITLE
[MNG-4371] NullPointerException in matchPattern

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5069]
**[Jean-Louis MONTEIRO](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ID134572)** opened **[MNG-4371](https://issues.apache.org/jira/browse/MNG-4371?redirect=false)** and commented

Hi,
For some unknown reasons, a NullPointerException breaks m2eclipse plugin.
Here is the stacktrace
java.lang.NullPointerException
at org.apache.maven.artifact.manager.DefaultWagonManager.matchPattern(DefaultWagonManager.java:857)
at org.apache.maven.artifact.manager.DefaultWagonManager.getMirror(DefaultWagonManager.java:829)
at org.apache.maven.artifact.manager.DefaultWagonManager.getMirrorRepository(DefaultWagonManager.java:668)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:418)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:335)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:193)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:83)
at org.maven.ide.eclipse.internal.project.EclipseArtifactResolver.resolve(EclipseArtifactResolver.java:34)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:552)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:233)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:131)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:518)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:138)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:88)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:526)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildProjectWithDependencies(DefaultMavenProjectBuilder.java:404)
at org.apache.maven.embedder.MavenEmbedder.readProjectWithDependencies_aroundBody0(MavenEmbedder.java:453)
at org.apache.maven.embedder.MavenEmbedder.readProjectWithDependencies_aroundBody1$advice(MavenEmbedder.java:304)
at org.apache.maven.embedder.MavenEmbedder.readProjectWithDependencies(MavenEmbedder.java:1)
at org.maven.ide.eclipse.internal.project.MavenProjectManagerImpl$MavenProjectReader.execute(MavenProjectManagerImpl.java:1053)
at org.maven.ide.eclipse.internal.project.MavenProjectManagerImpl.execute(MavenProjectManagerImpl.java:995)
at org.maven.ide.eclipse.internal.project.MavenProjectManagerImpl.refresh(MavenProjectManagerImpl.java:377)
at org.maven.ide.eclipse.internal.project.MavenProjectManagerImpl.refresh(MavenProjectManagerImpl.java:351)
at org.maven.ide.eclipse.internal.project.MavenProjectManagerRefreshJob.run(MavenProjectManagerRefreshJob.java:85)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

---
No further details from [MNG-4371](https://issues.apache.org/jira/browse/MNG-4371?redirect=false)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Please retry with the latest M2Eclipse release and refill the issue in their issue tracker if the problem persists. This report doesn't carry any version information which would be required to associate the stack trace with current code.
