### ISSUE TITLE
[MNG-3561] Improved error message when maven 2.1 is run with jdk 14

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5089]
**[Paul Gier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pgier)** opened **[MNG-3561](https://issues.apache.org/jira/browse/MNG-3561?redirect=false)** and commented

Currently if I try to run maven 2.1-alpha-1-SNAPSHOT with java 1.4 I get the standard jvm errors about wrong class type.  It would be nice to have some better error message saying that java 1.5 or higher is required.  This could probably go into the startup script.

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/codehaus/plexus/logging/AbstractLogEnabled (Unsupported major.minor version 49.0)
at java.lang.ClassLoader.defineClass0(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:539)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:123)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:251)
at java.net.URLClassLoader.access$100(URLClassLoader.java:55)
at java.net.URLClassLoader$1.run(URLClassLoader.java:194)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:187)

---

**Affects:** 3.0-alpha-1

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
