### ISSUE TITLE
[MNG-3929] Cannot find setter nor field in org.apache.maven.wagon.providers.ssh.jsch.ScpWagon for 'sshArgs'

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5135]
**[Martin West](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amartinwest)** opened **[MNG-3929](https://issues.apache.org/jira/browse/MNG-3929?redirect=false)** and commented

I followed this
http://maven.apache.org/plugins/maven-deploy-plugin/examples/deploy-ssh-external.html
help to specify an alternate ssh port but ...

cruise@thecla3:~/checkout/net.helixsys.jdocbook/trunk$ mvn -e deploy
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Reactor build order:
  [INFO]   Helixsys jdocbook artifacts
  [INFO]   Helixsys Manual Styles
  [INFO]   Helixsys JDocBook XSLT
  WAGON_VERSION: 1.0-beta-2
  [INFO] ------------------------------------------------------------------------
  [INFO] Building Helixsys jdocbook artifacts
  [INFO]    task-segment: [deploy]
  [INFO] ------------------------------------------------------------------------
  [INFO] [site:attach-descriptor]
  [INFO] [install:install]
  [INFO] Installing /mnt/sda5/builds/cruise/checkout/net.helixsys.jdocbook/trunk/pom.xml to /var/maven2/repo/net/helixsys/helixsys-jdocbook/1.0.0/helixsys-jdocbook-1.0.0.pom
  [INFO] [deploy:deploy]
  altDeploymentRepository = null
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Error deploying artifact: While configuring wagon for 'internal.repo': Unable to apply wagon configuration.

Cannot find setter nor field in org.apache.maven.wagon.providers.ssh.jsch.ScpWagon for 'sshArgs'
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error deploying artifact: While configuring wagon for 'internal.repo': Unable to apply wagon configuration.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:701)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:538)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:369)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error deploying artifact: While configuring wagon for 'internal.repo': Unable to apply wagon configuration.
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:174)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:676)
... 16 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error deploying artifact: While configuring wagon for 'internal.repo': Unable to apply wagon configuration.
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:94)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:152)
... 18 more
Caused by: org.apache.maven.artifact.manager.WagonConfigurationException: While configuring wagon for 'internal.repo': Unable to apply wagon configuration.
at org.apache.maven.artifact.manager.DefaultWagonManager.configureWagon(DefaultWagonManager.java:1063)
at org.apache.maven.artifact.manager.DefaultWagonManager.configureWagon(DefaultWagonManager.java:1033)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:199)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:172)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:80)
... 19 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter nor field in org.apache.maven.wagon.providers.ssh.jsch.ScpWagon for 'sshArgs'
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.\<init>(ComponentValueSetter.java:68)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:134)
at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:54)
at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:47)
at org.apache.maven.artifact.manager.DefaultWagonManager.configureWagon(DefaultWagonManager.java:1053)
... 23 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4 seconds
[INFO] Finished at: Fri Dec 19 16:58:14 GMT 2008
[INFO] Final Memory: 21M/227M

settings.xml : server

    <server>
      <id>internal.repo</id>
      <privateKey>${env.HOME}/.ssh/id_dsa</privateKey>
      <passphrase></passphrase>
      <filePermissions>664</filePermissions>
      <directoryPermissions>775</directoryPermissions>
      <configuration>
        <sshArgs>-p 78</sshArgs>
      </configuration>

\</server>

---

**Affects:** 2.0.9

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

sshArgs is for URLs starting with scpexe:// as described in the URL you provided.

It is irrelevant for scp:// which does not use an external scp executable.
