### ISSUE TITLE
[MNG-3924] FATAL ERROR if a variable contains &lt; or &gt;

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5140]
**[Stefan Franke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bebbo)** opened **[MNG-3924](https://issues.apache.org/jira/browse/MNG-3924?redirect=false)** and commented

Try to use a variable with content like:
\<properties>
\<xmlHeader>&lt;?xml version="1.0" ?&gt;\</xmlHeader>
\</properties>

Then maven fails with

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] 9262
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.ArrayIndexOutOfBoundsException: 9262
at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2447)
at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1245)
at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1093)
at hidden.org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:187)
at hidden.org.codehaus.plexus.util.xml.Xpp3DomBuilder.build(Xpp3DomBuilder.java:94)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePlugin(MavenXpp3Reader.java:2955)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseBuild(MavenXpp3Reader.java:753)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2224)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4422)
at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4433)
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolate(RegexBasedModelInterpolator.ja
va:105)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:1016)

    at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:878)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.ja

va:506)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:198)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:583)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:461)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Fri Dec 19 10:47:09 CET 2008
[INFO] Final Memory: 1M/2M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.9

**Issue Links:**
- [MNG-3662](https://issues.apache.org/jira/browse/MNG-3662) Model interpolation crashes if property resolves to value with ampersand

**Comment by jira-importer** [comment]
**[Stefan Franke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bebbo)** commented

HAHAHA JIRA is also buggy :) Let's try again:

    <properties>
        <xmlHeader>&amp;lt;?xml version="1.0" ?&amp;gt;</xmlHeader>
    </properties>

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

It's not the mere definition of the property but its interpolation in some other place that causes the error. This was fixed by refactoring of the model interpolation in both Maven 2.1.x (by John) and 3.x (by Shane).
