### ISSUE TITLE
[MNG-3529] mvn -Da=" " throws an excepltion

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5149]
**[Sean Bridges](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sgbridges)** opened **[MNG-3529](https://issues.apache.org/jira/browse/MNG-3529?redirect=false)** and commented

Doing,

mvn -Da=" "

throws,

---

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:146)
at java.lang.StringBuffer.setLength(StringBuffer.java:154)
at org.apache.maven.cli.MavenCli$CLIManager.cleanArgs(MavenCli.java:793)
at org.apache.maven.cli.MavenCli$CLIManager.parse(MavenCli.java:746)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 2.0.8

**Issue Links:**
- [MNG-3994](https://issues.apache.org/jira/browse/MNG-3994) StringIndexOutOfBoundsException with -Darguments=" "
 (_**"is duplicated by"**_)
- [MNG-4560](https://issues.apache.org/jira/browse/MNG-4560) Crash if command line parameter ends in space
 (_**"is duplicated by"**_)
- [MNG-4767](https://issues.apache.org/jira/browse/MNG-4767) Regression in parsing command-line arguments including variables

- [MNG-2190](https://issues.apache.org/jira/browse/MNG-2190) -Dkey=value parameters cannot include spaces in the value

2 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Dominic Mitchell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=happygiraffe)** commented

I've just seen this as well:

```
% mvn release:prepare -DscmCommentPrefix='FOO-139 '
---------------------------------------------------
constituent[0]: file:/usr/local/apache-maven-2.0.9/lib/maven-2.0.9-uber.jar
---------------------------------------------------
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:143)
        at java.lang.StringBuffer.setLength(StringBuffer.java:153)
        at org.apache.maven.cli.MavenCli$CLIManager.cleanArgs(MavenCli.java:824)
        at org.apache.maven.cli.MavenCli$CLIManager.parse(MavenCli.java:777)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

It's quite useful to have a trailing space in the scmCommentPrefix, as otherwise it gets joined up with the automatically generated commit message and looks rather ugly.

**Comment by jira-importer** [comment]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ID134349)** commented

The duplicated issue (MNG-3994) has 2.0.10 has an affected version, but I can't reproduce it using 2.0.10. I tried these commands:

```
mvn -Da=" "
mvn -Da=""
mvn validate -Da=" "
```

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I can definitely reproduce it here (Mac OS X)

**Comment by jira-importer** [comment]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ID134349)** commented

I wonder if it is an OS-specific issue? I am on Windows. The report indicates a unix problem and OS X is, unless I am mistaken, a port of unix.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

The problem originates from the Unix shell script we use to launch Maven, the relevant part:

```
QUOTED_ARGS=""
while [ "$1" != "" ] ; do
  QUOTED_ARGS="$QUOTED_ARGS \"$1\""
  shift
done

[...]

exec [...] $QUOTED_ARGS
```

While I can't explain it, this screws up the parameter passing and makes `-D=" "` parse as the two parameters `"-D=` and `"`

There seem to be two possible solutions to this:
a) Nuke the QUOTED_ARGS variable and use the special variable `$@` instead, i.e.

```
exec [...] "$@"
```

b) Mimic Ant's launch script and do

```
exec_cmd="exec [...] $QUOTED_ARGS"
eval $exec_cmd
```

Personally, I don't know enough about Unix shell scripting to judge which of these is preferrable or might have unwanted side effects so Unix gurus please speak up.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

It appears approach b) is more helpful as it also fixes a related issue with the MAVEN_OPTS variable. Right now

```
export "MAVEN_OPTS=-Dthe.prop=\"x y\""
```

makes mvn also fail (`Exception in thread "main" java.lang.NoClassDefFoundError: y"`).

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

Caused a regression; see: MNG-4767
