### ISSUE TITLE
[MNG-3870] Cannot use Wagon ftp on Mac OSX

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5189]
**[Patrick Moore](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patmoore@ieee.org)** opened **[MNG-3870](https://issues.apache.org/jira/browse/MNG-3870?redirect=false)** and commented

Seems to be MacOSX-specific. I have used Wagon ftp to deploy files to a ftp server on windows. Using the same configuration that successfully "mvn deploy"'s on windows fails on Mac OSX.

Please note that Wagon-ftp-1.0-beta-4 jars are downloaded and in the MacOSX repository. So this seems different than: MNG-2227 (but maybe not?)

mvn -Dmaven.test.skip=true -e deploy
Using Java version: 1.6
+ Error stacktraces are turned on.
  [INFO] Scanning for projects...
  [INFO] Reactor build order:
  [INFO]   Amplafi Hivemind
  [INFO]   Amplafi Test
  [INFO]   Tapestry Javaforge Acegi
  [INFO]   Amplafi Json
  [INFO]   Amplafi Sworddance
  [INFO]   Amplafi Flow - Core
  [INFO]   Flow - Web
  [INFO]   Amplafi - James Mailet
  [INFO]   Amplafi Wireservice - Foundation
  [INFO]   Amplafi Wireservice - IO Management
  [INFO]   Amplafi Wireservice - Core
  [INFO]   Amplafi Wireservice - Web
  [INFO]   Amplafi Project
  [INFO] ------------------------------------------------------------------------
  [INFO] Building Amplafi Hivemind
  [INFO]    task-segment: [deploy]
  [INFO] ------------------------------------------------------------------------
  [INFO] [resources:resources]
  [INFO] Using default encoding to copy filtered resources.
  [INFO] [compiler:compile]
  [INFO] Nothing to compile - all classes are up to date
  [INFO] [resources:testResources]
  [INFO] Using default encoding to copy filtered resources.
  [INFO] [compiler:testCompile]
  [INFO] Not compiling test sources
  [INFO] [surefire:test]
  [INFO] Tests are skipped.
  [INFO] [jar:jar]
  [INFO] Preparing source:jar
  [WARNING] Removing: jar from forked lifecycle, to prevent recursive invocation.
  [INFO] No goals needed for project - skipping
  [INFO] [source:jar {execution: attach-sources}]
  [INFO] Building jar: /Users/patmoore/projects/amplafi/amplafi-hivemind/target/amplafi-hivemind-0.8-SNAPSHOT-sources.jar
  [INFO] Preparing source:test-jar
  [WARNING] Removing: jar from forked lifecycle, to prevent recursive invocation.
  [WARNING] Removing: test-jar from forked lifecycle, to prevent recursive invocation.
  [INFO] No goals needed for project - skipping
  [INFO] [source:test-jar {execution: attach-sources}]
  [INFO] Building jar: /Users/patmoore/projects/amplafi/amplafi-hivemind/target/amplafi-hivemind-0.8-SNAPSHOT-test-sources.jar
  [INFO] [javadoc:jar {execution: attach-javadocs}]
  [INFO] Building jar: /Users/patmoore/projects/amplafi/amplafi-hivemind/target/amplafi-hivemind-0.8-SNAPSHOT-javadoc.jar
  [INFO] [install:install]
  [INFO] Installing /Users/patmoore/projects/amplafi/amplafi-hivemind/target/amplafi-hivemind-0.8-SNAPSHOT.jar to /Users/patmoore/.m2/repository/com/amplafi/amplafi-hivemind/0.8-SNAPSHOT/amplafi-hivemind-0.8-SNAPSHOT.jar
  [INFO] Installing /Users/patmoore/projects/amplafi/amplafi-hivemind/target/amplafi-hivemind-0.8-SNAPSHOT-sources.jar to /Users/patmoore/.m2/repository/com/amplafi/amplafi-hivemind/0.8-SNAPSHOT/amplafi-hivemind-0.8-SNAPSHOT-sources.jar
  [INFO] Installing /Users/patmoore/projects/amplafi/amplafi-hivemind/target/amplafi-hivemind-0.8-SNAPSHOT-test-sources.jar to /Users/patmoore/.m2/repository/com/amplafi/amplafi-hivemind/0.8-SNAPSHOT/amplafi-hivemind-0.8-SNAPSHOT-test-sources.jar
  [INFO] Installing /Users/patmoore/projects/amplafi/amplafi-hivemind/target/amplafi-hivemind-0.8-SNAPSHOT-javadoc.jar to /Users/patmoore/.m2/repository/com/amplafi/amplafi-hivemind/0.8-SNAPSHOT/amplafi-hivemind-0.8-SNAPSHOT-javadoc.jar
  [INFO] [deploy:deploy]
  altDeploymentRepository = amplafi.public::default::ftp://amplafi.com/httpdocs/repository
  [INFO] Using alternate deployment repository amplafi.public::default::ftp://amplafi.com/httpdocs/repository
  [INFO] Retrieving previous build number from amplafi.public
  [INFO] ------------------------------------------------------------------------
  [ERROR] BUILD ERROR
  [INFO] ------------------------------------------------------------------------
  [INFO] Error retrieving previous build number for artifact 'com.amplafi:amplafi-hivemind:jar': repository metadata for: 'snapshot com.amplafi:amplafi-hivemind:0.8-SNAPSHOT' could not be retrieved from repository: amplafi.public due to an error: Unsupported Protocol: 'ftp': Cannot find wagon which supports the requested protocol: ftp

Component descriptor cannot be found in the component repository: org.apache.maven.wagon.Wagonftp.
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error retrieving previous build number for artifact 'com.amplafi:amplafi-hivemind:jar': repository metadata for: 'snapshot com.amplafi:amplafi-hivemind:0.8-SNAPSHOT' could not be retrieved from repository: amplafi.public due to an error: Unsupported Protocol: 'ftp': Cannot find wagon which supports the requested protocol: ftp
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:701)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:538)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:517)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:369)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error retrieving previous build number for artifact 'com.amplafi:amplafi-hivemind:jar': repository metadata for: 'snapshot com.amplafi:amplafi-hivemind:0.8-SNAPSHOT' could not be retrieved from repository: amplafi.public due to an error: Unsupported Protocol: 'ftp': Cannot find wagon which supports the requested protocol: ftp
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:174)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:458)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:676)
... 16 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error retrieving previous build number for artifact 'com.amplafi:amplafi-hivemind:jar': repository metadata for: 'snapshot com.amplafi:amplafi-hivemind:0.8-SNAPSHOT' could not be retrieved from repository: amplafi.public due to an error: Unsupported Protocol: 'ftp': Cannot find wagon which supports the requested protocol: ftp
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:106)
at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForDeployment(DefaultArtifactTransformationManager.java:78)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:71)
at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:162)
... 18 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataResolutionException: repository metadata for: 'snapshot com.amplafi:amplafi-hivemind:0.8-SNAPSHOT' could not be retrieved from repository: amplafi.public due to an error: Unsupported Protocol: 'ftp': Cannot find wagon which supports the requested protocol: ftp
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:352)
at org.apache.maven.artifact.transform.SnapshotTransformation.resolveLatestSnapshotBuildNumber(SnapshotTransformation.java:161)
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:100)
... 21 more
Caused by: org.apache.maven.wagon.TransferFailedException: Unsupported Protocol: 'ftp': Cannot find wagon which supports the requested protocol: ftp
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:423)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadataFromDeploymentRepository(DefaultWagonManager.java:398)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.getArtifactMetadataFromDeploymentRepository(DefaultRepositoryMetadataManager.java:380)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:348)
... 23 more
Caused by: org.apache.maven.wagon.UnsupportedProtocolException: Cannot find wagon which supports the requested protocol: ftp
at org.apache.maven.artifact.manager.DefaultWagonManager.getWagon(DefaultWagonManager.java:147)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:417)
... 26 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository: org.apache.maven.wagon.Wagonftp.
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.artifact.manager.DefaultWagonManager.getWagon(DefaultWagonManager.java:143)
... 27 more

---

**Affects:** 2.1.0-M1

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

from what I can tell, if including the wagon and dependencies in M2_HOME/lib fixed it, you may have just forgotten to add the \<extension> element to support wagon-ftp. Is that right?

**Comment by jira-importer** [comment]
**[Patrick Moore](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patmoore@ieee.org)** commented

No.

I have this in the pom.xml since the beginning:

    <extensions>
        <extension>
            <groupId>org.apache.maven.wagon</groupId>
            <artifactId>wagon-ssh-external</artifactId>
            <version>${wagon-build}</version>
        </extension>
        <extension>
            <groupId>org.apache.maven.wagon</groupId>
            <artifactId>wagon-ftp</artifactId>
            <version>${wagon-build}</version>
        </extension>
    </extensions>

**Comment by jira-importer** [comment]
**[Patrick Moore](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patmoore@ieee.org)** commented

Sorry forgot to tell you this:

\<wagon-build>1.0-beta-2\</wagon-build>

so no ... we never went beyonf beta-2 (seemed there was reported problems ) after that build.

I have not tried on 2.0.10 I see its freshly released. Will download and try.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

ok, please reopen if either:
a) beta-2 doesn't work on 2.0.10, or
b) any version doesn't work on 2.1.0-SNAPSHOT (we'll be posting RCs soon).

You originally filed against 2.1.0-M1 which may have had some issues.

**Comment by jira-importer** [comment]
**[Patrick Moore](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=patmoore@ieee.org)** commented

Brett,

Retesting. We use "deploy" to push via ssh to the production server. Works fine on windows. But now that I am on the Mac I get http://jira.codehaus.org/browse/MDEPLOY-62

(Obviously this is **not** an ftp issue.)

Doing more ftp testing -- but ftp looks o.k. now.
