### ISSUE TITLE
[MNG-3857] Malformed respositories element could use a better error message

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5198]
**[Justin Edelson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=justinedelson)** opened **[MNG-3857](https://issues.apache.org/jira/browse/MNG-3857?redirect=false)** and commented

If you create a pom that has a repository element like this:
\<repositories>
\<repository>
\<id>just.an.id\</id>
\</repository>
\</repositories>

The error message isn't at all helpful:
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.wagon.PathUtils.protocol(PathUtils.java:206)
at org.apache.maven.wagon.repository.Repository.setUrl(Repository.java:121)
at org.apache.maven.wagon.repository.Repository.\<init>(Repository.java:74)
at org.apache.maven.artifact.repository.DefaultArtifactRepository.\<init>(DefaultArtifactRepository.java:87)
at org.apache.maven.artifact.repository.DefaultArtifactRepositoryFactory.createArtifactRepository(DefaultArtifactRepositoryFactory.java:85)
at org.apache.maven.project.ProjectUtils.buildArtifactRepository(ProjectUtils.java:105)
at org.apache.maven.project.ProjectUtils.buildArtifactRepositories(ProjectUtils.java:56)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildArtifactRepositories(DefaultMavenProjectBuilder.java:944)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1144)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:821)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:506)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:198)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:583)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:461)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Would be nice to have this be a more obvious message.

---

**Affects:** 2.0.9

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712806/pom.xml) (_484 bytes_)

**Issue Links:**
- [MNG-2739](https://issues.apache.org/jira/browse/MNG-2739) Repository entries are not validated and NPE will occur
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Jonathan K. Schneider](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jschneider)** commented

The problem is the missing "\<url>" tag...
Better error message will be great.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Johannes, as you can see form linked issue, this is already in Maven 2.0.10+
