### ISSUE TITLE
[MNG-3821] [regression] Project builder blows up when POM declares two plugins which use the same id for their executions/reportsets

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5225]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-3821](https://issues.apache.org/jira/browse/MNG-3821?redirect=false)** and commented

Running the core IT 2695 with trunk delivered:

```
java.io.IOException: org.codehaus.plexus.util.xml.pull.XmlPullParserException: end tag name </plugin> must match start t
ag name <executions> from line 43 (position: START_TAG seen ...<executions></plugin>... @43:22) :

[...]
        at org.apache.maven.project.builder.PomClassicTransformer.transformToDomainModel(PomClassicTransformer.java:237)
        at org.apache.maven.shared.model.ModelTransformerContext.transform(ModelTransformerContext.java:286)
        at org.apache.maven.project.builder.impl.DefaultProjectBuilder.buildFromLocalPath(DefaultProjectBuilder.java:176)
        at org.apache.maven.project.DefaultMavenProjectBuilder.readModelFromLocalPath(DefaultMavenProjectBuilder.java:544)
        at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:132)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:286)
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:256)
        at org.apache.maven.DefaultMaven.createReactorManager(DefaultMaven.java:93)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:147)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:854)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
[ERROR]
Failed to build MavenProject instance for: M:\maven\core-it\core-it-suite\src\test\resources\mng-2695\pom.xml
```

---

**Affects:** 3.0-alpha-1

**Issue Links:**
- [MNG-3838](https://issues.apache.org/jira/browse/MNG-3838) [regression] Some POMs fail to parse if the are subject to ModelContainer joining

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r711743](http://svn.eu.apache.org/viewvc?view=rev&revision=711743).

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

We can't feed containers of containers into the ModelTransformerContext. Merging of subcontainers needs to be handled in the ModelTransformer implementation.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Not sure why this was marked fixed but the corresponding IT MNG-3821 is still failing, both with the staged 3.0-alpha-1 and the SVN head.
