### ISSUE TITLE
[MNG-3414] Plexus bundled in Maven 2.1-SNAPSHOT built on 19 Feb 2008 introduced a regression in path handling

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5246]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** opened **[MNG-3414](https://issues.apache.org/jira/browse/MNG-3414?redirect=false)** and commented

Here's the error I get. This is working fine in an old 2.1 SNAPSHOT:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building XWiki Products - Watch - GWT
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory /Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/target
[INFO] [dependency:unpack]
[INFO] Configured Artifact: com.google.gwt:gwt-mac:1.3.3:zip
[INFO] Unpacking /Users/vmassol/.m2/repository/com/google/gwt/gwt-mac/1.3.3/gwt-mac-1.3.3.zipto
 /tmp/xwiki/gwt
with Includes null and excludes:null
[INFO] [remote-resources:process]
[INFO] [gwt:compile]
Using classpath: /Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/target/classes:/Users/vmassol/.m2/repository/com/google/gwt/gwt-servlet/1.3.3/gwt-servlet-1.3.3.jar:/Users/vmassol/.m2/repository/com/google/gwt/gwt-user/1.3.3/gwt-user-1.3.3.jar:/Users/vmassol/.m2/repository/gwt-widgets/gwt-widgets/0.1.3/gwt-widgets-0.1.3.jar:/Users/vmassol/.m2/repository/gwttk/gwttk/0.2.2/gwttk-0.2.2.jar:/Users/vmassol/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar:/Users/vmassol/.m2/repository/com/xpn/xwiki/platform/xwiki-web-gwt/1.3-SNAPSHOT/xwiki-web-gwt-1.3-SNAPSHOT.jar:/Users/vmassol/.m2/repository/com/xpn/xwiki/platform/xwiki-web-gwt/1.3-SNAPSHOT/xwiki-web-gwt-1.3-SNAPSHOT-sources.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-dev-linux.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-dev-mac.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-dev-windows.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-user.jar:/Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/src/main/resources:/Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/target/maven-shared-archive-resources:/Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/src/main/java
[INFO] Running GWTCompile with command: '"/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/bin"/java' -Xmx1024m -classpath /Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/target/classes:/Users/vmassol/.m2/repository/com/google/gwt/gwt-servlet/1.3.3/gwt-servlet-1.3.3.jar:/Users/vmassol/.m2/repository/com/google/gwt/gwt-user/1.3.3/gwt-user-1.3.3.jar:/Users/vmassol/.m2/repository/gwt-widgets/gwt-widgets/0.1.3/gwt-widgets-0.1.3.jar:/Users/vmassol/.m2/repository/gwttk/gwttk/0.2.2/gwttk-0.2.2.jar:/Users/vmassol/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar:/Users/vmassol/.m2/repository/com/xpn/xwiki/platform/xwiki-web-gwt/1.3-SNAPSHOT/xwiki-web-gwt-1.3-SNAPSHOT.jar:/Users/vmassol/.m2/repository/com/xpn/xwiki/platform/xwiki-web-gwt/1.3-SNAPSHOT/xwiki-web-gwt-1.3-SNAPSHOT-sources.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-dev-linux.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-dev-mac.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-dev-windows.jar:/tmp/xwiki/gwt/gwt-mac-1.3.3/gwt-user.jar:/Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/src/main/resources:/Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/target/maven-shared-archive-resources:/Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/src/main/java com.google.gwt.dev.GWTCompiler -logLevel WARN -style OBF -out /Users/vmassol/dev/xwiki/trunks/xwiki-product-watch/gwt/target/xwiki-watch-gwt-1.0-SNAPSHOT com.xpn.xwiki.watch.Watch
org.codehaus.plexus.util.cli.CommandLineException: Error while executing process.
        at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:697)
        at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:74)
        at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:60)
        at com.totsp.mavenplugin.gwt.CompileMojo.execute(CompileMojo.java:78)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:549)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:544)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
        at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
        at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:304)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
        at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody4(MavenEmbedder.java:880)
        at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody5$advice(MavenEmbedder.java:304)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: java.io.IOException: "/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Home/bin"/java: not found
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:52)
        at java.lang.ProcessImpl.start(ProcessImpl.java:91)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:451)
        at java.lang.Runtime.exec(Runtime.java:591)
        at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:692)
        ... 23 more
[INFO] [site:attach-descriptor]
```

---

**Affects:** 3.0-alpha-1

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

this MAY be related to the fix for PLXUTILS-64, though I can't get a clear enough look at it yet to know for sure.

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

John Casey said:

> I've been looking into that problem with the gwt plugin a bit more, and I found that the code is actually trying to compensate for an un-quoted java path itself.
> Not sure why it'd do that, but when you add to that the fact that plexus-utils now tries to quote the executable path and working directory, you get the mess we're seeing.
> In *nix environments, the single-quote means a literal string. Therefore, if something has single-quotes around it and contains the " character, it is presumed that that character is actually present in that path.
> 
> I'm not sure why he chose to wrap only the ${java.home}/bin directory in double quotes, but it's not compatible with plexus-utils from recent releases (I'd say > 1.4.5 or so, though I haven't looked for an exact revision).
> 
> I lost the link to the issue you filed with this problem, otherwise I'd report this little bit of progress there.

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

So I guess the solution if for the author of the GWT plugin to fix the problem...

In the meantime I've found a workaround by specifying explicitely the dependency on plexus-utils 1.4.2 (it doesn't work with 1.4.3 and above):

```
<plugin>
  <groupId>com.totsp.gwt</groupId>
  <artifactId>maven-googlewebtoolkit2-plugin</artifactId>
  <version>1.5.2</version>
  <configuration>
    <logLevel>WARN</logLevel> <!-- ERROR, WARN, INFO, TRACE, DEBUG, SPAM, ALL -->
    <style>OBF</style> <!-- OBF[USCATED], PRETTY, DETAILED -->
    <runTarget>com.xpn.xwiki.watch/Watch.html</runTarget>
    <gwtHome>${java.io.tmpdir}/xwiki/gwt/${gwtArtifactId}-${gwtVersion}</gwtHome>
    <compileTarget>
      <value>com.xpn.xwiki.watch.Watch</value>
    </compileTarget>
    <extraJvmArgs>-Xmx1024m</extraJvmArgs>
  </configuration>
  <dependencies>
    <dependency>
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
      <version>1.4.2</version>
    </dependency>
  </dependencies>
  <executions>
    <execution>
      <goals>
        <goal>compile</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

Thanks for your help John.
