### ISSUE TITLE
[MNG-3753] ArtifactResolverDiagnoser.diagnose() fails with NPE if nested IOException has no detail message

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5294]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-3753](https://issues.apache.org/jira/browse/MNG-3753?redirect=false)** and commented

The following stack trace has been extraced from MNG-3580:

```
java.lang.NullPointerException
        at java.lang.String.indexOf(String.java:792)
        at java.lang.String.indexOf(String.java:770)
        at org.apache.maven.usability.ArtifactResolverDiagnoser.diagnose(ArtifactResolverDiagnoser.java:53)
        at org.apache.maven.usability.diagnostics.ErrorDiagnostics.diagnose(ErrorDiagnostics.java:84)
        at org.apache.maven.DefaultMaven.logDiagnostics(DefaultMaven.java:754)
        at org.apache.maven.DefaultMaven.logError(DefaultMaven.java:701)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:135)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:79)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:618)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

While this was originally triggerd by an IBM JDK, this is really a Maven bug, the line

```java
if ( ioe != null && exception.getMessage().indexOf( ioe.getMessage() ) < 0 )
```

needs to check whether `ioe.getMessage()` is `null`. Compare API docs for `[Throwable.getMessage()](http://java.sun.com/javase/6/docs/api/java/lang/Throwable.html#getMessage())`.

---

**Affects:** 2.0.9

**Attachments:**
- [null-exception-message.patch](https://issues.apache.org/jira/secure/attachment/12712783/null-exception-message.patch) (_3.20 kB_)

**Issue Links:**
- [MNG-3580](https://issues.apache.org/jira/browse/MNG-3580) FATAL ERROR and NPE on start

3 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r793305](http://svn.apache.org/viewvc?view=rev&revision=793305).
