### ISSUE TITLE
[MNG-3756] having two properties that reference each other causes Maven to go into infinite loop

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5295]
**[Ian P. Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ips)** opened **[MNG-3756](https://issues.apache.org/jira/browse/MNG-3756?redirect=false)** and commented

I had the following in my pom (it was within a profile in case that matters):

    <properties>            
       <xxx>${yyy}</xxx>        
       <yyy>${xxx}</yyy>        
    </properties>

Here's the stack trace from a thread dump taken after Maven hung:

    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:393)
    at java.lang.StringBuffer.append(StringBuffer.java:225)
    - locked <0x06f7d9f0> (a java.lang.StringBuffer)
    at hidden.org.codehaus.plexus.util.StringUtils.replace(StringUtils.java:755)
    at hidden.org.codehaus.plexus.util.StringUtils.replace(StringUtils.java:721)
    at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolateInternal(RegexBasedModelInterpo

lator.java:177)
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolate(RegexBasedModelInterpolator.ja
va:98)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:1016)

    at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:878)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.ja

va:506)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:198)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:583)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:461)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)

---

**Affects:** 2.0.9

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712260/pom.xml) (_734 bytes_)

**Issue Links:**
- [MNG-2659](https://issues.apache.org/jira/browse/MNG-2659) possible to create an infinite loop in processing a POM
 (_**"supercedes"**_)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

got a small pom to reproduce this problem?

My build is using this feature and so far so good

**Comment by jira-importer** [comment]
**[Ian P. Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ips)** commented

Sure, it looks like the key is indeed that is has to be within a profile. Also, that profile needs to be activated from the command line, rather than via activeByDefault. Run the attached pom as follows:

mvn validate -P test

This should result in mvn hanging as follows:

"main" prio=6 tid=0x002a6000 nid=0x1d90 runnable [0x0090f000..0x0090fe54]
java.lang.Thread.State: RUNNABLE
at java.util.regex.Pattern$Start.match(Pattern.java:3055)
at java.util.regex.Matcher.search(Matcher.java:1105)
at java.util.regex.Matcher.find(Matcher.java:535)
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolateInternal(RegexBasedModelInterpo
lator.java:126)
at org.apache.maven.project.interpolation.RegexBasedModelInterpolator.interpolate(RegexBasedModelInterpolator.ja
va:98)
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:1016)

    at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:878)
    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.ja

va:506)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:198)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:583)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:461)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)

**Comment by jira-importer** [comment]
**[Dan Tran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dantran)** commented

you purposely create a recursive interpolation situation.

maven 2.1-M1 does detect condition and throws error.  So it is already fixed

But i dont think this is a valid usecase though

**Comment by jira-importer** [comment]
**[Ian P. Springer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ips)** commented

I don't understand why any recursion would come into play. I think the intuitive thing to do is evaluate the assignments in order, from top to bottom, just as would be done by any programming language. So:

\<xxx>${yyy}\</xxx>    // if yyy happens to have a value from the main section of this pom or some ancestor pom
\<yyy>${xxx}\</yyy>    // now assign the value of xxx to yyy - no need to re-evaluate the line above; just use whatever value for xxx was stored in memory

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

as Dan mentioned, can't reproduce in 2.1.0-M1.

The POM isn't a sequential script so the order of property definition shouldn't matter (if it did, it would break existing POMs that relied on forward references)
