### ISSUE TITLE
[MNG-3712] [regression] java.lang.NoClassDefFoundError in maven-jaxb-schemagen-plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5324]
**[Eugene Kuleshov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eu)** opened **[MNG-3712](https://issues.apache.org/jira/browse/MNG-3712?redirect=false)** and commented

When running maven-jaxb-schemagen-plugin with Maven 2.1-SNAPSHOT and latest 3.0-SNAPSHOT from trunk it fails with java.lang.NoClassDefFoundError. See attached test project and debug log from the build.

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory
	at com.sun.tools.jxc.maven2.SchemaGenMojo.execute(SchemaGenMojo.java:143)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:638)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:521)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:288)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:214)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:172)
	at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
	at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:303)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
	at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody2(MavenEmbedder.java:904)
	at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody3$advice(MavenEmbedder.java:303)
	at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
```

---

**Affects:** 3.0-alpha-1

**Attachments:**
- [build.log](https://issues.apache.org/jira/secure/attachment/12712254/build.log) (_80.83 kB_)
- [generate-schema.zip](https://issues.apache.org/jira/secure/attachment/12712302/generate-schema.zip) (_3.52 kB_)

**Issue Links:**
- [MNG-3586](https://issues.apache.org/jira/browse/MNG-3586) [regression] jaxws mojo wsgen failure with maven 3.0 due to system-scope dependencies being excluded
 (_**"duplicates"**_)
- [MNG-3715](https://issues.apache.org/jira/browse/MNG-3715) Maven 2.1plugin cannot use classes form tools.jar

- [MNG-5184](https://issues.apache.org/jira/browse/MNG-5184) java.lang.NoClassDefFoundError: com.sun.mirror.apt.AnnotationProcessorFactory on AIX 5.3

3 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Patrick Podenski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=podenski)** commented

Resolving this bug would help my use case a lot since I need to work extensively with JAXB and this bug prevents me from using Maven 2.1 with m2eclipse.

**Comment by jira-importer** [comment]
**[Yann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yann)** commented

I also raised an issue regarding this issue: MNG-3715
With this issue I provided a very simple plugin that try to use the class com/sun/mirror/apt/AnnotationProcessorFactory

**Comment by jira-importer** [comment]
**[Yann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yann)** commented

I did the test with maven  2.1.0-M1-RC17 and I haven't anymore the issue.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

needs verification on latest builds

**Comment by jira-importer** [comment]
**[Yann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yann)** commented

I just did the test with the last 3.0 SNAPSHOT and I still get the "java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory"

I did another test:
In the plugin that uses the AnnotationProcessorFactory class, instead of using the dependency:

```
    <dependency>
	  <groupId>com.sun</groupId>
	  <artifactId>tools</artifactId>
	  <version>1.5.12</version>
	  <scope>system</scope>
	  <systemPath>${java.home}/../lib/tools.jar</systemPath>
</dependency>
```

I used the same dependency without the system scope :

```
    <dependency>
	  <groupId>com.sun</groupId>
	  <artifactId>tools</artifactId>
	  <version>1.5.12</version>
</dependency>
```

Of course, I deployed the artefact in my repository which is not a good practice for the tools.jar file...

Then this time it worked
So it seems the problem is linked to the system scope...
