### ISSUE TITLE
[MNG-3711] NPE in ChecksumObserver

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5329]
**[Thomas Diesler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tdiesler)** opened **[MNG-3711](https://issues.apache.org/jira/browse/MNG-3711?redirect=false)** and commented

After Ctrl+C during 'mvn deploy' I seem to have a corrupt snapshot repository.

Subsequent deploy attempts fail with

Uploading: https://snapshots.jboss.org/maven2/org/jboss/bpm/bpm-dialect-xpdl21/1.0.0-SNAPSHOT/bpm-dialect-xpdl21-1.0.0-20080814.162232-1.jar
[INFO] Uploading project information for bpm-dialect-xpdl21 1.0.0-20080814.162232-1
[INFO] Retrieving previous metadata from snapshots.jboss.org
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.wagon.observers.ChecksumObserver.transferStarted(ChecksumObserver.java:65)
at org.apache.maven.wagon.events.TransferEventSupport.fireTransferStarted(TransferEventSupport.java:100)
at org.apache.maven.wagon.AbstractWagon.fireGetStarted(AbstractWagon.java:378)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:193)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:182)
at org.apache.maven.wagon.providers.webdav.WebDavWagon.get(WebDavWagon.java:426)
at org.apache.maven.wagon.providers.webdav.WebDavWagon.get(WebDavWagon.java:377)

---

**Affects:** 2.0.9

**Issue Links:**
- [WAGON-83](https://issues.apache.org/jira/browse/WAGON-83) mvn deploy causes NPE in ChecksumObserver.transferStarted
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

could you try this with 2.1.0-M1 or 2.0.10?

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

fixed in 2.1.0-M1 by wagon upgrade
