### ISSUE TITLE
[MNG-3704] NPE in DefaultLIfecycleExecutor when run from within Hudson builds

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5334]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** opened **[MNG-3704](https://issues.apache.org/jira/browse/MNG-3704?redirect=false)** and commented

```
[INFO] [clean:clean]
[HUDSON] Archiving /home/j2ee-hudson/.hudson/jobs/CXF/workspace/trunk/pom.xml to /home/j2ee-hudson/.hudson/jobs/CXF/modules/org.apache.cxf$cxf/builds/2008-08-11_16-49-47/archive/org.apache.cxf/cxf/2.1.2-SNAPSHOT/pom.xml
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.restoreDynamicState(DefaultLifecycleExecutor.java:779)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:636)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:533)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:512)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:364)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:325)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:176)
	at org.apache.maven.lifecycle.LifecycleExecutorInterceptor.execute(LifecycleExecutorInterceptor.java:42)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at hudson.maven.agent.Main.launch(Main.java:133)
	at hudson.maven.MavenBuilder.call(MavenBuilder.java:135)
	at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:536)
	at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:482)
	at hudson.remoting.UserRequest.perform(UserRequest.java:69)
	at hudson.remoting.UserRequest.perform(UserRequest.java:23)
	at hudson.remoting.Request$2.run(Request.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:885)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:907)
	at java.lang.Thread.run(Thread.java:619)
```

---

**Affects:** 2.0.10

**Issue Links:**
- [MNG-4137](https://issues.apache.org/jira/browse/MNG-4137) NPE in DefaultLIfecycleExecutor when run from within Hudson builds

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

This is still the case, even with 2.1.0-M1:

http://davidkarlsen.com/hudson/job/WAS6%20plugin/74/console

**Comment by jira-importer** [comment]
**[Eric TOURNIER](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eric_t)** commented

I confirm, this is still the case.
I'm using 2.1.0-M1 with Hudson-1.285 and Cobertura Maven Plugin 2.2. When the plugin is not used, everything works well, but as soon as the `<plugin>...</plugin>` section is activated, I got the NullPointerException, which is slighlty different from the preceding (the method where it occurs was not `restoreDynamicState` but `calculateConcreteConfiguration`) :\\
\\

```
[INFO] Preparing cobertura:cobertura
[WARNING] Removing: jar from forked lifecycle, to prevent recursive invocation.
[WARNING] Removing: cobertura from forked lifecycle, to prevent recursive invocation.
[HUDSON] Archiving (...)\pom.xml to (...)\pom.xml
[HUDSON] Archiving (...)\target\sequoia-security-impl-2.4.0-SNAPSHOT.jar to (...)\sequoia-security-impl-2.4.0-SNAPSHOT.jar
[HUDSON] Archiving (...)\target\sequoia-security-impl-2.4.0-SNAPSHOT-sources.jar to (...)\sequoia-security-impl-2.4.0-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.calculateConcreteConfiguration(DefaultLifecycleExecutor.java:759)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:576)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:538)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1177)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:1018)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:625)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:538)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:517)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:369)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:330)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
	at org.apache.maven.lifecycle.LifecycleExecutorInterceptor.execute(LifecycleExecutorInterceptor.java:65)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at hudson.maven.agent.Main.launch(Main.java:158)
```

**Comment by jira-importer** [comment]
**[luke w patterson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lukewpatterson)** commented

I still see the same issue too, whenever I run to site with Clover reports.

Is this related to
https://hudson.dev.java.net/issues/show_bug.cgi?id=2373
?

I'm using Maven 2.1.0-M1 / Hudson 1.291 / Clover 2.4.3

**Comment by jira-importer** [comment]
**[Jonathan Johnson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jonathan%20johnson)** commented

I'm still getting it.  See http://jira.codehaus.org/browse/MNG-4137
