### ISSUE TITLE
[MNG-3517] Bump to org.codehaus.plexus:plexus-maven-plugin:1.3.8

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5392]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** opened **[MNG-3517](https://issues.apache.org/jira/browse/MNG-3517?redirect=false)** and commented

Maven uses org.codehaus.plexus:plexus-maven-plugin:1.3.5 which is buggy when using anonymous inner classes:

```
public class AddTableDialog
    extends AbstractDialog
{
    ...

    private ModifyListener modifyListener = new ModifyListener()
    {
        /** {@inheritDoc} */
        public void modifyText( ModifyEvent event )
        {
            if ( okButton != null )
            {
                try
                {
                    int rows = Integer.parseInt( rowsText.getText().trim() );
                    int cols = Integer.parseInt( colsText.getText().trim() );

                    okButton.setEnabled( rows > 0 && cols > 0 );
                }
                catch ( Exception e )
                {
                    okButton.setEnabled( false );
                }
            }
        }
    };

    ...
}
```

We got the following stacktrace

```
[INFO] [plexus:descriptor {execution: default}]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] syntax error @[92,41] in file:/D:/java/apache.org/maven/src/trunks/doxia/doxia-tools/dox
ia-ide/eclipse/plugins/org.apache.maven.doxia.ide.eclipse.common.ui/src/main/java/org/apache/ma
ven/doxia/ide/eclipse/common/ui/dialogs/AddTableDialog.java
[INFO] ------------------------------------------------------------------------
[INFO] Trace
com.thoughtworks.qdox.parser.ParseException: syntax error @[92,41] in file:/D:/java/apache.org/
maven/src/trunks/doxia/doxia-tools/doxia-ide/eclipse/plugins/org.apache.maven.doxia.ide.eclipse
.common.ui/src/main/java/org/apache/maven/doxia/ide/eclipse/common/ui/dialogs/AddTableDialog.ja
va
        at com.thoughtworks.qdox.parser.impl.Parser.yyerror(Parser.java:638)
        at com.thoughtworks.qdox.parser.impl.Parser.yyparse(Parser.java:747)
        at com.thoughtworks.qdox.parser.impl.Parser.parse(Parser.java:619)
        at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:300)
        at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:316)
        at com.thoughtworks.qdox.JavaDocBuilder.addSource(JavaDocBuilder.java:312)
        at com.thoughtworks.qdox.JavaDocBuilder$1.visitFile(JavaDocBuilder.java:369)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:43
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.walk(DirectoryScanner.java:34
)
        at com.thoughtworks.qdox.directorywalker.DirectoryScanner.scan(DirectoryScanner.java:52
)
        at com.thoughtworks.qdox.JavaDocBuilder.addSourceTree(JavaDocBuilder.java:366)
        at org.codehaus.plexus.cdc.DefaultComponentDescriptorCreator.processSources(DefaultComp
onentDescriptorCreator.java:120)
        at org.codehaus.plexus.maven.plugin.AbstractDescriptorMojo.generateDescriptor(AbstractD
escriptorMojo.java:120)
        at org.codehaus.plexus.maven.plugin.PlexusDescriptorMojo.execute(PlexusDescriptorMojo.j
ava:71)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:4
51)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExe
cutor.java:558)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(Default
LifecycleExecutor.java:499)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExec
utor.java:478)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(Def
aultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifec
ycleExecutor.java:291)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor
.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25
)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

A workaround is to bump to org.codehaus.plexus:plexus-maven-plugin:1.3.8, ie:

```
<project>
   ...
  <build>
   ...
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.plexus</groupId>
          <artifactId>plexus-maven-plugin</artifactId>
          <version>1.3.8</version>
        </plugin>
      </plugins>
    </pluginManagement>
    
    <plugins>
      <plugin>
        <groupId>org.codehaus.plexus</groupId>
        <artifactId>plexus-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
```

---

**Affects:** 2.0.9

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

the current Maven parent has been using this for some time.
