### ISSUE TITLE
[MNG-3495] NPE  at org.apache.maven.wagon.repository.Repository.hashCode(Repository.java:241)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5418]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** opened **[MNG-3495](https://issues.apache.org/jira/browse/MNG-3495?redirect=false)** and commented

[INFO] ------------------------------------------------------------------------
[INFO] Building portal-core
[INFO]    task-segment: [clean, install]
[INFO] ------------------------------------------------------------------------
[INFO] [clean:clean]
[INFO] Deleting directory /tmp/portal-trunks/portal-core/target
Downloading: http://repo.sandsli.dnb.no/px/repository/public/opensymphony/quartz/1.6.0/quartz-1.6.0.pom
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.wagon.repository.Repository.hashCode(Repository.java:241)
at java.util.HashMap.put(HashMap.java:418)
at java.util.HashSet.add(HashSet.java:194)
at java.util.AbstractCollection.addAll(AbstractCollection.java:318)
at java.util.HashSet.\<init>(HashSet.java:100)
at org.apache.maven.artifact.resolver.AbstractArtifactResolutionException.constructMessageBase(AbstractArtifactResolutionException.java:188)
at org.apache.maven.artifact.resolver.AbstractArtifactResolutionException.\<init>(AbstractArtifactResolutionException.java:67)
at org.apache.maven.artifact.resolver.ArtifactNotFoundException.\<init>(ArtifactNotFoundException.java:55)
at org.apache.maven.artifact.resolver.ArtifactNotFoundException.\<init>(ArtifactNotFoundException.java:48)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:212)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:74)
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:545)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:249)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:105)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:380)
at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:76)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:300)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:288)
at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1415)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:405)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 42 seconds
[INFO] Finished at: Wed Apr 02 08:45:24 CEST 2008
[INFO] Final Memory: 24M/376M
[INFO] ------------------------------------------------------------------------

/tmp/portal-trunks $ java -version
java version "1.5.0_06"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.5.0_06-b05)
Java HotSpot(TM) Server VM (build 1.5.0_06-b05, mixed mode)

---

**Affects:** 2.0.9

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

fixed - though you should really add the missing \<id> to settings.xml in \<mirror>

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

Sure - how does it work?
http://maven.apache.org/ref/2.0.8/maven-settings/settings.html#class_mirror isn't very informative.
Probably all mirror's which have the same url have the same id?
