### ISSUE TITLE
[MNG-3422] [regression] deploy:deploy-file does not work

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5460]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-3422](https://issues.apache.org/jira/browse/MNG-3422?redirect=false)** and commented

mvn deploy:deploy-file -Dfile=test.sh -DrepositoryId=testing -DartifactId=artifactId -DgroupId=groupId -Dversion=1.0 -Dpackaging=jar -Durl=http://vesuvius.devzuz.com/private/devzuz/releases

[INFO] Searching repository for plugin with prefix: 'deploy'.
[INFO] Attempting to resolve a version for plugin: org.apache.maven.plugins:maven-deploy-plugin using meta-version: LATEST
[INFO] Using version: 2.3 of plugin: org.apache.maven.plugins:maven-deploy-plugin
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Default Project
[INFO]
[INFO] Id: org.apache.maven:super-pom:jar:2.1
[INFO] task-segment: [deploy:deploy-file] (aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] [deploy:deploy-file]
[INFO] artifact groupId:artifactId: checking for updates from testing

---

constituent[0]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/aspectjrt-1.5.3.jar
constituent[1]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/backport-util-concurrent-3.0.jar
constituent[2]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/commons-cli-1.0.jar
constituent[3]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/doxia-sink-api-1.0-alpha-9.jar
constituent[4]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/jsch-0.1.27.jar
constituent[5]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/jtidy-4aug2000r7-dev.jar
constituent[6]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-artifact-3.0-SNAPSHOT.jar
constituent[7]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-core-2.1-SNAPSHOT.jar
constituent[8]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-embedder-2.1-SNAPSHOT.jar
constituent[9]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-lifecycle-2.1-SNAPSHOT.jar
constituent[10]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-model-2.1-SNAPSHOT.jar
constituent[11]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-plugin-api-2.1-SNAPSHOT.jar
constituent[12]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-profile-2.1-SNAPSHOT.jar
constituent[13]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-project-2.1-SNAPSHOT.jar
constituent[14]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/maven-reporting-api-2.1-SNAPSHOT.jar
constituent[15]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/plexus-container-default-1.0-alpha-44.jar
constituent[16]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/plexus-interactivity-api-1.0-alpha-6.jar
constituent[17]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/plexus-utils-1.5.1.jar
constituent[18]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/retrotranslator-runtime-1.2.1.jar
constituent[19]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/wagon-file-1.0-beta-2.jar
constituent[20]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/wagon-http-lightweight-1.0-beta-2.jar
constituent[21]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/wagon-http-shared-1.0-beta-2.jar
constituent[22]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/wagon-provider-api-1.0-beta-2.jar
constituent[23]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/wagon-ssh-1.0-beta-2.jar
constituent[24]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/wagon-ssh-common-1.0-beta-2.jar
constituent[25]: file:/Applications/maven/apache-maven-2.1-SNAPSHOT/lib/wagon-ssh-external-1.0-beta-2.jar

---

java.lang.NullPointerException
at org.apache.maven.artifact.repository.DefaultArtifactRepository.pathOfRemoteRepositoryMetadata(DefaultArtifactRepository.java:123)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadata(DefaultWagonManager.java:390)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:349)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolve(DefaultRepositoryMetadataManager.java:107)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieveAvailableVersions(MavenMetadataSource.java:433)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.artifactHasBeenDeployed(DefaultArtifactDeployer.java:169)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:91)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:239)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:549)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentsForProject(DefaultLifecycleExecutor.java:265)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:180)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:225)
at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:304)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody4(MavenEmbedder.java:880)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody5$advice(MavenEmbedder.java:304)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)

---

**Affects:** 3.0-alpha-1

**Issue Links:**
- [MNG-3352](https://issues.apache.org/jira/browse/MNG-3352) install:install-file fails in plexus-tools/plexus-javadoc with NPE related to an ArtifactRepositoryLayout that cannot be found.
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Adam Leggett](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aleggett)** commented

I discovered the same issue when using 2.1-20080302.021203-37 of the embedder.

Seems to me that the injected repositoryLayouts in DeployFileMojo does not contain any valid layouts.
Short term fix for us was to bring the plugin inhouse and instanciate a default layout within execute():

ArtifactRepositoryLayout layout;

layout = ( ArtifactRepositoryLayout ) repositoryLayouts.get( repositoryLayout );

//
//FIX: issue when using maven-artifact-3.0-SNAPSHOT
//The plexus injected repositoryLayouts does not contain any valid layouts
//
if( layout == null )
{
layout = new DefaultRepositoryLayout();
}

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Confirmed. Taking a look now to see how bad it is.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this is probably the same problem with active collections seen here: MNG-3352

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Using the following:

mvn org.apache.maven.plugins:maven-deploy-plugin:2.2:deploy-file -Dfile=test.sh -DrepositoryId=testing -DartifactId=artifactId -DgroupId=groupId -Dversion=1.0 -Dpackaging=jar -Durl=file://repo

Wagon 1.0-beta-3 dies so I can't really tell easily if it's the plugin version or not.

java.lang.NullPointerException
at org.apache.maven.wagon.LazyFileOutputStream.flush(LazyFileOutputStream.java:77)
at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:124)
at java.io.FilterOutputStream.close(FilterOutputStream.java:140)
at org.codehaus.plexus.util.IOUtil.close(IOUtil.java:762)
at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:424)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:389)
at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:362)
at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:160)
at org.apache.maven.artifact.manager.DefaultWagonManager.putRemoteFile(DefaultWagonManager.java:237)
at org.apache.maven.artifact.manager.DefaultWagonManager.putArtifact(DefaultWagonManager.java:166)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:109)
at org.apache.maven.plugin.deploy.DeployFileMojo.execute(DeployFileMojo.java:194)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:638)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:498)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:265)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:180)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:149)
at org.apache.maven.DefaultMaven.execute_aroundBody0(DefaultMaven.java:223)
at org.apache.maven.DefaultMaven.execute_aroundBody1$advice(DefaultMaven.java:303)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:1)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody2(MavenEmbedder.java:904)
at org.apache.maven.embedder.MavenEmbedder.execute_aroundBody3$advice(MavenEmbedder.java:303)
at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:1)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:176)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

does test.sh have content? I thought that bug only surfaced on zero-length files

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

No content. With version 2.2 of the deploy plugin this works fine. There is a problem with 2.3 which introduced a bunch of duplicated code including the `@component` annotation pulling in all the layouts instead of just using the id and letting the factory take care of it. It's this form of the annotation that doesn't work, it works fine with standard plexus annotations.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

This is not an active collection problem, it's a the wrong classloader being used by the active collection so no components are returned. Now I can fix it.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Just an update that I have this fixed in Plexus, the wrong realm was being grabbed and so the right place for the components wasn't being used. I'm going to test m2e and then I'll check it all in.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

probably fixed, just needs to be verified

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed as of plexus-container-default:1.0-beta-1.2+, IT online.
