### ISSUE TITLE
[MNG-3352] install:install-file fails in plexus-tools/plexus-javadoc with NPE related to an ArtifactRepositoryLayout that cannot be found.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5501]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** opened **[MNG-3352](https://issues.apache.org/jira/browse/MNG-3352?redirect=false)** and commented

---

**Affects:** 3.0-alpha-1

**Issue Links:**
- [MNG-3422](https://issues.apache.org/jira/browse/MNG-3422) [regression] deploy:deploy-file does not work
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

this is related to active collections:

[DEBUG] Setting context classloader for plugin to: /plugins/org.apache.maven.plugins:maven-install-plugin:2.2@48/thread:main (instance is: ClassRealm[
/plugins/org.apache.maven.plugins:maven-install-plugin:2.2@48/thread:main, parent: ClassRealm[plexus.core, parent: null]])
[DEBUG] Failed to lookup a member of active collection with role: org.apache.maven.artifact.repository.layout.ArtifactRepositoryLayout and role-hint:
default
in realm: null
org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository: org.apa
che.maven.artifact.repository.layout.ArtifactRepositoryLayout [default] (lookup realm: null).
role: org.apache.maven.artifact.repository.layout.ArtifactRepositoryLayout
roleHint: default
classRealm: none specified
at org.codehaus.plexus.DefaultComponentLookupManager.lookup(DefaultComponentLookupManager.java:139)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:492)
at org.codehaus.plexus.component.collections.AbstractComponentCollection.lookup(AbstractComponentCollection.java:209)
at org.codehaus.plexus.component.collections.ComponentMap.get(ComponentMap.java:78)
at org.apache.maven.plugin.install.InstallFileMojo.execute(InstallFileMojo.java:170)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

possibly related
