### ISSUE TITLE
[MNG-3373] Maven 2 says host in unavailable while in browser I can download from that repository

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5505]
**[Markus KARG](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=markus-karg)** opened **[MNG-3373](https://issues.apache.org/jira/browse/MNG-3373?redirect=false)** and commented

I am using the offical Glassfish repository on java.net.

Maven tells me that it cannot resolve one of the references pointing into that repository. The stack trace tells me that the host is not available (see below).

In fact, when I go to that same URL in the browser, it downloads the artifact without any problem!

Also that worked for weeks and now is broken, but my POM didn't change!

So I assume a bug in WAGON.

Here is the POM excerpt, below the POM is the stack trace.

    <repositories>
    	<repository>
    		<id>glassfish-repository.dev.java.net</id>
    		<name>Java.net Repository for Glassfish</name>
    		<url>http://download.java.net/maven/glassfish</url>
    	</repository>
    </repositories>
    
    <dependencies>
    	<dependency>
    		<groupId>javax.resource</groupId>
    		<artifactId>connector-api</artifactId>
    		<version>1.5</version>
    		<scope>provided</scope>
    	</dependency>
    </dependencies>

org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency
information: Unable to read the metadata file for artifact 'javax.resource:conn
ector-api:jar': Cannot find parent: org.glassfish.api:api for project: javax.res
ource:connector-api:jar:1.5 for project javax.resource:connector-api:jar:1.5
javax.resource:connector-api:jar:1.5

from the specified remote repositories:
central (http://repo1.maven.org/maven2),
glassfish-repository.dev.java.net (http://download.java.net/maven/glassfish)
Path to dependency:
1) net.sourceforge.rafc:rafc:jar:1.1.1
   ...
   Caused by: java.net.UnknownHostException: download.java.net
   at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:177)
   at java.net.Socket.connect(Socket.java:519)
   at java.net.Socket.connect(Socket.java:469)
   at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
   at sun.net.www.http.HttpClient.openServer(HttpClient.java:394)
   at sun.net.www.http.HttpClient.openServer(HttpClient.java:529)
   at sun.net.www.http.HttpClient.\<init>(HttpClient.java:233)
   at sun.net.www.http.HttpClient.New(HttpClient.java:306)
   at sun.net.www.http.HttpClient.New(HttpClient.java:323)
   at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLC
   onnection.java:788)
   at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConne
   ction.java:729)
   at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection
   .java:654)
   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
   nection.java:977)
   at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputD
   ata(LightweightHttpWagon.java:83)
   ... 33 more

---

**Affects:** 2.0.8

**Issue Links:**
- [MNG-4183](https://issues.apache.org/jira/browse/MNG-4183) CLONE -Maven 2 says host is unavailable while in browser I can download from that repository
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency
information: Unable to read the metadata file for artifact 'javax.resource:conn
ector-api:jar': Cannot find parent: org.glassfish.api:api for project: javax.res
ource:connector-api:jar:1.5 for project javax.resource:connector-api:jar:1.5
javax.resource:connector-api:jar:1.5

---

Actually, it looks to me like it's getting caught while trying to resolve javax.resource:connector-api:1.5, specifically because the parent:

org.glassfish.api:api

can't be resolved for some reason. When I checked just now, javax.resource:connector-api:1.5 specified a parent version of 10.0-SNAPSHOT for the glassfish api parent-POM. 'm a little stumped as to why that would be the case, since it's in the java.net repository and that repository is obviously reachable from Maven, but that's definitely the sticking point:

Cannot find parent: org.glassfish.api:api for project: javax.resource:connector-api:jar:1.5

Maybe if you execute the build with the -X flag and capture the output to a file (`mvn -X clean install > build.log` or similar) it would shed more light on why it cannot download that parent POM.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Pushing to 2.0.11 so we can have a smaller set of high-value issues to target for the next release (2.0.10).

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

request for info wasn't followed up and this is no longer relevant in 2.2.0 (switched to httpclient)
