### ISSUE TITLE
[MNG-4168] String index out of range: 43807

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5588]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** opened **[MNG-4168](https://issues.apache.org/jira/browse/MNG-4168?redirect=false)** and commented

the issue occurs with the versions:display-plugin-updates. It throws :

```
[INFO] [versions:display-plugin-updates]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] String index out of range: 43807
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.StringIndexOutOfBoundsException: String index out of range: 43807
        at java.lang.StringBuffer.charAt(StringBuffer.java:163)
        at org.codehaus.mojo.versions.rewriting.ModifiedPomXMLEventReader.c(ModifiedPomXMLEventReader.java:444)
        at org.codehaus.mojo.versions.rewriting.ModifiedPomXMLEventReader.hasNext(ModifiedPomXMLEventReader.java:369)
        at org.codehaus.mojo.versions.DisplayPluginUpdatesMojo.findPluginsWithVersionsSpecified(DisplayPluginUpdatesMojo.java:471)
        at org.codehaus.mojo.versions.DisplayPluginUpdatesMojo.execute(DisplayPluginUpdatesMojo.java:247)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:553)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:523)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

I'll try to isolate the problem to see if it's due to the pom or to the maven version.

---

**Affects:** 2.2.0

**Comment by jira-importer** [comment]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** commented

reproduced with alpha-2, alpha-3 and current trunk (beta-1)

**Comment by jira-importer** [comment]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** commented

The issue is only with 2.0.0-RC2. It doesn't exist with 2.0.9 and 2.1.0.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

could this be a pom transformation issue? the versions plugin is doing some pretty specific stuff and may be the better place to fix it even if it is incompatible - depends on whether John's recent changes have helped already

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

This appears to have gone away after I withdrew the POM transformations code. Since we don't have a viable solution for POM transformations, it won't be likely to come up again in this release.
