### ISSUE TITLE
[MNG-4162] Removal of all reporting logic from the core of Maven

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5592]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** opened **[MNG-4162](https://issues.apache.org/jira/browse/MNG-4162?redirect=false)** and commented

Any reporting implementation will be implemented as a plugin. Maven will provide any information, APIs, and extension points to make this possible. But the conflation of building with reporting in the core makes it almost impossible for anyone to understand the distinction, makes it impossible to have alternate implementations and couple many tools like Doxia directly to the core which is unacceptable for Maven 3.x.

---

**Attachments:**
- [MNG-4162.patch](https://issues.apache.org/jira/secure/attachment/12713006/MNG-4162.patch) (_15.94 kB_)

**Sub-tasks:**
- [MNG-4163](https://issues.apache.org/jira/browse/MNG-4163) Deprecate all methods in MavenProject that relate to reporting.

**Issue Links:**
- [MNG-7504](https://issues.apache.org/jira/browse/MNG-7504) Warning about unknown reportPlugins parameters for m-site-p are always generated
 (_**"causes"**_)
- [MNG-6189](https://issues.apache.org/jira/browse/MNG-6189) WARN if maven-site-plugin configuration contains reportPlugins element

- [MNG-7408](https://issues.apache.org/jira/browse/MNG-7408) Explain reporting plugin version automatic selection (in Maven 3)

- [MNG-7505](https://issues.apache.org/jira/browse/MNG-7505) Remove ReportingConverter

- [MSHARED-628](https://issues.apache.org/jira/browse/MSHARED-628) support maven-model ReportPlugin in addition to local copy

- [MSITE-792](https://issues.apache.org/jira/browse/MSITE-792) drop reportPlugins parameter ("new format")

- [MNG-4261](https://issues.apache.org/jira/browse/MNG-4261) site plugin doesn't generate reports

- [MPIR-174](https://issues.apache.org/jira/browse/MPIR-174) remove use of container.getLoggerManager() (to be compatible wih maven 3.x)

- [MSITE-484](https://issues.apache.org/jira/browse/MSITE-484) Support adding and overriding report plugins in new maven-site-plugin 3.x reportPlugins configuration format

1 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

branches started :
- core : https://svn.apache.org/repos/asf/maven/components/branches/MNG-4162/
- site plugin : https://svn.apache.org/repos/asf/maven/plugins/branches/maven-site-plugin-3.x

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

I have commit stuff in core branch.
No big chance only new methods and some move from private to public.
No objections to merge to trunk ?

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

The approach used creating for each report plugin : creating a new ClassRealm with parent maven-site-plugin-realm with parent core realm.
Following imported from maven-site-plugin realm :
- org.apache.maven.reporting.MavenReport
- org.codehaus.doxia.sink.Sink
- org.apache.maven.doxia.sink.Sink
- org.apache.maven.doxia.sink.SinkEventAttributes

Note need to add org.apache.maven.artifact.manager.WagonConfigurationException in compat.
So I now have the famous issue with :

```
        ... 15 more
Caused by: java.lang.NoSuchMethodError: org.codehaus.plexus.PlexusContainer.getLoggerManager()Lorg/codehaus/plexus/logging/LoggerManager;
        at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:222)
        at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:90)
        at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:145)
        ... 19 more
```

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

note [rev  800978](http://svn.apache.org/viewvc?view=rev&revision=800978) is needed for be able to use maven-project-info-reports-plugin.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

So it looks to works fine now.
Please review core branches.
Note no huge hack has been added only new methods.
Please review before merging.
Thanks

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

merge  from branch MNG-4162

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Olivier, we can't consume the patch as is. The problem is that the Site Plugin heavily reuses the plugin manager. However, the plugin manager is coded to support build plugins, i.e. makes certain assumptions about its use. With the Site Plugin reusing it in its current form, we would for instance end up with plugin realms for build and report plugins getting crippled and hard to debug class loading errors during reactor builds.

I'm going to look into refactoring the plugin manager. I envision a little layering where we have some general-purpose plugin management components on top of which both the core's plugin manager and the Site Plugin's plugin manager can easily support build plugins and report plugins, respectively.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

first part of this working. Currently only for "simple" report plugins.
Now we have to work with complicated report plugins which fork lifecycle (surefire report, cobertura).

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

This is all done isn't it, the site plugin just doesn't work 100% right?

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

I have to review the its and understand the failures. (https://grid.sonatype.org/ci/view/Maven%203.0.x/job/maven-site-plugin-3.x/).
It looks something has changed (in classworld I think) and now some reporting plugins breaks.
But I haven't yet investigated.

**Comment by jira-importer** [comment]
**[Christopher Hunt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=huntc@internode.on.net)** commented

Am I correct in assuming that the 2.x reporting section of a pom file is completely incompatible with Maven 3? This has been my observation at least, and I suspect that it will impact on the uptake of Maven 3. I understand the motivation in factoring out the report plugin from core, but I would favour deprecation of the reporting section in the pom over removal in order to have Maven 3 become widely adopted.
