### ISSUE TITLE
[MNG-4137] NPE in DefaultLIfecycleExecutor when run from within Hudson builds

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5618]
**[Jonathan Johnson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jonathan%20johnson)** opened **[MNG-4137](https://issues.apache.org/jira/browse/MNG-4137?redirect=false)** and commented

Since upgrading from Maven 2.0.10 to 2.1.0 my Hudson midnight job that runs "clean site" fails with a NullPointerException at DefaultLifecycleExecutor.java:747 exception.  See below.

This is related, if not the same bug that was claimed fixed in 2.1.0 M1 - http://jira.codehaus.org/browse/MNG-3704

I though its was an issue with the Cobertura plugin - See https://hudson.dev.java.net/issues/show_bug.cgi?id=3468 but once I remove Cobertura I now get the same stack trace after "[INFO] Preparing surefire-report:report":

[INFO] Preparing surefire-report:report
[HUDSON] Archiving [...omittted for this posting...]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.calculateConcreteConfiguration(DefaultLifecycleExecutor.java:747)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:578)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1168)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:1009)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:647)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.lifecycle.LifecycleExecutorInterceptor.execute(LifecycleExecutorInterceptor.java:65)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at hudson.maven.agent.Main.launch(Main.java:158)
at hudson.maven.MavenBuilder.call(MavenBuilder.java:162)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:578)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:524)
at hudson.remoting.UserRequest.perform(UserRequest.java:97)
at hudson.remoting.UserRequest.perform(UserRequest.java:46)
at hudson.remoting.Request$2.run(Request.java:236)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:619)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6 minutes 45 seconds
[INFO] Finished at: Fri Apr 17 14:58:47 EDT 2009
[INFO] Final Memory: 76M/271M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.1.0

**Issue Links:**
- [MNG-3704](https://issues.apache.org/jira/browse/MNG-3704) NPE in DefaultLIfecycleExecutor when run from within Hudson builds

5 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Jonathan Johnson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jonathan%20johnson)** commented

After upgrading to Hudson ver. 1.306 and sticking with Maven 2.1 my nightly site report is building again without the error.   It also looks like issue 2373 on the Maven side has been addressed and will be available after Maven 2.1. Thank you!
