### ISSUE TITLE
[MNG-4503] Project building exception : Cannot find parent

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5642]
**[amaresh mourya](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=amaresh)** opened **[MNG-4503](https://issues.apache.org/jira/browse/MNG-4503?redirect=false)** and commented

I ran the org.apache.maven.project.MavenProject build() method from DeafultMavenProjectBuilder for maven-artifact's pom.xml (A) to build Maven Project for maven-artifact, but since it is derived from org.apache.maven:maven:2.2.0 's pom.xml which has parent entry like shown below (B), and maven-parent is not located at relative path is gives me the following error (C):
If maven-parent is not available at relative path it should download it from the central.

1. I haven't touched my local repo.
2. my setting.xml resides at \apache-maven-2.1.0\conf\settings.xml and have just proxy information
3. I have attached my test case with setting.xml

A: part of maven-artifact's pom.xml

\<parent>
\<groupId>org.apache.maven\</groupId>
\<artifactId>maven\</artifactId>
\<version>2.2.0\</version>
\</parent>
\<artifactId>maven-artifact\</artifactId>

B:part of maven's pom.xml

\<parent>
\<groupId>org.apache.maven\</groupId>
\<artifactId>maven-parent\</artifactId>
\<version>11\</version>
\<relativePath>../pom/maven/pom.xml\</relativePath>
\</parent>
\<artifactId>maven\</artifactId>
\<version>2.2.0\</version>
\<packaging>pom\</packaging>

C:Error thrown

org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.apache.maven:maven-parent for project: null:maven:pom:2.2.0 for project null:maven:pom:2.2.0
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1398)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1415)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:508)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:217)
at oracle.jdeveloper.maven.node.POMNode.getFullMavenProject(POMNode.java:322)
at oracle.jdevimpl.wizard.project.MavenProjectImportWorker.loadPOM(MavenProjectImportWorker.java:215)
at oracle.jdevimpl.wizard.project.MavenProjectImportWorker.generate(MavenProjectImportWorker.java:163)
at oracle.jdevimpl.wizard.project.MavenProjectImportWorker.runGen(MavenProjectImportWorker.java:136)
at oracle.jdevimpl.wizard.project.MavenProjectImportWorker.callImport(MavenProjectImportWorker.java:114)
at oracle.jdevimpl.wizard.project.MavenProjectImportWorker.run(MavenProjectImportWorker.java:91)
at java.lang.Thread.run(Thread.java:619)
Caused by: org.apache.maven.project.ProjectBuildingException: POM 'org.apache.maven:maven-parent' not found in repository: Unable to download the artifact from any repository

org.apache.maven:maven-parent:pom:11

from the specified remote repositories:
central (http://repo1.maven.org/maven2)

for project org.apache.maven:maven-parent
at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:605)
at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1394)
... 11 more
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException: Unable to download the artifact from any repository

org.apache.maven:maven-parent:pom:11

from the specified remote repositories:
central (http://repo1.maven.org/maven2)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:228)
    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:90)
    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:558)
    ... 12 more

Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: Unable to download the artifact from any repository
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:349)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:216)
... 14 more

---

**Affects:** 2.1.0

**Attachments:**
- [apache-maven-2.2.0.rar](https://issues.apache.org/jira/secure/attachment/12712967/apache-maven-2.2.0.rar) (_1.77 MB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> If maven-parent is not available at relative path it should download it from the central.
> And it does:

```
Caused by: org.apache.maven.artifact.resolver.ArtifactNotFoundException:
Unable to download the artifact from any repository

org.apache.maven:maven-parent:pom:11

from the specified remote repositories:
central (http://repo1.maven.org/maven2)
```

As this POM is available from [central](http://repo2.maven.org/maven2/org/apache/maven/maven-parent/11/), this indicates you have a network/proxy problem. Please use the [user mailing list](http://maven.apache.org/mail-lists.html) to solve your environment issue.
