### ISSUE TITLE
[MNG-4080] running mvn fails on IBM JDK 6 with NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5668]
**[Volker Karlmeier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=volker)** opened **[MNG-4080](https://issues.apache.org/jira/browse/MNG-4080?redirect=false)** and commented

Running mvn under IBM SDK 6.0 fails with NullPointerException:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building AlertBatches
[INFO]    task-segment: [compile]
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.apache.maven.project.ModelUtils.mergePluginLists(ModelUtils.java
164)
at org.apache.maven.project.inheritance.DefaultModelInheritanceAssemble
.assembleBuildInheritance(DefaultModelInheritanceAssembler.java:369)
at org.apache.maven.project.inheritance.DefaultModelInheritanceAssemble
.assembleModelInheritance(DefaultModelInheritanceAssembler.java:168)
at org.apache.maven.project.inheritance.DefaultModelInheritanceAssemble
.assembleModelInheritance(DefaultModelInheritanceAssembler.java:61)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(De
aultMavenProjectBuilder.java:851)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromReposit
ry(DefaultMavenProjectBuilder.java:252)
at org.apache.maven.plugin.DefaultPluginManager.checkRequiredMavenVersi
n(DefaultPluginManager.java:265)
at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(D
faultPluginManager.java:197)
at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPlu
inManager.java:176)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.verifyPlugin(Def
ultLifecycleExecutor.java:1275)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindPluginToLife
ycle(DefaultLifecycleExecutor.java:1239)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecyc
eMappings(DefaultLifecycleExecutor.java:1005)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defa
ltLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHa
dleFailures(DefaultLifecycleExecutor.java:331)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegme
ts(DefaultLifecycleExecutor.java:292)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultL
fecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:301)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl
java:59)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcce
sorImpl.java:39)
at java.lang.reflect.Method.invoke(Method.java:612)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Mar 10 17:49:51 CET 2009
[INFO] Final Memory: 5M/1024M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.8, 2.0.9, 2.0.10

**Issue Links:**
- [MNG-3580](https://issues.apache.org/jira/browse/MNG-3580) FATAL ERROR and NPE on start
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

From the stack trace, this appears to be a duplicate of MNG-3580 which should be fixed with IBM JDK 1.6 SR2.
