### ISSUE TITLE
[MNG-4469] [regression] deploy:deploy-file fails with secured repository

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5683]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-4469](https://issues.apache.org/jira/browse/MNG-4469?redirect=false)** and commented

`deploy:deploy-file` or any other mojo that creates artifact repositories on its own will appear to ignore mirror, proxy and authentication infos from the settings when run with Maven 3.0. This is due to the `ArtifactRepositoryFactory` and the `WagonManager` being stateless and not injecting these infos any longer automatically.

---

**Affects:** 3.0-alpha-5

**Issue Links:**
- [MNG-4478](https://issues.apache.org/jira/browse/MNG-4478) deploy plugin altDeploymentRepository does not use authorization credentials
 (_**"is duplicated by"**_)
- [MNG-4571](https://issues.apache.org/jira/browse/MNG-4571) mvn deploy -DaltDeploymentRepository errors out

- [MNG-4574](https://issues.apache.org/jira/browse/MNG-4574) [regression] invoker:install uses wrong local repo path when settings.xml contains wildcard mirror

3 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Anders, would you describe is a duplicate of MNG-4571.

**Comment by jira-importer** [comment]
**[Sarath PS](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sarath)** commented

Looks like it is still an issue. I get this when trying to upload to nexus
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact serra:serra-we:jar:1.10-20101006.213417-2 from snapshots (http://serra.we/nexus/content/repositories/snapshots, releases=true, snapshots=true, managed=false): Error transferring file
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:860)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:851)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.flush(WagonRepositoryConnector.java:775)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:389)
at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:223)
... 24 more
Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.finishPutTransfer(LightweightHttpWagon.java:213)
at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:413)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:392)
at org.apache.maven.wagon.AbstractWagon.putTransfer(AbstractWagon.java:365)
at org.apache.maven.wagon.StreamWagon.put(StreamWagon.java:163)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:736)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:388)
... 25 more
Caused by: java.io.IOException: Error writing to server
at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:468)
at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:480)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1070)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:373)
at org.apache.maven.wagon.providers.http.LightweightHttpWagon.finishPutTransfer(LightweightHttpWagon.java:185)
... 31 more
