### ISSUE TITLE
[MNG-4454] Incomplete <parent> element causes NPE

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5712]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-4454](https://issues.apache.org/jira/browse/MNG-4454?redirect=false)** and commented

A POM with

```xml
<parent>
</parent>
```

will produce a NPE instead of the proper validation messages about missing parent info.

```
Caused by: java.lang.NullPointerException
        at org.apache.maven.model.validation.DefaultModelValidator.validateRawModel(DefaultModelValidator.java:69)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:345)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:132)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:116)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:323)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:277)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:397)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:346)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:169)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:102)
```

---

**Affects:** 3.0-alpha-4

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r881784](http://svn.apache.org/viewvc?view=revision&revision=881784).
