### ISSUE TITLE
[MNG-4035] Cannot find setter nor field in org.apache.maven.plugin.plugin.metadata.AddPluginArtifactMetadataMojo for 'extractors'

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5716]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** opened **[MNG-4035](https://issues.apache.org/jira/browse/MNG-4035?redirect=false)** and commented

I am trying to build tycho [1] using maven 3.0 from trunk as of today. The build fails with the following exception

```
[ERROR] 
org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter nor field in org.apache.maven.plugin.plugin.metadata.AddPluginArtifactMetadataMojo for 'extractors'

While building project with id: org.codehaus.tycho:maven-osgi-compiler-plugin:maven-plugin:0.3.0-SNAPSHOT
Project File: /workspaces/tycho-dev/tycho/maven-osgi-compiler-plugin/pom.xml

Error stacktrace:
org.apache.maven.lifecycle.LifecycleExecutionException: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter nor field in org.apache.maven.plugin.plugin.metadata.AddPluginArtifactMetadataMojo for 'extractors'
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:527)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:258)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:200)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:163)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:207)
	at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:881)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:167)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: org.apache.maven.plugin.PluginConfigurationException: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter nor field in org.apache.maven.plugin.plugin.metadata.AddPluginArtifactMetadataMojo for 'extractors'
	at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1074)
	at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:880)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:584)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:491)
	... 15 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter nor field in org.apache.maven.plugin.plugin.metadata.AddPluginArtifactMetadataMojo for 'extractors'
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.<init>(ComponentValueSetter.java:85)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:138)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:58)
	at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1068)
	... 18 more

```

I am using the following command to build tycho

/tmp/apache-maven-3.0-SNAPSHOT/bin/mvn -e install

[1] http://svn.sonatype.org/m2eclipse/tycho/trunk

---

**Affects:** 3.0-alpha-3

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

I reverted out the recent plugin manager changes that used mixins. This fixes this problem.
