### ISSUE TITLE
[MNG-4426] Some javac errors not shown in console when error stacktraces are turned on

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5722]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul4christ79)** opened **[MNG-4426](https://issues.apache.org/jira/browse/MNG-4426?redirect=false)** and commented

This only occurs when -e option is specified. When my build failure happened, this was the output:

[ERROR] [0]
org.apache.maven.plugin.CompilationFailureException: Compilation failure
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:547)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:233)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:102)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:421)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:156)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [0] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Is this a feature or a bug? I thought it was the latter. Without the option, the compiling errors are again printed.

---

**Affects:** 3.0-alpha-3

**Attachments:**
- [MNG-4426.zip](https://issues.apache.org/jira/secure/attachment/12712728/MNG-4426.zip) (_1.61 kB_)
- [MNG-4426.zip](https://issues.apache.org/jira/secure/attachment/12713008/MNG-4426.zip) (_2.14 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

I couldn't reproduce this, the attached demo project outputs

```
[ERROR] [0]
org.apache.maven.plugin.CompilationFailureException: Compilation failure
M:\MNG-4426\src\main\java\Main.java:[3,20] ';' expected


	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
```

upon "mvn compile".
