### ISSUE TITLE
[MNG-4443] gwt-maven-plugin + gwt-2.0.0-ms2: GWTCompiler failed -> [Help 1]

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5731]
**[Tiago Fernandez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tiago182)** opened **[MNG-4443](https://issues.apache.org/jira/browse/MNG-4443?redirect=false)** and commented

I am used to build my GWT app (http://github.com/tiagofernandez/bazooka) with Maven 2.x without any problem, but when I try a clean packaging with Maven 3.0-alpha-3 I get the following error:

[ERROR] GWTCompiler failed -> [Help 1]
org.apache.maven.plugin.MojoExecutionException: GWTCompiler failed
at org.codehaus.mojo.gwt.CompileMojo.compile(CompileMojo.java:136)
at org.codehaus.mojo.gwt.CompileMojo.execute(CompileMojo.java:99)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:547)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:239)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:102)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:421)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:156)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:592)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
[ERROR]

I have attached the build.log with debug logs and exception traces and the pom.xml I'm using.

If you need more details, feel free to ask me. Thanks.

---

**Affects:** 3.0-alpha-3

**Attachments:**
- [build.log](https://issues.apache.org/jira/secure/attachment/12712127/build.log) (_205.78 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712580/pom.xml) (_6.78 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Could you also attach the debug log of a successful build by Maven 2.x? The missing plugin versions in your build make it otherwise hard to locate actual differences.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

as I can see there are some gwt compilation issue. As gwt-2.0.0-ms2 is not in central repo it's difficult to test your project. Does it works with ms1 ?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

I managed to reproduce the compilation failure when using gwt-maven-plugin:1.0 with both Maven 2.2.1 and Maven 3.0-alpha-3. The project builds fine as soon as the gwt-maven-plugin is locked down to version 1.1, again with both Maven 2.2.1 and 3.0-alpha-3. So it's just a matter of specifying the correct plugin version.

The difference between Maven 2 and 3 in case of a missing plugin version results from the current metadata for gwt-maven-plugin:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>gwt-maven-plugin</artifactId>
  <version>1.0</version>
  <versioning>
    <latest>1.1</latest>
    <release>1.0</release>
    <versions>
      <version>1.0</version>
      <version>1.1</version>
    </versions>
    <lastUpdated>20090618131729</lastUpdated>
  </versioning>
</metadata>
```

which lists latest=1.1 but release=1.0. Maven 3 intentionally prefers "release" over "latest". Given the version 1.1 of the plugin has neither sources nor javadoc, I guess the release manager did not use the Maven Release Plugin, thereby producing a bad plugin release.

**Comment by jira-importer** [comment]
**[Tiago Fernandez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tiago182)** commented

Indeed if I explicitly set gwt-maven-plugin to version 1.1 the build is successful. Thanks!
