### ISSUE TITLE
[MNG-4417] Exception using release:clean with Maven 3 snapshot

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5749]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** opened **[MNG-4417](https://issues.apache.org/jira/browse/MNG-4417?redirect=false)** and commented

Running mvn release:clean on my project, I get the following exception:

```
org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.shared.release.phase.ReleasePhase', it could not be started.
      role: org.apache.maven.shared.release.phase.ReleasePhase
  roleHint: map-release-versions
classRealm: plugin>org.apache.maven.plugins:maven-release-plugin:2.0-beta-8
        at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:373)
        at org.codehaus.plexus.DefaultComponentRegistry.lookup(DefaultComponentRegistry.java:184)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:399)
        at org.codehaus.plexus.component.collections.AbstractComponentCollection.lookup(AbstractComponentCollection.java:149)
        at org.codehaus.plexus.component.collections.ComponentMap.getComponentMap(ComponentMap.java:189)
        at org.codehaus.plexus.component.collections.ComponentMap.getMap(ComponentMap.java:148)
        at org.codehaus.plexus.component.collections.ComponentMap.get(ComponentMap.java:68)
        at org.apache.maven.shared.release.DefaultReleaseManager.clean(DefaultReleaseManager.java:443)
        at org.apache.maven.plugins.release.CleanReleaseMojo.execute(CleanReleaseMojo.java:48)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:547)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:224)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:97)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:453)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error constructing component
role: 'org.apache.maven.shared.release.phase.ReleasePhase', implementation: 'org.apache.maven.shared.release.phase.MapVersionsPhase', role hint: 'map-release-versions'
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:178)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.build(XBeanComponentBuilder.java:123)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:181)
        at org.codehaus.plexus.component.manager.SingletonComponentManager.getComponent(SingletonComponentManager.java:67)
        at org.codehaus.plexus.DefaultComponentRegistry.getComponent(DefaultComponentRegistry.java:358)
        ... 23 more
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/components/interactivity/PrompterException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
        at java.lang.Class.getConstructors(Class.java:1459)
        at org.apache.xbean.recipe.ReflectionUtil.findConstructor(ReflectionUtil.java:527)
        at org.apache.xbean.recipe.ObjectRecipe.findFactory(ObjectRecipe.java:532)
        at org.apache.xbean.recipe.ObjectRecipe.internalCreate(ObjectRecipe.java:270)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:96)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:61)
        at org.apache.xbean.recipe.AbstractRecipe.create(AbstractRecipe.java:49)
        at org.codehaus.plexus.component.builder.XBeanComponentBuilder.createComponentInstance(XBeanComponentBuilder.java:159)
        ... 27 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.components.interactivity.PrompterException
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
        ... 37 more
[DEBUG] Failed to lookup a member of active collection with role: org.apache.maven.shared.release.phase.ReleasePhase and
 role-hint: map-branch-versions
```

and at the end

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.265s
[INFO] Finished at: Fri Oct 30 14:35:38 CET 2009
[INFO] Final Memory: 5M/14M
[INFO] ------------------------------------------------------------------------
[ERROR] [0]
org.apache.maven.plugin.PluginExecutionException: : : null
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:119)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:547)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:224)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:97)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:453)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:105)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: : null
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:114)
        ... 14 more
Caused by: java.lang.NullPointerException
        at org.apache.maven.shared.release.DefaultReleaseManager.clean(DefaultReleaseManager.java:445)
        at org.apache.maven.plugins.release.CleanReleaseMojo.execute(CleanReleaseMojo.java:48)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
        ... 14 more
```

Please tell me if this error should be reported to release plugin instead. As it works fine with Maven2 I suppose it is a regression.

---

**Affects:** Issues to be reviewed for 4.x

**Attachments:**
- [MNG-4417.zip](https://issues.apache.org/jira/secure/attachment/12711777/MNG-4417.zip) (_846 bytes_)

**Comment by jira-importer** [comment]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** commented

Hi Benjamin,

I can send you the pom file to reproduce the first issue. But I prefer to not upload publicly because it is from my organisation.

What is your email adress?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

We privately confirmed it was a broken JAR in the local repository that corrupted the class path of the plugin.
