### ISSUE TITLE
[MNG-4086] [regression] Explicitly using plugin metaversions crashes plugin manager

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5783]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-4086](https://issues.apache.org/jira/browse/MNG-4086?redirect=false)** and commented

Invoking

```
mvn org.apache.maven.plugins:maven-clean-plugin:LATEST:clean
```

dies with

```
java.lang.IllegalStateException: The plugin descriptor for the plugin Plugin [org.apache.maven.plugins:maven-clean-plugin] was not found.
Please verify that the plugin JAR U:\Jeder\Maven-2\org\apache\maven\plugins\maven-clean-plugin\2.3\maven-clean-plugin-2.3.jar is intact.
        at org.apache.maven.plugin.DefaultPluginManager.addPlugin(DefaultPluginManager.java:328)
        at org.apache.maven.plugin.DefaultPluginManager.verifyVersionedPlugin(DefaultPluginManager.java:213)
        at org.apache.maven.plugin.DefaultPluginManager.verifyPlugin(DefaultPluginManager.java:175)
```

While users usually won't need to explicitly use RELEASE or LATEST, plugin developers do occasionally for testing.

---

**Affects:** 2.1.0

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r754667](http://svn.eu.apache.org/viewvc?view=rev&revision=754667) and [r754668](http://svn.eu.apache.org/viewvc?view=rev&revision=754668), respectively.
