### ISSUE TITLE
[MNG-4358] Multi-projects seem to send interrupt signals to some tasks

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5791]
**[Gustavo Hexsel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=quartz)** opened **[MNG-4358](https://issues.apache.org/jira/browse/MNG-4358?redirect=false)** and commented

Tasks like exec:exec and surefire (testing) seem to receive an occasional interrupt signal, causing the test or task to fail.  This only happens on multi-module projects (i.e. if I run it a module at a time, it works).

Here's an example stacktrace from exec:exec (I can try to reproduce the surefire one as well):

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Command execution failed.

Embedded error: Error while executing external command, process killed.
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Command execution failed.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:584)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:500)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:479)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:331)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:292)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:301)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution failed.
at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:288)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:453)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
... 16 more
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error while executing external command, process killed.
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:199)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:93)
at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:437)
at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:279)
... 18 more
Caused by: java.lang.InterruptedException
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at java.lang.UNIXProcess.waitFor(UNIXProcess.java:181)
at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:147)
... 21 more

---

**Affects:** 2.2.1

**Attachments:**
- [interrupt_on_resolve.tar.bz](https://issues.apache.org/jira/secure/attachment/12712957/interrupt_on_resolve.tar.bz) (_87.30 kB_)
- [out.tar.bz](https://issues.apache.org/jira/secure/attachment/12712958/out.tar.bz) (_197.42 kB_)

**Comment by jira-importer** [comment]
**[Gustavo Hexsel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=quartz)** commented

This is the full output of "mvn clean install -X"

**Comment by jira-importer** [comment]
**[Gustavo Hexsel](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=quartz)** commented

Found it (I believe)!  The problem is that the behaviour of surefire "parallel mode" causes interruptions in threads that are not directly related to testing (and to tests too, causing tests that have Thread.sleep() tests to fail randomly).

Please mark it as invalid, delete, or just reassign to surefire (I don't have the rights to any of these actions)!

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
