### ISSUE TITLE
[MNG-4063] Component descriptor cannot be found in the component repository: org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-javadoc-plugin:2.4:jar.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5848]
**[Martin Vysny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m.vysny)** opened **[MNG-4063](https://issues.apache.org/jira/browse/MNG-4063?redirect=false)** and commented

When I try to build a project against a completely clean local .m2 repository with Nexus cache the build fails with this exception. I have to run it again to remove the exception.

[INFO] ------------------------------------------------------------------------
[INFO] Building LSABPM: Escrow complete package
[INFO] ------------------------------------------------------------------------
[INFO] No goals needed for project - skipping
[INFO] Preparing javadoc:test-javadoc
[INFO] No goals needed for project - skipping
[INFO] Preparing cobertura:cobertura
[INFO] [cobertura:instrument]
[INFO] Not executing cobertura:instrument as the project is not a Java classpath-capable package
[INFO] Preparing findbugs:findbugs
[INFO] No goals needed for project - skipping
[INFO] Preparing surefire-report:report
[INFO] No goals needed for project - skipping
Downloading: http://magi.dynip:8081/nexus/content/repositories/central/org/apache/maven/wagon/wagon-file/1.0-alpha-5/wagon-file-1.0-alpha-5.jar
4/5K
5/5K
5K downloaded
Downloading: http://magi.dynip:8081/nexus/content/repositories/central/org/apache/maven/wagon/wagon-http-lightweight/1.0-alpha-5/wagon-http-lightweight-1.0-alpha-5.jar
4/7K
7/7K
7K downloaded
Downloading: http://magi.dynip:8081/nexus/content/repositories/central/org/apache/maven/wagon/wagon-ssh/1.0-alpha-5/wagon-ssh-1.0-alpha-5.jar
4/32K
8/32K
12/32K
16/32K
20/32K
24/32K
28/32K
32/32K
32/32K
32K downloaded
Downloading: http://magi.dynip:8081/nexus/content/repositories/central/com/jcraft/jsch/0.1.23/jsch-0.1.23.jar
4/113K
8/113K
12/113K
16/113K
20/113K
24/113K
28/113K
32/113K
36/113K
40/113K
44/113K
48/113K
52/113K
56/113K
60/113K
64/113K
68/113K
72/113K
76/113K
80/113K
84/113K
88/113K
92/113K
96/113K
100/113K
104/113K
108/113K
112/113K
113/113K
113K downloaded
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
[INFO] [site:site {execution: assembly-site}]
[ERROR] The Trac Report only supports Trac.  No Trac Report will be generated.
[ERROR] The JIRA Report only supports JIRA.  No JIRA Report will be generated.
[INFO] Not executing cobertura:report as the cobertura data file (/home/sdktest/lsabpm-escrow/lsabpm-src/lsabpm-escrow/lsabpm-escrow-all/target/cobertura/cobertura.ser) could not be found
[WARNING] Error loading report org.apache.maven.plugin.jxr.JxrReport - AbstractMethodError: canGenerateReport()
[WARNING] Error loading report org.codehaus.mojo.surefire.SurefireReportMojo - AbstractMethodError: canGenerateReport()
[WARNING] Unable to load parent project from repository: Could not find the model file '/home/sdktest/lsabpm-escrow/lsabpm-src/../pom.xml'. for project unknown
Downloading: http://magi.dynip:8081/nexus/content/repositories/central/com/whitestein/lsabpm/lsabpm-parent/1.30/lsabpm-parent-1.30-site_en.xml
Downloading: http://magi.dynip:8081/nexus/content/repositories/central/com/whitestein/lsabpm/lsabpm-parent/1.30/lsabpm-parent-1.30-site.xml
[INFO] artifact org.apache.maven.skins:maven-default-skin: checking for updates from central
Downloading: http://magi.dynip:8081/nexus/content/repositories/central/org/apache/maven/skins/maven-default-skin/1.0/maven-default-skin-1.0.jar
4/7K
7/7K
7K downloaded
[INFO] Generate "PMD Report" report.
[ERROR] VM #displayTree: error : too few arguments to macro. Wanted 2 got 0
[ERROR] VM #menuItem: error : too few arguments to macro. Wanted 1 got 0
[INFO] Generate "CPD Report" report.
[INFO] Generate "Dependencies" report.
[INFO] Generate "Dependency Convergence" report.
[INFO] Generate "Issue Tracking" report.
[INFO] Generate "Project License" report.
[INFO] Generate "Mailing Lists" report.
[INFO] Generate "About" report.
[INFO] Generate "Source Repository" report.
[INFO] Generate "Project Team" report.
[INFO] Generate "Source Xref" report.
[INFO] Generate "Maven Surefire Report" report.
[INFO] [source:jar {execution: default}]
[INFO] NOT adding java-sources to attached artifacts for packaging: 'pom'.
[INFO] [dependency:unpack {execution: module-javadoc-prepare}]
[INFO] Configured Artifact: com.whitestein.resources:whitestein-resources:1.0:jar
[INFO] Expanding: /home/sdktest/.m2/repository/com/whitestein/resources/whitestein-resources/1.0/whitestein-resources-1.0.jar into /home/sdktest/lsabpm-escrow/lsabpm-src/lsabpm-escrow/lsabpm-escrow-all/target/whitestein-resources
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-javadoc-plugin:2.4:jar': Unable to find the mojo 'org.apache.maven.plugins:maven-javadoc-plugin:2.4:jar' in the plugin 'org.apache.maven.plugins:maven-javadoc-plugin'
Component descriptor cannot be found in the component repository: org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-javadoc-plugin:2.4:jar.
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-javadoc-plugin:2.4:jar': Unable to find the mojo 'org.apache.maven.plugins:maven-javadoc-plugin:2.4:jar' in the plugin 'org.apache.maven.plugins:maven-javadoc-plugin'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:562)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-javadoc-plugin:2.4:jar' in the plugin 'org.apache.maven.plugins:maven-javadoc-plugin'
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:618)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:429)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
... 16 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository: org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-javadoc-plugin:2.4:jar.
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:312)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:609)
... 18 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10 minutes 50 seconds
[INFO] Finished at: Wed Mar 04 10:56:30 GMT+01:00 2009
[INFO] Final Memory: 238M/489M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.9

3 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

What command/goals were you running? From your second sentence I take it this is fully reproducible? Also, after the first build, i.e. the one that failed with the exception, can you verify the JAR for the Javadoc Plugin in your local repository is complete/intact?.

**Comment by jira-importer** [comment]
**[Martin Vysny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m.vysny)** commented

Thanks! It is a simple mvn clean install -e command. Yes, it is fully reproducible - just delete the .m2/repository and try mvn clean install -e . I'll try to create a small maven project which will fail similarly. I checked the maven-javadoc-plugin jar/pom and it is exactly the same as the one on ibiblio: http://mirrors.ibiblio.org/pub/mirrors/maven2/org/apache/maven/plugins/maven-javadoc-plugin/2.4/

**Comment by jira-importer** [comment]
**[Martin Vysny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=m.vysny)** commented

Hmm, I had this strange construct in my pom.xml/project/build/plugins:
\<plugin>
\<artifactId>maven-site-plugin\</artifactId>
\<executions>
\<execution>
\<id>assembly-site\</id>

\

\<phase>package\</phase>
\<goals>
\<goal>site\</goal>
\</goals>
\</execution>
\</executions>
\</plugin>

After I removed it, the build succeeded. Probably attaching site:site to package is not a good idea :)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

running site in the package cycle should work (but not a good idea, correct).

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I'm not able to reproduce with a configuration - were you able to come up with a simple test project?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

If no test project, a full debug log would be helpful.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
