### ISSUE TITLE
[MNG-4286] Possible race condition in DefaultWagonManagerTest.testGetWagonMultithreaded()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5870]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** opened **[MNG-4286](https://issues.apache.org/jira/browse/MNG-4286?redirect=false)** and commented

Periodically (especially when I'm trying to stage a release, but that may just be Maven's sense of humor) I'm seeing test failures that seem to be due to a race condition in the tearDown() functionality of DefaultWagonManagerTest.testGetWagonMultithreaded():

```
-------------------------------------------------------------------------------
Test set: org.apache.maven.artifact.manager.DefaultWagonManagerTest
-------------------------------------------------------------------------------
Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.817 sec <<< FAILURE!
testGetWagonMultithreaded(org.apache.maven.artifact.manager.DefaultWagonManagerTest)  Time elapsed: 0.338 sec  <<< ERROR!
java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:844)
	at java.util.HashMap$ValueIterator.next(HashMap.java:871)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:176)
	at java.util.ArrayList.<init>(ArrayList.java:136)
	at org.codehaus.plexus.DefaultPlexusContainer.disposeAllComponents(DefaultPlexusContainer.java:828)
	at org.codehaus.plexus.DefaultPlexusContainer.dispose(DefaultPlexusContainer.java:803)
	at org.codehaus.plexus.PlexusTestCase.tearDown(PlexusTestCase.java:160)
	at junit.framework.TestCase.runBare(TestCase.java:130)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at junit.framework.TestSuite.runTest(TestSuite.java:208)
	at junit.framework.TestSuite.run(TestSuite.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:213)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:138)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:125)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:290)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:818)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:818)
```

---

**Affects:** 2.2.1

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
