### ISSUE TITLE
[MNG-4266] Missing method ArtifactUtils.isSnapshot used in the release plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5886]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** opened **[MNG-4266](https://issues.apache.org/jira/browse/MNG-4266?redirect=false)** and commented

Testing current trunk with the release plugin :

```
constituent[20]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/commons-cli-1.2.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.artifact.ArtifactUtils.isSnapshot(Ljava/lang/String;)Z
        at org.apache.maven.plugins.release.phase.CheckPomPhase.execute(CheckPomPhase.java:93)
        at org.apache.maven.plugins.release.phase.CheckPomPhase.simulate(CheckPomPhase.java:105)
        at org.apache.maven.plugins.release.DefaultReleaseManager.prepare(DefaultReleaseManager.java:135)
        at org.apache.maven.plugins.release.PrepareReleaseMojo.execute(PrepareReleaseMojo.java:106)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:324)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:264)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:198)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:180)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:467)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:163)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
bash-3.00$ mvn -v
Apache Maven 3.0-SNAPSHOT (r799084; 2009-07-29 23:31:35+0200)
Java version: 1.6.0_14
Java home: /local/tomcat/shared/jdk1.6.0_14/jre
Default locale: en, platform encoding: ISO646-US
OS name: "sunos" version: "5.10" arch: "sparc" Family: "unix"
```

---

**Affects:** 3.0-alpha-3

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r799225](http://svn.apache.org/viewvc?view=rev&revision=799225).
