### ISSUE TITLE
[MNG-4243] maven build failuer in hudson

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5926]
**[SungHoon Ahn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gidionexp)** opened **[MNG-4243](https://issues.apache.org/jira/browse/MNG-4243?redirect=false)** and commented

Hi everyone - I'm a Maven newbie and need some help.
We are using Hudson to build some Maven Project in SVN use maven
In Local it has absolutely no problems to build
But when I build with Hudson, it makes compilation failure like this

<-- compilation failure -->
tframe.common.exception.TFrameException:[3,43] The import tframe.common.aop.TFrameXMLAdvice is never used

tframe.core.dao.IBatisAbstractDao:[5,72] The import org.springframework.orm.ibatis.SqlMapClientFactoryBean is never used

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: Compilation failure
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:699)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:181)
at org.apache.maven.lifecycle.LifecycleExecutorInterceptor.execute(LifecycleExecutorInterceptor.java:65)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at hudson.maven.agent.Main.launch(Main.java:165)
at hudson.maven.MavenBuilder.call(MavenBuilder.java:159)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:601)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:547)
at hudson.remoting.UserRequest.perform(UserRequest.java:103)
at hudson.remoting.UserRequest.perform(UserRequest.java:47)
at hudson.remoting.Request$2.run(Request.java:236)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:516)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:483)
at hudson.maven.agent.PluginManagerInterceptor.executeMojo(PluginManagerInterceptor.java:182)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:678)
... 28 more

this errors what maven say is not errors it's just a warining.
So I try to find solution about this, but there is a comment about this.
It says This is kind of a bug. Hudson thinks it's errors not warnings.

Anyway Somebody who knows solution about this, please let me know

I'm not English-speaking peoples so it may difficult to understand...
Anyway thanks.

---

**Affects:** 2.1.0

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Please use the [user mailing list](http://maven.apache.org/mail-lists.html) for questions. If a direct CLI invotion of Maven works, this could as well be a Hudson problem, hard to tell from the few pieces of information you provided.
