### ISSUE TITLE
[MNG-4239] NoSuchMethodError org.apache.maven.project.inheritance.ModelInheritanceAssembler.assembleModelInheritance(Lorg/apache/maven/model/Model;Lorg/apache/maven/model/Model;)V

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5931]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** opened **[MNG-4239](https://issues.apache.org/jira/browse/MNG-4239?redirect=false)** and commented

From m2eclipse-user mailing list http://www.nabble.com/m2eclipse-0.9.9-dev-problems-with-Apache-ServiceMix-component-projects-such-as-servicemix-camel-td24475825.html#a24475825

> I receive the following errors in my eclipse log attempting to use m2eclipse
> 0.9.9-dev with project
> https://svn.apache.org/repos/asf/servicemix/components/engines/servicemix-camel/trunk.
> I have tried using the embedded Maven runtime as well as the external Maven
> 2.2.0 release with no success.
> 
> Thoughts?
> 
> !ENTRY org.eclipse.core.resources 2 566 2009-07-14 04:17:22.357
> !MESSAGE Errors during build.
> !SUBENTRY 1 org.maven.ide.eclipse 2 75 2009-07-14 04:17:22.357
> !MESSAGE Errors running builder 'Maven Project Builder' on project
> 'servicemix-camel'.
> !SUBENTRY 1 org.maven.ide.eclipse 2 75 2009-07-14 04:17:22.357
> !MESSAGE
> org.apache.maven.project.inheritance.ModelInheritanceAssembler.assembleModelInheritance(Lorg/apache/maven/model/Model;Lorg/apache/maven/model/Model;)V
> !STACK 0
> java.lang.NoSuchMethodError:
> org.apache.maven.project.inheritance.ModelInheritanceAssembler.assembleModelInheritance(Lorg/apache/maven/model/Model;Lorg/apache/maven/model/Model;)V
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.mergeModels(ProcessRemoteResourcesMojo.java:903)
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.getProjects(ProcessRemoteResourcesMojo.java:520)
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.configureVelocityContext(ProcessRemoteResourcesMojo.java:665)
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.execute(ProcessRemoteResourcesMojo.java:413)
> at
> org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:322)
> at
> org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:206)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:182)
> at
> org.maven.ide.eclipse.internal.embedder.MavenImpl.execute(MavenImpl.java:164)
> at
> org.maven.ide.eclipse.internal.project.DefaultBuildParticipant.executePostBuild(DefaultBuildParticipant.java:138)
> at
> org.maven.ide.eclipse.internal.project.DefaultBuildParticipant.build(DefaultBuildParticipant.java:77)
> at
> org.maven.ide.eclipse.internal.builder.MavenBuilder.build(MavenBuilder.java:125)
> at
> org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:633)
> at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
> at
> org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:170)
> at
> org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:201)
> at
> org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:253)
> at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:37)
> at
> org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:256)
> at
> org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:218)
> at
> org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:360)
> at
> org.eclipse.core.internal.resources.Project.internalBuild(Project.java:516)
> at org.eclipse.core.internal.resources.Project.build(Project.java:94)
> at
> org.eclipse.jdt.internal.ui.util.CoreUtility$BuildJob.run(CoreUtility.java:160)
> at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
> 
> !ENTRY org.eclipse.core.jobs 4 2 2009-07-14 04:25:09.719
> !MESSAGE An internal error occurred during: "Updating Maven Configuration".
> !STACK 0
> java.lang.NoSuchMethodError:
> org.apache.maven.project.inheritance.ModelInheritanceAssembler.assembleModelInheritance(Lorg/apache/maven/model/Model;Lorg/apache/maven/model/Model;)V
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.mergeModels(ProcessRemoteResourcesMojo.java:903)
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.getProjects(ProcessRemoteResourcesMojo.java:520)
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.configureVelocityContext(ProcessRemoteResourcesMojo.java:665)
> at
> org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.execute(ProcessRemoteResourcesMojo.java:413)
> at
> org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:322)
> at
> org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:206)
> at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:182)
> at
> org.maven.ide.eclipse.internal.embedder.MavenImpl.execute(MavenImpl.java:164)
> at
> org.maven.ide.eclipse.jdt.internal.GenericJavaProjectConfigurator.getMavenProjects(GenericJavaProjectConfigurator.java:73)
> at
> org.maven.ide.eclipse.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:86)
> at
> org.maven.ide.eclipse.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:53)
> at
> org.maven.ide.eclipse.internal.project.GenericLifecycleMapping.configure(GenericLifecycleMapping.java:48)
> at
> org.maven.ide.eclipse.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:313)
> at
> org.maven.ide.eclipse.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:299)
> at
> org.maven.ide.eclipse.actions.UpdateSourcesAction$1.runInWorkspace(UpdateSourcesAction.java:81)
> at
> org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
> at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

---

**Affects:** 3.0-alpha-3

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Restored API in [r793910](http://svn.apache.org/viewvc?view=rev&revision=793910).
