### ISSUE TITLE
[MNG-4034] [regression] dependency version is not inherited from parent dependencyManagement

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5938]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** opened **[MNG-4034](https://issues.apache.org/jira/browse/MNG-4034?redirect=false)** and commented

Dependency version is missing for dependencies defined inside a profile and actual version provided in dependencyManagement section of the parent pom. I will attach sample (effective) pom shortly.

---

**Affects:** 3.0-alpha-1

**Attachments:**
- [effpom.xml](https://issues.apache.org/jira/secure/attachment/12712833/effpom.xml) (_24.37 kB_)
- [mng4034.zip](https://issues.apache.org/jira/secure/attachment/12712834/mng4034.zip) (_1.87 kB_)

**Issue Links:**
- [MNG-3957](https://issues.apache.org/jira/browse/MNG-3957) [regression] For artifact {stax:stax-api:null:jar}: The version cannot be empty.
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** commented

sample effective pom

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

This occurs because the building sequence is: 1) inheritance; 2) dependency management; 3) profiles. Since the profile contains the dependency, it is joined in after dependency management rules and thus does not contain the version. I'll re-work ordering.

**Comment by jira-importer** [comment]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** commented

Still see the problem using maven 3.0 trunk rev  745288. I will attach sample project in a moment.

**Comment by jira-importer** [comment]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** commented

Steps to reproduce the problem.

1. Unzip attached mng4034.zip
2. cd  mng4034/module
3. mvn -X -Pupdate-dependencies help:effective-pom

The above command fails with maven 3.0 with the following message

```
igor@desktop:/workspaces/tycho-dev/mng4034/module$ /tmp/apache-maven-3.0-SNAPSHOT/bin/mvn -X -Pupdate-dependencies help:effective-pom 
+ Error stacktraces are turned on.
Maven version: 3.0-SNAPSHOT built on unknown
Java version: 1.6.0_10
Java home: /opt/jdk1.6.0_10/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux" version: "2.6.27-11-generic" arch: "amd64" family: "unix"
[DEBUG] Checking for external profiles in: /workspaces/tycho-dev/mng4034/module/profiles.xml
[DEBUG] 'dependencies.dependency.version' is missing for org.apache.maven:maven-embedder
[ERROR] 
Failed to build MavenProject instance for: /workspaces/tycho-dev/mng4034/module/pom.xml


POM File: /workspaces/tycho-dev/mng4034/module/pom.xml


Error stacktrace:
org.apache.maven.reactor.MavenExecutionException: Failed to build MavenProject instance for: /workspaces/tycho-dev/mng4034/module/pom.xml
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:286)
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:252)
	at org.apache.maven.DefaultMaven.createReactorManager(DefaultMaven.java:97)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:151)
	at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:867)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:167)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: org.apache.maven.project.InvalidProjectModelException: Failed to validate POM for project org.maven.ide.components:module at /workspaces/tycho-dev/mng4034/module/pom.xml
	at org.apache.maven.project.DefaultMavenProjectBuilder.validateModel(DefaultMavenProjectBuilder.java:437)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildWithProfiles(DefaultMavenProjectBuilder.java:337)
	at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:147)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:282)
	... 14 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILED
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Feb 17 18:23:59 EST 2009
[INFO] Final Memory: 3M/112M
[INFO] ------------------------------------------------------------------------
```

Expected effective pom is produced with maven 2.1.0M1
