### ISSUE TITLE
[MNG-4202] Unable to resolve ${env.HOSTNAME}

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5940]
**[Pete de Zwart](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dezwart)** opened **[MNG-4202](https://issues.apache.org/jira/browse/MNG-4202?redirect=false)** and commented

Empirical test. Using the following POM, you will be able to resolve the environment variable `$FOO`:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <packaging>pom</packaging>
    <version>1.1-SNAPSHOT</version>

    <modules>
	<module>${env.FOO}</module>
    </modules>
</project>
```

If we then assign the value `BAR` to `$FOO`, we can observer that the environment has been set in the shell:

```
pdzwart@Fosters:/tmp[18:57:46](1,0)$ export FOO=BAR
pdzwart@Fosters:/tmp[18:58:48](1,0)$ echo $FOO
BAR
```

Now, running `mvn clean` using this POM, we expect that an exception will be thrown regarding `$PWD/BAR` not existing:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: unknown

Reason: Could not find the model file '/private/tmp/BAR'. for project unknown


[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Could not find the model file '/private/tmp/BAR'. for project unknown
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:432)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:300)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Could not find the model file '/private/tmp/BAR'. for project unknown
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1585)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:506)
	at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:200)
	at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:632)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:515)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:588)
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:419)
	... 11 more
Caused by: java.io.FileNotFoundException: /private/tmp/BAR (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:106)
	at hidden.org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
	at hidden.org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
	at hidden.org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:113)
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1580)
	... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Jun 16 18:59:37 EST 2009
[INFO] Final Memory: 1M/3M
[INFO] ------------------------------------------------------------------------
```

Excellent. Now, try this with `$env.HOSTNAME`, here is the POM:

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <packaging>pom</packaging>
    <version>1.1-SNAPSHOT</version>

    <modules>
	<module>${env.HOSTNAME}</module>
    </modules>
</project>
```

Here is what is currently assigned to `$HOSTNAME`:

```
pdzwart@Fosters:/tmp[19:00:10](1,0)$ echo $HOSTNAME
Fosters.sydney.atlassian.com
```

No, run maven again, and we expect that the directory `$PWD/Fosters.sydney.atlassian.com` does not exist:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: unknown

Reason: Could not find the model file '/private/tmp/${env.HOSTNAME}'. for project unknown


[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Could not find the model file '/private/tmp/${env.HOSTNAME}'. for project unknown
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:432)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:300)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Could not find the model file '/private/tmp/${env.HOSTNAME}'. for project unknown
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1585)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:506)
	at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:200)
	at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:632)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:515)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:588)
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:419)
	... 11 more
Caused by: java.io.FileNotFoundException: /private/tmp/${env.HOSTNAME} (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:106)
	at hidden.org.codehaus.plexus.util.xml.XmlReader.<init>(XmlReader.java:124)
	at hidden.org.codehaus.plexus.util.xml.XmlStreamReader.<init>(XmlStreamReader.java:67)
	at hidden.org.codehaus.plexus.util.ReaderFactory.newXmlReader(ReaderFactory.java:113)
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1580)
	... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Jun 16 19:01:25 EST 2009
[INFO] Final Memory: 1M/3M
[INFO] ------------------------------------------------------------------------
```

OOOOKKKAAAAY..... let's take a closer look at that shall we:

```
Reason: Could not find the model file '/private/tmp/${env.HOSTNAME}'. for project unknown
```

And closer:

```
'/private/tmp/${env.HOSTNAME}'
```

Some extra special magic is going on there; I suspect that this specific environment variable is being filtered out for some reason. So, let's try the following:
* `${env.HOSTNAM`}

```
 pdzwart@Fosters:/tmp[19:06:53](1,146)$ cat pom.xml && HOSTNAM=$HOSTNAME mvn clean
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <packaging>pom</packaging>
    <version>1.1-SNAPSHOT</version>

    <modules>
	<module>${env.HOSTNAM}</module>
    </modules>
</project>
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: unknown

Reason: Could not find the model file '/private/tmp/Fosters.sydney.atlassian.com'. for project unknown
...
```

* `${env.HOSTNAMEE`}

```
pdzwart@Fosters:/tmp[19:07:31](1,146)$ cat pom.xml && HOSTNAMEE=$HOSTNAME mvn clean
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <packaging>pom</packaging>
    <version>1.1-SNAPSHOT</version>

    <modules>
	<module>${env.HOSTNAMEE}</module>
    </modules>
</project>
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: unknown

Reason: Could not find the model file '/private/tmp/Fosters.sydney.atlassian.com'. for project unknown
...
```

* `${env.HOSTNAMO`}

```
pdzwart@Fosters:/tmp[19:07:59](1,146)$ cat pom.xml && HOSTNAMO=$HOSTNAME mvn clean
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>test</artifactId>
    <packaging>pom</packaging>
    <version>1.1-SNAPSHOT</version>

    <modules>
	<module>${env.HOSTNAMO}</module>
    </modules>
</project>
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: unknown

Reason: Could not find the model file '/private/tmp/Fosters.sydney.atlassian.com'. for project unknown
```

Thanks for coming in today maven.

---

**Affects:** 2.0.9, 2.0.10, 2.1.0

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Pete de Zwart](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dezwart)** commented

Woo, no edit permissions.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

This is platform-specific issue: `$HOSTNAME` is an [internal variable of the shell](http://tldp.org/LDP/abs/html/internalvariables.html), it is not an environment variable (cf. the output of the `env` command or the `System.getenv()` method) and as such not available to Maven.

**Comment by jira-importer** [comment]
**[Pete de Zwart](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dezwart)** commented

```
pdzwart@fosters:~[09:44:29](0,0)$ env | grep HOSTNAME
HOSTNAME=fosters.sydney.atlassian.com
```

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Again, quoting http://www.bsdnewsletter.com/bsda-book/Recognize__44___view_and_modify_environmental_variables.html

> Most shells have their own internal variables, which should not be confused with global environment variables as they are not passed to newly started processes.
> And `HOSTNAME` is such an internal shell variable (cf. http://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#Bash-Variables). So the "extra special magic" you mention is your OS/shell, not Maven. Maven eventually invokes `System.getenv()`, what the JVM+OS don't provide here, isn't available for interpolation. So please fill any issue about HOSTNAME with the vendor of your JVM/OS, Maven isn't responsible for the underlying software stack it runs on.

Besides, a pristine shell yields this for me:

```
bbm:~ bentmann$ env | grep HOSTNAME
bbm:~ bentmann$ echo $HOSTNAME
bbm
```

and furthermore, the expression `${env.HOSTNAME`} gets available for interpolation of the POM as soon as I do

```
export HOSTNAME=$HOSTNAME
```
