### ISSUE TITLE
[MNG-4187] dependency:trunk doesn't work with mvn trunk rev 782332

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5957]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** opened **[MNG-4187](https://issues.apache.org/jira/browse/MNG-4187?redirect=false)** and commented

running dependency:tree failed with current trunk :

Logs :

```
bash-3.00$ mvn dependency:tree
[INFO] Build Order:
[INFO]
[INFO] Commontrunk api
[INFO]
[INFO] Building Commontrunk api
[INFO] Executing maven-dependency-plugin[2.1]: tree on commontrunk-api
---------------------------------------------------
constituent[0]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-embedder-3.0-SNAPSHOT.jar
constituent[1]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-model-3.0-SNAPSHOT.jar
constituent[2]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/plexus-utils-1.5.15.jar
constituent[3]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-core-3.0-SNAPSHOT.jar
constituent[4]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-compat-3.0-SNAPSHOT.jar
constituent[5]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-model-builder-3.0-SNAPSHOT.jar
constituent[6]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/plexus-interpolation-1.11.jar
constituent[7]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/plexus-component-annotations-1.0-beta-3.0.8-20090528.210709-1.jar
constituent[8]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/plexus-container-default-1.0-beta-3.0.8-20090528.210709-1.jar
constituent[9]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/xbean-reflect-3.4.jar
constituent[10]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/nekohtml-1.9.6.2.jar
constituent[11]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/google-collect-snapshot-20080530.jar
constituent[12]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/wagon-provider-api-1.0-beta-5.jar
constituent[13]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/wagon-file-1.0-beta-5.jar
constituent[14]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/wagon-http-lightweight-1.0-beta-5.jar
constituent[15]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/wagon-http-shared-1.0-beta-5.jar
constituent[16]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/xercesMinimal-1.9.6.2.jar
constituent[17]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-repository-3.0-SNAPSHOT.jar
constituent[18]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-plugin-api-3.0-SNAPSHOT.jar
constituent[19]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/plexus-sec-dispatcher-1.2.jar
constituent[20]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/plexus-cipher-1.1.jar
constituent[21]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/maven-toolchain-3.0-SNAPSHOT.jar
constituent[22]: file:/local/olamy/apache-maven-3.0-SNAPSHOT/lib/commons-cli-1.0.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.project.MavenProject.createArtifacts(Lorg/apache/maven/artifact/factory/ArtifactFactory;Ljava/lang/String;Lorg/apache/maven/artifact/resolver/filter/ArtifactFilter;)Ljava/util/Set;
        at org.apache.maven.shared.dependency.tree.DefaultDependencyTreeBuilder.buildDependencyTree(DefaultDependencyTreeBuilder.java:90)
        at org.apache.maven.plugin.dependency.TreeMojo.execute(TreeMojo.java:249)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:338)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:202)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:147)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:535)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:167)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)

```

---

**Affects:** 3.0-alpha-3

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

tested with rev 788115. And it looks to work now.
Thanks !
