### ISSUE TITLE
[MNG-4013] DuplicateArtifactAttachmentException On Building Test Jar

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5976]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** opened **[MNG-4013](https://issues.apache.org/jira/browse/MNG-4013?redirect=false)** and commented

I see this problem when building nexus-proxy. This is due to maven-jar-plugin

Caused by: org.apache.maven.project.DuplicateArtifactAttachmentException: Duplicate artifact attachment detected. (project: org.sonatype.nexus:nexus-proxy:jar:1.3.0-SNAPSHOT; illegal attachment: org.sonatype.nexus:nexus-proxy:jar:tests:1.3.0-SNAPSHOT)
at org.apache.maven.project.MavenProject.addAttachedArtifact(MavenProject.java:1440)
at org.apache.maven.project.DefaultMavenProjectHelper.attachArtifact(DefaultMavenProjectHelper.java:102)
at org.apache.maven.project.DefaultMavenProjectHelper.attachArtifact(DefaultMavenProjectHelper.java:70)
at org.apache.maven.plugin.jar.AbstractJarMojo.execute(AbstractJarMojo.java:179)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:629)

---

**Affects:** 3.0-alpha-2

**Issue Links:**
- [MNG-3119](https://issues.apache.org/jira/browse/MNG-3119) Duplicate attached artifacts should not be allowed.

**Comment by jira-importer** [comment]
**[Brian E. Fox (imported)](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brianf@infinity.nu)** commented

Seems to be ignoring the classifier during the comparison (illegal attachment is the tests jar)

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

Identical plugin executions are allowed in pom. This can cause failure in Maven 3 (since there is no longer cloning of maven project) on duplicate attached artifacts. Maven just logs warning, no longer throws exception.
