### ISSUE TITLE
[MNG-4012] Nexus Migration Project Fails to Build:  No such archiver: 'pom'.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#5977]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** opened **[MNG-4012](https://issues.apache.org/jira/browse/MNG-4012?redirect=false)** and commented

Nexus migration project fails to build:

Caused by: org.codehaus.plexus.archiver.manager.NoSuchArchiverException: No such archiver: 'pom'.
at org.codehaus.plexus.archiver.manager.DefaultArchiverManager.getResourceCollection(DefaultArchiverManager.java:90)
at org.codehaus.plexus.archiver.manager.DefaultArchiverManager.getResourceCollection(DefaultArchiverManager.java:128)
at org.codehaus.plexus.archiver.AbstractArchiver.asResourceCollection(AbstractArchiver.java:506)

---

**Affects:** 3.0-alpha-2

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

Checking effective pom, the order of the plugins is reversed in 3.x. This could be causing a problem.

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

The assembly plugin things thinks this is the location of the file-set, which is causing the failure:
3.0.x
[DEBUG] Adding archived file-set in: /Users/brittonisbell/.m2/repository/org/apache/maven/archetype/archetype-common/2.0-alpha-1/archetype-common-2.0-alpha-1.pom to archive location:
[ERROR]
Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-2:single': Mojo execution failed.

In 2.0.9:
DEBUG] Adding archived file-set in: /Users/brittonisbell/checkout/nexus/nexus/nexus-migration-tool/nexus-metadata-rebuild-tool/target/nexus-metadata-rebuild-tool-1.3.0-SNAPSHOT.jar to archive location:
[DEBUG] FileSet[target/classes] dir perms: 40755 file perms: 100644
[DEBUG] The archive base directory is 'null'
[DEBUG] Adding file-set from directory: '/Users/brittonisbell/checkout/nexus/nexus/nexus-migration-tool/nexus-metadata-rebuild-tool/target/classes'
assembly output directory is: 'target/classes/'
[DEBUG] Adding directory file-set in: /Users/brittonisbell/checkout/nexus/nexus/nexus-migration-tool/nexus-metadata-rebuild-tool/target/classes to archive location: target/classes/
[INFO] Building jar: /Users/brittonisbell/checkout/nexus/nexus/nexus-migration-tool/nexus-metadata-rebuild-tool/target/nexus-metadata-rebuild-tool-1.3.0-SNAPSHOT-cli.jar

**Comment by jira-importer** [comment]
**[Britton Isbell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sisbell)** commented

This was regression due to dependency exclusions not being added as a collection.
