### ISSUE TITLE
[MNG-3956] Maven unable to find the child modules

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6014]
**[Sanjay Kumar Patil](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanjay_patil@johnlewis.co.uk)** opened **[MNG-3956](https://issues.apache.org/jira/browse/MNG-3956?redirect=false)*** and commented

Hi, Please can you assist me here.

I am using Maven 2.0.9. I have created a parent project for one of my Java project and was trying to run mvn compile cmd from the parent level
but it fails.  This is what i have declared in my parent POM.

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.johnlewis.jjs</groupId>
  <artifactId>jlp_jjs_jjs2core-parent</artifactId>
  <packaging>pom</packaging>
  <name/>
  <version>0.0.1-SNAPSHOT</version>
  <description/>
  <modules>
    <module>../jlp_jjs_jjs2core</module>
  </modules>
</project>
```

The error message is

```
+ Error stacktraces are turned on.
Maven version: 2.0.9
Java version: 1.5.0
OS name: "windows xp" version: "5.1 build 2600 service pack 2" arch: "x86" Family: "dos"
[DEBUG] Building Maven user-level plugin registry from: 'C:\Documents and Settings\tso005\.m2\plugin-registry.xml'
[DEBUG] Building Maven global-level plugin registry from: 'C:\Program Files\Maven\apache-maven-2.0.9\conf\plugin-registry.xml'
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
java.lang.StackOverflowError
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:957)
	at java.security.AccessController.doPrivileged(AccessController.java:275)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:487)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:603)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:595)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:327)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:569)
	at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassRealm.java:243)
	at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:30)
	at org.codehaus.plexus.DefaultPlexusContainer.createComponentInstance(DefaultPlexusContainer.java:1464)
	at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:93)
	at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:92)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
	at org.codehaus.plexus.DefaultPlexusContainer.lookupList(DefaultPlexusContainer.java:423)
	at org.apache.maven.profiles.DefaultProfileManager.isActive(DefaultProfileManager.java:260)
	at org.apache.maven.profiles.DefaultProfileManager.getActiveProfiles(DefaultProfileManager.java:209)
	at org.apache.maven.project.DefaultMavenProjectBuilder.injectActiveProfiles(DefaultMavenProjectBuilder.java:1478)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:761)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:506)
	at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:198)
	at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:583)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:461)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:534)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:534)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:534)
        [...]
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:534)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:534)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:534)
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:615)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14 seconds
[INFO] Finished at: Fri Jan 02 10:23:37 GMT 2009
[INFO] Final Memory: 2M/83M
[INFO] ------------------------------------------------------------------------
```

I am running the command from CLI.  Both the projects are under the same directory.

Cheers,
Sanjay Patil

---

**Affects:** 2.0.9

**Attachments:**
- [mng-3956.zip](https://issues.apache.org/jira/secure/attachment/12712859/mng-3956.zip) (_1.76 kB_)
- [mng-3956.zip](https://issues.apache.org/jira/secure/attachment/12712858/mng-3956.zip) (_1.62 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712817/pom.xml) (_5.95 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712857/pom.xml) (_507 bytes_)
- [sandebug.log](https://issues.apache.org/jira/secure/attachment/12712816/sandebug.log) (_321.35 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

The attached project seems to reproduce your issue but the projects are just malformed: It are two aggregator POMs that reference each other.

You might want to check your project setup for cycles or attach all your involved POMs for inspection.

**Comment by jira-importer** [comment]
**[Sanjay Kumar Patil](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanjay_patil@johnlewis.co.uk)** commented

Hi,

I have attached both the POM. Please can you have a look.

Cheers,
Sanjay Patil

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

I tried to arrange the POMs in a local file structure as suggested from their contents but I can't reproduce your issue. Running "mvn validate" on either of the modules works. Can you provide a ZIP/TAR/whatever archive with a ready-made demo project?

**Comment by jira-importer** [comment]
**[Sanjay Kumar Patil](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sanjay_patil@johnlewis.co.uk)** commented

Hi Benjamin,

I have fixed this problem but I dont know the reason for it. Thing is that my child module artifact id was same as parent POM project name and thats why it was going in loop. I gave a different name today and it started working.

Now I have come across another error while running mvn site command from the parent POM. I fails with the below error.

[DEBUG] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[DEBUG] Setting property: site.resource.loader.class => 'org.codehaus.plexus.velocity.SiteResourceLoader'.
[DEBUG] Setting property: velocimacro.messages.on => 'false'.
[DEBUG] Setting property: resource.loader => 'classpath,site'.
[DEBUG] Setting property: runtime.log.invalid.references => 'false'.
[DEBUG] Setting property: resource.manager.logwhenfound => 'false'.
[DEBUG] Setting property: velocimacro.permissions.allow.inline.to.replace.global => 'true'.
[DEBUG] *******************************************************************
[DEBUG] Starting Apache Velocity v1.5 (compiled: 2007-02-22 08:52:29)
[DEBUG] RuntimeInstance initializing.
[DEBUG] Default Properties File: org\apache\velocity\runtime\defaults\velocity.properties
[DEBUG] LogSystem has been deprecated. Please use a LogChute implementation.
[DEBUG] Default ResourceManager initializing. (class org.apache.velocity.runtime.resource.ResourceManagerImpl)
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader
[DEBUG] ResourceLoader instantiated: org.codehaus.plexus.velocity.SiteResourceLoader
[DEBUG] ResourceCache: initialized (class org.apache.velocity.runtime.resource.ResourceCacheImpl)
[DEBUG] Default ResourceManager initialization complete.
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Literal
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Macro
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Parse
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Include
[DEBUG] Loaded System Directive: org.apache.velocity.runtime.directive.Foreach
[DEBUG] Created '20' parsers.
[DEBUG] Velocimacro : initialization starting.
[DEBUG] Velocimacro : allowInline = true : VMs can be defined inline in templates
[DEBUG] Velocimacro : allowInlineToOverride = true : VMs defined inline may replace previous VM definitions
[DEBUG] Velocimacro : allowInlineLocal = false : VMs defined inline will be global in scope if allowed.
[DEBUG] Velocimacro : autoload off : VM system will not automatically reload global library macros
[DEBUG] Velocimacro : Velocimacro : initialization complete.
[DEBUG] RuntimeInstance successfully initialized.
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-site-plugin:2.0-beta-6:site' -->
[DEBUG]   (f) generateReports = true
[DEBUG]   (f) generatedSiteDirectory = C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\target\generated-site
[DEBUG]   (f) inputEncoding = ISO-8859-1
[DEBUG]   (f) localRepository = [local] -> file://c:\work\mavenrepository2
[DEBUG]   (f) outputDirectory = C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\target\site
[DEBUG]   (f) outputEncoding = ISO-8859-1
[DEBUG]   (f) project = MavenProject: com.johnlewis.jjs:jlp_jjs_jjs2core_Java:0.0.1-SNAPSHOT @ C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\pom.xml
[DEBUG]   (f) reactorProjects = [MavenProject: com.johnlewis.jjs:jlp_jjs_jjs2core_Java:0.0.1-SNAPSHOT @ C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\pom.xml, MavenProject: com.johnlewis.jjs:jlp_jjs_jjs2core-parent:0.0.1-SNAPSHOT @ C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core\pom.xml]
[DEBUG]   (f) reports = [org.apache.maven.plugin.checkstyle.CheckstyleReport@2a222a22, org.codehaus.mojo.cobertura.CoberturaReportMojo@781a781a, org.codehaus.mojo.findbugs.FindBugsMojo@426a426a, org.codehaus.mojo.jdepend.JDependMojo@5e505e50, org.apache.maven.report.projectinfo.CimReport@27f827f8, org.apache.maven.report.projectinfo.DependenciesReport@62b662b6, org.apache.maven.report.projectinfo.DependencyConvergenceReport@6500650, org.apache.maven.report.projectinfo.IssueTrackingReport@27642764, org.apache.maven.report.projectinfo.LicenseReport@b540b54, org.apache.maven.report.projectinfo.MailingListsReport@6e586e58, org.apache.maven.report.projectinfo.ProjectIndexPageReport@22dc22dc, org.apache.maven.report.projectinfo.ProjectSummaryReport@a640a64, org.apache.maven.report.projectinfo.ScmReport@271c271c, org.apache.maven.report.projectinfo.TeamListReport@32743274]
[DEBUG]   (f) repositories = [[central] -> http://repo1.maven.org/maven2]
[DEBUG]   (f) siteDirectory = C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\src\site
[DEBUG]   (f) templateDirectory = C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\src\site
[DEBUG]   (f) xdocDirectory = C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\xdocs
[DEBUG]   - end configuration --
[INFO] [site:site]
[DEBUG] Mapped url: C:\Work\IDE\workspace\tso005\jlp_jjs_JJS2Core~SP\jlp_jjs_JJS2Core_Java\src\site to relative path: src\site
[WARNING] No URL defined for the project - decoration links will not be resolved
[DEBUG] maven-default-skin: using locally installed snapshot
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] The skin does not exist: Unable to determine the release version

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=org.apache.maven.skins -DartifactId=maven-default-skin -Dversion=RELEASE -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there:
mvn deploy:deploy-file -DgroupId=org.apache.maven.skins -DartifactId=maven-default-skin -Dversion=RELEASE -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

org.apache.maven.skins:maven-default-skin:jar:RELEASE

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: The skin does not exist: Unable to determine the release version

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=org.apache.maven.skins -DartifactId=maven-default-skin -Dversion=RELEASE -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there:
mvn deploy:deploy-file -DgroupId=org.apache.maven.skins -DartifactId=maven-default-skin -Dversion=RELEASE -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

org.apache.maven.skins:maven-default-skin:jar:RELEASE

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:579)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:615)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.MojoFailureException: The skin does not exist: Unable to determine the release version

Try downloading the file manually from the project website.

Then, install it using the command:
mvn install:install-file -DgroupId=org.apache.maven.skins -DartifactId=maven-default-skin -Dversion=RELEASE -Dpackaging=jar -Dfile=/path/to/file

I will attach the log as well when the run the command from CLI.  Please can you have a look.

Cheers,
Sanjay Patil

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Make sure that your copy of `org/apache/maven/skins/maven-default-skin/maven-metadata-central.xml` in your local repo matches the [official remote copy](http://repo2.maven.org/maven2/org/apache/maven/skins/maven-default-skin/maven-metadata.xml) or delete the file's parent directory to have Maven redownload it. Also, try to add the flag "-U" to your command line to force a re-check of the metadata. Your skin issue is likely a duplicate of MNG-3139.
