### ISSUE TITLE
[MNG-4049] FATAL ERROR

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6023]
**[Matthew Corby-Eaglen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=matt.corby)** opened **[MNG-4049](https://issues.apache.org/jira/browse/MNG-4049?redirect=false)** and commented

```
$ mvn -v
Maven version: 2.0.10
Java version: 1.4.2_05
OS name: "sunos" version: "5.10" arch: "x86" Family: "unix"
$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: unknown
POM Location: /data/cruisecontrol/projects/WebAppPom/pom.xml

Reason: Parse error reading POM. Reason: Unrecognised association: 'inherited' (position: START_TAG seen ...<dependencies>\n\t\t\t\t\t<inherited>... @42:17)  for project unknown at /data/cruisecontrol/projects/WebAppPom/pom.xml


[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Parse error reading POM. Reason: Unrecognised association: 'inherited' (position: START_TAG seen ...<dependencies>\n\t\t\t\t\t<inherited>... @42:17)  for project unknown at /data/cruisecontrol/projects/WebAppPom/pom.xml
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:378)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:292)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:301)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:324)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.InvalidProjectModelException: Parse error reading POM. Reason: Unrecognised association: 'inherited' (position: START_TAG seen ...<dependencies>\n\t\t\t\t\t<inherited>... @42:17)  for project unknown at /data/cruisecontrol/projects/WebAppPom/pom.xml
        at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1591)
        at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1552)
        at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:503)
        at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:197)
        at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:583)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:461)
        at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:365)
        ... 11 more
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: Unrecognised association: 'inherited' (position: START_TAG seen ...<dependencies>\n\t\t\t\t\t<inherited>... @42:17)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePlugin(MavenXpp3Reader.java:3323)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseBuild(MavenXpp3Reader.java:894)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2542)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4998)
        at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1587)
        ... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Tue Feb 24 12:08:51 CET 2009
[INFO] Final Memory: 1M/2M
[INFO] ------------------------------------------------------------------------
```

pom has the following in plugins:

```
...
                        <plugin>
                                <dependencies>
                                        <inherited>true</inherited>
                                </dependencies>
                        </plugin>
...
```

---

**Affects:** 2.0.10

**Comment by jira-importer** [comment]
**[Matthew Corby-Eaglen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=matt.corby)** commented

does not happen in 2.0.9 - switching back for the time being.

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

2.0.10 is simply picking up incorrect syntax in your POM that other versions haven't. There has never been an \<inherited> flag in dependencies - you can safely delete it from your pom.xml
