### ISSUE TITLE
[MNG-3957] [regression] For artifact {stax:stax-api:null:jar}: The version cannot be empty. 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6025]
**[Jorg Heymans](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=heymjo)** opened **[MNG-3957](https://issues.apache.org/jira/browse/MNG-3957?redirect=false)** and commented

A module in my build includes a dep to spring-ws:

```
<dependency>
  <groupId>org.springframework.ws</groupId>
  <artifactId>spring-ws-core</artifactId>
  <version>1.5.5</version>
  <exclusions>
    <exclusion>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
    </exclusion>
    <exclusion>
      <groupId>org.springframework</groupId>
      <artifactId>spring-aop</artifactId>
    </exclusion>
    <exclusion>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
    </exclusion>
    <exclusion>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
    </exclusion>
    <exclusion>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
    </exclusion>
    <exclusion>
      <groupId>org.springframework</groupId>
      <artifactId>spring-beans</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

doing clean install i get this exception:

```
constituent[0]: file:/d:/tools/maven2/lib/bcpg-jdk15-140.jar
constituent[1]: file:/d:/tools/maven2/lib/bcprov-jdk15-140.jar
constituent[2]: file:/d:/tools/maven2/lib/commons-cli-1.0.jar
constituent[3]: file:/d:/tools/maven2/lib/commons-logging-api-1.1.jar
constituent[4]: file:/d:/tools/maven2/lib/doxia-sink-api-1.0-alpha-9.jar
constituent[5]: file:/d:/tools/maven2/lib/google-collect-snapshot-20080530.jar
constituent[6]: file:/d:/tools/maven2/lib/jetty-6.1.12.jar
constituent[7]: file:/d:/tools/maven2/lib/jetty-client-6.1.12.jar
constituent[8]: file:/d:/tools/maven2/lib/jetty-sslengine-6.1.12.jar
constituent[9]: file:/d:/tools/maven2/lib/jetty-util-6.1.12.jar
constituent[10]: file:/d:/tools/maven2/lib/jsch-0.1.38.jar
constituent[11]: file:/d:/tools/maven2/lib/log4j-1.2.12.jar
constituent[12]: file:/d:/tools/maven2/lib/maven-compat-3.0-alpha-1.jar
constituent[13]: file:/d:/tools/maven2/lib/maven-core-3.0-alpha-1.jar
constituent[14]: file:/d:/tools/maven2/lib/maven-distribution-3.0-alpha-1.jar
constituent[15]: file:/d:/tools/maven2/lib/maven-embedder-3.0-alpha-1.jar
constituent[16]: file:/d:/tools/maven2/lib/maven-lifecycle-3.0-alpha-1.jar
constituent[17]: file:/d:/tools/maven2/lib/maven-mercury-3.0-alpha-1.jar
constituent[18]: file:/d:/tools/maven2/lib/maven-model-3.0-alpha-1.jar
constituent[19]: file:/d:/tools/maven2/lib/maven-plugin-api-3.0-alpha-1.jar
constituent[20]: file:/d:/tools/maven2/lib/maven-project-3.0-alpha-1.jar
constituent[21]: file:/d:/tools/maven2/lib/maven-project-builder-3.0-alpha-1.jar
constituent[22]: file:/d:/tools/maven2/lib/maven-reporting-api-3.0-alpha-1.jar
constituent[23]: file:/d:/tools/maven2/lib/maven-toolchain-3.0-alpha-1.jar
constituent[24]: file:/d:/tools/maven2/lib/mercury-artifact-1.0.0-alpha-2.jar
constituent[25]: file:/d:/tools/maven2/lib/mercury-crypto-api-1.0.0-alpha-2.jar
constituent[26]: file:/d:/tools/maven2/lib/mercury-crypto-basic-1.0.0-alpha-2.jar
constituent[27]: file:/d:/tools/maven2/lib/mercury-event-1.0.0-alpha-2.jar
constituent[28]: file:/d:/tools/maven2/lib/mercury-external-1.0.0-alpha-2.jar
constituent[29]: file:/d:/tools/maven2/lib/mercury-logging-1.0.0-alpha-2.jar
constituent[30]: file:/d:/tools/maven2/lib/mercury-md-sat-1.0.0-alpha-2.jar
constituent[31]: file:/d:/tools/maven2/lib/mercury-md-shared-1.0.0-alpha-2.jar
constituent[32]: file:/d:/tools/maven2/lib/mercury-plexus-1.0.0-alpha-2.jar
constituent[33]: file:/d:/tools/maven2/lib/mercury-repo-api-1.0.0-alpha-2.jar
constituent[34]: file:/d:/tools/maven2/lib/mercury-repo-cache-fs-1.0.0-alpha-2.jar
constituent[35]: file:/d:/tools/maven2/lib/mercury-repo-local-m2-1.0.0-alpha-2.jar
constituent[36]: file:/d:/tools/maven2/lib/mercury-repo-remote-m2-1.0.0-alpha-2.jar
constituent[37]: file:/d:/tools/maven2/lib/mercury-repo-virtual-1.0.0-alpha-2.jar
constituent[38]: file:/d:/tools/maven2/lib/mercury-transport-api-1.0.0-alpha-2.jar
constituent[39]: file:/d:/tools/maven2/lib/mercury-transport-http-1.0.0-alpha-2.jar
constituent[40]: file:/d:/tools/maven2/lib/mercury-util-1.0.0-alpha-2.jar
constituent[41]: file:/d:/tools/maven2/lib/model-builder-1.0.jar
constituent[42]: file:/d:/tools/maven2/lib/nekohtml-1.9.6.2.jar
constituent[43]: file:/d:/tools/maven2/lib/org.sat4j.core-2.0.4.jar
constituent[44]: file:/d:/tools/maven2/lib/org.sat4j.pb-2.0.4.jar
constituent[45]: file:/d:/tools/maven2/lib/plexus-component-annotations-1.0-beta-3.0.1.jar
constituent[46]: file:/d:/tools/maven2/lib/plexus-container-default-1.0-beta-3.0.1.jar
constituent[47]: file:/d:/tools/maven2/lib/plexus-interactivity-api-1.0-alpha-6.jar
constituent[48]: file:/d:/tools/maven2/lib/plexus-interpolation-1.1.jar
constituent[49]: file:/d:/tools/maven2/lib/plexus-lang-1.1.jar
constituent[50]: file:/d:/tools/maven2/lib/plexus-plugin-manager-1.0-alpha-1.jar
constituent[51]: file:/d:/tools/maven2/lib/plexus-utils-1.5.6.jar
constituent[52]: file:/d:/tools/maven2/lib/servlet-api-2.5-6.1.12.jar
constituent[53]: file:/d:/tools/maven2/lib/slf4j-api-1.5.3.jar
constituent[54]: file:/d:/tools/maven2/lib/slf4j-jdk14-1.5.3.jar
constituent[55]: file:/d:/tools/maven2/lib/stax-api-1.0.1.jar
constituent[56]: file:/d:/tools/maven2/lib/wagon-file-1.0-beta-4.jar
constituent[57]: file:/d:/tools/maven2/lib/wagon-http-lightweight-1.0-beta-4.jar
constituent[58]: file:/d:/tools/maven2/lib/wagon-http-shared-1.0-beta-4.jar
constituent[59]: file:/d:/tools/maven2/lib/wagon-provider-api-1.0-beta-4.jar
constituent[60]: file:/d:/tools/maven2/lib/wagon-ssh-1.0-beta-4.jar
constituent[61]: file:/d:/tools/maven2/lib/wagon-ssh-common-1.0-beta-4.jar
constituent[62]: file:/d:/tools/maven2/lib/wagon-ssh-external-1.0-beta-4.jar
constituent[63]: file:/d:/tools/maven2/lib/wstx-asl-3.2.6.jar
constituent[64]: file:/d:/tools/maven2/lib/xbean-reflect-3.4.jar
constituent[65]: file:/d:/tools/maven2/lib/xercesMinimal-1.9.6.2.jar
---------------------------------------------------
org.apache.maven.artifact.InvalidArtifactRTException: For artifact {stax:stax-api:null:jar}: The version cannot be empty.
        at org.apache.maven.artifact.DefaultArtifact.validateIdentity(DefaultArtifact.java:159)
        at org.apache.maven.artifact.DefaultArtifact.<init>(DefaultArtifact.java:134)
        at org.apache.maven.artifact.factory.DefaultArtifactFactory.createArtifact(DefaultArtifactFactory.java:216)
        at org.apache.maven.artifact.factory.DefaultArtifactFactory.createDependencyArtifact(DefaultArtifactFactory.java:98)
        at org.apache.maven.project.artifact.MavenMetadataSource.createArtifacts(MavenMetadataSource.java:489)
        at org.apache.maven.project.MavenProject.createArtifacts(MavenProject.java:1681)
        at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:354)
        at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:524)
        at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:132)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:347)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:321)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:289)
        at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1505)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:543)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:492)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:259)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:201)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:164)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:207)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:846)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:160)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
```

---

**Affects:** 3.0-alpha-1

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712814/pom.xml) (_2.14 kB_)

**Issue Links:**
- [MNG-4034](https://issues.apache.org/jira/browse/MNG-4034) [regression] dependency version is not inherited from parent dependencyManagement
 (_**"duplicates"**_)
- [MNG-1957](https://issues.apache.org/jira/browse/MNG-1957) \<jdk>\</jdk> clause in the activation section has to provide more complex expressions.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Running "mvn compile" on the attached POM using Maven 3.x worked for me. Can you provide a minimal test project or at least your debug logs?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Guided by Brett's analysis and checking the POMs of spring-ws-core and spring-ws-parent this issue duplicates MNG-4034.
