### ISSUE TITLE
[MNG-3960] cannot build projects which use plexus-maven-plugin with 3.0-alpha-1

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6030]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** opened **[MNG-3960](https://issues.apache.org/jira/browse/MNG-3960?redirect=false)** and commented

When building projects with mvn 3.0-alpha-1 which plexus-maven-plugin (release project in mvn svn, some plugins maven-changes-plugin, continuum, archiva), I have the following exception (java.lang.ClassNotFoundException) :

```
Exception in thread "main" java.lang.NoClassDefFoundError
        at org.codehaus.plexus.cdc.gleaner.QDoxComponentGleaner.class$(QDoxComponentGleaner.java:231)
        at org.codehaus.plexus.cdc.gleaner.QDoxComponentGleaner.<clinit>(QDoxComponentGleaner.java:230)
        at org.codehaus.plexus.maven.plugin.SourceComponentDescriptorExtractor.extract(SourceComponentDescriptorExtractor.java:57)
        at org.codehaus.plexus.maven.plugin.AbstractDescriptorMojo.generateDescriptor(AbstractDescriptorMojo.java:131)
        at org.codehaus.plexus.maven.plugin.PlexusDescriptorMojo.execute(PlexusDescriptorMojo.java:60)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:631)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:492)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmentForProject(DefaultLifecycleExecutor.java:259)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:201)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:164)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:207)
        at org.apache.maven.embedder.MavenEmbedder.execute(MavenEmbedder.java:846)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:160)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.personality.plexus.lifecycle.phase.Suspendable
        at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadRealmClass(ClassRealm.java:174)
        at org.codehaus.plexus.classworlds.strategy.DefaultStrategy.loadClass(DefaultStrategy.java:67)
        at org.codehaus.plexus.classworlds.strategy.ForeignStrategy.loadClass(ForeignStrategy.java:39)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:207)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:201)
        at org.codehaus.plexus.classworlds.strategy.DefaultStrategy.loadClass(DefaultStrategy.java:73)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:207)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:201)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:164)
        ... 22 more

```

---

**Affects:** 3.0-alpha-1

**Issue Links:**
- [MNG-3972](https://issues.apache.org/jira/browse/MNG-3972) core-it-plugins fails to build when using maven trunk

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

This is result of cleaning out some code in Plexus, no one has ever implemented the Suspendable interface but it won't hurt to restore them and then this problem will go away.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Plexus updated to allow the operation of the plexus-maven-plugin.
