### ISSUE TITLE
[MNG-4765] Failing to determine java version for profile....

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6062]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** opened **[MNG-4765](https://issues.apache.org/jira/browse/MNG-4765?redirect=false)** and commented

I'm not sure if this is really a problem with Maven 3 or a problem in the Shade plugin, but it only occurs with Maven 3 and not 2.2.1 (or 2.0.x) so I'm reporting it here.

I've attached a sample pom.xml that shows the issue.   Just stick it someplace and run mvn install.   It ends up with a stack trace like:

[ERROR] Failed to determine Java version for profile jdk15 @ org.apache.cxf:cxf:2.3.0-SNAPSHOT, line 419, column 22
for project test:test-bundle:2.3.0-SNAPSHOT at /tmp/dependency-reduced-pom.xml
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:126)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:85)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:71)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:136)
at org.apache.maven.plugins.shade.mojo.ShadeMojo.createDependencyReducedPom(ShadeMojo.java:836)
at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:496)
... 21 more
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for test:test-bundle:2.3.0-SNAPSHOT
[ERROR] Failed to determine Java version for profile jdk15 @ org.apache.cxf:cxf:2.3.0-SNAPSHOT, line 419, column 22

    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:422)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:374)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:365)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:122)

---

**Affects:** 3.0-beta-1, 3.0-beta-2

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712668/pom.xml) (_3.41 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r987335](http://svn.apache.org/viewvc?view=revision&revision=987335).
