### ISSUE TITLE
[MNG-4615] [regression] @required plugin parameters are not validated

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6095]
**[nigel magnay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=magnayn)** opened **[MNG-4615](https://issues.apache.org/jira/browse/MNG-4615?redirect=false)** and commented

Executing

```
mvn -X install:install-file -DgroupId=com.adobe.flex.framework -DartifactId=halo -Dversion=4.0.0.14159 -Dpackaging=swc /Applications/Adobe\ Flash\ Builder\ 4/sdks/4.0.0/frameworks/themes/Halo/halo.swc 
```

Yields:

```
Apache Maven 3.0-alpha-7 (r921173; 2010-03-09 22:31:07+0000)
Java version: 1.6.0_17
Java home: /System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Home
Default locale: en_US, platform encoding: MacRoman
OS name: "mac os x" version: "10.6.3" arch: "x86_64" Family: "mac"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading user settings from /Users/magnayn/.m2/settings.xml
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Using local repository at /Users/magnayn/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project org.apache.maven:standalone-pom:pom:1: (none)
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[DEBUG] Resolving plugin prefix install from [org.jvnet.hudson.tools, org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Resolved plugin prefix install to org.apache.maven.plugins:maven-install-plugin from POM org.apache.maven:standalone-pom:pom:1
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: org.apache.maven:standalone-pom:pom:1
[DEBUG] Tasks:   [org.apache.maven.plugins:maven-install-plugin:2.3:install-file]
[DEBUG] Style:   Aggregating
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Project: org.apache.maven:standalone-pom:pom:1
[DEBUG] Tasks:   [/Applications/Adobe Flash Builder 4/sdks/4.0.0/frameworks/themes/Halo/halo.swc]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       org.apache.maven:standalone-pom:1
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.apache.maven.plugins:maven-install-plugin:2.3:install-file (default-cli)
[DEBUG] Style:         Aggregating
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <artifactId>${artifactId}</artifactId>
  <classifier>${classifier}</classifier>
  <createChecksum default-value="false">${createChecksum}</createChecksum>
  <file>${file}</file>
  <generatePom>${generatePom}</generatePom>
  <groupId>${groupId}</groupId>
  <javadoc>${javadoc}</javadoc>
  <localRepository>${localRepository}</localRepository>
  <localRepositoryPath>${localRepositoryPath}</localRepositoryPath>
  <packaging>${packaging}</packaging>
  <pomFile>${pomFile}</pomFile>
  <repositoryLayout default-value="default">${repositoryLayout}</repositoryLayout>
  <sources>${sources}</sources>
  <updateReleaseInfo default-value="false">${updateReleaseInfo}</updateReleaseInfo>
  <version>${version}</version>
</configuration>
[DEBUG] =======================================================================
[INFO] 
[INFO] --- maven-install-plugin:2.3:install-file (default-cli) @ standalone-pom ---
[DEBUG] Created new class realm plugin>org.apache.maven.plugins:maven-install-plugin:2.3
[DEBUG] Populating class realm plugin>org.apache.maven.plugins:maven-install-plugin:2.3
[DEBUG]   Included: org.apache.maven.plugins:maven-install-plugin:maven-plugin:2.3
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.5.6
[DEBUG]   Included: junit:junit:jar:3.8.1
[DEBUG]   Included: org.codehaus.plexus:plexus-digest:jar:1.0
[DEBUG]   Excluded: org.apache.maven:maven-plugin-api:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-project:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-settings:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-model:jar:2.0.6
[DEBUG]   Excluded: org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1
[DEBUG]   Excluded: classworlds:classworlds:jar:1.1-alpha-2
[DEBUG]   Excluded: org.apache.maven:maven-profile:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-artifact-manager:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-repository-metadata:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-artifact:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-plugin-registry:jar:2.0.6
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-install-plugin:2.3:install-file' with basic configurator -->
[DEBUG]   (f) artifactId = halo
[DEBUG]   (f) createChecksum = false
[DEBUG]   (f) groupId = com.adobe.flex.framework
[DEBUG]   (f) localRepository =        id: local
      url: file:///Users/magnayn/.m2/repository/
   layout: none

[DEBUG]   (f) packaging = swc
[DEBUG]   (f) repositoryLayout = default
[DEBUG]   (f) updateReleaseInfo = false
[DEBUG]   (f) version = 4.0.0.14159
[DEBUG] -- end configuration --
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.430s
[INFO] Finished at: Wed Mar 31 17:13:56 BST 2010
[INFO] Final Memory: 3M/80M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "jrebel" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.3:install-file (default-cli) on project standalone-pom: Execution default-cli of goal org.apache.maven.plugins:maven-install-plugin:2.3:install-file failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.3:install-file (default-cli) on project standalone-pom: Execution default-cli of goal org.apache.maven.plugins:maven-install-plugin:2.3:install-file failed.
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:592)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:323)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:247)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:104)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:427)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:157)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-install-plugin:2.3:install-file failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:114)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:576)
	... 14 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugin.install.InstallFileMojo.execute(InstallFileMojo.java:210)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
	... 15 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

---

**Affects:** 3.0-alpha-7

**Issue Links:**
- [MNG-4764](https://issues.apache.org/jira/browse/MNG-4764) `@required` plugin parameters using default-value with expressions are not validated

- [MNG-5476](https://issues.apache.org/jira/browse/MNG-5476) [REGRESSION] `@required` parameter not being enforced for arrays

1 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Your command is missing the -Dfile property

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r983050](http://svn.apache.org/viewvc?view=revision&revision=983050).
