### ISSUE TITLE
[MNG-4611] 3.0-alpha7 password decryption log verbosity

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6097]
**[Dale Wyttenbach](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wytten)** opened **[MNG-4611](https://issues.apache.org/jira/browse/MNG-4611?redirect=false)** and commented

The log verbosity of password decryption in 3.0-alpha7 that makes the mvn -X option effectively unusable.  The password I've got in my settings.xml file looks like this:

    <password>{DESede}y+qq...==</password> 

This is an Artifactory setup password and it does work, however mvn -X logs exceptions about it so frequently that it makes -X almost impossible to use.  Is there some way I can suppress this behavior through configuration?  The exception that it logs over and over again is:

[DEBUG] Failed to decrypt password for server central: org.sonatype.plexus.components.cipher.PlexusCipherException: java.lang.ArrayIndexOutOfBoundsException
org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: org.sonatype.plexus.components.cipher.PlexusCipherException: java.lang.ArrayIndexOutOfBoundsException
...
Caused by: java.lang.ArrayIndexOutOfBoundsException
at java.lang.System.arraycopy(Native Method)
at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:175)
... 47 more

---

**Issue Links:**
- [MNG-4704](https://issues.apache.org/jira/browse/MNG-4704) Maven 3.0 beta 1 password decryption log verbosity with FileNotFoundException
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

In conformance with [Maven Password Encryption](http://maven.apache.org/guides/mini/guide-encryption.html), the password you use should be decrypted by Maven but its format is invalid, so the log messages are justified.

AFAICT, the escape mechanism documented on that page is broken, so right now your only option is to either ignore the log messages or encrypt you password properly using Maven.

**Comment by jira-importer** [comment]
**[Yoav Landman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yoav)** commented

If the password escape mechanism is broken, how is it not a bug? There is really nothing "improper" about the password used, and it is currently the only way to centrally enforce security and to have zero client-side password generation or clear text keys on the client.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

This issue is about the "log verbosity". The log output is fine, as there is an issue with the password used.

**Comment by jira-importer** [comment]
**[Brendan Lawlor](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=blawlor)** commented

I've raised MNG-4626 as a more general but related point. I think the notion of encrypting 'properly' as suggested above is a problem in the first place. The encryption mechanism used by Dale and provided for by Yoav in Artifactory is clearly the sensible approach to password protection in maven, and maven/nexus should really be doing the same thing.
