### ISSUE TITLE
[MNG-4604] Error when changing M2_HOME on linux (at least :) )

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6103]
**[olivier o](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olivier%20o.)** opened **[MNG-4604](https://issues.apache.org/jira/browse/MNG-4604?redirect=false)** and commented

When I tried to change the value of M2_HOME directory, I get the following error

-bash-3.2$ mvn -v
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/plexus/classworlds/launcher/Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:276)
at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)

My m2_home includes the same settings.xml
If I unset the m2_home, it's find :

-bash-3.2$ mvn -v
Apache Maven 3.0-alpha-7 (r921173; 2010-03-09 23:31:07+0100)
Java version: 1.6.0_07
Java home: /opt/sun/jdk1.6.0_07/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "2.6.18-164.el5" arch: "amd64" Family: "unix"

---

**Affects:** 3.0-alpha-7

**Issue Links:**
- [MNG-4483](https://issues.apache.org/jira/browse/MNG-4483) Maven 3 user directory is .m2 (be .mvn or something else?)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

You can't mix the mvn run script and the M2_HOME var from different Maven major versions. If you point M2_HOME at a 2.x installation, the 3.x run script won't work and vice versa.

**Comment by jira-importer** [comment]
**[olivier o](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olivier%20o.)** commented

Thanks for the quick answer. It's make sense M2_HOME related to maven2 and M3_HOME to maven 3...
