### ISSUE TITLE
[MNG-4586] Plugin prefix can't be resolved from plugin management if management entry is missing plugin version

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6119]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-4586](https://issues.apache.org/jira/browse/MNG-4586?redirect=false)** and commented

For a POM snippet like

```xml
<build>
  <pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.its.plugin</groupId>
        <artifactId>maven-it-plugin-expression</artifactId>
        <!-- version omitted -->
      </plugin>
    </plugins>
  </pluginManagement>
</build>
```

and the command "mvn itexpression:eval" we end up with

```
[WARNING] Failed to retrieve plugin descriptor for Plugin [org.apache.maven.its.plugin:maven-it-plugin-expression]: null
java.lang.NullPointerException
        at org.apache.maven.plugin.DefaultPluginDescriptorCache$CacheKey.<init>(DefaultPluginDescriptorCache.java:148)
        at org.apache.maven.plugin.DefaultPluginDescriptorCache.createKey(DefaultPluginDescriptorCache.java:61)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:121)
        at org.apache.maven.plugin.DefaultBuildPluginManager.loadPlugin(DefaultBuildPluginManager.java:61)
        at org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver.resolveFromProject(DefaultPluginPrefixResolver.java:127)
        at org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver.resolveFromProject(DefaultPluginPrefixResolver.java:114)
        at org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver.resolve(DefaultPluginPrefixResolver.java:74)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.findPluginForPrefix(DefaultLifecycleExecutor.java:1798)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.getMojoDescriptor(DefaultLifecycleExecutor.java:1536)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.calculateTaskSegments(DefaultLifecycleExecutor.java:863)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.calculateProjectBuilds(DefaultLifecycleExecutor.java:751)
...
[ERROR] No plugin found for prefix 'itexpression' in the current project [...]
```

---

**Affects:** 3.0-alpha-7

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r921932](http://svn.apache.org/viewvc?view=revision&revision=921932).

**Comment by jira-importer** [comment]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ID134349)** commented

Are the dashes really irrelevant for the command?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Sorry, not sure what you mean.

**Comment by jira-importer** [comment]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ID134349)** commented

The command given was "mvn itexpression:eval" but the plugin is maven-it-plugin-expression. So Maven recognizes plugin names even without the dashes?

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

"itexpression" is the prefix for the plugin as given in its plugin descriptor.
