### ISSUE TITLE
[MNG-4576] Issue running test plugin, build failure .. -Tycho- (getEclipseLauncher?)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6130]
**[Michael Hüttermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michaelhuettermann)** opened **[MNG-4576](https://issues.apache.org/jira/browse/MNG-4576?redirect=false)** and commented

Setting up my test with \<packaging>eclipse-test-plugin\</packaging> provokes a build failure: the test bundle contains JUnit tests under src/.. and requires some of my other bundles. I run "mvn clean integration-test -Dtycho.targetPlatform=C:\app\mypath\rcp-target-platform\platform\win32\rcp" which breaks, see attached log file. (throwing a NPE in context of TestMojo.getEclipseLauncher?) Calling phases before integration-test suceeds. Please find enclosed the debug log and the POM.

---

**Affects:** 3.0-alpha-6

**Attachments:**
- [log.txt](https://issues.apache.org/jira/secure/attachment/12713025/log.txt) (_75.44 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712976/pom.xml) (_1.15 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

```
Caused by: java.lang.NullPointerException
	at org.codehaus.tycho.osgitest.TestMojo.getEclipseLauncher(TestMojo.java:566)
	at org.codehaus.tycho.osgitest.TestMojo.runTest(TestMojo.java:480)
```

Please report this against [Tycho](https://issues.sonatype.org/browse/TYCHO). It's apparently the plugin that fails, not Maven.
