### ISSUE TITLE
[MNG-4562] [regression] UnsupportedOperationException with Maven AndromMDA plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6140]
**[Julien HENRY](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henryju)** opened **[MNG-4562](https://issues.apache.org/jira/browse/MNG-4562?redirect=false)** and commented

Running mvn clean install -DperformRelease=true -e on the attached project generate the following error:

```
[ERROR] Failed to execute goal org.andromda.maven.plugins:andromda-maven-plugin:3.3:run (default) on project uml: Error
running AndroMDA: UnsupportedOperationException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.andromda.maven.plugins:andromda-maven
-plugin:3.3:run (default) on project uml: Error running AndroMDA
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:570)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeForkedExecutions(DefaultLifecycleExecutor.java:645)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:553)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:247)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:104)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:422)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:157)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:122)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error running AndroMDA
        at org.andromda.maven.plugin.AbstractAndroMDAMojo.execute(AbstractAndroMDAMojo.java:116)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:562)
        ... 16 more
Caused by: java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableCollection.add(Collections.java:1018)
        at org.andromda.maven.plugin.configuration.AbstractConfigurationMojo.addDependency(AbstractConfigurationMojo.java:259)
        at org.andromda.maven.plugin.configuration.AbstractConfigurationMojo.addPluginDependencies(AbstractConfigurationMojo.java:221)
        at org.andromda.maven.plugin.AbstractAndroMDAMojo.execute(AbstractAndroMDAMojo.java:101)
        ... 18 more
```

mvn clean install (without generating attached sources) works fine.

---

**Affects:** 3.0-alpha-6

**Attachments:**
- [test-bug-maven-andromda-sources.zip](https://issues.apache.org/jira/secure/attachment/12712973/test-bug-maven-andromda-sources.zip) (_3.41 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Already fixed, thanks for the example project.
