### ISSUE TITLE
[MNG-4559] MAVEN_OPTS are incorrectly resolved in Unix

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6145]
**[Maxim Podkolzine](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=maximp)** opened **[MNG-4559](https://issues.apache.org/jira/browse/MNG-4559?redirect=false)** and commented

I'm trying to pass a quoted parameter through MAVEN_OPTS, e.g.
MAVEN_OPTS="-Dfoo='bar baz'"

As a result the quotes are not resolved, causing Java failure:
Exception in thread "main" java.lang.NoClassDefFoundError: baz'
...

I couldn't figure out a way to make it work.

---

**Affects:** 2.2.1, 3.0.5

**Issue Links:**
- [MINVOKER-209](https://issues.apache.org/jira/browse/MINVOKER-209) ITs fail (on Windows 10) when working directory contains space
 (_**"blocks"**_)
- [MNG-7199](https://issues.apache.org/jira/browse/MNG-7199) MAVENHOME_CONFIG var in mvnlauncher script improperly handles two options at once

**Remote Links:**
- [GitHub Pull Request #2213
](https://github.com/apache/maven/pull/2213)

5 votes, 14 watchers

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

It appears to be still relevant in 3.0.5 at least. Please refer to this netbeans issue: https://netbeans.org/bugzilla/show_bug.cgi?id=242638

Steps to reproduce:
1. create a simple war project.
2. Download jrebel from http://zeroturnaround.com/software/jrebel/download/ and install it into a path with space
3. set MAVEN_OPTS environment variable to point the jrebel.jar.. eg.
   MAVEN_OPTS=-javaagent:/Users/mkleint/space in path/jrebel/jrebel.jar
   How to quote the value is open question here.
4. run mvn jetty:run and see in the output if the java agent got properly integrated.

**Comment by jira-importer** [comment]
**[heapifyman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=heapifyman)** commented

Still doesn't work with
Maven 3.2.1
Java 1.8.0_05
Mac OS 10.9.3

**Comment by jira-importer** [comment]
**[James Nord](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnord_cbs)** commented

still broken with 3.3.9

```
teilo@linuxdevx:~/a space$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /opt/apache/apache-maven-3.3.9
Java version: 1.8.0_66-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.2.0-16-generic", arch: "amd64", family: "unix"

teilo@linuxdevx:~/a space$ export MAVEN_OPTS=-Dmaven.repo.local=/home/teilo/a\ space/.m2_repo
teilo@linuxdevx:~/a space$ echo $MAVEN_OPTS
-Dmaven.repo.local=/home/teilo/a space/.m2_repo
teilo@linuxdevx:~/a space$ mvn --version
Error: Could not find or load main class space..m2_repo


teilo@linuxdevx:~/a space$ export MAVEN_OPTS=-Dmaven.repo.local="/home/teilo/a\ space/.m2_repo"
teilo@linuxdevx:~/a space$ echo $MAVEN_OPTS
-Dmaven.repo.local=/home/teilo/a\ space/.m2_repo
teilo@linuxdevx:~/a space$ mvn --version
Error: Could not find or load main class space..m2_repo


teilo@linuxdevx:~/a space$ export MAVEN_OPTS=-Dmaven.repo.local=\"/home/teilo/a\ space/.m2_repo\"
teilo@linuxdevx:~/a space$ echo $MAVEN_OPTS
-Dmaven.repo.local="/home/teilo/a space/.m2_repo"
teilo@linuxdevx:~/a space$ mvn --version
Error: Could not find or load main class space..m2_repo"


teilo@linuxdevx:~/a space$ export MAVEN_OPTS=-Dmaven.repo.local=\""/home/teilo/a space/.m2_repo\""
teilo@linuxdevx:~/a space$ echo $MAVEN_OPTS
-Dmaven.repo.local="/home/teilo/a space/.m2_repo"
teilo@linuxdevx:~/a space$ mvn --version
Error: Could not find or load main class space..m2_repo"


teilo@linuxdevx:~/a space$ export MAVEN_OPTS=-Dmaven.repo.local=\""'/home/teilo/a space/.m2_repo'"\"
teilo@linuxdevx:~/a space$ echo $MAVEN_OPTS
-Dmaven.repo.local="'/home/teilo/a space/.m2_repo'"
teilo@linuxdevx:~/a space$ mvn --version
Error: Could not find or load main class space..m2_repo'"

```

However this is handled - it should be cross platform so the same CI scripts can work on windows as well as Linux - thus quoting should be the preffered option/

**Comment by jira-importer** [comment]
**[James Nord](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jnord_cbs)** commented

attempting to workaround with `.mvn/jvm.config` or `.mvn/maven.config` also fail.

jvm config errors are similar to above, maven.config yeilds errors like

```
[ERROR] Error executing Maven.
org.apache.commons.cli.ParseException: Unrecognized maven.config entries: [space/.m2_repo]
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

There are numerous threads on SO how to properly escape special chars in env vars especially passing them again in a variable to a process. I had the same problem with `CATALINA_OPTS` and gave up. It was too confusing to make it readable.

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

I think the whole problem relies on the fact that `mvn` is using the Bourne shell `/bin/sh`, which doesn't support arrays (except `$\@`). As such, the single String consisting of the `MAVEN_OPTS` can't be understood as a sequence of parameters=value potentially containing spaces. So:

- If you quote `$MAVEN_OPTS` when used [here](https://github.com/apache/maven/blob/maven-3.3.9/apache-maven/src/bin/mvn#L239), the `java` executable will see it as 1 parameter, not multiple ones, so if you have `MAVEN_OPTS="-Xmx256m -Dparam=\"with space\""`, then `java` will understand a `Xmx` value of `256m -Dparam="with space"`...
- If you don't quote it, then every space separated token (even if it was escaped when declaring `MAVEN_OPTS`) will be considered a separate argument, so `-Dparam="with space"` will be understood as trying to launch the `space"` main class with the `-Dparam="with` system property...

Testing in Bash, I was able to make it work by defining `MAVEN_OPTS` as an array: `MAVEN_OPTS=$(-Xmx256m -Dparam="with space")` and using it in the final `java` call with `${MAVEN_OPTS\[\@\]&#125;`. But I'm not sure we can move towards Bash instead of Bourne Shell here. Also, I'm not sure if the single `$\@` array present in `/bin/sh` can be used as well, it would mean trying to tokenize the single String which is `MAVEN_OPTS` on spaces that aren't escaped... but is this reliable/possible?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

That would potentially apply to `jvm.config` as well. Did you try that?
Moreover, did you check how your change would behave when passed through Invoker's `<mavenOpts />`. If it covers all cases, I would even introduce `mvn.bash` and have the user decide wether he will replace the Bourne version with the Bourne again one.

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

Yes it applies to `.mvn/jvm.config` as well; the whole thing is concatenated to the existing `MAVEN_OPTS` [here](https://github.com/apache/maven/blob/maven-3.3.9/apache-maven/src/bin/mvn#L222). I didn't go as far as to test it with `<mavenOpts>` of the Invoker Plugin (there were other issues trying to use Bash in the current `mvn` script and wasn't sure if it would be an option), but I can try to create a complete `mvn.bash` and test with that.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

That would be great. I'd like to test that on FreeBSD and Cygwin with our Core IT Suite and Maven Invoker Plugin.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Works for me:

```
[mosipov@mika-ion ~]$ ls /tmp/bar*
ls: /tmp/bar*: No such file or directory
[mosipov@mika-ion ~]$ sh -x ~/apache-maven-3.6.1-SNAPSHOT/bin/mvn  help:system "-Dmaven.repo.local=""/tmp/bar"" ""baz"
+ [ -z '' ]
+ [ -f /etc/mavenrc ]
+ [ -f /home/mosipov/.mavenrc ]
+ cygwin=false
+ mingw=false
+ uname
+ PRG=/home/mosipov/apache-maven-3.6.1-SNAPSHOT/bin/mvn
+ [ -h /home/mosipov/apache-maven-3.6.1-SNAPSHOT/bin/mvn ]
+ pwd
+ saveddir=/home/mosipov
+ dirname /home/mosipov/apache-maven-3.6.1-SNAPSHOT/bin/mvn
+ MAVEN_HOME=/home/mosipov/apache-maven-3.6.1-SNAPSHOT/bin/..
+ cd /home/mosipov/apache-maven-3.6.1-SNAPSHOT/bin/..
+ pwd
+ MAVEN_HOME=/home/mosipov/apache-maven-3.6.1-SNAPSHOT
+ cd /home/mosipov
+ false
+ false
+ [ -z '' ]
+ which java
+ JAVACMD=/usr/local/bin/java
+ [ ! -x /usr/local/bin/java ]
+ echo /home/mosipov/apache-maven-3.6.1-SNAPSHOT/boot/plexus-classworlds-2.5.2.jar
+ CLASSWORLDS_JAR=/home/mosipov/apache-maven-3.6.1-SNAPSHOT/boot/plexus-classworlds-2.5.2.jar
+ CLASSWORLDS_LAUNCHER=org.codehaus.plexus.classworlds.launcher.Launcher
+ false
+ find_maven_basedir help:system '-Dmaven.repo.local=/tmp/bar baz'
+ find_file_argument_basedir help:system '-Dmaven.repo.local=/tmp/bar baz'
+ pwd
+ basedir=/home/mosipov
+ found_file_switch=0
+ [ 0 -eq 1 ]
+ [ help:system '=' -f -o help:system '=' --file ]
+ [ 0 -eq 1 ]
+ [ '-Dmaven.repo.local=/tmp/bar baz' '=' -f -o '-Dmaven.repo.local=/tmp/bar baz' '=' --file ]
+ echo /home/mosipov
+ basedir=/home/mosipov
+ wdir=/home/mosipov
+ [ /home/mosipov '!=' / ]
+ [ -d /home/mosipov/.mvn ]
+ cd /home/mosipov/..
+ pwd
+ wdir=/home
+ [ /home '!=' / ]
+ [ -d /home/.mvn ]
+ cd /home/..
+ pwd
+ wdir=/
+ [ / '!=' / ]
+ echo /home/mosipov
+ MAVEN_PROJECTBASEDIR=/home/mosipov
+ concat_lines /home/mosipov/.mvn/jvm.config
+ [ -f /home/mosipov/.mvn/jvm.config ]
+ MAVEN_OPTS=' '
+ false
+ export MAVEN_PROJECTBASEDIR
+ MAVEN_CMD_LINE_ARGS=' help:system -Dmaven.repo.local=/tmp/bar baz'
+ export MAVEN_CMD_LINE_ARGS
+ exec /usr/local/bin/java -classpath /home/mosipov/apache-maven-3.6.1-SNAPSHOT/boot/plexus-classworlds-2.5.2.jar '-Dclassworlds.conf=/home/mosipov/apache-maven-3.6.1-SNAPSHOT/bin/m2.conf' '-Dmaven.home=/home/mosipov/apache-maven-3.6.1-SNAPSHOT' '-Dlibrary.jansi.path=/home/mosipov/apache-maven-3.6.1-SNAPSHOT/lib/jansi-native' '-Dmaven.multiModuleProjectDirectory=/home/mosipov' org.codehaus.plexus.classworlds.launcher.Launcher help:system '-Dmaven.repo.local=/tmp/bar baz'
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom (3.9 kB at 793 B/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/22/maven-plugins-22.pom (13 kB at 7.4 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/21/maven-parent-21.pom (26 kB at 46 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/10/apache-10.pom (15 kB at 16 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.jar (25 kB at 27 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.4/maven-install-plugin-2.4.pom
[mosipov@mika-ion ~]$ ls /tmp/
bar baz                   hsperfdata_mosipov        portmasterfail.txt
f-41407-IPC_SAVE.UKc1Q0LQ hsperfdata_root
[mosipov@mika-ion ~]$ stat -x /tmp/bar\ baz/
  File: "/tmp/bar baz/"
  Size: 512          FileType: Directory
  Mode: (0755/drwxr-xr-x)         Uid: ( 1001/ mosipov)  Gid: (    0/   wheel)
Device: 0,89   Inode: 2166954    Links: 3
Access: Fri Mar 29 20:36:01 2019
Modify: Fri Mar 29 20:36:06 2019
Change: Fri Mar 29 20:36:06 2019
[mosipov@mika-ion ~]$
```

as well as

```
[mosipov@mika-ion ~]$  ~/apache-maven-3.6.1-SNAPSHOT/bin/mvn  help:system "-Dfoo=""bar"" ""baz" | grep foo
sun.java.command=org.codehaus.plexus.classworlds.launcher.Launcher help:system -Dfoo=bar baz
foo=bar baz
MAVEN_CMD_LINE_ARGS= help:system -Dfoo=bar baz
```

without using `MAVEN_OPTS`. Still looking into it.

[Here](https://github.com/freebsd/poudriere/commit/5496a1422545fe0e5d60e116dd7dcbea96d095aa) is one possible approach poudirere applies.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

My bad, hit the wrong button.

**Comment by jira-importer** [comment]
**[Markus Schuh](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mschuh)** commented

The support of path names containing spaces within maven is meanwhile quite complete due to meanwhile proper quoting. Just this special case issue is open.

As already mentioned by [Dale Wijnand](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dwijnand) in a comment above in 2012, the [POSIX|http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html] solution - within a POSIX shell -  for addition of the needed quoting in final call is just to prefix the exec by an "eval ".

The introduction of arrays (not yet part of POSIX) were cleaner - but requires bash (or another shell). This may have compatibility concerns for a tool of such wide spread usage as maven.

"eval" has some security implication (code injection) - but when used as prefix for "exec" this isn't relevant, since the "exec" terminates the shell execution anyway.

**Comment by jira-importer** [comment]
**[Benjamin Marwell](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mampf86)** commented

eval is necessary. Eg look at this IBM code, they also need to support ksh (which is a posix shell used by AIX as a default):

https://github.com/OpenLiberty/open-liberty/blob/bd54569d3322c4321a7dda4fcf94d65f85bf13bf/dev/com.ibm.ws.kernel.boot.ws-server/publish/bin/server#L695-L716

Follow the eval methods and how they define them.

(hint: EPLv1).

(hint 2: they support spaces and comments)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Just tried our Core ITs with spaces in paths:

```
[ERROR] Tests run: 879, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 271.672 s <<< FAILURE! - in org.apache.maven.it.IntegrationTestSuite
[ERROR] testWithoutBuildConsumer(org.apache.maven.it.MavenITmng5669ReadPomsOnce)  Time elapsed: 0.015 s  <<< ERROR!
org.apache.maven.it.VerificationException:
Exit code was non-zero: 1; command line and log =
/var/mosipov/Projekte/maven-integration-testing/core-it-suite/target/apache-maven/bin/mvn --global-settings /var/mosipov/Projekte/maven-integration-testing/core-it-suite/target/test-classes/settings.xml -q -U -Dmaven.experimental.buildconsumer=false -e --batch-mode -Dmaven.repo.local=/usr/home/mosipov/var/Projekte/m i t/repo verify
Error opening zip file or JAR manifest missing : /usr/home/mosipov/var/Projekte/m
Error occurred during initialization of VM
agent library failed to init: instrument

        at org.apache.maven.it.MavenITmng5669ReadPomsOnce.testWithoutBuildConsumer(MavenITmng5669ReadPomsOnce.java:65)

[ERROR] testWithBuildConsumer(org.apache.maven.it.MavenITmng5669ReadPomsOnce)  Time elapsed: 0.011 s  <<< ERROR!
org.apache.maven.it.VerificationException:
Exit code was non-zero: 1; command line and log =
/var/mosipov/Projekte/maven-integration-testing/core-it-suite/target/apache-maven/bin/mvn --global-settings /var/mosipov/Projekte/maven-integration-testing/core-it-suite/target/test-classes/settings.xml -q -U -Dmaven.experimental.buildconsumer=true -e --batch-mode -Dmaven.repo.local=/usr/home/mosipov/var/Projekte/m i t/repo verify
Error opening zip file or JAR manifest missing : /usr/home/mosipov/var/Projekte/m
Error occurred during initialization of VM
agent library failed to init: instrument

        at org.apache.maven.it.MavenITmng5669ReadPomsOnce.testWithBuildConsumer(MavenITmng5669ReadPomsOnce.java:119)
```

Reason: `jvm.config` contains an agent whose path contains a space, thus fails.
