### ISSUE TITLE
[MNG-4947] NPE in at org.codehaus.plexus.component.configurator.converters.lookup.DefaultConverterLookup.findConverterForType()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6152]
**[Ondra Žižka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pekarna)** opened **[MNG-4947](https://issues.apache.org/jira/browse/MNG-4947?redirect=false)** and commented

STR:
1) svn co https://anonsvn.jboss.org/repos/hibernate/core/tags/hibernate-3.3.2.GA_CP03
2) cd hibernate-3.3.2.GA_CP03/src/core
3) Download the attached settings-hbn.xml
4) mvn -s ../../settings-hbn.xml site

hibernate/src/core $ mvn -s ../../settings-hbn.xml site
...
164K downloaded  (plexus-utils-1.1.jar)
16K downloaded  (wagon-webdav-1.0-beta-2.jar)
[INFO] ------------------------------------------------------------------------
[INFO] Building Hibernate Core Parent POM
[INFO]    task-segment: [site]
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.codehaus.plexus.component.configurator.converters.lookup.DefaultConverterLookup.findConverterForType(DefaultConverterLookup.java:115)
at org.codehaus.plexus.component.configurator.converters.lookup.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:92)
at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:175)
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:54)
at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:47)
at org.codehaus.plexus.personality.plexus.lifecycle.phase.AutoConfigurePhase.execute(AutoConfigurePhase.java:39)
at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:92)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.execution.MavenSession.lookup(MavenSession.java:138)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.findMappingsForLifecycle(DefaultLifecycleExecutor.java:1358)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.bindLifecycleForPackaging(DefaultLifecycleExecutor.java:1292)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.constructLifecycleMappings(DefaultLifecycleExecutor.java:1275)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:534)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 4 seconds
[INFO] Finished at: Mon Dec 20 17:32:55 CET 2010
[INFO] Final Memory: 9M/303M
[INFO] ------------------------------------------------------------------------
ondra@ondra-redhat: ~/work/hbn/runner/EAP-5.1/work-space/src/core $

---

**Affects:** 2.2.1

**Attachments:**
- [MNG-4947 - NPE during site build.txt](https://issues.apache.org/jira/secure/attachment/12712677/MNG-4947+-+NPE+during+site+build.txt) (_9.53 kB_)
- [settings-hbn.xml](https://issues.apache.org/jira/secure/attachment/12713144/settings-hbn.xml) (_1.92 kB_)

**Issue Links:**
- [MNG-4972](https://issues.apache.org/jira/browse/MNG-4972) NPE in DefaultConverterLookup.findConverterForType()
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Ondra Žižka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pekarna)** commented

Can't reproduce. However someone could check the code and handle the pottential null value.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Under normal circumstances, I don't see how a null value could show up. Let us know, when you find out, what detail is required to actually reproduce this.

**Comment by jira-importer** [comment]
**[Petrica Grama](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pgrama)** commented

Just a small comment on this:

I think you can reproduce it by making a test with the following code:

DefaultConverterLookup dcl = new DefaultConverterLookup();
dcl.registerConverter(null);
dcl.lookupConverterForType(BooleanConverter.class);

I'm guessing that someone, somewhere, somehow (sorry for not being more precise), it's registering a null converter.

You can fix it by not allowing the registration of a null object inside the registerConverter method:
public void registerConverter( ConfigurationConverter converter )
{
if(converter != null)
{
customConverters.add( converter );
}
}

I know that this doesn't fix the actual problem but might be a way to avoid the annoying occurrence of this exception inside Hudson builds.

Just my 2 cents :)

**Comment by jira-importer** [comment]
**[Martin Todorov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlspring)** commented

We are still getting this with Maven 2.1.1. Could you please, re-open this bug report?

**Comment by jira-importer** [comment]
**[Ernst de Haan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=znerd)** commented

(sorry, forget my comment, it was a different NPE)
