### ISSUE TITLE
[MNG-4546] Cannot configure maven Wagon Provider

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6163]
**[Brian Ko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=briankous)** opened **[MNG-4546](https://issues.apache.org/jira/browse/MNG-4546?redirect=false)** and commented

Since I have outOfMemory error, I tried to use httpclient instead of default, lightweight. When I changed the configuration as follows
\<servers>
\<server>
\<id>central\</id>
\<configuration>
\<wagonProvider>httpclient\</wagonProvider>
[...]
\</configuration>
\</server>

I have follwoing error.

[INFO ] Retrieving previous build number from masco-coatings.snapshots
ERROR: Error retrieving previous build number for artifact 'mascocoatings.portal:mascocoatings-portal-coc:war': repository metadata for: 'snapshot mascocoatings.portal:mascocoatings-portal-coc:1.0.0-SNAPSHOT' could not be retrieved from repository: masco-coatings.snapshots due to an error: While configuring wagon for 'masco-coatings.snapshots': Unable to apply wagon configuration.
org.apache.maven.artifact.deployer.ArtifactDeploymentException: Error retrieving previous build number for artifact 'mascocoatings.portal:mascocoatings-portal-coc:war': repository metadata for: 'snapshot mascocoatings.portal:mascocoatings-portal-coc:1.0.0-SNAPSHOT' could not be retrieved from repository: masco-coatings.snapshots due to an error: While configuring wagon for 'masco-coatings.snapshots': Unable to apply wagon configuration.
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:106)
at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForDeployment(DefaultArtifactTransformationManager.java:78)
at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:71)
at hudson.maven.reporters.MavenArtifactRecord.deploy(MavenArtifactRecord.java:119)
at hudson.maven.reporters.MavenAggregatedArtifactRecord.deploy(MavenAggregatedArtifactRecord.java:79)
at hudson.maven.RedeployPublisher.perform(RedeployPublisher.java:96)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:508)
at hudson.model.AbstractBuild$AbstractRunner.performAllBuildStep(AbstractBuild.java:494)
at hudson.maven.MavenModuleSetBuild$RunnerImpl.post2(MavenModuleSetBuild.java:594)
at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:466)
at hudson.model.Run.run(Run.java:1197)
at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:303)
at hudson.model.ResourceController.execute(ResourceController.java:88)
at hudson.model.Executor.run(Executor.java:123)
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataResolutionException: repository metadata for: 'snapshot mascocoatings.portal:mascocoatings-portal-coc:1.0.0-SNAPSHOT' could not be retrieved from repository: masco-coatings.snapshots due to an error: While configuring wagon for 'masco-coatings.snapshots': Unable to apply wagon configuration.
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:352)
at org.apache.maven.artifact.transform.SnapshotTransformation.resolveLatestSnapshotBuildNumber(SnapshotTransformation.java:161)
at org.apache.maven.artifact.transform.SnapshotTransformation.transformForDeployment(SnapshotTransformation.java:100)
... 14 more
Caused by: org.apache.maven.artifact.manager.WagonConfigurationException: While configuring wagon for 'masco-coatings.snapshots': Unable to apply wagon configuration.
at org.apache.maven.artifact.manager.DefaultWagonManager.configureWagon(DefaultWagonManager.java:1004)
at org.apache.maven.artifact.manager.DefaultWagonManager.configureWagon(DefaultWagonManager.java:980)
at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:400)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifactMetadataFromDeploymentRepository(DefaultWagonManager.java:379)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.getArtifactMetadataFromDeploymentRepository(DefaultRepositoryMetadataManager.java:380)
at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolveAlways(DefaultRepositoryMetadataManager.java:348)
... 16 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter nor field in org.apache.maven.wagon.providers.http.LightweightHttpWagon for 'wagonProvider'
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.\<init>(ComponentValueSetter.java:68)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:134)
at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:54)
at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:47)
at org.apache.maven.artifact.manager.DefaultWagonManager.configureWagon(DefaultWagonManager.java:993)
... 21 more

When I tried to execute "mvn -Dmaven.wagon.provider.http=httpclient clean install" from Hudson, it did not work either. Did I miss something? Thank you.

---

**Affects:** 2.2.1

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Are you using the embedded Maven in Hudson by any chance?

**Comment by jira-importer** [comment]
**[Brian Ko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=briankous)** commented

Brett,

No, I am not.   I am using maven 2.2.1 and it is invoked from Hudson.  I changed MAVEN_OPTS and displayed the memory configuration during the build process to the console to verify MAVEN_OPTS was passed properly.

Thank you for quick reply.

Brian Ko

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I'll have to check the ITs for this to make sure the documentation is correct.

In the mean time, you can have effectively the same thing by using a URL like this:

dav:http://...

**Comment by jira-importer** [comment]
**[Brian Ko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=briankous)** commented

I am testing it now  with dav:http://...
My maven-deploy-plugin is 2.4. Thank you.

**Comment by jira-importer** [comment]
**[Brian Ko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=briankous)** commented

I tried with maven-deploy-plugin 2.5. But it does not work either.
It is working with dav:http://...  Thank you.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014
