### ISSUE TITLE
[MNG-4520] TOTSP GWT plugin fails to build GWT apps with Maven 3

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6181]
**[Basil James Whitehouse III](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jwhitehouse)** opened **[MNG-4520](https://issues.apache.org/jira/browse/MNG-4520?redirect=false)** and commented

The attached sample project builds successfully with Maven 2.0.9 but fails with Maven 3.0-alpha-5.  Note I got the same results with the [staged 3.0-alpha-6](https://repository.apache.org/content/repositories/maven-014/org/apache/maven/apache-maven/3.0-alpha-6/) which is used to produce the log in the sample.  I've attached logs for running with Maven 2.0.9 and Maven 3 alpha.

I used separate local repos for building with Maven 2 & 3 to isolate artifacts.

I'm using a feature of the gwt plugin to automatically setup the GWT tools to compile the source.  This downloads the platform specific archive, extracts it to the target directory, and then invokes GWTs platform specific complier.

Under Maven 2 the gwt plugin goal of setup adds the platform specific gwt archive to the dependencies for the next extractGwt goal to locate and extract the gwt build tools.  Under Maven 3 I don't see this same dependency being added.

I know there are newer versions of this plugin and the Codehaus one supersedes it, but I can't change the project at this point.

To run you'll need to add the repo and plugin repo to the pom or settings.xml (or repo manager):
http://gwt-maven.googlecode.com/svn/trunk/mavenrepo/

**Maven 2**
$ mvn -X --batch-mode -Dmaven.repo.local=$(pwd)/repos/m2-gwt-plugin clean install | tee mvn2-build.output
\<snip>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28 seconds
[INFO] Finished at: Wed Jan 06 11:57:44 EST 2010
[INFO] Final Memory: 18M/128M
[INFO] ------------------------------------------------------------------------

**Maven 3**
$ mvn3 -X --batch-mode -Dmaven.repo.local=$(pwd)/repos/m3-gwt-plugin clean install | tee mvn3-build.output
\<snip>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.924s
[INFO] Finished at: Wed Jan 06 11:58:59 EST 2010
[INFO] Final Memory: 4M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.totsp.gwt:maven-googlewebtoolkit2-plugin:2.0-beta15:extractGwt (compile-gwt) on project maven3-gwt-example: Error:  Could not load GWT artifact.  Make sure you have the setup goal enabled for this plugin or that you have setup a dependency on com.google.gwt:gwt-linux -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.totsp.gwt:maven-googlewebtoolkit2-plugin:2.0-beta15:extractGwt (compile-gwt) on project maven3-gwt-example: Error:  Could not load GWT artifact.  Make sure you have the setup goal enabled for this plugin or that you have setup a dependency on com.google.gwt:gwt-linux

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:570)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:247)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:104)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:422)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:157)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

Caused by: org.apache.maven.plugin.MojoExecutionException: Error:  Could not load GWT artifact.  Make sure you have the setup goal enabled for this plugin or that you have setup a dependency on com.google.gwt:gwt-linux

    at com.totsp.mavenplugin.gwt.GWTExtractor.execute(GWTExtractor.java:152)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:562)
    ... 14 more

[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

---

**Affects:** 3.0-alpha-5

**Attachments:**
- [m3-gwt-example.zip](https://issues.apache.org/jira/secure/attachment/12712335/m3-gwt-example.zip) (_29.49 kB_)
- [pom-for-codehaus-gwt.xml](https://issues.apache.org/jira/secure/attachment/12712961/pom-for-codehaus-gwt.xml) (_1.80 kB_)

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

why not move to http://mojo.codehaus.org/gwt-maven-plugin ?
I'm not sure the one you are using is still supported.

**Comment by jira-importer** [comment]
**[Basil James Whitehouse III](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jwhitehouse)** commented

Olivier, the totsp plugin has been merged into the codehaus one and you are correct in that the version that I cited is no longer supported.  Unfortunately there are several large GWT projects that don't have the bandwidth to change and verify the switch at the moment (some being in maintenance only mode).

I filed this to highlight an incompatible change between Maven 2 and Maven 3 but I understand if it won't be fixed if the codehaus plugin works correctly.  FWIW I tested the same project with Maven 3-alpha5 and the Codehaus GWT plugin version 1.1 and it build successfully with minor pom modifications required.  This project is only the sample one that comes with GWT so I don't expect it to be exhaustive but a good sign none-the-less.  I've attached the pom for this for future reference.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

The plugin itself is broken and works only by incident in Maven 2. E.g. add an execution of the maven-enforcer-plugin in front of the gwt plugin and see it fall apart in Maven 2 as well.
