### ISSUE TITLE
[MNG-4906] maven3+tycho build fails: can't find plugin with name "<plugin_name>_null"

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6212]
**[ask](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ask_12345)** opened **[MNG-4906](https://issues.apache.org/jira/browse/MNG-4906?redirect=false)** and commented

tried building my project with last Maven 3.0 + Tycho.
build failed with a weird error:

[INFO] Resolving target platform for project MavenProject: org.alskor.taskconverter:org.alskor.mspsync.rcp:1.0.0-SNAPSHOT @ C:\mspsync\org.alskor.msps
ync.rcp\pom.xml
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve plugin org.alskor.mspsync.rcp_null; Path to dependency: -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve plugin org.alskor.mspsync.rcp_null; Path to dep
endency:

    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:163)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

Caused by: java.lang.RuntimeException: Could not resolve plugin org.alskor.mspsync.rcp_null; Path to dependency:

    at org.codehaus.tycho.ArtifactDependencyVisitor.newRuntimeException(ArtifactDependencyVisitor.java:38)
    at org.codehaus.tycho.ArtifactDependencyVisitor.missingPlugin(ArtifactDependencyVisitor.java:27)
    at org.codehaus.tycho.osgitools.AbstractArtifactDependencyWalker.traversePlugin(AbstractArtifactDependencyWalker.java:240)
    at org.codehaus.tycho.osgitools.AbstractArtifactDependencyWalker.traverseProduct(AbstractArtifactDependencyWalker.java:115)
    at org.codehaus.tycho.osgitools.AbstractArtifactDependencyWalker.traverseProduct(AbstractArtifactDependencyWalker.java:98)
    at org.codehaus.tycho.osgitools.EclipseApplicationProject$1.walk(EclipseApplicationProject.java:28)
    at org.codehaus.tycho.osgitools.AbstractArtifactBasedProject.resolve(AbstractArtifactBasedProject.java:43)
    at org.codehaus.tycho.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:80)
    at org.codehaus.tycho.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:94)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:268)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:151)
    ... 11 more

---

**Affects:** 3.0

**Attachments:**
- [debug.log](https://issues.apache.org/jira/secure/attachment/12713142/debug.log) (_19.51 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12713212/pom.xml) (_619 bytes_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12712598/pom.xml) (_1.71 kB_)

**Comment by jira-importer** [comment]
**[ask](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ask_12345)** commented

the parent POM.xml file

**Comment by jira-importer** [comment]
**[ask](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ask_12345)** commented

org.alskor.mspsync.rcp\pom.xml file

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Please report this at https://issues.sonatype.org/browse/TYCHO.

**Comment by jira-importer** [comment]
**[ask](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ask_12345)** commented

the problem disappears if I remove "org.alskor.mspsync.rcp" from the build:

\

**Comment by jira-importer** [comment]
**[ask](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ask_12345)** commented

oh.... Tried to register at their website too, and got runtime exception from their Jira.
