### ISSUE TITLE
[MNG-4512] [regression] Profile activation based on JDK version range fails if current version is close to range boundary

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6216]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-4512](https://issues.apache.org/jira/browse/MNG-4512?redirect=false)** and commented

The POM snippet

```xml
<profiles>
  <profile>
    <id>test</id>
    <activation>
      <jdk>[1.5,1.6)</jdk>
    </activation>
  </profile>
</profiles>
```

yields

```
[ERROR]   The project org.apache.maven.its.mng:test:0.1 has 1 error
[ERROR]     Failed to determine activation for profile test: For input string: "0_07"
java.lang.NumberFormatException: For input string: "0_07"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
        at java.lang.Integer.parseInt(Integer.java:456)
        at java.lang.Integer.parseInt(Integer.java:497)
        at o.a.m.model.profile.activation.JdkVersionProfileActivator.getRelationOrder(JdkVersionProfileActivator.java:124)
        at o.a.m.model.profile.activation.JdkVersionProfileActivator.isInRange(JdkVersionProfileActivator.java:96)
        at o.a.m.model.profile.activation.JdkVersionProfileActivator.isActive(JdkVersionProfileActivator.java:70)
```

when run with JDK 1.6.0_07 in this case.

---

**Affects:** 3.0-alpha-5

**Issue Links:**
- [MNG-1957](https://issues.apache.org/jira/browse/MNG-1957) \<jdk>\</jdk> clause in the activation section has to provide more complex expressions.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r895185](http://svn.apache.org/viewvc?view=revision&revision=895185).
