### ISSUE TITLE
[MNG-4865] mvn fails because of null property

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6237]
**[eric zhu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laozhuking)** opened **[MNG-4865](https://issues.apache.org/jira/browse/MNG-4865?redirect=false)** and commented

I downloaded maven and ran 'maven -version' under 'C:\workplace\apache-maven-2.2.1\bin'
Got the error:
java.lang.NullPointerException: key can't be null
at java.lang.System.checkKey(System.java:771)
at java.lang.System.getProperty(System.java:647)
at org.codehaus.classworlds.Configurator.configure(Configurator.java:240)
at org.codehaus.classworlds.Launcher.configure(Launcher.java:156)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:426)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

I ran the same on another XP PC with the same source, everything worked fine

---

**Affects:** 2.2.1

**Issue Links:**
- [MNG-4924](https://issues.apache.org/jira/browse/MNG-4924) Running Maven 2.2.1 in Linux gives nullpointerexception
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Alexey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alexeydirect)** commented

Hello Eric, can you post your M2_HOME and JAVA_HOME on Vista machine?

I try running Maven 2.2.1 on Windows Vista 32 and it's worked fine.

**Comment by jira-importer** [comment]
**[eric zhu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laozhuking)** commented

Hi, Alexey

I reinstalled my OS today to XP. But the error just won't give up.
JAVA_HOME: C:\Java\jdk1.6.0_07
M2_HOME: C:\Workplace\apache-maven-2.2.1

**Comment by jira-importer** [comment]
**[eric zhu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laozhuking)** commented

I have found the root cause.
I added one line in m2.conf
set MAVEN_OPTS=-Xmx1024m -XX:MaxPermSize=256m
