### ISSUE TITLE
[MNG-4858] NullPointerException if goal name is malformed

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6248]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** opened **[MNG-4858](https://issues.apache.org/jira/browse/MNG-4858?redirect=false)** and commented

Typing a goal like:

```
mvn help:
```

or

```
mvn group:artifact:version:goal:onetoomany
```

Results in:

```
[ERROR] NullPointerException
java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.findPlugin(MojoDescriptorCreator.java:288)
	at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.injectPluginDeclarationFromProject(MojoDescriptorCreator.java:268)
	at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescriptor(MojoDescriptorCreator.java:211)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:106)
	at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:86)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:98)
```

In Maven 2.2.1, it produced an error message to adjust the goal format.

---

**Affects:** 3.0

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

Fixed in r1005860. After discussing with Benjamin, decided not to go for an IllegalArgumentException as it would not represent a clear error link to the user receiving it. Instead, the empty goal or overspecified goal (goal:toomany) are sent to the MojoNotFoundException so the user ends up getting back valid choices of goals from the plugin in question.
