### ISSUE TITLE
[MNG-4861] Maven 3 and Surefire plugin 2.6 fail to execute tests that use a custom runner (e.g ClasspathSuite)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6255]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** opened **[MNG-4861](https://issues.apache.org/jira/browse/MNG-4861?redirect=false)** and commented

In XWiki we're using ClasspathSuite (http://johanneslink.net/projects/cpsuite.jsp) in a AllTests file. This works fine with Maven 2.2.1 and Surefire plugin 2.6.

When using Maven 3.0 the test fails to run with the following error:

```
java.lang.Exception: Custom runner class ClasspathSuite should have a public constructor with signature ClasspathSuite(Class testClass)
        at org.junit.internal.runners.InitializationError.<init>(InitializationError.java:19)
        at org.junit.internal.requests.ClassRequest.buildRunner(ClassRequest.java:36)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:28)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:51)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:120)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:103)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:169)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
```

To reproduce you can check out and build (you'll need to have XWiki's remote repo in your settings.xml, see http://dev.xwiki.org/xwiki/bin/view/Community/Building):
http://svn.xwiki.org/svnroot/xwiki/enterprise/trunk/distribution-test/ui-tests/

Thanks

---

**Affects:** 3.0

**Comment by jira-importer** [comment]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** commented

The problem was that we had 2 conflicting jars in the classpath: junit-4.8.2.jar and junit-dep-4.4.jar (drawn by some dependency transitively). I assume that for some reason the classpath is created differently with maven2 and maven3 (the order is probably not the same one). This could be a problem in itself but another issue should be created for this and I'll leave it to committers more in the know to decide if this is a bug or not.

Thanks
