### ISSUE TITLE
[MNG-4844] Maven 3 RC1 crashes with IBM JDK 6

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6262]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** opened **[MNG-4844](https://issues.apache.org/jira/browse/MNG-4844?redirect=false)** and commented

Running the minimal project that is provided crashes maven with this error:

[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:315)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:600)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.NullPointerException
at org.sonatype.aether.util.graph.transformer.JavaEffectiveScopeCalculator.getInheritedScopes(JavaEffectiveScopeCalculator.java:149)
at org.sonatype.aether.util.graph.transformer.JavaEffectiveScopeCalculator.resolve(JavaEffectiveScopeCalculator.java:126)
at org.sonatype.aether.util.graph.transformer.JavaEffectiveScopeCalculator.transformGraph(JavaEffectiveScopeCalculator.java:80)
at org.sonatype.aether.util.graph.transformer.ChainedDependencyGraphTransformer.transformGraph(ChainedDependencyGraphTransformer.java:76)
at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:246)
at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:265)
at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:117)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:165)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:104)
at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:244)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:187)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:140)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)

All the details are in the readme.txt in the attached zip file.

---

**Attachments:**
- [mvn3-crash.zip](https://issues.apache.org/jira/secure/attachment/12713245/mvn3-crash.zip) (_1.91 kB_)

**Issue Links:**
- [MNG-4798](https://issues.apache.org/jira/browse/MNG-4798) NullPointerException at NearestVersionConflictResolver.selectVersion()
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Known bug in the IBM/Harmony class library, please try [3.0-RC3](https://repository.apache.org/content/repositories/maven-014/org/apache/maven/apache-maven/3.0-RC3/) where we added a workaround.
