### ISSUE TITLE
[MNG-4832] Maven 3 Regression: Missing constructor of org.codehaus.plexus.component.configurator.converters.special.ClassRealmConverter

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6280]
**[Brian Jackson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jaxzin)** opened **[MNG-4832](https://issues.apache.org/jira/browse/MNG-4832?redirect=false)** and commented

I reported MNG-4811 and it was fixed for 3.0-RC2 but introduced a new error.  The source for com.espn.maven.plugins.espnservice.IncludeProjectDependenciesComponentConfigurator is attached to MNG-4811.  The exception I'm seeing is below:

Caused by: java.lang.NoSuchMethodError: org.codehaus.plexus.component.configurator.converters.special.ClassRealmConverter.\<init>(Lorg/codehaus/classworlds/ClassRealm;)V
at com.espn.maven.plugins.espnservice.IncludeProjectDependenciesComponentConfigurator.configureComponent(IncludeProjectDependenciesComponentConfigurator.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.component.configurator.AbstractComponentConfigurator.configureComponent(AbstractComponentConfigurator.java:90)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:505)
... 22 more

---

**Affects:** 3.0

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Another side note about your converter or any other custom converter you write: You very likely don't need the following line for your mojo:

```java
converterLookup.registerConverter(new ClassRealmConverter(containerRealm));
```

In the basic converter, it exists only for backward-compat and I'm not aware of any valid use case that requires it.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r1001090](http://svn.apache.org/viewvc?view=revision&revision=1001090).

**Comment by jira-importer** [comment]
**[Brian Jackson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jaxzin)** commented

Thanks Ben for your help.  I confirmed with 3.0-RC3 that my plugin now works as-is with no apparent regressions.  I will refactor with your suggestions ASAP, but its nice to see it work untouched in a 3.0 release.
