### ISSUE TITLE
[MNG-4806] Building my eclipse rcp application results in an InternalErrorException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6294]
**[Andreas Wuest](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kickmetondy)** opened **[MNG-4806](https://issues.apache.org/jira/browse/MNG-4806?redirect=false)** and commented

Hi,

i am trying to build my rcp application with the tycho plugin. however all targets fail with:
Following the instructions on the wiki page i reported the issue (see attachment for full log)!

{org.osgi.framework.executionenvironment=OSGi/Minimum-1.0,OSGi/Minimum-1.1, osgi.ws=win32, osgi.arch=x86, osgi.os=win32, org.eclipse.update.install.features=true, org.osgi.framework.system.packages=}
[Software being installed: demoapp 0.1.0.SNAPSHOT, Missing requirement: demoapp 0.1.0.SNAPSHOT requires 'bundle javax.persistence 0.0.0' but it could not be found]
[ERROR] Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable.
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:164)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)

---

**Affects:** 3.0-beta-3

**Attachments:**
- [log.txt](https://issues.apache.org/jira/secure/attachment/12713039/log.txt) (_8.46 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable.
> This is a P2/Tycho issue, so pleas fill this at https://issues.sonatype.org/browse/TYCHO instead.
