### ISSUE TITLE
[MNG-4813] org.jboss.maven.plugins:maven-jdocbook-plugin:2.1.1:generate fails with Maven 3.0-RC1

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6302]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** opened **[MNG-4813](https://issues.apache.org/jira/browse/MNG-4813?redirect=false)** and commented

Module to reproduce : https://anonsvn.jboss.org/repos/exo-jcr/jcr/trunk/docs/reference/en
You'll probably need this repo to build : http://repository.exoplatform.org/public
The error :

```
[INFO] --- maven-jdocbook-plugin:2.1.1:generate (default-generate) @ reference-docs-en ---
Error at xsl:import on line 12 of jar:file:/Users/arnaud/.m2/repository/org/exoplatform/doc/exo-docbook-xslt/1/exo-docbook-xslt-1.jar!/xslt/org/exojcr/xhtml.xsl:
  Malformed URL classpath:/xslt/org/jboss/xhtml.xsl(base jar:file:/Users/arnaud/.m2/repository/org/exoplatform/doc/exo-docbook-xslt/1/exo-docbook-xslt-1.jar!/xslt/org/exojcr/xhtml.xsl): unknown protocol: classpath
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.898s
[INFO] Finished at: Thu Sep 16 22:13:39 CEST 2010
[INFO] Final Memory: 7M/125M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jboss.maven.plugins:maven-jdocbook-plugin:2.1.1:generate (default-generate) on project reference-docs-en: XSLT problem: unable to build transformer [null] : Failed to compile stylesheet. 1 error detected. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jboss.maven.plugins:maven-jdocbook-plugin:2.1.1:generate (default-generate) on project reference-docs-en: XSLT problem
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:203)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:140)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:315)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: XSLT problem
	at org.jboss.maven.plugins.jdocbook.AbstractDocBookMojo.execute(AbstractDocBookMojo.java:285)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:107)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:195)
	... 19 more
Caused by: org.jboss.jdocbook.xslt.XSLTException: unable to build transformer [null] : Failed to compile stylesheet. 1 error detected.
	at org.jboss.jdocbook.xslt.TransformerBuilder.buildTransformer(TransformerBuilder.java:94)
	at org.jboss.jdocbook.xslt.TransformerBuilder.buildTransformer(TransformerBuilder.java:78)
	at org.jboss.jdocbook.render.impl.BasicRenderer.buildTransformer(BasicRenderer.java:139)
	at org.jboss.jdocbook.render.impl.BasicRenderer.performRendering(BasicRenderer.java:119)
	at org.jboss.jdocbook.render.impl.BasicRenderer.render(BasicRenderer.java:115)
	at org.jboss.maven.plugins.jdocbook.GenerationMojo.process(GenerationMojo.java:117)
	at org.jboss.maven.plugins.jdocbook.AbstractDocBookMojo.doExecute(AbstractDocBookMojo.java:250)
	at org.jboss.maven.plugins.jdocbook.AbstractDocBookMojo.execute(AbstractDocBookMojo.java:282)
	... 21 more
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
	at com.icl.saxon.PreparedStyleSheet.prepare(PreparedStyleSheet.java:136)
	at com.icl.saxon.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:127)
	at com.icl.saxon.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:79)
	at org.jboss.jdocbook.xslt.TransformerBuilder.buildTransformer(TransformerBuilder.java:88)
	... 28 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

It works fine with Maven 2.2.1
It fails with 3.0-RC1 but all betas too.
I didn't test with alpha.

---

**Affects:** 3.0-alpha-6, 3.0-alpha-7, 3.0-beta-1, 3.0-beta-2, 3.0-beta-3

**Issue Links:**
- [MNG-4514](https://issues.apache.org/jira/browse/MNG-4514) Loading resource from plugin dependency using Plexus ResourceManager fails with leading slash

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Turns out to be a bug in `org.jboss.jdocbook.xslt.resolve.ClasspathResolver` which passes invalid resource names into `ClassLoader.getResource()`:

```
public Source resolve(String href, String base) throws TransformerException {
  // href would need to start with classpath:
  if ( !href.startsWith( "classpath:" ) ) {
    return null;
  }
  
  try {
    URL url = classLoader.getResource( href.substring(10) );
    return new StreamSource( url.openStream(), url.toExternalForm() );
  }
  catch ( Throwable t ) {
    return null;
  }
}
```

e.g. for "classpath:/xslt/org/jboss/xhtml-single.xsl", the class loader is asked for "/xslt/org/jboss/xhtml-single.xsl" (note the leading slash) instead of "xslt/org/jboss/xhtml-single.xsl".

**Comment by jira-importer** [comment]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** commented

But the question is why does it work with Maven 2.x ??
I didn't have the time to test more recent versions of this plugin to see if the code was improved.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Because Maven 2.x employs unusual class loaders.
