### ISSUE TITLE
[MNG-4799] Checkstyle can not find org.codehaus.plexus.personality.plexus.lifecycle.phase.ServiceLocator

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6304]
**[Dennis Brennan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisbrennan)** opened **[MNG-4799](https://issues.apache.org/jira/browse/MNG-4799?redirect=false)** and commented

Checkstyle had no issues with the same config in beta-2.  Upgrading to beta-3 breaks checkstyle with the following stacktrace...

Number of foreign imports: 4
import: Entry[import org.codehaus.plexus.util.xml.pull.XmlSerializer from realm ClassRealm[plexus.co
re, parent: null]]
import: Entry[import org.codehaus.plexus.util.xml.pull.XmlPullParserException from realm ClassRealm[
plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.xml.pull.XmlPullParser from realm ClassRealm[plexus.co
re, parent: null]]
import: Entry[import org.codehaus.plexus.util.xml.Xpp3Dom from realm ClassRealm[plexus.core, parent:
null]]

realm =    maven.api
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 21
import: Entry[import org.sonatype.aether from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.personality from realm ClassRealm[plexus.core, parent: null
]]
import: Entry[import org.codehaus.plexus.logging from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.lifecycle from realm ClassRealm[plexus.core, parent: null]]

import: Entry[import org.codehaus.plexus.context from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.container from realm ClassRealm[plexus.core, parent: null]]

import: Entry[import org.codehaus.plexus.configuration from realm ClassRealm[plexus.core, parent: nu
ll]]
import: Entry[import org.codehaus.plexus.component from realm ClassRealm[plexus.core, parent: null]]

import: Entry[import org.codehaus.plexus.classworlds from realm ClassRealm[plexus.core, parent: null
]]
import: Entry[import org.codehaus.plexus.PlexusContainerException from realm ClassRealm[plexus.core,
parent: null]]
import: Entry[import org.codehaus.plexus.PlexusContainer from realm ClassRealm[plexus.core, parent:
null]]
import: Entry[import org.codehaus.plexus.PlexusConstants from realm ClassRealm[plexus.core, parent:
null]]
import: Entry[import org.codehaus.plexus.MutablePlexusContainer from realm ClassRealm[plexus.core, p
arent: null]]
import: Entry[import org.codehaus.plexus.DuplicateChildContainerException from realm ClassRealm[plex
us.core, parent: null]]
import: Entry[import org.codehaus.plexus.DefaultPlexusContainer from realm ClassRealm[plexus.core, p
arent: null]]
import: Entry[import org.codehaus.plexus.DefaultContainerConfiguration from realm ClassRealm[plexus.
core, parent: null]]
import: Entry[import org.codehaus.plexus.DefaultComponentRegistry from realm ClassRealm[plexus.core,
parent: null]]
import: Entry[import org.codehaus.plexus.ContainerConfiguration from realm ClassRealm[plexus.core, p
arent: null]]
import: Entry[import org.codehaus.plexus.ComponentRegistry from realm ClassRealm[plexus.core, parent
: null]]
import: Entry[import org.codehaus.classworlds from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.apache.maven from realm ClassRealm[plexus.core, parent: null]]

---

    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMaven

PluginManager.java:412)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.j
ava:96)
... 20 more
Caused by: java.lang.NoClassDefFoundError: Lorg/codehaus/plexus/personality/plexus/lifecycle/phase/S
erviceLocator;
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Class.java:2259)
at java.lang.Class.getDeclaredFields(Class.java:1715)
at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:649)
at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)

    at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBind

ingImpl.java:151)
at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:559)
at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:517)
at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:503)
at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:812)
at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.jav
a:744)
at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:233)
at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:184)
at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:818)
at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:932)
at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:965)
at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:926)
at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:978)
at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProvider
Adapter.java:40)
at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:943)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:989)
at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:939)
at com.google.inject.Scopes$1$1.get(Scopes.java:63)
at org.sonatype.guice.bean.locators.QualifiedBean.getValue(QualifiedBean.java:85)
at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:55)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:234)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:226)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMaven
PluginManager.java:393)
... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following arti
cles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

---

**Affects:** 3.0-beta-3

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

which version of the checkstyle plugin are you using ?
You have to use 2.5 with maven 3.x

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

An example POM would be highly appreciated. In particular, the snippet above does not even tell us what exact version of the plugin is used which makes reproduction an unnecessary guess work.

**Comment by jira-importer** [comment]
**[Dennis Brennan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisbrennan)** commented

This is happening with version 2.3 of the maven-checkstyle-plugin

**Comment by jira-importer** [comment]
**[Dennis Brennan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisbrennan)** commented

If 2.3 is not compatible, it may be a good idea to update this page: https://cwiki.apache.org/MAVEN/maven-3x-plugin-compatibility-matrix.html

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

have a look here https://cwiki.apache.org/confluence/x/sokr
