### ISSUE TITLE
[MNG-4798] NullPointerException at NearestVersionConflictResolver.selectVersion()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6317]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** opened **[MNG-4798](https://issues.apache.org/jira/browse/MNG-4798?redirect=false)** and commented

this error only occurs with Maven 3 beta-3 but not Maven 3 beta-2.

Maby it is related to this error, but has a different stacktrace: MNG-4779

[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:141)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:99)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:315)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:600)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.NullPointerException
at org.sonatype.aether.util.graph.transformer.NearestVersionConflictResolver.selectVersion(NearestVersionConflictResolver.java:218)
at org.sonatype.aether.util.graph.transformer.NearestVersionConflictResolver.transformGraph(NearestVersionConflictResolver.java:81)
at org.sonatype.aether.util.graph.transformer.ChainedDependencyGraphTransformer.transformGraph(ChainedDependencyGraphTransformer.java:76)
at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:246)
at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:265)
at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:117)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:202)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:141)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveDependencies(LifecycleDependencyResolver.java:118)
at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveDependencies(LifecycleDependencyResolver.java:82)
at org.apache.maven.lifecycle.internal.BuilderCommon.resolveBuildPlan(BuilderCommon.java:130)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:83)
... 16 more

---

**Affects:** 3.0-beta-3

**Issue Links:**
- [MNG-4794](https://issues.apache.org/jira/browse/MNG-4794) 'org.apache.maven.plugins:maven-install-plugin:2.3.1'. A required class is missing: org.codehaus.plexus.digest.Digester
 (_**"duplicates"**_)
- [MNG-4844](https://issues.apache.org/jira/browse/MNG-4844) Maven 3 RC1 crashes with IBM JDK 6
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Any chance of an example project?

**Comment by jira-importer** [comment]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** commented

same project.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

I can't follow, same project from what? And what exactly is the relation to MNG-4794 that shows a completely different error output?

**Comment by jira-importer** [comment]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** commented

Sorry, for my short comment.
If I run mvn clean install I'll get MNG-4794
If I run mvn clean package I'll get MNG-4798 (this issue)

It is the same maven multiproject from within I call maven.
It ONLY happens with Maven 3 Beta-3 and NOT with Beta-2.
It ONLY happens on my Linux Server and not on my Windows Notebook. (Same Java Version).

I don't have an example project currently.
What else can I do for you? Providing debug output?

I thought, maybe my Maven 3 Beta-3 installation (from tar.gz) is broken, but I'll get the same error from another installtion out of the zip-archive.

What else can be plattform specific? Or can be corrupt on my Linux-Server?
I'll try to run it on another Linux-Installation to check it there.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> What else can I do for you? Providing debug output?
> Yes, that's always a help as it gives some more context. In particular, if MNG-4794 is reproducible for you, I would like to see the debug from a failing "mvn clean install" against an empty local repo (or at least one, where the maven-install-plugin has been completely deleted).

**Comment by jira-importer** [comment]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** commented

I found the cause of this problem!
On the SLES Server there were two JDK's installed. The Sun JDK and an IBM JDK.

JAVA_HOME was pointing to the IBM-JDK and in the PATH the Sun JDK was first:
output of: mvn -version
Apache Maven 3.0-beta-3 (r990787; 2010-08-30 14:44:03+0200)
Java version: 1.6.0
Java home: /usr/lib/jvm/java-1_6_0-ibm-1.6.0/jre
Default locale: de_DE, platform encoding: ISO-8859-1
OS name: "linux" version: "2.6.27.48-0.6-pae" arch: "x86" Family: "unix"

output of (Sun JDK): java -version
java version "1.6.0_21"
Java(TM) SE Runtime Environment (build 1.6.0_21-b06)
Java HotSpot(TM) Client VM (build 17.0-b16, mixed mode, sharing)

output of (IBM-JDK): /usr/lib/jvm/java-1_6_0-ibm-1.6.0/jre/java -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxi3260sr8-20100409_01(SR8))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux x86-32 jvmxi3260sr8-20100401_55940 (JIT enabled, AOT enabled)
J9VM - 20100401_055940
JIT  - r9_20100401_15339
GC   - 20100308_AA)
JCL  - 20100408_01

Then I changed the JAVA_HOME to the Sun-JDK and it works. Afterwards I changed the JAVA_HOME and the PATH to the IBM-JDK and I'm getting the exception again.

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Please fill this as a bug against the JDK vendor.

**Comment by jira-importer** [comment]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** commented

Couple more stack traces from IBM JDK

igor@desktop:/code/sonatype-aether$ $JAVA_HOME/bin/java -version
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxa6460sr8fp1-20100624_01(SR8 FP1))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux amd64-64 jvmxa6460sr8ifx-20100609_59383 (JIT enabled, AOT enabled)
J9VM - 20100609_059383
JIT  - r9_20100401_15339ifx2
GC   - 20100308_AA)
JCL  - 20100624_01

Building current maven 3.0 trunk with 3.0-RC1

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.436s
[INFO] Finished at: Fri Sep 17 11:18:49 EDT 2010
[INFO] Final Memory: 7M/20M
[INFO] ------------------------------------------------------------------------
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:315)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:600)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.NullPointerException
	at org.sonatype.aether.util.graph.transformer.JavaEffectiveScopeCalculator.resolve(JavaEffectiveScopeCalculator.java:134)
	at org.sonatype.aether.util.graph.transformer.JavaEffectiveScopeCalculator.transformGraph(JavaEffectiveScopeCalculator.java:80)
	at org.sonatype.aether.util.graph.transformer.ChainedDependencyGraphTransformer.transformGraph(ChainedDependencyGraphTransformer.java:76)
	at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:246)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:265)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:165)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:104)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:244)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:187)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:140)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	... 16 more
```

building aether with 3.0-RC1

```

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.2:install (default-install) on project aether-parent: Execution default-install of goal org.apache.maven.plugins:maven-install-plugin:2.2:install failed: Unable to load the mojo 'install' in the plugin 'org.apache.maven.plugins:maven-install-plugin:2.2'. A required class is missing: org.codehaus.plexus.digest.Digester
-----------------------------------------------------
realm =    plugin>org.apache.maven.plugins:maven-install-plugin:2.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/igor/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.2/maven-install-plugin-2.2.jar
urls[1] = file:/home/igor/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
Number of foreign imports: 4
import: Entry[import org.codehaus.plexus.util.xml.pull.XmlSerializer from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.xml.pull.XmlPullParserException from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.xml.pull.XmlPullParser from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.xml.Xpp3Dom from realm ClassRealm[plexus.core, parent: null]]

realm =    maven.api
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
Number of foreign imports: 21
import: Entry[import org.sonatype.aether from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.personality from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.logging from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.lifecycle from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.context from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.container from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.configuration from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.component from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.classworlds from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.PlexusContainerException from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.PlexusContainer from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.PlexusConstants from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.MutablePlexusContainer from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.DuplicateChildContainerException from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.DefaultPlexusContainer from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.DefaultContainerConfiguration from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.DefaultComponentRegistry from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.ContainerConfiguration from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.ComponentRegistry from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.classworlds from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.apache.maven from realm ClassRealm[plexus.core, parent: null]]

-----------------------------------------------------
-> [Help 1]
```

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Stuart McCulloch debugged this and tracked it down to [HARMONY-6419](https://issues.apache.org/jira/browse/HARMONY-6419) which affects the `ConflictMarker.mark()` method from Aether.
