### ISSUE TITLE
[MNG-4773] Stack trace printed from MavenProject.getParent

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6322]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** opened **[MNG-4773](https://issues.apache.org/jira/browse/MNG-4773?redirect=false)** and commented

When M3 is embedded inside NetBeans, and a project is missing a local copy of its parent POM, an unwanted stack trace is printed to console:

```
org.apache.maven.project.ProjectBuildingException: Error resolving project artifact: The repository system is offline and the requested artifact is not locally available at ...
  org.glassfish:glassfish-parent:pom:3.1-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2, releases=true, snapshots=false)
 for project org.glassfish:glassfish-parent:pom:3.1-SNAPSHOT
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:244)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:209)
        at org.apache.maven.project.MavenProject.getParent(MavenProject.java:356)
        at <<NetBeans code...>>
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: The repository system is offline and the requested artifact is not locally available at ...
  org.glassfish:glassfish-parent:pom:3.1-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2, releases=true, snapshots=false)

        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:291)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:540)
        at org.apache.maven.repository.legacy.LegacyRepositorySystem.resolve(LegacyRepositorySystem.java:340)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:231)
        ... 14 more
```

Please do not print this stack trace, or send it to a proper logging component where it will be suppressed by default.

---

**Affects:** 3.0-beta-2

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r987610](http://svn.apache.org/viewvc?view=revision&revision=987610).
