### ISSUE TITLE
[MNG-4718] [regression] Missing Class in 3.0-beta-1: org.apache.maven.project.artifact.AttachedArtifact

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6367]
**[Chris Graham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chrisgwarp)** opened **[MNG-4718](https://issues.apache.org/jira/browse/MNG-4718?redirect=false)** and commented

I have a custom plugin that I wrote to support WebSphere Message Broker BAR files.
It works fine under 2.0.9, 2.0.11 and 2.2.1. I tried it under 3.0-beta-1 and got:

```
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:129)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: org.apache.maven.project.artifact.AttachedArtifact
        at com.ibm.issw.maven.plugins.messagebroker.AbstractMessageBrokerMojo.addAttachedArtifact(AbstractMessageBrokerMojo.java:48)
        at com.ibm.issw.maven.plugins.messagebroker.GenerateDeploymentPackages.generateDeploymentPackages(GenerateDeploymentPackages.java:204)
        at com.ibm.issw.maven.plugins.messagebroker.GenerateDeploymentPackages.execute(GenerateDeploymentPackages.java:62)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
        ... 20 more
```

The code that is calling it is:

```java
/**
 * Add an additional file artefact to the Maven project.
 * @param artefactFile The file to add.
 * @param classifier A classifier.
 * @param extension The file type extension.
 */
protected void addAttachedArtifact(String artefactFile, String classifier, final String extension)
{
    Artifact artifact = new AttachedArtifact(project.getArtifact(), project.getPackaging(), classifier, new DefaultArtifactHandler()
    {
        public String getExtension()
        {
            return extension;
        }
    });
    artifact.setFile(new File(artefactFile));
    artifact.setResolved(true);
    project.addAttachedArtifact(artifact);
}
```

It's failing on the first line of the method (new AttachedArtifact()...).

---

**Affects:** 3.0-beta-1

**Attachments:**
- [build.log](https://issues.apache.org/jira/secure/attachment/12713033/build.log) (_285.45 kB_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r960855](http://svn.apache.org/viewvc?view=revision&revision=960855).

FYI, `AttachedArtifact` is an internal implementation class, you should be using `MavenProjectHelper.attachArtifact()` instead.

**Comment by jira-importer** [comment]
**[Chris Graham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=chrisgwarp)** commented

Thank you for the outstandingly fast resolution!
I've also fixed my code.
Thanks!
-Chris
