### ISSUE TITLE
[MNG-4704] Maven 3.0 beta 1 password decryption log verbosity with FileNotFoundException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6371]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** opened **[MNG-4704](https://issues.apache.org/jira/browse/MNG-4704?redirect=false)** and commented

I'm using decrypted passwords like described here:
http://blogs.jfrog.org/2009/01/avoiding-clear-text-passwords-in-maven.html

It works fine no problem. The only problem I have now, is the log verbosity while using mvn -X or Maven in DEBUG mode.
It prints out hundreds of stack traces and so becomes unusable.

Please change the logging of this kind of messages. Maybe log only the first stack trace and then stop repeating this stack trace printing.

I don't have a settings-security.xml, because I don't need one and so I get this FileNotFoundException stack trace:
[DEBUG] Failed to decrypt password for server central: org.sonatype.plexus.components.sec.dispatcher
.SecDispatcherException: java.io.FileNotFoundException: C:\Dokumente und Einstellungen\stijoc\.m2\
settings-security.xml (Das System kann die angegebene Datei nicht finden)
org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: org.sonatype.plexus.components
.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: C:\Dokumente und Einstellunge
n\stijoc\.m2\settings-security.xml (Das System kann die angegebene Datei nicht finden)
at org.sonatype.plexus.components.sec.dispatcher.DefaultSecDispatcher.decrypt(DefaultSecDisp
atcher.java:121)
at org.apache.maven.settings.crypto.DefaultSettingsDecrypter.decrypt(DefaultSettingsDecrypte
r.java:106)
at org.apache.maven.settings.crypto.DefaultSettingsDecrypter.decrypt(DefaultSettingsDecrypte
r.java:62)
at org.apache.maven.repository.legacy.LegacyRepositorySystem.injectAuthentication(LegacyRepo
sitorySystem.java:477)
at org.apache.maven.project.DefaultProjectBuildingHelper.createArtifactRepositories(DefaultP
rojectBuildingHelper.java:117)
at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled(DefaultMod
elBuildingListener.java:127)
at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire(ModelBuildingEventCatap
ult.java:43)
at org.apache.maven.model.building.DefaultModelBuilder.fireEvent(DefaultModelBuilder.java:88
8)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:288)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:271)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:262)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:129)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:117)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:245)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:204)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetad
ataSource.java:576)
at org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSource.java:1
89)
at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(Defaul
tLegacyArtifactCollector.java:533)
at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.recurse(Defaul
tLegacyArtifactCollector.java:594)
at org.apache.maven.repository.legacy.resolver.DefaultLegacyArtifactCollector.collect(Defaul
tLegacyArtifactCollector.java:150)
at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolve
r.java:590)
at org.apache.maven.repository.legacy.LegacyRepositorySystem.resolve(LegacyRepositorySystem.
java:325)
at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginD
ependenciesResolver.java:123)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMaven
PluginManager.java:324)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenP
luginManager.java:272)
at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManage
r.java:184)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.j
ava:80)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:133)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:77)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:69)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu
ilder.java:82)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu
ilder.java:54)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.singleThreadedBuild(DefaultLifecycleE
xecutor.java:218)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java
:190)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:246)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:95)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:430)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:160)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

---

**Affects:** 3.0-beta-1

**Issue Links:**
- [MNG-4611](https://issues.apache.org/jira/browse/MNG-4611) 3.0-alpha7 password decryption log verbosity
 (_**"duplicates"**_)
- [MNG-4626](https://issues.apache.org/jira/browse/MNG-4626) Password encryption escaped mechanism doesn't work as advertised
 (_**"is superceded by"**_)

**Comment by jira-importer** [comment]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** commented

also a problem with the log verbosity

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

See MNG-4626 instead.
