### ISSUE TITLE
[MNG-4731] NPE from AttachedArtifact.getVersion rather than meaningful error

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6382]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** opened **[MNG-4731](https://issues.apache.org/jira/browse/MNG-4731?redirect=false)** and commented

I am working on a problem with `nbm:populate-repository` (from `org.codehaus.mojo:nbm-maven-plugin`). Maven 2.2.1, when run under certain circumstances, fails when running this goal with the following unhelpful message:

```
...
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
	at org.apache.maven.project.artifact.AttachedArtifact.getVersion(AttachedArtifact.java:122)
	at org.apache.maven.artifact.DefaultArtifact.validateIdentity(DefaultArtifact.java:141)
	at org.apache.maven.artifact.DefaultArtifact.<init>(DefaultArtifact.java:122)
	at org.apache.maven.project.artifact.AttachedArtifact.<init>(AttachedArtifact.java:42)
	at org.codehaus.mojo.nbm.PopulateRepositoryMojo.createAttachedArtifact(PopulateRepositoryMojo.java:617)
	at org.codehaus.mojo.nbm.PopulateRepositoryMojo.execute(PopulateRepositoryMojo.java:424)
...
```

Inspection of the code reveals the immediate cause of the NPE: in `getVersion`, the `parent` field is null. Even though this is a final field set in the constructor to a non-null value, it has not yet been set when the super constructor is called. This is because `DefaultArtifact` uses the antipattern of calling an overridable method (`getVersion`) from its constructor (indirectly via `validateIdentity`). The NPE then prevents the details of the problem from being reported to the user.

Ideally this antipattern would be solved, by making `validateIdentity` public and requiring all creators of a `DefaultArtifact` to call it after construction. Since this cannot now be done compatibly (e.g. `PopulateRepositoryMojo` above would need to be modified), the next best thing is to assume that `AttachedArtifact` is the only subclass, and ensure that `validateIdentity` is called only once the object has been fully constructed. With that change (patch against `2.2.2-SNAPSHOT` attached), the error message is informative (specifics of this run have been elided) and points toward possible problems in the plugin:

```
...
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An invalid artifact was detected.

This artifact might be in your project's POM, or it might have been included transitively
during the resolution process. Here is the information we do have for this artifact:

    o GroupID:     ...
    o ArtifactID:  ...
    o Version:     ...
    o Type:        <<< MISSING >>>

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.artifact.InvalidArtifactRTException: For artifact {...:...:...:null}: The type cannot be empty.
	at org.apache.maven.artifact.DefaultArtifact.validateIdentity(DefaultArtifact.java:141)
	at org.apache.maven.project.artifact.AttachedArtifact.validateIdentity(AttachedArtifact.java:63)
	at org.apache.maven.project.artifact.AttachedArtifact.<init>(AttachedArtifact.java:53)
	at org.codehaus.mojo.nbm.PopulateRepositoryMojo.createAttachedArtifact(PopulateRepositoryMojo.java:617)
	at org.codehaus.mojo.nbm.PopulateRepositoryMojo.execute(PopulateRepositoryMojo.java:424)
...
```

---

**Affects:** 2.2.1

**Attachments:**
- [validateIdentity.diff](https://issues.apache.org/jira/secure/attachment/12713031/validateIdentity.diff) (_3.86 kB_)

**Issue Links:**
- [MNG-6641](https://issues.apache.org/jira/browse/MNG-6641) NPE from AttachedArtifact.getVersion rather than meaningful error
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

As a side note, the stack trace suggests the plugin is directly accessing `AttachedArtifact` which isn't expected either. `MavenProjectHelper.attachArtifact()` should be used instead.

**Comment by jira-importer** [comment]
**[Jesse N. Glick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jglick)** commented

If `AttachedArtifact` is not supposed to be accessed directly by plugins, it should not have been made public I guess. But I will pass on the advice.

**Comment by jira-importer** [comment]
**[Milos Kleint](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkleint)** commented

Benjamin, unfortunately the MavenProjectHelper requires a MavenProject instance as parameter which I don't have for the artifact in this case so I just copied the code from MavenProjectHelper at some point in time.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.

**Comment by jira-importer** [comment]
**[Dale King](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dalewking)** commented

Re-reported as: https://issues.apache.org/jira/browse/MNG-6641
