### ISSUE TITLE
[MNG-4695] Missing Error during pom validation: "You cannot have two plugin executions with the same (or missing) <id/> elements."

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6388]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** opened **[MNG-4695](https://issues.apache.org/jira/browse/MNG-4695?redirect=false)** and commented

Maven 2.2.1 gives an error "You cannot have two plugin executions with the same (or missing) \<id/> elements.", if there are two executions for the same plugin without an id element.
Maven 3.0 beta1 doesn't throw this usefull validation error. It uses the first configuration for both executions.

A relatet issue, where this error has occured with an attached example: http://jira.codehaus.org/browse/MRPM-76

---

**Affects:** 3.0-beta-1

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r949720](http://svn.apache.org/viewvc?view=revision&revision=949720).

**Comment by jira-importer** [comment]
**[ajoe04](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ajoe04)** commented

the maven 2.2.1 console output, that is missing in maven 3.0 beta1

Project ID: apps:config-rpm
POM Location: /home/sti/maven-TRUNK/apps/config-rpm/pom.xml
Validation Messages:

    [0]  You cannot have two plugin executions with the same (or missing) <id/> elements.

Offending execution

Id: 'default'
Plugin:'org.codehaus.mojo:rpm-maven-plugin'

Reason: Failed to validate POM for project apps:config-rpm at /home/sti/maven-TRUNK/apps/config-rpm/pom.xml

[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Failed to validate POM for project config-rpm at /home/sti/maven-TRUNK/apps/config-rpm/pom.xml
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:404)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.InvalidProjectModelException: Failed to validate POM for project nivadis.apps:vbs-polas-config-rpm at /home/sti/maven-TRUNK/apps/config-rpm/pom.xml
at org.apache.maven.project.DefaultMavenProjectBuilder.processProjectLogic(DefaultMavenProjectBuilder.java:1077)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:880)
at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:508)
at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:200)
at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:604)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:487)
at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:391)
... 12 more
