### ISSUE TITLE
[MNG-4659] Strange exception when running Maven from Hudson

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6418]
**[Joe Gamache](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jgamache)** opened **[MNG-4659](https://issues.apache.org/jira/browse/MNG-4659?redirect=false)** and commented

Running Hudson with a LOT of jobs defined.  We recently moved all of our group's jobs up to Maven 2.2.1; however, several other groups still run their jobs with Maven 2.0.9.   Since we made this change, it seems that about once a day we get the exception/stack trace shown below.  Note: all of the jobs in our Hudson environment run as the same user.  To make the error go away, one needs to go the hudson user's .m2/repository directory and type:   rm -rf com
then when you re-run the job it works successfully!  So even though the error seems like a Clover one, because of the fix, I thought it should be reported here.  Sorry if this was a mistake!

[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at com.atlassian.maven.plugin.clover.CloverInstrumentInternalMojo.swizzleCloverDependencies(CloverInstrumentInternalMojo.java:394)
at com.atlassian.maven.plugin.clover.CloverInstrumentInternalMojo.swizzleCloverDependencies(CloverInstrumentInternalMojo.java:345)
at com.atlassian.maven.plugin.clover.CloverInstrumentInternalMojo.execute(CloverInstrumentInternalMojo.java:248)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkProjectLifecycle(DefaultLifecycleExecutor.java:1205)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.forkLifecycle(DefaultLifecycleExecutor.java:1038)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:643)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 minutes 45 seconds
[INFO] Finished at: Tue May 04 09:56:24 EDT 2010
[INFO] Final Memory: 51M/311M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.2.1

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Please report this to the plugin authors, they will contact back the Maven core team if their investigation discovers it's really a core issue and not a plugin bug.
