### ISSUE TITLE
[MNG-4648] NullPointerException thrown from DefaultPluginRealmCache#pluginHashCode method if project-level plugin dependency misses version

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6428]
**[Ivica Loncar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iloncar)** opened **[MNG-4648](https://issues.apache.org/jira/browse/MNG-4648?redirect=false)** and commented

As a user i would like to see better error reporting from DefaultPluginRealmCache#pluginHashCode method

Currently it calculates hash value based on a dependency metadata, but if I omit version it fails with NullPointer exception.

It would be more user friendly to validate metadata prior to calculating hash value and to display more meaningful error to the end user.

Test scenario:
- configure plugin and create dependencies
- add dependency but DO NOT specify version
- run maven such that plugin is invoked
  maven will fail without reporting which dependency doesn't have version

---

**Affects:** 3.0-beta-1

**Issue Links:**
- [MNG-4661](https://issues.apache.org/jira/browse/MNG-4661) NPE in DefaultPluginRealmCache.pluginHashCode()
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

```
[ERROR] NullPointerException
java.lang.NullPointerException
        at org.apache.maven.plugin.DefaultPluginRealmCache.pluginHashCode(DefaultPluginRealmCache.java:161)
        at org.apache.maven.plugin.DefaultPluginRealmCache$CacheKey.<init>(DefaultPluginRealmCache.java:73)
        at org.apache.maven.plugin.DefaultPluginRealmCache.get(DefaultPluginRealmCache.java:114)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:261)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:184)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:80)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:133)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:77)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:69)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:82)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:54)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.singleThreadedBuild(DefaultLifecycleExecutor.java:218)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:190)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:246)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:95)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:430)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:160)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:124)
```

we can safely call this a bug...

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r938410](http://svn.apache.org/viewvc?view=revision&revision=938410).
