### ISSUE TITLE
[MNG-5711] LinkageError org.apache.maven.surefire.shade.org.apache.maven.shared.utils.io.IOUtil

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6456]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** opened **[MNG-5711](https://issues.apache.org/jira/browse/MNG-5711?redirect=false)** and commented

Every so often when I am running the unit tests on a standard Maven project I get a linkage error:

[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ asf-maven-
plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ asf-maven-plugi
n ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ as
f-maven-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory d:\rtc-workspace-asf-10\asf-build-sys
tem\maven-plugins\asf-maven-plugin\src\test-resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ asf-mav
en-plugin ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ asf-maven-plugin ---

[INFO] Surefire report directory: d:\rtc-workspace-asf-10\asf-build-system\maven
-plugins\asf-maven-plugin\target\surefire-reports

---

T E S T S

---

Exception in thread "Thread-7" java.lang.LinkageError: org.apache.maven.surefire
.shade.org.apache.maven.shared.utils.io.IOUtil
at java.lang.ClassLoader.defineClassImpl(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:306)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
3)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:700)
at java.net.URLClassLoader.access$400(URLClassLoader.java:81)
at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1148)
at java.security.AccessController.doPrivileged(AccessController.java:366
)
at java.net.URLClassLoader.findClass(URLClassLoader.java:583)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(Cl
assRealm.java:389)
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(
SelfFirstStrategy.java:42)
at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadCl
ass(ClassRealm.java:259)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm
.java:235)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm
.java:227)
at org.apache.maven.surefire.shade.org.apache.maven.shared.utils.cli.Str
eamPumper.run(StreamPumper.java:95)
Terminate batch job (Y/N)? y

This error is not reproducible but I am getting it from time to time when running maven on the command line as well as in my Jenkins jobs that are running Maven jobs.

When this LinkageError occurs the maven run blocks.

This is what I have in the effective pom for the run above that blocked:

    <plugin>
      <artifactId>maven-surefire-plugin</artifactId>
      <version>2.16</version>
      <inherited>true</inherited>
      <configuration>
        <argLine>-Xms768m -Xmx768m</argLine>
        <trimStackTrace>true</trimStackTrace>
        <childDelegation>false</childDelegation>
        <classpathDependencyExcludes>
          <classpathDependencyExclude>org.dom4j:dom4j</classpathDependencyExclude>
        </classpathDependencyExcludes>
      </configuration>
    </plugin>

Thanks,

Julian Payne

---

**Affects:** 3.2.3

1 votes, 5 watchers

**Comment by jira-importer** [comment]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** commented

This seems to happen only with the IBM JDK (1.7).

**Comment by jira-importer** [comment]
**[Tibor Digana](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor17)** commented

`@Julian` Payne
Does this bug still happen with Surefire 2.17 ?
Only you have this problem ?
Did you come over with Oracle JDK ?

**Comment by jira-importer** [comment]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** commented

This problem only occurs with the IBM JDK (which I have to use). I have also encountered this problem recently with other maven plugins (the compiler plugin) so I suspect that it is related to some of the utility methods that are being used by the plugins?

**Comment by jira-importer** [comment]
**[Tibor Digana](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor17)** commented

Pls check it out with Oracle JDK.
Can you debug the maven and put break point to the classloader ?
Start in project in console: mvnDebug test
and surefire configuration with
\<debugForkedProcess>-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000\</debugForkedProcess>
Then in IDEA, Run/Debug Configurations > + > Remote > change to port 8000
Go to console. If you see halting maven process with something like Listening to port ..., then start remote debugging in IDEA, repeat again if wants to connect or if failed to connect.
You can discover whole class-path if the particular IOUtil class really exists.
Check the system properties for classpath in surefire reports folder, TEST-*.xml, find the library which has the class.

**Comment by jira-importer** [comment]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** commented

I do not have the problem with the Oracle JDK.

I will try to debug the problem and come back to you with more information. This may take some time as this seems to be some sort of race condition and only happens from time to time.

**Comment by jira-importer** [comment]
**[Tibor Digana](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor17)** commented

These kinds of failures need having deeper look.

Definitely this class was modified with maven-shade-plugin.
Download project from Github and check the configuration of every pom.xml having "maven-shade-plugin" if repackaging org.apache.maven.shared package.
Then Check Release Notes if some higher version of shade plugin has candidate bug fix.
You can check requirements for Java version in the bytecode.

Alternatively you may use some IBM bytecode verifier tool if exists, before/after bytecode manipulation.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

I would think this issue is related to the classloading lock bug that was recently found in the IBM JDK, see MNG-5676

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Plexus classworlds 2.5.2 which fixes the problem should be available for download "soon" should fix the problem: Donwload the jar file from http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-classworlds/ and put it into lib/ext of your maven installation.

Please give some feedback if this solves your problem

**Comment by jira-importer** [comment]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** commented

I will do that as soon as I get the new version - thanks for all your help.

**Comment by jira-importer** [comment]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** commented

I have installed 2.5.2 and rerun my long unit tests and everything is fine. Given that this only occurs from time to time I would prefer to wait a few more days before closing this issue? Thanks again for all your help.

**Comment by jira-importer** [comment]
**[Tibor Digana](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor17)** commented

`@Kristian`

Will be new classworld 2.5.2 released in the next Maven distribution?

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

`@Tibor` Classworlds 2.5.2 was just commited in maven core.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Originally from surefire, I moved this issue here. Fixed with clasworlds update

**Comment by jira-importer** [comment]
**[julianpayne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=julianpayne)** commented

> Plexus classworlds 2.5.2 which fixes the problem should be available for download "soon" should fix the
> problem: Donwload the jar file from http://repo1.maven.org/maven2/org/codehaus/plexus/plexus-
> classworlds/ and put it into lib/ext of your maven installation.
> 
> Please give some feedback if this solves your problem

This does indeed fix the problem but **only** if we replace the jar that is in the "boot" directory, it does not work if the jar is put in the "lib/ext" directory.

Thanks for the help and solution of this problem.
