### ISSUE TITLE
[MNG-5613] NPE error when building a reactor with duplicated artifacts

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6469]
**[Dominique Broeglin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dominique.broeglin)** opened **[MNG-5613](https://issues.apache.org/jira/browse/MNG-5613?redirect=false)** and commented

Using v3.2.1 when building a malformed project containing a duplicated groupId:artifactId I got this rather unhelpful error:

```
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	... 11 more
```

The more helpful error should have been:

```
org.apache.maven.project.DuplicateProjectException: Project 'com.foo.bar:foo-bar:2.15.0' is duplicated in the reactor
	at org.apache.maven.project.ProjectSorter.<init>(ProjectSorter.java:93)
	at org.apache.maven.DefaultProjectDependencyGraph.<init>(DefaultProjectDependencyGraph.java:53)
	at org.apache.maven.DefaultMaven.createProjectDependencyGraph(DefaultMaven.java:819)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:268)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

---

**Affects:** 3.2.1

**Attachments:**
- [foo.zip](https://issues.apache.org/jira/secure/attachment/12713412/foo.zip) (_1.66 kB_)

**Issue Links:**
- [MNG-5628](https://issues.apache.org/jira/browse/MNG-5628) NullPointerException with Maven 3.2.1 when circular dependency exists in POMs
 (_**"is duplicated by"**_)
- [MNG-5651](https://issues.apache.org/jira/browse/MNG-5651) Null pointer exception when trying to execute a mvn build
 (_**"is duplicated by"**_)

1 votes, 9 watchers

**Comment by jira-importer** [comment]
**[Dominique Broeglin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dominique.broeglin)** commented

The fix was easy. I submitted it in the following pull request: https://github.com/apache/maven/pull/12

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Provide a sample project that caused the problem and I'll look at the patch.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Or a unit test would be even better, I can help make one of those as we have too much of our testing in integration tests which makes it a lot harder for drive-by contributors like yourself to know everything is working. I know this is a very localized patch but I'd still like to add a test.

**Comment by jira-importer** [comment]
**[Dominique Broeglin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dominique.broeglin)** commented

Here a sample project that reproduces the error. I would gladly have written a unit test but there was not one for that class and I did not have enough time to understand how testing is done the maven project. The issue is quite straightforward, as is the fix, I think you should not have any issue bringing it up to the quality level you require but due to lack of time my contribution will stop there.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Great, thanks Dominique.

**Comment by jira-importer** [comment]
**[Michael Vorburger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vorburger)** commented

I've also just been hit by this... you can repro. by git clone https://github.com/vorburger/com.temenos.ds.op.git; git checkout 05817dde22bac06506a7d3bc3746f0e3df47c306; mvn clean -> same NPE as above.

**Comment by jira-importer** [comment]
**[Sébastian Le Merdy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=seblm)** commented

I've created a [new pull request](https://github.com/apache/maven/pull/13) with unit test. Please see if it suits your needs. I think this bug is important to fix in order to give better feedback to developers when there is a cycle or a duplication into their project reactor.

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Thanks for the test, if you haven't run the integration tests. Then we can show you how to run them to validate or I can run them quickly. If you've run them and verified they are ok, i'll process the pull request.

This should be easier, our CI system for participants like yourself, is not very good. It's totally manual.

**Comment by jira-importer** [comment]
**[Sébastian Le Merdy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=seblm)** commented

I've followed [this guide](http://maven.apache.org/guides/development/guide-m2-development.html#Dont_forget_tests) to run the integration tests. Result was ok (but took a lot of time :))

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Committed on bef7fac6e3495dae57a44e6a5902afd89c74b196
Submitted by: Sebastian Le Merdy
From: https://github.com/apache/maven/pull/13

**Comment by jira-importer** [comment]
**[Delany](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=delany)** commented

Getting this in multi-module build after updating plugin versions to latest.
