### ISSUE TITLE
[MNG-5727] unexpected InvalidArtifactRTException from ProjectBuilder#build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6573]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** opened **[MNG-5727](https://issues.apache.org/jira/browse/MNG-5727?redirect=false)** and commented

Calling into ProjectBuilder#build(File, ProjectBuildingRequest) results in InvalidArtifactRTException below if project pom.xml has managed dependency without \<version>. Although the pom is invalid, I expected to get ProjectBuildingException that includes location of problematic dependency, similar to what I get during command line build.

```
org.apache.maven.artifact.InvalidArtifactRTException: For artifact {org.apache.maven.its:a:null:jar}: The version cannot be empty.
	at org.apache.maven.artifact.DefaultArtifact.validateIdentity(DefaultArtifact.java:148)
	at org.apache.maven.artifact.DefaultArtifact.<init>(DefaultArtifact.java:123)
	at org.apache.maven.bridge.MavenRepositorySystem.XcreateArtifact(MavenRepositorySystem.java:695)
	at org.apache.maven.bridge.MavenRepositorySystem.XcreateDependencyArtifact(MavenRepositorySystem.java:613)
	at org.apache.maven.bridge.MavenRepositorySystem.createDependencyArtifact(MavenRepositorySystem.java:121)
	at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:808)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:174)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:118)
...
```

---

**Issue Links:**
- [MNG-5680](https://issues.apache.org/jira/browse/MNG-5680) java.lang.UnsupportedOperationException on DefaultProjectBuilder.build

- [MDEP-506](https://issues.apache.org/jira/browse/MDEP-506) NPE in AnalyzeDepMgt.getMismatch

**Remote Links:**
- [Discussion on the mailing list
](https://www.mail-archive.com/dev%40maven.apache.org/msg107115.html)

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Igor, you made the commit but did not close the issue. Why?
Anyway, I ran the test project you attached and it fails. Though it does not mention `dependencyManagement` but `dependencies` only. Is that what you intended? I have raised a question to his on the dev mailing list.

**Comment by jira-importer** [comment]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** commented

I am not sure what attached project you refer to. The test project I committed as part of [1] includes \<dependencyManagement> entry without \<version> element. The test project is expected to fail with ProjectBuildingException, which is ensured by the regression test introduced as part of the commit.

This issue was specifically about InvalidArtifactRTException, which is fixed now, so I am closing this issue as such.

[1] https://git1-us-west.apache.org/repos/asf?p=maven.git;a=commit;h=ce6f0bfdb527e20c3afbd76b9c742e07b13d25b2

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I am refering about this file: https://git1-us-west.apache.org/repos/asf?p=maven.git;a=blob;f=maven-core/src/test/resources/projects/versionless-managed-dependency.xml;h=40bf2955f8d4cda72dba823296696154d7778749;hb=ce6f0bfdb527e20c3afbd76b9c742e07b13d25b2

If you run that with `mvn -f` you give a failure about dependencies but not dependencyManagement. This is what I would expect.

**Comment by jira-importer** [comment]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** commented

I didn't want to change how maven handles unused invalid \<dependencyManagement> elements, so reporting problems with invalid \<dependencies> seems like the right way to fix InvalidArtifactRTException. For example, I don't see why the following pom.xml should be considered invalid

```
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>versionless-managed-dependency.xml</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

**Comment by jira-importer** [comment]
**[Joerg Schaible](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joehni)** commented

Or this overriding the scope in a "later" dependenciesManagement section:

```xml
<project>
  <modelVersion>4.0.0</modelVersion>
   <groupId>test</groupId>
  <artifactId>parent</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <scope>4.12</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
```

```xml
<project>
      <modelVersion>4.0.0</modelVersion>
      <parent>
            <groupId>test</groupId>
            <artifactId>parent</artifactId>
            <version>0.0.1-SNAPSHOT</version>
      </parent>

      <artifactId>versionless-managed-dependency.xml</artifactId>
    
      <dependencies>
        <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
        </dependency>
      </dependencies>
    
      <dependencyManagement>
        <dependencies>
          <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>runtime</scope>
          </dependency>
        </dependencies>
      </dependencyManagement>
    
    </project>
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

So, you guys are saying that elements in `dependencyManagement` are used as partial templates for the `dependencies` section and ultimate resolution shall happen in `dependencies` only?

**Comment by jira-importer** [comment]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** commented

This is how Maven appears to work now and I think the current behaviour makes sense.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks for this clarification.
