### ISSUE TITLE
[MNG-5732] Java 9 completely changes JDK directory layout and drops tools.jar

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6582]
**[Markus Karg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mkarg)** opened **[MNG-5732](https://issues.apache.org/jira/browse/MNG-5732?redirect=false)** and commented

Oracle published plans to drop the existence of tools.jar and totally restructure the directory layout of the JDK beginning with JDK 9, including changes in the extensions mechanism and location of rt.jar. As a side effect, all plugins relying on a particular layout structure and / or the existence of tools.jar won't work on JDK 9.

The intention is to move from a histrically grown infrastructure to a layout which is clearly documented by JEP 220, hence it can be considered consistent on all future JDKs, which is a positive thing, but imposes problems for many tool vendors.

As this is a cross-plugin concern, all plugins have to be checked and possibly fixed.

For more information see http://openjdk.java.net/jeps/220.

A pre-release of JDK 9 can be downloaded from https://jdk9.java.net/download/.

Oracle is interested to get in touch with projects being currently dependend of the existing pre-9 JDK structure. Such projects shall report on the jigsaw-dev mailing list.

Some effects in short:

Ã¢â¬Â¢	JRE and JDK images now have identical structures. Previously a JDK image embedded the JRE in a jre subdirectory; now a JDK image is simply a run-time image that happens to contain the full set of development tools and other items historically found in the JDK.

Ã¢â¬Â¢	User-editable configuration files previously located in the lib directory are now in the new 'conf' directory. The files that remain in the lib directory are private implementation details of the run-time system, and should never be opened or modified.

Ã¢â¬Â¢	The endorsed-standards override mechanism has been removed. Applications that rely upon this mechanism, either by setting the system property java.endorsed.dirs or by placing jar files into the lib/endorsed directory of a JRE, will not work. We expect to provide similar functionality later in JDK 9 in the form of upgradeable modules.

Ã¢â¬Â¢	The extension mechanism has been removed. Applications that rely upon this mechanism, either by setting the system property java.ext.dirs or by placing jar files into the lib/ext directory of a JRE, will not work. In most cases, jar files that were previously installed as extensions can simply be placed at the front of the class path.

Ã¢â¬Â¢	The internal files rt.jar, tools.jar, and dt.jar have been removed. The content of these files is now stored in a more efficient format in implementation-private files in the lib directory. Class and resource files previously in tools.jar and dt.jar are now always visible via the bootstrap or application class loaders in a JDK image.

Ã¢â¬Â¢	A new, built-in NIO file-system provider can be used to access the class and resource files stored in a run-time image. Tools that previously read rt.jar and other internal jar files directly should be updated to use this file system.

(Source: December Oracle Java CAP Program Newsletter)

---

3 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Maven runs fine with JDK9, but there are some plugins which will require some changes. It has our attention.

**Comment by jira-importer** [comment]
**[Arindam Bandyopadhyay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aribandy)** commented

I am from Glassfish application team . We have some Maven based tests . When I am trying to run  the tests with Glassfish on JDK 9, I am getting the following exception . I am using the latest released version of Maven (3.3.9) .

```
----------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default-test) on project quicklook: Execution default-test of goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools-jar:jar:1 at specified path /Users/aribandy/jdk_ea/build/macosx-x86_64/jdk/../lib/tools.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default-test) on project quicklook: Execution default-test of goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools-jar:jar:1 at specified path /Users/aribandy/jdk_ea/build/macosx-x86_64/jdk/../lib/tools.jar
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(java.base@9.0/Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(java.base@9.0/NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9.0/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9.0/Method.java:530)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run failed: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools-jar:jar:1 at specified path /Users/aribandy/jdk_ea/build/macosx-x86_64/jdk/../lib/tools.jar
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools-jar:jar:1 at specified path /Users/aribandy/jdk_ea/build/macosx-x86_64/jdk/../lib/tools.jar
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:400)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:372)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:102)
	... 21 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.sun:tools-jar:jar:1 at specified path /Users/aribandy/jdk_ea/build/macosx-x86_64/jdk/../lib/tools.jar
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
	... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.sun:tools-jar:jar:1 at specified path /Users/aribandy/jdk_ea/build/macosx-x86_64/jdk/../lib/tools.jar
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:286)
	... 29 more
--------------------------------------------------------------
```

**Comment by jira-importer** [comment]
**[Arindam Bandyopadhyay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aribandy)** commented

Please follow the bellow link if you want to run the tests to reproduce the issue .
https://svn.java.net/svn/glassfish~svn/trunk/main/appserver/tests/quicklook/QuickLook_Test_Instructions.html

**Comment by jira-importer** [comment]
**[Alexandre Iline](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shurymury)** commented

This is great news!

Thanks, Arindam!

Shura

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

The problem lies in your own [pom.xml](https://svn.java.net/svn/glassfish~svn/trunk/main/appserver/tests/quicklook/pom.xml). Line 248 describes:

```xml
<dependency>
    <groupId>com.sun</groupId>
    <artifactId>tools-jar</artifactId>
    <version>1</version>
    <scope>system</scope>
    <systemPath>${java.home}/../lib/tools.jar</systemPath>
</dependency>
```

These are solutions I can think of:
- try to replace these ant-scripts.
- Assuming you don't need this dependency anymore with Java9, you could use a profile with java activation, e.g.

```xml
<profiles>
  <profile>
    <activation>
      <jdk>(,1.9)</jdk>
    </activation>
    <build>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <dependencies>
            <dependency>
              <groupId>com.sun</groupId>
              <artifactId>tools-jar</artifactId>
              <version>1</version>
              <scope>system</scope>
              <systemPath>${java.home}/../lib/tools.jar</systemPath>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </build>
  </profile>
</profiles>
```

**Comment by jira-importer** [comment]
**[Arindam Bandyopadhyay](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aribandy)** commented

Thanks Robert . After deleting the tools-jar dependency maven is running fine.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I think this can be closed safely. So far I haven't seen any issues with Java 9 which are directly related to Maven.
