### ISSUE TITLE
[MNG-5705] NPE on parallel build in BuilderCommon.handleBuildError(BuilderCommon.java:147)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6598]
**[Ondra Žižka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pekarna)** opened **[MNG-5705](https://issues.apache.org/jira/browse/MNG-5705?redirect=false)** and commented

STR:

```
git clone git@github.com:OndraZizka/windup.git
cd windup
git checkout 91a454b  # MavenNPE2
mvn -T 1C clean javadoc:aggregate -PjavadocDist
```

```
[INFO] ------------------------------------------------------------------------
[INFO] Windup Parent ..................................... SUCCESS [  0.132 s]
[INFO] Windup Engine - Frames ............................ SUCCESS [  0.009 s]
[INFO] Windup Engine - Utils ............................. SUCCESS [  0.035 s]
[INFO] Windup Engine - Graph Parent ...................... SUCCESS [  0.004 s]
[INFO] Windup Engine - Graph API ......................... FAILURE [  0.003 s]
[INFO] Windup Engine - Graph Impl ........................ SKIPPED
[INFO] Windup Engine - Graph Addon ....................... SKIPPED
[INFO] Windup Engine - Graph Tests ....................... SKIPPED
[INFO] Windup Engine - Config Parent ..................... SUCCESS [  0.008 s]
[INFO] Windup Engine - Config API ........................ SKIPPED
[INFO] Windup Engine - Config Impl ....................... SKIPPED
[INFO] Windup Engine - Config Addon ...................... SKIPPED
[INFO] Windup Engine - Decompiler ........................ SUCCESS [  0.011 s]
[INFO] Windup Engine - Decompiler API .................... SUCCESS [  0.039 s]
[INFO] Windup Engine - Decompiler Procyon ................ SKIPPED
[INFO] Windup Extension - Config - XML ................... SKIPPED
[INFO] Windup Engine - Reporting Parent .................. SUCCESS [  0.016 s]
[INFO] Windup Engine - Reporting API ..................... SKIPPED
[INFO] Windup Engine - Reporting Impl .................... SKIPPED
[INFO] Windup Engine - Reporting Addon ................... SKIPPED
[INFO] Windup Engine - Execution API Parent .............. SUCCESS [  0.003 s]
[INFO] Windup Engine - Execution API ..................... SKIPPED
[INFO] Windup Engine - Execution API Impl ................ SKIPPED
[INFO] Windup Engine - Execution API Addon ............... SKIPPED
[INFO] Windup Rules - XML - Basic ........................ SKIPPED
[INFO] Windup Extension - Config - Groovy ................ SKIPPED
[INFO] Windup Rules - Java - Basic ....................... SKIPPED
[INFO] Windup Engine - Config Tests ...................... SKIPPED
[INFO] Windup Rules - Java EE - Basic .................... SKIPPED
[INFO] Windup Engine - Execution API Tests ............... SKIPPED
[INFO] Windup Engine - Reporting Tests ................... SKIPPED
[INFO] Windup Engine - UI ................................ SKIPPED
[INFO] Windup Engine - Test Utilities .................... SUCCESS [  0.004 s]
[INFO] Windup Engine - Tests ............................. SKIPPED
[INFO] Windup - Bootstrap module ......................... SUCCESS [  0.002 s]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ decompiler-api ---
[INFO] Windup - Distribution Build ....................... FAILURE [  0.008 s]
[INFO] Windup Rulesets BOM ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.721 s (Wall Clock)
[INFO] Finished at: 2014-10-22T16:39:30+01:00
[INFO] Final Memory: 21M/211M
[INFO] ------------------------------------------------------------------------
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
        at org.apache.maven.lifecycle.internal.builder.BuilderCommon.handleBuildError(BuilderCommon.java:147)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.maven.execution.MavenSession.getPluginContext(MavenSession.java:314)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:504)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:120)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        ... 8 more
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
        at org.apache.maven.lifecycle.internal.builder.BuilderCommon.handleBuildError(BuilderCommon.java:147)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.maven.cli.event.ExecutionEventLogger.projectStarted(ExecutionEventLogger.java:232)
        at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:71)
        at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:99)
        ... 8 more
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
        at org.apache.maven.lifecycle.internal.builder.BuilderCommon.handleBuildError(BuilderCommon.java:147)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:288)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        ... 8 more
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
        at org.apache.maven.lifecycle.internal.builder.BuilderCommon.handleBuildError(BuilderCommon.java:147)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.calcImports(DefaultMavenPluginManager.java:413)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:308)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:230)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:100)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
        ... 8 more

```

---

**Affects:** 3.2.1

**Issue Links:**
- [MNG-5965](https://issues.apache.org/jira/browse/MNG-5965) Parallel build multiplies work if multiple goals are given

- [MNG-5965](https://issues.apache.org/jira/browse/MNG-5965) Parallel build multiplies work if multiple goals are given
 (_**"depends upon"**_)

2 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Unfortunately this still fails with 3.4.0-SNAPSHOT.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Ondra Žižka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pekarna), can you check branch MNG-5965 if it solves your issue?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Implicitly fixed with MNG-5965:

```
$ /d/Entwicklung/Programme/apache-maven-3.6.1-SNAPSHOT/bin/mvn -V -T 1C clean javadoc:aggregate -PjavadocDist
Apache Maven 3.6.1-SNAPSHOT (d92d874a37361723a22285e7e5673f7f27f3c0c8; 2018-12-26T14:13:05+01:00)
Maven home: D:\Entwicklung\Programme\apache-maven-3.6.1-SNAPSHOT
Java version: 1.7.0_191, vendor: Azul Systems, Inc., runtime: C:\Program Files\Zulu\zulu-7\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Windup Parent 2.0.0-SNAPSHOT:
[INFO]
[INFO] Windup Parent ...................................... SUCCESS [02:09 min]
[INFO] Windup Engine - Frames ............................. SUCCESS [  0.075 s]
[INFO] Windup Engine - Utils .............................. SUCCESS [  0.045 s]
[INFO] Windup Engine - Graph Parent ....................... SUCCESS [  0.030 s]
[INFO] Windup Engine - Graph API .......................... SUCCESS [  0.072 s]
[INFO] Windup Engine - Graph Impl ......................... SUCCESS [  0.024 s]
[INFO] Windup Engine - Graph Addon ........................ SUCCESS [  0.006 s]
[INFO] Windup Engine - Graph Tests ........................ SUCCESS [  0.003 s]
[INFO] Windup Engine - Config Parent ...................... SUCCESS [  0.030 s]
[INFO] Windup Engine - Config API ......................... SUCCESS [  0.041 s]
[INFO] Windup Engine - Config Impl ........................ SUCCESS [  0.013 s]
[INFO] Windup Engine - Config Addon ....................... SUCCESS [  0.007 s]
[INFO] Windup Engine - Decompiler ......................... SUCCESS [  0.006 s]
[INFO] Windup Engine - Decompiler API ..................... SUCCESS [  0.094 s]
[INFO] Windup Engine - Decompiler Procyon ................. SUCCESS [  0.025 s]
[INFO] Windup Extension - Config - XML .................... SUCCESS [  0.017 s]
[INFO] Windup Engine - Reporting Parent ................... SUCCESS [  0.009 s]
[INFO] Windup Engine - Reporting API ...................... SUCCESS [  0.025 s]
[INFO] Windup Engine - Reporting Impl ..................... SUCCESS [  0.053 s]
[INFO] Windup Engine - Reporting Addon .................... SUCCESS [  0.007 s]
[INFO] Windup Engine - Execution API Parent ............... SUCCESS [  0.014 s]
[INFO] Windup Engine - Execution API ...................... SUCCESS [  0.016 s]
[INFO] Windup Engine - Execution API Impl ................. SUCCESS [  0.015 s]
[INFO] Windup Engine - Execution API Addon ................ SUCCESS [  0.007 s]
[INFO] Windup Rules - XML - Basic ......................... SUCCESS [  0.020 s]
[INFO] Windup Extension - Config - Groovy ................. SUCCESS [  0.012 s]
[INFO] Windup Rules - Java - Basic ........................ SUCCESS [  0.029 s]
[INFO] Windup Engine - Config Tests ....................... SUCCESS [  0.004 s]
[INFO] Windup Rules - Java EE - Basic ..................... SUCCESS [  0.017 s]
[INFO] Windup Engine - Execution API Tests ................ SUCCESS [  0.005 s]
[INFO] Windup Engine - Reporting Tests .................... SUCCESS [  0.003 s]
[INFO] Windup Engine - UI ................................. SUCCESS [  0.014 s]
[INFO] Windup Engine - Test Utilities ..................... SUCCESS [  0.030 s]
[INFO] Windup Engine - Tests .............................. SUCCESS [  0.005 s]
[INFO] Windup - Bootstrap module .......................... SUCCESS [  0.012 s]
[INFO] Windup - Distribution Build ........................ SUCCESS [  0.085 s]
[INFO] Windup Rulesets BOM ................................ SUCCESS [  0.121 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:10 min (Wall Clock)
[INFO] Finished at: 2018-12-27T14:35:18+01:00
[INFO] ------------------------------------------------------------------------
```

and the following changes:

```
diff --git a/frames/pom.xml b/frames/pom.xml
index bb72b76f3..411507dd8 100644
--- a/frames/pom.xml
+++ b/frames/pom.xml
@@ -182,7 +182,7 @@
             <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-javadoc-plugin</artifactId>
-                <version>2.8</version>
+                <version>3.0.1</version>
                 <executions>
                     <execution>
                         <id>attach-javadocs</id>
diff --git a/pom.xml b/pom.xml
index 00e884da1..7eb66a8da 100644
--- a/pom.xml
+++ b/pom.xml
@@ -161,7 +161,7 @@
                 <plugins>
                     <plugin>
                         <artifactId>maven-javadoc-plugin</artifactId>
-                        <version>2.10.1</version>
+                        <version>3.0.1</version>
                         <executions>
                             <execution>
                                 <id>javadocs-dist</id>
@@ -183,9 +183,7 @@
                                     <dependencySourceExcludes>
                                         <dependencySourceExclude>com.tinkerpop.frames:frames</dependencySourceExclude>
                                     </dependencySourceExcludes>
-                                    <excludePackageNames>
-                                        <excludePackageName>com.tinkerpop.frames.*</excludePackageName>
-                                    </excludePackageNames>
+                                    <excludePackageNames>com.tinkerpop.frames.*</excludePackageNames>

                                     <groups>
                                         <group>

```
