### ISSUE TITLE
[MNG-5321] "IOException: Failed to delete repository.xml while trying to rename" during parallel build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6599]
**[Victor Burdejny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vburdejny)** opened **[MNG-5321](https://issues.apache.org/jira/browse/MNG-5321?redirect=false)** and commented

The following problem has been found in console when parallel build was used (-T command line parameter):

[INFO] --- maven-bundle-plugin:2.3.6:install (default-install) @ my-bundle ---
[WARNING] Exception while updating local OBR: IOException
org.apache.maven.plugin.MojoExecutionException: IOException
at org.apache.felix.obrplugin.ObrUpdate.writeRepositoryXml(ObrUpdate.java:293)
at org.apache.felix.obrplugin.ObrInstall.execute(ObrInstall.java:149)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
...

'stderr' contains the following stacktrace:

java.io.IOException: Failed to delete c:\.m2\repository.xml while trying to rename C:\Users\User\AppData\Local\Temp\repository8243840781003249024.xml
at org.codehaus.plexus.util.FileUtils.rename(FileUtils.java:2128)
at org.apache.felix.obrplugin.ObrUpdate.writeRepositoryXml(ObrUpdate.java:288)
...

Full stacktraces are provided in the attachment.

I did not find any problems that it causes for the build, but I suspect that such problems might exist. The problem itself is (I suspect) a trivial race condition.

---

**Affects:** 3.0.3

**Attachments:**
- [maven-repository-xml-issue.txt](https://issues.apache.org/jira/secure/attachment/12712697/maven-repository-xml-issue.txt) (_3.47 kB_)

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

This sounds like the maven-bundle-plugin is not thread-safe. That would need to be reported to the Felix community: https://issues.apache.org/jira/browse/FELIX/component/12311143

**Comment by jira-importer** [comment]
**[Victor Burdejny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vburdejny)** commented

The problem has been reported to Felix community: https://issues.apache.org/jira/browse/FELIX-3619

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

thanks
