### ISSUE TITLE
[MNG-5703] ClosedChannelException from DefaultUpdateCheckManager.read on Linux

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6603]
**[Tony Reix](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trex58)** opened **[MNG-5703](https://issues.apache.org/jira/browse/MNG-5703?redirect=false)** and commented

I already added a note in: http://jira.codehaus.org/browse/MNG-5629 .
But, since this JIRA deals with Windows, since my issues are on Linux, and since I'm blocked, I'm opening a new JIRA.

I was working on the port of Falcon on PPC64 when it appeared. I'm now blocked.
First, I was on RHEL7/PPC64BE: this Maven error was not there, and I've been able to compile and run tests, with IBM JVM v1.6 .
Then, I moved to Ubuntu/PPC64LE, with IBM JVM 1.7, and the issue appeared.
I then tried on Ubuntu/x86_64, with IBM JVM and then Oracle JVM, v1.7, and the issue was there too. Same with IBM JVM 1.6 .

Traces show the issue when using -X only.

Example of traces, on Ubuntu/x86_64 , with IBM JVM 1.6 :

```
export HADOOP_VERSION=2.4.1
export HADOOP_PROFILE=hadoop-2
export OOZIE_VERSION=4.0.1
mvn -X compile -P $HADOOP_PROFILE -Dhadoop.version=$HADOOP_VERSION -Doozie.version=$OOZIE_VERSION -Doozie.forcebuild=false -DskipTests

...
[DEBUG] Determining update check for artifact asm:asm (/home/reixt/.m2/repository/asm/asm/maven-metadata-central.xml) from central (http://repo1.maven.org/maven2)
[DEBUG] Searching for central.maven-metadata-central.xml.lastUpdated in resolution tracking file.
[DEBUG] Reading resolution-state from: /home/reixt/.m2/repository/asm/asm/resolver-status.properties
[DEBUG] Error releasing shared lock for resolution tracking file: /home/reixt/.m2/repository/asm/asm/resolver-status.properties
java.nio.channels.ClosedChannelException
at sun.nio.ch.FileLockImpl.release(FileLockImpl.java:47)
at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.read(DefaultUpdateCheckManager.java:396)
at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.readLastUpdated(DefaultUpdateCheckManager.java:323)
at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.readLastUpdated(DefaultUpdateCheckManager.java:159)
at org.apache.maven.repository.legacy.DefaultUpdateCheckManager.isUpdateRequired(DefaultUpdateCheckManager.java:148)

...

[INFO] Apache Falcon Oozie EL Extension .................. FAILURE [ 26.935 s]
[INFO] Apache Falcon Embedded Hadoop - Test Cluster ...... SKIPPED
....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17:52 min
[INFO] Finished at: 2014-10-20T10:18:30-05:00
[INFO] Final Memory: 38M/181M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project falcon-oozie-el-extension: Could not resolve dependencies for project org.apache.falcon:falcon-oozie-el-extension:jar:0.5-incubating: Could not find artifact org.apache.oozie:oozie-core:jar:4.0.1-falcon in central (http://repo1.maven.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project falcon-oozie-el-extension: Could not resolve dependencies for project org.apache.falcon:falcon-oozie-el-extension:jar:0.5-incubating: Could not find artifact org.apache.oozie:oozie-core:jar:4.0.1-falcon in central 
```

Testcase:
- download Falcon v0.5
- use above mvn options

---

**Affects:** 3.2.1

**Comment by jira-importer** [comment]
**[Tony Reix](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trex58)** commented

On RHEL7/PPC64BE, I'm now using a Falcon patch that enables me to compile Falcon (and the modified version of Oozie that Falcon uses) with IBM Java 1.7 .
And I do not have the Maven issue in this environment. Is it related to Ubuntu ?

$ mvn --version
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: /opt/apache-maven-3.2.1
Java version: 1.7.0, vendor: IBM Corporation
Java home: /usr/lib/jvm/ibm-java-ppc64-71/jre
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "3.10.0-123.6.3.el7.ppc64", arch: "ppc64", family: "unix"

**Comment by jira-importer** [comment]
**[Tony Reix](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trex58)** commented

On RHEL7/x86_64, I also have the issue when trying to compile FALCON (with a patch changing Oozie in order to not require Java 1.6).
- Maven 3.2.3
- IBM JVM 1.7

However, though I've got 347 java.nio.channels.ClosedChannelException exceptions when compiling Falcon, the compilation phase is: SUCCESS.
So, this exception may not be the blocker for my compilation on the other machines. More analyzis is required.

Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /opt/apache-maven-3.2.3
Java version: 1.7.0, vendor: IBM Corporation
Java home: /usr/lib/jvm/ibm-java-x86_64-71/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-123.4.4.el7.x86_64", arch: "amd64", family: "unix"

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

[Tony Reix](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trex58), what's the status?

**Comment by jira-importer** [comment]
**[Tony Reix](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trex58)** commented

A colleague is now working on this, but without the option  "-Doozie.forcebuild=false" , and he says he does not have the issue.
Trying again now, with and without.

**Comment by jira-importer** [comment]
**[Tony Reix](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trex58)** commented

I cannot find the rationale about why using: -Doozie.forcebuild=false .
However, with: -Doozie.forcebuild=true , that's the same (same error message "Error releasing shared lock for resolution tracking file").
And, without -Doozie.forcebuild=.... , that's the same.

However, the compilation reaches the end and SUCCEEDs now.

And the error message ("Error releasing shared lock for resolution tracking file") seems to be printed only if I use the  "-X" option (more trace).

OK. I think I have understood: I had another issue which made the compilation to fail AND I was using -X AND there was some issue in my Maven .m2 environment which produced an issue that was by-passed by Maven and which is NOT shown when NOT using -X .  So, seeing these error messages, I thought it was the root cause of the build failure, but it was not.
Damned Maven ! And I was not good at analyzing this issue...

So, there is an issue, but Maven can by-pass it ! So, I'm done. We can close this.

**Comment by jira-importer** [comment]
**[Tony Reix](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=trex58)** commented

It is an internal issue in Maven I think, due to some issue in my .m2 environment ; but Maven can by-pass it. So, I'm no more blocked. Closing.
