### ISSUE TITLE
[MNG-5680] java.lang.UnsupportedOperationException on DefaultProjectBuilder.build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6636]
**[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi)** opened **[MNG-5680](https://issues.apache.org/jira/browse/MNG-5680?redirect=false)** and commented

```
ProjectBuildingRequest request = ...
ProjectBuilder builder = plexus.lookup(ProjectBuilder.class);
builder.build(file, request);
```

When the build method is called, the following exception is thrown:

```
java.lang.UnsupportedOperationException
	at java.util.AbstractMap.put(AbstractMap.java:209)
	at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:815)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:174)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:118)
```

The code should be reviewed. This is the offending code inside DefaultProjectBuilder:

```
                    Artifact artifact = repositorySystem.createDependencyArtifact( d );

                    if ( artifact == null )
                    {
                        map = Collections.emptyMap();
                    }

                    map.put( d.getManagementKey(), artifact );

```

---

**Affects:** 3.2.3

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12713194/pom.xml) (_1.90 kB_)

**Issue Links:**
- [MNG-5727](https://issues.apache.org/jira/browse/MNG-5727) unexpected InvalidArtifactRTException from ProjectBuilder#build

- [MNG-5368](https://issues.apache.org/jira/browse/MNG-5368) UnsupportedOperationException thrown when version range is not correct in dependencyManagement definitions

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi)** commented

Raising the priority, since DefaultProjectBuilder is unusable without fixing this

**Comment by jira-importer** [comment]
**[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi)** commented

pom.xml to reproduce problem attached

**Comment by jira-importer** [comment]
**[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi)** commented

To reproduce, run mvn clean install in the attached pom.xml

**Comment by jira-importer** [comment]
**[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi)** commented

This error doesn't happen in 3.2.2 and earlier versions

**Comment by jira-importer** [comment]
**[Shaun](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=selliott@paml.com)** commented

[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi) can you post your environment information, such as operating system, jdk, etc? You can get this with "mvn --version". Also, are you by chance using homebrew?

**Comment by jira-importer** [comment]
**[Shaun](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=selliott@paml.com)** commented

I'm linking this to MNG-5368, it looks like they could be related.

**Comment by jira-importer** [comment]
**[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi)** commented

I am using Fedora 20, running on Maven 3.2.3 on JDK 1.8.0_11. I am not using homebrew

**Comment by jira-importer** [comment]
**[George Gastaldi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gastaldi)** commented

Yes, it looks like a duplicate of MNG-5368, it should be reopened and fixed

**Comment by jira-importer** [comment]
**[Shaun](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=selliott@paml.com)** commented

I had a colleague who was having this same issue, MNG-5368 was definitely the cause. It would be an improvement for maven to give some sensible error rather than it manifesting in this way.

FWIW, it was not environmental issues, but here was his settings:

```
username-mbp112:bin username$ mvn --version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T13:58:10-07:00)
Maven home: /usr/share/java/apache-maven-3.2.3
Java version: 1.7.0_45, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"
```

**Comment by jira-importer** [comment]
**[Joseph Walton](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joe@kafsemo.org)** commented

It looks like [this commit](https://github.com/apache/maven/commit/ce6f0bfdb527e20c3afbd76b9c742e07b13d25b2#diff-9037bac1b0c7ac509f2f375f84d60f8d) in 3.2.4 for MNG-5727 may fix this.
