### ISSUE TITLE
[MNG-5637] NPE in org.apache.maven.DefaultMaven.execute()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6684]
**[Ondra Žižka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pekarna)** opened **[MNG-5637](https://issues.apache.org/jira/browse/MNG-5637?redirect=false)** and commented

Steps to reproduce:

git clone git@github.com:windup/windup.git
cd windup
git checkout MavenNPE
mvn clean install

Result:

```
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        ... 11 more
```

---

**Affects:** 3.2.1

**Issue Links:**
- [MNG-5628](https://issues.apache.org/jira/browse/MNG-5628) NullPointerException with Maven 3.2.1 when circular dependency exists in POMs

- [MNG-5633](https://issues.apache.org/jira/browse/MNG-5633) NullPointerException when project contains cyclic references

**Comment by jira-importer** [comment]
**[Ondra Žižka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pekarna)** commented

Seems to be related, if not duplicate, MNG-5628 and MNG-5633

**Comment by jira-importer** [comment]
**[Ondra Žižka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pekarna)** commented

Maven 3.1.1 correctly reveals what's wrong:
Two or more projects in the reactor have the same identifier, please make sure that \<groupId>:\<artifactId>:\<version> is unique for each project: {org.jboss.windup.test.apps.jboss:sample-jee-jboss-web:2.0.0-SNAPSHOT=[/home/ondra/work/Migration/WindUp/sample-apps/jee-example-jboss/jee-example-web/pom.xml, /home/ondra/work/Migration/WindUp/sample-apps/jee-example-weblogic/jee-example-web/pom.xml]} -> [Help 1]

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Project doesn't build:

[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jboss.windup:JBossEapRecognition:2.0.0-SNAPSHOT (/private/tmp/windup/addons/server/JBossEapRecognition/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.jboss.windup:windup-parent:pom:2.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
