### ISSUE TITLE
[MNG-5623] Exception when printing Reactor Summary

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6698]
**[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung)** opened **[MNG-5623](https://issues.apache.org/jira/browse/MNG-5623?redirect=false)** and commented

We get the following exception in maven 3.2.1:

```
17:14:29,313 INFO  - org.emftext.commons.antlr3_4_0 .................... SUCCESS [ 13.624 s]
17:14:29,313 INFO  - acceleo-maven ..................................... SUCCESS [ 0.811 s]
17:14:29,313 INFO  - com.ptvgroup.geoplatform.dfspec ................... SUCCESS [ 6.208 s]
17:14:29,313 INFO  - com.ptvgroup.geoplatform.dfspec.resource.dfspec ... SUCCESS [ 9.181 s]
17:14:29,313 INFO  - com.ptvgroup.geoplatform.dfspec.generator ......... SUCCESS [ 27.518 s]
17:14:29,313 INFO  - df7-java-generator ................................ SUCCESS [ 12.459 s]
17:14:29,313 INFO  - df7-cpp-generator ................................. SUCCESS [ 16.046 s]
17:14:29,313 INFO  - df7-wiki-generator ................................ SUCCESS [ 8.318 s]
17:14:29,313 INFO  - dfutils ........................................... SUCCESS [ 17.114 s]
17:14:29,313 INFO  - com.ptvgroup.geoplatform.dfspec.resource.dfspec.ui SUCCESS [ 7.206 s]
17:14:29,313 INFO  - com.ptvgroup.geoplatform.dfspec.validation ........ SUCCESS [ 10.988 s]
17:14:29,313 INFO  - df7-cpp-testgenerator ............................. SUCCESS [01:11 min]
17:14:29,313 INFO  - df7-java-testgenerator ............................ SUCCESS [01:10 min]
17:14:29,313 INFO  - df7-wiki-testgenerator ............................ SUCCESS [ 10.267 s]
17:14:29,324 ERROR - Internal error: java.lang.NegativeArraySizeException -> [Help 1]
17:14:29,327 ERROR - org.apache.maven.InternalErrorException: Internal error: java.lang.NegativeArraySizeException
17:14:29,327 ERROR -     at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:167)
17:14:29,327 ERROR -     at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
17:14:29,327 ERROR -     at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
17:14:29,327 ERROR -     at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
17:14:29,327 ERROR -     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:14:29,327 ERROR -     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
17:14:29,327 ERROR -     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:14:29,327 ERROR -     at java.lang.reflect.Method.invoke(Method.java:606)
17:14:29,327 ERROR -     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
17:14:29,327 ERROR -     at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
17:14:29,327 ERROR -     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
17:14:29,327 ERROR -     at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
17:14:29,327 ERROR - Caused by: java.lang.NegativeArraySizeException
17:14:29,328 ERROR -     at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:64)
17:14:29,328 ERROR -     at java.lang.StringBuilder.<init>(StringBuilder.java:97)
17:14:29,328 ERROR -     at org.apache.maven.cli.event.ExecutionEventLogger.chars(ExecutionEventLogger.java:67)
17:14:29,328 ERROR -     at org.apache.maven.cli.event.ExecutionEventLogger.logReactorSummary(ExecutionEventLogger.java:155)
17:14:29,328 ERROR -     at org.apache.maven.cli.event.ExecutionEventLogger.sessionEnded(ExecutionEventLogger.java:111)
17:14:29,328 ERROR -     at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:64)
17:14:29,328 ERROR -     at org.apache.maven.lifecycle.internal.DefaultExecutionEventCatapult.fire(DefaultExecutionEventCatapult.java:42)
17:14:29,329 ERROR -     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:125)
17:14:29,329 ERROR -     at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
17:14:29,329 ERROR -     at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
17:14:29,329 ERROR -     ... 11 more
17:14:29,329 ERROR - 
```

It occurs not every build, but maybe every second or third.
I downloaded the source tar.gz and found that indeed in line 155 of ExecutionEventLogger.java we have

```
154:                String buildTimeDuration = formatDuration( buildSummary.getTime() ); 
155:                buffer.append( chars( ' ', BUILD_TIME_DURATION_LENGTH - buildTimeDuration.length() ) );
```

where

```
47:    private static final int BUILD_TIME_DURATION_LENGTH = 9;
```

However, in `formatDuration`, from `CLIReportingUtils.java` , it seems that the generated strings can well exceed this length:

```
177:            format = "%d d %02d:%02d h";
```

This has, as far as I understand, at least 6 characters, if we add two for minutes and minimum one for hour and one for day, this will already exceed the BUILD_TIME:DURATION_LENGTH. This seems an obvious bug to me.

However our build times are usually less than one hour, so there must be some other reason for our strange long build time duration string.
If the bug above was fixed, we could see better what's going on.

---

**Affects:** 3.2.1

**Attachments:**
- [MNG-5626.patch](https://issues.apache.org/jira/secure/attachment/12713377/MNG-5626.patch) (_2.72 kB_)

**Issue Links:**
- [MNG-5626](https://issues.apache.org/jira/browse/MNG-5626) Avoid negative durations or handle them correctly

- [MNG-5626](https://issues.apache.org/jira/browse/MNG-5626) Avoid negative durations or handle them correctly

0 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Christian, yes, 9 is too short. Do you have build times above 24 hours? Will you be able to test a patch if I provide one?

After a first look, the subtraction has to beimproved. The current formatting aligns all times to the most common build time, namely minutes. They need nine chars. I will take care of this and provide a patch. But the question remains, I hardly can believe that your build time exceeds 24 hours.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Christian, please try this patch against master or [this](https://repository.apache.org/service/local/repositories/snapshots/content/org/apache/maven/apache-maven/3.2.2-SNAPSHOT/apache-maven-3.2.2-20140427.155130-23-bin.tar.gz) snapshot.

**Comment by jira-importer** [comment]
**[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung)** commented

Hi Michael,
thanks for the quick reply and the fix.
I cannot try the fix on our build servers and i am not sure if the error occurs locally.
I will first try to reproduce it locally, and then try your patch.

When will be the next release containing this patch? Probably 3.2.2.

Concerning the strange build times, I still have to investigate this,
but this is maybe a different and more tricky issue.
All our builds are below one hour.

I remember measuring negative times (not with maven),
when the start and end were determined on different processors.
This happens especially when the system has been running for a long time.
This is probably true for our build machines, which are also virtual machines.

Maybe you know better how maven measures the times and if this could happen there as well.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Christian, please mind the link to the snapshot: https://repository.apache.org/service/local/repositories/snapshots/content/org/apache/maven/apache-maven/3.2.2-SNAPSHOT/apache-maven-3.2.2-20140427.155130-23-bin.tar.gz

If you confirm that this has been fixed by my patch, I will commit and it will be included in 3.2.2.

Regarding measuring times: `time mvn ...`

**Comment by jira-importer** [comment]
**[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung)** commented

I could not reproduce it locally until now, I'm now looking for a possibility to use one of the build machines. Stay tuned.

**Comment by jira-importer** [comment]
**[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung)** commented

Concerning the strange timing values:
We recently changed from mvn 3.0.5 to 3.2.1, and i found an older log with the following reactor log snippet:

```
08:25:28,138 INFO  - DF7JavaTest ....................................... SUCCESS [-10.-206s]
```

With mvn 3.2.1 this could clearly account for the behaviour we see, because it adds two extra unexpected minus characters.
The unit test for `formatDuration()` does not cover any negative numbers, which do not make any sense anyway IMHO.
An explicit warning there or in `BuildSummary` might be helpful, to find cases where projects are assigned a negative time.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Christian, now we have two issues here.

1. The original one, the negative array size which should be fixed with the patch and linked snapshot.
2. A negative build time has obviously some other cause and should not be rooted in the `formatDuration` method. I think, this should be in a separate ticket. The code in question requires on the `buildSummary`.

What do you think?

**Comment by jira-importer** [comment]
**[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung)** commented

I found out that the negative time also occurs outside maven, so it is probably an issue of the virtual machine the thing runs on.
The bad thing is that i find it difficult to reproduce the problem, so its also difficult to write a proper bug request.

It may well be that we can not do anything against it, so maven must be able to cope in some way with this kind of problem.
The simplest way would be to print the negative times as they are, so we either leave `formatDuration()` as it is
or extend it to negative times. That negative times are printed in a strange way is surely just a minor problem.

So for now I'd treat this issue as fixed.
You may want to add some test cases to `formatDuration()` if you feel this is necessary.

**Comment by jira-importer** [comment]
**[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ID134349)** commented

A possible Maven enhancement would be to capture negative times and log a WARN with the start and end date.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I am reopening this issue because the problem was actually the `NegativeArraySizeException` and **not** the negative build time. I will commit the patch for this issue.

Please open a further issue for the negativity anomaly.

[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung), can you verify that the negative build time reflects the absolut build time of this project/module?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Paul Benedict](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=paul4christ79), I have never observed such a problem on the maven mailing list. The root cause is either in the `BuildSummary` or the system itself.

**Comment by jira-importer** [comment]
**[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) I saw in one case, that the overall maven build time, as measured from outside (i.e. by our QuickBuild system) was -10.8 seconds. The corresponding reactor summary was:

```
13:55:25,184 INFO  - Reactor Summary:
13:55:25,184 INFO  -
13:55:25,184 INFO  - module1 ........................................... SUCCESS [ 5.911 s]
13:55:25,184 INFO  - module2 ........................................... SUCCESS [ 0.255 s]
13:55:25,184 INFO  - gpPlaygroundBase-lnx-x64-gcc4 ..................... SUCCESS [-27.-64 s]
13:55:25,185 INFO  - ------------------------------------------------------------------------
13:55:25,185 INFO  - BUILD SUCCESS
13:55:25,185 INFO  - ------------------------------------------------------------------------
13:55:25,185 INFO  - Total time: -20.-73 s
13:55:25,185 INFO  - Finished at: 2014-04-28T13:55:25+01:00
13:55:25,572 INFO  - Final Memory: 32M/439M
13:55:25,572 INFO  - ------------------------------------------------------------------------
13:55:25,619 INFO  - Executing post-execute action...
```

Note that this did not crash because the string uses only 9 characters. It had, if the 1000s had been printed correctly as -27.-064

Our administrators suspected that just at this point, the local clock was synchronized with some outer source.

After reading [this stackoverflow article](http://stackoverflow.com/questions/2978598/will-sytem-currenttimemillis-always-return-a-value-previous-calls) i doubt that we can ever be sure that all durations are positive, even if we used `nanoTime()` instead of `getCurrentTimeMillis()`.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung), thanks for the SO question. That would of course affect everyone. Please perform another test: `time mvn package`. Check what duration `time` spits out. I am curious whether this is different from the JVM.

Anyway, please open another issue here and link the SO question. We'll see, how we can cope with this in Maven.

**Comment by jira-importer** [comment]
**[Christian Jung](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christian.jung)** commented

The new issue is MNG-5626.

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) Its currently not possible for me to run any commands on the build servers, but i found a simpler way to reproduce the error:
With the following simple script i reset the time every few seconds:
{code:timewarp.sh}
#!/bin/bash
while true; do
date +%T -s "10:13:13"
sleep 5
date
done

```
This produces negative durations in maven. The output is then:
```

INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] module1 ........................................... SUCCESS [  0.002 s]
[INFO] module2 ........................................... SUCCESS [  0.000 s]
[INFO] gpPlaygroundBase-lnx-x86-gcc4 ..................... SUCCESS [-2.-497 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: -1.-774 s
[INFO] Finished at: 2014-04-29T10:13:14+01:00
[INFO] Final Memory: 17M/310M
[INFO] ------------------------------------------------------------------------

real    0m0.000s
user    0m6.148s
sys     0m0.996s

```
It seems that time does not display any negative times.
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks, I will target this one.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commit;h=45ab718bc0fa1bda6e41dd19a10360fa6953ed19
