### ISSUE TITLE
[MNG-5158] Make loading of extensions from lib/ext more robust with regard to existence of ext directory

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6752]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** opened **[MNG-5158](https://issues.apache.org/jira/browse/MNG-5158?redirect=false)** and commented

Someone who tries to delete or temporarily rename `lib/ext` will get rewarded with an error:

```
java.io.FileNotFoundException: D:\apache-maven-3.0.3\bin\..\lib\ext
        at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.loadGlob(ConfigurationParser.java:336)
        at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.parse(ConfigurationParser.java:247)
        at org.codehaus.plexus.classworlds.launcher.Configurator.configure(Configurator.java:135)
        at org.codehaus.plexus.classworlds.launcher.Launcher.configure(Launcher.java:132)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:405)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
```

Classworlds provides a means to handle a missing dir more gracefully which fits the idea of optional extensions better.

---

**Affects:** 3.0.3

**Issue Links:**
- [MNG-4984](https://issues.apache.org/jira/browse/MNG-4984) Simplify drop in of 3rd party extensions for Maven core

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Done in [r1159520](http://svn.apache.org/viewvc?view=revision&revision=1159520).
