### ISSUE TITLE
[MNG-5573] NPE in legacy DefaultWagonManager

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6758]
**[Richard Opalka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=opalka)** opened **[MNG-5573](https://issues.apache.org/jira/browse/MNG-5573?redirect=false)** and commented

When executing the following command:

mvn idea:idea -DdownloadSources=true" -e

I'm getting the following NPE.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-idea-plugin:2.2:idea (default-cli) on project wildfly-cli: Execution default-cli of goal org.apache.maven.plugins:maven-idea-plugin:2.2:idea failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-idea-plugin:2.2:idea (default-cli) on project wildfly-cli: Execution default-cli of goal org.apache.maven.plugins:maven-idea-plugin:2.2:idea failed.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-idea-plugin:2.2:idea failed.
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
... 19 more
Caused by: java.lang.NullPointerException
at org.apache.maven.repository.legacy.DefaultWagonManager.connectWagon(DefaultWagonManager.java:240)
at org.apache.maven.repository.legacy.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:337)
at org.apache.maven.repository.legacy.DefaultWagonManager.getArtifact(DefaultWagonManager.java:109)
at org.apache.maven.repository.legacy.DefaultWagonManager.getArtifact(DefaultWagonManager.java:161)
at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:155)
at org.apache.maven.plugin.idea.IdeaModuleMojo.resolveClassifiedArtifact(IdeaModuleMojo.java:966)
at org.apache.maven.plugin.idea.IdeaModuleMojo.resolveClassifier(IdeaModuleMojo.java:929)
at org.apache.maven.plugin.idea.IdeaModuleMojo.rewriteDependencies(IdeaModuleMojo.java:569)
at org.apache.maven.plugin.idea.IdeaModuleMojo.rewriteModule(IdeaModuleMojo.java:409)
at org.apache.maven.plugin.idea.IdeaMojo.rewriteModule(IdeaMojo.java:220)
at org.apache.maven.plugin.idea.IdeaMojo.execute(IdeaMojo.java:200)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
... 20 more

---

**Affects:** 3.1.1

**Comment by jira-importer** [comment]
**[Richard Opalka](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=opalka)** commented

I was able to fix this problem locally (local maven 3.1.1 build) by replacing:

if(legacySupport.getRepositorySession() != null )

with

if( legacySupport != null && legacySupport.getRepositorySession() != null )

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

The maven-idea-plugin is deprecated. There is no reason to use it, importing POMs directly into Intellij works very well.
