### ISSUE TITLE
[MNG-5542] Parent resolution issue when using -pl on the command line

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6781]
**[Vincent Massol](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vmassol)** opened **[MNG-5542](https://issues.apache.org/jira/browse/MNG-5542?redirect=false)** and commented

When I build using -pl and one of the pom has a parent that isn't in my local repository, I get a failure:

```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.xwiki.platform:xwiki-platform-core:pom:5.3-SNAPSHOT in local.central (file:///Users/vmassol/.m2/repository)
        at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$6.wrap(WagonRepositoryConnector.java:1012)
        at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$6.wrap(WagonRepositoryConnector.java:1004)
        at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:725)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
```

I think Maven should download it from the remote repository.

To reproduce:
* Remove all org/xwiki artifacts from your local maven repository
* Git clone https://github.com/xwiki/xwiki-platform.git in some directory (let's call it XWIKIHOME)
* Add the XWiki remote repository to your settings.xml, see http://dev.xwiki.org/xwiki/bin/view/Community/Building#HInstallingMaven
* cd in /tmp
* Execute:

```
mvn -B -f XWIKIHOME/xwiki-platform/pom.xml -amd -pl org.xwiki.platform:xwiki-platform-tool-packager-plugin,org.xwiki.platform:xwiki-platform-administration-test-tests,org.xwiki.platform:xwiki-platform-messagestream-test-tests,org.xwiki.platform:xwiki-platform-panels-test-tests,org.xwiki.platform:xwiki-platform-wysiwyg-test-tests clean deploy -Plegacy,integration-tests -U -e
```

---

**Affects:** 3.1.1

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This issue has been auto closed because it has been inactive for a long period of time. If you think this issue still applies, retest your problem with the most recent version of Maven and the affected component, reopen and post your results.
