### ISSUE TITLE
[MNG-5465] Maven repository broken after using a different maven version

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6866]
**[Johannes Pfeifer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=j.pfeifer.pe)** opened **[MNG-5465](https://issues.apache.org/jira/browse/MNG-5465?redirect=false)** and commented

We use Jenkins to build our java products. Our builds broke the maven repositories today, when the maven version changed from one build to another. This was an unknown error of one change that was made to build server (and will never be made again).

In one build the maven version is 3.0.4 and in the next build the maven version 3.0-beta-2 was used. Since then our build maven repository seems to be broken, throwing the exception listed below.

How can we fix this?

We tried clearing the repository by:
1) Re-running the project with maven 3.0.4
2) Removing repository: rm -rfv ~jenkins/.m2/repository
3) Clearing the jenkins workspace: rm -rfv ./*
4) Clearing repository through mojo in pom.xml
   ...

\<executions>
\<execution>
\<id>remove-old-artifacts\</id>
\<phase>package\</phase>
\<goals>
\<goal>remove-project-artifact\</goal>
\</goals>
\<configuration>
\<removeAll>true\</removeAll>
\</configuration>
\</execution>
\</executions>
...

Unfortunatly this did not help and we are still getting this exception:

[ERROR] Internal error: com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting: org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   while locating org.apache.maven.AbstractMavenLifecycleParticipant annotated with `@com`.google.inject.name.Named(value=TychoMavenLifecycleListener)

1 error: Guice provision errors:

1) Error injecting: org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   while locating org.eclipse.tycho.resolver.TychoDependencyResolver
   while locating org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant

1 error: Guice provision errors:

1) No implementation for org.codehaus.plexus.logging.Logger was bound.
   while locating org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver

1 error
-> [Help 1]
org.apache.maven.InternalErrorException: Internal error: com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting: org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   while locating org.apache.maven.AbstractMavenLifecycleParticipant annotated with `@com`.google.inject.name.Named(value=TychoMavenLifecycleListener)

1 error
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:164)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:445)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:168)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
at java.lang.reflect.Method.invoke(Method.java:611)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting: org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   while locating org.apache.maven.AbstractMavenLifecycleParticipant annotated with `@com`.google.inject.name.Named(value=TychoMavenLifecycleListener)

1 error
at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:952)
at org.sonatype.guice.bean.locators.QualifiedBean.getValue(QualifiedBean.java:85)
at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:55)
at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:129)
at java.util.AbstractCollection.addAll(AbstractCollection.java:92)
at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:539)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:265)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
... 11 more
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting: org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   at ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:0.17.0, parent: ClassRealm[maven.api, parent: null]]
   while locating org.eclipse.tycho.resolver.TychoDependencyResolver
   while locating org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant

1 error
at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:952)
at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:978)
at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:996)
at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at com.google.inject.Scopes$1$1.get(Scopes.java:63)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:943)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:989)
at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:939)
... 18 more
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.codehaus.plexus.logging.Logger was bound.
   while locating org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver

1 error
at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:952)
at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:978)
at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:996)
at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
at com.google.inject.Scopes$1$1.get(Scopes.java:63)
at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:943)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:996)
at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:939)
at org.sonatype.guice.bean.locators.QualifiedBean.getValue(QualifiedBean.java:85)
at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:55)
at org.sonatype.guice.plexus.binders.PlexusRequirements$RequirementProvider.get(PlexusRequirements.java:222)
at org.sonatype.guice.plexus.binders.ProvidedPropertyBinding.injectProperty(ProvidedPropertyBinding.java:50)
at org.sonatype.guice.bean.inject.BeanInjector.injectMembers(BeanInjector.java:53)
at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:120)
at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:253)
at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:943)
at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:996)
at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:939)
... 29 more

---

**Affects:** 3.0.4

**Comment by jira-importer** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

The users mailing list is probably more appropriate for this question unless you're saying this is a bug that should be fixed.
