### ISSUE TITLE
[MNG-5211] NPE on org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6914]
**[Amrutraj Patil](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apatil)** opened **[MNG-5211](https://issues.apache.org/jira/browse/MNG-5211?redirect=false)** and commented

Hello,

We are getting following Null Pointer Exception during maven build of one of our module.
We use,
Maven version : 2.2.1
JDK version: 1.6.0_16

Does anyone know what is the resolution for this issue. It looks like something to do with plexus. I have tried with maven 3.0.3 version as well, but didn't help.

[INFO] Building war: /apps/build/hudson_slave/workspace/abc/abc/target/abc.war
[INFO] [assembly:single {execution: bundle-project-artifacts}]
[INFO] Reading assembly descriptor: src/assembly/assembly.xml
[INFO] Building zip: /apps/build/hudson_slave/workspace/abc/abc/target/deployment-package-1.0-SNAPSHOT.zip
[WARNING] DEPRECATED [wait]: The wait parameter is now deprecated, please use cargo:run instead
[HUDSON] Archiving disabled - not archiving /apps/build/hudson_slave/workspace/abc/abc/pom.xml
[HUDSON] Archiving disabled - not archiving /apps/build/hudson_slave/workspace/abc/abc/target/abc.war
[HUDSON] Archiving disabled - not archiving /apps/build/hudson_slave/workspace/abc/abc/target/deployment-package-1.0.zip
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:90)
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:207)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:90)
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:247)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:137)
at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
at hudson.maven.agent.ComponentConfiguratorFilter.configureComponent(ComponentConfiguratorFilter.java:49)
at hudson.maven.agent.PluginManagerInterceptor$MojoIntercepter.configureComponent(PluginManagerInterceptor.java:146)
at org.apache.maven.plugin.DefaultPluginManager.populatePluginFields(DefaultPluginManager.java:1357)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:724)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:468)
at hudson.maven.agent.PluginManagerInterceptor.executeMojo(PluginManagerInterceptor.java:182)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.lifecycle.LifecycleExecutorInterceptor.execute(LifecycleExecutorInterceptor.java:65)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at hudson.maven.agent.Main.launch(Main.java:173)
at hudson.maven.MavenBuilder.call(MavenBuilder.java:164)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:882)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:813)
at hudson.remoting.UserRequest.perform(UserRequest.java:114)
at hudson.remoting.UserRequest.perform(UserRequest.java:48)
at hudson.remoting.Request$2.run(Request.java:270)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:619)

Thanks,
Amrutraj

---

**Affects:** 2.2.1

**Attachments:**
- [NPE.txt](https://issues.apache.org/jira/secure/attachment/12713263/NPE.txt) (_5.41 kB_)

**Comment by jira-importer** [comment]
**[Amrutraj Patil](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apatil)** commented

Anybody had chance to look in to this? Any pointers will definitely help us.

**Comment by jira-importer** [comment]
**[Amrutraj Patil](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apatil)** commented

This is resolved in our case. One of the configured variable for cargo plugin settings was null. Closing this issue.
