### ISSUE TITLE
[MNG-5307] NPE during resolution of dependencies - parallel mode

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#6928]
**[Jeroen Benckhuijsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeroen.benckhuijsen)** opened **[MNG-5307](https://issues.apache.org/jira/browse/MNG-5307?redirect=false)** and commented

When building a project for the first time, maven fails with an internal NPE (see stacktrace below). This happens in case the first build is a parallel build (-T 5C), regardless for the actual goal (install, deploy,..). When the build is first run without -T, subsequent builds run without any issues.

Given the code in http://svn.apache.org/viewvc/maven/maven-3/tags/maven-3.0.4/maven-core/src/main/java/org/apache/maven/lifecycle/internal/MojoExecutor.java?revision=1232336&view=markup projectToResolve seems to be null, which seems to be a MavenSession problem (just guessing here).

Stacktrace:

```
5-Jul-2012 01:03:50	[INFO] BUILD FAILURE
05-Jul-2012 01:03:50	[INFO] ------------------------------------------------------------------------
05-Jul-2012 01:03:50	[INFO] Total time: 13.424s (Wall Clock)
05-Jul-2012 01:03:50	[INFO] Finished at: Thu Jul 05 01:03:50 CEST 2012
05-Jul-2012 01:03:50	[INFO] Final Memory: 107M/361M
05-Jul-2012 01:03:50	[INFO] ------------------------------------------------------------------------
05-Jul-2012 01:03:50	[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
05-Jul-2012 01:03:50	org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:167)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:163)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:315)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask.run(FutureTask.java:150)
05-Jul-2012 01:03:50	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:453)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:315)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask.run(FutureTask.java:150)
05-Jul-2012 01:03:50	        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:898)
05-Jul-2012 01:03:50	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:920)
05-Jul-2012 01:03:50	        at java.lang.Thread.run(Thread.java:736)
05-Jul-2012 01:03:50	Caused by: java.lang.NullPointerException
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:289)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
05-Jul-2012 01:03:50	        ... 10 more
05-Jul-2012 01:03:50	[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
05-Jul-2012 01:03:50	org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:167)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:163)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:315)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask.run(FutureTask.java:150)
05-Jul-2012 01:03:50	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:453)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:315)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask.run(FutureTask.java:150)
05-Jul-2012 01:03:50	        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:898)
05-Jul-2012 01:03:50	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:920)
05-Jul-2012 01:03:50	        at java.lang.Thread.run(Thread.java:736)
05-Jul-2012 01:03:50	Caused by: java.lang.NullPointerException
05-Jul-2012 01:03:50	        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.calcImports(DefaultMavenPluginManager.java:406)
05-Jul-2012 01:03:50	        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:302)
05-Jul-2012 01:03:50	        at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:175)
05-Jul-2012 01:03:50	        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:78)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
05-Jul-2012 01:03:50	        ... 10 more
05-Jul-2012 01:03:50	[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.3.1:install (default-install) on project domainservices: Failed to install metadata nl.apg.gps:domainservices:2012.2.1.0-SNAPSHOT/maven-metadata.xml: Could not read metadata /var/maven/repo3/nl/apg/gps/domainservices/2012.2.1.0-SNAPSHOT/maven-metadata-local.xml: input contained no data -> [Help 2]
05-Jul-2012 01:03:50	org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.3.1:install (default-install) on project domainservices: Failed to install metadata nl.apg.gps:domainservices:2012.2.1.0-SNAPSHOT/maven-metadata.xml: Could not read metadata /var/maven/repo3/nl/apg/gps/domainservices/2012.2.1.0-SNAPSHOT/maven-metadata-local.xml: input contained no data
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:167)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:163)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:315)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask.run(FutureTask.java:150)
05-Jul-2012 01:03:50	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:453)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:315)
05-Jul-2012 01:03:50	        at java.util.concurrent.FutureTask.run(FutureTask.java:150)
05-Jul-2012 01:03:50	        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:898)
05-Jul-2012 01:03:50	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:920)
05-Jul-2012 01:03:50	        at java.lang.Thread.run(Thread.java:736)
05-Jul-2012 01:03:50	Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install metadata nl.apg.gps:domainservices:2012.2.1.0-SNAPSHOT/maven-metadata.xml: Could not read metadata /var/maven/repo3/nl/apg/gps/domainservices/2012.2.1.0-SNAPSHOT/maven-metadata-local.xml: input contained no data
05-Jul-2012 01:03:50	        at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:139)
05-Jul-2012 01:03:50	        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
05-Jul-2012 01:03:50	        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
05-Jul-2012 01:03:50	        ... 13 more
05-Jul-2012 01:03:50	Caused by: org.apache.maven.artifact.installer.ArtifactInstallationException: Failed to install metadata nl.apg.gps:domainservices:2012.2.1.0-SNAPSHOT/maven-metadata.xml: Could not read metadata /var/maven/repo3/nl/apg/gps/domainservices/2012.2.1.0-SNAPSHOT/maven-metadata-local.xml: input contained no data
05-Jul-2012 01:03:50	        at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:111)
05-Jul-2012 01:03:50	        at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:89)
05-Jul-2012 01:03:50	        ... 15 more
05-Jul-2012 01:03:50	Caused by: org.sonatype.aether.installation.InstallationException: Failed to install metadata nl.apg.gps:domainservices:2012.2.1.0-SNAPSHOT/maven-metadata.xml: Could not read metadata /var/maven/repo3/nl/apg/gps/domainservices/2012.2.1.0-SNAPSHOT/maven-metadata-local.xml: input contained no data
05-Jul-2012 01:03:50	        at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:313)
05-Jul-2012 01:03:50	        at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:211)
05-Jul-2012 01:03:50	        at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:158)
05-Jul-2012 01:03:50	        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.install(DefaultRepositorySystem.java:436)
05-Jul-2012 01:03:50	        at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:107)
05-Jul-2012 01:03:50	        ... 16 more
05-Jul-2012 01:03:50	Caused by: org.sonatype.aether.RepositoryException: Could not read metadata /var/maven/repo3/nl/apg/gps/domainservices/2012.2.1.0-SNAPSHOT/maven-metadata-local.xml: input contained no data
05-Jul-2012 01:03:50	        at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:101)
05-Jul-2012 01:03:50	        at org.apache.maven.repository.internal.MavenMetadata.merge(MavenMetadata.java:69)
05-Jul-2012 01:03:50	        at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:301)
05-Jul-2012 01:03:50	        ... 20 more
05-Jul-2012 01:03:50	Caused by: java.io.EOFException: input contained no data
05-Jul-2012 01:03:50	        at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:3005)
05-Jul-2012 01:03:50	        at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3048)
05-Jul-2012 01:03:50	        at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1422)
05-Jul-2012 01:03:50	        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1407)
05-Jul-2012 01:03:50	        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
05-Jul-2012 01:03:50	        at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1193)
05-Jul-2012 01:03:50	        at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1122)
05-Jul-2012 01:03:50	        at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:97)
05-Jul-2012 01:03:50	        ... 22 more
05-Jul-2012 01:03:50	[ERROR] 
```

---

**Affects:** 3.0.4

**Issue Links:**
- [MNG-2802](https://issues.apache.org/jira/browse/MNG-2802) Concurrent-safe access to local Maven repository
 (_**"is a child of"**_)
- [MINSTALL-54](https://issues.apache.org/jira/browse/MINSTALL-54) [INFO] Error installing artifact's metadata

- [MNG-6996](https://issues.apache.org/jira/browse/MNG-6996) Upgrade Maven Resolver to 1.6.1
 (_**"requires"**_)

**Backported to:** [4.0.0-alpha-2](https://github.com/apache/maven/milestone/113?closed=1), [3.8.2](https://github.com/apache/maven/milestone/103?closed=1)

0 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Tibor Digana](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tibor17)** commented

I have the same observations with Maven 3.0.3.
Project executing in parallel -T 2C.
My project crashed on aggregator.

Does it mean that some variables are thread-unsafe?

    [exec] [ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
    [exec] org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
    [exec] 	at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
    [exec] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
    [exec] 	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:167)
    [exec] 	at org.apache.maven.lifecycle.internal.LifecycleThreadedBuilder$1.call(LifecycleThreadedBuilder.java:164)
    [exec] 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    [exec] 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    [exec] 	at java.lang.Thread.run(Thread.java:662)
    [exec] Caused by: java.lang.NullPointerException
    [exec] 	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.calcImports(DefaultMavenPluginManager.java:406)
    [exec] 	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:302)
    [exec] 	at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:175)
    [exec] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:78)
    [exec] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    [exec] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    [exec] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    [exec] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    [exec] 	... 10 more

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Hi, we are seeing this as well sporadically on our Jenkins instance. The exceptions occurs every couple of weeks on a different part of the build each time. There is currently no pattern emerging as to what is triggering the errors.

Our environment:
Linux (RHEL 6), Java 1.6.0_45, Maven 3.0.4 and 3.1.1 (I have bumped these to 3.0.5 and 3.2.1 now to see if it makes a difference), Jenkins 1.509.4

We are not running parallel builds, just "clean install -e". This is a trunks type of build with about 120 projects and modules. Maven Install Plugin version is either 2.4 or 2.5.1 depending on the sub project being built, and the errors have happened for both versions.

Here is the latest stack trace (for the job running Maven 3.0.4)

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.1:install (default-install) on project mdh-java-parent: Failed to install metadata se.mdh:mdh-java-parent:25-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/mdh-java-parent/25-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
	at org.jvnet.hudson.maven3.agent.Maven3Main.launch(Maven3Main.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:129)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:67)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install metadata se.mdh:mdh-java-parent:25-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/mdh-java-parent/25-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.plugin.install.InstallMojo.installProject(InstallMojo.java:239)
	at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 31 more
Caused by: org.apache.maven.artifact.installer.ArtifactInstallationException: Failed to install metadata se.mdh:mdh-java-parent:25-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/mdh-java-parent/25-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:111)
	at org.apache.maven.plugin.install.InstallMojo.installProject(InstallMojo.java:185)
	... 34 more
Caused by: org.sonatype.aether.installation.InstallationException: Failed to install metadata se.mdh:mdh-java-parent:25-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/mdh-java-parent/25-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:313)
	at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:211)
	at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:158)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.install(DefaultRepositorySystem.java:436)
	at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:107)
	... 35 more
Caused by: org.sonatype.aether.RepositoryException: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/mdh-java-parent/25-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:101)
	at org.apache.maven.repository.internal.MavenMetadata.merge(MavenMetadata.java:69)
	at org.sonatype.aether.impl.internal.DefaultInstaller.install(DefaultInstaller.java:301)
	... 39 more
Caused by: java.io.EOFException: input contained no data
	at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:3005)
	at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3048)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1422)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1407)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1193)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:1122)
	at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:97)
	... 41 more
```

Here is the latest stack trace (for the job running Maven 3.1.1)

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.4:install (default-install) on project mdh-html: Failed to install metadata se.mdh.html:mdh-html:5.7-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/html/mdh-html/5.7-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:129)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:67)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install metadata se.mdh.html:mdh-html:5.7-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/html/mdh-html/5.7-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:153)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 31 more
Caused by: org.apache.maven.artifact.installer.ArtifactInstallationException: Failed to install metadata se.mdh.html:mdh-html:5.7-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/html/mdh-html/5.7-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:111)
	at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:101)
	... 33 more
Caused by: org.eclipse.aether.installation.InstallationException: Failed to install metadata se.mdh.html:mdh-html:5.7-SNAPSHOT/maven-metadata.xml: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/html/mdh-html/5.7-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:333)
	at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:231)
	at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:178)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.install(DefaultRepositorySystem.java:406)
	at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:107)
	... 34 more
Caused by: org.eclipse.aether.RepositoryException: Could not read metadata /jenkins/home/jenkins/.m2/repository/se/mdh/html/mdh-html/5.7-SNAPSHOT/maven-metadata-local.xml: input contained no data
	at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:107)
	at org.apache.maven.repository.internal.MavenMetadata.merge(MavenMetadata.java:75)
	at org.eclipse.aether.internal.impl.DefaultInstaller.install(DefaultInstaller.java:321)
	... 38 more
Caused by: java.io.EOFException: input contained no data
	at org.codehaus.plexus.util.xml.pull.MXParser.fillBuf(MXParser.java:3031)
	at org.codehaus.plexus.util.xml.pull.MXParser.more(MXParser.java:3074)
	at org.codehaus.plexus.util.xml.pull.MXParser.parseProlog(MXParser.java:1448)
	at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1433)
	at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:913)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:519)
	at org.apache.maven.repository.internal.MavenMetadata.read(MavenMetadata.java:103)
	... 40 more
```

If the bumped Maven versions does not solve this, I'll set up a job for maven-trunks, or something similar, using our settings on our Jenkins to see if I can trigger the same exception.

**Comment by jira-importer** [comment]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** commented

Hasn't been reported for a while. Is this still happening?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This still may be the case, but requires confirmation.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

MRESOLVER-131 introduces a fully new, multi-JVM concurrent approach based on Redis. Try it from here: https://github.com/apache/maven-resolver/tree/MRESOLVER-131. Read it from here: https://maven.apache.org/resolver-archives/resolver-LATEST/maven-resolver-synccontext-redisson/index.html

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Use any of the two new sync contexts to solve this concurrency issue.
