### ISSUE TITLE
[MNG-5162] Maven stuck on downloading dependencies when using java 7.

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7014]
**[Lukas Stampf](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=l.stampf)** opened **[MNG-5162](https://issues.apache.org/jira/browse/MNG-5162?redirect=false)** and commented

When JAVA_HOME is set to the Java 7 JDK and I run "mvn clean install" on my project the following happens:
Maven downloads the dependencies to my local repository, as usual, but on some dependencies he stops while downloading and never continues. He is just stuck. I then must use CTRL+C and start from the beginning with my build, but it doesnt help because he gets stuck at the same dependencies again. In my local repository, where the failed dependency belongs is just a tmp file like: org.apache.servicemix.bundles.serp-1.13.1_4.jar.tmp90088a9d7e9e4642

When I set JAVA_HOME to java 6 Update 27 everything works fine.
The problem does not seem to be related to JAR size because, I saw it fail on 19kb dependencies as well.
I have the impression it happens mostly to JARs with "long" names.

Attached you will find a subproject of the project I am working on. it contains the org.apache.servicemix.bundles.serp-1.13.1_4 dependency, which is one of almost all servicemix bundles that is failing for me, when i use java7.

---

**Affects:** 3.0.1, 3.0.3

**Attachments:**
- [dump.tdump](https://issues.apache.org/jira/secure/attachment/12712748/dump.tdump) (_13.38 kB_)
- [edb.zip](https://issues.apache.org/jira/secure/attachment/12713342/edb.zip) (_115.27 kB_)
- [java6.jpg](https://issues.apache.org/jira/secure/attachment/12713160/java6.jpg) (_139.67 kB_)
- [java7.jpg](https://issues.apache.org/jira/secure/attachment/12713165/java7.jpg) (_66.01 kB_)

6 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

A thread dump, e.g. taking via jvisualvm, when the process gets stuck, would be helpful.

**Comment by jira-importer** [comment]
**[Lukas Stampf](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=l.stampf)** commented

dump taken when stuck added

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

According to that thread dump, the main thread just is waiting for the download to finish (pool-1-thread-1). How long exactly did you wait for it to finish before you aborted it? The default request timeout is 60s, so I'm curious whether the transfer eventually fails with a timeout error after that period. If indeed the download itself gets stuck, you might need to bug Oracle about that issue in their HTTP client code. On the Maven side, the only option appears to be using a different wagon impl, e.g. by declaring `org.apache.maven.wagon:wagon-http:1.0` as a build extension.

**Comment by jira-importer** [comment]
**[Lukas Stampf](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=l.stampf)** commented

just tested again for exactly 10 minutes. No changes still stuck.

**Comment by jira-importer** [comment]
**[Alexander Panzhin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jalexoid)** commented

Exactly the same problem with Maven 2.2.1. Gets stuck no matter what.
Using single fetching or multiple fetching makes no difference (-Dmaven.artifact.threads=1 or -Dmaven.artifact.threads=5)

To be fair, Maven tends to get stuck hen downloading on 1.5.0_22 and 1.6.0_27 also.

I'd say that this is a Critical bug on Java7, since it renders Maven unusable.

(Microsoft Windows7 x64 [Version 6.1.7601]; Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode); Java HotSpot(TM) 64-Bit Server VM (build 20.2-b06, mixed mode) ;Java HotSpot(TM) 64-Bit Server VM (build 1.5.0_22-b03, mixed mode))

Problem most critical on:
Apache Maven 2.2.1 (r801777; 2009-08-06 20:16:01+0100)
Java version: 1.7.0
Java home: C:\Program Files\Java\jdk1.7.0\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7" version: "6.1" arch: "amd64" Family: "windows"

Apache Maven 3.0.3 (r1075438; 2011-02-28 17:31:09+0000)
Maven home: c:\x\apache-maven-3.0.3\bin\..
Java version: 1.7.0, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

Problems rarely occur on:

Apache Maven 2.2.1 (r801777; 2009-08-06 20:16:01+0100)
Java version: 1.5.0_22
Java home: C:\Program Files\Java\jdk1.5.0_22\jre
Default locale: en_IE, platform encoding: Cp1252
OS name: "windows 7" version: "6.1" arch: "amd64" Family: "windows"

Apache Maven 3.0.3 (r1075438; 2011-02-28 17:31:09+0000)
Maven home: c:\x\apache-maven-3.0.3\bin\..
Java version: 1.5.0_22, vendor: Sun Microsystems Inc.
Java home: C:\Program Files\Java\jdk1.5.0_22\jre
Default locale: en_IE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

**Comment by jira-importer** [comment]
**[Tony Childs](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=programmist)** commented

I've had the same issue and have had to switch back to Java 1.6 because of this.

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

could you please try with 3.0.4 RC4 ?
see http://markmail.org/message/nlawddtd3lfhhdtd
Thanks.

**Comment by jira-importer** [comment]
**[Damien Coraboeuf](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dcoraboeuf)** commented

Is there any update on this issue? Because it really make Maven unuseable with JDK 7.

**Comment by jira-importer** [comment]
**[Damien Coraboeuf](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dcoraboeuf)** commented

I have tested with following version:

```
$ mvn --version
Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Maven home: d:\data\damien\app\apache-maven-3.0.4
Java version: 1.7.0_03, vendor: Oracle Corporation
Java home: c:\Program Files\Java\jdk1.7.0_03\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

The downloads get stuck. If I interrupt the process (ctrl-c) and restart, the download resumes until it stops again.

**Comment by jira-importer** [comment]
**[Yoel Kazareski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yo_el_yoel)** commented

It may be a bug between Java 7 and Windows 64bit.

Found this:
http://blog.bielu.com/2011/11/hotspot-64bit-server-hangs-on-socket.html

**Comment by jira-importer** [comment]
**[gopi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gkrsihan)** commented

Today i have upgraded maven 2.2.1 to 3.0.4 on Linux 64 bit system and when i invoke "mvn clean install" command build is keep throwing below exceptions since 8 hours and build still going.   (Note: everything works fine on Window system for the same project with maven 3.0.4)

-bash-3.2$ mvn --version
Apache Maven 3.0.4 (r1232337; 2012-01-17 00:44:56-0800)
Maven home: /usr/local/maven/apache-maven-3.0.4
Java version: 1.6.0_29, vendor: Sun Microsystems Inc.
Java home: /usr/java/jdk1.6.0_29/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "2.6.18-194.3.1.el5", arch: "amd64", family: "unix"

Please suggest, if i miss any steps.

28-Mar-2012 09:41:36  Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-jar-plugin/maven-metadata.xml (588 B at 0.7 KB/sec)
28-Mar-2012 09:42:06  [WARNING] Failed to write resolution tracking file /home/gopigadu/.m2/repository/org/apache/maven/plugins/maven-jar-plugin/resolver-status.properties
28-Mar-2012 09:42:06  java.io.IOException: No locks available

28-Mar-2012 09:43:06  [WARNING] Failed to write resolution tracking file /home/gopigadu/.m2/repository/org/apache/maven/plugins/maven-jar-plugin/2.4/_maven.repositories
28-Mar-2012 09:43:06  java.io.IOException: No locks available

**Comment by jira-importer** [comment]
**[Rene Schwietzke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=renes)** commented

I have exactly the same problem. Ubuntu 64Bit/Java 7/ Maven 2.2.1 -> maven gets stuck while downloading the dependencies. Switching to Java 6 on the same machine and the download works fine.

**Comment by jira-importer** [comment]
**[David Boden](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daveboden)** commented

Thread dump when stuck on Java 7:

2012-04-07 00:04:54
Full thread dump Java HotSpot(TM) Client VM (22.1-b02 mixed mode, sharing):

"RMI TCP Connection(2)-192.168.0.201" daemon prio=6 tid=0x0475ec00 nid=0x1bc0 runnable [0x064ef000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:150)
at java.net.SocketInputStream.read(SocketInputStream.java:121)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
- locked <0x244007c8> (a java.io.BufferedInputStream)
  at java.io.FilterInputStream.read(FilterInputStream.java:83)
  at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:535)
  at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:808)
  at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
  at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- <0x24400928> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"JMX server connection timeout 42" daemon prio=6 tid=0x0475e400 nid=0x1790 in Object.wait() [0x0633f000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
- waiting on <0x244009c0> (a [I)
  at com.sun.jmx.remote.internal.ServerCommunicatorAdmin$Timeout.run(ServerCommunicatorAdmin.java:168)
- locked <0x244009c0> (a [I)
  at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- None

"RMI Scheduler(0)" daemon prio=6 tid=0x0475e000 nid=0x17f0 waiting on condition [0x0539f000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x24400a48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807)
  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
  at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- None

"RMI TCP Connection(idle)" daemon prio=6 tid=0x0475d800 nid=0x1394 waiting on condition [0x061cf000]
java.lang.Thread.State: TIMED_WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x2444b960> (a java.util.concurrent.SynchronousQueue$TransferStack)
  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
  at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:359)
  at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:942)
  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
  at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- None

"RMI TCP Accept-0" daemon prio=6 tid=0x0475d000 nid=0x1914 runnable [0x00dbf000]
java.lang.Thread.State: RUNNABLE
at java.net.DualStackPlainSocketImpl.accept0(Native Method)
at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:121)
at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:183)
- locked <0x24402ef8> (a java.net.SocksSocketImpl)
  at java.net.ServerSocket.implAccept(ServerSocket.java:522)
  at java.net.ServerSocket.accept(ServerSocket.java:490)
  at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
  at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:387)
  at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:359)
  at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- None

"pool-26-thread-5" prio=6 tid=0x0475cc00 nid=0x6cc waiting on condition [0x0572f000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x24403090> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1043)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1103)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
  at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- None

"pool-26-thread-4" prio=6 tid=0x0475c400 nid=0xa38 runnable [0x0552f000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:150)
at java.net.SocketInputStream.read(SocketInputStream.java:121)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:195)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:173)
at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:138)
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:493)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:339)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:310)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:287)
at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- <0x244066a8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-26-thread-3" prio=6 tid=0x0475c000 nid=0x1ff0 runnable [0x053ef000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:150)
at java.net.SocketInputStream.read(SocketInputStream.java:121)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:195)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:173)
at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:138)
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:493)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:339)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:310)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:287)
at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- <0x24409b98> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-26-thread-2" prio=6 tid=0x050f3400 nid=0x14fc runnable [0x054de000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:150)
at java.net.SocketInputStream.read(SocketInputStream.java:121)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:195)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:173)
at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:138)
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:493)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:339)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:310)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:287)
at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- <0x2440d088> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pool-26-thread-1" prio=6 tid=0x048a9000 nid=0x7d8 runnable [0x0543f000]
java.lang.Thread.State: RUNNABLE
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:150)
at java.net.SocketInputStream.read(SocketInputStream.java:121)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:149)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:110)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:195)
at org.apache.maven.wagon.providers.http.httpclient.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:173)
at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:138)
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:493)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:339)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:310)
at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:287)
at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:97)
at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)

Locked ownable synchronizers:
- <0x2440e4f0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"Service Thread" daemon prio=6 tid=0x00a19800 nid=0x216c runnable [0x00000000]
java.lang.Thread.State: RUNNABLE

Locked ownable synchronizers:
- None

"C1 CompilerThread0" daemon prio=10 tid=0x00a14400 nid=0x12c4 waiting on condition [0x00000000]
java.lang.Thread.State: RUNNABLE

Locked ownable synchronizers:
- None

"Attach Listener" daemon prio=10 tid=0x00a13000 nid=0x189c waiting on condition [0x00000000]
java.lang.Thread.State: RUNNABLE

Locked ownable synchronizers:
- None

"Signal Dispatcher" daemon prio=10 tid=0x00a0fc00 nid=0x1df8 runnable [0x00000000]
java.lang.Thread.State: RUNNABLE

Locked ownable synchronizers:
- None

"Finalizer" daemon prio=8 tid=0x009fe000 nid=0x1384 in Object.wait() [0x00d0f000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
- waiting on <0x29440288> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
- locked <0x29440288> (a java.lang.ref.ReferenceQueue$Lock)
  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:177)

Locked ownable synchronizers:
- None

"Reference Handler" daemon prio=10 tid=0x009f9400 nid=0xe9c in Object.wait() [0x00e7f000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
- waiting on <0x29440310> (a java.lang.ref.Reference$Lock)
  at java.lang.Object.wait(Object.java:503)
  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
- locked <0x29440310> (a java.lang.ref.Reference$Lock)

Locked ownable synchronizers:
- None

"main" prio=6 tid=0x003b9800 nid=0x1cc8 waiting on condition [0x0086e000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder.awaitTerminationOfAllRunnables(RunnableErrorForwarder.java:115)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder.await(RunnableErrorForwarder.java:88)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.get(WagonRepositoryConnector.java:448)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:457)
at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:207)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:353)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:321)
- locked <0x295fddc0> (a org.apache.maven.plugin.internal.DefaultMavenPluginManager)
  at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:175)
  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:78)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
  at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:601)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

Locked ownable synchronizers:
- None

"VM Thread" prio=10 tid=0x009f7400 nid=0x18c4 runnable

"VM Periodic Task Thread" prio=10 tid=0x00a2b800 nid=0x1dd0 waiting on condition

JNI global references: 245

**Comment by jira-importer** [comment]
**[Jukka Zitting](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jukka)** commented

Setting `MAVEN_OPTS` to `-Djava.net.preferIPv4Stack=true` fixed this problem for me.

```
Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Maven home: c:\Program Files\apache-maven-3.0.4
Java version: 1.7.0_04, vendor: Oracle Corporation
Java home: c:\Program Files\Java\jdk1.7.0_04\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"
```

**Comment by jira-importer** [comment]
**[Damien Coraboeuf](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dcoraboeuf)** commented

> Setting `MAVEN_OPTS` to `-Djava.net.preferIPv4Stack=true`

It seems to do the trick as well :) I'm back to JDK7.

Thanks,
Damien.

**Comment by jira-importer** [comment]
**[Barrie Treloar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baerrach)** commented

This is probably not a bug with Maven but with Java and the IP stack selection.

Since there is a workaround (i.e. for IPv4), will close this as not a bug.

Documented at https://cwiki.apache.org/confluence/display/MAVEN/ConnectException

**Comment by jira-importer** [comment]
**[Barrie Treloar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baerrach)** commented

Added code to exception handling to link to https://cwiki.apache.org/confluence/display/MAVEN/ConnectException
