### ISSUE TITLE
[MNG-5157] NPE stemming from DefaultModelBuilder.containsCoordinates

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7015]
**[Andrew Lee Rubinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alr@alrubinger.com)** opened **[MNG-5157](https://issues.apache.org/jira/browse/MNG-5157?redirect=false)** and commented

[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.NullPointerException
at java.lang.String.contains(String.java:2103)
at org.apache.maven.model.building.DefaultModelBuilder.containsCoordinates(DefaultModelBuilder.java:1047)
at org.apache.maven.model.building.DefaultModelBuilder.importDependencyManagement(DefaultModelBuilder.java:948)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:403)
at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:374)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:536)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:542)
at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:328)
at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:632)
at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:581)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:233)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
... 11 more

I was able to come across this by declaring in a parent POM a dependencyManagement/dependency entry, then in a child POM putting the same dependencyManagement/dependency entry in place, this time w/ "import" scope.

---

**Affects:** 3.0.3

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r1158623](http://svn.apache.org/viewvc?view=revision&revision=1158623). What mvn meant to report is that your dependency declaration for the import POM is missing one of the coordinates groupId, artifactId or version.

**Comment by jira-importer** [comment]
**[Andrew Lee Rubinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=alr@alrubinger.com)** commented

My thanks. :)

https://twitter.com/#!/ALRubinger/status/103784873315143680
