### ISSUE TITLE
[MNG-5009] StackOverflowError in DefaultProjectBuilder.build when <module> points at current aggregator POM

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7149]
**[Igor Fedorenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf)** opened **[MNG-5009](https://issues.apache.org/jira/browse/MNG-5009?redirect=false)** and commented

I was refactoring m2e unit tests and got the following StackOverflowError when rebuilding test artifact repository (see below). To reproduce, run "mvn clean" from testLifecycleMappingMetadata of the attached project. I'll provide more info when I figure out what causes this.

```
[INFO] Scanning for projects...
---------------------------------------------------
constituent[0]: file:/opt/maven/lib/maven-embedder-3.0.2.jar
constituent[1]: file:/opt/maven/lib/maven-settings-3.0.2.jar
constituent[2]: file:/opt/maven/lib/plexus-utils-2.0.4.jar
constituent[3]: file:/opt/maven/lib/maven-core-3.0.2.jar
constituent[4]: file:/opt/maven/lib/maven-model-3.0.2.jar
constituent[5]: file:/opt/maven/lib/maven-settings-builder-3.0.2.jar
constituent[6]: file:/opt/maven/lib/plexus-interpolation-1.14.jar
constituent[7]: file:/opt/maven/lib/plexus-component-annotations-1.5.5.jar
constituent[8]: file:/opt/maven/lib/plexus-sec-dispatcher-1.3.jar
constituent[9]: file:/opt/maven/lib/plexus-cipher-1.4.jar
constituent[10]: file:/opt/maven/lib/maven-repository-metadata-3.0.2.jar
constituent[11]: file:/opt/maven/lib/maven-artifact-3.0.2.jar
constituent[12]: file:/opt/maven/lib/maven-plugin-api-3.0.2.jar
constituent[13]: file:/opt/maven/lib/sisu-inject-plexus-1.4.3.1.jar
constituent[14]: file:/opt/maven/lib/sisu-inject-bean-1.4.3.1.jar
constituent[15]: file:/opt/maven/lib/sisu-guice-2.9.1-noaop.jar
constituent[16]: file:/opt/maven/lib/maven-model-builder-3.0.2.jar
constituent[17]: file:/opt/maven/lib/maven-aether-provider-3.0.2.jar
constituent[18]: file:/opt/maven/lib/aether-api-1.9.jar
constituent[19]: file:/opt/maven/lib/aether-spi-1.9.jar
constituent[20]: file:/opt/maven/lib/aether-util-1.9.jar
constituent[21]: file:/opt/maven/lib/aether-impl-1.9.jar
constituent[22]: file:/opt/maven/lib/maven-compat-3.0.2.jar
constituent[23]: file:/opt/maven/lib/wagon-provider-api-1.0-beta-7.jar
constituent[24]: file:/opt/maven/lib/commons-cli-1.2.jar
constituent[25]: file:/opt/maven/lib/wagon-http-lightweight-1.0-beta-7.jar
constituent[26]: file:/opt/maven/lib/wagon-http-shared-1.0-beta-7.jar
constituent[27]: file:/opt/maven/lib/xercesMinimal-1.9.6.2.jar
constituent[28]: file:/opt/maven/lib/nekohtml-1.9.6.2.jar
constituent[29]: file:/opt/maven/lib/wagon-file-1.0-beta-7.jar
constituent[30]: file:/opt/maven/lib/aether-connector-wagon-1.9.jar
---------------------------------------------------
Exception in thread "main" java.lang.StackOverflowError
	at java.util.Vector.size(Vector.java:268)
	at java.util.Stack.pop(Stack.java:65)
	at org.codehaus.plexus.interpolation.PrefixAwareRecursionInterceptor.expressionResolutionFinished(PrefixAwareRecursionInterceptor.java:85)
	at org.codehaus.plexus.interpolation.StringSearchInterpolator.interpolate(StringSearchInterpolator.java:246)
	at org.codehaus.plexus.interpolation.StringSearchInterpolator.interpolate(StringSearchInterpolator.java:124)
	at org.apache.maven.model.interpolation.AbstractStringBasedModelInterpolator.interpolateInternal(AbstractStringBasedModelInterpolator.java:241)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction.traverseObjectWithParents(StringSearchModelInterpolator.java:158)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction.traverseObjectWithParents(StringSearchModelInterpolator.java:305)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator$InterpolateObjectAction.run(StringSearchModelInterpolator.java:122)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator.interpolateObject(StringSearchModelInterpolator.java:75)
	at org.apache.maven.model.interpolation.StringSearchModelInterpolator.interpolateModel(StringSearchModelInterpolator.java:58)
	at org.apache.maven.model.building.DefaultModelBuilder.interpolateModel(DefaultModelBuilder.java:643)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:339)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:354)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:417)
        ....
```

---

**Affects:** 2.2.1, 3.0.2

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12713299/pom.xml) (_488 bytes_)

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Fixed in [r1070083](http://svn.apache.org/viewvc?view=revision&revision=1070083).
