### ISSUE TITLE
[MNG-6404] Cassandra-Maven plugin does not start

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7208]
**[Ravindra](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rrb441)** opened **[MNG-6404](https://issues.apache.org/jira/browse/MNG-6404?redirect=false)** and commented

I am working on Spring Boot REST API. I use cassandra-maven plugin to start the cassandra instance to run in local for integration testing purposes. The cassandra starts sometimes with out any issues and executes all the integration tests but most of the time it throws the following error mentioned below. I cannot figure how to resolve the issue. I have attached the pom.xml where I used the plugin. Thanks in advance.

```
 

[INFO] Cassandra not running!
 [INFO] ------------------------------------------------------------------------
 [INFO] BUILD FAILURE
 [INFO] ------------------------------------------------------------------------
 [INFO] Total time: 03:18 min
 [INFO] Finished at: 2018-05-09T17:57:11-05:00
 [INFO] Final Memory: 95M/1452M
 [INFO] ------------------------------------------------------------------------
 [ERROR] Failed to execute goal org.codehaus.mojo:cassandra-maven-plugin:3.5:start (start-cassandra) on project odr-parameter-cloud: Cassandra failed to start within 180s -> [Help 1]org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:cassandra-maven-plugin:3.5:start (start-cassandra) on project odr-parameter-cloud: Cassandra failed to start within 180s
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
 at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
 at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
 at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
 at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
 at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
 at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
 at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
 at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
 at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
 Caused by: org.apache.maven.plugin.MojoFailureException: Cassandra failed to start within 180s
 at org.codehaus.mojo.cassandra.StartCassandraMojo.execute(StartCassandraMojo.java:107)
 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
 ... 21 more

[ERROR] 
 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
 [ERROR] 
 [ERROR] For more information about the errors and possible solutions, please read the following articles:
 [ERROR] [Help 1] [http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException]

 
```

 

Can you please help me with this.

 

 

---

**Affects:** 3.5.0

**Attachments:**
- [Error Screen.png](https://issues.apache.org/jira/secure/attachment/12922752/Error+Screen.png) (_553.84 kB_)
- [pom.png](https://issues.apache.org/jira/secure/attachment/12922753/pom.png) (_249.10 kB_)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

This plugin is maintained by the mojohaus team, please file your issue at https://github.com/mojohaus/cassandra-maven-plugin
