### ISSUE TITLE
[MNG-6157] org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7286]
**[Michael Vorburger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vorburger)** opened **[MNG-6157](https://issues.apache.org/jira/browse/MNG-6157?redirect=false)** and commented

https://bugs.eclipse.org/bugs/show_bug.cgi?id=496944 (and https://bugs.eclipse.org/bugs/show_bug.cgi?id=510439) report an issue encountered in M2E which shows a org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException as the root caused by, so the underlying problem may be here in Maven core?

May be a concurrency issue - could it be made more multi thread safe?

```
org.apache.maven.plugin.PluginExecutionException: Execution default-testResources of goal org.apache.maven.plugins:maven-resources-plugin:3.0.1:testResources failed: Unable to load the mojo 'testResources' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-resources-plugin:3.0.1'
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'testResources' (or one of its required components) from the plugin 'org.apache.maven.plugins:maven-resources-plugin:3.0.1'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:551)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	... 31 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.plugin.Mojo
  roleHint: org.apache.maven.plugins:maven-resources-plugin:3.0.1:testResources
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:517)
	... 32 more
Caused by: java.util.NoSuchElementException
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:118)
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:1)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 34 more
	pom.xml	/org.opendaylight.netvirt.elanmanager-impl	line 11	Maven Build Problem
```

---

**Affects:** 3.3.9

**Attachments:**
- [image-2018-05-25-11-05-24-862.png](https://issues.apache.org/jira/secure/attachment/12925098/image-2018-05-25-11-05-24-862.png) (_31.98 kB_)
- [image-2018-05-25-14-03-01-554.png](https://issues.apache.org/jira/secure/attachment/12925117/image-2018-05-25-14-03-01-554.png) (_10.31 kB_)
- [image-2018-05-25-14-03-45-626.png](https://issues.apache.org/jira/secure/attachment/12925118/image-2018-05-25-14-03-45-626.png) (_8.88 kB_)
- [IncludeProjectDependenciesComponentConfigurator.java](https://issues.apache.org/jira/secure/attachment/12925120/IncludeProjectDependenciesComponentConfigurator.java) (_3.30 kB_)

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Michael Vorburger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vorburger)** commented

Setting Affects Version to 3.3.9 because that's the one embedded in M2E 1.7.0 (Preferences > Maven > Installations).

**Comment by jira-importer** [comment]
**[Michael Vorburger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vorburger)** commented

Sorry for now having opened multiple bugs, but I'm hitting this almost daily since half a year, so perhaps this will help get it some attention and traction..

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Can you reproduce it when using Maven from commandline?

**Comment by jira-importer** [comment]
**[Michael Vorburger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vorburger)** commented

> Can you reproduce it when using Maven from commandline?

Nope, never; only in M2E. FYI: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496944 just updated with a possible interesting analysis. Feel free to close of course if you're sure that this is certainly not a problem in Maven core.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Root cause is not inside Maven.

**Comment by jira-importer** [comment]
**[Sainath](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sdyapa)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte), I'm able to reproduce this issue from command line.

!image-2018-05-25-11-05-24-862.png!

Here is the complete stack trace:

```

[ERROR] Failed to execute goal com.portware:portware-maven-plugin:1.6:genIniFile (generate-ini) on project pw-configdescriptors: Unable to retrieve component configurator include-project-dependencies for configuration of mojo com.portware:portware-maven-plugin:1.6:genIniFile: java.util.NoSuchElementException
 [ERROR]       role: org.codehaus.plexus.component.configurator.ComponentConfigurator
 [ERROR]   roleHint: include-project-dependencies
 [ERROR] -> [Help 1]
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.portware:portware-maven-plugin:1.6:genIniFile (generate-ini) on project pw-configdescriptors: Unable to retrieve component configurator include-project-dependencies for configuration of mojo com.portware:portware-maven-plugin:1.6:genIniFile
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke (Method.java:498)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
 Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to retrieve component configurator include-project-dependencies for configuration of mojo com.portware:portwaremaven-plugin:1.6:genIniFile
     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields (DefaultMavenPluginManager.java:670)
     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:596)
     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:121)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke (Method.java:498)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
 Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
       role: org.codehaus.plexus.component.configurator.ComponentConfigurator
   roleHint: include-project-dependencies
     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:267)
     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields (DefaultMavenPluginManager.java:624)
     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:596)
     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:121)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke (Method.java:498)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
 Caused by: java.util.NoSuchElementException
     at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next (RealmFilteredBeans.java:118)
     at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next (RealmFilteredBeans.java:1)
     at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next (DefaultPlexusBeans.java:76)
     at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next (DefaultPlexusBeans.java:1)
     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
     at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields (DefaultMavenPluginManager.java:624)
     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:596)
     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:121)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke (Method.java:498)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
 [ERROR]
 [ERROR]
 [ERROR] For more information about the errors and possible solutions, please read the following articles:
 [ERROR] [Help 1] [http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException]

 
```

Could you please help me with this.

Thanks in advance

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

[Sainath](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sdyapa) key issue is this:

```
[ERROR]       role: org.codehaus.plexus.component.configurator.ComponentConfigurator
[ERROR]   roleHint: include-project-dependencies
```

This might be a component that existed in Maven 2, but I'm not aware of its existience in Maven 3. You should ask the maintainers of portware-maven-plugin to update their code, this is not a Maven bug.

**Comment by jira-importer** [comment]
**[Sainath](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sdyapa)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte),

That is the new configurator which I had written so as to use that in my Mojo. Please find the screenshots below.

!image-2018-05-25-14-03-01-554.png!

!image-2018-05-25-14-03-45-626.png!

If there is any thing wrong with the code, Could you please help me in fixing that issue.

Here is the source file for the configurator:

[^IncludeProjectDependenciesComponentConfigurator.java]

**^+Usage :+^**

^`@Mojo`(name = "generateIniFile", threadSafe = true,^ **^configurator = "include-project-dependencies"^**^, requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME)^
^public class ConfigDescriptionGenerateIni extends AbstractMojo {^

  ^public void execute() throws MojoExecutionException, MojoFailureException {^

  ^............^

  ^.............^

  ^}^

^}^

Thanks.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Be sure to add `<extension>true</extension>` to the port-maven-plugin, see https://maven.apache.org/guides/mini/guide-using-extensions.html
If this doesn't help, please switch to the [user mailinglist](https://maven.apache.org/mail-lists.html), because this topic has nothing to do with the original issue anymore.
