### ISSUE TITLE
[MNG-6098] Unable to run Maven test. Getting org.apache.maven.surefire.util.SurefireReflectionException: 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7335]
**[V Ravi Sankar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=v%20ravi%20sankar)** opened **[MNG-6098](https://issues.apache.org/jira/browse/MNG-6098?redirect=false)** and commented

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building MavenSelenium3 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.testng:testng:jar:5.14.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.testng:testng:jar:5.14.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.testng:testng:jar:5.14.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ MavenSelenium3 ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ MavenSelenium3 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ MavenSelenium3 ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ MavenSelenium3 ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ MavenSelenium3 ---
[INFO] Surefire report directory: C:\Users\RaviVinnakota\workspace\MavenSelenium3\target\surefire-reports

---

T E S T S

---

Running TestSuite
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.apache.maven.surefire.testset.TestSetFailedException: Unknown TestNG version 6.9.13.6
at org.apache.maven.surefire.testng.TestNGExecutor.getConfigurator(TestNGExecutor.java:207)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:174)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
... 9 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.218 s
[INFO] Finished at: 2016-10-03T08:11:07+05:30
[INFO] Final Memory: 13M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project MavenSelenium3: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

---

**Affects:** 3.3.9

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

There are a couple of issue with your POM. First, you're using an old version of Surefire (2.12.4), and the version 6.9.13.6 (with 4 digits) isn't correctly recognized, which explains the failure. Upgrade to version 2.19.1 instead of 2.12.4, that will solve your immediate issue.

Second, it seems you have multiple conflicting versions of TestNG in the classpath, as shown by:

```
[WARNING] The POM for org.testng:testng:jar:5.14.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.testng:testng:jar:5.14.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.testng:testng:jar:5.14.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

You should use a single version of TestNG with a `<scope>test</scope>`. With regard to those warnings, the artifacts downloaded by Maven were most likely corrupted (partial transfer, proxy settings...), so you'll need to remove them from your local repository and have Maven redownload them. They should be located by default in `~/.m2/repository/org/testng/testng`.

**Comment by jira-importer** [comment]
**[V Ravi Sankar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=v%20ravi%20sankar)** commented

Thank you very much Guillaume Boué. Upgrading to 2.19.1 worked like magic.. Thanks again. I am trying to do the second one ...need some help here.. I navigated to .m2\repository\org\testng\testng and see tons of testng folders there. Among them 5.14.3, 5.14.4, 5.14.5 are the 3. Should I delete the 3 folders directly? and if so, after that what should I do?

**Comment by jira-importer** [comment]
**[V Ravi Sankar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=v%20ravi%20sankar)** commented

Yes, you can close the ticket as the main problem is resolved.
But, even though I deleted those 3 folders, the warning came back during execution.
[WARNING] The POM for org.testng:testng:jar:5.14.3 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.testng:testng:jar:5.14.4 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] The POM for org.testng:testng:jar:5.14.5 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

Also, it is saying [TestNGContentHandler] [WARN] It is strongly recommended to add "\<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
Should I add that line in the testng suite.xml file? The below is the first line there -

\<?xml version="1.0" encoding="UTF-8"?>
