### ISSUE TITLE
[MNG-6494] Surefire's forked vm crashes when tests produce a lot of output

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7356]
**[David Bilge](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=davidbilge)** opened **[MNG-6494](https://issues.apache.org/jira/browse/MNG-6494?redirect=false)** and commented

This problem occurs since Maven 3.5.3. Version 3.5.2 is fine, 3.5.4 is also affected. I tested on Windows 10 with Oracle Java 8 and AdoptOpenJDK 11, the error occurs on both.

When running a project with tests that produce a lot of output on stdout/stderr, the Maven build reliably fails with the error "The forked VM terminated without properly saying goodbye. VM crash or System.exit called?".

I could reproduce this problem with a small sample project (see attachments). It writes random alpanumeric Strings to System.out for 5 minutes. After 05:34 min the maven build always fails on my machine.

The output is:

```
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:34 min
[INFO] Finished at: 2018-10-16T09:40:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project mvnbug: There are test failures.
[ERROR]
[ERROR] Please refer to C:\_git\mvnbug\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\java\jre\bin\java" -jar C:\Users\DAVID~1.BIL\AppData\Local\Temp\surefire5632911154526112701\surefirebooter1008892796522566308.jar C:\Users\david.bilge\AppData\Local\Temp\surefire5632911154526112701 2018-10-16T09-35-09_901-jvmRun1 surefire6343504960327000994tmp surefire_06251817685909309259tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] com.example.mvnbug.StdOutSpammingTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\java\jre\bin\java" -jar C:\Users\DAVID~1.BIL\AppData\Local\Temp\surefire5632911154526112701\surefirebooter1008892796522566308.jar C:\Users\david.bilge\AppData\Local\Temp\surefire5632911154526112701 2018-10-16T09-35-09_901-jvmRun1 surefire6343504960327000994tmp surefire_06251817685909309259tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] com.example.mvnbug.StdOutSpammingTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I could not find any dumpfiles in the target directory.

---

**Attachments:**
- [mvnbug.zip](https://issues.apache.org/jira/secure/attachment/12944072/mvnbug.zip) (_2.41 kB_)

1 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

After playing around a little bit. This was a surefire issue not Maven itself. I'm using `maven-surefire-plugin:3.0.0-M3`

```
uN
LMFnNOc0K8QTYXFmxTWdMHTxpokvKdW1OYGx60fDWqoJAdg8PYTea7WS9aLLKIGViAYz5cqlVLpJUktZKq6O52lugsXt3YPh0Ya8GxvsSn8ak3Hh7YYcek7lyHLyDob592fInLMkdWnTKEcNlnisjLxn7Af2n
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 304.102 s - in com.example.mvnbug.StdOutSpammingTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:06 min
[INFO] Finished at: 2019-02-23T15:24:15+01:00
[INFO] ------------------------------------------------------------------------

```
