### ISSUE TITLE
[MNG-6481] Allow to compile and test Maven with Java 11

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7385]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** opened **[MNG-6481](https://issues.apache.org/jira/browse/MNG-6481?redirect=false)** and commented

Java 11 is coming closer, let's prepare to use it for the development of Maven.

A minimal requirement to run Maven - still Java 7.

* compile and pass Maven's tests with Java 11
* adjust ITs to run under Java 11

Do we need compile and to pass all tests with Java 9, 10 and 11?

---

**Issue Links:**
- [MNG-6472](https://issues.apache.org/jira/browse/MNG-6472) Mockito cannot mock this class: interface org.eclipse.aether.impl.RepositoryEventDispatcher
 (_**"is blocked by"**_)
- [MNG-6473](https://issues.apache.org/jira/browse/MNG-6473) Update Mockito to 2.21.0
 (_**"is blocked by"**_)
- [MNG-6491](https://issues.apache.org/jira/browse/MNG-6491) Upgrade commons-lang3 to 3.8.1
 (_**"is blocked by"**_)
- [MNG-6515](https://issues.apache.org/jira/browse/MNG-6515) Fix javadoc build errors under Java 8 and 11

- [MNG-6488](https://issues.apache.org/jira/browse/MNG-6488) JDK10 maven surefire commonslang3 SystemUtils.isJavaVersionAtLeast NullPointerException

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

JDK 11 latest RC1 (EA 28) should be available on all nodes see INFRA-17027 so we should check if we can run on 7,8,9,10,11...Yes we should do this cause many people are on 8,9,10 etc.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

I have build that pass compile and tests for 7, 8 and 11 here: https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven/job/remove-commons-lang/ - we only need to remove commons-lang3 dependency or upgrade to an upper version with Java 11 support.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I'd upgrade Commons Lang for 3.6.0. Remove `Validate` would just add a lot of boiterplate code.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

ok, so w have now MNG-6491 ready for review and merge.

About testing - each ITs takes about 30minutes and it can be waste of our server resources.

IMHO it would be better to test with 7, 8, 11 and maybe with each next ea build until next Java LTS version.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

+1 to testing only 7, 8 and 11
9 and 10 are now just in limbo, only 11 LTS is now important

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

With all last fixes, Maven can be compiled with Java 11 and pass all internal tests. Unfortunately, few tests failed in ITs [failed](https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven/job/MNG-6481/) (Linux and Windows the same)
[linux-jdk11] [ERROR] testBad(org.apache.maven.it.MavenITmng5958LifecyclePhaseBinaryCompat)  Time elapsed: 0.202 s  <<< ERROR!
[linux-jdk11] org.apache.maven.it.VerificationException: Text not found in log: [ERROR] Internal error: java.lang.ClassCastException: org.apache.maven.lifecycle.mapping.LifecyclePhase cannot be cast to
[linux-jdk11] 	at org.apache.maven.it.MavenITmng5958LifecyclePhaseBinaryCompat.testBad(MavenITmng5958LifecyclePhaseBinaryCompat.java:42)
[linux-jdk11]
[linux-jdk11] [ERROR] testit(org.apache.maven.it.MavenITmng4877DeployUsingPrivateKeyTest)  Time elapsed: 0.214 s  <<< FAILURE!
[linux-jdk11] junit.framework.AssertionFailedError: expected:\<testuser> but was:\<null>
[linux-jdk11] 	at org.apache.maven.it.MavenITmng4877DeployUsingPrivateKeyTest.testit(MavenITmng4877DeployUsingPrivateKeyTest.java:60)
[linux-jdk11]
[linux-jdk11] [ERROR] testitMNG1957(org.apache.maven.it.MavenITmng1957JdkActivationWithVersionRangeTest)  Time elapsed: 0.131 s  <<< FAILURE!
[linux-jdk11] junit.framework.ComparisonFailure: expected:\<PASSED> but was:\<null>
[linux-jdk11] 	at org.apache.maven.it.MavenITmng1957JdkActivationWithVersionRangeTest.testitMNG1957(MavenITmng1957JdkActivationWithVersionRangeTest.java:64)
[linux-jdk11]

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Only one left

mng4877DeployUsingPrivateKey(it)............................FAILURE (0.7 s)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz) Could you please name your branches based on the issue ...instead of something different...

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Sorry, yes, my branches deleted - that was multiple patches combined for testing with Java 8/11 only code before planned merge to master. Next time I'll submit patches one by one :)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

So the build server is green. I would love to see at least the ITs to run with Java 11. https://github.com/apache/maven/commit/5844c6e5b501dfe8befb0674fb84256ddb36eb21 shows a bit more changes: skipping rat and checkstyle. Can these be fixed as well?
Would be nice if I could demo this Tuesday at Devoxx that Java 11 is validated at the buildserver too.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

No issues with rat and checkstyle - just try to decrease test time, but no significant improvement. I'll remove that part.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Fixed with [f92bd9e98126ca6a9b85ed42aaf753406954f652](https://gitbox.apache.org/repos/asf?p=maven.git;a=commit;h=f92bd9e98126ca6a9b85ed42aaf753406954f652)
