### ISSUE TITLE
[MNG-6400] can not work with a system dependency on a unix / mac / windows project

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7458]
**[Terrien Jean-Yves](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sekaijin)** opened **[MNG-6400](https://issues.apache.org/jira/browse/MNG-6400?redirect=false)** and commented

the sapjco3.jar and sapIdoc3.jar jars can not be renamed.
to work with you have to use an addiction system

however, a unix / windows project can not have an identical absolute path on both systems.

in previous versions of maven you can set properties in .m2 / settings.xml \<sapidoc3> and \<spajco3> and use \<scope> system </ scope>
\<SystemPath> $ {sapidoc3} </ systemPath>

a warnning will be displayed.
on version 3.5.3 it is an error.

But that's not all because even putting the system dependency with an absolute path the jar is not found with the correct name

\<dependency>
\<groupId>de.sap\</groupId>
\<artifactId>sapjco3\</artifactId>
\<version>3.0.0\</version>
\<scope>system\</scope>
\<systemPath>D:/project-ati/libs/libsap/sapjco3.jar\</systemPath>
\</dependency>

JCO3 code

protected boolean registerNativeMethods(Class<?> clazz){
if(!initializedDLL){
try{
JCoRuntime.nativeLibraryPath = loadLibrary("sapjco3");
initializedDLL = true;
}catch(UnsatisfiedLinkError arg2){
JCoRuntime.nativeLibraryPath = "not loaded, caused by " + arg2.toString();
arg2.printStackTrace();
throw arg2;
}
}

return true;
}

java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
at java.lang.Runtime.loadLibrary0(Runtime.java:870)
at java.lang.System.loadLibrary(System.java:1122)
at com.sap.conn.jco.rt.DefaultJCoRuntime.loadLibrary(DefaultJCoRuntime.java:444)

 

The first sap-schema-plugin is a project with sap dependencies defined by an absolute path or property. it compiles well.

the second project use this plugin.
if the plugin project is compiled whith properties
=> error absolute pah is ${sapjco3}
if the plugin project is compiled with absolute path
=> java.lang.UnsatisfiedLinkError: no sapjco3 in java.library.path

 

the same project without change with maven 3.3.9 works perfectly

 

 

---

**Affects:** 3.5.3

**Comment by jira-importer** [comment]
**[John Patrick](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nhoj.patrick)** commented

Could you setup a unix and also a windows profile within either the settings.xml or pom.xml, that activate upon that os.

Then within that os specific profile they define properties for the systemPath value.

Then in the systemPath section it uses the variable defined from the profile.

 

I had to do something similar when trying to get jitwatch working on java 7, 8, 9 and 10, because javafx and specifically due to jfxrt.jar

For reference see the pom https://github.com/AdoptOpenJDK/jitwatch/blob/master/pom.xml

**Comment by jira-importer** [comment]
**[Terrien Jean-Yves](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sekaijin)** commented

No this is the problem :
with profile in .m2/settings.xml I've properties defined for each JCO jar with the value of systemPath depending on OS.

In some project that use JCO, I've a dépencencie with \<SystemPath>${sapidoc3}\</systemPath>

\<SystemPath>${sapijco3}\</systemPath>

In this configuration it work with maven 3.3.9 but not with maven 3.5.3
=> error absolute path is ${sapjco3}

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Terrien Jean-Yves](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sekaijin), the DLL loading is not related to the system path. Please exactly define your issue.
