### ISSUE TITLE
[MNG-6382] JANSI fails frequently with NumberFormatException when building in parallel

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7484]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** opened **[MNG-6382](https://issues.apache.org/jira/browse/MNG-6382?redirect=false)** and commented

After upgrading from 3.3.9 to 3.5.4 my parallel Maven build fail frequently with:

```
java.lang.NumberFormatException: For input string: "34m"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.<init>(Integer.java:1096)
        at org.fusesource.jansi.AnsiPrintStream.filter(AnsiPrintStream.java:129)
        at org.fusesource.jansi.FilterPrintStream.write(FilterPrintStream.java:97)
        at org.fusesource.jansi.FilterPrintStream.write(FilterPrintStream.java:107)
        at org.fusesource.jansi.FilterPrintStream.print(FilterPrintStream.java:161)
        at org.slf4j.impl.MavenSimpleLogger.writeThrowable(MavenSimpleLogger.java:81)
        at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:319)
        at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:295)
        at org.slf4j.impl.SimpleLogger.error(SimpleLogger.java:593)
        at org.apache.maven.cli.CLIReportingUtils.showError(CLIReportingUtils.java:138)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:309)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

This seems to have been [fixed in JANSI master branch](https://github.com/fusesource/jansi/commit/e45e4665538ba9234f5ee5d7b06d78d6a03deda3) but it has not yet been released. There is already a request for a bugfix release, see [issue 114 ("Need 1.17.1 release")](https://github.com/fusesource/jansi/issues/114).

Maven 3.5.4 should therefore upgrade to JANSI 1.17.1.

---

**Affects:** 3.5.3

**Issue Links:**
- [MNG-6419](https://issues.apache.org/jira/browse/MNG-6419) Error if debug log enabled in multithreaded builds
 (_**"is duplicated by"**_)
- [MNG-6372](https://issues.apache.org/jira/browse/MNG-6372) On Windows Maven can output spurious ANSI escapes such as [0m [0m

**Remote Links:**
- [Jansi issue #110
](https://github.com/fusesource/jansi/issues/110)

0 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

PS: Added "Environment" info (it also happens with JDK 9.0.4 and JDK8u162).

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

https://gitbox.apache.org/repos/asf?p=maven.git&a=commit&h=3c3a5901f35783289d502b67bfc520b8e6936ed8
