### ISSUE TITLE
[MNG-6337] NPE on usage of DefaultMavenSettingsBuilder

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7524]
**[Dominic Monroe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dominicm)** opened **[MNG-6337](https://issues.apache.org/jira/browse/MNG-6337?redirect=false)** and commented

Basic usage of the class results in an error. I am not writing java, but I have tried to translate.

```
DefaultMavenSettingsBuilder x = new DefaultMavenSettingsBuilder();
x.buildSettings();
```

This is the stacktrace, sorry that there is frames mixed in:

```
java.lang.NullPointerException
        at org.apache.maven.settings.DefaultMavenSettingsBuilder.build(DefaultMavenSettingsBuilder.java:90)
        at org.apache.maven.settings.DefaultMavenSettingsBuilder.buildSettings(DefaultMavenSettingsBuilder.java:76)
        at org.apache.maven.settings.DefaultMavenSettingsBuilder.buildSettings(DefaultMavenSettingsBuilder.java:56)
        at user$eval3.invokeStatic(NO_SOURCE_FILE:2)
        at user$eval3.invoke(NO_SOURCE_FILE:2)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.eval(Compiler.java:6890)
        at clojure.core$eval.invokeStatic(core.clj:3105)
        at clojure.core$eval.invoke(core.clj:3101)
        at clojure.main$repl$read_eval_print__7408$fn__7411.invoke(main.clj:240)
        at clojure.main$repl$read_eval_print__7408.invoke(main.clj:240)
        at clojure.main$repl$fn__7417.invoke(main.clj:258)
        at clojure.main$repl.invokeStatic(main.clj:258)
        at clojure.main$repl_opt.invokeStatic(main.clj:322)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.Var.invoke(Var.java:375)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
```

---

**Affects:** 3.5.2

**Attachments:**
- [mng-6337-1.patch](https://issues.apache.org/jira/secure/attachment/12905653/mng-6337-1.patch) (_1.38 kB_)

**Comment by jira-importer** [comment]
**[Dominic Monroe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dominicm)** commented

I have attempted a patch to fix this. It works for me locally.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Maven makes use of CDI. If you take a look at [the source](https://maven.apache.org/ref/3.5.2/maven-core/xref/org/apache/maven/settings/DefaultMavenSettingsBuilder.html) you'll see some Plexus Annotations. The `@Requires` annotation is equivalent to `@Inject`.
These classes are not intended to be created without a CDI container.
I tend to close this as "Won't Fix", making all code accessible by constructor alone would come with a lot of unnecessary overhead.

**Comment by jira-importer** [comment]
**[Dominic Monroe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dominicm)** commented

Could you point me at CDI? I'm unfamiliar with it.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

http://maven.apache.org/maven-jsr330.html probably contains most information and and links to other resources.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Hi [Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte), while looking at Maven sources I found that migration to CDI was not finished.
Would this be appropriate to finish migration for other components or is anyone already doing it?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz), a bit off-topic, but I guess you mean switching from plexus to jsr330. I can't find a branch for it. It is a maintenance task, doesn't change the behavior of Maven, just makes it more common to contributors. Just know that not everything can be replaced. IIRC lifecycle mapping uses the same implementation, but different configuration. JSR330 doesn't provide a solution for such cases.
