### ISSUE TITLE
[MNG-6298] 3.5.2: ClassNotFoundException: javax.annotation.security.RolesAllowed

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7561]
**[Ryan Heaton](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stoicflame)** opened **[MNG-6298](https://issues.apache.org/jira/browse/MNG-6298?redirect=false)** and commented

Maven 3.5.2 appears to have introduces some kind of a class loading error, manifesting itself like this:

```
Caused by: java.lang.ClassNotFoundException: javax.annotation.security.RolesAllowed
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 184 more
```

Previous versions of Maven do not manifest this.

To reproduce this:

* Clone [the Enunciate sample project](https://github.com/stoicflame/enunciate-sample).
* Build the project (mvn clean package) with 3.5.0 and note the success.
* Build the project with 3.5.2 and note the failure.

---

**Affects:** 3.5.2

**Issue Links:**
- [MNG-6084](https://issues.apache.org/jira/browse/MNG-6084) Support JSR 250 annotations
 (_**"is broken by"**_)

**Remote Links:**
- [GitHub Pull Request #26
](https://github.com/apache/maven-integration-testing/pull/26)
- [GitHub Pull Request #139
](https://github.com/apache/maven/pull/139)

4 votes, 13 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Confirmed. And the weird thing is that we decided to remove classloader related changes done for 3.5.1 and have a better look at it. Not sure where this one is comming from.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

bisect result

```
a7dddcb87626fec256f1b8ccbe957f94cdf401e4 is the first bad commit
commit a7dddcb87626fec256f1b8ccbe957f94cdf401e4
Author: Dan Tran <dantran@apache.org>
Date:   Sun Sep 11 21:07:39 2016 -0700

[MNG-6084] Support JSR 250 annotations

:040000 040000 edca56f4652fa10dc0881cf9f8220ca08db6b9a0 6dbca280754abd9cc5a3240fc7d8770ce5037fd3 M	maven-core
:040000 040000 581a1beedef2ce71beaa87729e370c7404c0d2fa 258f3592fd311031c5371ca029cde30fe31c35e8 M	maven-embedder
:100644 100644 5e12e36201f2afe4a84f52018adb113fa6543ecd d6f165cd3ff3475c7f8fd5fa42fdeb4fff7f00f4 M	pom.xml
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I think this change makes sense. Let's also minimize the sample project and add it to https://github.com/apache/maven-integration-testing

**Comment by jira-importer** [comment]
**[Bengt Söderberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bengt1982)** commented

Done. Added minimal regression test that fails without the fix. Unsure about versioning so set it to 3.5.3 and onwards for now, range of test might need adjusting depending on version it ends up in.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Hi, can you please squash your commits on the pull request....

**Comment by jira-importer** [comment]
**[Bengt Söderberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bengt1982)** commented

[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise) Not sure what you mean, only one commit per pull request. One for maven and one for maven-integration-testing?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Hi [Bengt1982](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Bengt1982)..Yes that is exactly what I have in mind, cause that in results means we have only a single commit which contains the fix and can in worst cases simply being reverted and makes the history of Maven easier to read...Thanks in advance..

**Comment by jira-importer** [comment]
**[Bengt Söderberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bengt1982)** commented

Hi [Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise), With you so far, however I only have one commit per repo already or am I misunderstanding something?

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Sorry have mistaken that. I have created a branch for it applied the patch and now lets see what the [CI says](https://builds.apache.org/view/M-R/view/Maven/job/maven-wip/job/maven/job/MNG-6298/)..

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

So branches have been created for [Maven Core](https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commitdiff;h=ddd63d9bffdf996c44909b6b0c5f58aa55b16fe0) and [Integration Testing](https://git-wip-us.apache.org/repos/asf?p=maven-integration-testing.git;a=commitdiff;h=55db62ff59715248edf37b636821461d0f1081c4). So lets see if we haven another dev who will second this.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Hi [Bengt1982](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Bengt1982) can you please take a look at the comment of Robet Scholte on the dev list https://www.mail-archive.com/dev@maven.apache.org/msg115802.html

**Comment by jira-importer** [comment]
**[Bengt Söderberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bengt1982)** commented

Hi [Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise), updated the commit with the requested changes. My first commit to maven, thanks for your patience :)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Tack [Bengt1982](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Bengt1982). I appreciate you support for the Maven project. I have updated the branch accordingly. Lets wait for CI result. BTW. Small hint. Usually you should mention the issue in the commit message like:

```
[MXXX-XX] Subject
 o more details
```

That makes it easier to associate the pr/commit with the appropriate issue entry...
Kind regards
Karl Heinz Marbaise

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Done in [6285bb96c5104a9eabd4e35131aec917b4f9e048](https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commitdiff;h=6285bb96c5104a9eabd4e35131aec917b4f9e048)
