### ISSUE TITLE
[MNG-6286] ArrayIndexOutOfBoundsException: MXParser.java:2502

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7579]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hohwille)** opened **[MNG-6286](https://issues.apache.org/jira/browse/MNG-6286?redirect=false)** and commented

I found a regression bug with maven 3.5.0. The error I get is:

```
[ERROR] 24777
java.lang.ArrayIndexOutOfBoundsException: 24777
        at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2502)
        at org.codehaus.plexus.util.xml.pull.MXParser.parseEpilog(MXParser.java:1604)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1434)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1131)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:3856)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:595)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:109)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:82)
        at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:81)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:535)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1097)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:321)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:199)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:544)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:528)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:418)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:372)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:360)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:263)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:325)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:169)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

It occurs when I build this project:
https://github.com/m-m-m/code/
The error does not occur when I build with an older maven version (verified with 3.3.9 and 3.2.5).
Might be related to MNG-6204 but I do not use `<?m2e` in my POMs. So the result is that maven 3.5.0 can not build projects using maven 3.5.0.

```
[INFO] Reactor Summary:
[INFO]
[INFO] mmm-code-parent .................................... SUCCESS [  0.936 s]
[INFO] mmm-code-bom ....................................... SUCCESS [  0.062 s]
[INFO] mmm-code-modules ................................... SUCCESS [  0.317 s]
[INFO] mmm-code-api ....................................... SUCCESS [  1.840 s]
[INFO] mmm-code-base ...................................... SUCCESS [  0.239 s]
[INFO] mmm-code-java ...................................... SUCCESS [  0.047 s]
[INFO] mmm-code-java-parser ............................... SUCCESS [  8.694 s]
[INFO] mmm-code-java-maven ................................ FAILURE [  0.015 s]
[INFO] mmm-code-java-impl ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

---

**Affects:** 3.5.0

**Issue Links:**
- [MNG-6280](https://issues.apache.org/jira/browse/MNG-6280) ArrayIndexOutOfBoundsException caused by pom.xml with process instructions
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hohwille)** commented

same error for this build hash:
https://github.com/mojohaus/flatten-maven-plugin/commit/8bdbb7b25750f3928ba36f2a1facaa3cd6405c8b

**Comment by jira-importer** [comment]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hohwille)** commented

maven 3.5.0 is IMHO broken.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

This one should be fixed with MNG-6280

**Comment by jira-importer** [comment]
**[Jörg Hohwiller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hohwille)** commented

Retested with 3.5.2 - works like a charm. Thanks so much. Awesome. Colors in console log!
