### ISSUE TITLE
[MNG-5845] when in maven mojo, ClassNotFoundException slf4j-api `MessageFormatter` class

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7596]
**[feilong](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=feilong)** opened **[MNG-5845](https://issues.apache.org/jira/browse/MNG-5845?redirect=false)** and commented

**my code is**

```
@Mojo(name = "hello",requiresProject = false)
public class HelloWorldMojo extends AbstractMojo{

    @Override
    public void execute() throws MojoExecutionException,MojoFailureException{
        String[] argStrings = { "Hello world" };
        FormattingTuple formattingTuple = MessageFormatter.arrayFormat("{}", argStrings);
        getLog().info(formattingTuple.getMessage());
    }
}
```

**when i run my plugins , show me result:**

```
Caused by: java.lang.NoClassDefFoundError: org/slf4j/helpers/MessageFormatter
	at com.feilong.core.log.Slf4jUtil.formatMessage(Slf4jUtil.java:77)
	at com.feilong.project.train.mojo.BaseFlowMojo.getFolderPath(BaseFlowMojo.java:72)
	at com.feilong.project.train.mojo.InvitationMojo.handleExecute(InvitationMojo.java:89)
	at com.feilong.project.train.mojo.BaseFlowMojo.execute(BaseFlowMojo.java:111)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.helpers.MessageFormatter
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 26 more
```

**And from the log (run with -X), i see that :**

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T19:57:37+08:00)
Maven home: D:\FeiLong Soft\Essential\Development\apache-maven-3.3.3\bin\..
Java version: 1.8.0_11, vendor: Oracle Corporation
Java home: D:\Program Files\Java\jdk1.8.0_11\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 7", version: "6.1", arch: "x86", family: "dos"
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: javax.enterprise.inject.* < plexus.core
[DEBUG]   Imported: javax.enterprise.util.* < plexus.core
[DEBUG]   Imported: javax.inject.* < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution.scope < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.* < plexus.core
[DEBUG]   Imported: org.eclipse.aether.artifact < plexus.core
[DEBUG]   Imported: org.eclipse.aether.collection < plexus.core
[DEBUG]   Imported: org.eclipse.aether.deployment < plexus.core
[DEBUG]   Imported: org.eclipse.aether.graph < plexus.core
[DEBUG]   Imported: org.eclipse.aether.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.installation < plexus.core
[DEBUG]   Imported: org.eclipse.aether.internal.impl < plexus.core
[DEBUG]   Imported: org.eclipse.aether.metadata < plexus.core
[DEBUG]   Imported: org.eclipse.aether.repository < plexus.core
[DEBUG]   Imported: org.eclipse.aether.resolution < plexus.core
[DEBUG]   Imported: org.eclipse.aether.spi < plexus.core
[DEBUG]   Imported: org.eclipse.aether.transfer < plexus.core
[DEBUG]   Imported: org.eclipse.aether.version < plexus.core
[DEBUG]   Imported: org.slf4j.* < plexus.core
[DEBUG]   Imported: org.slf4j.spi.* < plexus.core
[DEBUG] Populating class realm maven.api
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from D:\FeiLong Soft\Essential\Development\apache-maven-3.3.3\bin\..\conf\settings.xml
[DEBUG] Reading user settings from C:\Users\feilong\.m2\settings.xml
[DEBUG] Reading global toolchains from D:\FeiLong Soft\Essential\Development\apache-maven-3.3.3\bin\..\conf\toolchains.xml
[DEBUG] Reading user toolchains from C:\Users\feilong\.m2\toolchains.xml
[DEBUG] Using local repository at D:\FeiLong Soft\Essential\Development\repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10.0 for D:\FeiLong Soft\Essential\Development\repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project org.apache.maven:standalone-pom:pom:1: (none)
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[plexus.core, parent: null]
[DEBUG] Skipped remote request for com.feilong.maven.plugins:feilong-training-plugin:1.2.1-SNAPSHOT/maven-metadata.xml, locally installed metadata up-to-date.
[DEBUG] Skipped remote request for com.feilong.maven.plugins:feilong-training-plugin:1.2.1-SNAPSHOT/maven-metadata.xml, locally installed metadata up-to-date.
[DEBUG] Skipped remote request for com.feilong.platform:parent:1.2.1-SNAPSHOT/maven-metadata.xml, locally installed metadata up-to-date.
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: org.apache.maven:standalone-pom:pom:1
[DEBUG] Tasks:   [com.feilong.maven.plugins:feilong-training-plugin:1.2.1-SNAPSHOT:invitation]
[DEBUG] Style:   Aggregating
[DEBUG] =======================================================================
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       org.apache.maven:standalone-pom:1
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [compile+runtime]
[DEBUG] Repositories (dependencies): [central (http://search.maven.org/remotecontent?filepath=, default, releases+snapshots)]
[DEBUG] Repositories (plugins)     : [maven-plugin (http://search.maven.org/remotecontent?filepath=, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          com.feilong.maven.plugins:feilong-training-plugin:1.2.1-SNAPSHOT:invitation (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration/>
[DEBUG] =======================================================================
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=0, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=0, DefaultDependencyCollector.collectTime=0, DefaultDependencyCollector.transformTime=5}
[DEBUG] org.apache.maven:standalone-pom:pom:1
[INFO] 
[INFO] --- feilong-training-plugin:1.2.1-SNAPSHOT:invitation (default-cli) @ standalone-pom ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=2, ConflictMarker.markTime=0, ConflictMarker.nodeCount=176, ConflictIdSorter.graphTime=1, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=84, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=9, ConflictResolver.conflictItemCount=163, DefaultDependencyCollector.collectTime=418, DefaultDependencyCollector.transformTime=12}
[DEBUG] com.feilong.maven.plugins:feilong-training-plugin:jar:1.2.1-SNAPSHOT:
[DEBUG]    org.apache.maven:maven-core:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.3.3:compile
[DEBUG]          org.apache.maven:maven-builder-support:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.3.3:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.3.3:compile
[DEBUG]          com.google.guava:guava:jar:18.0:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.3.3:compile
[DEBUG]          org.eclipse.aether:aether-spi:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-impl:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.aether:aether-util:jar:1.0.2.v20150114:compile
[DEBUG]       org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0:compile
[DEBUG]          javax.enterprise:cdi-api:jar:1.0:compile
[DEBUG]             javax.annotation:jsr250-api:jar:1.0:compile
[DEBUG]          org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0:compile
[DEBUG]       org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5:compile
[DEBUG]          javax.inject:javax.inject:jar:1:compile
[DEBUG]          aopalliance:aopalliance:jar:1.0:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.4:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.3.3:compile
[DEBUG]    org.codehaus.plexus:plexus-container-default:jar:1.6:compile
[DEBUG]       org.apache.xbean:xbean-reflect:jar:3.7:compile
[DEBUG]       com.google.collections:google-collections:jar:1.0:compile
[DEBUG]    org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-6:compile
[DEBUG]       org.codehaus.plexus:plexus-component-api:jar:1.0-alpha-16:compile
[DEBUG]          junit:junit:jar:4.12:test
[DEBUG]             org.hamcrest:hamcrest-core:jar:1.3:test
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
[DEBUG]    com.feilong.project:feilong-train:jar:1.2.1-SNAPSHOT:compile
[DEBUG]       com.feilong.office:feilong-office-excel:jar:1.2.1-SNAPSHOT:compile
[DEBUG]          com.feilong.platform:feilong-servlet:jar:1.2.1-SNAPSHOT:compile
[DEBUG]             javax.servlet:jstl:jar:1.2:compile
[DEBUG]          org.apache.poi:poi:jar:3.11:compile
[DEBUG]             commons-codec:commons-codec:jar:1.9:compile
[DEBUG]          org.apache.poi:poi-ooxml:jar:3.11:compile
[DEBUG]          org.apache.poi:poi-ooxml-schemas:jar:3.11:compile
[DEBUG]             org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[DEBUG]                stax:stax-api:jar:1.0.1:compile
[DEBUG]          loxia2:loxia2-support:jar:2.5.2:compile
[DEBUG]             org.aspectj:aspectjweaver:jar:1.6.8:compile
[DEBUG]             ognl:ognl:jar:2.7.3:compile
[DEBUG]                jboss:javassist:jar:3.7.ga:compile
[DEBUG]          commons-digester:commons-digester:jar:2.1:compile
[DEBUG]       com.feilong.chart:feilong-chart-core:jar:1.2.1-SNAPSHOT:compile
[DEBUG]       com.feilong.chart:feilong-chart-amcharts:jar:1.2.1-SNAPSHOT:compile
[DEBUG]       com.feilong.platform.tools:feilong-tools-ant:jar:1.2.1-SNAPSHOT:compile
[DEBUG]          org.apache.ant:ant:jar:1.9.4:compile
[DEBUG]             org.apache.ant:ant-launcher:jar:1.9.4:compile
[DEBUG]       com.feilong.platform.tools:feilong-tools-mail:jar:1.2.1-SNAPSHOT:compile
[DEBUG]          com.sun.mail:javax.mail:jar:1.5.2:compile
[DEBUG]             javax.activation:activation:jar:1.1:compile
[DEBUG]       com.feilong.platform.tools:feilong-tools-velocity:jar:1.2.1-SNAPSHOT:compile
[DEBUG]          org.apache.velocity:velocity:jar:1.7:compile
[DEBUG]          org.apache.velocity:velocity-tools:jar:2.0:compile
[DEBUG]             commons-chain:commons-chain:jar:1.1:compile
[DEBUG]             commons-validator:commons-validator:jar:1.3.1:compile
[DEBUG]             dom4j:dom4j:jar:1.6.1:compile
[DEBUG]                xml-apis:xml-apis:jar:1.4.01:compile
[DEBUG]             oro:oro:jar:2.0.8:compile
[DEBUG]       com.feilong.platform:feilong-core:jar:1.2.1-SNAPSHOT:compile
[DEBUG]          commons-lang:commons-lang:jar:2.6:compile
[DEBUG]          org.apache.commons:commons-lang3:jar:3.4:compile
[DEBUG]          commons-beanutils:commons-beanutils:jar:1.9.2:compile
[DEBUG]          commons-logging:commons-logging:jar:1.2:compile
[DEBUG]          commons-collections:commons-collections:jar:3.2.1:compile
[DEBUG]          commons-io:commons-io:jar:2.4:compile
[DEBUG]          net.sf.json-lib:json-lib:jar:jdk15:2.4:compile
[DEBUG]             net.sf.ezmorph:ezmorph:jar:1.0.6:compile
[DEBUG]    com.feilong.data:feilong-data-redis:jar:1.2.1-SNAPSHOT:compile
[DEBUG]       redis.clients:jedis:jar:2.6.2:compile
[DEBUG]          org.apache.commons:commons-pool2:jar:2.0:compile
[DEBUG]    com.feilong.platform.tools:feilong-tools-jsoup:jar:1.2.1-SNAPSHOT:compile
[DEBUG]       org.jsoup:jsoup:jar:1.7.3:compile
[DEBUG]    ch.qos.logback:logback-core:jar:1.1.3:compile
[DEBUG]    ch.qos.logback:logback-classic:jar:1.1.3:compile
 
[DEBUG]    org.slf4j:slf4j-api:jar:1.7.12:compile

[DEBUG] Created new class realm plugin>com.feilong.maven.plugins:feilong-training-plugin:1.2.1-SNAPSHOT
[DEBUG] Importing foreign packages into class realm plugin>com.feilong.maven.plugins:feilong-training-plugin:1.2.1-SNAPSHOT
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>com.feilong.maven.plugins:feilong-training-plugin:1.2.1-SNAPSHOT
[DEBUG]   Included: com.feilong.maven.plugins:feilong-training-plugin:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: org.apache.maven:maven-builder-support:jar:3.3.3
[DEBUG]   Included: com.google.guava:guava:jar:18.0
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.0.2.v20150114
[DEBUG]   Included: javax.enterprise:cdi-api:jar:1.0
[DEBUG]   Included: javax.annotation:jsr250-api:jar:1.0
[DEBUG]   Included: org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.5
[DEBUG]   Included: aopalliance:aopalliance:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.21
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.4
[DEBUG]   Included: org.apache.xbean:xbean-reflect:jar:3.7
[DEBUG]   Included: com.google.collections:google-collections:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-6
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.22
[DEBUG]   Included: com.feilong.project:feilong-train:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: com.feilong.office:feilong-office-excel:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: com.feilong.platform:feilong-servlet:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: javax.servlet:jstl:jar:1.2
[DEBUG]   Included: org.apache.poi:poi:jar:3.11
[DEBUG]   Included: commons-codec:commons-codec:jar:1.9
[DEBUG]   Included: org.apache.poi:poi-ooxml:jar:3.11
[DEBUG]   Included: org.apache.poi:poi-ooxml-schemas:jar:3.11
[DEBUG]   Included: org.apache.xmlbeans:xmlbeans:jar:2.6.0
[DEBUG]   Included: stax:stax-api:jar:1.0.1
[DEBUG]   Included: loxia2:loxia2-support:jar:2.5.2
[DEBUG]   Included: org.aspectj:aspectjweaver:jar:1.6.8
[DEBUG]   Included: ognl:ognl:jar:2.7.3
[DEBUG]   Included: jboss:javassist:jar:3.7.ga
[DEBUG]   Included: commons-digester:commons-digester:jar:2.1
[DEBUG]   Included: com.feilong.chart:feilong-chart-core:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: com.feilong.chart:feilong-chart-amcharts:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: com.feilong.platform.tools:feilong-tools-ant:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: org.apache.ant:ant:jar:1.9.4
[DEBUG]   Included: org.apache.ant:ant-launcher:jar:1.9.4
[DEBUG]   Included: com.feilong.platform.tools:feilong-tools-mail:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: com.sun.mail:javax.mail:jar:1.5.2
[DEBUG]   Included: javax.activation:activation:jar:1.1
[DEBUG]   Included: com.feilong.platform.tools:feilong-tools-velocity:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: org.apache.velocity:velocity:jar:1.7
[DEBUG]   Included: org.apache.velocity:velocity-tools:jar:2.0
[DEBUG]   Included: commons-chain:commons-chain:jar:1.1
[DEBUG]   Included: commons-validator:commons-validator:jar:1.3.1
[DEBUG]   Included: dom4j:dom4j:jar:1.6.1
[DEBUG]   Included: xml-apis:xml-apis:jar:1.4.01
[DEBUG]   Included: oro:oro:jar:2.0.8
[DEBUG]   Included: com.feilong.platform:feilong-core:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: commons-lang:commons-lang:jar:2.6
[DEBUG]   Included: org.apache.commons:commons-lang3:jar:3.4
[DEBUG]   Included: commons-beanutils:commons-beanutils:jar:1.9.2
[DEBUG]   Included: commons-logging:commons-logging:jar:1.2
[DEBUG]   Included: commons-collections:commons-collections:jar:3.2.1
[DEBUG]   Included: commons-io:commons-io:jar:2.4
[DEBUG]   Included: net.sf.json-lib:json-lib:jar:jdk15:2.4
[DEBUG]   Included: net.sf.ezmorph:ezmorph:jar:1.0.6
[DEBUG]   Included: com.feilong.data:feilong-data-redis:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: redis.clients:jedis:jar:2.6.2
[DEBUG]   Included: org.apache.commons:commons-pool2:jar:2.0
[DEBUG]   Included: com.feilong.platform.tools:feilong-tools-jsoup:jar:1.2.1-SNAPSHOT
[DEBUG]   Included: org.jsoup:jsoup:jar:1.7.3
[DEBUG]   Included: ch.qos.logback:logback-core:jar:1.1.3
[DEBUG]   Included: ch.qos.logback:logback-classic:jar:1.1.3 
```

\*and i also see that,  in  maven  "META-INF/maven/extension.xml" file ,
here is slf4j  exportedArtifact config:*

```
<exportedArtifact>org.slf4j:slf4j-api</exportedArtifact>
```

**and in org.apache.maven.classrealm.DefaultClassRealmManager.isProvidedArtifact(Artifact)   line 167 , has code validator**

```
if ( artifacts != null )
        {
            for ( Artifact artifact : artifacts )
            {
                if ( !isProvidedArtifact( artifact ) )
                {
                    artifactIds.add( getId( artifact ) );
                    if ( artifact.getFile() != null )
                    {
                        constituents.add( new ArtifactClassRealmConstituent( artifact ) );
                    }
                }
            }
        }

```

......

**why in my plugins, can not use MessageFormatter?**

---

**Affects:** 3.3.3

**Issue Links:**
- [MNG-5787](https://issues.apache.org/jira/browse/MNG-5787) Moving from Maven 3.0.5 to 3.3.3 breaks plugins with some dependencies on the class path
 (_**"duplicates"**_)
- [MNG-5842](https://issues.apache.org/jira/browse/MNG-5842) java.lang.NoClassDefFoundError: org/slf4j/helpers/MessageFormatter with jetty plugin
 (_**"duplicates"**_)

0 votes, 5 watchers

**Comment by jira-importer** [comment]
**[S L](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=thesnoozer)** commented

This issue sounds to be a similar problem: https://issues.apache.org/jira/browse/MNG-5787
The main problems seems to be a class loading issue wit maven 3.3.3.

Can you try to run your project with 3.3.2 and see if it still breaks?

**Comment by jira-importer** [comment]
**[feilong](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=feilong)** commented

maybe similar with https://issues.apache.org/jira/browse/MNG-5842

**Comment by jira-importer** [comment]
**[Arnaud Heritier](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aheritier)** commented

Reported as MNG-5842, and MNG-5787. The problem comes from the fact that we are exporting the slf4j-api artefact, thus plugins cannot use their own version but we forgot to export the content of the package org/slf4j/helpers. Thus the `java.lang.ClassNotFoundException: org.slf4j.helpers.MessageFormatter`
