### ISSUE TITLE
[MNG-5805] Custom packaging types: configuring DefaultLifecycleMapping mojo executions

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7625]
**[Anton Tanasenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=atanasenko)** opened **[MNG-5805](https://issues.apache.org/jira/browse/MNG-5805?redirect=false)** and commented

Currently, DefaultLifecycleMapping does not support mapping phases to goals with a custom configuration (see maven-core/src/main/resources/META-INF/plexus/default-bindings.xml). It is impossible to bind, say, an assembly plugin to 'package' phase within a custom packaging type, since assembly plugin requires a meaningful configuration to be set.

At my job, we have a number of poms, each serving a purpose of defining a lifecycle for a particular type of project (there's one for jar, a couple for wars and several more for other types of deployable artifacts).

Now that I somewhat understand maven's lifecycle, It seems natural to convert such poms to custom packaging types, leaving only a single parent with global config and pluginManagement. But it is currently impossible, since we are using mostly standard plugins (only occasional dedicated ones) to configure projects' lifecycles.

I did some digging around and put together a relatively straightforward change to maven-core: https://github.com/apache/maven/compare/master...atanasenko:mng-5805-lifecycle-mojo-config?w=1

It both introduces support for specifying configuration and dependencies for mojo executions:

```xml
<install>
  <mojos>
    <mojo>
      <goal>org.apache.maven.plugins:maven-install-plugin:2.4:install</goal>
      <configuration>...</configuration>
      <dependencies>...</dependencies>
    </mojo>
    <mojo>
      ...
    </mojo>
  </mojos>
</install>
```

as well as retains support for existing mapping syntax:

```xml
<install>org.apache.maven.plugins:maven-install-plugin:2.4:install, ...</install>
```

I will put together some its (as well as make sure that existing are running ok) and create a pull request for both. Also, there are a couple of changes that break API in org/apache/maven/lifecycle/Lifecycle.java and org/apache/maven/lifecycle/mapping/Lifecycle.java. How critical is it to mantain compatibility in those two?

ITS: https://github.com/apache/maven-integration-testing/compare/master...atanasenko:mng-5805-lifecycle-mojo-config?w=1

---

**Issue Links:**
- [MNG-5958](https://issues.apache.org/jira/browse/MNG-5958) java.lang.String cannot be cast to org.apache.maven.lifecycle.mapping.LifecyclePhase

0 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Anton Tanasenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=atanasenko)** commented

It is currently impossible to add this support out of the box due to missing feature in sisu-plexus.
I submitted a bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=464959

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Applied on d8ae13fd7b6be8a238a2b74f2b494668cd967c30

**Comment by jira-importer** [comment]
**[Mirko Friedenhagen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mfriedenhagen)** commented

Unfortunately this breaks enforcers' requirePluginVersions rule as the later one relies on getting the phase as a String.

```
Caused by: java.lang.ClassCastException: org.apache.maven.lifecycle.mapping.LifecyclePhase cannot be cast to java.lang.String
    at org.apache.maven.plugins.enforcer.RequirePluginVersions.getAllPlugins(RequirePluginVersions.java:739)
    at org.apache.maven.plugins.enforcer.RequirePluginVersions.getBoundPlugins(RequirePluginVersions.java:606)
    at org.apache.maven.plugins.enforcer.RequirePluginVersions.execute(RequirePluginVersions.java:232)
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:150)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
```

**Comment by jira-importer** [comment]
**[Anton Tanasenko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=atanasenko)** commented

In case if anyone wants to take a glance, there's a combined diff of both the original and the new commit together at https://github.com/atanasenko/maven/compare/mng5805_followup%5E%5E...mng5805_followup

**Comment by jira-importer** [comment]
**[Stuart McCulloch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mcculls)** commented

note the MNG-5805 style of lifecycle configuration should go inside:

```xml
<configuration>
  <lifecycles>
    <lifecycle>
      <id>foo</id>
      <lifecyclePhases>		<!-- use this for MNG-5805 advanced lifecycle mappings -->
```

rather than:

```xml
<configuration>
  <lifecycles>
    <lifecycle>
      <id>foo</id>
      <phases>			<!-- use this for legacy (deprecated) lifecycle mappings -->
```

There was a bug in Maven 3.3.9 where it also accepted MNG-5805 style configuration using `<phases>` but this broke backwards compatibility with plugins like flexmojos (see https://issues.apache.org/jira/browse/MNG-5958 for more details)

If you stick with `<lifecyclePhases>` then your MNG-5805 lifecycle configuration will work with 3.3.9 and 3.4.0+

An example of the new lifecycle configuration can be seen in https://github.com/apache/maven-integration-testing/blob/master/core-it-support/core-it-plugins/mng5805-extension/src/main/resources/META-INF/plexus/components.xml
