### ISSUE TITLE
[MNG-6226] mvn dependency:get error - Premature end of Content-Length delimited message body (expected: 56473600; received: 6843

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7648]
**[Sahil Amar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sahilamar)** opened **[MNG-6226](https://issues.apache.org/jira/browse/MNG-6226?redirect=false)** and commented

Hi Team,

I am trying to use the maven dependency get plugin to get the artifact which is a tar file from our central repo.

Here is the command:

```xml
mvn dependency:get -DgroupId=com.sample -DartifactId=sample-project -Dversion=1.0.1-SNAPSHOT -Dtransitive=false -Dpackaging=tar 
```

It gives me the below error:

```xml
[ERROR] : Premature end of Content-Length delimited message body (expected: 56473600; received: 6843
[ERROR] -> [Help 1]
```

And also when I try it with the debug(-X) mode, this is the error I get:

```xml
Caused by: org.apache.maven.wagon.providers.http.httpclient.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 56473600; received: 6835
        at org.apache.maven.wagon.providers.http.httpclient.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
        at org.apache.maven.wagon.providers.http.httpclient.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at org.apache.maven.wagon.AbstractWagon.transfer(AbstractWagon.java:572)
        at org.apache.maven.wagon.AbstractWagon.getTransfer(AbstractWagon.java:372)
        ... 43 more
```

The above command when I try on windows it works. But issue is when I run it on UNIX.

But when I try to get the jar using the below command(with -Dpackaging=jar) on both Linux and windows, it works:

```xml
mvn dependency:get -DgroupId=com.sample -DartifactId=sample-project -Dversion=1.0.1-SNAPSHOT -Dtransitive=false -Dpackaging=jar
```

Also the same works for a war.

Please help.

Thanks and Regards,
Sahil Amar

---

**Affects:** 3.5.0

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Provide a full dump with `curl --verbose $URL` of the target in question. This seems to be an issue with your internal setup.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No further information provided.
