### ISSUE TITLE
[MNG-6072] Cannot build archetypes on Windows

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7676]
**[Thomas Diesler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tdiesler)** opened **[MNG-6072](https://issues.apache.org/jira/browse/MNG-6072?redirect=false)** and commented

```
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T21:10:27+01:00)
Maven home: C:\Program Files\Java\apache-maven-3.3.1
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_101\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows server 2012 r2", version: "6.3", arch: "amd64", family: "dos"

[INFO] --- maven-archetype-plugin:2.2:integration-test (default-integration-test) @ wildfly-camel-archetype-cdi ---
[INFO] Processing Archetype IT project: test-archetype-cdi
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: wildfly-camel-archetype-cdi:4.2.0-SNAPSHOT
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: artifactId, Value: wildfly-camel-archetype-cdi-test
[INFO] Parameter: version, Value: 1.0
[INFO] Parameter: package, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: packageInPathFormat, Value: org/wildfly/camel/archetype/test
[INFO] Parameter: version-wildfly-arquillian, Value: 1.0.2.Final
[INFO] Parameter: version-jboss-arquillian, Value: 1.1.10.Final
[INFO] Parameter: version-wildfly, Value: 10.0.0.Final
[INFO] Parameter: groupId, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: version-junit, Value: 4.11
[INFO] Parameter: version, Value: 1.0
[INFO] Parameter: version-maven-war-plugin, Value: 2.5
[INFO] Parameter: version-apache-camel, Value: 2.17.2
[INFO] Parameter: package, Value: org.wildfly.camel.archetype.test
[INFO] Parameter: version-wildfly-maven-plugin, Value: 1.1.0.Alpha7
[INFO] Parameter: version-maven-compiler-plugin, Value: 3.1
[INFO] Parameter: artifactId, Value: wildfly-camel-archetype-cdi-test
[INFO] Parameter: version-wildfly-camel, Value: 4.2.0-SNAPSHOT
[INFO] Parameter: version-maven-surefire-plugin, Value: 2.18.1
[INFO] project created from Archetype in dir: C:\Users\Administrator\git\wildfly-camel\archetypes\archetype-cdi\target\t
est-classes\projects\test-archetype-cdi\project\wildfly-camel-archetype-cdi-test
[INFO] Invoking post-archetype-generation goals: verify -Parq-managed -Djboss.home=C:\\Users\\Administrator\\git\\wildfl
y-camel\\archetypes\\archetype-cdi\\target\\wildfly-10.0.0.Final -Dserver.config=standalone.xml

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.142 s
[INFO] Finished at: 2016-07-29T11:30:52+02:00
[INFO] Final Memory: 65M/762M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration
-test) on project wildfly-camel-archetype-cdi:
[ERROR] Archetype IT 'test-archetype-cdi' failed: Cannot run additions goals.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-
plugin:2.2:integration-test (default-integration-test) on project wildfly-camel-archetype-cdi:
Archetype IT 'test-archetype-cdi' failed: Cannot run additions goals.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException:
Archetype IT 'test-archetype-cdi' failed: Cannot run additions goals.
        at org.apache.maven.archetype.mojos.IntegrationTestMojo.execute(IntegrationTestMojo.java:268)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
PS C:\Users\Administrator\git\wildfly-camel\archetypes\archetype-cdi>
```

This still works with maven-3.2.5, but breaks from maven-3.3.1 onward

To reproduce

```
> git clone -b 4.1.0 https://github.com/wildfly-extras/wildfly-camel.git
> cd wildfly-camel
> mvn clean install -pl .\archetypes\archetype-cdi -am -Dts.all
```

---

**Affects:** 3.3.1, 3.3.3, 3.3.9

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

The original issue has been closed already. I cannot reproduce this neither with the tag and master (63a14183fb7789888622587b84f8cd5e1c00faf0). All I get with

```
Apache Maven 3.4.0-SNAPSHOT (8a1b6359f31178ce804018cfb524e72f1178028a; 2016-12-17T20:46:55+01:00)
Maven home: D:\Entwicklung\Programme\apache-maven-3.4.0-SNAPSHOT
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_112\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

is

```
[INFO] --- wildfly-feature-pack-build-maven-plugin:1.1.6.Final:build (feature-pack-build) @ wildfly-camel-feature-pack ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Wildfly Camel ...................................... SUCCESS [  2.031 s]
[INFO] Wildfly Camel :: Config ............................ SUCCESS [  3.042 s]
[INFO] WildFly Camel :: CXF Undertow ...................... SUCCESS [  4.421 s]
[INFO] Wildfly Camel :: Subsystem ......................... SUCCESS [  0.027 s]
[INFO] Wildfly Camel :: Subsystem :: Core ................. SUCCESS [  2.187 s]
[INFO] Wildfly Camel :: Subsystem :: CDI .................. SUCCESS [  2.740 s]
[INFO] Wildfly Camel :: Subsystem :: Security ............. SUCCESS [  0.926 s]
[INFO] Wildfly Camel :: Subsystem :: Undertow ............. SUCCESS [  1.344 s]
[INFO] Wildfly Camel :: Feature Pack ...................... FAILURE [ 19.737 s]
[INFO] Wildfly Camel :: Archetypes ........................ SKIPPED
[INFO] Wildfly Camel :: Archetypes :: CDI ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.231 s
[INFO] Finished at: 2016-12-18T00:21:26+01:00
[INFO] Final Memory: 222M/1548M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.build:wildfly-feature-pack-build-maven-plugin:1.1.6.Final:build (feature-pack-build) on project wildfly-camel-feature-pack: Execution feature-pack-build of goal org.wildfly.build:wildfly-feature-pack-build-maven-plugin:1.1.6.Final:build failed: java.lang.RuntimeException: Some errors were encountered creating the feature pack
[ERROR] Missing module ModuleIdentifier{name='junit', slot='5.5'}. Module was required by [ModuleIdentifier{name='org.apache.lucene', slot='5.5'}]
[ERROR] Missing module ModuleIdentifier{name='ch.qos.logback', slot='main'}. Module was required by [ModuleIdentifier{name='io.netty', slot='4.1'}, ModuleIdentifier{name='org.quartz', slot='main'}, ModuleIdentifier{name='org.springframework.security', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='org.osgi.compendium', slot='main'}. Module was required by [ModuleIdentifier{name='org.fusesource.mqtt', slot='main'}, ModuleIdentifier{name='org.fusesource.hawtdispatch', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='org.apache.aries.blueprint', slot='main'}. Module was required by [ModuleIdentifier{name='org.apache.cxf.ext', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='io.netty.parts', slot='main'}. Module was required by [ModuleIdentifier{name='io.netty', slot='4.1'}, ModuleIdentifier{name='org.apache.camel.component.mongodb', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='jline', slot='main'}. Module was required by [ModuleIdentifier{name='org.apache.camel.script.groovy', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='org.joda.convert', slot='main'}. Module was required by [ModuleIdentifier{name='org.apache.camel.component.swagger', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='junit', slot='main'}. Module was required by [ModuleIdentifier{name='org.apache.camel.component.jacksonxml', slot='main'}, ModuleIdentifier{name='org.apache.kafka.clients', slot='main'}, ModuleIdentifier{name='org.fusesource.hawtdispatch', slot='main'}, ModuleIdentifier{name='org.apache.ws.commons.axiom.axiom-api', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jdbc', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.atom', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.salesforce', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.xmlsecurity', slot='main'}, ModuleIdentifier{name='org.apache.kafka', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.flatpack', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.soap', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.barcode', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.xmlbeans', slot='main'}, ModuleIdentifier{name='org.apache.abdera.core', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.ejb', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.lucene', slot='main'}, ModuleIdentifier{name='org.apache.pdfbox', slot='main'}, ModuleIdentifier{name='com.fasterxml.jackson.dataformat.cbor', slot='main'}, ModuleIdentifier{name='org.apache.commons.configuration', slot='main'}, ModuleIdentifier{name='com.fasterxml.jackson.dataformat.smile', slot='main'}, ModuleIdentifier{name='org.wildfly.extension.camel', slot='main'}, ModuleIdentifier{name='org.apache.camel.script.rhino', slot='main'}, ModuleIdentifier{name='org.elasticsearch', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.pdf', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.http4', slot='main'}, ModuleIdentifier{name='org.fusesource.hawtbuf', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.syslog', slot='main'}, ModuleIdentifier{name='com.fasterxml.jackson.datatype.joda', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.nats', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.velocity', slot='main'}, ModuleIdentifier{name='com.google.code.gson', slot='main'}, ModuleIdentifier{name='org.beanshell', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.mongodb', slot='main'}, ModuleIdentifier{name='com.netflix.hystrix', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jsonpath', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jasypt', slot='main'}, ModuleIdentifier{name='org.apache.camel.script.groovy', slot='main'}, ModuleIdentifier{name='org.apache.commons.csv', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.tagsoup', slot='main'}, ModuleIdentifier{name='net.sourceforge.cssparser', slot='main'}, ModuleIdentifier{name='org.infinispan.query.dsl', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.linkedin', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.mail', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.snakeyaml', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jpa', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.ldap', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.protobuf', slot='main'}, ModuleIdentifier{name='org.apache.ws.commons.axiom.axiom-impl', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.cxf', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.crypto', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.spring.security', slot='main'}, ModuleIdentifier{name='org.mvel.mvel2', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.mvel', slot='main'}, ModuleIdentifier{name='org.scala.modules', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.mina2', slot='main'}, ModuleIdentifier{name='org.apache.abdera.i18n', slot='main'}, ModuleIdentifier{name='org.apache.commons.httpclient', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.saxon', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.vertx', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.hl7', slot='main'}, ModuleIdentifier{name='org.apache.abdera.parser', slot='main'}, ModuleIdentifier{name='org.apache.zookeeper', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jgroups', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.quartz2', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.netty4', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.activemq', slot='main'}, ModuleIdentifier{name='org.apache.commons.lang3', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.csv', slot='main'}, ModuleIdentifier{name='io.netty', slot='4.1'}, ModuleIdentifier{name='org.apache.camel.component.infinispan', slot='main'}, ModuleIdentifier{name='org.apache.camel.core', slot='main'}, ModuleIdentifier{name='org.quartz', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.dozer', slot='main'}, ModuleIdentifier{name='org.apache.cxf.ext', slot='main'}, ModuleIdentifier{name='org.apache.commons.net', slot='main'}, ModuleIdentifier{name='org.wildfly.extras.config.plugin.camel', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.gson', slot='main'}, ModuleIdentifier{name='org.apache.xbean.spring', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.script', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.beanio', slot='main'}, ModuleIdentifier{name='org.apache.httpcomponents', slot='4.5.2'}, ModuleIdentifier{name='org.apache.camel.component.twitter', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.cdi', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.smpp', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.metrics', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.bindy', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.swagger', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.ognl', slot='main'}, ModuleIdentifier{name='net.sourceforge.htmlunit', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.castor', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.bean.validator', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.sql', slot='main'}, ModuleIdentifier{name='org.apache.olingo', slot='main'}, ModuleIdentifier{name='com.thoughtworks.xstream', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jackson', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.undertow', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.zipkin', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.dns', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.rss', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.braintree', slot='main'}, ModuleIdentifier{name='org.apache.activemq', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.http.common', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.mqtt', slot='main'}, ModuleIdentifier{name='org.apache.commons.compress', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.stream', slot='main'}, ModuleIdentifier{name='com.fasterxml.jackson.dataformat.xml', slot='main'}, ModuleIdentifier{name='org.fusesource.mqtt', slot='main'}, ModuleIdentifier{name='com.rometools.rome', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.groovy', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jmx', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.xstream', slot='main'}, ModuleIdentifier{name='org.apache.mina.core', slot='main'}, ModuleIdentifier{name='com.fasterxml.jackson.dataformat.yaml', slot='main'}, ModuleIdentifier{name='org.apache.commons.pool2', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.jaxb', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.servlet', slot='main'}, ModuleIdentifier{name='org.apache.camel.component.servicenow', slot='main'}, ModuleIdentifier{name='org.springframework.security', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='com.beust.jcommander', slot='main'}. Module was required by [ModuleIdentifier{name='org.apache.camel.script.groovy', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='org.slf4j', slot='5.5'}. Module was required by [ModuleIdentifier{name='org.apache.lucene', slot='5.5'}]
[ERROR] Missing module ModuleIdentifier{name='net.sf.kxml', slot='main'}. Module was required by [ModuleIdentifier{name='com.thoughtworks.xstream', slot='main'}]
[ERROR] Missing module ModuleIdentifier{name='org.jruby', slot='main'}. Module was required by [ModuleIdentifier{name='org.springframework.context', slot='main'}]
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wildfly-camel-feature-pack
```

If you still think that this issue persists, please reopen and provide an updated testcase.
