### ISSUE TITLE
[MNG-5943] Build Failure due to NoClassDefFoundException: org/eclipse/aether/spi/connector/Transfer$State

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7744]
**[Adarsh Kumar Maurya](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adarshmauyra)** opened **[MNG-5943](https://issues.apache.org/jira/browse/MNG-5943?redirect=false)** and commented

Mentioned below are the steps which results in Exception:

**Step 1.**
mvn -X install:install-file -Dfile=%ANDROID_HOME%\platforms\android-21\android.jar -DgroupId=com.google.android -DartifactId=android -Dversion=5.0.1_r2 -Dpackaging=jar -DgeneratePom=true>>log.txt

**Step 2.**
mvn -X archetype:generate -DarchetypeArtifactId=android-quickstart  -DarchetypeGroupId=de.akquinet.android.archetypes -DarchetypeVersion=1.1.0 -DgroupId=com.packt.androidMaven -DartifactId=chapter -Dversion=1.0-SNAPSHOT -Dplatform=21 --batch-mode --quiet>>log.txt

**Step 3.**  Check <platform.version> tag. If it is empty change to above used.

**Step 4.** D:\16.Maven\chapter>mvn -X  build>log.txt

It results in below mentioned exceptions:

{
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
... 5 more
}

---

**Affects:** 3.3.9

**Issue Links:**
- [MNG-5819](https://issues.apache.org/jira/browse/MNG-5819) Failure with maven-site-plugin:stage
 (_**"Blocked"**_)

**Comment by jira-importer** [comment]
**[Adarsh Kumar Maurya](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adarshmauyra)** commented

Hi, Team. Please check the issue above and kindly fix it. Thanks :)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Can you tell what this command: `mvn -X build`   should do? Cause if i try to do such thing i will get an error message regarding the unknown life cycle phase...

**Comment by jira-importer** [comment]
**[Adarsh Kumar Maurya](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adarshmauyra)** commented

Can you please use the build's- install command

> mvn -X install  . When I do it I can regenerate the below exception stack trace again:

Mentioned below are the steps which results in Exception:
**Step 1.**
mvn -X install:install-file -Dfile=%ANDROID_HOME%\platforms\android-21\android.jar -DgroupId=com.google.android -DartifactId=android -Dversion=5.0.1_r2 -Dpackaging=jar -DgeneratePom=true>>log.txt
**Step 2.**
mvn -X archetype:generate -DarchetypeArtifactId=android-quickstart -DarchetypeGroupId=de.akquinet.android.archetypes -DarchetypeVersion=1.1.0 -DgroupId=com.packt.androidMaven -DartifactId=chapter -Dversion=1.0-SNAPSHOT -Dplatform=21 --batch-mode --quiet>>log.txt
**Step 3.**  Check <platform.version> tag. If it is empty change to above used.
**Step 4.**  D:\16.Maven\chapter> mvn -X install>log.txt

Below is an excerpt of the error log :/
...
[DEBUG] Using connector WagonRepositoryConnector from ClassRealm[extension>com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.8.2, parent: sun.misc.Launcher$AppClassLoader@47858e] with priority 0.0 for https://repo.maven.apache.org/maven2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.509 s
[INFO] Finished at: 2015-12-08T23:40:00+05:30
[INFO] Final Memory: 12M/31M
[INFO] ------------------------------------------------------------------------

---

constituent[0]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/aether-api-1.0.2.v20150114.jar
constituent[1]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/aether-connector-basic-1.0.2.v20150114.jar
constituent[2]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/aether-impl-1.0.2.v20150114.jar
constituent[3]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/aether-spi-1.0.2.v20150114.jar
constituent[4]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/aether-transport-wagon-1.0.2.v20150114.jar
constituent[5]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/aether-util-1.0.2.v20150114.jar
constituent[6]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/aopalliance-1.0.jar
constituent[7]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/cdi-api-1.0.jar
constituent[8]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/commons-cli-1.2.jar
constituent[9]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/commons-io-2.2.jar
constituent[10]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/commons-lang-2.6.jar
constituent[11]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/commons-lang3-3.4.jar
constituent[12]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/guava-18.0.jar
constituent[13]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/guice-4.0-no_aop.jar
constituent[14]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/javax.inject-1.jar
constituent[15]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/jsoup-1.7.2.jar
constituent[16]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/jsr250-api-1.0.jar
constituent[17]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-aether-provider-3.3.9.jar
constituent[18]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-artifact-3.3.9.jar
constituent[19]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-builder-support-3.3.9.jar
constituent[20]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-compat-3.3.9.jar
constituent[21]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-core-3.3.9.jar
constituent[22]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-embedder-3.3.9.jar
constituent[23]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-model-3.3.9.jar
constituent[24]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-model-builder-3.3.9.jar
constituent[25]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-plugin-api-3.3.9.jar
constituent[26]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-repository-metadata-3.3.9.jar
constituent[27]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-settings-3.3.9.jar
constituent[28]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/maven-settings-builder-3.3.9.jar
constituent[29]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/org.eclipse.sisu.inject-0.3.2.jar
constituent[30]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/org.eclipse.sisu.plexus-0.3.2.jar
constituent[31]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/plexus-cipher-1.7.jar
constituent[32]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/plexus-component-annotations-1.6.jar
constituent[33]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/plexus-interpolation-1.21.jar
constituent[34]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/plexus-sec-dispatcher-1.3.jar
constituent[35]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/plexus-utils-3.0.22.jar
constituent[36]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/slf4j-api-1.7.5.jar
constituent[37]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/slf4j-simple-1.7.5.jar
constituent[38]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/wagon-file-2.10.jar
constituent[39]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/wagon-http-2.10-shaded.jar
constituent[40]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/wagon-http-shared-2.10.jar
constituent[41]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../lib/wagon-provider-api-2.10.jar
constituent[42]: file:/D:/16.Maven/apache-maven-3.3.9/bin/../conf/logging/

---

Exception in thread "pool-1-thread-1" Exception in thread "pool-1-thread-2" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
... 5 more
java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/spi/connector/Transfer$State
at org.eclipse.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:608)
at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.spi.connector.Transfer$State
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
... 5 more

Thanks a lot.

**Comment by jira-importer** [comment]
**[Adarsh Kumar Maurya](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adarshmauyra)** commented

From the logs I was trying to use a wagon to send files to somewhere and the wagon which I using does not come out of the apache-maven-3.3.9 and I haven't included the jar file for it.

So, I copied the relevant jars-aether-api-0.9.0.M2,aether-impl-0.9.0.M2,aether-connector-wagon-0.9.0.M2,aether-spi-0.9.0.M2,aether-util-0.9.0.M2 and copied it in Directory:\...\.Maven\apache-maven-3.3.9\lib

After it, I executed mvn clean install and it worked.

Please check: https://github.com/simpligility/android-maven-plugin/issues/686
