### ISSUE TITLE
[MNG-5831] NoClassDefFoundError: org/apache/commons/cli/ParseException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7793]
**[FeiCao](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cfly)** opened **[MNG-5831](https://issues.apache.org/jira/browse/MNG-5831?redirect=false)** and commented

C:\>java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

C:\>mvn -v
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2436)
at java.lang.Class.getMethod0(Class.java:2679)
at java.lang.Class.getMethod(Class.java:1605)
at org.codehaus.plexus.classworlds.launcher.Launcher.getEnhancedMainMethod(Launcher.java:172)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:268)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:254)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
... 9 more
C:\>set |findstr M2
M2=C:\cc\apache-maven-3.2.5

---

**Affects:** 3.2.5

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Did you try a newer version of Maven?

**Comment by jira-importer** [comment]
**[FeiCao](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cfly)** commented

I downlaod again [apache-maven-3.2.5-bin.zip].
Now it's work fine.

C:\>mvn -v
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-15T01:29:23+08:00)
Maven home: C:\cc\apache-maven-3.2.5\bin\..
Java version: 1.6.0_45, vendor: Sun Microsystems Inc.
Java home: C:\cc\jdk1.6.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

Sorry,
Not bug, it's my fault.
Thank you very much.
