### ISSUE TITLE
[MNG-5779] NoClassDefFoundError: org/slf4j/spi/LocationAwareLogger when generating javadoc during site reporting

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7818]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** opened **[MNG-5779](https://issues.apache.org/jira/browse/MNG-5779?redirect=false)** and commented

issue found while working on another topic: https://github.com/apache/maven/pull/32#issuecomment-76933957

when running m-site-p ITs, following issue happen with m-javadoc-p too (without failing the build): see full-reporting IT output log:

```
[INFO] Generating "JavaDocs" report             --- maven-javadoc-plugin:2.9.1:javadoc
[DEBUG] Trying to add links for dependencies...
[WARNING] An issue has occurred with maven-javadoc-plugin:2.9.1:javadoc, skipping LinkageError org/slf4j/spi/LocationAwareLogger, please report an issue to Maven dev team.
java.lang.NoClassDefFoundError: org/slf4j/spi/LocationAwareLogger
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:156)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:131)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:272)
	at org.apache.http.impl.conn.PoolingClientConnectionManager.<init>(PoolingClientConnectionManager.java:73)
	at org.apache.http.impl.conn.PoolingClientConnectionManager.<init>(PoolingClientConnectionManager.java:99)
	at org.apache.http.impl.conn.PoolingClientConnectionManager.<init>(PoolingClientConnectionManager.java:85)
	at org.apache.http.impl.conn.PoolingClientConnectionManager.<init>(PoolingClientConnectionManager.java:93)
	at org.apache.maven.plugin.javadoc.JavadocUtil.createHttpClient(JavadocUtil.java:1811)
	at org.apache.maven.plugin.javadoc.JavadocUtil.isValidPackageList(JavadocUtil.java:1704)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.isValidJavadocLink(AbstractJavadocMojo.java:5638)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.getDependenciesLinks(AbstractJavadocMojo.java:5480)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.collectLinks(AbstractJavadocMojo.java:2960)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.addLinkArguments(AbstractJavadocMojo.java:3921)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.addStandardDocletOptions(AbstractJavadocMojo.java:4676)
	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1954)
	at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:130)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:236)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:182)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:851)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:275)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LocationAwareLogger
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 43 more
```

---

**Affects:** 3.3.0

**Attachments:**
- [core-build-failure.log](https://issues.apache.org/jira/secure/attachment/12713427/core-build-failure.log) (_10.80 kB_)

**Issue Links:**
- [MNG-5783](https://issues.apache.org/jira/browse/MNG-5783) cobertura-maven-plugin:instrument failing NoClassDefFoundError: org/slf4j/LoggerFactory

- [MNG-5771](https://issues.apache.org/jira/browse/MNG-5771) improved user-configurable core extensions mechanism

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

this one is even worse than expected: I tried compiling core (yes, compiling, not generating the site) with 3.3.0-SNAPSHOT and got following failure:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.14:check (checkstyle-check) on project maven: Execution checkstyle-check of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.14:check failed: A required class was missing while executing org.apache.maven.plugins:maven-checkstyle-plugin:2.14:check: org/slf4j/spi/LocationAwareLogger
```

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

thanks for your feedback

Here is my output for `mvn -V install`: what do I do wrong (???)

**Comment by jira-importer** [comment]
**[Jason van Zyl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jvanzyl)** commented

Hervé, try master now (57a6196422873eaf2f00a282b33894a74dcfd19c) and see if that fixes the javadoc issue for you. I'll check in tomorrow.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

great: both javadoc and checkstyle:check (for Maven core build) work

link added to MNG-5771, since I now understand this was a missed package export declaration

Thank you Jason: we're avoiding here a failed release vote :)
