### ISSUE TITLE
[MNG-5907] org.apache.maven.repository.internal.RemoteSnapshotMetadataTest fails to start at midnight

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7906]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** opened **[MNG-5907](https://issues.apache.org/jira/browse/MNG-5907?redirect=false)** and commented

Currently this test fails (it seemed to be the reason having started the build at midnight CET):

Running org.apache.maven.repository.internal.RemoteSnapshotMetadataTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec <<< FAILURE! - in org.apache.maven.repository.internal.RemoteSnapshotMetadataTest
gregorianCalendarIsUsed(org.apache.maven.repository.internal.RemoteSnapshotMetadataTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: Expected 20151007 to be in [20151008]
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.apache.maven.repository.internal.RemoteSnapshotMetadataTest.gregorianCalendarIsUsed(RemoteSnapshotMetadataTest.java:79)

Running org.apache.maven.repository.internal.RepositorySystemTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.832 sec - in org.apache.maven.repository.internal.RepositorySystemTest

I have run maven build several times over the day and had no problems..I have to take a deeper look into this...

I have run the build at about 11:00 o'clock am (CET) and the build is successful....with the exact same code state.

---

**Affects:** 3.3.9

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

As far as I can see is that the timezone in `gregorianDate` is not set to `Etc/UTC`. Try with that and it should work, imho. Just noticed that I did not review the PR good enough.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Just reproduced it. Just like a set, a time zone issue. Fails here at 15:00 `Europe/Berlin` if I set time zone to `Pacific/Auckland`.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [316298e529c08936562d707ef136dc2756f0f084](https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commit;h=316298e529c08936562d707ef136dc2756f0f084) and [2ec27257b4936762a92c2ac860ea5d633c633e77](https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commit;h=2ec27257b4936762a92c2ac860ea5d633c633e77).
