### ISSUE TITLE
[MNG-7055] Using MINSTALL/DEPLOY 3.0.0-M1+ does not write plugin information into maven-metadata.xml

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#7983]
**[Elliotte Rusty Harold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elharo)** opened **[MNG-7055](https://issues.apache.org/jira/browse/MNG-7055?redirect=false)** and commented

explanation: [`metadata/plugins` content in maven-metadata.xml descriptor](https://maven.apache.org/ref/3.8.6/maven-repository-metadata/repository-metadata.html) from plugin's groupId is not updated (ie. `plugin/name+prefix+artifactId`) on first plugin release deployment, then plugin's prefix is not published

see for example existing plugin data in [https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml](https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml)

Copying [Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)'s comment from mailing list on HEAD with Maven core ITs:

https://markmail.org/message/ggcioupa6yaet4xe#query:+page:1+mid:noyp5d3iyclrfgyp+state:results

```
[ERROR] Tests run: 834, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 287.261 s <<< FAILURE! - in org.apache.maven.it.IntegrationTestSuite
[ERROR] testitMNG3372(org.apache.maven.it.MavenITmng3372DirectInvocationOfPluginsTest)
Time elapsed: 1.5 s  <<< ERROR!
org.apache.maven.it.VerificationException:
Exit code was non-zero: 1; command line and log =
/var/osipovmi/Projekte/maven-integration-testing/core-it-suite/target/apache-maven/bin/mvn
--global-settings
/var/osipovmi/Projekte/maven-integration-testing/core-it-suite/target/test-classes/settings.xml
-s
/var/osipovmi/Projekte/maven-integration-testing/core-it-suite/target/test-classes/mng-3372/direct-using-prefix/settings.xml
-e --batch-mode
-Dmaven.repo.local=/net/home/osipovmi/var/Projekte/maven-integration-testing/repo
mng3372:test
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for
org.apache.maven.its.mng3372:project:jar:1.0-SNAPSHOT
[WARNING] Version not locked for default bindings plugins [maven-clean-plugin,
maven-resources-plugin, maven-jar-plugin, maven-compiler-plugin,
maven-surefire-plugin, maven-install-plugin, maven-deploy-plugin,
maven-site-plugin], you should define versions in pluginManagement section of
your pom.xml or parent @ line 6, column 14
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] Downloading from central: file:target/null/org/apache/maven/its/mng3372/maven-metadata.xml
[INFO] Downloading from central: file:target/null/org/apache/maven/plugins/maven-metadata.xml
[INFO] Downloading from central: file:target/null/org/codehaus/mojo/maven-metadata.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.056 s
[INFO] Finished at: 2020-06-04T22:03:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'mng3372' in the current project and in the
plugin groups [org.apache.maven.its.mng3372, org.apache.maven.plugins,
org.codehaus.mojo] available from the repositories [local
(/net/home/osipovmi/var/Projekte/maven-integration-testing/repo), central
(file:target/null)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found
for prefix 'mng3372' in the current project and in the plugin groups
[org.apache.maven.its.mng3372, org.apache.maven.plugins, org.codehaus.mojo]
available from the repositories [local (/net/home/osipovmi/var/Projekte/maven-integration-testing/repo), central (file:target/null)]
    at org.apache.maven.plugin.prefix.internal.DefaultPluginPrefixResolver.resolve(DefaultPluginPrefixResolver.java:98)
    at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.findPluginForPrefix(MojoDescriptorCreator.java:269)
    at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescript
```

---

**Issue Links:**
- [MPOM-332](https://issues.apache.org/jira/browse/MPOM-332) Upgrade maven-deploy-plugin to 3.1.1
 (_**"blocks"**_)
- [MSHARED-920](https://issues.apache.org/jira/browse/MSHARED-920) NPE in DefaultArtifactInstaller.install - missing injection of RepositoryManager

- [MNG-7870](https://issues.apache.org/jira/browse/MNG-7870) Undeprecate wrongly deprecated repository metadata

- [MNG-6556](https://issues.apache.org/jira/browse/MNG-6556) Packaging 'maven-plugin' binding plugin upgrades

- [MPLUGIN-384](https://issues.apache.org/jira/browse/MPLUGIN-384) Nexus Staging Plugin - incompatibility

- [MNG-7375](https://issues.apache.org/jira/browse/MNG-7375) Potential NPE in o.a.m.artifact.repository.metadata.Metadata.merge(...) with invalid/incomplete plugin metadata

- [MDEPLOY-291](https://issues.apache.org/jira/browse/MDEPLOY-291) Update POM parent and Maven + warn if older Maven is used to build a Maven plugin (as impacted by MNG-7055)

- [MPOM-368](https://issues.apache.org/jira/browse/MPOM-368) Bump maven-install-plugin from 2.5.2 to 3.0.1

**Remote Links:**
- [GitHub Pull Request #555
](https://github.com/apache/maven/pull/555)
- [GitHub Pull Request #691
](https://github.com/apache/maven/pull/691)
- [Github Pull Request #691 (backport to 3.9.x)
](https://github.com/apache/maven/pull/691)

**Backported to:** [4.0.0-alpha-2](https://github.com/apache/maven/milestone/113?closed=1), [3.9.0](https://github.com/apache/maven/milestone/2?closed=1)

0 votes, 11 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Looking at it, this looks like this is the start of dropping the Maven2 mechanism to install artifacts and to start using Aether/Maven Artifact Resolver. Looks unrelated to the error.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Artifact Transfer is just a bridge, to make it possible to work with Sonetype Aether and Eclipse Aether. The logic for plugin metadata doesn't belong there. I don't know where it should be now.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I agree with that because this is packaging specific. The problem is the it currently not possible to install or deploy that piece of information with MINSTALL/MDEPLOY 3.0.0-x. Maven needs this metadata to work properly, so we have to solve this problem somehow.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

IMO this belongs in Maven itself, not in a library or plugin. I'll need ito investigate if there is a clean way for plugin artifacts to hook into MAven Artifact Resolver

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks, this is really something to be very nice in 4.0.0. Let me know if I can help.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

So this should be moved to MNG and I can perform a release of this component?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

issue is unrelated to maven-artifact-transfer, so go ahead.

**Comment by jira-importer** [comment]
**[Maarten Mulders](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mthmulders)** commented

[Martin Kanters](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=martinkanters) and I will start working on this. We will move the existing "install / deploy" logic into Core, implementing it on top of Maven Resolver API. The M-I-P and M-D-P will leverage that, but they will still need a fallback (implemented with Eclipse Aether) so they are compatible with Maven 3.1 and above. We expect to drop Maven 3.0 compatibility.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Failing ITs when update m-i-p and m-d-p to 3.x are:

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MavenITmng3441MetadataUpdatedFromDeploymentRepositoryTest>AbstractMavenIntegrationTestCase.runTest:265->testitMNG3441:72 expected:<[test-artifact]> but was:<[blah]>
[ERROR] Errors: 
[ERROR]   MavenITmng3372DirectInvocationOfPluginsTest>AbstractMavenIntegrationTestCase.runTest:265->testitMNG3372:65 » Verification
[INFO] 
[ERROR] Tests run: 879, Failures: 1, Errors: 1, Skipped: 0
 
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas), can you tell whether this can/should be backported to 3.9.0?

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

I would try to backport it, it's a real shame that two of most important plugins (install and deploy) were NEVER released for maven 3 as 3.x.x

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Backported as https://github.com/apache/maven/pull/691, locally tested and all ok. Please bless it (pretty much same change as already scrutinized original PR).

**Comment by jira-importer** [comment]
**[Václav Haisman](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wilx)** commented

Can you please confirm that for Maven 3.6.3, I should use maven-deploy-plugin 2.8.2 to avoid this issue?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

This applies to packaging maven-plugin only.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Maybe we should have warning inside deploy plugin about this issue?

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz) - we have:

https://github.com/apache/maven-deploy-plugin/blob/master/src/main/java/org/apache/maven/plugins/deploy/AbstractDeployMojo.java#L95-L102
