### ISSUE TITLE
[MNG-7011] consistent profile/module exclusion

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8022]
**[Delany](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=delany)** opened **[MNG-7011](https://issues.apache.org/jira/browse/MNG-7011?redirect=false)** and commented

I can exclude a profile with -P\!beetroot or -P-beetroot

But I can only exclude a module with -pl\!carrot

---

**Affects:** 3.6.3

**Issue Links:**
- [MNG-7051](https://issues.apache.org/jira/browse/MNG-7051) Optionally skip non-existing profiles

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Interesting, have you looked yourself in the code why that is the case?

**Comment by jira-importer** [comment]
**[Delany](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=delany)** commented

Where do I start?

**Comment by jira-importer** [comment]
**[Martin Kanters](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=martinkanters)** commented

This is the method that processes the -pl flag: https://github.com/apache/maven/blob/master/maven-embedder/src/main/java/org/apache/maven/cli/MavenCli.java#L1476 .
The method below is the one that processes the -P flag: `determineProfileActivation`.

It does seem to support - as well as !. So maybe there is a bug in that method or somewhere else. 
I advice you to check out the source code and attach a debugger to it (using `mvnDebug`).

**Comment by jira-importer** [comment]
**[Piotr Zygielo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pzygielo)** commented

I observe similar as reported AND similar as expected:
1. as expected - module exclusion works with exclamation point and dash with the exception described below,
2. **if the module** to be excluded starts with the character that is also short maven option - for example: `-pl -saturn,` following happens.

```java
org.apache.commons.cli.MissingArgumentException: Missing argument for option: pl
	at org.apache.commons.cli.Parser.processArgs(Parser.java:363)
	at org.apache.commons.cli.Parser.processOption(Parser.java:395)
	at org.apache.commons.cli.Parser.parse(Parser.java:210)
	at org.apache.commons.cli.Parser.parse(Parser.java:88)
	at org.apache.maven.cli.CLIManager.parse(CLIManager.java:162)
```

But it works with dash if `-pl -:saturn` is used (i.e. artifactId instead of module's folder).

So I suppose `carrot` can't be excluded with `-`, due to

```java
-c,--lax-checksums                     Warn if checksums don't match
```

This works however too: `-pl " -saturn"` (with argument to `-pl` starting with skippable, innocent space).
