### ISSUE TITLE
[MNG-6843] Parallel build fails due to missing JAR artifacts in compilePath

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8194]
**[Stepan Hrbacek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stepan.hrbacek@gmail.com)** opened **[MNG-6843](https://issues.apache.org/jira/browse/MNG-6843?redirect=false)** and commented

Build of our multi module (57) Java maven project is failing phase when running it as parallel in 4 threads (mvn -T 4 clean install). The failure happens during compilation because packages/classes from compile dependencies cannot be found:

```
[main] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project common: Compilation failure: Compilation failure: 
[main] [ERROR] /home/common/src/main/java/com/foo/ZonedDateTimeParser.java:[6,32] package org.apache.commons.lang3 does not exist
```

After enabling debug logging (with thread names) I have found out that a compile path of the failing module is empty (besides target/classes):

When running in 4 threads (-T 4):

```
[BuilderThread 2] [DEBUG] (f) compilePath = [/home/common/target/classes]
...
[BuilderThread 2] [DEBUG] Command line options:
[BuilderThread 2] [DEBUG] -d /home/common/target/classes -classpath /home/common/target/classes: -sourcepath /home/common/src/main/java:/home/common/target/generated-sources/annotations: -s /home/common/target/generated-sources/annotations -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8
```

When running in a single thread (-T 1):

```
[BuilderThread 0] [DEBUG] (f) compilePath = [/home/common/target/classes, /root/.m2/repository/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar, /root/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, /root/.m2/repository/org/apache/commons/commons-collections4/4.3/commons-collections4-4.3.jar, /root/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar, /root/.m2/repository/org/jooq/jool-java-8/0.9.14/jool-java-8-0.9.14.jar, /root/.m2/repository/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar, /root/.m2/repository/org/springframework/spring-beans/5.1.8.RELEASE/spring-beans-5.1.8.RELEASE.jar, /root/.m2/repository/org/springframework/spring-core/5.1.8.RELEASE/spring-core-5.1.8.RELEASE.jar, /root/.m2/repository/org/springframework/spring-context/5.1.8.RELEASE/spring-context-5.1.8.RELEASE.jar]
...
[BuilderThread 0] [DEBUG] Command line options:
[BuilderThread 0] [DEBUG] -d /home/common/target/classes -classpath /home/common/target/classes:/root/.m2/repository/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar:/root/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/root/.m2/repository/org/apache/commons/commons-collections4/4.3/commons-collections4-4.3.jar:/root/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar:/root/.m2/repository/org/jooq/jool-java-8/0.9.14/jool-java-8-0.9.14.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar:/root/.m2/repository/org/springframework/spring-beans/5.1.8.RELEASE/spring-beans-5.1.8.RELEASE.jar:/root/.m2/repository/org/springframework/spring-core/5.1.8.RELEASE/spring-core-5.1.8.RELEASE.jar:/root/.m2/repository/org/springframework/spring-context/5.1.8.RELEASE/spring-context-5.1.8.RELEASE.jar: -sourcepath /home/common/src/main/java:/home/common/target/generated-sources/annotations: -s /home/common/target/generated-sources/annotations -g -nowarn -target 1.8 -source 1.8 -encoding UTF-8
```

After adding custom log messages I have found out that the root cause is that org.apache.maven.project.MavenProject.setArtifactFilter() is called with null artifactFilter parameter. The call happens for the failing module from a thread that is building another module. The call stack is:

```java
"BuilderThread 0@2513" prio=5 tid=0xe nid=NA runnable
 java.lang.Thread.State: RUNNABLE
 at org.apache.maven.project.MavenProject.setArtifactFilter(MavenProject.java:1437)
 at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:279)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:202)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
 at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
 at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
```

The MavenProject objects are shared among all build threads via MavenSession - member `org.apache.maven.execution.MavenSession#projects`.
As all the MavenSession objects are created by cloning an initial MavenSession object, I have added cloning of projects into the MavenSession clone() method. With this change the build succeeded:

```java
@Override
public MavenSession clone()
{
    try
    {
        MavenSession thisClone = (MavenSession) super.clone();
        thisClone.setProjects(getProjectsClone());
        return thisClone;
    }
    catch ( CloneNotSupportedException e )
    {
        throw new RuntimeException( "Bug", e );
    }
}

private synchronized List<MavenProject> getProjectsClone()
{
    if (projects == null) {
        return null;
    } else {
        if (projects.isEmpty()) {
            return Collections.emptyList();
        } else {
            List<MavenProject> clonedProjects = new ArrayList<>(projects.size());
            for (MavenProject project : projects) {
                clonedProjects.add(project.clone());
            }            return clonedProjects;
        }
    }
}
```

---

**Affects:** 3.6.3

**Issue Links:**
- [MNG-7335](https://issues.apache.org/jira/browse/MNG-7335) [Regression] Parallel build fails due to missing JAR artifacts in compilePath
 (_**"is cloned by"**_)
- [MNG-7220](https://issues.apache.org/jira/browse/MNG-7220) [REGRESSION] test-classpath incorrectly resolved
 (_**"causes"**_)
- [MNG-4526](https://issues.apache.org/jira/browse/MNG-4526) [regression] Shade plugin includes too much (relative to 2.2.1)
 (_**"is caused by"**_)
- [MNG-7157](https://issues.apache.org/jira/browse/MNG-7157) Provide a better design for obtaining artifacts from a MavenProject inside a mojo

- [MNG-7212](https://issues.apache.org/jira/browse/MNG-7212) Prefer use of InheritableThreadLocal to fix possible issue when mojo starts a thread and tries to access some artifacts

- [MNG-7285](https://issues.apache.org/jira/browse/MNG-7285) [Regression] MavenProject.getArtifacts() not returning correct value across multiple threads
 (_**"breaks"**_)
- [MNG-7312](https://issues.apache.org/jira/browse/MNG-7312) Revert ThreadLocal approach from MNG-6843 and MNG-7251
 (_**"breaks"**_)

**Remote Links:**
- [GitHub Pull Request #310
](https://github.com/apache/maven/pull/310)
- [GitHub Pull Request #413
](https://github.com/apache/maven/pull/413)
- [GitHub Pull Request #482
](https://github.com/apache/maven/pull/482)

**Backported to:** [4.0.0-alpha-2](https://github.com/apache/maven/milestone/113?closed=1), [3.8.2](https://github.com/apache/maven/milestone/103?closed=1)

7 votes, 19 watchers

**Comment by jira-importer** [comment]
**[Stepan Hrbacek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stepan.hrbacek@gmail.com)** commented

None that I can share at the moment :-(.
I would have to create a dummy project with the same structure that, IMHO, is causing the race condition I am experiencing.

Easier would be to debug a build - simulate the race condition via pausing threads at `org.apache.maven.project.MavenProject.setArtifactFilter()` and then resuming them in a desired order.

**Comment by jira-importer** [comment]
**[Filip Kaliński](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fkalinski)** commented

As discussed on the Github, I have tried another workaround by using ThreadLocal for MavenProject dependency artifact list related fields and it works for me, at least. It's https://github.com/fkalinski/maven/commit/b38e3c2bfb6183c0f45214012112a1c1ca4048bd.
I have also created a Maven extension https://github.com/fkalinski/parallel-workaround  to make it possible to use the workaround without modified Maven.

The problem looks to be triggered by aggregator mojos. In my case by maven-help-plugin:effective-pom, which was executed for every project. Every time it was called, the loop over all projects called MavenProject.setArtifactFilter in MojoExecutor.ensureDependenciesAreResolved(), leading to a very high chance of project dependency artifacts being overwritten. I have just moved the call to effective-pom from the parent project to the top-level project, to have it called once, and it was sufficient.

Of course Maven needs to properly handle also such cases, for sure there are more legitimate uses of aggregator mojos. Maybe cloning of the projects only for the execution of aggregators would be a good approach?

**Comment by jira-importer** [comment]
**[Stepan Hrbacek](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stepan.hrbacek@gmail.com)** commented

> Stepan Hrbacek have you ever managed to create a reproducer? I cannot share my project either (closed source).

[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod): I have not. Always after removing proprietary stuff (that cannot be shared) the build timing has changed and build succeeded.

**Comment by jira-importer** [comment]
**[Filip Kaliński](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fkalinski)** commented

I have added a reproducible test case at https://github.com/fkalinski/parallel-testbed

There is a script for generating a number of child modules. For 20 child modules and 8 threads the build always fail for me. After applying the workaround it always succeed.

Of course there can be problems due to the codebase not really prepared for concurency, that can have different ways of fixing...

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

FWIW, [Filip Kaliński](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fkalinski) , you generate script ist not portable. It does not work with BSD sed. Please apply the following:

 

```
index ddc4dbe..2285a68 100755
--- a/generate.sh
+++ b/generate.sh
@@ -1,4 +1,4 @@
 #!/bin/sh
 COUNT=$1
 find . -maxdepth 1 -type d -name 'child*' | grep -v 'child1$' | xargs rm -rf
-MODULES=$(for i in `seq 2 $COUNT`; do cp -a child1 child$i; sed -i "s/>child1</>child$i</" child$i/pom.xml; echo "<module>child$i</module>"; done); (cat pom-start; echo $MODULES; cat pom-end) > pom.xml
+MODULES=$(for i in `seq 2 $COUNT`; do cp -a child1 child$i; sed -i"" -e "s/>child1</>child$i</" child$i/pom.xml; echo "<module>child$i</module>"; done); (cat pom-start; echo $MODULES; cat pom-end) > pom.xml
 
```

I expect it to work with GNU sed too.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I confirm that this still happens on Maven master with Resolver 1.7.0-SNAPSHOT. This isn't Resolver related because no dependency resolution happens in the build.

**Comment by jira-importer** [comment]
**[Matt Nelson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mattnelson)** commented

> Btw: It seems that in my case the problem can be worked around by defining the respective dependencies directly instead of relying on being pulled in transitively.

Not a solution, but can be used as a temporary workaround. Having a compilation dependency transitively provided can be fragile if the top level dependency no longer provides that transitive after an update. The dependency plugin's analyze* goals can alert to this situation with a "used and undeclared" warning.

https://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [73e00ed85df84ba0c557dd020740812b2453f2d3](https://gitbox.apache.org/repos/asf?p=maven.git;a=commit;h=73e00ed85df84ba0c557dd020740812b2453f2d3)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod), do you want to backport your PR back to 3.8.x?

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) Please see https://github.com/apache/maven/pull/482 for the backport.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with [76d5f0d942f52650d3bdf775b6af42d23d69066b](https://gitbox.apache.org/repos/asf?p=maven.git;a=commit;h=76d5f0d942f52650d3bdf775b6af42d23d69066b) for `maven-3.8.x` branch.

**Comment by jira-importer** [comment]
**[Mickael Istria](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mickael.istria)** commented

This does unfortunately cause a regression in m2e when moving from 3.8.1 to 3.8.3: https://github.com/eclipse-m2e/m2e-core/issues/346 and https://github.com/eclipse-m2e/m2e-core/issues/347 . Apparently, because of this change, using MavenProject across different threads makes that some classpath references are missing in some cases.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Mickael Istria](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mickael.istria), please spawn a new issue and lets discuss it there. Ping me then.

**Comment by jira-importer** [comment]
**[Mickael Istria](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mickael.istria)** commented

> please spawn a new issue

Done with MNG-7285

**Comment by jira-importer** [comment]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) Shouldn't this be reopened with https://issues.apache.org/jira/browse/MNG-7312 applied to 3.8.4 and 4.0?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

No, because that would mean that the change has been undone in a previous release. A change in history so to speak. In 3.8.3 it is supposed to work somehow. If this is still broken (again) in 3.8.4 then a new or cloned issue needs to be created.

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

> If this is still broken (again) in 3.8.4 then a new or cloned issue needs to be created.

Just to set the record straight:

There is no "if" here. MNG-7312 removed the ThreadLocal approach that fixed this issue and no alternative solution has been incorporated.

So the breakage is a fact, MNG-6843 (this issue) is back in 3.8.4.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Correct. The TL fix caused multiple regressions.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I hope we can get this straight in 3.8.5 or 3.9.0.

**Comment by jira-importer** [comment]
**[Falko Modler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=famod)** commented

I created a clone (as suggested): MNG-7335
