### ISSUE TITLE
[MNG-7188] Maven fails to start in Cygwin when installed with SDKMAN

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8277]
**[Davor Krtic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkrtic)** opened **[MNG-7188](https://issues.apache.org/jira/browse/MNG-7188?redirect=false)** and commented

 Exception:

```
java.io.FileNotFoundException: C:\cygwin64\home\davor.krtic\.sdkman\candidates\maven\current\bin\m2.conf ...
```

`current` folder is a symlink which Windows doesn't recognize. (SDKMAN uses symlinks to manage different versions)

Changing the following line in the `mvn` script from:

```java
MAVEN_HOME=`cd "$MAVEN_HOME" && pwd`
```

to:

```java
MAVEN_HOME=`cd "$MAVEN_HOME" && pwd -P`
```

fixes the problem as it avoids symlinks.

---

**Affects:** 3.8.1

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please show the exact error.

**Comment by jira-importer** [comment]
**[Davor Krtic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkrtic)** commented

The exact error:

```
java.io.FileNotFoundException: C:\cygwin64\home\davor.krtic\.sdkman\candidates\maven\current\bin\m2.conf (Das System kann auf die Datei nicht zugreifen)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:381)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

In Cygwin shell:

```
➜ maven pwd
/home/davor.krtic/.sdkman/candidates/maven 
➜ maven ls -lG
insgesamt 8
drwxr-xr-x+ 1 davor.krtic 0 7. Nov 2019 3.6.3
drwxr-xr-x+ 1 davor.krtic 0 7. Nov 2019 3.8.1
lrwxrwxrwx  1 davor.krtic 5 6. Mai 12:46 current -> 3.8.1
➜  maven cd current/bin
➜  bin pwd
/home/davor.krtic/.sdkman/candidates/maven/current/bin
➜  bin pwd -P
/home/davor.krtic/.sdkman/candidates/maven/3.8.1/bin
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Let me reproduce this...

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I cannot reproduce this:

```
mosipov@mikaw10 /cygdrive/d
$ ls -l | grep maven
drwxrwx---+ 1 mosipov      Kein                   0 15. Jul 17:42 apache-maven-3.8.2-SNAPSHOT
lrwxrwxrwx  1 mosipov      Kein                  27 15. Jul 17:43 apache-maven-current -> apache-maven-3.8.2-SNAPSHOT
$ ./apache-maven-current/bin/mvn -v
Apache Maven 3.8.2-SNAPSHOT (176b272f30c4fbd62013b4702ab28518c21628ac)
Maven home: D:\apache-maven-3.8.2-SNAPSHOT
Java version: 1.8.0_292, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by jira-importer** [comment]
**[Davor Krtic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkrtic)** commented

How does your link look like from Windows CMD or PS ?

From some SO thread: Default Cygwin symlinks are just regular files
When I create a symlink after i do

```java
export CYGWIN="winsymlinks:nativestrict"
```

then it works, but I have to start Cygwin as Administrator to be able to create symlinks.

How the links look from CMD :

```java
15.07.2021  22:52    <JUNCTION>     link_default [...]
15.07.2021  22:52    <SYMLINKD>     link_strict [3.8.1]
```

And from PS:

```java
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----l        15.07.2021     22:52                link_strict
-a---l        15.07.2021     22:52              0 link_default
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I will try to reproduce this with Windows native symbolic links and not Cygwin softlinks.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Cygwin does not create junctions for me, it does use the System mode, at least PS shows me that.
I have create natively symlinks with Cygwin and PS and both show up as symbolic links and works from PS, CMD, Cygwin, MinGW for 4.0.x and 3.8.x.
I cannot reproduce it. If SDKMAN has modified the Maven distro for some reason, then its their fault.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please provide exact commands without SDKMAN and all versions of tools you have used (e.g., Cygwin).

**Comment by jira-importer** [comment]
**[Davor Krtic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkrtic)** commented

Upgrading Cygwin from 3.1.7 to 3.2.0 fixed the issue so it looks like this was a bug in Cygwin.
If I downgrade back to 3.1.7 the problem returns.

You can close this issue.
