### ISSUE TITLE
[MNG-7165] Maven does not start if there is no Jansi native library available

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8288]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[MNG-7165](https://issues.apache.org/jira/browse/MNG-7165?redirect=false)** and commented

Compiled Maven from 5c45b3fe22d8ec4270b2cf1016581b8927d2913d and started on:

```
$ uname -a
HP-UX deblndw0 B.11.31 U ia64 HP-UX
$ java -version
java version "1.8.0.21-hp-ux"
Java(TM) SE Runtime Environment (build 1.8.0.21-hp-ux-b1)
Java HotSpot(TM) Server VM (build 25.21-b1, mixed mode)
```

with following result:

```
$ ~/apache-maven-4.0.0-alpha-1-SNAPSHOT/bin/mvn
---------------------------------------------------
constituent[0]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/conf/logging/
constituent[1]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-embedder-4.0.0-alpha-1-SNAPSHOT.jar
constituent[2]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-settings-4.0.0-alpha-1-SNAPSHOT.jar
constituent[3]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-settings-builder-4.0.0-alpha-1-SNAPSHOT.jar
constituent[4]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-plugin-api-4.0.0-alpha-1-SNAPSHOT.jar
constituent[5]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-model-4.0.0-alpha-1-SNAPSHOT.jar
constituent[6]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-model-builder-4.0.0-alpha-1-SNAPSHOT.jar
constituent[7]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-builder-support-4.0.0-alpha-1-SNAPSHOT.jar
constituent[8]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-api-1.7.0.jar
constituent[9]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-util-1.7.0.jar
constituent[10]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-shared-utils-3.3.4.jar
constituent[11]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/commons-io-2.6.jar
constituent[12]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-slf4j-wrapper-4.0.0-alpha-1-SNAPSHOT.jar
constituent[13]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/guice-4.2.3-no_aop.jar
constituent[14]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/guava-30.1-jre.jar
constituent[15]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/failureaccess-1.0.1.jar
constituent[16]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/javax.inject-1.jar
constituent[17]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/jsr250-api-1.0.jar
constituent[18]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/plexus-utils-3.3.0.jar
constituent[19]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/plexus-sec-dispatcher-1.4.jar
constituent[20]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/slf4j-api-1.7.30.jar
constituent[21]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/commons-lang3-3.8.1.jar
constituent[22]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-core-4.0.0-alpha-1-SNAPSHOT.jar
constituent[23]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-repository-metadata-4.0.0-alpha-1-SNAPSHOT.jar
constituent[24]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-artifact-4.0.0-alpha-1-SNAPSHOT.jar
constituent[25]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-model-transform-4.0.0-alpha-1-SNAPSHOT.jar
constituent[26]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-provider-4.0.0-alpha-1-SNAPSHOT.jar
constituent[27]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-impl-1.7.0.jar
constituent[28]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-named-locks-1.7.0.jar
constituent[29]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/javax.annotation-api-1.3.2.jar
constituent[30]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-spi-1.7.0.jar
constituent[31]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[32]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-compat-4.0.0-alpha-1-SNAPSHOT.jar
constituent[33]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/plexus-interpolation-1.26.jar
constituent[34]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/plexus-component-annotations-2.1.0.jar
constituent[35]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/wagon-provider-api-3.4.3.jar
constituent[36]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[37]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/commons-cli-1.4.jar
constituent[38]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/wagon-http-3.4.3-shaded.jar
constituent[39]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/jcl-over-slf4j-1.7.30.jar
constituent[40]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/wagon-file-3.4.3.jar
constituent[41]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-connector-basic-1.7.0.jar
constituent[42]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-resolver-transport-wagon-1.7.0.jar
constituent[43]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/maven-slf4j-provider-4.0.0-alpha-1-SNAPSHOT.jar
constituent[44]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/jansi-2.2.0.jar
constituent[45]: file:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/plexus-cipher-1.8.jar
---------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.fusesource.jansi.AnsiConsole.ansiStream(AnsiConsole.java:239)
        at org.fusesource.jansi.AnsiConsole.initStreams(AnsiConsole.java:542)
        at org.fusesource.jansi.AnsiConsole.systemInstall(AnsiConsole.java:496)
        at org.apache.maven.shared.utils.logging.MessageUtils.systemInstall(MessageUtils.java:67)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:200)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.RuntimeException: Unable to load jansi native library
        at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:62)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:30)
        ... 13 more
Caused by: java.lang.Exception: No native library found for os.name=HPUX, os.arch=ia64_32, paths=[/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/jansi-native/HPUX/ia64_32:/net/home/osipovmi/apache-maven-4.0.0-alpha-1-SNAPSHOT/lib/jansi-native:/opt/oracle/product/19.0.0/client_1/lib:/usr/lib]
        at org.fusesource.jansi.internal.JansiLoader.loadJansiNativeLibrary(JansiLoader.java:333)
        at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:60)
        ... 14 more
```

This makes Maven unusable if Jansi native is not available. This behavior is unacceptable for a portable application.

---

**Affects:** 3.0-alpha-1

**Issue Links:**
- [MNG-7179](https://issues.apache.org/jira/browse/MNG-7179) Upgrade Jansi to 2.3.3
 (_**"depends upon"**_)

**Remote Links:**
- [#207 Jansi fails to start on Mac arm
](https://github.com/fusesource/jansi/issues/207)

**Backported to:** [4.0.0-alpha-2](https://github.com/apache/maven/milestone/113?closed=1)

0 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Martin Kanters](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=martinkanters), [gnodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnodet), what to do with this?

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte), is this a blocker for 4.0.0-alpha-1?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

It means that this class-check ( https://github.com/apache/maven-shared-utils/blob/master/src/main/java/org/apache/maven/shared/utils/logging/MessageUtils.java#L44-L57 ) is not enough. It seems like there's no method yet to verify if JAnsi is avialable without calling `systemInstall()` and catching the Exception.

Assuming it does work with Maven 3.8.1, I wonder why it did work with that version.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I will try 3.8.x as well this evening and let you know.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

3.8.1 still works:

```
osipovmi@deblndw024v:/tmp
$ uname -a
HP-UX deblndw0 B.11.31 U ia64 HP-UX
osipovmi@deblndw024v:/tmp
$ apache-maven-3.8.1/bin/mvn -v
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /tmp/apache-maven-3.8.1
Java version: 11.0.4, vendor: Hewlett Packard Enterprise, runtime: /opt/java11
Default locale: de_DE, platform encoding: UTF8
OS name: "hp-ux", version: "b.11.31", arch: "ia64n", family: "unix"
osipovmi@deblndw024v:/tmp
$ unset JAVA_HOME
osipovmi@deblndw024v:/tmp
$ apache-maven-3.8.1/bin/mvn -v
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /tmp/apache-maven-3.8.1
Java version: 1.8.0.21-hp-ux, vendor: Hewlett Packard Enterprise, runtime: /opt/java8/jre
Default locale: de_DE, platform encoding: UTF8
OS name: "hp-ux", version: "b.11.31", arch: "ia64n", family: "unix"
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Looking at the Maven code, I see no differences. It looks like this regression is caused by a change in JAnsi.
This is important enough for me to delay the release of 4.0.0-alpha-1, as it might result in a lot of negative experiences.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I agree.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

[#207](https://github.com/fusesource/jansi/issues/207) is exactly the same error.
https://github.com/fusesource/jansi/blob/jansi-2.3.2/src/main/java/org/fusesource/jansi/AnsiConsole.java#L239-L250 shows a line using CLibrary which should probably be in the catch of the next try/catch block, based on the comment.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [371faf7a49298bd1752632c2675aa499fee64667](https://gitbox.apache.org/repos/asf?p=maven.git;a=commit;h=371faf7a49298bd1752632c2675aa499fee64667)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I can confirm now that this issue is fixed.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin) thanks for your feedback. Just to be sure: you don't see these issues with Maven 3.8.1?
The libs/jansi-native are extracted from the jansi jar by https://github.com/apache/maven/blob/master/apache-maven/src/assembly/maven/component.xml#L66-L73. Either [gnodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnodet) or [Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy) needs to verify this, maybe these lines can be removed.
I do remember we explicitly extracted them, otherwise JAnsi would do it, always creating temp files (without removing them).

**Comment by jira-importer** [comment]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** commented

3.8.1 works fine without any warnings and also the warning vanish from 4.0.0-alpha1 SNAPSHOT once I remove the folder `lib/jansi-native`.

I think GateKeeper prevents loading binaries downloaded from a browser (https://support.blackfire.io/en/articles/3669492-issues-with-macos-catalina).
I don't know why the temp files extracted from the JAR on demand don't suffer from that issue.

But it seems the issue with orphaned tmp files has been solved meanwhile https://github.com/fusesource/jansi/issues/98.

In any case the binaries are not signed at all.

```
codesign -vvvv /Users/konradwindszus/Downloads/apache-maven/lib/jansi-native/Mac/x86_64/libjansi.jnilib
/Users/konradwindszus/Downloads/apache-maven/lib/jansi-native/Mac/x86_64/libjansi.jnilib: code object is not signed at all
In architecture: x86_64

xattr /Users/konradwindszus/Downloads/apache-maven/lib/jansi-native/Mac/x86_64/libjansi.jnilib
com.apple.quarantine

xattr /Users/konradwindszus/Downloads/apache-maven/lib/jansi-2.3.3.jar
com.apple.quarantine
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

The exploaded directory must stay.

**Comment by jira-importer** [comment]
**[Konrad Windszus](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kwin)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) I was trying to provide constructive feedback in the context of this issue, as to me it seemed related. Do whatever you want with that. I don't invest more time in it just to get harsh reactions...
