### ISSUE TITLE
[MNG-7124] java.lang.NullPointerException at org.apache.maven.cli.MavenCliTest.testStyleColors(MavenCliTest.java:327)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8322]
**[Ivan Serdyuk](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oceanfish81)** opened **[MNG-7124](https://issues.apache.org/jira/browse/MNG-7124?redirect=false)** and commented

I was trying to build Maven's version

??$ git log -1??
??commit 3e656376e8271d839c99de3d0ae2746c593e7daa (HEAD -> master, origin/master, origin/HEAD)??
??Author: rfscholte <rfscholte@apache.org>??
??Date: Sun Mar 21 17:40:31 2021 +0100??

with

??$ mvn --version??
??Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)??
??Maven home: /home/oceanfish81/apache-maven-3.6.3??
??Java version: 16-ea, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-16-openj9-arm64??
??Default locale: en_US, platform encoding: UTF-8??
??OS name: "linux", version: "5.4.0-40-generic", arch: "aarch64", family: "unix"??

and this error:

??[INFO] -------------------------------------------------------??

??[INFO] -------------------------------------------------------??

??[INFO]  T E S T S??

??[INFO] -------------------------------------------------------??

??[INFO] Running org.apache.maven.cli.event.ExecutionEventLoggerTest??

??[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.587 s - in org.apache.maven.cli.event.ExecutionEventLoggerTest??

??[INFO] Running org.apache.maven.cli.CLIReportingUtilsTest??

??[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.maven.cli.CLIReportingUtilsTest??

??[INFO] Running org.apache.maven.cli.CleanArgumentTest??

??[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.maven.cli.CleanArgumentTest??

??[INFO] Running org.apache.maven.cli.CLIManagerTest??

??[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 s - in org.apache.maven.cli.CLIManagerTest??

??[INFO] Running org.apache.maven.cli.MavenCliTest??

??[ERROR] Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.329 s <<< FAILURE! - in org.apache.maven.cli.MavenCliTest??

??[ERROR] testStyleColors  Time elapsed: 0.036 s  <<< ERROR!java.lang.NullPointerException at org.apache.maven.cli.MavenCliTest.testStyleColors(MavenCliTest.java:327)??
??[INFO] Running org.apache.maven.cli.CLIManagerDocumentationTest??

??[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.maven.cli.CLIManagerDocumentationTest??

??[INFO] Running org.apache.maven.cli.transfer.FileSizeFormatTest??

??[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 s - in org.apache.maven.cli.transfer.FileSizeFormatTest??

??[INFO] ??

??[INFO] Results:??

??[INFO] ??

??[ERROR] Errors:??

?? [ERROR]   MavenCliTest.testStyleColors:327 » NullPointer??

??[INFO] ??

??[ERROR] Tests run: 30, Failures: 0, Errors: 1, Skipped: 0??

---

**Affects:** 3.0-alpha-1

**Issue Links:**
- [MNG-7127](https://issues.apache.org/jira/browse/MNG-7127) NullPointerException in MavenCliTest.testStyleColors in JDK 16
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Ivan Serdyuk](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=oceanfish81)** commented

I am targeting Aarch64 ports of OpenJ9.

 

Let me know if I could do more, to track the cause of this.
