### ISSUE TITLE
[MNG-7096] Maven master and m-shade-p 3.2.1 hangs forever

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8357]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** opened **[MNG-7096](https://issues.apache.org/jira/browse/MNG-7096?redirect=false)** and commented

A fairly huge build, works okay with Maven 3.6.3, but with Maven 4.0.0-alpha-1-SNAPSHOT (ab20190a1a9fecdc8f85b40e8d03d806f3da4fc6) hangs forever at maven-shade-plugin:3.2.1 shade:shade goal.

Env

```
$ ~/bin/maven/apache-maven-4.0.0-alpha-1-SNAPSHOT/bin/mvn -v
Apache Maven 4.0.0-alpha-1-SNAPSHOT (ab20190a1a9fecdc8f85b40e8d03d806f3da4fc6)
Maven home: /home/cstamas/bin/maven/apache-maven-4.0.0-alpha-1-SNAPSHOT
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.8.0-43-generic", arch: "amd64", family: "unix"
```

JStack shows this:

`"main" #1 prio=5 os_prio=0 tid=0x00007fa84000b000 nid=0x9846 runnable [0x00007fa84634d000]"main" #1 prio=5 os_prio=0 tid=0x00007fa84000b000 nid=0x9846 runnable [0x00007fa84634d000]   java.lang.Thread.State: RUNNABLE at org.jdom2.output.support.AbstractFormattedWalker.next(AbstractFormattedWalker.java:465) at org.jdom2.output.support.AbstractXMLOutputProcessor.printContent(AbstractXMLOutputProcessor.java:925) at org.jdom2.output.support.AbstractXMLOutputProcessor.printElement(AbstractXMLOutputProcessor.java:868) at org.jdom2.output.support.AbstractXMLOutputProcessor.printContent(AbstractXMLOutputProcessor.java:946) at org.jdom2.output.support.AbstractXMLOutputProcessor.printElement(AbstractXMLOutputProcessor.java:868) at org.jdom2.output.support.AbstractXMLOutputProcessor.printContent(AbstractXMLOutputProcessor.java:946) at org.jdom2.output.support.AbstractXMLOutputProcessor.printElement(AbstractXMLOutputProcessor.java:868) at org.jdom2.output.support.AbstractXMLOutputProcessor.printContent(AbstractXMLOutputProcessor.java:946) at org.jdom2.output.support.AbstractXMLOutputProcessor.printElement(AbstractXMLOutputProcessor.java:868) at org.jdom2.output.support.AbstractXMLOutputProcessor.printContent(AbstractXMLOutputProcessor.java:946) at org.jdom2.output.support.AbstractXMLOutputProcessor.printElement(AbstractXMLOutputProcessor.java:868) at org.jdom2.output.support.AbstractXMLOutputProcessor.printDocument(AbstractXMLOutputProcessor.java:533) at org.jdom2.output.support.AbstractXMLOutputProcessor.process(AbstractXMLOutputProcessor.java:191) at org.jdom2.output.XMLOutputter.output(XMLOutputter.java:822) at org.apache.maven.plugins.shade.pom.MavenJDOMWriter.write(MavenJDOMWriter.java:2159) at org.apache.maven.plugins.shade.pom.PomWriter.write(PomWriter.java:75) at org.apache.maven.plugins.shade.mojo.ShadeMojo.rewriteDependencyReducedPomIfWeHaveReduction(ShadeMojo.java:1049) at org.apache.maven.plugins.shade.mojo.ShadeMojo.createDependencyReducedPom(ShadeMojo.java:978) at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:538) at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:136) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:151) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:115) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:79) at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:64) at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:131) at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:338) at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:217) at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:130) at org.apache.maven.cli.MavenCli.execute(MavenCli.java:980) at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:294) at org.apache.maven.cli.MavenCli.main(MavenCli.java:198) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282) at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225) at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406) at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)`

---

**Affects:** 4.0.x-candidate

**Issue Links:**
- [MSHADE-413](https://issues.apache.org/jira/browse/MSHADE-413) Maven shade plugin enters endless loop

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Tried with m-shade-p 3.2.4 (latest), and got similar behavior but a bit different stack:

"main" #1 prio=5 os_prio=0 tid=0x00007f073800b000 nid=0xdc12 runnable [0x00007f073f63c000]"main" #1 prio=5 os_prio=0 tid=0x00007f073800b000 nid=0xdc12 runnable [0x00007f073f63c000]   java.lang.Thread.State: RUNNABLE at org.jdom2.Text.getTextTrim(Text.java:132) at org.apache.maven.plugins.shade.pom.MavenJDOMWriter.insertAtPreferredLocation(MavenJDOMWriter.java:277) at org.apache.maven.plugins.shade.pom.MavenJDOMWriter.iterateExclusion(MavenJDOMWriter.java:492) at org.apache.maven.plugins.shade.pom.MavenJDOMWriter.updateDependency(MavenJDOMWriter.java:1339) at org.apache.maven.plugins.shade.pom.MavenJDOMWriter.iterateDependency(MavenJDOMWriter.java:390) at org.apache.maven.plugins.shade.pom.MavenJDOMWriter.updateModel(MavenJDOMWriter.java:1628) at org.apache.maven.plugins.shade.pom.MavenJDOMWriter.write(MavenJDOMWriter.java:2164) at org.apache.maven.plugins.shade.pom.PomWriter.write(PomWriter.java:75) at org.apache.maven.plugins.shade.mojo.ShadeMojo.rewriteDependencyReducedPomIfWeHaveReduction(ShadeMojo.java:1169) at org.apache.maven.plugins.shade.mojo.ShadeMojo.createDependencyReducedPom(ShadeMojo.java:1098) at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:599) at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:136) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159) at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:151) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:115) at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:79) at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:64) at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:131) at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:338) at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:217) at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:130) at org.apache.maven.cli.MavenCli.execute(MavenCli.java:980) at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:294) at org.apache.maven.cli.MavenCli.main(MavenCli.java:198) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282) at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225) at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406) at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

There is a similar issue regarding shading JUnit 5.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas), can you verify again?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas), ping!

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Will try today later with latest alpha snapshot on same build...
