### ISSUE TITLE
[MNG-6598] Maven 3.6.0 and Surefire problem

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8435]
**[Lars Borup Jensen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lborupj)** opened **[MNG-6598](https://issues.apache.org/jira/browse/MNG-6598?redirect=false)** and commented

We've been using 3.5.2 for a longer period of time and just recently upgraded to 3.6.0 and then the problems started.

First we experienced way longer build times when running the absolutely same build in 3.6.0 than 3.5.2. Using -B when running locally does seem to improve build time but still not quite the same.

The main issue and one that is really causing us headaches is that Surefire 2.22.0 suddently started failing to create forks when running tests - setting forkCount does help on this, but then we come back to the above mentioned problem: build time, which then becomes painfully slow. 

So our discovery is: same source, same POM (same versions of plugins etc) fails to build on 3.6.0 but works on 3.5.2 (and even faster) - do you have any pointers for us, what to look for?

Stacktrace from Maven

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project myproj: There are test failures.
[ERROR]
[ERROR] Please refer to C:\projects\myproj\proj\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\tools\oracle\jdk\1.8.0_192\jre\bin\java -javaagent:C:\\tools\\apache\\maven\\m2repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=C:\\projects\\myproj\\proj\\target\\jacoco.exec,append=true,excludes=*_javassist_*:**/com/**/*:**/dk/company/schemas/**/*:**/dk/oio/**/*:**/net/companynet/**/*:**/dk/othercompany/**/*:**/dk/othercompany/integration/**/*:**/dk/company/stub/**/* -jar C:\Users\someuser\AppData\Local\Temp\surefire1255787583870225582\surefirebooter6297886391209366508.jar C:\Users\someuser\AppData\Local\Temp\surefire1255787583870225582 2019-02-22T09-01-49_197-jvmRun1 surefire7364437855153295156tmp surefire_13521419335267356208tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] dk.company.proj.persistence.RepositoryTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "C:\tools\oracle\jdk\1.8.0_192\jre\bin\java -javaagent:C:\\tools\\apache\\maven\\m2repository\\org\\jacoco\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=C:\\projects\\myproj\\proj\\target\\jacoco.exec,append=true,excludes=*_javassist_*:**/com/**/*:**/dk/company/schemas/**/*:**/dk/oio/**/*:**/net/companynet/**/*:**/dk/othercompany/**/*:**/dk/othercompany/integration/**/*:**/dk/company/stub/**/* -jar C:\Users\someuser\AppData\Local\Temp\surefire1255787583870225582\surefirebooter6297886391209366508.jar C:\Users\someuser\AppData\Local\Temp\surefire1255787583870225582 2019-02-22T09-01-49_197-jvmRun1 surefire7364437855153295156tmp surefire_13521419335267356208tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] dk.company.proj.persistence.RepositoryTest
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
```

 

---

**Affects:** 3.6.0

**Issue Links:**
- [MNG-6900](https://issues.apache.org/jira/browse/MNG-6900) Upgrade Jansi to 1.18
 (_**"depends upon"**_)
- [MNG-7179](https://issues.apache.org/jira/browse/MNG-7179) Upgrade Jansi to 2.3.3
 (_**"depends upon"**_)

**Backported to:** [4.0.0-alpha-2](https://github.com/apache/maven/milestone/113?closed=1), [3.8.2](https://github.com/apache/maven/milestone/103?closed=1)

0 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

That's great news. Do you think you could bisect JAnsi too to give us a change to fix that?
[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy), that is an iteresting case for you.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

"interesting"... issues with JAnsi native  library on Windows is really not fun...
https://github.com/fusesource/jansi/blob/master/changelog.md

I added a diagnostic for Jansi (run "java -jar jansi.jar") since 1.17, but it is not available in 1.16, then 1.16 was really a pain to test outside any integration.
Perhaps I should prepare a 1.16 branch to integrate just the diagnostic code, so it's easier to compare how the library works

I know that with the diagnostic, every time I launch on Windows, I see that the link with the native library takes "some time": but I don't know if it was as long in 1.16.
Ready to work together on testing?

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

I just published 1.16.x branch with diagnostic merged: https://github.com/fusesource/jansi/tree/1.16.x
can you build it for yourself?

then please test if "java -jar jansi-*.jar" gives you a visible difference between 1.16.1-SNAPSHOT and 1.17 then report here...

**Comment by jira-importer** [comment]
**[Lars Borup Jensen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lborupj)** commented

Thanks alot, [Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy) and [Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) . I cloned your 1.16.x repo and build it locally and compared it against the maven 3.6.0 version (1.17.1) and even though I did feel like I saw a difference, it was very minor so I added a small test to the AnsiMain class like this 

```java
private static void perfTestAnsi(boolean stderr) {
 @SuppressWarnings( "resource" )
 PrintStream s = stderr ? System.err : System.out;
 long startTime = System.currentTimeMillis();
 for (int i=0;i<1000;i++) {
 for(Ansi.Color c: Ansi.Color.values()) {
 s.print(" " + ansi().bold().fg(c) + c + ansi().reset());
 }
 s.println();
 }
 long endTime = System.currentTimeMillis();
 System.out.println("Total time " + (endTime - startTime) + "ms");
 }
```

 

and added the call to the try-catch block

 

```java
testAnsi(false);
 testAnsi(true);
 perfTestAnsi(false);
if (args.length == 0) {
 
```

 

and here are the numbers

 

Jansi-1.16.1 Run#1 3364ms
Jansi-1.16.1 Run#2 3415ms
Jansi-1.16.1 Run#3 3065ms
Jansi-1.16.1 Run#4 3357ms
Jansi-1.16.1 Run#5 3125ms

Jansi-1.18-SNAPSHOT Run#1 5488ms
Jansi-1.18-SNAPSHOT Run#2 6687ms
Jansi-1.18-SNAPSHOT Run#3 7095ms
Jansi-1.18-SNAPSHOT Run#4 6385ms
Jansi-1.18-SNAPSHOT Run#5 5697ms

 

1.16.1 is the new branch you created, Hervé - and Jansi 1.18-SNAPSHOT is just current master and as you can see for 1000 lines there are notifceable performance differences and many of our builds output many many more lines than one thousand. I cannot tell if it is in the native part or the java-part.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

great news that this AnsiMain helps digging into Jansi questionning without being polluted by any integration into any (complex) tool

if you're convinced that this Jansi throughput test performance is relevant, measuring the perf without Jansi before measuring it with Jansi could be useful, to see Jansi overhead.

On explaining the difference, between Jansi 1.16 and 1.17, the internal of Jansi completely changed to better manage encoding: it's the addition of PrintStream based implementation in https://github.com/fusesource/jansi/commit/d340856e78925269ecc76cd16c29850fa9ca01e0
what you can test is the difference of performance of the old OutputStream returned by AnsiConsole.wrapOutputStream(...) vs the performance of the new AnsiConsole.wrapSystemOut(...): if the difference in performance is visible in 1.18-SNAPSHOT, we'll know that this is the right place to improve

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

notice: this discussion about Jansi performance would perhaps better be logged in Jansi issue tracking...

**Comment by jira-importer** [comment]
**[Claus Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clausfod)** commented

If you replace Jansi 1.17.1 with Jansi 1.18 or Jansi 1.19 the problem reported here will be fixed. Any plans on upgrading Jansi for Maven 3.6.x ?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Is that a confirmation? If yes, we can target a Jansi update for 3.7.0 which will implicitly fix this issue too. No changes planned for 3.6.x.

**Comment by jira-importer** [comment]
**[Claus Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clausfod)** commented

Yes - it's a confirmation. I have replaced the Jansi library manually on 3.6.3 with both 1.18 and 1.19 and the problem described in this ticket then disappear. (I work together with the reporter Lars Borup)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Claus Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clausfod), I have uploaded branch MNG-6900. Can you kindly build Maven from that and reconfirm your observations with that?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Claus Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clausfod), can you confirm?

**Comment by jira-importer** [comment]
**[Claus Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clausfod)** commented

I guess I need some instructions on how to build Maven from source and use it locally to confirm. Is it just as simple as running a mvn clean package on the branch?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Correct, build as usual, extract and run.

**Comment by jira-importer** [comment]
**[Claus Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clausfod)** commented

I have checked out the branch MNG-6900 and I ran this command:
mvn -DdistributionTargetDir="c:/projects/maven/target/apache-maven-3.7.x-SNAPSHOT" clean package

The build produced this error:

```
[INFO] Apache Maven ....................................... SUCCESS [ 38.799 s]
[INFO] Maven Model ........................................ SUCCESS [ 40.950 s]
[INFO] Maven Artifact ..................................... SUCCESS [  7.900 s]
[INFO] Maven Plugin API ................................... FAILURE [  3.797 s]
[INFO] Maven Builder Support .............................. SKIPPED
[INFO] Maven Model Builder ................................ SKIPPED
[INFO] Maven Settings ..................................... SKIPPED
[INFO] Maven Settings Builder ............................. SKIPPED
[INFO] Maven Repository Metadata Model .................... SKIPPED
[INFO] Maven Artifact Resolver Provider ................... SKIPPED
[INFO] Maven Core ......................................... SKIPPED
[INFO] Maven SLF4J Wrapper ................................ SKIPPED
[INFO] Maven SLF4J Simple Provider ........................ SKIPPED
[INFO] Maven Embedder ..................................... SKIPPED
[INFO] Maven Compat ....................................... SKIPPED
[INFO] Apache Maven Distribution .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:32 min
[INFO] Finished at: 2020-05-26T13:09:03+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (rat-check) on project maven-plugin-api: Too many files with unapproved license: 1 See RAT report in: C:\projects\maven\maven-plugin-api\target\rat.txt -> [Help 1]

[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :maven-plugin-api
```

Something i'm missing ?

**Comment by jira-importer** [comment]
**[Claus Nielsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clausfod)** commented

Yes - I can confirm that the MNG-6900 branch fixes this issue :-)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Fixed with Jansi upgrade.
