### ISSUE TITLE
[MNG-6737] StackOverflowError when version ranges are unsolvable and graph contains a cycle

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8520]
**[Tomo Suzuki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=suztomo)** opened **[MNG-6737](https://issues.apache.org/jira/browse/MNG-6737?redirect=false)** and commented

Maven throws StackOverflowError when version ranges are unsolvable and the dependency graph contains a cycle.

```java
$ mvn install
...
[INFO] --------------------------< suztomo:module-c >--------------------------
[INFO] Building module-c 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.406 s
[INFO] Finished at: 2019-08-16T12:10:30-04:00
[INFO] ------------------------------------------------------------------------
...
Exception in thread "main" java.lang.StackOverflowError
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:341)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
	at org.eclipse.aether.graph.DefaultDependencyNode.accept(DefaultDependencyNode.java:345)
...(omitting many lines)...
 
```

# Example 

Example project to reproduce the issue:  https://github.com/suztomo/maven-cyclic-dependency-with-range 

# Diagnosis

In the example above, because of a version conflict on grpc-core (1.21.0 v.s. 1.16.1), [org.eclipse.aether.util.graph.transformer.NearestVersionSelector.newFailure](https://github.com/apache/maven-resolver/blob/maven-resolver-1.4.0/maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/NearestVersionSelector.java#L158) tries to throw UnsolvableVersionConflictExceptoin. However, before throwing the exception PathRecordingDependencyVisitor visits nodes in the dependency graph and the graph contains a cycle. The visitor goes to infinite recursion in visiting the cyclic path, resulting in StackOverflowError.

 

```java
private UnsolvableVersionConflictException newFailure( final ConflictContext context )
{
 ...
 PathRecordingDependencyVisitor visitor = new PathRecordingDependencyVisitor( filter );
 context.getRoot().accept( visitor );
 return new UnsolvableVersionConflictException( visitor.getPaths() );
}
```

 

The cycle in the graph consists of module-a and module-b as illustrated below:

```java
module-c:1.0.0
+- module-b:2.0.0
 +- module-a:1.0.0
 +- module-b:0.0.1
 +- module-b:1.0.0
 | +- module-a:1.0.0
 | +- module-b:0.0.1
 | +- module-b:1.0.0
   ...
```

 

---

**Affects:** 3.6.1

**Issue Links:**
- [MRESOLVER-38](https://issues.apache.org/jira/browse/MRESOLVER-38) SOE/OOME in DefaultDependencyNode.accept

- [MRESOLVER-93](https://issues.apache.org/jira/browse/MRESOLVER-93) PathRecordingDependencyVisitor to handle 3 cycles

- [MNG-6672](https://issues.apache.org/jira/browse/MNG-6672) Upgrade Maven Resolver to 1.4.2
 (_**"depends upon"**_)

**Backported to:** [4.0.0-alpha-2](https://github.com/apache/maven/milestone/113?closed=1), [3.8.2](https://github.com/apache/maven/milestone/103?closed=1)

2 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Tomo Suzuki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=suztomo)** commented

My memo: PathRecordingDependencyVisitor has logic to prevent visiting nodes that already visited. Why didn't this work?

https://github.com/apache/maven-resolver/blob/47edcfe/maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/visitor/PathRecordingDependencyVisitor.java#L121

**Comment by jira-importer** [comment]
**[Tomo Suzuki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=suztomo)** commented

I was able to create a test case in PathRecordingDependencyVisitorTest https://github.com/apache/maven-resolver/commit/3e6eb7842727d6af28af27e79f82cb1ed1808031

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

With Maven Resolver 1.4.2 this now correctly exits with:

```
[INFO]
[INFO] --------------------------< suztomo:module-c >--------------------------
[INFO] Building module-c 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.401 s
[INFO] Finished at: 2020-04-27T13:52:52+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project module-c: Could not resolve dependencies for project suztomo:module-c:jar:1.0.0: Failed to collect dependencies for suztomo:module-c:jar:1.0.0: Could not resolve version conflict among [io.grpc:grpc-netty-shaded:jar:1.21.0 -> io.grpc:grpc-core:jar:[1.21.0,1.21.0], io.grpc:grpc-netty:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1]] -> [Help 1]
```

I will close this as soon as MNG-6672 is resolved.

**Comment by jira-importer** [comment]
**[Tomo Suzuki](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=suztomo)** commented

Thank you.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

MNG-6672 has been resolved, so has this issue.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Implicitly fixed in `maven-3.8.x` branch because it contains Resolver 1.6.2.

**Comment by jira-importer** [comment]
**[Henrik Rueping](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=henrikrueping)** commented

I seem to still run into this problem. It happens when I want to find the transitive Dependencies of the ArtifactI seem to still run into this problem. It happens when I want to find the transitive Dependencies of the Artifact
org.webjars.npm:babel-core:6.0.16

(even if I just add it to Eclipse as a dependency, it crushes Eclipse if I want to see the dependency hierarchy).In java itself, I encounter the Stacktrace:

 

```java
Thread [main] (Suspended) Stack<E>.get(int) line: 75
 AbstractList$Itr.next() line: 358 Stack<E>(AbstractCollection<E>).contains(Object) line: 106 PathRecordingDependencyVisitor.visitEnter(DependencyNode) line: 99 DefaultDependencyNode.accept(DependencyVisitor) line: 343
 DefaultDependencyNode.accept(DependencyVisitor) line: 347 
(... omitted many Repititions...)
DefaultDependencyNode.accept(DependencyVisitor) line: 347 NearestVersionSelector.newFailure(ConflictResolver$ConflictContext) line: 158 NearestVersionSelector.backtrack(NearestVersionSelector$ConflictGroup, ConflictResolver$ConflictContext) line: 120 NearestVersionSelector.selectVersion(ConflictResolver$ConflictContext) line: 93 ConflictResolver.transformGraph(DependencyNode, DependencyGraphTransformationContext) line: 180 
ChainedDependencyGraphTransformer.transformGraph(DependencyNode, DependencyGraphTransformationContext) line: 80
DefaultDependencyCollector.collectDependencies(RepositorySystemSession, CollectRequest) line: 273 DefaultRepositorySystem.collectDependencies(RepositorySystemSession, CollectRequest) line: 284     
(..ommitted own code...)
```

I used:
org.apache.maven:maven-resolver-provider:3.8.1
org.apache.maven.resolver:maven-resolver-util:1.6.2

I used ArtifactDescriptorPolicy.STRICT (maybe this setting makes a difference).

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[HenrikRueping](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=HenrikRueping), please create a seperate ticket.
