### ISSUE TITLE
[MNG-6643] Version comparison CLI does not work anymore

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8582]
**[Benoit GUERIN](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bguerin)** opened **[MNG-6643](https://issues.apache.org/jira/browse/MNG-6643?redirect=false)** and commented

Since 3.6.1, comparison CLI does not work :

```java
$ java -jar apache-maven-3.6.1/lib/maven-artifact-3.6.1.jar 5.32 5.27
Display parameters as parsed by Maven (in canonical form) and comparison result:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
at org.apache.maven.artifact.versioning.ComparableVersion.stripLeadingZeroes(ComparableVersion.java:612)
at org.apache.maven.artifact.versioning.ComparableVersion.parseItem(ComparableVersion.java:594)
at org.apache.maven.artifact.versioning.ComparableVersion.parseVersion(ComparableVersion.java:529)
at org.apache.maven.artifact.versioning.ComparableVersion.<init>(ComparableVersion.java:496)
at org.apache.maven.artifact.versioning.ComparableVersion.main(ComparableVersion.java:679)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 5 more
```

 

---

**Affects:** 3.6.1

**Issue Links:**
- [MNG-6572](https://issues.apache.org/jira/browse/MNG-6572) use int or long instead of BigIntegers for little numbers in ComparableVersion
 (_**"is caused by"**_)

1 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Done in [80c6fe3a01aac53c083f1ae21375e305f3ff7dcb](https://gitbox.apache.org/repos/asf?p=maven.git;a=commitdiff;h=80c6fe3a01aac53c083f1ae21375e305f3ff7dcb)

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

can we find a way to check that in the future, no dependency is added like this happened here?
