### ISSUE TITLE
[MNG-6618] Maven doesn't export org.slf4j.event.Level

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8595]
**[Viacheslav Yakunin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=viacheslav.yakunin)** opened **[MNG-6618](https://issues.apache.org/jira/browse/MNG-6618?redirect=false)** and commented

Hi, this is the same issue as [MNG-6360](https://issues.apache.org/jira/browse/MNG-6360). Unfortunately I was not able to reopen it so I am creating new one.

I was able to reproduce it when I tried to create maven plugin for running kafka broker during integration tests. Kafka refers to org.slf4j.event.Level and this causes following exception during plugin execution.

```java
[ERROR] [KafkaServer id=1] Fatal error during KafkaServer shutdown.
java.lang.NoClassDefFoundError: org/slf4j/event/Level
                at kafka.utils.CoreUtils$.swallow$default$3(CoreUtils.scala:84)
                at kafka.server.KafkaServer.shutdown(KafkaServer.scala:567)
                at net.sla.buildtools.kafka.maven.plugin.SingletonLauncher.stop(SingletonLauncher.java:73)
                at net.sla.buildtools.kafka.maven.plugin.StopKafkaBrokerMojo.execute(StopKafkaBrokerMojo.java:18)
                at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
                at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
                at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
                at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
                at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
                at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
                at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
                at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
                at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
                at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
                at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
                at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
                at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
                at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:65)
Caused by: java.lang.ClassNotFoundException: org.slf4j.event.Level
                at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
                at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
                at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
                at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
                ... 32 more

```

---

**Affects:** 3.6.0

**Issue Links:**
- [MNG-5842](https://issues.apache.org/jira/browse/MNG-5842) java.lang.NoClassDefFoundError: org/slf4j/helpers/MessageFormatter with jetty plugin

- [MNG-6360](https://issues.apache.org/jira/browse/MNG-6360) Maven doesn't export org.slf4j.event.Level

0 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Viacheslav Yakunin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=viacheslav.yakunin)** commented

Linking to original one

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

What is your proposal to fix that?

**Comment by jira-importer** [comment]
**[Viacheslav Yakunin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=viacheslav.yakunin)** commented

it may be the same as was for MNG-6360, export package org.slf4j.event.*

https://github.com/apache/maven/pull/157/files

But I am not able to assess the impact of the change (

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

It looks good to me, it's the last package from slf4j-api not exported. [Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o) can we add fox for that to 3.6.1?

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

If all ITs pass, I am good to merge it into 3.6.1 from my POV.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

All existing ITs have gone well, but we do not have much that covers slf4j.

[Viacheslav Yakunin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=viacheslav.yakunin) please check and confirm if Maven build from branch https://github.com/apache/maven/tree/MNG-6618

You can also try to use artifacts from our CI: https://builds.apache.org/view/M-R/view/Maven/job/maven-box/job/maven/job/MNG-6618/1/artifact/org/apache/maven/apache-maven/3.6.1-SNAPSHOT/

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz), let's merge it and see what happens. I guess it was proven to work earlier. Karl wants to continue on the release.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

Fixed with [0ba5753c17a37b96a42df39a197e1c607a224b4d](https://gitbox.apache.org/repos/asf?p=maven.git;a=commit;h=0ba5753c17a37b96a42df39a197e1c607a224b4d)

**Comment by jira-importer** [comment]
**[Viacheslav Yakunin](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=viacheslav.yakunin)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o), [Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz), I checked and it is working. Thanks a lot for fast fix, I appreciate!

**Comment by jira-importer** [comment]
**[Didier Loiseau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=didier%20loiseau)** commented

This was basically the same issue as MNG-5842 but for `org.slf4j.event` instead of `org.slf4j.helpers`.

Related SO question: https://stackoverflow.com/q/53757567/525036

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Didier Loiseau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Didier%20Loiseau), is there anything else we need to do? If yes, create a new issue and a PR. I will review and merge it.

**Comment by jira-importer** [comment]
**[Didier Loiseau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=didier%20loiseau)** commented

[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o), no, 3.6.1 works for us, thanks :) I only wanted to link issues together and the SO question for future reference.
