### ISSUE TITLE
[MNG-7663] The local ArtifactRepository is broken when using enhanced local repo

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8789]
**[Guillaume Nodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnt)** opened **[MNG-7663](https://issues.apache.org/jira/browse/MNG-7663?redirect=false)** and commented

This happens when using split repositories with maven resolver 1.9.x.
This breaks the flatten-maven-plugin for example.

The reason is that maven injects a `org.apache.maven.artifact.repository.ArtifactRepository` instance for the `{}${localRepository{`}} which is the same than the one available from `MavenExecutionRequest.getLocalRepository()` .  

Unfortunately those objects do not wrap the maven resolver local repository implementation and the layout is hardcoded.  The actual implementation is created by https://github.com/apache/maven/blob/maven-3.9.x/maven-core/src/main/java/org/apache/maven/bridge/MavenRepositorySystem.java#L638

---

**Affects:** 3.9.0, 4.0.0-alpha-3

**Issue Links:**
- [MRESOLVER-322](https://issues.apache.org/jira/browse/MRESOLVER-322) Local repository split (releases/snapshots) fails with flatten-maven-plugin and imported dependencies
 (_**"causes"**_)
- [MNG-7706](https://issues.apache.org/jira/browse/MNG-7706) Deprecate ${localRepository} mojo parameter expression

**Comment by jira-importer** [comment]
**[Guillaume Nodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnt)** commented

Camel build log:

```
[INFO] Error stacktraces are turned on.
[INFO] Processing build on daemon 13c52657
[INFO] Scanning for projects...
[INFO] BuildTimeEventSpy is registered.
[INFO] 
[INFO] -----------------------< org.apache.camel:camel >-----------------------
[INFO] Building Camel 4.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- enforcer:3.0.0:enforce (enforce-maven-version) @ camel ---
[INFO] 
[INFO] --- enforcer:3.0.0:enforce (enforce-java-version) @ camel ---
[INFO] 
[INFO] --- enforcer:3.0.0:enforce (enforce-maven) @ camel ---
[INFO] 
[INFO] --- flatten:1.3.0:flatten (default-cli) @ camel ---
[INFO] Generating flattened POM of project org.apache.camel:camel:pom:4.0.0-SNAPSHOT...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.117 s
[INFO] Finished at: 2023-01-04T15:21:08+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:flatten (default-cli) on project camel: 1 problem was encountered while building the effective model for /Users/gnodet/work/git/camel/pom.xml
[ERROR] [FATAL] Non-readable POM /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom: /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom (No such file or directory) @ /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:flatten-maven-plugin:1.3.0:flatten (default-cli) on project camel: 1 problem was encountered while building the effective model for /Users/gnodet/work/git/camel/pom.xml
[FATAL] Non-readable POM /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom: /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom (No such file or directory) @ /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom

	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:341)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:324)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:77)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:60)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:132)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:306)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:228)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
	at org.apache.maven.cli.DaemonMavenCli.execute(DaemonMavenCli.java:691)
	at org.apache.maven.cli.DaemonMavenCli.doMain(DaemonMavenCli.java:233)
	at org.apache.maven.cli.DaemonMavenCli.main(DaemonMavenCli.java:209)
	at org.mvndaemon.mvnd.daemon.Server.handle(Server.java:593)
	at org.mvndaemon.mvnd.daemon.Server.client(Server.java:269)
	at org.mvndaemon.mvnd.daemon.Server.accept(Server.java:236)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.maven.plugin.MojoExecutionException: 1 problem was encountered while building the effective model for /Users/gnodet/work/git/camel/pom.xml
[FATAL] Non-readable POM /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom: /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom (No such file or directory) @ /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom

	at org.codehaus.mojo.flatten.FlattenMojo.createEffectivePom(FlattenMojo.java:986)
	at org.codehaus.mojo.flatten.FlattenMojo.createFlattenedPom(FlattenMojo.java:594)
	at org.codehaus.mojo.flatten.FlattenMojo.execute(FlattenMojo.java:422)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:336)
	... 21 common frames omitted
Caused by: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model for /Users/gnodet/work/git/camel/pom.xml
[FATAL] Non-readable POM /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom: /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom (No such file or directory) @ /Users/gnodet/.m2/erepo/org/apache/apache/29/apache-29.pom

	at org.apache.maven.model.building.DefaultModelProblemCollector.newModelBuildingException(DefaultModelProblemCollector.java:176)
	at org.apache.maven.model.building.DefaultModelBuilder.doReadFileModel(DefaultModelBuilder.java:1064)
	at org.apache.maven.model.building.DefaultModelBuilder.readFileModel(DefaultModelBuilder.java:971)
	at org.apache.maven.model.building.DefaultModelBuilder.readRawModel(DefaultModelBuilder.java:1095)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1550)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:1339)
	at org.apache.maven.model.building.DefaultModelBuilder.readEffectiveModel(DefaultModelBuilder.java:798)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:896)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:664)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:645)
	at org.codehaus.mojo.flatten.ModelBuilderThreadSafetyWorkaround.build(ModelBuilderThreadSafetyWorkaround.java:134)
	at org.codehaus.mojo.flatten.FlattenMojo.createEffectivePom(FlattenMojo.java:982)
	... 25 common frames omitted
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

In this case, the pom was downloaded and stored to `/Users/gnodet/.m2/erepo/cached/releases/central/org/apache/apache/29/apache-29.pom`

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

This is actually problem of flatten-maven-plugin and fix is provided (needs someone to pick it up) https://github.com/mojohaus/flatten-maven-plugin/pull/336
