### ISSUE TITLE
[MNG-7475] [REGRESSION] ModelBuilder API Change breaks ShrinkWrap: NoSuchMethodError in FileProfileActivator.setPathTranslator()

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#8982]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** opened **[MNG-7475](https://issues.apache.org/jira/browse/MNG-7475?redirect=false)** and commented

Maven 3.8.5 breaks [Arquillian ShrinkWrap](https://arquillian.org/modules/shrinkwrap-shrinkwrap) (and thereby, most if not all use of Red Hat/JBoss Arquillian) by changing the published public API of class org.apache.maven.model.profile.activation.FileProfileActivator:

```java
[ERROR] com.dbenergie.ndm.bnb.business.NutzungsinformationenCreateOrtungsinfoTest  Time elapsed: 0.127 s  <<< ERROR!
java.lang.NoSuchMethodError: 'org.apache.maven.model.profile.activation.FileProfileActivator org.apache.maven.model.profile.activation.FileProfileActivator.setPathTranslator(org.apache.maven.model.path.PathTranslator)'
        at org.jboss.shrinkwrap.resolver.impl.maven.internal.SettingsXmlProfileSelector.<init>(SettingsXmlProfileSelector.java:50)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.getRemoteRepositories(MavenWorkingSessionImpl.java:327)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:199)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:71)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:53)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:40)
        at org.arquillian.container.chameleon.controller.Resolver.resolve(Resolver.java:45)
        at org.arquillian.container.chameleon.ContainerLoader.load(ContainerLoader.java:36)
        at org.arquillian.container.chameleon.ChameleonConfiguration.getConfiguredAdapter(ChameleonConfiguration.java:116)
        at org.arquillian.container.chameleon.ChameleonContainer.init(ChameleonContainer.java:81)
        at org.arquillian.container.chameleon.InitiateContainer.initiateChameleon(InitiateContainer.java:69)
        at org.arquillian.container.chameleon.InitiateContainer.setup(InitiateContainer.java:38) 
```

It seems that method

```java
public FileProfileActivator setPathTranslator( PathTranslator pathTranslator ) 
```

as well as the class of its argument - has been refactored/renamed to

```java
public FileProfileActivator setProfileActivationFilePathInterpolator( ProfileActivationFilePathInterpolator profileActivationFilePathInterpolator ) 
```

While the new name might be regarded as more stylish and/or even more appropriate, unfortunately, this results in an incompatible change of a publicly documented API:

https://maven.apache.org/ref/3.8.4/maven-model-builder/apidocs/org/apache/maven/model/profile/activation/FileProfileActivator.html

https://maven.apache.org/ref/3.8.5/maven-model-builder/apidocs/org/apache/maven/model/profile/activation/FileProfileActivator.html

Therefore, please revert this change - it clearly breaks some valuable dependent software (which unfortunately is no longer maintained by RedHat)...

Many thanks in advance! :)

 

---

**Affects:** 3.8.5

**Attachments:**
- [arquillian-reproducer.zip](https://issues.apache.org/jira/secure/attachment/13043656/arquillian-reproducer.zip) (_7.63 kB_)

**Remote Links:**
- [GitHub Pull Request #738
](https://github.com/apache/maven/pull/738)

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Okay, let's fix this in 3.8.6, and make it work. Of course, I will deprecate the returned setter as well, with notice, that it is about to be removed in 3.9.x and later (so this will be only 3.8.5 change, and given 3.8.6 is last planned of 3.8.x line, that's it).  Still, given this is as you say unmaintained software, that is doing it wrong from beginning as we assessed here, this is the price of the decision made in past: it will not work with 3.9.x line, nor Maven 4... We have to move forward, and we do not have resources nor time to make sure all (unintended) uses of classes from maven will work. In case of any question, there is Mailing List where we are glad to answer questions, and help write more durable, robust code that integrates with Maven in well manner.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Eh, this is just getting worse... I just spotted this class (added in 2010): https://github.com/apache/maven/blob/4bc349170646a8e461e434cdfa29d913a757babc/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilderFactory.java

Is not used by Maven at runtime (only when Maven integrated into something when no Sisu available, hence via ServiceLocator or Guice module), and it's Javadoc nicely explains the intent of this class: so, if RH developers did not want to use Plexus/Sisu, this should have been used instead, so another alternative that was missed.

Problem with "deprecate forever" is that it only introduces impediments (for us, Maven developers), and given the huge legacy trail, plus all these as well, just makes near impossible to improve, move forward. In this very case, we would end up with single class, that would work in two very distinct way: if it is container constructed, then do the "fixed" work, but if manually constructed using setter (alas setter sets an object not suitable for "proper way of working"), them we need to retain broken way of working. In short, this class would be a big IF block, separating logic "if manually constructed" and "if container constructed".

Some mutant class like this: https://github.com/apache/maven/pull/738

But, let's see what you can do: could you try creating a "patch" JAR, that would contain only the FileProfileActivator class from Maven 3.8.4, and add that "patch jar" to plugin dependency? IMPORTANT: use your own coordinates, do NOT use any org.apache.maven etc coordinates for patch jar...

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

Just to make sure I got the idea properly:

You mean that I should prepend a JAR, containing nothing but the FileProfileActivator class from Maven 3.8.4, to the normal classpath consisting of Maven 3.8.5, so basically patching this single class & replacing its 3.8.5 by the 3.8.4 version?

I can do so later this evening - I'll be away from my desk for ~4 hours now...

Many thanks so far for your kind help and openness to find some way that does not completely leave us behind, requiring to use Arquillian/ShrinkWrap...

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Nope, this is the idea:

Create a JAR that contains only this one single class:

org.apache.maven.model.profile.activation.FileProfileActivator.class

And that class should originate from Maven 3.8.4. Deploy that class to your local Repository Manager (or for test sake, is okay only to "install" it into your local repository). Let's assume you deployed it on org.foo.bar:my-maven-patch:1.0.0 coordinates (deployed or installed to local repository, whatever).

Then, modify your POM, the shrinkwrap plugin declaration like this:

```
 <plugin>
  <groupId>shrinkwrap-group</groupId>
  <artifactId>shrinkwrap-plugin</artifactId>
  <version>shrinkwrap-version</version>
  <dependencies>
    <dependency>
      <groupId>org.foo.bar</groupId>
      <artifactId>my-maven-patch</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</plugin>
```

To be frank, am unsure how you use this shrinkwrap thing. Would be helpful if you could show me a "test bed" project to try this out.

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

OK, I'm back - and now finally also got the idea correctly. I will try this out immediately and report back shortly whether this works - stay tuned... ;)

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

Update: Oops - I seem to have just entered dependency hell - it looks like I have to dig through a hierarchy of Red Hat Arquillian component POM imports to see where even the ShrinkWrap Resolver version gets finally determined. :(

Sorry, please do no longer expect an update before the weekend, but I promise I will do my best to finally achieve the above dependency change... :)

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

This might be one - but only from a cursorily glance (no guarantees...).

https://citrusframework.org/samples/arquillian/

Our own setup is slightly more complex (sorry, but I must not share our three-level nested hierarchy without changing all references to my customer), but basically similar...

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Okay, I understand that my proposal is not feasible.

IMHO, the change you will need to implement in shrinkwrap/maven-resolver is really to instead manually construct components, use SISU to inject them. This change is really "internal" to shrinkwrap resolver, none of these should "surface up" to client code, so to say, your test should remain totally unchanged. So, IMHO, this is not like you mention "use cases of the surefire or failsafe plugin where the test driver code additionally creates a Sisu environment". No, this is really internal matter of https://github.com/shrinkwrap/resolver/tree/master/maven/impl-maven (if I guessed the module correctly). The change itself is not quite trivial, but may be done gradually. For example look at breakage:

https://github.com/shrinkwrap/resolver/blob/f564882d785db86460f43cc7512650e3efae3380/maven/impl-maven/src/main/java/org/jboss/shrinkwrap/resolver/impl/maven/internal/SettingsXmlProfileSelector.java#L46-L51

All these classes created in this ctor are actually components, hence, they should be injected. This means a change to ctor of SettingsXmlProfileSelector and have it all parameters declared and added @`{}Inject{`} annotation. For this to work, you'd want to add @`{}Named{`} annotation as now SettingsXmlProfileSelector itself must be managed as well. Finally, you would want to look for all places where instance of SettingsXmlProfileSelector are instantiated and replace that with either inject or play a bit "dirty" and use direct container lookup instead. So, as you see, these changes will have effect to "propagate", so for start, I'd play a bit opportunistic, and fix known breakage (by converting SettingsXmlProfileSelector into a component, fix places where it's created) and stop, and give it a try. Maybe this is it. But maybe not.

For creating Plexus Shim (sisu container plexus compatibility layer) look into resolver demos (there are demos for service locator and "vanilla" guice as well, but I'd not use those, sisu would simplify a lot for you).

https://github.com/apache/maven-resolver/tree/master/maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/sisu

but again, am unsure "how much" or "what" is shrinkwrap resolver using from Maven universe, so maybe this above in resolver is not enough, and you may want actually Plexus Shim (sisu powered container that provides Plexus backward compatible behavior like honoring legacy component descriptors).

I know all this may sound overwhelming, will try to create a PR for you to show what I mean...

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

just found this: https://cwiki.apache.org/confluence/display/MAVEN/Maven+Ecosystem+Cleanup#MavenEcosystemCleanup-Generalguidelines
(but still keen on learning more about our scenario - Arquillian including ShrinkWrap as a "test case execution" being called from the maven-failsafe-plugin...)

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

https://github.com/shrinkwrap/resolver/pull/166

It "works for me" (at least the related Junit tests), so module and module tests do pass, but I cannot build whole project as later (post this module) the build breaks for me. But the idea is there, and also this could "gradually" be done for any other component not used as component (I hope), with maybe some minor refactoring.

So, what we concluded:
* all releases of shrinkwrap resolver breaks with Maven 3.8.5
* to use it with ALL supported maven versions (incl 3.8.5, 3.9.x...) that PR above needs to be ingested by shrinkwrap resolver

Now, does it happen in project, or in a fork, that remains to be answered.

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

Sorry, [Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas) , here I am (have been stuck in meetings...) :)

Thanks a million - my customer definitely owes you a big virtual ice cream :P for even proposing a PR for ShrinkWrap. Great work! :)

And yes, as the content of your PR looks very promising to me, I hereby give **my "all-clear" that you may close this issue as "won't fix"** - and I'll concentrate on looking into forking ShrinkWrap and applying your PR into my fork, and ty to move on from there...

**Thanks again to the whole Maven team for your kind help with this!** (y)

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

.. and also thank you for the pointer to the Maven Users ML - I will definitely use this in case I'll run into follow-up issues with my fork - even though I think it should be simply possible to only selectively fork/"patch" shrinkwrap-resolver-impl-maven and use the rest of the modules as-is.

Please be warned that once again, I will most likely only be able to try this out over this coming weekend... :(

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

The fix materialized in form of a patch for the affected project, that similarly like in MNG-7449 constructed Maven internal bits manually, instead to rely on container as "factory" for components.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Yes, I think as well, that only one module needs this patch, so forking whole project is not needed. Still, be warned, that "best practice" for forks is to clearly distinguish forks from the forked project (as later you will step on that rake and will hit you in face). This means, {**}change the GAV of forked project{**}. Simplest would be – and I hope you do use some repository manager that is able to host Maven artifacts – to deploy complete shrinkwrap project on alternate GAV, and then really just "flip" to patched JAR+POM of this single changed module and use resolver from this alternate/patched GAV from that point on.

Now, I have no idea how easy this would be, given the deep hierarchy of arquillian POMs and heavy use of import scopes for POMs, so "overriding the resolver GAV" may prove nightmare-ish... But let's discuss that once we are there... :) 

You are welcome, and the whole Maven team is happy to help, whenever it can ;)

**Comment by jira-importer** [comment]
**[Andreas Loew](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289351)** commented

BTW: finally found it: here's the link to the full Woody Woodpecker video ("Bunco Busters") on YouTube - https://youtu.be/3fm61avmjn8 :D

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Ftr. https://github.com/shrinkwrap/resolver/pull/170
