### ISSUE TITLE
[MNG-7455] [REGRESSION] IllegalStateException in SessionScope during guice injection in multithreaded build

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#9008]
**[Emond Papegaaij](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=papegaaij)** opened **[MNG-7455](https://issues.apache.org/jira/browse/MNG-7455?redirect=false)** and commented

Since Maven 3.8.5 we are seeing intermittent failures with the stacktrace below. With 3.8.4 we did not have this issue. Looking at the changelog I suspect this regression is caused by MNG-7347.

```java
09:36:53 [mvn-builder-keyhub-manual] [INFO] --- asciidoctor-maven-plugin:2.2.2:process-asciidoc (output-html-nl) @ keyhub-manual ---
09:36:53 [mvn-builder-keyhub-manual] [WARNING] Error injecting: org.asciidoctor.maven.AsciidoctorMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.IllegalStateException
  at org.apache.maven.session.scope.internal.SessionScopeModule.configure(SessionScopeModule.java:64) (via modules: org.eclipse.sisu.wire.WireModule -> org.apache.maven.session.scope.internal.SessionScopeModule)
  while locating org.apache.maven.execution.MavenSession
    for field at org.asciidoctor.maven.AsciidoctorMojo.session(Unknown Source)
  while locating org.asciidoctor.maven.AsciidoctorMojo

1 error
    at com.google.inject.internal.InternalProvisionException.toProvisionException (InternalProvisionException.java:226)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1053)
    at com.google.inject.internal.InjectorImpl.getInstance (InjectorImpl.java:1086)
    at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833)
Caused by: java.lang.IllegalStateException
    at org.apache.maven.session.scope.internal.SessionScope$1.get (SessionScope.java:44)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at org.eclipse.sisu.bean.BeanScheduler$CycleActivator.onProvision (BeanScheduler.java:230)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:120)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.ProviderToInternalFactoryAdapter.get (ProviderToInternalFactoryAdapter.java:40)
    at org.apache.maven.session.scope.internal.SessionScope$CachingProvider.get (SessionScope.java:166)
    at org.apache.maven.session.scope.internal.SessionScope$3.get (SessionScope.java:133)
    at com.google.inject.internal.InternalFactoryToProviderAdapter.get (InternalFactoryToProviderAdapter.java:39)
    at com.google.inject.internal.SingleFieldInjector.inject (SingleFieldInjector.java:52)
    at com.google.inject.internal.MembersInjectorImpl.injectMembers (MembersInjectorImpl.java:147)
    at com.google.inject.internal.ConstructorInjector.provision (ConstructorInjector.java:124)
    at com.google.inject.internal.ConstructorInjector.access$000 (ConstructorInjector.java:32)
    at com.google.inject.internal.ConstructorInjector$1.call (ConstructorInjector.java:98)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ConstructorInjector.construct (ConstructorInjector.java:93)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get (ConstructorBindingImpl.java:306)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at com.google.inject.internal.InjectorImpl.getInstance (InjectorImpl.java:1086)
    at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:121)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)
    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:539)
    at java.util.concurrent.FutureTask.run (FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
    at java.lang.Thread.run (Thread.java:833) 
```

---

**Affects:** 3.8.5

**Attachments:**
- [pom.xml.effective](https://issues.apache.org/jira/secure/attachment/13042280/pom.xml.effective) (_10.86 kB_)

**Issue Links:**
- [MNG-7459](https://issues.apache.org/jira/browse/MNG-7459) Revert MNG-7347 (SessionScoped beans should be singletons for a given session)
 (_**"is fixed by"**_)
- [MNG-7401](https://issues.apache.org/jira/browse/MNG-7401) Make MavenSession#getCurrentProject() using a thread local

- [MNG-7347](https://issues.apache.org/jira/browse/MNG-7347) SessionScoped beans should be singletons for a given session

**Remote Links:**
- [GitHub Pull Request #713
](https://github.com/apache/maven/pull/713)
- [GitHub Pull Request #714
](https://github.com/apache/maven/pull/714)
- [GitHub Pull Request #715
](https://github.com/apache/maven/pull/715)
- [GitHub Pull Request #716
](https://github.com/apache/maven/pull/716)

1 votes, 10 watchers

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[Abel S.Romero](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Abel%20S.Romero), we need to find out whether this is truly a regression or simply a bug trigged in the plugin which was not visible before.

**Comment by jira-importer** [comment]
**[Emond Papegaaij](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=papegaaij)** commented

[Abel S.Romero](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Abel%20S.Romero) A reproducer will be difficult, but I've attached the full configuration of the plugin as generated by help:effective-pom: [^pom.xml.effective]. As you can see, we run quite a few steps in different executions, but we only have 1 module with the asciidoctor plugin. By multi threaded I indeed meant parallel builds. The error is not consistent, it only happens once every 20 or so builds.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

[Abel S.Romero](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Abel%20S.Romero) provider would be needed if you instantiate component outside of session (but touch session ONLY when invoked within one), for example if your component would be a Maven extension. In case of "plain" Mojo, the Mojo itself is instantiated within session, so direct injection should be good. This merely smells like some concurrency issue to me...

**Comment by jira-importer** [comment]
**[Guillaume Nodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnt)** commented

Yes, this clearly looks like a regression caused by  MNG-7347.

**Comment by jira-importer** [comment]
**[Guillaume Nodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnt)** commented

[Emond Papegaaij](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=papegaaij)do you use a maven plugin that is an aggregator in your build ?

**Comment by jira-importer** [comment]
**[Guillaume Nodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnt)** commented

So the problem certainly happens if a thread is mutating the scope while another is injecting a session.  Between the following lines
https://github.com/apache/maven/blob/b4518b5fe416a552a59e5201b4569a9bc0af3153/maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java#L96-L97
the session will be null, and thus, a null session can be injected into a Mojo.

This specific concurrency issue can easily be mitigated by changing the `SessionScope` and providing the session as an argument, so that there will be no gap with a null session, however, this also means that the session that is injected into a mojo may be a random session, and not the one that is actually used to execute the project, which is wrong too.

Given the session are cloned and injected into components, I think MNG-7347 may need to be reverted, as there's no way to ensure the correct sessions are injected into components.  I need to investigate if this will have an impact on the build-cache extension and mvnd...

**Comment by jira-importer** [comment]
**[Emond Papegaaij](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=papegaaij)** commented

[gnodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnodet) what plugins do you mean with an aggregator? These are the plugins we use in this particular module:

```java
maven-enforcer-plugin:3.0.0
maven-source-plugin:3.2.1
io.github.git-commit-id:git-commit-id-maven-plugin:5.0.0
maven-assembly-plugin:3.3.0
maven-dependency-plugin:3.3.0
maven-resources-plugin:3.2.0
org.asciidoctor:asciidoctor-maven-plugin:2.2.2
maven-clean-plugin:3.1.0
maven-install-plugin:2.5.2
maven-deploy-plugin:2.8.2
maven-site-plugin:3.11.0
```

**Comment by jira-importer** [comment]
**[Abel Salgado Romero](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=abel%20s.romero)** commented

Thank you all for the support. As I understand this is not specific to the aasciidoctor-maven-plugin so I'll wait, in the meantime FYI, we inject the session because it's required to use MavenResourcesExecution, but we have been considering removing it for some time in favor of simpler solution to copy resource files https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/335.
So we could provide a fix if necessary.

**Comment by jira-importer** [comment]
**[Christoph Läubrich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laeubi)** commented

From my testing the only reliable wa to get the "right" session is sadly using the LegacySupport class.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

[gnodet](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gnodet), since you reverted the offending commit, should this be marked as fixed also?
