### ISSUE TITLE
[MNG-7481] [ERROR] Internal error: java.lang.ArrayIndexOutOfBoundsException: 20081 -> [Help 1]

### ISSUE THREAD

**Issue by jira-importer** [apache/maven#9125]
**[Simon Matthews](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER289762)** opened **[MNG-7481](https://issues.apache.org/jira/browse/MNG-7481?redirect=false)** and commented

 I get this message when I run "mvn install" on the unaltered source for the Jenkins plugin "analysis model":

https://github.com/jenkinsci/analysis-model

 

$ mvn install
[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.ArrayIndexOutOfBoundsException: 20081 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ArrayIndexOutOfBoundsException: 20081
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:168)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20081
    at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2470)
    at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1257)
    at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
    at org.codehaus.plexus.util.xml.pull.MXParser.nextTag(MXParser.java:1090)
    at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parsePluginExecution(MavenXpp3ReaderEx.java:3541)
    at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parsePlugin(MavenXpp3ReaderEx.java:3336)
    at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseBuildBase(MavenXpp3ReaderEx.java:1398)
    at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseProfile(MavenXpp3ReaderEx.java:3751)
    at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.parseModel(MavenXpp3ReaderEx.java:2809)
    at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:4627)
    at org.apache.maven.model.io.xpp3.MavenXpp3ReaderEx.read(MavenXpp3ReaderEx.java:837)
    at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:118)
    at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:91)
    at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:77)
    at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:456)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:261)
    at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
    at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:343)
    at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
    at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    ... 11 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

 

 

 

---

**Affects:** 3.0.5

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Upgrade to Maven 3.8.5.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Yes please upgrade to most recent versions because 3.0.5 is of 2013-02-23	so roughly 10 years old... also I've checked the referenced project which uses a version like `${revision` which will not work in Maven 3.0.5... also the project contains a [maven-enforcer-rule which says to use at least Maven 3.5.0...](https://github.com/jenkinsci/analysis-model/blob/master/pom.xml#L495)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

His entire OS is 10 years old, so he's consistently stuck in 2012/2013.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Thank you for your feedback.
